import type { Batch2CoreServicePage, Batch2Metro, Batch2StateExpansion } from "./batch2-core-service-types";

const jacksonSources = [
  { label: "City of Jackson residential building and permits", url: "https://jacksonms.gov/residents/residential-building-and-permits/" },
  { label: "City of Jackson planning", url: "https://jacksonms.gov/departments/planning/" },
  { label: "City of Jackson public works", url: "https://jacksonms.gov/departments/public-works/" },
  { label: "Entergy Mississippi", url: "https://www.entergy.com/mississippi" },
  { label: "Mississippi DEQ stormwater", url: "https://www.mdeq.ms.gov/water/sw/" },
  { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  { label: "Mississippi adopted-code administrative rules", url: "https://www.sos.ms.gov/adminsearch" },
  { label: "Mississippi Board of Licensure for Professional Engineers and Surveyors", url: "https://www.pepls.ms.gov/" },
];
const gulfportSources = [
  { label: "City of Gulfport building code services", url: "https://www.gulfport-ms.gov/departments/urban_development/building_code_services/index.php" },
  { label: "City of Gulfport urban development", url: "https://www.gulfport-ms.gov/government/urban_development/index.php" },
  { label: "City of Gulfport public works", url: "https://www.gulfport-ms.gov/government/public_works/index.php" },
  { label: "Mississippi Power", url: "https://www.mississippipower.com/" },
  { label: "Mississippi DEQ coastal program", url: "https://www.mdeq.ms.gov/land/coastal/" },
  { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  { label: "Mississippi adopted-code administrative rules", url: "https://www.sos.ms.gov/adminsearch" },
  { label: "Mississippi Board of Licensure for Professional Engineers and Surveyors", url: "https://www.pepls.ms.gov/" },
];
const hattiesburgSources = [
  { label: "City of Hattiesburg community development", url: "https://www.hattiesburgms.com/departments/community-development/" },
  { label: "City of Hattiesburg planning", url: "https://www.hattiesburgms.com/departments/planning/" },
  { label: "City of Hattiesburg public works", url: "https://www.hattiesburgms.com/departments/public-works/" },
  { label: "Mississippi Power", url: "https://www.mississippipower.com/" },
  { label: "Mississippi DEQ stormwater", url: "https://www.mdeq.ms.gov/water/sw/" },
  { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  { label: "Mississippi adopted-code administrative rules", url: "https://www.sos.ms.gov/adminsearch" },
  { label: "Mississippi Board of Licensure for Professional Engineers and Surveyors", url: "https://www.pepls.ms.gov/" },
];
const southavenSources = [
  { label: "City of Southaven building permits", url: "https://www.southaven.org/100/Building" },
  { label: "City of Southaven planning and development", url: "https://www.southaven.org/213/Planning-Development" },
  { label: "City of Southaven public works", url: "https://www.southaven.org/139/Public-Works" },
  { label: "Northcentral Electric Cooperative", url: "https://www.northcentralelectric.com/" },
  { label: "Mississippi DEQ stormwater", url: "https://www.mdeq.ms.gov/water/sw/" },
  { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  { label: "Mississippi adopted-code administrative rules", url: "https://www.sos.ms.gov/adminsearch" },
  { label: "Mississippi Board of Licensure for Professional Engineers and Surveyors", url: "https://www.pepls.ms.gov/" },
];
const meridianSources = [
  { label: "City of Meridian community development", url: "https://www.meridianms.org/departments/community-development/" },
  { label: "City of Meridian planning", url: "https://www.meridianms.org/departments/planning/" },
  { label: "City of Meridian public works", url: "https://www.meridianms.org/departments/public-works/" },
  { label: "East Mississippi Electric Power Association", url: "https://www.emepa.com/" },
  { label: "Mississippi DEQ stormwater", url: "https://www.mdeq.ms.gov/water/sw/" },
  { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  { label: "Mississippi adopted-code administrative rules", url: "https://www.sos.ms.gov/adminsearch" },
  { label: "Mississippi Board of Licensure for Professional Engineers and Surveyors", url: "https://www.pepls.ms.gov/" },
];

const jacksonServices: Batch2CoreServicePage[] = [
  {
    serviceSlug: "structural-engineering",
    title: "Jackson structural engineering for additions and existing homes",
    description: "Structural design for Jackson additions, ADUs, and alterations using measured framing, flood information, and local review criteria.",
    h1: "Structural Engineering for Jackson, Mississippi",
    kicker: "Jackson load paths, foundations, and existing buildings",
    lede: "A Jackson structural package should start with the actual framing, footing, and grade record. Older renovations, loess and clay soils, Pearl River drainage, and severe weather can make a seemingly small opening an engineered change.",
    permitAuthority: "Jackson residential building and permits is the starting point for city work; Hinds County and nearby municipalities have separate authorities and checklists.",
    codeContext: "Confirm the Jackson-adopted building or residential code, Mississippi amendments, occupancy, wind criteria, flood provisions, and special-inspection requirements before calculations.",
    localConditions: "Jackson’s rolling loess and clay, aging drainage, Pearl River tributaries, heat, thunderstorms, and tornado winds affect foundations and connections.",
    projectTypes: "Residential additions, detached ADUs, porch enclosures, infill, tenant alterations, and small commercial structures.",
    sections: [
      { heading: "Existing Jackson framing is a design input", body: "Probe bearing walls, headers, rafters, joists, crawlspace footings, and prior porch work before sizing an opening. Permit drawings should distinguish observed construction from an assumption about a typical Jackson house." },
      { heading: "Grades and the Pearl River interface", body: "Compare finished floors and foundation drainage with a current survey and FEMA map. A rear ADU may be outside a mapped floodway yet still need a practical drainage and equipment-elevation decision." },
      { heading: "Plan-check corrections close the load path", body: "Answer a Jackson comment with the affected calculation, connection detail, and coordinated architectural or MEP sheet. If demolition reveals different framing, reassess the load path rather than approving an undocumented field fix." },
    ],
    permitSteps: [
      "Confirm the Jackson address, occupancy, adopted code, wind and flood criteria, and whether city or county review applies.",
      "Document framing, foundations, soil or fill, roof loads, moisture, demolition limits, and survey grades before final member design.",
      "Coordinate headers, bracing, anchors, fire separations, MEP penetrations, finished floors, and special-inspection notes.",
      "Log every plan-check correction by sheet and calculation, then issue controlled revisions after the responsible engineer reviews field changes.",
    ],
    faqs: [
      { question: "Does a Jackson ADU always require structural engineering?", answer: "A new foundation, bearing-wall change, roof alteration, uncertain footing, or unusual connection may require engineering; the Jackson reviewer and responsible engineer determine the submission scope." },
      { question: "Why does flood information matter to a structural addition?", answer: "Flood elevation and drainage can affect finished floors, foundation details, materials, equipment placement, and allowable site work even when the addition is not in a mapped floodway." },
      { question: "How should Jackson structural comments be answered?", answer: "Use a numbered response tied to revised sheets or calculations and revisit the design when openings expose framing that differs from the measured record." },
    ],
    sources: jacksonSources,
  },
  {
    serviceSlug: "mep-engineering",
    title: "Jackson MEP engineering for humid renovations and additions",
    description: "Jackson mechanical, electrical, and plumbing coordination tied to Entergy service, municipal utilities, ventilation, and storm conditions.",
    h1: "MEP Engineering for Jackson, Mississippi",
    kicker: "Jackson service capacity and hot-humid building systems",
    lede: "Jackson MEP design begins with service capacity and hot-humid operation rather than a square-foot allowance. An addition or ADU can expose limits in the existing panel, sewer connection, ventilation, and condensate route.",
    permitAuthority: "Jackson building intake can involve fire, public works, health, floodplain, and utility reviews; verify the route for the property address.",
    codeContext: "Identify the Jackson-adopted mechanical, plumbing, fuel-gas, electrical, fire, and energy provisions and the edition used by each reviewer.",
    localConditions: "Long cooling seasons, high latent loads, severe storms, short freezes, and Pearl River drainage influence equipment, controls, and service routing.",
    projectTypes: "Medical interiors, restaurants, occupied renovations, multifamily work, residential additions, and small commercial buildings.",
    sections: [
      { heading: "Jackson capacity must be documented", body: "Record Entergy service information, meter configuration, domestic-water pressure, sewer connection, and available fire-flow data before fixing schedules. An existing residential panel or pipe is not proof of spare capacity." },
      { heading: "Humidity and outage decisions", body: "Ventilation, filtration, condensate, corrosion protection, and restart controls should reflect Jackson’s humid air and storm outages. Equipment near a flood-prone grade needs a coordinated elevation and access detail." },
      { heading: "One response for linked system comments", body: "Risers, one-lines, equipment clearances, penetrations, controls, and load calculations should answer building, fire, and utility comments together. A substitution that changes load or ventilation requires a cross-discipline check." },
    ],
    permitSteps: [
      "Identify Jackson building, fire, health, floodplain, right-of-way, and utility handoffs before selecting the MEP review path.",
      "Obtain address-specific Entergy, water, sewer, and fire-flow information and field-trace existing service equipment.",
      "Coordinate feeders, ventilation, condensate, plumbing, flood-sensitive equipment, ADU tie-ins, and shutdowns with architecture and structure.",
      "Return numbered MEP responses through the AHJ with revised schedules, risers, calculations, and utility correspondence.",
    ],
    faqs: [
      { question: "What changes MEP design for a Jackson addition?", answer: "New electrical load, sewer demand, ventilation, service water, flood elevation, and the condition of the existing panel or meter can all change the design." },
      { question: "How does Jackson humidity affect an HVAC permit set?", answer: "Latent load, outdoor air, condensate routing, controls, and equipment placement should be documented instead of copied from a dry-climate design." },
      { question: "What closes a Jackson MEP plan-check comment?", answer: "Identify the comment, revise its drawing or calculation, check related disciplines, and submit a dated response through the Jackson review process." },
    ],
    sources: jacksonSources,
  },
  {
    serviceSlug: "civil-engineering",
    title: "Jackson civil engineering for drainage and infill sites",
    description: "Jackson grading, drainage, utilities, and access design that connects surveyed lots to Pearl River and municipal systems.",
    h1: "Civil Engineering for Jackson, Mississippi",
    kicker: "Jackson grading, drainage, and utility connections",
    lede: "Jackson civil work must connect surveyed grades to the receiving drainage system. Urban inlets, clay and loess, Pearl River influence, and neighborhood runoff can turn an addition or ADU into a site-design decision.",
    permitAuthority: "Jackson planning, public works, floodplain, stormwater, and utility reviewers may be separate from building intake; confirm the parcel’s review sequence.",
    codeContext: "Use current Jackson zoning, drainage, right-of-way, floodplain, and Mississippi DEQ stormwater requirements for the proposed disturbance and watershed.",
    localConditions: "Clay and loess, intense rain, aging inlets, Pearl River tributaries, established lots, and utility easements affect Jackson grading.",
    projectTypes: "Infill lots, commercial parking, detached ADUs, room additions, redevelopment, and small public-frontage improvements.",
    sections: [
      { heading: "A Jackson outlet needs evidence", body: "Survey inlets, ditches, easements, downstream grades, and floodway status before selecting detention or an outfall. A nearby ditch is not automatically an approved receiving system." },
      { heading: "Small additions still alter the site", body: "Keep an ADU or room addition’s roof water away from crawlspaces, alleys, and adjacent lots while preserving accessible routes, fire access, and utility maintenance corridors." },
      { heading: "Frontage corrections need revised profiles", body: "Driveways, curb cuts, sidewalks, utility locates, and erosion controls should be reconciled with Jackson right-of-way requirements. Answer grade comments with updated profiles and volumes, not only narrative." },
    ],
    permitSteps: [
      "Confirm Jackson zoning, flood panel, watershed, disturbance boundary, frontage, and utility service area for the parcel.",
      "Prepare a current survey and obtain outfall, utility, fire-access, easement, and right-of-way information.",
      "Coordinate grading, finished floors, detention or infiltration, ADU access, erosion controls, and profiles with the building set.",
      "Log Jackson civil comments and submit revised calculations, maintenance notes, profiles, and sheets before closeout.",
    ],
    faqs: [
      { question: "Can a Jackson detached ADU avoid civil review?", answer: "A detached foundation, driveway, sewer tie-in, flood exposure, or added impervious area can trigger civil or utility review even when the building is small." },
      { question: "What controls a Jackson stormwater outlet?", answer: "The local drainage system, downstream capacity, floodplain, easements, Mississippi DEQ conditions, and maintenance responsibility control the outlet." },
      { question: "Why can Jackson civil corrections reach structural sheets?", answer: "A grade or finished-floor change can affect foundation drainage, retaining, access, utility depth, and neighboring runoff, so disciplines must be revised together." },
    ],
    sources: jacksonSources,
  },
  {
    serviceSlug: "energy-compliance",
    title: "Jackson energy compliance for additions and renovations",
    description: "Jackson energy documentation for hot-humid envelopes, HVAC, lighting, and the applicable local alteration path.",
    h1: "Energy Compliance for Jackson, Mississippi",
    kicker: "Jackson envelope, HVAC, and lighting documentation",
    lede: "Jackson energy compliance should match the submitted envelope and cooling design. Humidity, air sealing, storm exposure, and an existing home’s connected systems matter when an addition or ADU is added.",
    permitAuthority: "Ask Jackson building officials which residential or commercial energy method, edition, forms, and alteration provisions apply to the address.",
    codeContext: "The local AHJ determines the adopted energy provisions and Mississippi amendments; identify the method and edition instead of implying one statewide workflow.",
    localConditions: "Hot-humid loads, solar gain, infiltration, heavy rain, outages, and corrosion-sensitive equipment inform Jackson envelope and HVAC choices.",
    projectTypes: "Tenant improvements, small commercial shells, residential additions, ADUs, schools, and medical spaces.",
    sections: [
      { heading: "Use Jackson’s actual compliance path", body: "Occupancy, conditioned area, alteration category, insulation, glazing, lighting, and HVAC schedules should drive the forms. A generic worksheet can conflict with the building set." },
      { heading: "Continuity matters in a humid envelope", body: "Air sealing, moisture decisions, ventilation, condensate, roof transitions, and equipment controls deserve coordinated details at the addition-to-existing-building interface." },
      { heading: "Corrections need a field record", body: "Keep model inputs, forms, equipment substitutions, and revised drawings versioned. A corrected efficiency value should trigger a review of loads, service, controls, and installation notes." },
    ],
    permitSteps: [
      "Confirm Jackson’s adopted energy edition, compliance method, forms, and addition or alteration trigger with the AHJ.",
      "Collect envelope, glazing, lighting, HVAC, ventilation, service-water, schedule, and control inputs from the coordinated design.",
      "Reconcile the compliance record with openings, MEP equipment, fire separations, ADU boundaries, and moisture details.",
      "Answer each Jackson energy comment by input and sheet, retaining final field-verification responsibilities and substitutions.",
    ],
    faqs: [
      { question: "Does a Jackson ADU automatically use new-construction energy forms?", answer: "The local method, conditioned area, alteration scope, and connected systems determine the documentation; Jackson should confirm the path." },
      { question: "Does compliance predict a Jackson utility bill?", answer: "No. It tests documented weather, schedules, envelope, equipment, and controls; rates, occupants, maintenance, and construction quality affect actual use." },
      { question: "How should Jackson energy corrections be documented?", answer: "Tie each comment to a form, model input, drawing, and responsible field item, then coordinate any HVAC or envelope change with the permit set." },
    ],
    sources: jacksonSources,
  },
  {
    serviceSlug: "pe-stamped-drawings",
    title: "Jackson PE-stamped drawings for defined engineering scopes",
    description: "Jackson permit documents with verified site evidence, discipline boundaries, and controlled professional revisions.",
    h1: "PE-Stamped Drawings for Jackson, Mississippi",
    kicker: "Jackson responsible-charge and permit coordination",
    lede: "A Jackson sealed discipline package should show what was observed, which code path applies, and where city, utility, floodplain, and environmental approvals remain separate.",
    permitAuthority: "Jackson building and development offices decide the permit route; the Mississippi Board of Licensure for Professional Engineers and Surveyors governs professional licensure, while a responsible PE defines only the engineering discipline and scope accepted for review. Neither replaces local approval.",
    codeContext: "Identify adopted local codes, wind and flood criteria, existing-condition limits, special inspections, and boundaries with architecture, survey, and geotechnical work.",
    localConditions: "Loess, aging infrastructure, Pearl River flooding, severe weather, and utility capacity require address-specific evidence before sealing.",
    projectTypes: "Civil site plans, structural alterations, MEP packages, additions, ADUs where engineering is required, and public-facing improvements.",
    sections: [
      { heading: "Evidence before a Jackson seal", body: "Survey, measured framing, geotechnical information, utility letters, equipment data, and flood records give a PE a basis for judgment; a seal does not fill missing facts." },
      { heading: "Separate Jackson agency handoffs", body: "Planning, fire, public works, stormwater, floodplain, utilities, and Mississippi DEQ may receive different portions of a set. The index should make those boundaries visible." },
      { heading: "Revisions remain accountable", body: "A demolition discovery, substitution, RFI, or changed drainage condition can alter accepted scope. The responsible PE should review the change and control replacement sheets." },
    ],
    permitSteps: [
      "Map Jackson building, planning, fire, utility, flood, stormwater, and environmental handoffs for the address.",
      "Assemble survey, existing-condition, geotechnical, architectural, equipment, and utility records before accepting engineering scope.",
      "Submit authenticated discipline sheets through Jackson’s stated route and label specialty or contractor documents separately.",
      "Track comments, RFIs, substitutions, inspections, and field changes; issue revisions only after responsible-professional review.",
    ],
    faqs: [
      { question: "Does a PE seal replace Jackson approval?", answer: "No. It communicates responsibility for a defined engineering scope; Jackson and separate utility, fire, floodplain, stormwater, and environmental authorities decide their approvals." },
      { question: "Can a Jackson ADU be sealed from photos alone?", answer: "The PE decides whether evidence is adequate. Existing framing, foundations, soil, flood, service, and connections may require measurements or other investigation." },
      { question: "What happens after a Jackson sealed-set correction?", answer: "The PE reviews the affected design, coordinates related sheets, submits a numbered response, and records whether the accepted scope changed." },
    ],
    sources: jacksonSources,
  },
];

const gulfportServices: Batch2CoreServicePage[] = [
  {
    serviceSlug: "structural-engineering",
    title: "Gulfport structural engineering for coastal additions",
    description: "Coastal structural design for Gulfport homes and commercial alterations using wind, surge, groundwater, and corrosion evidence.",
    h1: "Structural Engineering for Gulfport, Mississippi",
    kicker: "Gulfport coastal load paths and foundations",
    lede: "Gulfport structural work must account for coastal wind, surge, sandy or filled ground, high groundwater, and salt exposure. A measured existing condition is more useful than a stock coastal detail.",
    permitAuthority: "Gulfport Building Code Services and Urban Development start the city review; Harrison County, floodplain, coastal, and utility reviews may be separate.",
    codeContext: "Confirm Gulfport’s adopted building or residential code, wind and flood criteria, coastal requirements, occupancy, and special-inspection notes before design.",
    localConditions: "Low coastal grades, sandy fill, high groundwater, hurricane wind and surge, salt air, and heavy rain shape Gulfport foundations and connections.",
    projectTypes: "Coastal additions, detached ADUs, lodging, restaurants, tenant improvements, and small commercial redevelopment.",
    sections: [
      { heading: "Gulfport buildings need measured connections", body: "Verify masonry, wood framing, roof-to-wall ties, crawlspace supports, corrosion, and prior enclosure work before sizing an opening or addition. Existing coastal damage is a condition to document, not a generic allowance." },
      { heading: "Surge, groundwater, and finished floors", body: "Compare the survey, FEMA flood information, and local requirements when selecting foundation elevation, flood-resistant materials, anchors, and equipment supports. High groundwater also changes excavation and drainage assumptions." },
      { heading: "Coastal corrections must be specific", body: "Return Gulfport comments with revised wind details, calculations, flood notes, and a coordinated architectural sheet. Do not close an exposed connection or field condition with a generic response." },
    ],
    permitSteps: [
      "Confirm Gulfport jurisdiction, occupancy, adopted code, flood zone, wind criteria, coastal review, and special inspections.",
      "Obtain survey, soil or fill information, flood data, framing exposures, corrosion observations, and demolition limits.",
      "Coordinate anchors, shear walls, finished floors, flood-resistant materials, MEP penetrations, and fire separations.",
      "Answer each Gulfport correction by sheet and calculation, with the responsible engineer reviewing changed coastal assumptions.",
    ],
    faqs: [
      { question: "Does a Gulfport ADU need structural review?", answer: "A new foundation, wind connection, flood elevation, altered bearing line, or uncertain existing support can require engineering; the AHJ and responsible engineer determine scope." },
      { question: "What does coastal exposure change structurally?", answer: "Surge, wind-driven rain, salt air, groundwater, and corrosion can change foundations, anchors, materials, equipment supports, and drainage decisions." },
      { question: "How are Gulfport structural comments closed?", answer: "Use a numbered response tied to each revised sheet or calculation and retain the city, floodplain, and other agency records." },
    ],
    sources: gulfportSources,
  },
  {
    serviceSlug: "mep-engineering",
    title: "Gulfport MEP engineering for coastal buildings",
    description: "Gulfport MEP coordination for Mississippi Power, municipal services, latent cooling, corrosion, surge, and occupied renovations.",
    h1: "MEP Engineering for Gulfport, Mississippi",
    kicker: "Gulfport coastal HVAC, utility, and equipment coordination",
    lede: "Gulfport MEP design joins Mississippi Power and municipal service information to latent cooling, salt air, wind-driven rain, and flood-sensitive equipment placement.",
    permitAuthority: "Gulfport building review may be joined by fire, public works, floodplain, coastal, health, and utility authorities; verify each handoff for the address.",
    codeContext: "Identify Gulfport’s adopted mechanical, plumbing, electrical, fire, energy, and flood provisions and the edition used by the reviewing authority.",
    localConditions: "Humid cooling, high groundwater, salt air, hurricanes, surge, heavy rain, and outage recovery affect equipment and controls.",
    projectTypes: "Restaurants, lodging, medical interiors, coastal tenant work, multifamily additions, and detached ADUs.",
    sections: [
      { heading: "Service facts before Gulfport schedules", body: "Obtain Mississippi Power service information, water pressure, sewer connection, fire-flow data, and existing panel records before selecting equipment. Coastal availability is not the same as project capacity." },
      { heading: "Humidity, salt, and surge", body: "Latent load, filtration, corrosion protection, condensate, intake placement, disconnect elevation, and restart sequences should be explicit where Gulfport storms can interrupt service." },
      { heading: "One coordinated plan-check record", body: "A change to a panel, riser, ventilation rate, or flood-sensitive unit can affect energy, fire separation, structure, and accessibility. Revise linked Gulfport sheets together." },
    ],
    permitSteps: [
      "Confirm Gulfport building, fire, health, floodplain, coastal, right-of-way, and utility review handoffs.",
      "Request Mississippi Power, water, sewer, and fire-flow information and field-trace existing service equipment.",
      "Coordinate feeders, risers, ventilation, condensate, corrosion protection, equipment elevation, and ADU tie-ins.",
      "Return numbered Gulfport responses with revised calculations, schedules, risers, controls, and utility correspondence.",
    ],
    faqs: [
      { question: "What changes MEP design in Gulfport?", answer: "Service capacity, latent load, salt air, surge, ventilation, flood elevation, and equipment access can all change the design." },
      { question: "Why coordinate flood information with Gulfport MEP?", answer: "Flood elevation and surge can affect equipment placement, disconnects, condensate, service routing, materials, and maintenance access." },
      { question: "What makes a useful Gulfport MEP response?", answer: "Revise the affected schedule or calculation, cross-check related sheets, and answer the city or agency comment in writing." },
    ],
    sources: gulfportSources,
  },
  {
    serviceSlug: "civil-engineering",
    title: "Gulfport civil engineering for coastal drainage and access",
    description: "Gulfport civil plans for low grades, sandy soils, canals, outfalls, utilities, flood elevation, and frontage work.",
    h1: "Civil Engineering for Gulfport, Mississippi",
    kicker: "Gulfport grading, outfalls, and coastal site interfaces",
    lede: "A Gulfport civil package must connect the building pad to a surveyed receiving system. Low coastal grades, canals, groundwater, storm surge, and public frontage make a standard detention sketch unreliable.",
    permitAuthority: "Gulfport Urban Development and Public Works may review separately from Building Code Services; Harrison County and coastal or flood authorities can have additional roles.",
    codeContext: "Confirm Gulfport zoning, drainage, right-of-way, floodplain, coastal, and Mississippi DEQ requirements for the disturbance and receiving watershed.",
    localConditions: "Low grades, sandy soils, canals, high groundwater, hurricane rainfall, surge, salt exposure, and coastal outfalls shape Gulfport civil work.",
    projectTypes: "Lodging sites, restaurant parking, residential additions, detached ADUs, redevelopment, and utility or frontage improvements.",
    sections: [
      { heading: "Survey the Gulfport receiving system", body: "Locate inlets, ditches, canals, easements, tide-sensitive outfalls, utility crossings, and downstream grades before choosing detention or discharge. The nearest pipe is not automatically an approved outlet." },
      { heading: "Additions and ADUs at low grades", body: "A new roof or driveway must direct runoff away from crawlspaces and neighbors while preserving flood-safe access, sewer service, finished-floor decisions, and equipment maintenance." },
      { heading: "Frontage and coastal corrections", body: "Curb cuts, drainage easements, erosion controls, utility crossings, and public access belong in the Gulfport correction record. Respond to grade comments with revised profiles, volumes, and maintenance notes." },
    ],
    permitSteps: [
      "Confirm Gulfport zoning, flood zone, coastal status, disturbance area, frontage, watershed, and review agencies.",
      "Obtain survey control, outfall ownership, utility locates, groundwater or soil information, finished-floor data, and access requirements.",
      "Coordinate grading, detention or infiltration, flood-sensitive elevations, ADU access, erosion controls, and utility profiles.",
      "Submit a numbered response to each Gulfport civil comment with revised calculations, profiles, details, and maintenance responsibilities.",
    ],
    faqs: [
      { question: "Can a Gulfport ADU skip civil review?", answer: "A detached foundation, driveway, sewer tie, flood exposure, or added impervious area can trigger site review even on a residential lot." },
      { question: "What controls a Gulfport outfall?", answer: "Local drainage, tide or surge conditions, floodplain, easements, Mississippi DEQ requirements, ownership, and maintenance responsibility control it." },
      { question: "Why do Gulfport grade comments affect foundations?", answer: "A grade or finished-floor change can alter crawlspace drainage, flood exposure, access, utility depth, and erosion at neighboring property." },
    ],
    sources: gulfportSources,
  },
  {
    serviceSlug: "energy-compliance",
    title: "Gulfport energy compliance for humid coastal envelopes",
    description: "Gulfport energy documentation coordinated with coastal envelope details, HVAC, lighting, glazing, and the local alteration method.",
    h1: "Energy Compliance for Gulfport, Mississippi",
    kicker: "Gulfport humidity, envelope, and cooling documentation",
    lede: "Gulfport energy documentation should match the actual humid-coastal envelope and cooling design. Air sealing, wind-driven rain, glazing, corrosion, and flood-sensitive equipment cannot be separated from the permit set.",
    permitAuthority: "Ask Gulfport Building Code Services which energy edition, method, forms, and residential or commercial alteration provisions apply.",
    codeContext: "The local AHJ determines the adopted energy provisions and Mississippi amendments; state administrative rules do not replace Gulfport’s project-specific direction.",
    localConditions: "High latent loads, solar gain, salt air, hurricane exposure, wind-driven rain, outages, and high groundwater influence Gulfport assemblies and systems.",
    projectTypes: "Coastal additions, ADUs, lodging, restaurants, tenant improvements, schools, and small commercial shells.",
    sections: [
      { heading: "Classify the Gulfport alteration", body: "Conditioned area, occupancy, existing envelope, glazing, lighting, HVAC, and the alteration category should drive the selected method. A generic worksheet can conflict with Gulfport drawings." },
      { heading: "Envelope and coastal moisture", body: "Air sealing, roof and wall transitions, glazing, moisture control, ventilation, condensate, and corrosion protection need details that remain compatible with wind-driven rain and flood decisions." },
      { heading: "Keep corrections buildable", body: "Version model inputs, forms, equipment substitutions, and field checks together. A revised efficiency or window value should trigger a review of loads, service, controls, and envelope details." },
    ],
    permitSteps: [
      "Confirm Gulfport’s energy edition, method, forms, climate inputs, and addition or alteration trigger with the AHJ.",
      "Collect verified assemblies, windows, shading, HVAC, ventilation, lighting, service-water, and controls information.",
      "Cross-check compliance inputs against coastal details, flood-resistant equipment placement, fire separations, and MEP schedules.",
      "Answer each Gulfport energy comment with its form, input, cited provision, revised drawing, and field-verification responsibility.",
    ],
    faqs: [
      { question: "Does a Gulfport addition use a new energy path?", answer: "Gulfport’s reviewer classifies the work using the conditioned area, existing envelope, alteration category, and connected equipment; those facts determine which documentation belongs in the coastal permit set." },
      { question: "Does energy compliance guarantee lower coastal bills?", answer: "No. Actual use depends on rates, occupants, maintenance, controls, construction quality, weather, and operating schedules." },
      { question: "How should Gulfport energy corrections be answered?", answer: "Tie each comment to its form, model input, drawing, cited provision, and field responsibility, then coordinate linked HVAC or envelope changes." },
    ],
    sources: gulfportSources,
  },
  {
    serviceSlug: "pe-stamped-drawings",
    title: "Gulfport PE-stamped drawings for coastal permit scopes",
    description: "Gulfport sealed engineering documents with flood, wind, survey, utility, coastal, and correction boundaries clearly identified.",
    h1: "PE-Stamped Drawings for Gulfport, Mississippi",
    kicker: "Gulfport engineering responsibility and coastal review",
    lede: "A Gulfport sealed package should define the discipline, evidence, wind and flood criteria, and separate city, utility, coastal, and environmental handoffs without implying approval.",
    permitAuthority: "Gulfport Building Code Services and Urban Development determine the city route; the Mississippi Board of Licensure for Professional Engineers and Surveyors governs professional licensure, while a Mississippi PE is responsible only for the defined engineering scope. Neither replaces local approval.",
    codeContext: "Identify adopted local codes, coastal and flood criteria, existing-condition limits, special inspections, and boundaries with survey, geotechnical, architecture, and contractors.",
    localConditions: "Sandy or filled ground, surge, groundwater, salt air, hurricane wind, coastal drainage, and utility constraints require address-specific evidence.",
    projectTypes: "Structural alterations, civil site plans, MEP packages, additions, ADUs where required, lodging, and public-facing improvements.",
    sections: [
      { heading: "Gulfport evidence before sealing", body: "Survey, flood information, geotechnical recommendations, measured construction, utility letters, equipment data, and corrosion observations establish a basis for professional judgment." },
      { heading: "Separate coastal agency roles", body: "Building, planning, fire, public works, floodplain, stormwater, utilities, MDEQ, and coastal authorities may each receive different sheets. The index should show those boundaries." },
      { heading: "Controlled revisions after review", body: "A changed flood elevation, substitution, RFI, or field discovery can alter accepted scope. The responsible PE should evaluate it and control replacement sheets and responses." },
    ],
    permitSteps: [
      "Map Gulfport building, planning, fire, utility, flood, stormwater, and coastal or environmental handoffs.",
      "Assemble survey, flood, soil, existing-condition, architectural, equipment, utility, and calculation records before accepting scope.",
      "Have the responsible Mississippi PE review the complete coordinated discipline package before submission.",
      "Track comments, substitutions, RFIs, inspections, and field changes; issue revised sealed sheets only for reviewed scope changes.",
    ],
    faqs: [
      { question: "Does a Gulfport PE seal replace a permit?", answer: "No. The seal identifies responsibility for a defined engineering scope; city, coastal, utility, fire, floodplain, and environmental authorities retain their approvals." },
      { question: "Can coastal existing conditions be inferred from photos?", answer: "The PE decides whether photos are adequate; survey, measurements, openings, flood records, or other evidence may be needed." },
      { question: "What happens after a Gulfport PE correction?", answer: "The PE reviews the changed design, coordinates affected sheets, and issues a controlled revision and numbered response when the scope requires it." },
    ],
    sources: gulfportSources,
  },
];

const hattiesburgServices: Batch2CoreServicePage[] = [
  {
    serviceSlug: "structural-engineering",
    title: "Hattiesburg structural engineering for Piney Woods sites",
    description: "Structural design for Hattiesburg additions, ADUs, and commercial work using measured framing, variable soils, slopes, and storm criteria.",
    h1: "Structural Engineering for Hattiesburg, Mississippi",
    kicker: "Hattiesburg foundations, framing, and existing conditions",
    lede: "Hattiesburg structural design changes between Piney Woods slopes, sandy or clay soils, and older residential or commercial construction. Field evidence should precede a new opening, addition, or detached ADU.",
    permitAuthority: "Hattiesburg Community Development and Planning are city starting points; Forrest County and nearby jurisdictions have separate review paths.",
    codeContext: "Confirm Hattiesburg’s adopted building or residential code, Mississippi amendments, wind criteria, occupancy, flood provisions, and special inspections.",
    localConditions: "Piney Woods slopes, sand and clay, creek floodplains, intense rain, heat, and tornado exposure affect Hattiesburg foundations and connections.",
    projectTypes: "University-area infill, medical work, residential additions, ADUs, retail, and light industrial alterations.",
    sections: [
      { heading: "Hattiesburg framing needs a field record", body: "Measure rafters, joists, footings, crawlspaces, masonry, and prior porch alterations before sizing an opening. A nearby house is not evidence of this building’s bearing layout." },
      { heading: "Slopes and creeks affect foundations", body: "Relate footing elevations, retaining, surface drainage, and finished floors to the survey and flood information. Piney Woods sand can drain quickly while clay or fill changes settlement and runoff." },
      { heading: "Corrections should follow discoveries", body: "Answer Hattiesburg comments with revised calculations and connection details. If demolition exposes rot, fill, or framing unlike the permit record, document the decision before construction continues." },
    ],
    permitSteps: [
      "Confirm the Hattiesburg address, occupancy, adopted code, wind and flood criteria, and city or county authority.",
      "Record framing, footings, soil or fill, retaining geometry, roof loads, moisture, and demolition limits.",
      "Coordinate load paths, anchors, bracing, foundation drainage, MEP penetrations, access, and fire separations.",
      "Submit a numbered Hattiesburg correction response and obtain responsible-engineer review for field-dependent revisions.",
    ],
    faqs: [
      { question: "Does a Hattiesburg addition or ADU need structural engineering?", answer: "New foundations, bearing changes, retaining, uncertain existing support, or unusual wind connections can require engineering; the AHJ and responsible professional determine scope." },
      { question: "Why check a Hattiesburg creek or floodplain for a small project?", answer: "Flood elevation and drainage can affect foundation elevation, finished floors, retaining, access, and materials even when the building footprint is modest." },
      { question: "What makes a useful Hattiesburg structural response?", answer: "Tie each comment to a calculation or revised detail and state how an unexpected existing condition was investigated and coordinated." },
    ],
    sources: hattiesburgSources,
  },
  {
    serviceSlug: "mep-engineering",
    title: "Hattiesburg MEP engineering for humid occupied buildings",
    description: "Hattiesburg MEP coordination for Mississippi Power, municipal services, ventilation, medical and university uses, and storm resilience.",
    h1: "MEP Engineering for Hattiesburg, Mississippi",
    kicker: "Hattiesburg HVAC, utility, and occupied-building coordination",
    lede: "Hattiesburg MEP design should reconcile Mississippi Power, municipal water and sewer, humid cooling, and the actual occupancy before equipment schedules are fixed.",
    permitAuthority: "Hattiesburg Community Development coordinates the city permit route; fire, health, public works, utility, and county reviews may be separate.",
    codeContext: "Identify the Hattiesburg-adopted mechanical, plumbing, electrical, fuel-gas, fire, and energy requirements and applicable edition.",
    localConditions: "Hot-humid operation, heavy rain, short freezes, storm outages, creek drainage, and university or medical schedules affect systems.",
    projectTypes: "Medical suites, university-area interiors, restaurants, occupied renovations, additions, and ADUs.",
    sections: [
      { heading: "Verify Hattiesburg service capacity", body: "Document Mississippi Power service, panel capacity, water pressure, sewer point, ventilation, and fire-flow information before final schedules. Existing equipment nameplates do not establish available capacity." },
      { heading: "Humidity and occupancy are linked", body: "Outdoor air, latent load, filtration, condensate, controls, and after-hours operation should reflect Hattiesburg’s climate and the building’s use rather than a generic office assumption." },
      { heading: "Keep the occupied-building response coordinated", body: "Risers, shutdown phases, equipment clearances, fire penetrations, and controls should answer building, fire, and utility comments together. A changed load can affect energy and service documents." },
    ],
    permitSteps: [
      "Confirm Hattiesburg building, fire, health, public works, floodplain, and utility handoffs for the project.",
      "Request Mississippi Power, water, sewer, and fire-flow information and field-trace the occupied building’s systems.",
      "Coordinate equipment, feeders, ventilation, condensate, controls, shutdowns, ADU tie-ins, and accessible maintenance.",
      "Answer each Hattiesburg MEP comment with revised schedules, risers, calculations, and a numbered response.",
    ],
    faqs: [
      { question: "What changes MEP design for a Hattiesburg addition?", answer: "Added electrical and sewer loads, humid-air ventilation, panel condition, fire separation, flood or drainage exposure, and occupancy schedules can all change the design." },
      { question: "Why do medical or university uses need different Hattiesburg documentation?", answer: "Occupancy, ventilation, controls, emergency operation, and shutdown requirements can differ, so the permit set should reflect the actual use." },
      { question: "How should Hattiesburg MEP corrections be closed?", answer: "Revise the affected riser, schedule, calculation, or detail, cross-check linked disciplines, and submit a dated response through the AHJ." },
    ],
    sources: hattiesburgSources,
  },
  {
    serviceSlug: "civil-engineering",
    title: "Hattiesburg civil engineering for slopes, creeks, and access",
    description: "Hattiesburg civil design for rolling grades, creek drainage, utilities, erosion control, access, and additions.",
    h1: "Civil Engineering for Hattiesburg, Mississippi",
    kicker: "Hattiesburg grading, drainage, and utility profiles",
    lede: "Hattiesburg civil plans connect rolling grades and creek floodplains to safe access, utilities, outfalls, and erosion controls instead of assuming a level Piney Woods lot.",
    permitAuthority: "Hattiesburg Planning and Community Development may share review with Public Works, floodplain, fire, utility, and Forrest County authorities.",
    codeContext: "Confirm Hattiesburg zoning, drainage, right-of-way, floodplain, erosion, and Mississippi DEQ stormwater requirements for the disturbance.",
    localConditions: "Rolling sandy and clay soils, creek floodplains, intense rainfall, wooded lots, steep drives, and established drainage affect site design.",
    projectTypes: "Residential additions, ADUs, university infill, medical sites, retail parking, and light industrial redevelopment.",
    sections: [
      { heading: "Survey the Hattiesburg receiving system", body: "Locate creeks, ditches, inlets, easements, utility crossings, downstream grades, and flood limits before selecting an outlet. A roadside ditch is not automatically approved or adequately sized." },
      { heading: "Additions must preserve access and drainage", body: "A room addition or ADU can redirect roof water, consume a fire route, cross a utility, or increase erosion. Show finished floors, accessible paths, drive grades, and maintenance access together." },
      { heading: "Profiles answer Hattiesburg corrections", body: "When a reviewer changes the grade or outlet, revise contours, profiles, volumes, erosion details, and maintenance notes. Narrative alone cannot establish a workable receiving system." },
    ],
    permitSteps: [
      "Confirm Hattiesburg zoning, flood status, watershed, disturbance boundary, frontage, fire access, and review agencies.",
      "Prepare a current survey and obtain utility, outfall, soil, flood, easement, and right-of-way information.",
      "Coordinate grading, finished floors, erosion control, drainage, ADU access, utilities, and profiles with the building set.",
      "Return a numbered response to every Hattiesburg civil correction with revised calculations, drawings, and maintenance responsibilities.",
    ],
    faqs: [
      { question: "Can a Hattiesburg ADU avoid civil review?", answer: "A new driveway, sewer tie, impervious area, drainage path, flood exposure, or steep access condition can trigger civil or utility review." },
      { question: "What controls a Hattiesburg stormwater outlet?", answer: "The receiving creek or ditch, downstream capacity, floodplain, easements, soil, Mississippi DEQ conditions, and maintenance responsibility control it." },
      { question: "Why can a Hattiesburg grade correction change the building?", answer: "Finished-floor, access, foundation drainage, retaining, utility depth, and erosion decisions are tied to the revised grade." },
    ],
    sources: hattiesburgSources,
  },
  {
    serviceSlug: "energy-compliance",
    title: "Hattiesburg energy compliance for humid alterations",
    description: "Hattiesburg energy documentation for envelope, glazing, cooling, lighting, and the adopted residential or commercial path.",
    h1: "Energy Compliance for Hattiesburg, Mississippi",
    kicker: "Hattiesburg envelope and cooling records",
    lede: "Hattiesburg energy documents should reflect humid cooling, air sealing, lighting, and the actual alteration path selected by the local AHJ rather than a generic Memphis or Gulf Coast worksheet.",
    permitAuthority: "Ask Hattiesburg Community Development which energy edition, method, forms, and addition or alteration provisions apply.",
    codeContext: "Identify the adopted Hattiesburg energy provisions and Mississippi amendments, along with the method and edition used for this permit.",
    localConditions: "High cooling and latent loads, solar gain, heavy rain, wooded shading, storm outages, and short freezes inform Hattiesburg compliance.",
    projectTypes: "Medical interiors, university spaces, retail, residential additions, ADUs, and small commercial buildings.",
    sections: [
      { heading: "Use the Hattiesburg occupancy and alteration record", body: "Conditioned area, use, insulation, glazing, lighting, HVAC, and alteration category should drive the selected forms. Existing-building assumptions need to be stated rather than silently carried forward." },
      { heading: "Air and moisture continuity", body: "Air sealing, roof and wall transitions, ventilation, condensate, and moisture control need details at the addition interface. A lower modeled load does not remove the need for buildable envelope notes." },
      { heading: "Correct the model with the drawings", body: "Version Hattiesburg inputs, reports, equipment substitutions, and field checks. A window or HVAC correction should be reflected in MEP schedules, architectural details, and service calculations." },
    ],
    permitSteps: [
      "Ask Hattiesburg Community Development to identify the accepted energy edition, calculation method, forms, climate data, and alteration trigger.",
      "Build the Hattiesburg input record from verified assemblies, fenestration, shading, cooling equipment, outdoor air, lighting, water heating, and controls.",
      "Audit the report against fire separations, structural penetrations, MEP schedules, ADU boundaries, and moisture-transition details before filing.",
      "Respond to each Hattiesburg correction with the cited provision, changed input, replacement form, drawing cloud, and assigned field verification.",
    ],
    faqs: [
      { question: "Does a Hattiesburg addition use the same energy path as a new building?", answer: "Not necessarily. The adopted method, conditioned area, alteration category, connected systems, and AHJ direction determine the documentation." },
      { question: "Does compliance promise a Hattiesburg energy bill?", answer: "No. Compliance documents a selected method; weather, rates, occupants, maintenance, controls, and construction quality affect actual use." },
      { question: "What if Hattiesburg plan check changes the HVAC design?", answer: "Update the energy inputs and affected forms, then coordinate the revised equipment, loads, controls, and architectural details." },
    ],
    sources: hattiesburgSources,
  },
  {
    serviceSlug: "pe-stamped-drawings",
    title: "Hattiesburg PE-stamped drawings for defined scopes",
    description: "Hattiesburg sealed engineering packages that identify evidence, local handoffs, discipline boundaries, and controlled revisions.",
    h1: "PE-Stamped Drawings for Hattiesburg, Mississippi",
    kicker: "Hattiesburg professional scope and correction control",
    lede: "A Hattiesburg PE package should distinguish city, fire, utility, flood, stormwater, and Mississippi DEQ responsibilities and show the evidence supporting the accepted engineering discipline.",
    permitAuthority: "Hattiesburg Community Development and Planning determine the city route; the Mississippi Board of Licensure for Professional Engineers and Surveyors governs professional licensure, while a Mississippi PE accepts responsibility only for a defined engineering scope. Neither replaces local approval.",
    codeContext: "Identify adopted codes, wind and flood criteria, existing-condition limits, special inspections, and boundaries with architecture, survey, geotechnical, and contractor work.",
    localConditions: "Piney Woods slopes, sand and clay, creek floodplains, heat, intense rain, and utility capacity can require address-specific records.",
    projectTypes: "Civil site plans, structural alterations, MEP packages, additions, ADUs where required, medical work, and university-area improvements.",
    sections: [
      { heading: "Evidence for a Hattiesburg seal", body: "Survey, field observations, soil information, measured construction, utility records, equipment data, flood information, and calculations establish the design basis and its limitations." },
      { heading: "Hattiesburg agency boundaries", body: "Planning, building, fire, public works, utilities, floodplain, stormwater, and MDEQ may review different parts of a set. An index should identify who receives each document." },
      { heading: "Revisions after comments or RFIs", body: "A changed grade, substitution, demolition discovery, or RFI can alter scope. The responsible PE should decide whether calculations and sealed sheets must change before field use." },
    ],
    permitSteps: [
      "Map Hattiesburg building, planning, fire, utility, flood, stormwater, and environmental handoffs.",
      "Assemble survey, soil, flood, existing-condition, architectural, equipment, utility, and calculation records before scope acceptance.",
      "Have the responsible Mississippi PE review coordinated drawings, details, notes, schedules, and calculations before submission.",
      "Track comments and field changes, issue a numbered response, and release revised sealed sheets only after PE review.",
    ],
    faqs: [
      { question: "Does a Hattiesburg PE seal replace city approval?", answer: "No. It communicates responsibility for a defined scope; Hattiesburg and separate fire, utility, flood, stormwater, and environmental authorities retain approval decisions." },
      { question: "Can a Hattiesburg PE rely on photos of an addition?", answer: "The PE decides whether evidence is sufficient; framing, foundations, soil, utilities, flood conditions, and connections may require measurements or investigation." },
      { question: "How are Hattiesburg sealed-set corrections controlled?", answer: "The PE reviews the affected design, coordinates related sheets, answers the cited comments, and records any change to accepted scope." },
    ],
    sources: hattiesburgSources,
  },
];

const southavenServices: Batch2CoreServicePage[] = [
  {
    serviceSlug: "structural-engineering",
    title: "Southaven structural engineering for additions and infill",
    description: "Structural design for Southaven homes, ADUs, and commercial alterations using Delta-edge soils, drainage, and measured existing conditions.",
    h1: "Structural Engineering for Southaven, Mississippi",
    kicker: "Southaven foundations, framing, and flat-site drainage",
    lede: "Southaven’s Delta-edge clay and alluvium, suburban fill, rapid development, and Wolf River drainage make existing-condition and foundation evidence important before adding loads.",
    permitAuthority: "Southaven Building is the city permit starting point; Planning and Development, DeSoto County, fire, and utility reviews can be separate.",
    codeContext: "Confirm Southaven’s adopted building or residential code, Mississippi amendments, wind and flood criteria, occupancy, and special inspections.",
    localConditions: "Flat Delta-edge terrain, heavy clay and alluvium, fill, intense storms, Wolf River tributaries, and tornado exposure affect foundations and connections.",
    projectTypes: "Subdivision additions, detached ADUs, infill, retail alterations, warehouse interiors, and small commercial buildings.",
    sections: [
      { heading: "Verify Southaven’s existing construction", body: "Inspect slab edges, crawlspaces, footings, headers, roof connections, fill, and prior porch or room work before assigning new loads. Rapidly built neighboring homes are not evidence of this parcel." },
      { heading: "Flat grades still carry risk", body: "Clay, fill, Wolf River drainage, and shallow site grades can influence settlement, foundation drainage, finished floors, and access. Relate structural decisions to the survey and flood record." },
      { heading: "Plan-check changes cross disciplines", body: "Answer Southaven comments with revised calculations and connection details, then check civil, MEP, fire separation, and energy sheets. A changed grade or opening should not be left as a contractor interpretation." },
    ],
    permitSteps: [
      "Confirm Southaven jurisdiction, occupancy, adopted code, wind and flood criteria, and city or county reviewers.",
      "Collect survey, soil or fill information, framing exposures, footing evidence, roof loads, drainage elevations, and demolition limits.",
      "Coordinate foundations, hold-downs, headers, bracing, fire separations, MEP penetrations, and finished floors.",
      "Submit numbered Southaven correction responses with revised sheets and calculations after responsible-engineer review.",
    ],
    faqs: [
      { question: "Does a Southaven ADU need a new foundation review?", answer: "A detached foundation, bearing change, uncertain existing footing, new roof load, or unusual connection can require engineering; the AHJ and engineer determine scope." },
      { question: "Why check Wolf River drainage on a Southaven structure?", answer: "Flood and site drainage can influence finished floors, foundation moisture, equipment placement, access, and materials even when the building is outside a mapped floodway." },
      { question: "How should Southaven structural corrections be answered?", answer: "Tie each response to the revised detail or calculation and document how unexpected framing, fill, or foundation conditions were resolved." },
    ],
    sources: southavenSources,
  },
  {
    serviceSlug: "mep-engineering",
    title: "Southaven MEP engineering for growing buildings",
    description: "Southaven MEP coordination for Northcentral Electric, municipal water and sewer, humid cooling, fire flow, and additions.",
    h1: "MEP Engineering for Southaven, Mississippi",
    kicker: "Southaven service capacity and building-system coordination",
    lede: "Southaven MEP design should verify Northcentral Electric service, municipal water and sewer, cooling demand, and fire-flow information before equipment selection for a new interior or ADU.",
    permitAuthority: "Southaven Building and Planning are starting points; fire, public works, utilities, DeSoto County, and floodplain reviewers may have separate roles.",
    codeContext: "Identify Southaven’s adopted mechanical, plumbing, electrical, fuel-gas, fire, and energy provisions and the edition used by the permit reviewer.",
    localConditions: "Humid summers, flat drainage, clay, rapid subdivision growth, storm outages, short freezes, and Wolf River tributaries shape system routing.",
    projectTypes: "Retail, restaurants, warehouse fit-outs, multifamily additions, medical interiors, and detached ADUs.",
    sections: [
      { heading: "Southaven service records precede schedules", body: "Document Northcentral Electric service, transformer or meter information, water pressure, sewer connection, and fire flow before finalizing loads. Existing panels and pipes do not prove spare capacity." },
      { heading: "Humidity and flat sites affect equipment", body: "Latent load, outdoor air, condensate, filtration, flood-sensitive placement, and maintenance access should reflect the occupancy and Southaven site, not a generic Memphis assumption." },
      { heading: "Corrections need one utility record", body: "Risers, one-lines, controls, fire penetrations, and equipment clearances should be updated together when Southaven review changes a load, service, or ventilation decision." },
    ],
    permitSteps: [
      "Confirm Southaven building, fire, planning, public works, floodplain, utility, and energy handoffs.",
      "Request Northcentral Electric, water, sewer, and fire-flow information and field-trace existing service and distribution.",
      "Coordinate feeders, risers, ventilation, condensate, equipment elevations, controls, ADU tie-ins, and shutdowns.",
      "Return each Southaven MEP comment with revised schedules, risers, calculations, provider records, and a numbered response.",
    ],
    faqs: [
      { question: "What changes MEP design for a Southaven addition?", answer: "Added service load, water and sewer demand, humid-air ventilation, panel condition, fire separation, and drainage or flood exposure can change the design." },
      { question: "Does Northcentral Electric availability prove Southaven capacity?", answer: "No. Availability and project capacity differ; provider information must be reconciled with calculated loads and the existing service." },
      { question: "What closes a Southaven MEP correction?", answer: "Revise the affected drawing or calculation, cross-check related disciplines, and submit the provider or field evidence that supports the response." },
    ],
    sources: southavenSources,
  },
  {
    serviceSlug: "civil-engineering",
    title: "Southaven civil engineering for flat sites and growth",
    description: "Southaven grading, drainage, detention, access, utilities, and flood coordination for additions, infill, and development.",
    h1: "Civil Engineering for Southaven, Mississippi",
    kicker: "Southaven grading, detention, and utility profiles",
    lede: "Southaven civil work must connect flat Delta-edge grades, Wolf River tributaries, subdivision detention, drives, and utilities to a real receiving system as development changes the site.",
    permitAuthority: "Southaven Planning and Development and Building may share review with Public Works, fire, floodplain, utilities, and DeSoto County.",
    codeContext: "Confirm Southaven zoning, drainage, right-of-way, floodplain, detention, erosion, and Mississippi DEQ stormwater requirements for the address.",
    localConditions: "Heavy clay and alluvium, flat grades, rapid growth, subdivision ponds, intense storms, Wolf River drainage, and crowded utilities affect civil design.",
    projectTypes: "Subdivision additions, detached ADUs, retail parking, warehouse sites, infill, and frontage or utility improvements.",
    sections: [
      { heading: "Southaven outfalls need a surveyed path", body: "Locate inlets, ponds, ditches, easements, utility crossings, downstream grades, and Wolf River tributary limits before selecting detention or an outlet. A nearby basin is not proof of available capacity." },
      { heading: "Small residential changes still move water", body: "An ADU, patio, driveway, or addition can redirect runoff toward a crawlspace, lot line, alley, or existing detention system. Preserve fire access, utilities, and maintainable grades." },
      { heading: "Growth makes correction records important", body: "Answer Southaven grade comments with revised profiles, storage or flow calculations, access slopes, erosion details, and maintenance notes rather than only descriptive prose." },
    ],
    permitSteps: [
      "Confirm Southaven zoning, flood panel, watershed, disturbance boundary, detention threshold, frontage, and review agencies.",
      "Prepare a current survey and obtain outfall ownership, utility, soil, flood, fire-access, and easement information.",
      "Coordinate grading, finished floors, detention, erosion controls, ADU access, utilities, and profiles with architecture and structure.",
      "Submit numbered Southaven civil corrections with revised contours, profiles, calculations, details, and maintenance responsibilities.",
    ],
    faqs: [
      { question: "Can a Southaven ADU avoid site review?", answer: "A new driveway, sewer tie, impervious area, drainage path, flood exposure, or detention connection can trigger civil or utility review." },
      { question: "What controls a Southaven stormwater outlet?", answer: "Receiving-system capacity, Wolf River drainage, detention ownership, floodplain, easements, soils, Mississippi DEQ conditions, and maintenance control it." },
      { question: "Why do Southaven grade comments affect the building set?", answer: "Finished floors, foundation drainage, access, utility depth, fire routes, and neighboring runoff follow the revised site grades." },
    ],
    sources: southavenSources,
  },
  {
    serviceSlug: "energy-compliance",
    title: "Southaven energy compliance for additions and fit-outs",
    description: "Southaven energy documentation for humid envelopes, HVAC, glazing, lighting, and the local alteration method.",
    h1: "Energy Compliance for Southaven, Mississippi",
    kicker: "Southaven envelope and cooling documentation",
    lede: "Southaven energy work should fit the adopted local method and humid summer envelope, not a generic Memphis-area worksheet. Additions and ADUs require coordinated records for existing and new systems.",
    permitAuthority: "Ask Southaven Building which energy edition, method, forms, and residential or commercial alteration provisions apply.",
    codeContext: "Identify Southaven’s adopted energy provisions and Mississippi amendments, including the method and edition accepted for this permit.",
    localConditions: "High cooling loads, humidity, solar gain, heavy rain, flat roofs, storm outages, and existing subdivision construction influence compliance details.",
    projectTypes: "Retail fit-outs, warehouse offices, residential additions, ADUs, restaurants, multifamily work, and small commercial buildings.",
    sections: [
      { heading: "Classify the Southaven project", body: "Occupancy, conditioned area, alteration category, insulation, glazing, lighting, and HVAC schedules should drive the forms. Do not treat an addition as a standalone new building without AHJ direction." },
      { heading: "Coordinate envelope and equipment", body: "Air sealing, roof transitions, moisture control, ventilation, condensate, glazing, controls, and equipment schedules should agree across Southaven architectural, MEP, and energy documents." },
      { heading: "Plan-check changes need version control", body: "Keep model inputs, forms, equipment substitutions, and field checks synchronized. A corrected efficiency, window, or HVAC value can change loads, service, and construction details." },
    ],
    permitSteps: [
      "Ask Southaven Building to identify the adopted energy edition, accepted compliance method, forms, climate inputs, and alteration classification.",
      "Assemble Southaven inputs from the selected wall and roof assemblies, windows, shading, cooling units, ventilation, lighting, water heating, and controls.",
      "Compare the submitted record with fire-rated construction, structural penetrations, MEP schedules, ADU limits, and moisture details at each interface.",
      "Close every Southaven energy comment with a provision citation, revised input or form, drawing reference, and documented field-check responsibility.",
    ],
    faqs: [
      { question: "Does a Southaven ADU automatically use new-construction forms?", answer: "Not automatically: the ADU’s conditioned boundary, relationship to the existing dwelling, new services, alteration scope, and Southaven’s accepted method control the forms and supporting schedules." },
      { question: "Does compliance guarantee lower Southaven energy bills?", answer: "No. Rates, weather, occupants, maintenance, controls, construction quality, and operating schedules affect actual use." },
      { question: "What if Southaven plan check changes a window or unit?", answer: "Update the compliance inputs and affected drawings, then check service loads, controls, envelope details, and the coordinated permit record." },
    ],
    sources: southavenSources,
  },
  {
    serviceSlug: "pe-stamped-drawings",
    title: "Southaven PE-stamped drawings for coordinated permits",
    description: "Southaven sealed engineering documents with site evidence, city and utility boundaries, and controlled correction responses.",
    h1: "PE-Stamped Drawings for Southaven, Mississippi",
    kicker: "Southaven responsible scope and plan-check record",
    lede: "A Southaven PE package should make city, DeSoto County, utility, fire, flood, and stormwater boundaries explicit and show the evidence supporting the accepted engineering scope.",
    permitAuthority: "Southaven Building and Planning determine the city route; the Mississippi Board of Licensure for Professional Engineers and Surveyors governs professional licensure, while a Mississippi PE is responsible only for the engineering discipline and scope independently accepted. Neither replaces local approval.",
    codeContext: "Identify adopted codes, wind and flood criteria, existing-condition limits, special inspections, and boundaries with architecture, survey, geotechnical, and contractors.",
    localConditions: "Clay and alluvium, flat drainage, rapid growth, Wolf River tributaries, severe storms, and utility capacity require address-specific evidence.",
    projectTypes: "Civil site plans, structural alterations, MEP packages, additions, ADUs where required, retail, and warehouse improvements.",
    sections: [
      { heading: "Southaven evidence before sealing", body: "Survey, soil or fill records, measured construction, utility letters, flood information, equipment data, and calculations establish the basis and limitations of professional judgment." },
      { heading: "Make agency boundaries legible", body: "Building, planning, fire, public works, utilities, floodplain, stormwater, and MDEQ may receive different documents. A Southaven drawing index should show the handoff." },
      { heading: "Keep post-review changes controlled", body: "A revised grade, service, substitution, RFI, or field discovery can affect sealed work. The responsible PE should evaluate the change before a revised sheet reaches construction." },
    ],
    permitSteps: [
      "Map Southaven building, planning, fire, public works, utility, flood, stormwater, and environmental handoffs.",
      "Assemble survey, soil, flood, existing-condition, equipment, utility, architectural, and calculation records before accepting scope.",
      "Have the responsible Mississippi PE review coordinated drawings, schedules, details, notes, and calculations before submission.",
      "Track corrections and field changes in a dated matrix, then issue revised sealed sheets only after PE review.",
    ],
    faqs: [
      { question: "Does a Southaven PE seal replace city approval?", answer: "No. It communicates responsibility for a defined scope; Southaven and separate utility, fire, flood, stormwater, and environmental authorities decide approvals." },
      { question: "Can a Southaven PE rely on an unverified subdivision plan?", answer: "The PE should identify limitations and obtain enough current evidence to exercise independent judgment for the defined scope." },
      { question: "Who reviews a Southaven field change after sealing?", answer: "The responsible PE evaluates changes within the sealed scope, while Southaven determines whether a permit revision is required." },
    ],
    sources: southavenSources,
  },
];

const meridianServices: Batch2CoreServicePage[] = [
  {
    serviceSlug: "structural-engineering",
    title: "Meridian structural engineering for industrial and residential work",
    description: "Meridian structural design for additions and alterations using red-clay soils, existing industrial framing, drainage, and severe-weather criteria.",
    h1: "Structural Engineering for Meridian, Mississippi",
    kicker: "Meridian foundations, industrial framing, and connections",
    lede: "Meridian structural design must distinguish rolling red clay and fill from older rail or industrial construction. Existing masonry, roof equipment, and severe wind make field verification important before a new load is assigned.",
    permitAuthority: "Meridian Community Development is the city starting point; Lauderdale County, fire, utility, and industrial owner reviews may be separate.",
    codeContext: "Confirm Meridian’s adopted building or residential code, Mississippi amendments, occupancy, wind and flood criteria, and special inspections.",
    localConditions: "Rolling red-clay and sandy soils, industrial redevelopment, urban drainage, heat, intense rain, and severe wind affect Meridian foundations and connections.",
    projectTypes: "Industrial alterations, retail interiors, residential additions, detached ADUs, rail-adjacent redevelopment, and small commercial buildings.",
    sections: [
      { heading: "Meridian existing buildings need investigation", body: "Inspect masonry, steel or wood framing, foundations, roof equipment, corrosion, and prior openings before relying on an older industrial or residential record. Document what is observed and what remains uncertain." },
      { heading: "Clay, fill, and drainage meet structure", body: "Relate footing, slab, retaining, and finished-floor decisions to survey grades, soil information, and flood data. Rolling sites can move runoff toward an addition or adjacent industrial yard." },
      { heading: "Answer Meridian comments with calculations", body: "Return load, connection, and foundation corrections with revised details and affected civil or MEP sheets. If demolition reveals different masonry or fill, pause the assumed load path and reassess." },
    ],
    permitSteps: [
      "Confirm Meridian jurisdiction, occupancy, adopted code, wind and flood criteria, industrial review, and fire requirements.",
      "Collect survey, soil or fill evidence, framing exposures, foundation observations, roof loads, equipment data, and demolition limits.",
      "Coordinate foundations, bracing, anchors, openings, equipment supports, fire separations, MEP penetrations, and drainage.",
      "Submit numbered Meridian correction responses after the responsible engineer reviews changed field conditions and calculations.",
    ],
    faqs: [
      { question: "Does a Meridian industrial addition need existing-building engineering?", answer: "A new opening, equipment load, foundation change, uncertain framing, or altered occupancy can require engineering; the AHJ and responsible engineer define scope." },
      { question: "Why does Meridian clay matter to an addition?", answer: "Clay, fill, slope, and drainage can influence settlement, foundation movement, finished floors, retaining, and moisture decisions." },
      { question: "How should Meridian structural plan-check comments be handled?", answer: "Use a numbered response tied to revised calculations and details, and record how field discoveries changed or confirmed the design." },
    ],
    sources: meridianSources,
  },
  {
    serviceSlug: "mep-engineering",
    title: "Meridian MEP engineering for industrial and occupied spaces",
    description: "Meridian MEP coordination for East Mississippi EPA service, municipal systems, process loads, ventilation, and storm resilience.",
    h1: "MEP Engineering for Meridian, Mississippi",
    kicker: "Meridian utility, process, and building-system coordination",
    lede: "Meridian MEP work must reconcile East Mississippi Electric Power Association service, water and sewer, industrial or medical loads, ventilation, and storm resilience before schedules are finalized.",
    permitAuthority: "Meridian Community Development coordinates city building review; fire, public works, utility, industrial owner, and county reviews can be separate.",
    codeContext: "Identify Meridian’s adopted mechanical, plumbing, electrical, fuel-gas, fire, and energy provisions and the edition applied to this permit.",
    localConditions: "Industrial heat, humid summers, severe storms, urban drainage, short freezes, and variable utility demands influence Meridian systems.",
    projectTypes: "Industrial tenant work, process-support spaces, retail, medical interiors, occupied renovations, additions, and ADUs.",
    sections: [
      { heading: "Meridian service capacity is project-specific", body: "Obtain East Mississippi EPA service information, panel or transformer data, water pressure, sewer capacity, and fire flow before fixing equipment. A facility’s existing connection may serve a different load or use." },
      { heading: "Process and comfort loads need separation", body: "Ventilation, exhaust, makeup air, controls, condensate, filtration, and after-hours operation should distinguish industrial or medical processes from ordinary occupied space." },
      { heading: "Track Meridian corrections by system", body: "Risers, one-lines, equipment schedules, controls, fire penetrations, and shutdown plans should be revised together when a reviewer or owner changes capacity or use." },
    ],
    permitSteps: [
      "Confirm Meridian building, fire, public works, industrial, floodplain, energy, and utility review handoffs.",
      "Request East Mississippi EPA, water, sewer, and fire-flow information and field-trace existing service and process systems.",
      "Coordinate feeders, risers, exhaust, ventilation, condensate, controls, shutdowns, equipment supports, and ADU connections.",
      "Return numbered Meridian MEP corrections with revised calculations, schedules, risers, controls, and provider correspondence.",
    ],
    faqs: [
      { question: "What changes MEP design for a Meridian industrial alteration?", answer: "Process exhaust, electrical demand, water and sewer use, occupancy, fire separation, existing service condition, and ventilation can change the design." },
      { question: "Does East Mississippi EPA availability establish Meridian capacity?", answer: "No. Provider information must be checked against calculated project loads, service equipment, and any process demand." },
      { question: "How should Meridian MEP substitutions be documented?", answer: "Recheck loads, controls, clearances, energy information, and related disciplines, then submit revised schedules or calculations with a numbered response." },
    ],
    sources: meridianSources,
  },
  {
    serviceSlug: "civil-engineering",
    title: "Meridian civil engineering for rolling sites and redevelopment",
    description: "Meridian grading, drainage, utility, access, and erosion plans for industrial redevelopment, additions, and infill.",
    h1: "Civil Engineering for Meridian, Mississippi",
    kicker: "Meridian grades, outfalls, utilities, and industrial access",
    lede: "Meridian civil design connects rolling grades, industrial drives, urban drainage, and creek outfalls to the actual receiving system rather than assuming a usable ditch or level parcel.",
    permitAuthority: "Meridian Community Development and Public Works may share review with Planning, fire, utilities, floodplain, and Lauderdale County.",
    codeContext: "Confirm Meridian zoning, drainage, right-of-way, floodplain, erosion, Mississippi DEQ stormwater, and industrial access requirements.",
    localConditions: "Red clay, sandy fill, rolling grades, heavy rain, urban inlets, industrial yards, creek drainage, and utility crossings shape Meridian civil plans.",
    projectTypes: "Industrial redevelopment, commercial parking, residential additions, ADUs, rail-adjacent sites, and public-frontage work.",
    sections: [
      { heading: "Meridian outfalls require current survey", body: "Locate ditches, inlets, creeks, easements, industrial drives, utility crossings, downstream grades, and flood limits before selecting detention or an outlet." },
      { heading: "Industrial access and residential drainage", body: "A new loading area, driveway, ADU, or addition can change heavy-vehicle access, fire routes, roof runoff, sewer demand, and neighboring drainage. Keep maintenance and emergency access visible." },
      { heading: "Profiles make Meridian corrections actionable", body: "Revise contours, profiles, storage or flow calculations, erosion details, utility crossings, and maintenance notes when Public Works or Planning changes a grade or outlet." },
    ],
    permitSteps: [
      "Confirm Meridian zoning, flood status, watershed, disturbance boundary, access, frontage, and review agencies.",
      "Prepare a current survey and obtain outfall ownership, utility, soil, flood, fire-access, easement, and right-of-way information.",
      "Coordinate grading, finished floors, detention, erosion controls, industrial access, ADU routes, and utility profiles.",
      "Submit numbered Meridian civil responses with revised drawings, calculations, details, and maintenance responsibilities.",
    ],
    faqs: [
      { question: "Can a Meridian ADU avoid civil review?", answer: "A driveway, sewer connection, added impervious area, drainage change, flood exposure, or utility crossing can trigger site or utility review." },
      { question: "What controls a Meridian industrial outfall?", answer: "The receiving ditch or creek, downstream capacity, floodplain, easements, soil, Mississippi DEQ conditions, ownership, and maintenance responsibility control it." },
      { question: "Why do Meridian civil comments reach structural design?", answer: "Grade, access, retaining, finished-floor, foundation drainage, utility depth, and equipment-support decisions are linked across the site and building." },
    ],
    sources: meridianSources,
  },
  {
    serviceSlug: "energy-compliance",
    title: "Meridian energy compliance for industrial and residential alterations",
    description: "Meridian energy documentation for humid envelopes, industrial schedules, HVAC, lighting, and local alteration review.",
    h1: "Energy Compliance for Meridian, Mississippi",
    kicker: "Meridian envelope, equipment, and operating-schedule records",
    lede: "Meridian compliance documents should reflect the adopted local path, hot summers, lighting, HVAC, and actual existing-building or industrial alteration rather than a generic worksheet.",
    permitAuthority: "Ask Meridian Community Development which energy edition, method, forms, and residential or commercial alteration provisions apply.",
    codeContext: "Identify Meridian’s adopted energy provisions and Mississippi amendments, the selected method and edition, and any occupancy-specific requirements.",
    localConditions: "Humid cooling, industrial schedules, process heat, solar gain, heavy rain, storm outages, and older envelopes influence Meridian inputs.",
    projectTypes: "Industrial tenant improvements, retail, medical spaces, residential additions, ADUs, warehouses, and small commercial buildings.",
    sections: [
      { heading: "Meridian schedules must describe actual use", body: "Occupancy, operating hours, process loads, conditioned area, lighting, glazing, insulation, and HVAC should drive the selected compliance method. A warehouse office and a process area do not share assumptions." },
      { heading: "Coordinate process and envelope changes", body: "Air sealing, roof transitions, ventilation, exhaust, controls, condensate, lighting, and equipment schedules need consistent architectural and MEP details at an alteration." },
      { heading: "Correction records protect the field set", body: "Version model inputs, forms, equipment substitutions, and field checks together. A change to operating schedule or unit efficiency may alter service, loads, controls, and drawings." },
    ],
    permitSteps: [
      "Confirm Meridian’s adopted energy edition, method, forms, climate data, occupancy, and alteration trigger with the AHJ.",
      "Collect verified envelope, glazing, lighting, HVAC, process, ventilation, service-water, and control inputs.",
      "Reconcile the report with Meridian fire separations, structural penetrations, MEP equipment, ADU boundaries, and moisture details.",
      "Answer every energy correction with its cited provision, input, revised form, drawing reference, and field responsibility.",
    ],
    faqs: [
      { question: "Does a Meridian industrial alteration use a residential energy path?", answer: "No assumption should be made; occupancy, conditioned area, process scope, alteration category, and AHJ direction determine the documentation." },
      { question: "Does Meridian energy compliance predict operating cost?", answer: "No. Rates, schedules, process use, weather, maintenance, controls, and construction quality affect actual energy use." },
      { question: "What if Meridian equipment changes during procurement?", answer: "Recheck the compliance inputs, loads, service, controls, and MEP schedules, then document the coordinated permit revision." },
    ],
    sources: meridianSources,
  },
  {
    serviceSlug: "pe-stamped-drawings",
    title: "Meridian PE-stamped drawings for industrial and civic review",
    description: "Meridian sealed engineering packages that define evidence, professional scope, agency handoffs, and correction control.",
    h1: "PE-Stamped Drawings for Meridian, Mississippi",
    kicker: "Meridian professional responsibility and permit boundaries",
    lede: "A Meridian sealed package should identify existing conditions, discipline limits, city and utility handoffs, industrial interfaces, and how plan-check corrections will be controlled.",
    permitAuthority: "Meridian Community Development determines the city permit route; the Mississippi Board of Licensure for Professional Engineers and Surveyors governs professional licensure, while a Mississippi PE is responsible only for a defined engineering discipline and scope. Neither replaces local approval.",
    codeContext: "Identify adopted codes, wind and flood criteria, industrial or occupancy requirements, existing-condition limitations, special inspections, and consultant boundaries.",
    localConditions: "Red clay and fill, industrial structures, rolling drainage, severe weather, utility capacity, and creek outfalls require address-specific evidence.",
    projectTypes: "Industrial alterations, civil site plans, structural work, MEP packages, additions, ADUs where required, and public improvements.",
    sections: [
      { heading: "Meridian evidence before sealing", body: "Survey, soil and fill information, field observations, measured framing, utility records, equipment data, flood information, and calculations establish a defensible basis and its limitations." },
      { heading: "Separate Meridian review roles", body: "Building, planning, fire, public works, utilities, floodplain, stormwater, MDEQ, and industrial owners may review different documents. The index should make each boundary clear." },
      { heading: "Controlled revisions preserve responsibility", body: "A changed process load, grade, substitution, RFI, or demolition discovery can affect sealed work. The responsible PE should review the change before revised sheets or field direction are issued." },
    ],
    permitSteps: [
      "Map Meridian building, planning, fire, public works, utility, flood, stormwater, environmental, and owner handoffs.",
      "Assemble survey, soil, flood, existing-condition, equipment, process, utility, architectural, and calculation records.",
      "Route Meridian’s coordinated sheets, details, notes, schedules, and calculations to the responsible Mississippi PE for pre-submission review.",
      "Track comments, RFIs, substitutions, inspections, and field changes; issue revised sealed sheets only after PE review.",
    ],
    faqs: [
      { question: "Does a Meridian PE seal replace city or owner approval?", answer: "No. It communicates responsibility for a defined engineering scope; Meridian and separate fire, utility, flood, stormwater, environmental, and owner authorities retain approvals." },
      { question: "Can a Meridian PE seal undocumented industrial framing?", answer: "The PE should identify limitations and obtain enough survey, measurement, testing, or investigation to exercise independent judgment." },
      { question: "What happens after a Meridian sealed-set correction?", answer: "The responsible PE evaluates the changed industrial or site condition, updates linked documents when necessary, and records the response and any change in accepted scope." },
    ],
    sources: meridianSources,
  },
];

const mississippiMetros: Batch2Metro[] = [
  { slug: "jackson", name: "Jackson", county: "Hinds County", services: jacksonServices },
  { slug: "gulfport", name: "Gulfport", county: "Harrison County", services: gulfportServices },
  { slug: "hattiesburg", name: "Hattiesburg", county: "Forrest County", services: hattiesburgServices },
  { slug: "southaven", name: "Southaven", county: "DeSoto County", services: southavenServices },
  { slug: "meridian", name: "Meridian", county: "Lauderdale County", services: meridianServices },
];

const mississippiBatch4: Batch2StateExpansion = {
  stateSlug: "mississippi",
  stateName: "Mississippi",
  stateAbbrev: "MS",
  hub: {
    title: "Mississippi engineering permit coordination",
    description: "Mississippi structural, MEP, civil, energy, and PE-scope guidance grounded in local agencies, utilities, drainage, and adopted requirements.",
    h1: "Engineering for Mississippi Projects",
    kicker: "Address-specific Mississippi permit coordination",
    lede: "Mississippi projects cross municipal or county building review with utility, fire, floodplain, stormwater, and environmental decisions. Start with the parcel, current adopted provisions, surveyed conditions, and the actual scope of work.",
    sections: [
      { heading: "The address determines the authority", body: "Jackson, Gulfport, Hattiesburg, Southaven, Meridian, and their counties use different building, zoning, fire, floodplain, right-of-way, and stormwater routes. Confirm the AHJ before fixing design criteria or promising a permit sequence." },
      { heading: "Ground and weather vary across Mississippi", body: "Delta alluvium, clay, coastal sand and groundwater, Piney Woods slopes, urban fill, river channels, hurricanes, tornadoes, heat, and intense rain change foundation, envelope, equipment, and drainage decisions by parcel." },
      { heading: "Utilities and environmental reviews are separate", body: "Entergy Mississippi, Mississippi Power, electric cooperatives, municipal systems, MDEQ, MEMA, FEMA, fire authorities, and local public works may each affect a different sheet or approval. A building permit does not establish utility capacity." },
      { heading: "Additions and ADUs remain integrated", body: "An addition or ADU can change foundations, service, sewer, drainage, energy, occupancy, access, and flood elevation. Carry those interfaces through one coordinated set and answer each correction with a controlled revision." },
      { heading: "Frontage and transportation access", body: "A project with a new or modified driveway, sidewalk, drainage connection, or work near a state route may need coordination beyond the building counter. Mississippi Department of Transportation access or right-of-way requirements can apply on a state-maintained road, while a city or county public-works office may control local frontage, curb, ditch, or utility work. The responsible team should identify the road owner, sight-distance and drainage constraints, construction access, and any encroachment or access application before civil and architectural plans are finalized. These agencies may review related work separately from the building permit." },
    ],
    faqs: [
      { question: "Does Mississippi have one statewide building permit office?", answer: "No. A municipality or county generally administers the building route, while fire, utility, floodplain, stormwater, and environmental authorities may make separate decisions." },
      { question: "What should be checked before Mississippi engineering begins?", answer: "Confirm the parcel AHJ, current code edition, survey, soils, flood status, drainage, utility capacity, occupancy, wind exposure, and alteration scope." },
      { question: "Does a PE seal guarantee Mississippi approval?", answer: "No. A seal communicates responsibility for a defined engineering scope; the AHJ and other agencies decide whether their requirements are satisfied." },
    ],
    sources: [
      { label: "Mississippi Secretary of State administrative rules", url: "https://www.sos.ms.gov/adminsearch" },
      { label: "Mississippi DEQ stormwater", url: "https://www.mdeq.ms.gov/water/sw/" },
      { label: "Mississippi Emergency Management Agency", url: "https://www.msema.org/" },
      { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
      { label: "Mississippi Board of Licensure for Professional Engineers and Surveyors", url: "https://www.pepls.ms.gov/" },
    ],
  },
  metros: mississippiMetros,
};

export { mississippiBatch4 };
export default mississippiBatch4;