import type { Batch2StateExpansion, Batch2CoreServiceSlug } from "./batch2-core-service-types";

type MetroSeed = {
  slug: string; name: string; county: string; ahj: string; source: { label: string; url: string };
  utility: string; conditions: string; localCode: string; projects: string;
};
type ServiceSeed = {
  slug: Batch2CoreServiceSlug; label: string; focus: string; discipline: string;
  sections: [string, string, string]; steps: [string, string, string, string];
  questions: [string, string, string];
};

const stateSources = [
  { label: "Connecticut State Building Code and regulations", url: "https://portal.ct.gov/dcp/building-code-and-regulations" },
  { label: "Connecticut DEEP stormwater permits", url: "https://portal.ct.gov/deep/water/permits-and-registrations/stormwater" },
  { label: "Connecticut DEEP flood management", url: "https://portal.ct.gov/deep/water/flood-management" },
  { label: "Connecticut professional engineer licensing", url: "https://portal.ct.gov/dcp/occupational-and-professional-licenses/professional-engineers" },
];

const metros: MetroSeed[] = [
  { slug: "bridgeport", name: "Bridgeport", county: "Fairfield County", ahj: "City of Bridgeport Building Department", source: { label: "Bridgeport Building Department", url: "https://www.bridgeportct.gov/government/departments/building" }, utility: "Aquarion Water Company, Eversource electric and gas, and the City Engineering and Public Facilities divisions", conditions: "coastal storm surge and tidal flooding around the harbor, dense older masonry, variable fill over glacial deposits, salt exposure, and intense rainfall", localCode: "Bridgeport zoning, coastal site-plan and floodplain review, plus the Connecticut State Building Code", projects: "port-adjacent reuse, multifamily rehabilitation, two-family conversions, ADUs where zoning allows, and residential additions" },
  { slug: "new-haven", name: "New Haven", county: "New Haven County", ahj: "City of New Haven Building Department", source: { label: "New Haven Building Department", url: "https://www.newhavenct.gov/government/departments/building" }, utility: "South Central Connecticut Regional Water Authority, Eversource, and the City Engineering Department", conditions: "shoreline and river flood exposure, steep West Rock-area grades, urban fill, older wood-frame and brick buildings, and winter freeze-thaw", localCode: "New Haven zoning and zoning-board processes, floodplain review, and the Connecticut State Building Code as locally administered", projects: "university-area tenant improvements, historic row-house work, accessory apartments, porch repairs, and infill additions" },
  { slug: "stamford", name: "Stamford", county: "Fairfield County", ahj: "City of Stamford Building Department", source: { label: "Stamford Building Department", url: "https://www.stamfordct.gov/government/operations/land-use-building-management/building" }, utility: "Aquarion Water Company, Eversource, and Stamford Engineering", conditions: "Long Island Sound surge, steep glacial till and ledge transitions, high-value dense construction, winter snow, and constrained utility corridors", localCode: "Stamford zoning, flood and coastal-site review, and Connecticut code provisions with any city amendments confirmed at intake", projects: "downtown high-rise fit-outs, shoreline houses, suburban ADUs, office-to-residential changes, and additions on ledge" },
  { slug: "hartford", name: "Hartford", county: "Hartford County", ahj: "City of Hartford Development Services and Licenses & Inspections", source: { label: "Hartford Development Services", url: "https://www.hartfordct.gov/Government/Departments/Development-Services" }, utility: "The Metropolitan District, Eversource, and Hartford Public Works", conditions: "Connecticut River and Park River floodplains, urban fill, aging brick and timber stock, freeze-thaw, snow drift, and riverine groundwater", localCode: "Hartford zoning and historic-district review where applicable, floodplain requirements, and the Connecticut State Building Code", projects: "downtown adaptive reuse, neighborhood multifamily, historic storefronts, ADU feasibility, and code-driven residential additions" },
  { slug: "norwalk", name: "Norwalk", county: "Fairfield County", ahj: "City of Norwalk Building Department", source: { label: "Norwalk Building Department", url: "https://www.norwalkct.gov/282/Building-Department" }, utility: "Aquarion Water Company, Eversource, and Norwalk Department of Public Works", conditions: "tidal Norwalk River and coastal flooding, salt-laden wind, ledge and glacial soils, dense shoreline lots, and heavy snow or rain events", localCode: "Norwalk zoning and coastal-area review with the Connecticut State Building Code and floodplain requirements", projects: "waterfront commercial work, beach-area additions, accessory apartments, restaurant fit-outs, and drainage-sensitive residential redevelopment" },
];

const serviceSeeds: ServiceSeed[] = [
  { slug: "structural-engineering", label: "Structural Engineering", focus: "existing framing, gravity and lateral load paths, foundations, and safe interfaces between new and retained construction", discipline: "structural", sections: ["Existing-condition verification is the first design control for {name}. Field measurements, permit history, probes, and the architect’s demolition plan distinguish assumed framing from confirmed framing before a beam, opening, ADU, or residential addition is sized.", "The {conditions} make load paths and foundations site-specific. A {project} may require a survey, geotechnical opinion, flood-elevation check, corrosion review, or snow and wind assessment rather than a detail copied from an inland site.", "After {ahj} issues plan-check comments, the response should identify each sheet and calculation change, preserve superseded details, and route structural revisions through the responsible Connecticut PE before resubmittal."], steps: ["Confirm the parcel, occupancy, existing permits, zoning triggers, and current Connecticut code edition with {ahj}.", "Document framing, soils, flood/wind/snow assumptions, utility penetrations, and construction access before selecting the {discipline} system.", "Coordinate calculations, connection details, special-inspection notes, and architectural or MEP openings with the {ahj} submission.", "Log every plan-check correction from {ahj}, issue a coordinated revision, and retain field-observation or as-built decisions for closeout."], questions: ["When does {project} need structural investigation in {name}?", "How should {ahj} corrections be answered for a {discipline} set?", "Do coastal or snow conditions change a {name} structural design?"] },
  { slug: "mep-engineering", label: "MEP Engineering", focus: "mechanical, electrical, plumbing, ventilation, life-safety interfaces, utility capacity, and maintainable routing", discipline: "MEP", sections: ["MEP scope for {name} starts with occupancy, equipment schedules, existing service traces, and a utility conversation with {utility}. A residential addition or ADU can be small on paper yet still expose panel, water-pressure, sewer, ventilation, or fire-separation limits.", "For a {project}, {conditions} affect corrosion protection, heating design, freeze protection, ventilation, emergency power, and condensate or drainage routing. Each system should be reconciled with Connecticut mechanical, plumbing, electrical, energy, and fire requirements in the applicable code edition.", "A useful {ahj} plan-check response pairs every correction with a revised sheet, calculation, schedule, or narrative. Substitutions and inaccessible shafts should be re-coordinated rather than silently marked up after the first review."], steps: ["Open the {ahj} building and occupancy intake and verify the applicable Connecticut code path, fire review, and utility service contacts.", "Obtain service data from {utility}, field-trace equipment and shafts, and establish loads, ventilation, water demand, drainage, and controls.", "Coordinate MEP plans with structure, envelope, accessibility, energy documentation, and construction shutdown or phasing constraints.", "Return {ahj} comments in a numbered correction log, revise the coordinated set, and preserve commissioning, testing, and utility correspondence."], questions: ["What utility information is needed for MEP work in {name}?", "How do ADU or residential-addition loads affect a {discipline} review?", "What is a responsible response to {ahj} MEP comments?"] },
  { slug: "civil-engineering", label: "Civil Engineering", focus: "survey, grading, stormwater, erosion control, utilities, access, and floodplain or coastal coordination", discipline: "civil", sections: ["A {name} civil plan joins the survey, parcel limits, zoning, public frontage, utilities, and receiving drainage system instead of treating a building permit as the entire site approval. The {ahj} handoff should be identified before the footprint or disturbance area is fixed.", "Because {conditions}, grading around a {project} may involve flood storage, coastal or riverine elevations, ledge, retaining, soil infiltration limits, salt exposure, and winter erosion. Connecticut DEEP permits and local drainage standards are triggered by the actual disturbance and outfall.", "When reviewers return corrections, the engineer should show changed drainage areas, slopes, details, calculations, and maintenance responsibilities in a revision cloud or response matrix. That workflow keeps the building, stormwater, and erosion packages consistent."], steps: ["Pull the current survey, FEMA flood information, zoning map, utility records, and {ahj} site or right-of-way checklist.", "Send disturbance, grading, outfall, coastal or floodplain, and erosion-control questions to {ahj} and Connecticut DEEP as the project requires.", "Coordinate accessible routes, fire access, retaining, utilities, tree or shoreline constraints, and construction sequencing with the building set.", "Answer plan-check corrections by revising the civil sheets and calculations, then record inspection, maintenance, and surveyed-as-built obligations."], questions: ["Who reviews stormwater for a {name} site?", "Can a {project} use the existing drainage connection?", "How are flood or coastal comments handled after {ahj} review?"] },
  { slug: "energy-compliance", label: "Energy Compliance", focus: "the adopted Connecticut energy path, envelope, HVAC, lighting, service water, controls, and alteration documentation", discipline: "energy", sections: ["Energy documentation for {name} follows occupancy, alteration scope, and the Connecticut code edition confirmed with {ahj}; it is not an incentive promise. Envelope sections, lighting, equipment schedules, and controls must agree with the permit drawings for a {project}.", "The {conditions} influence heating degree days, wind exposure, air leakage, moisture safety, snow at roofs, and coastal durability. An ADU or residential addition may use a prescriptive path or another permitted route, but the assumptions must match the actual assemblies and equipment.", "Plan-check correction is a design-control step: record the reviewer’s code citation, update forms or model inputs, revise the affected architectural or MEP sheets, and resubmit one coordinated Connecticut package rather than changing only the energy worksheet."], steps: ["Ask {ahj} to confirm the current Connecticut energy-code edition, alteration category, forms, and local submission sequence.", "Collect envelope, glazing, lighting, HVAC, service-water, controls, schedules, and utility inputs for the {project}.", "Cross-check the energy analysis against structural penetrations, MEP equipment, architectural details, and field implementation responsibilities.", "Respond to {ahj} energy comments with a numbered matrix and revised forms, then retain final equipment and functional-testing records."], questions: ["Does {project} in {name} require energy documentation?", "How do coastal or winter conditions affect the energy path?", "Can an energy correction be submitted separately from {ahj} building revisions?"] },
  { slug: "pe-stamped-drawings", label: "PE-Stamped Drawings", focus: "professional responsibility, discipline boundaries, calculations, seals, and a review-ready Connecticut submission", discipline: "sealed engineering", sections: ["A Connecticut PE seal represents responsibility for a defined {discipline} scope, not a generic permit guarantee. For {name}, the record should identify the parcel, existing conditions, code edition, design assumptions, and the actual sheets the responsible engineer reviewed.", "The {conditions} and {project} may require survey, geotechnical, utility, flood, fire, or specialty information before a PE can accept responsibility. {ahj} may also route drawings to planning, fire, coastal, health, or public-works reviewers with separate authority.", "A correction workflow protects the seal: log {ahj} comments, let the responsible PE evaluate each technical change, revise the affected drawings and calculations, and submit a dated coordinated set. Contractor RFIs or substitutions should not alter sealed work without that review."], steps: ["Identify the Connecticut jurisdiction, {ahj} checklist, occupancy, code edition, and discipline scope before assigning seal responsibility.", "Assemble verified survey, field observations, geotechnical and utility information, calculations, and consultant interfaces for the {project}.", "Have the responsible PE review the coordinated drawings, notes, details, schedules, and required seal format before submission.", "Track {ahj} corrections and construction RFIs through the responsible PE, issuing revised sealed sheets only where the accepted scope changes."], questions: ["What does a Connecticut PE seal cover for {project}?", "Can {ahj} require more than the sealed drawing set?", "How are field changes to sealed work documented in {name}?"] },
];

function renderService(m: MetroSeed, s: ServiceSeed): any {
  const fill = (text: string) => text.replaceAll("{name}", m.name).replaceAll("{ahj}", m.ahj).replaceAll("{conditions}", m.conditions).replaceAll("{project}", m.projects).replaceAll("{utility}", m.utility).replaceAll("{discipline}", s.discipline);
  return {
    serviceSlug: s.slug, title: `${m.name} ${s.label} for ${m.projects}`, description: `${s.label} for ${m.name} projects, coordinated with ${m.ahj}, Connecticut code, local conditions, utilities, and the responsible professional.`,
    h1: `${s.label} for ${m.name} Projects`, kicker: `${m.name} permitting and ${s.discipline} coordination`,
    lede: `${s.label} in ${m.name} requires a site-specific scope, current code check, and a clear correction path with ${m.ahj}. ${s.focus}.`,
    permitAuthority: `${m.ahj} is the named local building authority for work in ${m.name}; planning, fire, zoning, public works, health, floodplain, coastal, and utility reviewers may have separate roles. The applicable Connecticut PE confirms professional responsibility and seal requirements.`,
    codeContext: `${m.localCode}. Confirm the current Connecticut State Building Code edition, state amendments, energy provisions, local ordinances, and project transition rules with the AHJ before documents are finalized.`,
    localConditions: `${m.conditions}. These facts should be tested against current survey, geotechnical, flood, utility, and field information rather than assumed from a regional average.`,
    projectTypes: m.projects,
    sections: s.sections.map((x, i) => ({ heading: [`${m.name} ${s.label} scope and records`, `${m.name} conditions in the design`, `Plan-check corrections for ${m.name}`][i], body: fill(x) })),
    permitSteps: s.steps.map(fill), faqs: s.questions.map((q, i) => ({ question: fill(q), answer: [fill(`The answer depends on the ${s.discipline} scope, existing conditions, current Connecticut requirements, and the information ${m.ahj} requests. A ${m.name} project should document those facts before the design is fixed.`), fill(`${m.ahj} may involve zoning, building, fire, floodplain, coastal, public-works, or utility reviewers. The project team should answer the cited correction with a coordinated revision and keep the response record.`), fill(`No. ${m.ahj} and the responsible Connecticut PE determine the required documents for the actual scope. Field conditions, code edition, occupancy, and project changes can add review.`)][i] })),
    sources: [m.source, ...stateSources],
  };
}

const connecticutBatch3: Batch2StateExpansion = {
  stateSlug: "connecticut", stateName: "Connecticut", stateAbbrev: "CT",
  hub: {
    title: "Connecticut Engineering Services for Permitted Projects",
    description: "Connecticut structural, MEP, civil, energy-compliance, and PE-stamped drawing support grounded in local AHJ, coastal, flood, snow, and site conditions.",
    h1: "Engineering for Connecticut Communities and Coastlines", kicker: "Connecticut permitting and design coordination",
    lede: "Connecticut has a statewide building-code framework, but cities and towns administer zoning, plan review, utilities, floodplain, coastal, and site approvals locally. A useful design record identifies the responsible AHJ, current code edition, site conditions, and a practical plan-check correction workflow.",
    sections: [
      { heading: "State code, local authority", body: "The Connecticut State Building Code and its current amendments establish the baseline; Bridgeport, New Haven, Stamford, Hartford, Norwalk, and other local authorities control their own intake, zoning, fire, public-way, site processes, and local amendments. A state code reference does not replace an address-specific AHJ check." },
      { heading: "Coast, rivers, snow, and ground", body: "Long Island Sound and tidal rivers bring surge, salt, and flood-elevation questions, while inland river corridors, glacial soils, ledge, freeze-thaw, snow, and steep terrain affect foundations, drainage, envelopes, and utilities. Current survey, geotechnical, FEMA, and utility records matter." },
      { heading: "Residential work needs the same discipline", body: "ADUs and residential additions can change egress, fire separation, structure, HVAC, service capacity, grading, and energy documentation. The team should treat them as integrated permit scopes and carry AHJ corrections through one coordinated revision set." },
      { heading: "Coastal and inland reviews follow different paths", body: "A shoreline parcel may require municipal coastal-site-plan, floodplain, wetlands, or harbor coordination in addition to the building permit, while an inland property can involve a local inland-wetlands agency, steep-slope rules, or Metropolitan District utility review. The submission matrix should name each authority, required datum, design-flood elevation, utility owner, and responsible drawing before the permit set is issued." },
    ],
    faqs: [
      { question: "Does Connecticut have one local building department?", answer: "No. The state publishes the code framework, while the city or town where the parcel sits administers building and related local reviews. The responsible AHJ and any parallel coastal, flood, utility, or zoning authority must be confirmed by address." },
      { question: "How should a Connecticut plan-check correction be handled?", answer: "Log each comment, identify the cited requirement, revise every affected drawing or calculation, and submit a coordinated response through the AHJ. The responsible PE evaluates technical changes; approval is a decision of the reviewing authority." },
      { question: "Are ADUs and additions exempt from engineering review?", answer: "Not automatically. Scope, occupancy, existing conditions, zoning, structure, utilities, flood exposure, and the local checklist determine what documents are required." },
    ],
    sources: stateSources,
  },
  metros: metros.map((m) => ({ slug: m.slug, name: m.name, county: m.county, services: serviceSeeds.map((s) => renderService(m, s)) })),
};

export { connecticutBatch3 };
export default connecticutBatch3;