import type { Batch2CoreServicePage, Batch2StateExpansion } from "./batch2-core-service-types";

type Service = Batch2CoreServicePage;
type Source = { label: string; url: string };

const missouriEngineeringBoardSource: Source = {
  label: "Missouri Board for Architects, Professional Engineers, Professional Land Surveyors and Professional Landscape Architects",
  url: "https://pr.mo.gov/apelsla.asp",
};

const kcSources: Source[] = [
  { label: "Kansas City Planning and Development", url: "https://www.kcmo.gov/city-hall/departments/city-planning-development" },
  { label: "Kansas City Development Services", url: "https://www.kcmo.gov/city-hall/departments/city-planning-development/development-services" },
  { label: "Kansas City Public Works", url: "https://www.kcmo.gov/city-hall/departments/public-works" },
  { label: "Kansas City Water", url: "https://www.kcwater.us/" },
  { label: "Evergy Missouri", url: "https://www.evergy.com/" },
  { label: "Missouri DNR water and stormwater programs", url: "https://dnr.mo.gov/water" },
  { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  { label: "U.S. Department of Energy building energy codes", url: "https://www.energy.gov/cmei/buildings" },
];
const stlSources: Source[] = [
  { label: "St. Louis Building Division", url: "https://www.stlouis-mo.gov/government/departments/public-safety/building/" },
  { label: "St. Louis zoning and land use", url: "https://www.stlouis-mo.gov/government/departments/public-safety/building/zoning/" },
  { label: "St. Louis Water Division", url: "https://www.stlwater.com/" },
  { label: "St. Louis Streets Department", url: "https://www.stlouis-mo.gov/government/departments/street/" },
  { label: "Ameren Missouri", url: "https://www.ameren.com/missouri" },
  { label: "Missouri DNR water and stormwater programs", url: "https://dnr.mo.gov/water" },
  { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  { label: "U.S. Department of Energy building energy codes", url: "https://www.energy.gov/cmei/buildings" },
];
const springfieldSources: Source[] = [
  { label: "Springfield Building Development Services", url: "https://www.springfieldmo.gov/303/Building-Development-Services" },
  { label: "Springfield Planning and Zoning", url: "https://www.springfieldmo.gov/270/Planning-Zoning" },
  { label: "Springfield Public Works", url: "https://www.springfieldmo.gov/377/Public-Works" },
  { label: "City Utilities of Springfield", url: "https://www.cityutilities.net/" },
  { label: "Missouri DNR water and stormwater programs", url: "https://dnr.mo.gov/water" },
  { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  { label: "U.S. Department of Energy building energy codes", url: "https://www.energy.gov/cmei/buildings" },
];
const columbiaSources: Source[] = [
  { label: "Columbia Community Development", url: "https://www.como.gov/community-development/" },
  { label: "Columbia Planning", url: "https://www.como.gov/community-development/planning/" },
  { label: "Columbia Public Works", url: "https://www.como.gov/public-works/" },
  { label: "Columbia Water and Light", url: "https://www.como.gov/utilities/" },
  { label: "Missouri DNR water and stormwater programs", url: "https://dnr.mo.gov/water" },
  { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  { label: "U.S. Department of Energy building energy codes", url: "https://www.energy.gov/cmei/buildings" },
];
const independenceSources: Source[] = [
  { label: "Independence Building Inspections", url: "https://www.independencemo.gov/government/city-departments/community-development/building-inspections-division" },
  { label: "Independence Development Services", url: "https://www.independencemo.gov/government/city-departments/community-development/development-services" },
  { label: "Independence permits for public infrastructure improvements", url: "https://www.independencemo.gov/government/city-departments/municipal-services/permits-public-infrastructure-improvements" },
  { label: "City of Independence Power and Light", url: "https://www.independencemo.gov/government/city-departments/power-and-light/about-independence-power-light" },
  { label: "Independence Water Division service area", url: "https://www.independencemo.gov/government/city-departments/municipal-services/water-division/water-service-area" },
  { label: "Independence stormwater management plan", url: "https://www.independencemo.gov/government/city-departments/municipal-services/environmental-programs/stormwater-management-plan" },
  { label: "Missouri DNR water and stormwater programs", url: "https://dnr.mo.gov/water" },
  { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  { label: "U.S. Department of Energy building energy codes", url: "https://www.energy.gov/cmei/buildings" },
];

const kansasCity: Service[] = [
  {
    serviceSlug: "structural-engineering",
    title: "Kansas City structural engineering for additions and infill",
    description: "Structural design for Kansas City renovations, additions, and infill with verified loads, foundations, and local review coordination.",
    h1: "Structural Engineering for Kansas City, Missouri",
    kicker: "Kansas City load paths, foundations, and urban infill",
    lede: "Kansas City structural work starts with the actual framing, soil record, and permit history, especially where an addition meets older urban construction.",
    permitAuthority: "Kansas City Planning and Development is the building permit contact; zoning, fire, public works, floodplain, and utility reviews can be separate.",
    codeContext: "Confirm the adopted building and residential codes, amendments, occupancy, wind, snow, seismic, and special-inspection requirements with Kansas City Development Services.",
    localConditions: "Loess and urban fill, river-tributary flooding, freeze-thaw, ice, tornado wind, and irregular older foundations can change the design assumptions.",
    projectTypes: "Residential additions, detached ADUs, storefront alterations, multifamily repairs, and urban infill",
    sections: [
      { heading: "Existing Kansas City framing", body: "Probe masonry, wood diaphragms, footings, and prior openings before sizing a new beam. Permit history and field measurements are more reliable than a typical detail." },
      { heading: "Fill, drainage, and lateral resistance", body: "A structural package should identify bearing assumptions and coordinate finished floors, flood information, retaining, and lateral connections where loess or fill meets a sloped lot." },
      { heading: "Plan-check correction record", body: "Answer a Kansas City comment with the affected calculation, connection or foundation detail, and coordinated architectural and MEP sheet; document limits on concealed conditions." },
    ],
    permitSteps: [
      "Confirm the Kansas City address, occupancy, zoning route, adopted code, flood status, and structural review checklist.",
      "Collect survey control, geotechnical recommendations, framing exposures, existing permit information, and loads from architectural and MEP design.",
      "Coordinate foundations, collectors, anchors, openings, shoring, rooftop equipment, and special-inspection notes before the set is submitted.",
      "Log each reviewer correction, revise the cited sheet or calculation, and have the responsible PE review field-dependent changes before resubmittal.",
    ],
    faqs: [
      { question: "Does a Kansas City addition automatically require new footing calculations?", answer: "Not automatically. New reactions, soil evidence, foundation condition, setbacks, and the city checklist determine whether a new calculation or detail is needed." },
      { question: "Can an urban-fill bearing value be copied from a nearby project?", answer: "No. Fill thickness and composition vary by parcel; the geotechnical record and observed conditions should support the selected bearing approach." },
      { question: "Who accepts a structural correction response?", answer: "The Kansas City reviewer decides whether the response satisfies the permit review; the responsible PE explains the engineering scope without promising approval." },
    ],
    sources: kcSources,
  },
  {
    serviceSlug: "mep-engineering",
    title: "Kansas City MEP engineering for occupied buildings",
    description: "Kansas City MEP design for tenant work, additions, and ADUs coordinated with utilities, fire protection, and local plan review.",
    h1: "MEP Engineering for Kansas City, Missouri",
    kicker: "Kansas City service capacity and building-system coordination",
    lede: "Kansas City MEP documents need the building's real occupancy, utility capacity, ventilation, and winter operating conditions rather than a generic equipment schedule.",
    permitAuthority: "Kansas City Development Services coordinates building review, while fire, utility, public works, and zoning authorities may request separate documents.",
    codeContext: "Verify the adopted mechanical, plumbing, electrical, energy, fire, and accessibility provisions and the applicable alteration path with the local reviewer.",
    localConditions: "Hot humid summers, ice, winter design temperatures, tornado exposure, older services, and combined sewer or stormwater constraints affect system coordination.",
    projectTypes: "Tenant improvements, occupied renovations, multifamily work, restaurant fit-outs, and detached ADUs",
    sections: [
      { heading: "Capacity before equipment selection", body: "Record existing panels, gas service, water pressure, sewer points, and fire-flow information before finalizing equipment, risers, and domestic-water demands." },
      { heading: "Ventilation and weather response", body: "Schedules should address outdoor air, filtration, condensate, freeze protection, controls, equipment access, and safe shutdowns for the actual Kansas City occupancy." },
      { heading: "Cross-discipline corrections", body: "A panel, shaft, or fire-separation comment can alter structure, energy forms, and architecture. Revise the riser, load calculation, schedule, and related detail together." },
    ],
    permitSteps: [
      "Confirm occupancy, adopted mechanical, plumbing, electrical, energy, fire, and accessibility requirements with Kansas City Development Services.",
      "Field-verify existing services and request current electric, gas, water, sewer, and fire-flow information from the applicable providers.",
      "Coordinate equipment clearances, shafts, condensate, controls, panel schedules, metering, and construction phasing with architecture and structure.",
      "Return numbered corrections with revised calculations, risers, schedules, and utility correspondence tied to each agency comment.",
    ],
    faqs: [
      { question: "Does a Kansas City ADU need an independent MEP design?", answer: "Its service loads, water and sewer connections, ventilation, fire separation, and utility arrangement determine the required documents; the AHJ sets the submittal path." },
      { question: "Is utility availability the same as available capacity?", answer: "No. A provider's service territory or connection option does not replace project load calculations and written capacity information." },
      { question: "What happens when an MEP product changes after plan check?", answer: "Recheck loads, clearances, energy inputs, controls, and connected architectural details, then issue a coordinated revision through the responsible design professional." },
    ],
    sources: kcSources,
  },
  {
    serviceSlug: "civil-engineering",
    title: "Kansas City civil engineering for grading and drainage",
    description: "Civil plans for Kansas City site access, grading, drainage, utilities, and infill projects tied to local public works review.",
    h1: "Civil Engineering for Kansas City, Missouri",
    kicker: "Kansas City grades, outfalls, and utility interfaces",
    lede: "A Kansas City civil plan connects the surveyed parcel to its receiving drainage system, frontage, utilities, fire access, and flood information.",
    permitAuthority: "Kansas City Planning and Development handles the local development route; Public Works, zoning, floodplain, and utility reviews may add requirements.",
    codeContext: "Check the current Kansas City zoning, site-development, stormwater, right-of-way, accessibility, and erosion-control requirements for the address.",
    localConditions: "Rolling grades, loess, urban fill, clay, intense rain, tributary flooding, alleys, and constrained outfalls make parcel-level drainage evidence important.",
    projectTypes: "Infill lots, parking changes, residential additions, detached ADUs, commercial frontage, and small public improvements",
    sections: [
      { heading: "Survey to receiving system", body: "Show parcel limits, spot grades, inlets, alleys, easements, utilities, accessible routes, fire access, and the owned or permitted downstream connection." },
      { heading: "Runoff on compact lots", body: "An addition or detached ADU can send roof water toward a basement, alley, retaining wall, or neighboring lot. Grading and finished-floor elevations should show the intended path." },
      { heading: "Public works coordination", body: "A nearby inlet is not automatically an approved outfall. Confirm capacity, right-of-way limits, maintenance responsibility, erosion protection, and any floodplain review." },
    ],
    permitSteps: [
      "Confirm Kansas City zoning, public-works, stormwater, floodplain, right-of-way, and erosion-control thresholds for the parcel.",
      "Obtain a current survey and verify utilities, easements, finished floors, receiving inlets, outfall ownership, and soil or infiltration assumptions.",
      "Coordinate grading, drainage calculations, utility profiles, accessible routes, fire access, retaining, and construction protection with the building set.",
      "Answer each correction with revised contours, profiles, calculations, details, and maintenance notes that identify the responsible party.",
    ],
    faqs: [
      { question: "Can a Kansas City site drain to the nearest street inlet?", answer: "Only after the inlet, right-of-way, grade, capacity, and public-works acceptance are checked; proximity alone does not establish a permitted connection." },
      { question: "When can an ADU trigger civil work?", answer: "New roof, paving, grading, utility work, access, easement impacts, or flood exposure can require site documentation even on a small residential parcel." },
      { question: "Who owns a private or public outfall?", answer: "Ownership and maintenance must be confirmed from current city, utility, easement, and parcel records rather than inferred from field appearance." },
    ],
    sources: kcSources,
  },
  {
    serviceSlug: "energy-compliance",
    title: "Kansas City energy compliance for additions and fit-outs",
    description: "Kansas City energy documentation coordinated with the adopted code, envelope details, HVAC schedules, and alteration scope.",
    h1: "Energy Compliance for Kansas City, Missouri",
    kicker: "Kansas City envelope, equipment, and alteration documentation",
    lede: "Kansas City energy compliance is a coordinated record of envelope, lighting, HVAC, controls, and the code path selected for the actual project.",
    permitAuthority: "Kansas City Development Services determines the permit review route and can identify the adopted energy provisions and alteration documentation.",
    codeContext: "Confirm the current locally adopted energy edition, residential or commercial method, climate inputs, exemptions, and forms before modeling.",
    localConditions: "Humid summers, cold winters, ice, solar gain, wind, and older envelope assemblies affect air sealing, insulation, equipment, and controls.",
    projectTypes: "Commercial alterations, residential additions, tenant improvements, multifamily renovations, and ADUs",
    sections: [
      { heading: "Envelope inputs from the drawings", body: "Glazing, shading, insulation, air barriers, roof assemblies, and thermal bridges should match the architectural details and the selected compliance method." },
      { heading: "Kansas City HVAC and lighting", body: "Equipment efficiency, ventilation, condensate, controls, lighting power, and service-water inputs must agree with the MEP schedules and the operating use." },
      { heading: "Alterations and additions", body: "Classify the work before assuming an exemption. A new addition can change fenestration, envelope, HVAC, and lighting obligations while the existing building remains occupied." },
    ],
    permitSteps: [
      "Ask Kansas City Development Services to confirm the current energy edition, climate inputs, alteration category, and required forms.",
      "Collect verified assemblies, windows, shading, HVAC, lighting, service-water, control, and equipment data from the coordinated design.",
      "Compare modeled inputs with architectural details, structural penetrations, MEP schedules, and procurement constraints before submission.",
      "Respond to energy comments with the applicable provision, revised form or model input, and references to each changed construction detail.",
    ],
    faqs: [
      { question: "Is a Kansas City residential addition exempt from energy documentation?", answer: "There is no universal answer; the scope, alteration category, current adopted provisions, and reviewer instructions determine the documentation path." },
      { question: "Do compliance forms guarantee lower utility bills?", answer: "No. They document the selected code-compliance method and design inputs, not future bills, incentives, or operating performance." },
      { question: "What if a specified HVAC unit is substituted?", answer: "Recheck efficiency, capacity, controls, electrical loads, and modeled inputs, then coordinate the change with the permit drawings and responsible professional." },
    ],
    sources: kcSources,
  },
  {
    serviceSlug: "pe-stamped-drawings",
    title: "Kansas City PE-stamped drawings for permit coordination",
    description: "Kansas City sealed engineering documents that define discipline scope, site evidence, revisions, and local review boundaries.",
    h1: "PE-Stamped Drawings for Kansas City, Missouri",
    kicker: "Kansas City responsible-charge documentation",
    lede: "A Kansas City sealed set should identify its engineering scope, site evidence, design criteria, and revision controls without implying approval.",
    permitAuthority: "Kansas City Planning and Development reviews the applicable permit set; zoning, fire, public works, floodplain, and utility authorities retain their own roles.",
    codeContext: "Confirm the city checklist, adopted code editions, seal format, special inspections, and discipline-specific submittal requirements before sealing; check Missouri board requirements for the responsible PE's signature and seal.",
    localConditions: "Urban fill, older construction, river-tributary flooding, weather extremes, utility constraints, and narrow lots can require outside survey or geotechnical evidence.",
    projectTypes: "Permit sets for additions, tenant work, infill, public-facing renovations, site changes, and residential ADUs",
    sections: [
      { heading: "Define the Kansas City scope", body: "Identify the parcel, occupancy, code path, survey, soil and flood assumptions, calculations, drawings, exclusions, and the professional responsible for each discipline." },
      { heading: "Evidence and consultant boundaries", body: "Surveyors, geotechnical professionals, utilities, fire reviewers, and public works may provide facts outside the PE's direct observation; state those dependencies clearly." },
      { heading: "Controlled revisions after review", body: "A dated comment matrix links each Kansas City correction, substitution, RFI, and field discovery to a sheet or calculation and the responsible PE's decision." },
    ],
    permitSteps: [
      "For Kansas City, record the enforcing office, occupancy, code path, discipline limits, checklist, seal presentation, and any public-works or flood handoff.",
      "Assemble current survey, field observations, soil, flood, utility, existing-condition, calculation, and consultant records.",
      "Before Kansas City submission, the responsible PE should reconcile the sealed sheets with the architectural issue set, calculations, details, notes, and stated assumptions.",
      "Route plan-check corrections, substitutions, RFIs, and field discoveries back through the PE and issue revised sealed sheets when scope changes.",
    ],
    faqs: [
      { question: "Does a Kansas City PE seal mean the permit will be approved?", answer: "No. It identifies professional responsibility for a defined engineering scope; the city and other authorities decide whether their requirements are met." },
      { question: "Can a PE seal concealed existing framing without inspection?", answer: "The professional must identify limitations and exercise independent judgment; unverified conditions should remain qualified rather than presented as confirmed." },
      { question: "Are contractor substitutions covered automatically?", answer: "No. A substitution that affects sealed work needs review, documentation, and any revised sheet or calculation required by the responsible PE and AHJ." },
    ],
    sources: [...kcSources, missouriEngineeringBoardSource],
  },
];

const stLouis: Service[] = [
  {
    serviceSlug: "structural-engineering",
    title: "St. Louis structural engineering for historic and infill work",
    description: "Structural design for St. Louis additions, masonry buildings, and renovations with verified conditions and local review coordination.",
    h1: "Structural Engineering for St. Louis, Missouri",
    kicker: "St. Louis masonry, foundations, and river-city load paths",
    lede: "St. Louis structural design must reconcile historic masonry, urban fill, changing basements, and the actual condition of a building before a new load is assigned.",
    permitAuthority: "The St. Louis Building Division is the primary building review contact; zoning, fire, streets, flood, and utility reviews can be independent.",
    codeContext: "Confirm the City of St. Louis adopted building, existing-building, residential, fire, wind, snow, seismic, and special-inspection provisions with the Building Division.",
    localConditions: "Historic brick, shallow and altered foundations, urban fill, clay, freeze-thaw, Mississippi and River des Peres flooding, and ice affect structural decisions.",
    projectTypes: "Historic rehabs, townhouse additions, storefront alterations, multifamily conversions, and detached ADUs",
    sections: [
      { heading: "Masonry and altered basements", body: "Document brick wythe condition, joists, lintels, basement walls, previous openings, and underpinning evidence before relying on an old load path." },
      { heading: "Flood and foundation interfaces", body: "River and low-lying parcels need finished-floor, drainage, soil, and flood information coordinated with foundation details and moisture-sensitive materials." },
      { heading: "Building Division responses", body: "Tie each correction to a revised calculation, masonry or connection detail, and affected architectural sheet; distinguish observed facts from assumptions about concealed construction." },
    ],
    permitSteps: [
      "Confirm the St. Louis address, historic or zoning status, occupancy, adopted code, flood information, and Building Division checklist.",
      "Gather survey, geotechnical recommendations, probes, framing measurements, prior permit records, and loads from the coordinated design.",
      "Coordinate foundation, masonry, temporary shoring, opening, equipment, fire-separation, and special-inspection details before submission.",
      "Prepare a numbered correction response, revise the cited documents, and obtain PE review of any field condition or construction change.",
    ],
    faqs: [
      { question: "Does a St. Louis historic building require a new structural survey?", answer: "The necessary evidence depends on the scope and available records, but historic masonry and altered basements should not be treated as typical without observation." },
      { question: "Can an addition bear on an existing St. Louis foundation?", answer: "Only after its condition, geometry, new reactions, soil, settlement relationship, and the AHJ's requested documents are evaluated." },
      { question: "Does a structural seal resolve historic-review comments?", answer: "No. A PE addresses defined engineering work; building, zoning, and any historic-review authority retain their own decisions." },
    ],
    sources: stlSources,
  },
  {
    serviceSlug: "mep-engineering",
    title: "St. Louis MEP engineering for older buildings",
    description: "St. Louis MEP coordination for historic renovations, tenant work, additions, and ADUs with utility and plan-check interfaces.",
    h1: "MEP Engineering for St. Louis, Missouri",
    kicker: "St. Louis utility, ventilation, and occupied-building coordination",
    lede: "St. Louis MEP planning must account for older services, masonry routes, humid summers, winter operation, and the use of the renovated space.",
    permitAuthority: "The St. Louis Building Division reviews the building package; Water Division, Ameren, fire, zoning, and Streets may have separate requirements.",
    codeContext: "Verify current adopted mechanical, plumbing, electrical, energy, fire, accessibility, and existing-building provisions with the local review offices.",
    localConditions: "Historic construction, limited shafts, combined sewer areas, freeze-thaw, summer humidity, ice, and flood-sensitive basements influence system routing.",
    projectTypes: "Historic tenant improvements, multifamily conversions, restaurants, occupied renovations, and residential additions or ADUs",
    sections: [
      { heading: "Trace services before design", body: "Field-verify panels, gas, domestic water, sewer, ventilation routes, and fire protection rather than assuming a historic riser serves the proposed occupancy." },
      { heading: "Masonry, humidity, and maintenance", body: "Penetrations, condensate, outdoor air, filtration, equipment access, and controls need details that protect old masonry and support safe operation." },
      { heading: "Utility and fire comments", body: "A service or fire-separation change can alter shafts, structure, energy documents, and egress. Keep the revised riser, load calculations, and architectural plan synchronized." },
    ],
    permitSteps: [
      "Confirm occupancy, historic or zoning constraints, adopted mechanical, plumbing, electrical, energy, and fire provisions with St. Louis reviewers.",
      "Field-trace existing systems and obtain current Water Division, Ameren, sewer, electrical, and fire-flow information where applicable.",
      "Coordinate equipment, shafts, penetrations, condensate, controls, clearances, shutdowns, and occupied phasing with architecture and structure.",
      "Answer comments with revised schedules, risers, calculations, and provider records that identify every affected sheet.",
    ],
    faqs: [
      { question: "Can a St. Louis ADU use the dwelling's existing services?", answer: "That depends on measured capacity, utility rules, water and sewer arrangement, ventilation, fire separation, and the approved occupancy scope." },
      { question: "Why are masonry penetrations an MEP issue?", answer: "Opening size, lintels, fire stopping, moisture, and historic construction can affect structural and building-review documents as well as the mechanical route." },
      { question: "Does a utility response replace an MEP design?", answer: "No. Provider information establishes an interface or constraint; the design still documents loads, distribution, equipment, controls, and code coordination." },
    ],
    sources: stlSources,
  },
  {
    serviceSlug: "civil-engineering",
    title: "St. Louis civil engineering for urban drainage",
    description: "St. Louis civil plans for grades, flood-sensitive lots, utilities, access, and public-street coordination.",
    h1: "Civil Engineering for St. Louis, Missouri",
    kicker: "St. Louis grades, alleys, and river drainage",
    lede: "St. Louis civil design connects a tight urban parcel to streets, alleys, sewers, utilities, accessible routes, and flood information using a current survey.",
    permitAuthority: "St. Louis Community Development and Public Safety coordinate local development review; Streets, Water, zoning, and floodplain authorities may review separate elements.",
    codeContext: "Confirm current site-development, zoning, stormwater, right-of-way, floodplain, erosion, accessibility, and utility requirements for the address.",
    localConditions: "Steep streets, historic alleys, clay and fill, combined-sewer interfaces, Mississippi and River des Peres flood exposure, and intense rain affect drainage.",
    projectTypes: "Rowhouse additions, parking changes, infill lots, commercial frontage, ADUs, and small site improvements",
    sections: [
      { heading: "Urban survey and outfalls", body: "Show spot grades, curb and alley elevations, inlets, manholes, easements, utility crossings, finished floors, accessible paths, and the receiving system." },
      { heading: "Basements and overland flow", body: "A new roof, patio, or driveway can direct water toward a basement or adjacent lot. The plan should identify positive drainage, overflow, and maintenance responsibility." },
      { heading: "Streets and water coordination", body: "A connection to a nearby manhole or inlet needs ownership, capacity, right-of-way, and agency confirmation; do not infer an approval from existing pavement." },
    ],
    permitSteps: [
      "Identify St. Louis zoning, Streets, Water, floodplain, right-of-way, stormwater, and erosion-review requirements for the parcel.",
      "Verify survey datum, curb and alley grades, utilities, sewer points, easements, finished floors, flood information, and outfall ownership.",
      "Coordinate grading, drainage, accessible routes, fire access, utility profiles, pavement restoration, and construction protection with the building plans.",
      "Respond to each correction using revised contours, profiles, calculations, details, and clearly assigned maintenance notes.",
    ],
    faqs: [
      { question: "Can an urban St. Louis addition discharge to the alley?", answer: "Only if grades, property rights, public drainage, and the responsible city or utility reviewer support that connection; an alley is not automatically an outfall." },
      { question: "When does flood information change a small project?", answer: "It can affect finished floors, drainage, materials, utilities, and review agencies even when the addition itself is modest." },
      { question: "Are sewer and stormwater approvals the same?", answer: "No. The applicable utility, public-works, flood, and building reviews can address different portions of a site connection." },
    ],
    sources: stlSources,
  },
  {
    serviceSlug: "energy-compliance",
    title: "St. Louis energy compliance for historic alterations",
    description: "St. Louis energy documentation for renovations, additions, and tenant work tied to the adopted method and existing-building scope.",
    h1: "Energy Compliance for St. Louis, Missouri",
    kicker: "St. Louis envelope, humidity, and alteration records",
    lede: "St. Louis energy documentation must balance the adopted compliance path with historic assemblies, humid summers, winter heat, and the actual alteration boundary.",
    permitAuthority: "The St. Louis Building Division identifies the building and energy submittal route; zoning or historic review can impose additional design constraints.",
    codeContext: "Confirm the current adopted energy provisions, residential or commercial method, existing-building exceptions, climate inputs, and forms before modeling.",
    localConditions: "Masonry walls, older windows, humid summers, cold winters, ice, air leakage, and flood-sensitive lower levels affect envelope and equipment choices.",
    projectTypes: "Historic renovations, commercial tenant improvements, multifamily work, residential additions, and ADUs",
    sections: [
      { heading: "Existing envelope evidence", body: "Record wall, roof, window, air-barrier, insulation, and shading conditions. A historic assembly should be modeled or documented rather than silently replaced with a generic wall." },
      { heading: "Moisture and HVAC coordination", body: "Heating, cooling, ventilation, filtration, controls, and condensate details should agree with the envelope strategy and avoid creating moisture problems in masonry." },
      { heading: "Scope classification", body: "An addition or tenant alteration can trigger different documentation from a repair. Establish the work area and selected compliance route with the Building Division." },
    ],
    permitSteps: [
      "Confirm St. Louis energy provisions, climate inputs, historic or existing-building treatment, alteration category, and required forms.",
      "Collect actual assemblies, windows, shading, HVAC, lighting, water-heating, control, and equipment information from the coordinated plans.",
      "Cross-check modeled inputs against masonry details, structural penetrations, MEP schedules, and field installation constraints.",
      "Answer corrections with cited provisions, revised forms or inputs, and coordinated drawing references rather than an isolated worksheet.",
    ],
    faqs: [
      { question: "Can historic windows be excluded from St. Louis energy review?", answer: "The applicable existing-building or historic provisions and the project scope determine the route; an assumption about age is not a determination." },
      { question: "How does humidity affect a St. Louis renovation?", answer: "Ventilation, cooling, filtration, controls, and envelope vapor or air movement should be coordinated for the actual use and assembly." },
      { question: "Does an energy compliance report promise performance?", answer: "No. It records a code method and design inputs; operating results depend on construction, controls, weather, and use." },
    ],
    sources: stlSources,
  },
  {
    serviceSlug: "pe-stamped-drawings",
    title: "St. Louis PE-stamped drawings for coordinated review",
    description: "St. Louis sealed engineering sets that document professional scope, existing conditions, and correction control.",
    h1: "PE-Stamped Drawings for St. Louis, Missouri",
    kicker: "St. Louis scope, evidence, and revision accountability",
    lede: "A St. Louis sealed package should explain what was reviewed, which existing facts support it, and how Building Division comments are controlled.",
    permitAuthority: "The St. Louis Building Division reviews the building submission; zoning, historic, fire, Streets, Water, and utility offices retain separate authority.",
    codeContext: "Confirm the applicable city checklist, adopted code, existing-building provisions, seal presentation, and required discipline documents; verify the responsible PE's Missouri board obligations before sealing.",
    localConditions: "Historic masonry, urban fill, river flood exposure, narrow rights-of-way, older utilities, and concealed alterations can limit available evidence.",
    projectTypes: "Historic permits, additions, commercial fit-outs, multifamily repairs, site alterations, and ADU packages",
    sections: [
      { heading: "Professional scope in the set", body: "Identify the St. Louis parcel, occupancy, code path, survey, soil and flood assumptions, calculations, sheets, exclusions, and discipline boundaries." },
      { heading: "Separate agency interfaces", body: "Historic, zoning, fire, Streets, Water, utility, and geotechnical information may be supplied by other authorities or professionals; record those dependencies without overstating them." },
      { heading: "Correction and field control", body: "A response matrix should connect each comment, substitution, RFI, or concealed condition to the responsible PE's evaluation and any revised sealed document." },
    ],
    permitSteps: [
      "Identify the St. Louis enforcing office, occupancy, code path, historic or zoning constraints, checklist, and seal requirements.",
      "Assemble verified survey, field observations, existing-building, soil, flood, utility, calculation, and consultant information.",
      "Before St. Louis submission, the responsible PE should review the masonry, flood, utility, and existing-condition interfaces along with every sealed drawing and calculation.",
      "Route review comments and construction changes through that PE and issue revised sealed sheets only for the changed professional scope.",
    ],
    faqs: [
      { question: "Does a St. Louis PE seal replace historic or zoning approval?", answer: "No. It identifies responsibility for a defined engineering scope, while the city offices and other authorities decide their own requirements." },
      { question: "Can a sealed set certify an unseen masonry condition?", answer: "The PE should identify observation limits and avoid treating concealed or unverified construction as confirmed." },
      { question: "Who decides whether a field change needs a permit revision?", answer: "The Building Division determines the permit route, and the responsible PE evaluates whether the change affects sealed engineering work." },
    ],
    sources: [...stlSources, missouriEngineeringBoardSource],
  },
];

const springfield: Service[] = [
  {
    serviceSlug: "structural-engineering",
    title: "Springfield structural engineering for Ozark sites",
    description: "Structural design for Springfield additions, renovations, and infill with karst, rock, grades, and local permit review in view.",
    h1: "Structural Engineering for Springfield, Missouri",
    kicker: "Springfield foundations, rock, and severe-weather load paths",
    lede: "Springfield structural work begins with the actual soil, rock, framing, and drainage evidence because Ozark ground conditions vary across short distances.",
    permitAuthority: "Springfield Building Development Services is the local building contact; planning, fire, public works, flood, and utility reviews may be separate.",
    codeContext: "Ask Springfield Building Development Services which locally adopted building, residential, fire, energy, wind, snow, and inspection provisions govern this occupancy and foundation scope.",
    localConditions: "Ozark karst, shallow rock, clay, rolling grades, flash runoff, ice, and severe wind can change foundation and connection details.",
    projectTypes: "Residential additions, detached ADUs, hillside homes, commercial renovations, and small infill buildings",
    sections: [
      { heading: "Ozark ground and existing framing", body: "Use probes, survey, geotechnical recommendations, and observed framing to distinguish rock, fill, clay, retaining, and undocumented alterations before sizing new work." },
      { heading: "Water near the foundation", body: "Rolling sites and karst-sensitive drainage require finished floors, footings, retaining, roof runoff, and erosion paths to be coordinated rather than treated as separate details." },
      { heading: "Springfield corrections", body: "Respond to Building Development Services with a numbered calculation or detail, identify related civil and MEP changes, and state what remains field-verified." },
    ],
    permitSteps: [
      "Confirm Springfield jurisdiction, occupancy, zoning, adopted code, flood status, wind criteria, and required structural documents.",
      "Collect survey, soil or rock recommendations, framing exposures, existing permit information, roof loads, and equipment loads.",
      "Coordinate foundations, retaining, connectors, openings, shoring, utility penetrations, and special inspections with the complete permit set.",
      "Track each correction and obtain responsible-PE review of revised calculations and field discoveries before resubmission.",
    ],
    faqs: [
      { question: "Can a Springfield footing assume uniform rock?", answer: "No. Rock depth, weathering, clay, voids, and fill can vary; site evidence should support the bearing and excavation approach." },
      { question: "Does a Springfield ADU change structural scope?", answer: "It may add foundation, roof, lateral, fire-separation, service, or grading demands; the building scope and site evidence determine the documents." },
      { question: "Are severe-wind details interchangeable with another Missouri city?", answer: "Design criteria and exposure are project-specific, so the adopted local requirements and the actual building geometry should control." },
    ],
    sources: springfieldSources,
  },
  {
    serviceSlug: "mep-engineering",
    title: "Springfield MEP engineering for additions and fit-outs",
    description: "Springfield MEP design for homes, commercial alterations, and ADUs coordinated with City Utilities and local review.",
    h1: "MEP Engineering for Springfield, Missouri",
    kicker: "Springfield utility capacity, ventilation, and service coordination",
    lede: "Springfield MEP plans need measured service conditions, Ozark weather, occupancy loads, and City Utilities interfaces before equipment is finalized.",
    permitAuthority: "Springfield Building Development Services reviews the building package; City Utilities, fire, planning, and public works can have separate requirements.",
    codeContext: "Verify adopted mechanical, plumbing, electrical, energy, fire, accessibility, and alteration requirements with the city before selecting the compliance route.",
    localConditions: "Hot humid summers, winter ice, severe storms, rolling sites, variable water pressure, and older service equipment influence system design.",
    projectTypes: "Commercial fit-outs, residential additions, detached ADUs, multifamily renovations, and occupied remodeling",
    sections: [
      { heading: "City Utilities data first", body: "Record electrical service, gas or fuel arrangements, water pressure, sewer points, and fire-flow information before finalizing panels, equipment, and risers." },
      { heading: "Ventilation in a changing climate", body: "Cooling, humidity, filtration, outdoor air, condensate, freeze protection, and controls should reflect occupancy and maintenance access rather than a copied schedule." },
      { heading: "ADU and addition interfaces", body: "An added dwelling can change panel load, water demand, sewer flow, fire separation, and HVAC zoning. Keep those links visible in the coordinated permit set." },
    ],
    permitSteps: [
      "Confirm Springfield occupancy, adopted mechanical, plumbing, electrical, energy, fire, and accessibility requirements with Building Development Services.",
      "Field-trace existing systems and request current electric, gas, water, sewer, and fire-flow information from City Utilities or the responsible provider.",
      "Coordinate equipment, risers, shafts, condensate, controls, clearances, panel schedules, and shutdown phases with the other disciplines.",
      "Answer comments with revised schedules, calculations, risers, and utility records tied to the plan-check response.",
    ],
    faqs: [
      { question: "Does a Springfield ADU require a new electrical service?", answer: "Not in every case. Connected load, service capacity, metering, utility rules, and the AHJ's documentation request determine the arrangement." },
      { question: "How should karst affect MEP site work?", answer: "Utility trenches, drainage, sewer connections, and equipment pads should follow surveyed grades and site recommendations rather than an assumed subsurface profile." },
      { question: "Can the contractor resolve an MEP comment in the field?", answer: "A change affecting permitted loads, distribution, equipment, or life safety should be reviewed and documented through the design and permit process." },
    ],
    sources: springfieldSources,
  },
  {
    serviceSlug: "civil-engineering",
    title: "Springfield civil engineering for rolling sites",
    description: "Springfield civil plans for grading, drainage, access, utilities, and small development tied to local public works review.",
    h1: "Civil Engineering for Springfield, Missouri",
    kicker: "Springfield grades, karst drainage, and utility connections",
    lede: "Springfield civil work shows how a building pad, driveway, drainage route, and utility connection fit rolling Ozark terrain and public infrastructure.",
    permitAuthority: "Springfield Planning and Zoning and Building Development Services administer local development review; Public Works, flood, and utility offices may review specific elements.",
    codeContext: "Check current Springfield zoning, site-development, stormwater, right-of-way, erosion, accessibility, flood, and utility requirements for the address.",
    localConditions: "Rolling grades, clay over rock, karst, flash runoff, creek corridors, ice, and constrained residential rights-of-way make grading evidence important.",
    projectTypes: "Infill lots, residential additions, detached ADUs, parking changes, commercial sites, and neighborhood access work",
    sections: [
      { heading: "Survey the whole drainage path", body: "Show spot grades, drainage divides, inlets, ditches, easements, utilities, finished floors, accessible routes, fire access, and the receiving system." },
      { heading: "Karst and flash runoff", body: "A nearby sink, ditch, or channel is not automatically a safe outfall. Document infiltration assumptions, overflow, erosion protection, and downstream ownership." },
      { heading: "Small lots still have interfaces", body: "An ADU, addition, or new driveway can change roof runoff, sewer demand, access, and easement use; include those changes even without a subdivision." },
    ],
    permitSteps: [
      "Confirm Springfield zoning, Public Works, stormwater, flood, right-of-way, erosion, and access thresholds for the address.",
      "Verify survey control, utilities, easements, finished floors, receiving drainage, outfall ownership, soil, and infiltration evidence.",
      "Lay out Springfield contours, karst-sensitive drainage, utility profiles, accessible routes, fire access, and construction controls as one site package.",
      "Respond to each agency correction with revised contours, profiles, details, calculations, and identified maintenance duties.",
    ],
    faqs: [
      { question: "Can a Springfield lot use a roadside ditch as its outfall?", answer: "Only after ownership, capacity, grade, erosion, right-of-way, and agency acceptance are verified for that location." },
      { question: "Does a detached ADU always need a full civil plan?", answer: "No single answer applies; added impervious area, grading, flood exposure, utilities, access, and the city checklist establish the scope." },
      { question: "Why does rock matter to a Springfield drainage plan?", answer: "Rock can limit infiltration, affect utility excavation and outlets, and change erosion or retaining details, so the site record should support the method." },
    ],
    sources: springfieldSources,
  },
  {
    serviceSlug: "energy-compliance",
    title: "Springfield energy compliance for Ozark additions",
    description: "Springfield energy documentation for homes, renovations, and tenant work aligned with adopted provisions and coordinated HVAC details.",
    h1: "Energy Compliance for Springfield, Missouri",
    kicker: "Springfield envelope and equipment documentation",
    lede: "Springfield energy compliance ties envelope, HVAC, lighting, controls, and water heating to the local adopted method and the actual alteration scope.",
    permitAuthority: "Springfield Building Development Services identifies the energy submittal route and reviews the building documents with the applicable adopted provisions.",
    codeContext: "Establish Springfield's locally adopted energy edition, climate inputs, residential or commercial method, alteration classification, forms, and inspection expectations before modeling.",
    localConditions: "Hot humid summers, cold winters, ice, severe weather, solar exposure, and variable older assemblies influence envelope and equipment inputs.",
    projectTypes: "Residential additions, ADUs, commercial alterations, multifamily renovations, and new interior build-outs",
    sections: [
      { heading: "Assemblies must match construction", body: "List insulation, air sealing, windows, shading, roofs, walls, and thermal bridges as they will actually be detailed and built, including rock or slab interfaces." },
      { heading: "HVAC and moisture balance", body: "Cooling, heating, outdoor air, filtration, controls, and condensate schedules should agree with the MEP design and the occupancy's humidity loads." },
      { heading: "Plan-check changes", body: "When a window, wall, lighting fixture, or HVAC selection changes, update the energy inputs and the affected architectural and MEP documents together." },
    ],
    permitSteps: [
      "Confirm Springfield's current energy edition, climate data, alteration category, compliance method, and required forms.",
      "Collect verified envelope, fenestration, HVAC, lighting, water-heating, control, and equipment information from the coordinated plans.",
      "Cross-check the model or forms against structural penetrations, architectural assemblies, MEP schedules, and procurement limitations.",
      "Respond to each correction with the cited provision, revised input or form, and coordinated sheet reference.",
    ],
    faqs: [
      { question: "Is a Springfield addition automatically on the new-construction energy path?", answer: "No. The alteration category, size, connected systems, current provisions, and local review instructions determine the documentation." },
      { question: "Does an energy model approve the installed equipment?", answer: "It documents the selected compliance inputs; installed equipment and field changes still need to match the approved design or be reviewed." },
      { question: "How do rock or slab conditions affect energy details?", answer: "They can change slab edges, insulation continuity, moisture control, and penetrations, which should be reflected in both the modeled assembly and drawings." },
    ],
    sources: springfieldSources,
  },
  {
    serviceSlug: "pe-stamped-drawings",
    title: "Springfield PE-stamped drawings for local permits",
    description: "Springfield sealed engineering packages defining scope, site evidence, agency interfaces, and correction control.",
    h1: "PE-Stamped Drawings for Springfield, Missouri",
    kicker: "Springfield responsible-charge and permit records",
    lede: "A Springfield sealed package should make the engineering scope, site assumptions, and response to Building Development Services comments easy to trace.",
    permitAuthority: "Springfield Building Development Services reviews the applicable set; Planning and Zoning, Public Works, fire, flood, and City Utilities retain separate roles.",
    codeContext: "Confirm the local checklist, adopted codes, seal format, special inspections, energy documents, and discipline-specific requirements before sealing; verify the responsible PE's Missouri board obligations.",
    localConditions: "Karst, rock, rolling grades, flash runoff, older services, severe weather, and hidden remodeling can create evidence and coordination limits.",
    projectTypes: "Residential permits, commercial alterations, additions, ADUs, site work, and public-facing improvements",
    sections: [
      { heading: "Scope that the seal actually covers", body: "State the Springfield parcel, occupancy, code route, survey, soil and drainage assumptions, calculations, sheets, exclusions, and responsible discipline." },
      { heading: "City Utilities and site interfaces", body: "Utility responses, survey, geotechnical recommendations, fire access, flood information, and public works requirements may be dependencies rather than PE observations." },
      { heading: "Corrections remain controlled", body: "Use a dated matrix linking each reviewer comment, RFI, substitution, and field discovery to the responsible PE's decision and any changed document." },
    ],
    permitSteps: [
      "Identify Springfield's enforcing office, occupancy, code path, discipline boundary, checklist, and required seal presentation.",
      "Assemble current survey, field, soil, flood, drainage, utility, calculation, and consultant records supporting the defined scope.",
      "Before Springfield submission, the responsible PE should reconcile surveyed grades, karst or rock evidence, utility penetrations, and the complete sealed drawing and calculation record.",
      "Route plan-check and construction changes back through the PE and issue revised sealed sheets only where the professional scope changes.",
    ],
    faqs: [
      { question: "Does a Springfield PE seal replace City Utilities review?", answer: "No. A seal covers a defined professional scope; City Utilities and city departments make their own service and permit decisions." },
      { question: "Can a PE seal a plan based only on a typical Ozark soil profile?", answer: "The professional should obtain enough parcel-specific evidence to exercise independent judgment and identify any remaining limitations." },
      { question: "Who decides if a correction changes the sealed set?", answer: "The responsible PE evaluates the engineering impact, while the city reviewer decides what must be resubmitted for the permit." },
    ],
    sources: [...springfieldSources, missouriEngineeringBoardSource],
  },
];

const columbia: Service[] = [
  {
    serviceSlug: "structural-engineering",
    title: "Columbia structural engineering for infill and additions",
    description: "Structural design for Columbia homes, university-area infill, and commercial alterations with site-specific foundations and review.",
    h1: "Structural Engineering for Columbia, Missouri",
    kicker: "Columbia foundations, infill, and freeze-thaw load paths",
    lede: "Columbia structural design must account for limestone or clay, changing grades, older housing, and the precise interface between an addition and existing work.",
    permitAuthority: "Columbia Community Development is the local building contact; planning, fire, Public Works, flood, and utility reviews can be separate.",
    codeContext: "Use Columbia Community Development's current adopted-code direction to establish the residential or commercial path, occupancy, wind, snow, fire, energy, and inspection documents.",
    localConditions: "Limestone and clay, creek floodplains, university-area infill, rolling grades, freeze-thaw, ice, and intense storms affect foundations and connections.",
    projectTypes: "Infill housing, residential additions, detached ADUs, tenant alterations, multifamily work, and accessory structures",
    sections: [
      { heading: "Existing Columbia buildings", body: "Verify framing, footings, masonry, crawlspaces, prior openings, and utility penetrations before assuming an older house or infill building has a continuous load path." },
      { heading: "Limestone, clay, and creek corridors", body: "Bearing, drainage, finished floors, retaining, and flood information should be coordinated where variable soil or creek elevation meets a new foundation." },
      { heading: "Community Development corrections", body: "Tie every comment to a revised calculation or detail and identify impacts on grading, fire separation, MEP openings, and the architectural permit sheets." },
    ],
    permitSteps: [
      "Confirm Columbia jurisdiction, zoning, occupancy, adopted code, flood status, wind and snow criteria, and structural checklist.",
      "Collect survey, geotechnical or soil information, framing exposures, existing permit records, and new architectural and MEP loads.",
      "Coordinate foundations, retaining, connectors, openings, shoring, rooftop equipment, and special-inspection notes before submission.",
      "Respond to each plan-check correction with a revised document and route field-dependent changes through the responsible PE.",
    ],
    faqs: [
      { question: "Does Columbia limestone guarantee adequate bearing?", answer: "No. Rock quality, depth, clay, fill, weathering, and excavation conditions vary; parcel evidence should support the foundation design." },
      { question: "Can an addition share a Columbia crawlspace foundation?", answer: "Only after existing geometry, condition, new reactions, differential movement, drainage, and the AHJ's requested documentation are evaluated." },
      { question: "Are university-area infill loads predictable from neighboring projects?", answer: "No. Adjacent sites can have different fill, grades, occupancy, and framing; use the actual parcel and building record." },
    ],
    sources: columbiaSources,
  },
  {
    serviceSlug: "mep-engineering",
    title: "Columbia MEP engineering for mixed-use and residential work",
    description: "Columbia MEP design for tenant improvements, multifamily work, additions, and ADUs coordinated with Water and Light.",
    h1: "MEP Engineering for Columbia, Missouri",
    kicker: "Columbia utility, occupancy, and building-system coordination",
    lede: "Columbia MEP work connects Water and Light information, actual occupancy, ventilation, and winter operation to a coordinated permit package.",
    permitAuthority: "Columbia Community Development reviews the building set; Water and Light, fire, planning, and Public Works may impose separate requirements.",
    codeContext: "Verify current mechanical, plumbing, electrical, energy, fire, accessibility, and alteration requirements with Columbia reviewers.",
    localConditions: "Humid summers, cold winters, ice, university-area occupancy shifts, aging services, creek flood exposure, and intense storms shape system design.",
    projectTypes: "Mixed-use fit-outs, student-area renovations, multifamily buildings, commercial interiors, additions, and ADUs",
    sections: [
      { heading: "Water and Light capacity", body: "Record panel and meter arrangements, water pressure, sewer points, gas or fuel service, and fire-flow information before final equipment and riser schedules." },
      { heading: "Occupancy-driven ventilation", body: "Student housing, restaurants, offices, and homes have different outdoor-air, controls, filtration, condensate, and equipment-access needs; schedules should state the actual use." },
      { heading: "Plan-check coordination", body: "A service, fire, or energy correction can move shafts, panels, structure, and architectural clearances. Update all affected sheets and calculations together." },
    ],
    permitSteps: [
      "Confirm Columbia occupancy, adopted mechanical, plumbing, electrical, energy, fire, and accessibility provisions for the project.",
      "Field-verify existing systems and obtain current Water and Light, sewer, electric, gas, and fire-flow information where applicable.",
      "Coordinate Columbia risers, equipment, condensate, controls, clearances, panel schedules, metering, shutdowns, and maintenance access with the occupancy plan.",
      "Return numbered corrections with revised schedules, risers, calculations, and utility correspondence tied to affected documents.",
    ],
    faqs: [
      { question: "Does a Columbia ADU need a separate utility meter?", answer: "Metering and service depend on the project arrangement, connected loads, Water and Light requirements, and the city's permit review—not the ADU label alone." },
      { question: "Why does occupancy matter to Columbia MEP design?", answer: "Occupancy controls ventilation, plumbing demand, equipment sizing, controls, fire interfaces, and often the applicable code path." },
      { question: "Can a plan-check response leave the original MEP schedule unchanged?", answer: "If the comment changes a load, system, or equipment assumption, the schedule and related drawings should be revised so the set remains internally consistent." },
    ],
    sources: columbiaSources,
  },
  {
    serviceSlug: "civil-engineering",
    title: "Columbia civil engineering for creek and infill sites",
    description: "Columbia civil plans for grading, drainage, access, utilities, and university-area infill coordinated with local review.",
    h1: "Civil Engineering for Columbia, Missouri",
    kicker: "Columbia grades, creek corridors, and utility plans",
    lede: "A Columbia civil package should show how a building, driveway, drainage route, and utility connection work on the surveyed parcel and its receiving system.",
    permitAuthority: "Columbia Community Development and Planning review development documents; Public Works, flood, zoning, and utilities may review specific site elements.",
    codeContext: "Check current Columbia zoning, land-development, stormwater, right-of-way, erosion, accessibility, flood, and utility requirements at the address.",
    localConditions: "Rolling terrain, limestone and clay, creek floodplains, university infill, intense rain, ice, and constrained alleys affect site design.",
    projectTypes: "Infill lots, student-area additions, detached ADUs, parking changes, commercial sites, and small public-facing improvements",
    sections: [
      { heading: "Columbia survey and receiving routes", body: "Show spot grades, drainage divides, inlets, creeks, easements, utilities, finished floors, accessible routes, fire access, and the permitted outfall." },
      { heading: "Creek and lot-scale drainage", body: "A new impervious area can redirect water toward a basement, neighboring parcel, or creek. Document overflow, erosion protection, flood information, and maintenance." },
      { heading: "University-area interfaces", body: "Infill can affect parking, fire access, alleys, utilities, and construction staging. Coordinate those practical constraints with zoning and Public Works review." },
    ],
    permitSteps: [
      "Confirm Columbia planning, zoning, Public Works, stormwater, flood, right-of-way, erosion, and access thresholds for the parcel.",
      "Verify Independence survey control, utility crossings, easements, finished floors, flood information, receiving system, outfall ownership, and soil assumptions.",
      "Reconcile Columbia parking and creek grades with drainage calculations, utility profiles, accessible routes, fire access, and construction staging.",
      "Answer corrections with revised contours, profiles, calculations, details, and maintenance responsibilities linked to each comment.",
    ],
    faqs: [
      { question: "Can Columbia creek frontage serve as a drainage outfall?", answer: "Not without checking ownership, flood and erosion constraints, grade, capacity, permits, and the responsible reviewing agencies." },
      { question: "Does adding a Columbia parking space affect civil review?", answer: "It can change grading, stormwater, access, setbacks, drainage, and right-of-way work, so the local checklist should be consulted." },
      { question: "Why show finished floor elevation on a small Columbia addition?", answer: "It helps demonstrate positive drainage and identify flood, basement, accessibility, and tie-in relationships at the existing building." },
    ],
    sources: columbiaSources,
  },
  {
    serviceSlug: "energy-compliance",
    title: "Columbia energy compliance for infill and renovation",
    description: "Columbia energy documentation for additions and tenant work coordinated with envelope, HVAC, lighting, and adopted provisions.",
    h1: "Energy Compliance for Columbia, Missouri",
    kicker: "Columbia envelope and occupancy-specific energy records",
    lede: "Columbia energy compliance should follow the adopted method and the actual infill or alteration scope, with building and MEP documents using the same inputs.",
    permitAuthority: "Columbia Community Development identifies the applicable building and energy review path and can clarify required forms and calculations.",
    codeContext: "Confirm current Columbia energy provisions, climate inputs, residential or commercial method, alteration treatment, and submittal forms before modeling.",
    localConditions: "Humid summers, cold winters, ice, solar gain, older housing, mixed-use occupancy, and creek moisture exposure affect envelope and equipment choices.",
    projectTypes: "Student-area renovations, commercial tenant work, residential additions, ADUs, multifamily alterations, and infill buildings",
    sections: [
      { heading: "Infill envelope continuity", body: "Document walls, roofs, windows, shading, air barriers, insulation, and slab or foundation interfaces so the compliance record matches the construction details." },
      { heading: "Mixed-use HVAC inputs", body: "Different uses may require separate schedules for ventilation, cooling, heating, controls, filtration, lighting, and service water; do not blend them into one generic model." },
      { heading: "Corrections tied to drawings", body: "When glazing, assemblies, fixtures, or equipment change during plan check, update the compliance input and each affected architectural or MEP detail." },
    ],
    permitSteps: [
      "Confirm Columbia's current energy edition, climate data, alteration category, selected method, and required submittal forms.",
      "Collect verified envelope, fenestration, shading, HVAC, lighting, water-heating, control, and equipment data for each occupancy.",
      "Cross-check the energy record against architectural assemblies, structural penetrations, MEP schedules, and actual procurement selections.",
      "Answer every energy comment with its cited requirement, revised input or form, and coordinated drawing reference.",
    ],
    faqs: [
      { question: "Is a Columbia ADU treated as a new building for energy purposes?", answer: "The applicable treatment depends on the connected scope, alteration provisions, systems, and current Community Development direction." },
      { question: "Can one model cover a Columbia mixed-use building?", answer: "A method may permit a combined submission, but occupancy-specific inputs and separate systems should not be hidden in an averaged assumption." },
      { question: "What does an energy correction need beyond a narrative?", answer: "When an input or assembly changes, provide the revised form or calculation and update the referenced construction and equipment drawings." },
    ],
    sources: columbiaSources,
  },
  {
    serviceSlug: "pe-stamped-drawings",
    title: "Columbia PE-stamped drawings for site-specific permits",
    description: "Columbia sealed engineering documents defining design scope, parcel evidence, agency interfaces, and correction tracking.",
    h1: "PE-Stamped Drawings for Columbia, Missouri",
    kicker: "Columbia professional scope and coordinated revisions",
    lede: "A Columbia sealed set should show the site facts, design criteria, discipline boundary, and correction record without presenting a seal as approval.",
    permitAuthority: "Columbia Community Development reviews the applicable permit set; Planning, Public Works, flood, fire, and Water and Light retain separate authority.",
    codeContext: "Confirm the Columbia checklist, adopted code and energy provisions, seal presentation, special inspections, and discipline documents; check Missouri board requirements for the responsible PE's seal.",
    localConditions: "Limestone and clay, creek floodplains, university infill, rolling grades, older utilities, and intense storms can require verified consultant information.",
    projectTypes: "Infill permits, additions, tenant improvements, ADUs, grading packages, and small public improvements",
    sections: [
      { heading: "Columbia scope and assumptions", body: "Identify the parcel, occupancy, code route, survey, soil and flood assumptions, calculations, drawings, exclusions, and responsible discipline before sealing." },
      { heading: "Agency information is not a seal", body: "Survey, geotechnical, utility, fire, flood, zoning, and Public Works inputs may come from separate sources; preserve their limits and dates in the record." },
      { heading: "A usable correction matrix", body: "Link each plan-check comment, RFI, substitution, or field discovery to the affected sheet, calculation, consultant dependency, and responsible PE decision." },
    ],
    permitSteps: [
      "Identify Columbia's enforcing office, occupancy, code path, discipline boundary, checklist, seal format, and related agency reviews.",
      "Bring Columbia's survey, creek and flood information, field notes, soil, drainage, utility, calculations, and consultant records into the defined design file.",
      "Before Columbia submission, the responsible PE should reconcile creek, infill, utility, and occupancy interfaces across the plans, details, notes, schedules, and calculations.",
      "Route corrections and construction changes through the PE and issue revised sealed documents only where the professional scope is affected.",
    ],
    faqs: [
      { question: "Does a Columbia PE seal approve a floodplain or utility connection?", answer: "No. A PE seal covers the identified engineering scope; Columbia and the applicable utility or flood authority decide their own approvals." },
      { question: "Can a PE rely on a university-area typical detail?", answer: "Typical details can inform design but do not replace parcel-specific survey, soil, existing-condition, code, and utility evidence." },
      { question: "What should happen when a field condition differs from the set?", answer: "Pause the affected work, document the condition, and have the responsible PE determine whether calculations, details, or permit documents require revision." },
    ],
    sources: [...columbiaSources, missouriEngineeringBoardSource],
  },
];

const independence: Service[] = [
  {
    serviceSlug: "structural-engineering",
    title: "Independence structural engineering for older neighborhoods",
    description: "Structural design for Independence additions, renovations, and infill with clay, loess, flooding, and local review coordination.",
    h1: "Structural Engineering for Independence, Missouri",
    kicker: "Independence foundations, older framing, and storm load paths",
    lede: "Independence structural work must connect older neighborhood construction to current loads, variable clay and loess, and the actual parcel drainage record.",
    permitAuthority: "Independence Building Inspections is the building permit contact; Development Services, Public Works, flood, fire, and utilities may review separate items.",
    codeContext: "Independence Building Inspections should identify the applicable building and residential provisions, local amendments, occupancy, severe-weather criteria, energy path, and inspection notes.",
    localConditions: "Rolling clay and loess, older foundations, Blue River flooding, ice, freeze-thaw, and severe storms affect settlement and lateral details.",
    projectTypes: "Older-home additions, detached ADUs, commercial renovations, infill buildings, accessory structures, and repairs",
    sections: [
      { heading: "Older neighborhood evidence", body: "Measure framing, footings, crawlspaces, masonry, previous openings, and roof additions before assuming a continuous load path in an older Independence building." },
      { heading: "Clay, loess, and Blue River exposure", body: "Foundation details should coordinate soil recommendations, finished floors, flood information, drainage, retaining, and moisture-sensitive construction." },
      { heading: "Building Inspections corrections", body: "Identify the exact calculation or detail changed by each comment and coordinate structural revisions with grading, fire separation, MEP penetrations, and architecture." },
    ],
    permitSteps: [
      "Confirm Independence jurisdiction, occupancy, zoning, adopted code, flood status, severe-weather criteria, and structural checklist.",
      "Gather survey, soil or geotechnical information, framing exposures, prior permit records, new loads, and existing-condition photographs.",
      "Coordinate foundations, retaining, connectors, openings, shoring, equipment, fire-rated interfaces, and special inspections.",
      "Track every correction and have the responsible PE review revised calculations and field discoveries before resubmission.",
    ],
    faqs: [
      { question: "Can an Independence addition rely on an older footing without testing?", answer: "Only after its condition, geometry, soil, existing and new reactions, drainage, and the requested permit evidence are evaluated." },
      { question: "Does Blue River flood information affect structural design?", answer: "It can affect finished floors, foundations, materials, utilities, and civil-structural coordination; the parcel's current flood record should control." },
      { question: "Are clay and loess foundation details interchangeable?", answer: "No. Thickness, moisture, fill, and bearing behavior vary by site, so a neighboring detail is not a substitute for project evidence." },
    ],
    sources: independenceSources,
  },
  {
    serviceSlug: "mep-engineering",
    title: "Independence MEP engineering for renovations and ADUs",
    description: "Independence MEP design for occupied renovations, additions, and ADUs coordinated with city utilities and plan review.",
    h1: "MEP Engineering for Independence, Missouri",
    kicker: "Independence service capacity and older-building systems",
    lede: "Independence MEP planning needs real service measurements, utility requirements, occupancy loads, and weather controls for the building being changed.",
    permitAuthority: "Independence Building Inspections reviews the building set; Development Services, Power and Light, Water, fire, and Public Works may review separate interfaces.",
    codeContext: "Verify current mechanical, plumbing, electrical, energy, fire, accessibility, and existing-building requirements with the city.",
    localConditions: "Older services, humid summers, winter ice, severe storms, rolling lots, variable water pressure, and flood-sensitive low areas influence system design.",
    projectTypes: "Home additions, detached ADUs, tenant improvements, multifamily renovations, occupied remodels, and small commercial work",
    sections: [
      { heading: "Existing service verification", body: "Field-trace panels, meters, water, sewer, gas or fuel, ventilation, and fire systems before selecting equipment or promising that an existing connection can be reused." },
      { heading: "Weather and maintenance details", body: "Schedules should account for heating and cooling, outdoor air, filtration, condensate, freeze protection, controls, clearances, and practical maintenance access." },
      { heading: "ADU coordination", body: "An ADU can alter electric load, water demand, sewer flow, fire separation, ventilation, and access. Show those links across the architectural and MEP documents." },
    ],
    permitSteps: [
      "Confirm Independence occupancy, adopted mechanical, plumbing, electrical, energy, fire, accessibility, and alteration requirements.",
      "Field-verify existing equipment and request current Power and Light, Water, sewer, gas, and fire-flow information where applicable.",
      "Coordinate equipment, risers, condensate, controls, clearances, panel schedules, metering, shutdowns, and service access.",
      "Answer plan-check comments with revised load calculations, schedules, risers, and provider records tied to the affected sheets.",
    ],
    faqs: [
      { question: "Can an Independence ADU share the main home's utility services?", answer: "It may, but connected load, water and sewer capacity, metering, fire separation, and city or provider requirements must be verified." },
      { question: "What if the existing panel label in an older home is unreliable?", answer: "Field verification and load assessment should precede design; an uncertain label should not be treated as a confirmed service capacity." },
      { question: "Does a utility capacity letter complete the MEP permit?", answer: "No. It informs the service interface while the MEP package still documents loads, distribution, equipment, controls, and code compliance." },
    ],
    sources: independenceSources,
  },
  {
    serviceSlug: "civil-engineering",
    title: "Independence civil engineering for Blue River drainage",
    description: "Independence civil plans for grading, drainage, access, utilities, and older-neighborhood site changes.",
    h1: "Civil Engineering for Independence, Missouri",
    kicker: "Independence grades, Blue River flood routes, and public works",
    lede: "Independence civil plans should connect the surveyed parcel to streets, easements, utilities, and a lawful drainage route without assuming an old neighborhood grade is adequate.",
    permitAuthority: "Independence Development Services and Public Works administer site review; Building Inspections, floodplain, zoning, fire, and utilities may review distinct elements.",
    codeContext: "Check current Independence zoning, site-development, stormwater, right-of-way, erosion, accessibility, floodplain, and utility requirements.",
    localConditions: "Rolling clay and loess, older streets and alleys, Blue River flood exposure, intense storms, ice, and constrained outfalls affect grading.",
    projectTypes: "Residential additions, detached ADUs, infill lots, parking changes, commercial frontage, and neighborhood drainage work",
    sections: [
      { heading: "Parcel to public system", body: "Show spot grades, curb and alley elevations, inlets, manholes, easements, utilities, finished floors, accessible paths, fire access, and the actual receiving route." },
      { heading: "Blue River and low-lot runoff", body: "A small addition can direct water toward a basement, neighboring lot, or flood-sensitive area. Document overflow, finished-floor relationship, erosion, and maintenance." },
      { heading: "Older infrastructure checks", body: "An existing inlet, culvert, or sewer connection may have a different owner or capacity than expected. Confirm the interface with Public Works and the utility." },
    ],
    permitSteps: [
      "Confirm Independence zoning, Development Services, Public Works, floodplain, stormwater, right-of-way, erosion, and access thresholds.",
      "Verify current survey, utilities, easements, finished floors, flood information, receiving system, outfall ownership, and soil assumptions.",
      "Coordinate grading, drainage calculations, profiles, utility connections, accessible routes, fire access, parking, and construction protection.",
      "Respond to each correction with revised contours, profiles, calculations, details, and maintenance responsibility notes.",
    ],
    faqs: [
      { question: "Can an Independence property drain to an existing roadside ditch?", answer: "The city, property rights, ditch capacity, grade, erosion controls, and downstream responsibility must be confirmed before using that route." },
      { question: "Does a driveway change require civil coordination?", answer: "It can affect grade, sight distance, drainage, right-of-way, access, utilities, and flood behavior, so the local review criteria should be checked." },
      { question: "Why are finished floors important near the Blue River?", answer: "They help relate the building to overland flow, flood information, basement risk, positive drainage, and utility entry elevations." },
    ],
    sources: independenceSources,
  },
  {
    serviceSlug: "energy-compliance",
    title: "Independence energy compliance for older-home additions",
    description: "Independence energy documentation for renovations, additions, and ADUs coordinated with the adopted code and actual assemblies.",
    h1: "Energy Compliance for Independence, Missouri",
    kicker: "Independence envelope, HVAC, and alteration records",
    lede: "Independence energy work documents the selected compliance route and the real envelope, equipment, lighting, and control conditions of an older building or addition.",
    permitAuthority: "Independence Building Inspections identifies the building and energy submittal route and reviews the applicable code documentation.",
    codeContext: "For Independence, confirm the adopted energy edition, existing-building treatment, climate inputs, selected residential or commercial method, forms, and inspection instructions.",
    localConditions: "Older walls and windows, clay-lot moisture, humid summers, cold winters, ice, severe storms, and solar exposure affect energy inputs.",
    projectTypes: "Older-home additions, detached ADUs, commercial renovations, multifamily alterations, and tenant improvements",
    sections: [
      { heading: "Existing assemblies first", body: "Record wall, roof, window, air-sealing, insulation, shading, and slab or crawlspace conditions before selecting a method for the alteration." },
      { heading: "HVAC, moisture, and controls", body: "Heating, cooling, ventilation, filtration, condensate, controls, and lighting schedules should agree with the actual occupancy and the MEP design." },
      { heading: "Plan-check and procurement changes", body: "A changed window, insulation assembly, light, or equipment selection should trigger a coordinated input check rather than a stale compliance form." },
    ],
    permitSteps: [
      "Ask Independence Building Inspections to identify the effective energy edition, climate data, alteration category, compliance method, and forms for this older-building scope.",
      "Collect verified existing and proposed assemblies, windows, shading, HVAC, lighting, water-heating, control, and equipment information.",
      "Cross-check inputs against architectural details, structural penetrations, MEP schedules, and field installation constraints.",
      "For Independence energy comments, cite the requirement, revise the form or input, and point reviewers to each coordinated drawing change.",
    ],
    faqs: [
      { question: "Is an Independence detached ADU automatically treated as an addition?", answer: "The applicable path depends on its connected systems, scope, current energy provisions, and the Building Inspections review." },
      { question: "Can an older wall be modeled as a typical wood frame?", answer: "Only if field evidence supports that assembly; existing construction, air movement, insulation, and moisture conditions should be documented." },
      { question: "What does a correction response do when a window changes?", answer: "It updates the fenestration input and the referenced plans, details, schedules, and calculations so the permitted record remains coordinated." },
    ],
    sources: independenceSources,
  },
  {
    serviceSlug: "pe-stamped-drawings",
    title: "Independence PE-stamped drawings for permit review",
    description: "Independence sealed engineering sets defining scope, existing conditions, utility interfaces, and correction control.",
    h1: "PE-Stamped Drawings for Independence, Missouri",
    kicker: "Independence accountable scope and revision records",
    lede: "An Independence sealed package should make its engineering responsibility, parcel evidence, and response to city comments clear without implying guaranteed approval.",
    permitAuthority: "Independence Building Inspections reviews the building set; Development Services, Public Works, floodplain, fire, and utility authorities retain separate roles.",
    codeContext: "Confirm the local checklist, adopted codes and energy provisions, seal presentation, special inspections, and discipline-specific documents; verify Missouri board requirements before the responsible PE seals.",
    localConditions: "Older construction, clay and loess, Blue River flood exposure, constrained rights-of-way, aging utilities, and severe storms can limit assumptions.",
    projectTypes: "Addition permits, ADUs, older-building renovations, commercial fit-outs, civil interfaces, and accessory structures",
    sections: [
      { heading: "Document the defined scope", body: "For Independence, state the parcel, occupancy, code path, observed conditions, soil and flood limits, calculations, drawings, exclusions, and each responsible discipline." },
      { heading: "Separate public and utility decisions", body: "Public Works, Development Services, floodplain, fire, Power and Light, Water, survey, and geotechnical inputs may remain separate from the PE's professional scope." },
      { heading: "Revision accountability", body: "Use a dated matrix linking each correction, substitution, RFI, and field condition to the affected document and the responsible PE's review." },
    ],
    permitSteps: [
      "For Independence, document the enforcing office, occupancy, code route, discipline boundary, checklist, seal format, and related agency reviews.",
      "Build the Independence evidence file from measured existing conditions, survey control, flood and drainage records, soil information, utility responses, calculations, and consultant limits.",
      "Before Independence submission, the responsible PE should review older-building observations, flood and soil assumptions, drawings, details, schedules, and calculations as one record.",
      "Route plan-check and construction changes back through the PE and issue revised sealed documents only for affected professional work.",
    ],
    faqs: [
      { question: "Does an Independence PE seal replace floodplain approval?", answer: "No. The seal identifies responsibility for defined engineering work; the city's floodplain and building reviewers determine their requirements." },
      { question: "Can a PE seal an older home's framing from photographs alone?", answer: "Photographs may inform the record but do not automatically verify concealed members or connections; the PE should identify limits and obtain adequate evidence." },
      { question: "Who decides whether a stamped revision is needed?", answer: "The responsible PE evaluates the engineering effect, while Independence Building Inspections determines the permit submittal or revision requirement." },
    ],
    sources: [...independenceSources, missouriEngineeringBoardSource],
  },
];

const missouriBatch4: Batch2StateExpansion = {
  stateSlug: "missouri",
  stateName: "Missouri",
  stateAbbrev: "MO",
  hub: {
    title: "Missouri engineering permit coordination",
    description: "Site-specific structural, MEP, civil, energy, and PE-scope coordination for Missouri permit work.",
    h1: "Engineering Permit Coordination Across Missouri",
    kicker: "Missouri city, county, utility, and site review",
    lede: "Missouri permit requirements are administered locally. Start with the address, enforcing authority, adopted code, survey, flood information, utility interfaces, and the actual alteration scope.",
    sections: [
      { heading: "Local code administration", body: "Kansas City, St. Louis, Springfield, Columbia, Independence, and surrounding counties use different review routes, amendments, zoning decisions, fire procedures, and site requirements. Confirm the enforcing office before design documents are finalized." },
      { heading: "Ground, water, and weather", body: "River floodplains, loess, clay, Ozark karst, limestone, urban fill, ice, freeze-thaw, severe rain, and tornado wind are not uniform statewide design assumptions. Survey, geotechnical, flood, and drainage evidence belong in the project record." },
      { heading: "Utilities and public agencies", body: "Municipal water and power departments, Evergy, Ameren Missouri, public works, fire authorities, Missouri DNR, and FEMA information can govern separate portions of a permit. A utility or seal does not replace another agency's review." },
      { heading: "Additions, ADUs, and corrections", body: "An addition or ADU can change foundations, service capacity, sewer, drainage, energy, fire separation, occupancy, and access. Track each plan-check correction to the revised sheet, calculation, utility response, or field decision that resolves it." },
      { heading: "Transportation and right-of-way interfaces", body: "A site plan is not necessarily approval to change a driveway, sidewalk, curb, drainage inlet, or state-route frontage. Missouri Department of Transportation may control access or work within its right of way, while a city or county public-works office may review local streets, traffic sight distance, construction access, and utility cuts. Identify the road owner and any access, encroachment, or frontage submittal before the civil set is complete. Separate transportation review can affect grading, fire access, parking layout, erosion control, and the location of water or sewer improvements." },
    ],
    faqs: [
      { question: "Does Missouri have one statewide building permit office?", answer: "No. The city or county with jurisdiction generally administers the building route, while fire, zoning, floodplain, stormwater, utility, and environmental authorities may have separate decisions." },
      { question: "What should a Missouri project verify first?", answer: "Confirm the address and AHJ, adopted code and energy path, occupancy, survey, soils, flood status, drainage, utilities, zoning, and alteration scope before relying on standard details." },
      { question: "Does a PE seal guarantee Missouri permit approval?", answer: "No. A seal identifies professional responsibility for a defined scope. The AHJ and other agencies decide whether their respective requirements are satisfied." },
    ],
    sources: [
      missouriEngineeringBoardSource,
      { label: "Missouri Department of Natural Resources water and stormwater programs", url: "https://dnr.mo.gov/water" },
      { label: "Missouri State Emergency Management Agency", url: "https://sema.dps.mo.gov/" },
      { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
    ],
  },
  metros: [
    { slug: "kansas-city", name: "Kansas City", county: "Jackson County", services: kansasCity },
    { slug: "st-louis", name: "St. Louis", county: "City of St. Louis", services: stLouis },
    { slug: "springfield", name: "Springfield", county: "Greene County", services: springfield },
    { slug: "columbia", name: "Columbia", county: "Boone County", services: columbia },
    { slug: "independence", name: "Independence", county: "Jackson County", services: independence },
  ],
};

export { missouriBatch4 };
export default missouriBatch4;