import type { Batch2CoreServicePage, Batch2CoreServiceSlug, Batch2StateExpansion } from "./batch2-core-service-types";

type Copy = {
  slug: Batch2CoreServiceSlug; title: string; description: string; h1: string; kicker: string; lede: string;
  sections: [{ heading: string; body: string }, { heading: string; body: string }, { heading: string; body: string }];
  permitSteps: [string, string, string, string]; faqs: [{ question: string; answer: string }, { question: string; answer: string }, { question: string; answer: string }];
};
type Local = { slug: string; name: string; county: string; ahj: string; review: string; conditions: string; sources: Array<{ label: string; url: string }>; copies: Copy[] };

const stateSources = [
  { label: "Nevada State Public Works building codes", url: "https://publicworks.nv.gov/Services/Building_Codes/" },
  { label: "Nevada NDEP construction stormwater permit", url: "https://ndep.nv.gov/water/water-pollution-control/permitting/stormwater-discharge-permits/construction-sites-greater-than-1-acre/" },
  { label: "Nevada Division of Water Resources floodplain management", url: "https://water.nv.gov/programs/floodplain-management/" },
  { label: "Nevada Board of Professional Engineers and Land Surveyors", url: "https://nvbpels.org/" },
];
const city = (label: string, url: string) => ({ label, url });
const compact = (slug: Batch2CoreServiceSlug, title: string, lede: string, sections: [string,string,string], steps: [string,string,string,string], faqs: [string,string,string,string,string,string]): Copy => ({
  slug, title, description: `${title}. Site-specific Nevada documentation for the described permit scope.`, h1: title, kicker: `${title} plan review`, lede,
  sections: sections.map((body, i) => ({ heading: [`Existing conditions and ${slug}`, "Local agencies and design criteria", "Correction record and residential interfaces"][i], body })) as Copy["sections"],
  permitSteps: steps, faqs: [0,2,4].map((i) => ({ question: faqs[i], answer: faqs[i + 1] })) as Copy["faqs"],
});

const locals: Local[] = [
  {
    slug: "las-vegas", name: "Las Vegas", county: "Clark County", ahj: "City of Las Vegas Building and Safety",
    review: "City building, zoning, fire, flood, right-of-way, and regional drainage reviews are separate from unincorporated Clark County.",
    conditions: "Las Vegas Valley caliche and variable alluvium, extreme heat, desert washes, dust, and urban heat island",
    sources: [
      city("Las Vegas Building and Safety", "https://www.lasvegasnevada.gov/Government/Departments/Building-Safety"),
      city("Las Vegas planning and zoning", "https://www.lasvegasnevada.gov/Government/Departments/Planning"),
      city("Las Vegas Public Works", "https://www.lasvegasnevada.gov/Government/Departments/Public-Works"),
      city("Las Vegas Valley Water District development services", "https://www.lvvwd.com/engineering-resources/building-permit/index.html"),
      city("Clark County Regional Flood Control District", "https://www.regionalflood.org/"),
    ],
    copies: [
      { slug:"structural-engineering", title:"Las Vegas structural engineering for desert infill", description:"Structural design for Las Vegas infill, additions, and tenant work grounded in caliche, heat, wind, and city review.", h1:"Structural Engineering for Las Vegas, Nevada", kicker:"Las Vegas load paths and desert foundations", lede:"Las Vegas structural work starts with field-verified framing, caliche assumptions, and the city’s flood and wind criteria—not a generic desert detail.", sections:[{heading:"Existing buildings in Las Vegas",body:"Older masonry, tract wood framing, rooftop equipment, and undocumented alterations require probes and permit-history checks before sizing a new opening or addition."},{heading:"Caliche and wash interfaces",body:"Foundation recommendations should reconcile variable alluvium, caliche lenses, expansive pockets, flash-flood routes, and finished floors shown against Regional Flood Control District data."},{heading:"City correction record",body:"Answer Building and Safety comments by identifying the revised calculation, connection detail, and affected architectural or MEP sheet; do not leave a field change to the contractor."}], permitSteps:["Confirm the parcel’s city jurisdiction, current Nevada code, occupancy, wind, seismic, and flood criteria with Building and Safety.","Obtain survey, geotechnical recommendations, framing exposures, roof-equipment loads, and drainage elevations before finalizing members.","Coordinate beam pockets, collectors, anchors, shoring, and special-inspection notes with the architectural and MEP permit set.","Log each city correction, cloud revised sheets, and obtain the responsible PE’s review before resubmittal."], faqs:[{question:"Does a Las Vegas addition always need a new foundation design?",answer:"Not always; existing capacity, new loads, soil evidence, setbacks, and the city’s requested documents determine the scope."},{question:"Can caliche be assumed across a Las Vegas parcel?",answer:"No. Caliche depth and continuity vary, so the geotechnical and field record should control footing and drainage assumptions."},{question:"Who decides whether structural corrections are accepted?",answer:"The City of Las Vegas Building and Safety reviewer decides; the responsible PE documents technical responses but does not promise approval."}]},
      { slug:"mep-engineering", title:"Las Vegas MEP engineering for heat-intensive buildings", description:"Las Vegas MEP engineering for additions, tenant improvements, and ADUs with NV Energy, water, sewer, and extreme-heat coordination.", h1:"MEP Engineering for Las Vegas, Nevada", kicker:"Las Vegas HVAC, service, and water coordination", lede:"In Las Vegas, MEP design must reconcile extreme cooling loads, desert dust, utility capacity, and a city plan-check path for the actual occupancy.", sections:[{heading:"Cooling and ventilation at the parcel",body:"Equipment schedules should reflect heat-island exposure, outside-air filtration, low humidity, condensate routing, and roof access rather than copying a temperate-climate load."},{heading:"Water and electrical service",body:"Las Vegas Valley Water District connection data, sewer points, NV Energy service information, and fire-flow requirements belong in the load and riser record for an addition or ADU."},{heading:"Coordinating city comments",body:"A correction to panel capacity or ventilation can change structure, energy forms, and fire separation; revise the linked drawings together in the Building and Safety response."}], permitSteps:["Confirm occupancy, adopted mechanical, plumbing, electrical, energy, and fire provisions with Building and Safety.","Request available electric, gas, water-pressure, sewer, and fire-flow information from the named providers and field-trace existing systems.","Coordinate equipment clearances, shafts, condensate, filtration, panel schedules, and shutdown phasing with the other disciplines.","Return numbered corrections with revised schedules, risers, calculations, and utility correspondence."], faqs:[{question:"Does a Las Vegas ADU need a separate utility study?",answer:"Its added loads may require service, water, sewer, or fire-flow verification; the AHJ and providers determine the required documents."},{question:"How should dust affect Las Vegas ventilation?",answer:"Filter selection, outdoor-air rates, intake placement, and maintenance access should be based on the occupancy and equipment design, not an unsupported promise of indoor-air performance."},{question:"Can a utility quote replace an MEP calculation?",answer:"No. Utility correspondence informs available service; the engineer still documents loads, distribution, equipment, and code coordination."}]},
      { slug:"civil-engineering", title:"Las Vegas civil engineering for wash-sensitive infill", description:"Civil plans for Las Vegas grading, drainage, access, utilities, and flood coordination with city and regional authorities.", h1:"Civil Engineering for Las Vegas, Nevada", kicker:"Las Vegas grading, washes, and utility plans", lede:"A Las Vegas civil package connects the building pad to desert drainage, public frontage, utilities, and Regional Flood Control District criteria.", sections:[{heading:"Survey and receiving systems",body:"A city site plan should show parcel limits, alleys, existing inlets, washes, accessible routes, fire access, and the actual downstream drainage connection."},{heading:"Monsoon runoff and caliche",body:"Short intense storms can overwhelm poorly documented grades; caliche and low infiltration affect detention, outlet protection, and whether an existing connection is usable."},{heading:"Small residential sites",body:"An ADU or addition still needs roof-runoff, sewer, fire-access, easement, and finished-floor checks when its impervious area or flow path changes."}], permitSteps:["Confirm city engineering, zoning, flood, right-of-way, and Regional Flood Control District thresholds for the address.","Verify survey control, existing utilities, wash limits, outfall ownership, finished-floor elevation, and soil infiltration assumptions.","Coordinate grading, drainage, accessible routes, fire access, utility profiles, and erosion controls with the building package.","Revise contours, calculations, details, and maintenance notes in response to every agency comment."], faqs:[{question:"Can Las Vegas roof runoff simply discharge to the street?",answer:"Not without checking city drainage, frontage, grading, and downstream capacity requirements for the parcel."},{question:"Does a detached Las Vegas ADU need civil review?",answer:"It may when it changes impervious area, access, utilities, drainage, flood elevation, or easements; the local checklist controls."},{question:"Which authority reviews a regional wash?",answer:"The city and Clark County Regional Flood Control District may have separate responsibilities, so the drainage map and address determine the route."}]},
      { slug:"energy-compliance", title:"Las Vegas energy compliance for high-solar buildings", description:"Las Vegas energy documentation coordinated with Nevada code, city permit drawings, HVAC schedules, glazing, and desert envelope details.", h1:"Energy Compliance for Las Vegas, Nevada", kicker:"Las Vegas envelope and cooling-load documentation", lede:"Las Vegas energy compliance is an envelope-and-equipment record tied to the adopted Nevada path, solar exposure, and the actual alteration scope.", sections:[{heading:"Solar gain and envelope evidence",body:"Glazing, shading, roof reflectance, air sealing, insulation continuity, and thermal bridges should match the city permit details and the modeled assemblies."},{heading:"Cooling, ventilation, and controls",body:"High summer loads and dust make equipment efficiency, filtration, outdoor air, controls, and condensate assumptions important to the energy and MEP sheets."},{heading:"Additions and ADUs",body:"An addition may trigger envelope, fenestration, HVAC, or lighting documentation even when the existing dwelling remains; classify the alteration with Building and Safety."}], permitSteps:["Confirm Nevada’s current energy provisions, climate inputs, alteration category, and city forms with Building and Safety.","Collect verified assemblies, windows, shading, HVAC, lighting, service-water, and control schedules from the coordinated design.","Check every modeled input against architectural details, structural penetrations, MEP equipment, and field installation notes.","Answer energy corrections with cited provisions, revised forms, and coordinated sheets rather than a standalone worksheet."], faqs:[{question:"Is a Las Vegas residential addition automatically exempt?",answer:"No. The applicable alteration category and scope determine the documentation; the AHJ should confirm the route."},{question:"Do energy forms document utility savings?",answer:"They document code compliance under the selected method; they do not guarantee bills, incentives, or operating performance."},{question:"What if the approved HVAC changes after plan check?",answer:"Recheck the energy inputs and affected MEP sheets, then have the responsible design professional issue the coordinated revision."}]},
      { slug:"pe-stamped-drawings", title:"Las Vegas PE-stamped drawings for coordinated permits", description:"Las Vegas sealed engineering documents with verified site data, local review boundaries, and correction tracking.", h1:"PE-Stamped Drawings for Las Vegas, Nevada", kicker:"Las Vegas responsible-charge documentation", lede:"A Las Vegas PE-stamped package should define the discipline, parcel evidence, design criteria, and review boundaries rather than imply approval or a universal stamping service.", sections:[{heading:"What the record contains",body:"The package identifies the city jurisdiction, code edition, survey, soil and flood assumptions, calculations, drawings, and the specific scope independently reviewed by the responsible PE."},{heading:"Desert interfaces",body:"Caliche, washes, heat, rooftop equipment, utility capacity, and fire access can require information from surveyors, geotechnical professionals, providers, and the regional flood agency."},{heading:"After the first review",body:"A dated comment matrix preserves who changed a detail, which calculation moved, and when the responsible PE reviewed a substitution, RFI, or field condition."}], permitSteps:["Identify the City of Las Vegas checklist, occupancy, code path, discipline limits, and required seal format.","Assemble survey, field observations, geotechnical and utility records, flood information, calculations, and consultant boundaries.","Have the responsible PE review the complete coordinated drawings, details, notes, schedules, and calculations before submission.","Route plan-check changes and construction RFIs back through that PE and issue revised sealed sheets only for changed scope."], faqs:[{question:"Does a Nevada PE seal mean the city must approve the set?",answer:"No. It identifies professional responsibility for a defined scope; Building and Safety retains approval authority."},{question:"Can a PE seal unverified existing framing?",answer:"The responsible professional must exercise independent judgment and identify limitations; unverified conditions should not be presented as confirmed facts."},{question:"Are contractor substitutions automatically covered?",answer:"No. A substitution affecting sealed work needs responsible-PE review and documented revision or acceptance."}]},

    ],
  },
  {
    slug:"henderson", name:"Henderson", county:"Clark County", ahj:"City of Henderson Community Development and Services", review:"Henderson building, planning, engineering, fire, and flood reviews are separate from unincorporated Clark County.", conditions:"Mojave heat, caliche, Black Mountain foothills, washes, drought, and planned-community grading", sources:[
      city("Henderson building and fire safety","https://www.cityofhenderson.com/government/departments/community-development-and-services/building-and-fire-safety"), city("Henderson development code","https://www.cityofhenderson.com/government/departments/community-development-and-services/planning"), city("Henderson public works","https://www.cityofhenderson.com/government/departments/public-works"), city("Henderson utilities","https://www.cityofhenderson.com/government/departments/utility-services"), city("Clark County Regional Flood Control District","https://www.regionalflood.org/")],
    copies:[
      compact("structural-engineering","Henderson structural engineering for foothill additions","Henderson structural design changes between flat subdivision pads and Black Mountain slopes; field soil and grade evidence controls the load path.",["Tract framing, retaining, stepped slabs, and prior alterations should be exposed before sizing an opening or addition.","Caliche, alluvial fans, washes, and foothill cuts affect bearing, lateral resistance, drainage, and retaining details.","Answer Henderson comments with revised calculations and connections coordinated with grading, fire separation, and MEP penetrations."],["Confirm Henderson code, occupancy, wind, seismic, flood, and hillside triggers.","Obtain survey, geotechnical, framing, retaining, and drainage evidence.","Coordinate foundations, anchors, openings, shoring, and inspections.","Log each correction and route technical changes through the responsible PE."],["Can a Henderson foothill addition use a standard footing?","Only after site soil, slope, drainage, and load criteria support it.","Why verify a flat Henderson subdivision?","Laterals, fills, washes, and utility changes can make neighboring lots materially different.","Who accepts structural revisions?","Henderson decides approval after the PE responds to cited comments."]),
      compact("mep-engineering","Henderson MEP engineering for planned neighborhoods","Henderson MEP design joins high cooling demand to planned-community service capacity, foothill exposure, and the occupancy’s ventilation needs.",["City utility records, NV Energy, Southwest Gas, water pressure, sewer points, and fire flow belong in load calculations.","Roof equipment, condensate, filtration, freeze protection, and maintenance access need details that work on slopes and flat pads.","An ADU can change panel, water, sewer, fire separation, and HVAC zoning; document those interfaces in one permit set."],["Confirm Henderson mechanical, plumbing, electrical, energy, and fire routes.","Request electric, gas, water, sewer, and fire-flow data and field-trace systems.","Coordinate risers, equipment, condensate, controls, clearances, and shutdowns.","Return numbered corrections with revised schedules and calculations."],["Does Henderson availability prove capacity?","No; provider data and project load calculations address different questions.","How should a foothill HVAC unit be placed?","Coordinate slope, access, drainage, noise, clearances, and manufacturer requirements.","Can a narrative alone answer an MEP comment?","Not when a load, riser, schedule, or detail changes."]),
      compact("civil-engineering","Henderson civil engineering for washes and slopes","Henderson civil plans show how a pad, driveway, fire route, and utilities connect to city drainage across changing grades.",["Survey should show subdivision inlets, washes, accessible slopes, fire access, utilities, and public frontage.","Monsoon runoff, caliche infiltration, alluvial fans, and ponds affect detention, outfalls, and erosion protection.","An ADU, patio, or addition can redirect roof water or cross an easement even without public street work."],["Confirm Henderson engineering, flood, zoning, right-of-way, and regional drainage thresholds.","Verify survey, wash limits, outfall ownership, finished floor, easements, and soils.","Coordinate grading, retaining, fire access, routes, utilities, and erosion controls.","Revise contours, profiles, calculations, details, and maintenance notes for every comment."],["Does a Henderson ADU need drainage design?","It may when roof, paving, grading, utilities, or flood exposure changes.","Can caliche be assumed to infiltrate?","Only with site evidence and an accepted method.","Who owns an outfall?","Confirm city, regional, and private records rather than assuming from the nearest inlet."]),
      compact("energy-compliance","Henderson energy compliance for desert additions","Henderson energy documentation ties solar gain and cooling demand to Nevada’s adopted method and the actual alteration scope.",["Glazing, shading, roof insulation, air leakage, and thermal bridges should match Henderson construction details.","Cooling, heat-pump operation, filtration, ventilation, lighting, and controls must agree with MEP schedules.","An addition or ADU may change envelope and equipment scope; Community Development should confirm its category."],["Confirm Nevada energy provisions, climate inputs, alteration category, and Henderson forms.","Collect assemblies, fenestration, HVAC, lighting, water-heating, and control inputs.","Cross-check modeled inputs against structure, penetrations, equipment, and architecture.","Answer citations with revised forms, inputs, and coordinated drawing references."],["Is every Henderson ADU on one energy path?","No; connected systems and alteration scope control the documentation.","Does shading matter?","Where the selected method uses it, document designed shade rather than an assumption.","What if equipment changes?","Recheck the analysis and coordinate the substitution with MEP and permit records."]),
      compact("pe-stamped-drawings","Henderson PE-stamped drawings for local review","Henderson sealed documents should define scope and evidence without implying that a professional seal substitutes for city approval.",["State parcel, code, soil and flood assumptions, utilities, calculations, sheets, and exclusions before sealing.","Survey, geotechnical, civil, fire, provider, and grading information may be outside one discipline’s responsibility.","A dated matrix links Henderson comments, substitutions, RFIs, observations, and the PE’s decision."],["Identify Henderson authority, occupancy, code, discipline boundary, and seal format.","Assemble survey, soils, flood, utility, field, calculation, and consultant records.","Review coordinated drawings and calculations with the responsible Nevada PE.","Resubmit after technical corrections are evaluated and revised sealed sheets are issued where needed."],["Does a Henderson seal replace grading approval?","No; city, regional, utility, and specialty authorities retain their review.","Can a PE rely on an unverified tract plan?","The professional should identify limits and obtain adequate evidence.","Who evaluates a field change?","The responsible PE reviews technical effects; Henderson decides permit-revision needs."]),
    ],
  },
  {
    slug:"reno", name:"Reno", county:"Washoe County", ahj:"City of Reno Community Development", review:"Reno city review is separate from Washoe County and Sparks; flood, hillside, fire, and public-works routes are parcel-specific.", conditions:"Truckee River floodplain, Sierra snow and wind, high-desert temperature swings, wildfire, alluvium, and steep foothills", sources:[
    city("Reno building permits","https://www.reno.gov/business-development/development-services/building-permits.php"), city("Reno planning and zoning","https://www.reno.gov/business-development/development-services/planning-engineering-applications/index.php"), city("Reno Public Works","https://www.reno.gov/government/departments/public-works/index.php"), city("Truckee Meadows Water Authority development","https://tmwa.com/development/"), city("Washoe County drainage and flooding","https://www.washoecounty.gov/csd/engineering_capitalprojects/drainage_and_flooding/index.php")],
    copies:[
      compact("structural-engineering","Reno structural engineering for river and foothill sites","Reno structural design bridges Sierra snow, Truckee River elevation, wildfire exposure, and irregular foothill grades.",["Downtown masonry, wood diaphragms, prior openings, and rooftop equipment need field verification.","Snow drift, wind, river elevation, alluvial soils, and cut-and-fill govern different parcels.","Answer Reno comments with calculation and detail changes coordinated with civil grades and MEP openings."],["Confirm Reno or Washoe jurisdiction and snow, wind, seismic, flood criteria.","Collect survey, soils, framing, flood, roof-load, and retaining evidence.","Coordinate foundations, connections, openings, shoring, and inspections.","Log comments and obtain PE review of changed calculations."],["Does Reno snow control every roof?","Site elevation, geometry, exposure, drift, and code criteria determine it.","How does the river affect structure?","Flood elevation can affect floors, foundations, materials, and civil interfaces.","Can old brick be assumed sound?","No; condition and connections require observation."]),
      compact("mep-engineering","Reno MEP engineering for cold nights and smoke","Reno MEP design balances cold nights, smoke filtration, snow exposure, utility capacity, and the building’s actual use.",["Altitude, smoke, filtration, combustion, and ventilation controls belong in schedules and sequences.","TMWA, NV Energy, Southwest Gas, sewer, and fire-flow information support service calculations.","An ADU or addition can change panel, condensate, water pressure, sewer, and fire separation."],["Confirm Reno or Washoe AHJ, occupancy, code, utilities, and fire thresholds.","Field-trace systems and obtain electric, gas, water, sewer, and fire-flow data.","Coordinate equipment, filtration, freeze protection, controls, and shutdowns.","Answer comments with revised risers, schedules, loads, and provider records."],["Does altitude change HVAC sizing?","Use project climate and manufacturer data rather than a regional assumption.","Can an addition share a sewer connection?","Only after capacity, ownership, connection, and utility rules are verified.","How should filtration be represented?","State equipment, filter, outdoor-air, controls, and maintenance assumptions without promises."]),
      compact("civil-engineering","Reno civil engineering for Truckee Meadows drainage","Reno civil work joins river elevation and foothill grading to snow storage, wildfire access, and public utilities.",["Plans should show flood elevation, alleys, inlets, accessible paths, fire routes, utilities, and drainage.","Snow storage, freeze-thaw, groundwater, alluvium, and steep cuts alter retaining and winter access.","An ADU can redirect water, consume fire access, and add sewer demand."],["Confirm Reno or Washoe engineering, flood, hillside, right-of-way, and stormwater routes.","Verify datum, flood, snow storage, utilities, outfalls, slopes, and finished floor.","Coordinate grading, drainage, retaining, access, utilities, and erosion controls.","Revise profiles, contours, calculations, and maintenance notes for each comment."],["Does snow storage belong on the plan?","Show it where it affects access, drainage, visibility, or public operations.","Can foothill grading use a flat standard?","No; slopes, retaining, runoff, and wildfire access control it.","Who reviews river comments?","Local and applicable regional or federal flood authorities may have distinct roles."]),
      compact("energy-compliance","Reno energy compliance for high-desert envelopes","Reno energy compliance reflects cold nights, solar swings, snow, smoke, and Nevada’s selected method.",["Air sealing, insulation, glazing, snow exposure, thermal bridges, and moisture details must match the assembly.","Heating, low-temperature heat pumps, filtration, ventilation, lighting, and controls need one schedule.","An addition changes envelope area and HVAC zoning; do not assume small area means exemption."],["Confirm Reno energy provisions, climate data, alteration category, and forms.","Gather assemblies, fenestration, HVAC, ventilation, lighting, service-water, and controls.","Cross-check inputs with structure, roof, equipment, and construction details.","Answer citations with revised inputs, forms, and affected drawings."],["Does Reno require a performance model?","Scope, occupancy, method, and AHJ direction determine the route.","Does filtration prove indoor air quality?","No; energy documents record design inputs, not operating outcomes.","What if a window changes?","Update energy, architectural, structural, and MEP records together."]),
      compact("pe-stamped-drawings","Reno PE-stamped drawings for snow and flood review","A Reno sealed set makes snow, flood, scope, and independent review boundaries clear without promising approval.",["State parcel, code, snow, wind, flood, survey, soils, calculations, and sealed sheets.","River elevation, foothill grading, wildfire access, utilities, and masonry may require specialist records.","A dated matrix connects Reno comments, RFIs, substitutions, observations, and PE decisions."],["Identify Reno or Washoe AHJ, occupancy, code, discipline boundary, flood route, and seal format.","Assemble field, survey, soil, snow, flood, utility, calculation, and consultant records.","Review coordinated drawings, notes, schedules, and calculations with the PE.","Route corrections through the PE and issue revised sealed sheets only when warranted."],["Does a Reno seal resolve flood approval?","No; flood and building authorities retain their jurisdictions.","Can snow criteria be copied?","Only when exposure, elevation, geometry, and code assumptions match.","Who approves field revisions?","The PE evaluates technical change; the AHJ decides permit revision."]),
    ],
  },
  {
    slug:"sparks", name:"Sparks", county:"Washoe County", ahj:"City of Sparks Community Development", review:"Sparks building and planning review is separate from Washoe County, regional flood agencies, and utility providers.", conditions:"Truckee Meadows alluvium, industrial redevelopment, river and channel flooding, winter freeze, Sierra wind, and smoke", sources:[
    city("Sparks building permits","https://www.cityofsparks.us/your_government/departments/community_development/building_permits/index.php"), city("Sparks planning and zoning","https://www.cityofsparks.us/your_government/departments/planning_and_zoning/index.php"), city("Sparks public works","https://www.cityofsparks.us/your_government/departments/public_works/index.php"), city("Truckee Meadows Water Authority development","https://tmwa.com/development/"), city("Washoe County drainage and flooding","https://www.washoecounty.gov/csd/engineering_capitalprojects/drainage_and_flooding/index.php")],
    copies:[
      compact("structural-engineering","Sparks structural engineering for industrial sites","Sparks structural work accounts for warehouse equipment, older commercial framing, flood routes, and snow and wind.",["Mezzanines, rooftop units, charging equipment, and large openings require field load-path verification.","Alluvium, groundwater, channels, freeze-thaw, and snow affect slabs, foundations, and exterior supports.","Respond to Sparks comments with reactions, calculations, connections, and coordinated fire and MEP details."],["Confirm Sparks occupancy, code, snow, wind, seismic, flood, and equipment criteria.","Verify framing, soil, groundwater, equipment reactions, flood elevation, and sequencing.","Coordinate structure, fire penetrations, MEP supports, loading, and inspections.","Log corrections and obtain PE review before issuing a revision."],["Can a warehouse slab accept new equipment?","Check slab, anchors, vibration, soil, and utilities for the actual equipment.","Does flood affect an interior tenant project?","It may affect equipment, floors, utilities, materials, and documentation.","What makes a correction complete?","Address the issue on calculations and every affected drawing."]),
      compact("mep-engineering","Sparks MEP engineering for industrial loads","Sparks MEP design connects industrial equipment and ventilation to city capacity, winter conditions, and fire systems.",["Charging, process, rooftop, ventilation, and lighting loads can change electric, gas, water, and fire demand.","Cold nights, dust, smoke, snow, and low areas affect intakes, filtration, freeze protection, and equipment elevation.","An expansion or ADU should document service, sewer, fire separation, controls, and shutdowns."],["Confirm Sparks occupancy, code, utility, fire, flood, and energy routes.","Obtain provider capacity and field-trace panels, water, sewer, gas, and fire systems.","Coordinate loads, clearances, ventilation, controls, condensate, protection, and phasing.","Return corrections with revised calculations, risers, diagrams, and utility records."],["Does industrial power need provider coordination?","Changed or large loads should be checked and documented with calculations.","How should rooftop units handle snow?","Supports, access, drainage, clearances, and manufacturer criteria govern.","Can a tenant set ignore the base building?","No; existing service, fire, and structural interfaces matter."]),
      compact("civil-engineering","Sparks civil engineering for logistics drainage","Sparks civil plans tie warehouse circulation, snow storage, flood routes, utilities, and public frontage together.",["Truck turning, loading, fire lanes, rail interfaces, accessible routes, and utility crossings need survey control.","Alluvium, storms, channels, snow storage, groundwater, and outfall ownership affect drainage.","An expansion or ADU can change impervious area, roof runoff, sewer, access, and easements."],["Confirm Sparks engineering, flood, zoning, right-of-way, fire, and regional drainage reviews.","Verify survey, utilities, outfalls, flood and snow areas, grades, easements, and soils.","Coordinate grading, drainage, utilities, fire access, loading, routes, and erosion.","Address comments with contours, profiles, calculations, details, and maintenance notes."],["Does warehouse work need snow storage?","Show it when it affects access, drainage, sightlines, or public operations.","Can existing detention serve expansion?","Capacity, ownership, maintenance, and impervious change need proof.","Who reviews a flood-route change?","City and applicable regional or federal authorities may review different parts."]),
      compact("energy-compliance","Sparks energy compliance for warehouse envelopes","Sparks energy documentation reflects large envelopes, high-bay lighting, equipment, cold nights, and Nevada code.",["Walls, roofs, doors, docks, glazing, air leakage, and thermal bridges should match the industrial assemblies.","Lighting controls, ventilation, process loads, heating, service water, and rooftop equipment must reconcile.","Tenant and addition scopes need an alteration classification rather than a residential assumption."],["Confirm Sparks climate data, occupancy, energy edition, alteration route, and forms.","Collect envelope, doors, glazing, lighting, HVAC, process, service-water, controls, and utility inputs.","Cross-check architecture, structure, equipment schedules, and field details.","Submit cited corrections with revised forms, inputs, schedules, and drawing references."],["Does a Sparks warehouse use a house path?","Occupancy, size, systems, and alteration scope determine the route.","Are process loads automatically excluded?","Their treatment depends on the adopted method and documented equipment.","What if controls change?","Update energy, lighting plans, schedules, and control narrative together."]),
      compact("pe-stamped-drawings","Sparks PE-stamped drawings for industrial review","Sparks sealed documents define equipment, utility, structural, and civil interfaces without implying a permit result.",["State occupancy, equipment, service, survey, soil, flood, code, calculations, sheets, and exclusions.","City engineering, utilities, fire, flood, and specialty contractors may provide information outside one discipline.","RFIs and substitutions affecting reactions or supports need responsible-PE review."],["Identify Sparks AHJ, occupancy, code, discipline, utility contacts, and seal format.","Assemble survey, field, geotechnical, flood, equipment, utility, calculation, and consultant records.","Review coordinated drawings and calculations with the PE.","Track corrections, substitutions, RFIs, and observations; issue changed sealed sheets only when reviewed."],["Does a seal cover contractor equipment supports?","Only when within the PE’s defined and independently reviewed scope.","Does a seal replace utility approval?","No; providers and AHJ retain capacity and connection decisions.","How should an industrial RFI be routed?","The PE evaluates effects and documents changed sheets or calculations."]),
    ],
  },
  {
    slug:"carson-city", name:"Carson City", county:"Carson City", ahj:"Carson City Community Development", review:"Carson City is an independent city-county with its own building, planning, historic, flood, and public-works route.", conditions:"Sierra foothill slopes, snow, freeze-thaw, Carson River floodplain, alluvial fans, wildfire, and older downtown construction", sources:[
      city("Carson City Community Development","https://www.carson.org/government/departments-g-z/community-development"), city("Carson City planning","https://www.carson.org/government/departments-g-z/community-development/planning"), city("Carson City Public Works","https://www.carson.org/government/departments-g-z/public-works"), city("Carson City utilities","https://www.carson.org/government/departments-g-z/public-works/utility-services"), city("Carson River flood information","https://www.carson.org/government/departments-g-z/community-development/floodplain-management")],
    copies:[
      compact("structural-engineering","Carson City structural engineering for historic and foothill sites","Carson City structural design respects historic fabric while addressing snow, foothill grades, river flood exposure, and older foundations.",["Probes and permit-history review should distinguish original masonry or wood from later alterations.","Snow drift, alluvial fans, freeze-thaw, wildfire, and river elevation affect foundations, retaining, roofs, and floors.","Answer Community Development comments with calculations and details coordinated with historic, fire, MEP, and accessibility work."],["Confirm independent city-county code, historic, flood, snow, wind, and hillside requirements.","Document framing, foundations, survey, soils, flood, roof loads, and historic elements.","Coordinate structure, shoring, penetrations, fire separation, retaining, and inspections.","Log corrections and obtain PE review before resubmission."],["Does historic status prevent alteration?","The designation and ordinance affect materials and review; the AHJ determines scope.","Should Carson City use Las Vegas snow assumptions?","No; elevation and exposure require project criteria.","Who accepts corrections?","Carson City decides after the PE responds to cited issues."]),
       compact("mep-engineering","Carson City MEP engineering for cold rehabilitation","Carson City MEP work fits older buildings and historic constraints while handling cold nights, snow, freeze protection, and utilities.",["Risers, penetrations, combustion, ventilation, fire stopping, and access should be field-traced before routing.","Water, sewer, NV Energy, Southwest Gas, panel, pressure, and fire-flow data inform rehabilitation and additions.","Corrections should coordinate shutdowns, temporary systems, controls, energy forms, and revised penetrations."],["Confirm Carson City code, historic, fire, energy, occupancy, and utility routes.","Trace existing systems and obtain Carson City electric, gas, water, sewer, and fire-flow records.","Coordinate equipment, shafts, ventilation, freeze protection, controls, and phased shutdowns.","Return corrections with revised risers, schedules, calculations, and records."],["Can historic walls be chased for MEP?","Evaluate historic, structural, fire, access, and less-invasive routing constraints.","Does an addition need water-pressure verification?","Added fixtures and fire demands should be checked against provider data.","How are field changes recorded?","Document the changed system, drawing, responsible review, and AHJ revision need."]),
      compact("civil-engineering","Carson City civil engineering for river and foothill parcels","Carson City civil design connects the independent city-county route to river flood, foothill grades, snow storage, and public frontage.",["Survey should show historic frontage, accessible routes, fire access, inlets, water, sewer, and right-of-way ownership.","Alluvial fans, river elevations, freeze-thaw, snowmelt, wildfire access, and slopes control floors, erosion, retaining, and outfalls.","A porch, ADU, driveway, or addition can change roof drainage, parking, easements, and utility demand."],["Confirm Carson City planning, engineering, flood, historic, fire, right-of-way, and utility requirements.","Verify datum, flood, grades, snow storage, outfalls, utilities, easements, and soils.","Coordinate grading, drainage, retaining, access, utilities, frontage, and erosion details.","Answer corrections with contours, profiles, calculations, details, and maintenance responsibilities."],["Can flood affect a residential addition?","It can change floors, drainage, access, materials, and required review.","Can snow storage occupy a swale?","Only if the accepted design maintains drainage and access.","Who reviews right-of-way connections?","Carson City public works or engineering controls them with utilities as applicable."]),
      compact("energy-compliance","Carson City energy compliance for historic additions","Carson City energy work reconciles cold nights and snow with historic assemblies, Nevada’s adopted path, and the alteration category.",["Windows, air sealing, insulation, thermal bridges, moisture, and roof assemblies should show historic and energy constraints.","Heating, low-temperature operation, ventilation, lighting, service water, and controls must match MEP schedules.","A new wing or ADU can change envelope and equipment scope; confirm the route with Community Development."],["Confirm energy provisions, historic review, climate data, alteration category, and forms.","Collect assemblies, windows, HVAC, ventilation, lighting, water-heating, controls, and utility inputs.","Cross-check analysis with historic details, structure, penetrations, equipment, and field notes.","Answer citations with revised forms, inputs, drawings, and a coordinated matrix."],["Can historic windows be ignored?","The adopted method and historic review determine treatment; document actual assemblies.","Does a small foothill addition need review?","Scope and alteration category determine the requirement.","Do forms guarantee lower bills?","No; they document compliance under stated assumptions."]),
      compact("pe-stamped-drawings","Carson City PE-stamped drawings for historic review","Carson City sealed engineering documents state scope and evidence while leaving historic, flood, utility, and permit decisions to their authorities.",["Identify parcel, city-county jurisdiction, code, historic status, snow, flood, survey, soils, calculations, and sealed sheets.","Community Development, public works, fire, utilities, and historic reviewers may require information beyond one discipline.","A response matrix links changed historic details, utility conditions, RFIs, observations, and PE decisions."],["Identify Carson City authority, occupancy, code, historic path, discipline, utilities, and seal format.","Assemble survey, field, soil, snow, flood, utility, historic, calculation, and consultant records.","Review coordinated drawings, notes, schedules, and calculations with the responsible PE.","Track corrections and changes through the PE; issue revised sealed sheets only for reviewed scope."],["Does a Carson City seal approve historic work?","No; historic and building authorities retain separate approval roles.","Can a seal cover an unknown foundation?","The PE must identify limits and obtain adequate evidence.","Are RFIs irrelevant to a sealed set?","No, not when they affect sealed design; they need documented review."]),
    ],
  },
];

type ServiceContext = Pick<Batch2CoreServicePage, "permitAuthority" | "codeContext" | "localConditions" | "projectTypes">;
const serviceContexts: Record<string, ServiceContext> = {
  "las-vegas:structural-engineering": {
    permitAuthority: "Las Vegas Building and Safety leads structural permit review for this desert-infill scope; the Regional Flood Control District and city drainage reviewers may separately control flood and wash interfaces.",
    codeContext: "Las Vegas structural documents should state the adopted Nevada structural provisions, caliche and alluvial bearing evidence, desert wind, seismic demand, rooftop loading, and any flood-related finished-floor criteria.",
    localConditions: "Las Vegas structural work addresses tract framing, caliche lenses, variable alluvium, expansive pockets, monsoon washes, extreme heat, and undocumented alterations at the specific infill parcel.",
    projectTypes: "This Las Vegas structural record is authored for desert infill openings, additions, rooftop equipment, tenant alterations, and ADUs where existing load paths need field confirmation.",
  },
  "las-vegas:mep-engineering": {
    permitAuthority: "Las Vegas Building and Safety reviews the MEP permit set with utility providers and fire reviewers; Las Vegas Valley Water District, NV Energy, and the actual sewer authority retain their service decisions.",
    codeContext: "Las Vegas MEP design should identify the applicable Nevada mechanical, plumbing, electrical, energy, and fire provisions alongside extreme cooling loads, filtration, condensate, and utility-service criteria.",
    localConditions: "Las Vegas MEP coordination responds to heat-island exposure, desert dust, low humidity, water pressure, sewer connection limits, panel capacity, and roof equipment access at the project address.",
    projectTypes: "This Las Vegas MEP record covers heat-intensive tenant improvements, additions, ADUs, service upgrades, and occupied-building equipment changes requiring coordinated risers and shutdowns.",
  },
  "las-vegas:civil-engineering": {
    permitAuthority: "Las Vegas Public Works and Building and Safety review the civil interface, while Clark County Regional Flood Control District controls applicable regional wash and outfall requirements.",
    codeContext: "Las Vegas civil plans should document the city grading and drainage criteria, Regional Flood Control District thresholds, accessible-route rules, right-of-way limits, and the accepted stormwater discharge path.",
    localConditions: "Las Vegas civil design is specific to caliche-limited infiltration, intense monsoon runoff, desert washes, alleys, frontage grades, finished floors, and the receiving drainage system for the parcel.",
    projectTypes: "This Las Vegas civil record addresses wash-sensitive infill, additions, detached ADUs, driveway changes, roof-runoff revisions, utility connections, and small sites with altered impervious area.",
  },
  "las-vegas:energy-compliance": {
    permitAuthority: "Las Vegas Building and Safety determines the energy submittal route for this alteration; the reviewing official, not the designer, decides whether the submitted path satisfies the city permit.",
    codeContext: "Las Vegas energy documentation should identify the current Nevada energy provisions, climate inputs, alteration category, solar-control method, cooling equipment, and coordinated envelope assemblies.",
    localConditions: "Las Vegas energy analysis is shaped by high solar gain, extreme summer cooling, desert dust, low humidity, roof reflectance, glazing exposure, and condensate details at the actual building.",
    projectTypes: "This Las Vegas energy record is authored for high-solar additions, ADUs, tenant improvements, glazing changes, HVAC replacements, and envelope work tied to the city permit drawings.",
  },
  "las-vegas:pe-stamped-drawings": {
    permitAuthority: "The responsible Nevada PE defines the sealed discipline for this Las Vegas package, while Las Vegas Building and Safety, flood control, utilities, and fire authorities retain their separate approval roles.",
    codeContext: "A Las Vegas sealed set should state the adopted code path, parcel wind and seismic criteria, caliche and flood assumptions, survey basis, calculations, and the limits of the PE’s independent review.",
    localConditions: "This Las Vegas professional record must distinguish verified framing, caliche, desert washes, heat-driven equipment, utility capacity, and regional drainage evidence from consultant or field assumptions.",
    projectTypes: "This Las Vegas PE record covers coordinated infill, additions, ADUs, tenant work, flood-sensitive civil interfaces, and correction or RFI revisions within the defined sealed discipline.",
  },
  "henderson:structural-engineering": {
    permitAuthority: "Henderson Community Development and Services reviews this structural scope, with separate Henderson engineering, fire, flood, and regional drainage decisions where the parcel triggers them.",
    codeContext: "Henderson structural documents should establish the Nevada code path, wind and seismic criteria, hillside triggers, caliche bearing evidence, retaining requirements, and flood-related elevation constraints.",
    localConditions: "Henderson structural design is specific to Black Mountain foothill grades, planned-community fills, caliche, alluvial fans, washes, stepped slabs, retaining walls, and tract alterations.",
    projectTypes: "This Henderson structural record is authored for foothill additions, subdivision modifications, retaining work, ADUs, hillside openings, and commercial additions with changing grade or soil evidence.",
  },
  "henderson:mep-engineering": {
    permitAuthority: "Henderson Community Development and Services coordinates the MEP permit review, while NV Energy, Southwest Gas, Henderson utilities, sewer, and fire authorities decide their respective capacities and connections.",
    codeContext: "Henderson MEP design should identify Nevada mechanical, plumbing, electrical, energy, and fire requirements together with planned-community service criteria, cooling demand, and hillside equipment constraints.",
    localConditions: "Henderson MEP work responds to Mojave heat, planned-community utility networks, foothill exposure, water pressure, sewer points, condensate routing, filtration, and access on sloped parcels.",
    projectTypes: "This Henderson MEP record covers planned-neighborhood additions, ADUs, tenant interiors, service changes, hillside HVAC placement, and occupied projects requiring phased utility shutdowns.",
  },
  "henderson:civil-engineering": {
    permitAuthority: "Henderson engineering and Community Development review this civil scope, with Clark County Regional Flood Control District and right-of-way owners retaining authority over applicable regional drainage and frontage work.",
    codeContext: "Henderson civil documentation should apply the city grading, drainage, flood, hillside, right-of-way, fire-access, and regional detention criteria confirmed for the address.",
    localConditions: "Henderson civil design distinguishes flat master-planned pads from Black Mountain foothills, caliche-limited infiltration, subdivision ponds, washes, easements, and changing finished-floor grades.",
    projectTypes: "This Henderson civil record addresses foothill drainage, subdivision additions, ADU grading, driveway and patio changes, retaining, utility profiles, and roof runoff redirected across established lots.",
  },
  "henderson:energy-compliance": {
    permitAuthority: "Henderson Community Development and Services decides the energy documentation route for this alteration, including any coordination with its building, fire, and planning review.",
    codeContext: "Henderson energy work should identify Nevada provisions, climate data, alteration category, solar exposure, heat-pump or cooling inputs, envelope assemblies, and the forms required by the city.",
    localConditions: "Henderson energy analysis accounts for Mojave solar gain, foothill orientation, caliche dust, roof insulation, glazing shade, cooling controls, and the actual planned-community addition.",
    projectTypes: "This Henderson energy record is authored for desert additions, detached ADUs, high-solar glazing changes, HVAC substitutions, tenant alterations, and envelope upgrades needing coordinated forms.",
  },
  "henderson:pe-stamped-drawings": {
    permitAuthority: "The responsible Nevada PE seals only the defined Henderson discipline; Henderson Community Development, utilities, fire, flood, and regional agencies keep their independent review authority.",
    codeContext: "A Henderson sealed package should record the city code path, foothill or flat-site criteria, caliche and flood assumptions, survey and consultant evidence, calculations, and seal boundaries.",
    localConditions: "This Henderson professional record separates verified subdivision grading, Black Mountain slopes, caliche, washes, utility interfaces, and retaining conditions from unverified site assumptions.",
    projectTypes: "This Henderson PE record covers local-review packages for foothill additions, planned-community ADUs, tenant work, grading interfaces, retaining, and technical corrections within sealed scope.",
  },
  "reno:structural-engineering": {
    permitAuthority: "Reno Community Development reviews this structural work inside the city; Washoe County, flood authorities, and fire reviewers may control separate portions of a river or foothill parcel.",
    codeContext: "Reno structural documents should establish Nevada code, Sierra snow drift, wind and seismic criteria, Truckee River flood elevation, foothill grading, and the existing-building design basis.",
    localConditions: "Reno structural design is specific to older masonry and wood framing, Truckee River elevation, alluvial soils, Sierra snow, wildfire exposure, and irregular foothill cut-and-fill.",
    projectTypes: "This Reno structural record addresses river-area additions, downtown infill, older-building openings, foothill tenant work, rooftop equipment, retaining interfaces, and flood-sensitive foundations.",
  },
  "reno:mep-engineering": {
    permitAuthority: "Reno Community Development reviews this MEP scope, while Truckee Meadows Water Authority, NV Energy, Southwest Gas, sewer, and fire agencies decide service and life-safety requirements.",
    codeContext: "Reno MEP design should document Nevada mechanical, plumbing, electrical, energy, and fire provisions with altitude, cold-night performance, smoke filtration, snow exposure, and utility-load criteria.",
    localConditions: "Reno MEP coordination responds to Truckee Meadows cold nights, wildfire smoke, Sierra snow, high-desert dust, freeze protection, water pressure, and existing-building service constraints.",
    projectTypes: "This Reno MEP record covers cold-climate additions, ADUs, smoke-aware tenant improvements, occupied retrofits, service upgrades, and equipment changes needing coordinated shutdowns.",
  },
  "reno:civil-engineering": {
    permitAuthority: "Reno engineering and Community Development review this civil work, with Washoe County, river-flood authorities, right-of-way owners, and utilities handling their distinct jurisdictional interfaces.",
    codeContext: "Reno civil documents should state the applicable flood, stormwater, hillside, right-of-way, snow-storage, accessible-route, fire-access, and drainage criteria for the city or county address.",
    localConditions: "Reno civil design is shaped by Truckee River elevation, snowmelt, shallow groundwater, alluvium, freeze-thaw, Sierra foothill cuts, winter access, and the surveyed outfall.",
    projectTypes: "This Reno civil record addresses Truckee Meadows infill, river-area additions, ADUs, snow-storage layouts, foothill grading, utility extensions, and drainage changes at residential sites.",
  },
  "reno:energy-compliance": {
    permitAuthority: "Reno Community Development determines the energy path for this alteration, with the city or Washoe County AHJ deciding how the submitted documentation is accepted.",
    codeContext: "Reno energy analysis should identify Nevada energy provisions, cold-climate inputs, snow exposure, smoke-related ventilation assumptions, alteration category, and the modeled or prescriptive method.",
    localConditions: "Reno energy work accounts for cold nights, solar swings, snow loads at roof interfaces, wildfire-smoke filtration, freeze-thaw moisture control, and high-desert envelope assemblies.",
    projectTypes: "This Reno energy record is authored for cold-climate additions, ADUs, smoke-aware HVAC changes, snow-exposed roof work, tenant improvements, and window or envelope alterations.",
  },
  "reno:pe-stamped-drawings": {
    permitAuthority: "The responsible Nevada PE defines the sealed Reno discipline, while Reno or Washoe County, flood, fire, utility, and public-works authorities retain their own approval decisions.",
    codeContext: "A Reno sealed package should state jurisdiction, snow and wind criteria, Truckee River flood information, seismic basis, survey and soil evidence, calculations, and the PE’s review limits.",
    localConditions: "This Reno professional record distinguishes verified river elevation, Sierra snow, foothill grades, existing masonry, wildfire access, smoke systems, and utility information from assumptions.",
    projectTypes: "This Reno PE record covers flood- and snow-aware infill, additions, ADUs, older-building tenant work, civil interfaces, and correction or construction changes within sealed scope.",
  },
  "sparks:structural-engineering": {
    permitAuthority: "Sparks Community Development reviews this structural scope, with Washoe County drainage, fire, utility, and regional flood authorities retaining their separate responsibilities for industrial sites.",
    codeContext: "Sparks structural documents should establish Nevada code, industrial occupancy, snow and wind, seismic and flood criteria, equipment reactions, soil evidence, and construction sequencing.",
    localConditions: "Sparks structural design is specific to Truckee Meadows alluvium, groundwater, channels, warehouse equipment, older commercial framing, winter freeze, and snow or wind exposure.",
    projectTypes: "This Sparks structural record addresses warehouse tenant work, industrial additions, equipment supports, mezzanines, loading interfaces, flood-sensitive slabs, and commercial infill.",
  },
  "sparks:mep-engineering": {
    permitAuthority: "Sparks Community Development coordinates this MEP permit, while NV Energy, Truckee Meadows Water Authority, Southwest Gas, sewer, fire, and flood reviewers decide their service or safety interfaces.",
    codeContext: "Sparks MEP design should identify Nevada mechanical, plumbing, electrical, energy, and fire provisions alongside industrial process loads, ventilation, snow exposure, and flood-protection criteria.",
    localConditions: "Sparks MEP coordination responds to warehouse equipment, charging loads, Truckee Meadows cold nights, dust and smoke, snow, low-area flooding, filtration, and municipal service capacity.",
    projectTypes: "This Sparks MEP record covers industrial tenant improvements, warehouse expansions, equipment-driven service upgrades, commercial additions, and ADUs sharing existing utility systems.",
  },
  "sparks:civil-engineering": {
    permitAuthority: "Sparks engineering and Community Development review this civil work, with Washoe County drainage, flood authorities, rail or right-of-way owners, and utilities controlling their respective interfaces.",
    codeContext: "Sparks civil plans should apply the city industrial-site, stormwater, flood-route, snow-storage, fire-access, loading, accessible-route, right-of-way, and regional drainage criteria.",
    localConditions: "Sparks civil design is shaped by Truckee Meadows alluvium, channels, intense storms, shallow groundwater, warehouse circulation, snow storage, rail interfaces, and outfall ownership.",
    projectTypes: "This Sparks civil record addresses logistics yards, warehouse additions, industrial infill, ADU or office changes, loading access, detention expansions, utility crossings, and flood routes.",
  },
  "sparks:energy-compliance": {
    permitAuthority: "Sparks Community Development determines the energy route for this industrial or infill alteration, including the forms and coordination expected with the building permit.",
    codeContext: "Sparks energy documentation should identify Nevada provisions, industrial occupancy, large-envelope inputs, high-bay lighting, process loads, cold nights, snow, and the alteration classification.",
    localConditions: "Sparks energy analysis accounts for warehouse roofs and docks, high-bay controls, equipment schedules, dust, smoke, snow exposure, cold-night heating, and large service loads.",
    projectTypes: "This Sparks energy record is authored for warehouses, logistics tenant improvements, industrial additions, equipment changes, commercial infill, and mixed-use alterations.",
  },
  "sparks:pe-stamped-drawings": {
    permitAuthority: "The responsible Nevada PE defines the sealed Sparks discipline, while Sparks Community Development, utilities, fire, flood, and industrial authorities retain their independent approval roles.",
    codeContext: "A Sparks sealed set should record industrial occupancy, equipment reactions, service assumptions, snow and flood criteria, survey and soil evidence, calculations, and sealed-sheet boundaries.",
    localConditions: "This Sparks professional record distinguishes verified warehouse framing, Truckee Meadows alluvium, groundwater, flood routes, utility capacity, equipment supports, and public frontage conditions.",
    projectTypes: "This Sparks PE record covers industrial permits, warehouse expansions, tenant improvements, equipment supports, civil interfaces, mixed-use additions, and reviewed RFIs or substitutions.",
  },
  "carson-city:structural-engineering": {
    permitAuthority: "Carson City Community Development reviews this structural scope as an independent city-county authority, with historic, flood, fire, and public-works reviews potentially separate.",
    codeContext: "Carson City structural documents should establish Nevada code, Sierra snow and wind, seismic and hillside criteria, Carson River flood information, historic constraints, and older-foundation evidence.",
    localConditions: "Carson City structural design is specific to historic masonry and wood, foothill slopes, alluvial fans, snow drift, freeze-thaw, wildfire exposure, and Carson River elevation.",
    projectTypes: "This Carson City structural record addresses historic rehabilitation, foothill additions, ADUs, state-area tenant work, river-valley foundations, retaining, and reversible alterations.",
  },
  "carson-city:mep-engineering": {
    permitAuthority: "Carson City Community Development coordinates this MEP scope, while city utilities, NV Energy, Southwest Gas, fire, historic, and public-works authorities retain their distinct reviews.",
    codeContext: "Carson City MEP design should document Nevada mechanical, plumbing, electrical, energy, fire, and historic-review requirements with cold-night, snow, freeze-protection, and phased-occupancy criteria.",
    localConditions: "Carson City MEP coordination responds to older building fabric, historic penetrations, snow and freeze-thaw, cold-climate heating, water pressure, sewer capacity, and fire stopping.",
    projectTypes: "This Carson City MEP record covers historic rehabilitation, cold-climate additions, ADUs, occupied retrofits, utility upgrades, and state-area tenant work with phased shutdowns.",
  },
  "carson-city:civil-engineering": {
    permitAuthority: "Carson City engineering and Community Development review this civil scope, with flood, historic, fire, utility, and right-of-way authorities controlling their separate frontage and drainage decisions.",
    codeContext: "Carson City civil plans should state the independent city-county flood, hillside, snow-storage, historic-frontage, accessible-route, fire-access, utility, and outfall criteria.",
    localConditions: "Carson City civil design is shaped by Carson River flood elevation, Sierra foothill grades, alluvial fans, snowmelt, freeze-thaw, historic frontage, and established neighborhood easements.",
    projectTypes: "This Carson City civil record addresses river-valley additions, foothill ADUs, historic neighborhood driveways, snow storage, frontage work, utility connections, retaining, and drainage revisions.",
  },
  "carson-city:energy-compliance": {
    permitAuthority: "Carson City Community Development determines the energy path for this historic or cold-climate alteration and coordinates it with applicable building and historic review.",
    codeContext: "Carson City energy documentation should identify Nevada provisions, cold-climate inputs, snow exposure, historic assembly treatment, alteration category, heating systems, and required forms.",
    localConditions: "Carson City energy analysis accounts for retained historic windows, cold nights, snow, freeze-thaw moisture, foothill orientation, heating equipment, and the actual rehabilitation envelope.",
    projectTypes: "This Carson City energy record is authored for historic additions, ADUs, cold-climate rehabilitation, window work, HVAC changes, tenant improvements, and retained-envelope upgrades.",
  },
  "carson-city:pe-stamped-drawings": {
    permitAuthority: "The responsible Nevada PE defines the sealed Carson City discipline, while Community Development, historic, flood, fire, utilities, and public works retain their independent approval authority.",
    codeContext: "A Carson City sealed package should state independent city-county jurisdiction, historic status, snow and flood criteria, survey and soil evidence, calculations, and the precise PE scope.",
    localConditions: "This Carson City professional record distinguishes verified historic fabric, Sierra snow, foothill grades, Carson River flood data, older foundations, utility conditions, and consultant limits.",
    projectTypes: "This Carson City PE record covers historic rehabilitation, foothill additions, ADUs, river-valley work, public-frontage interfaces, utility coordination, and reviewed field changes.",
  },
};

function page(local: Local, copy: Copy): Batch2CoreServicePage {
  const context = serviceContexts[`${local.slug}:${copy.slug}`];
  if (!context) throw new Error(`Missing service context for ${local.slug}:${copy.slug}`);
  return {
    serviceSlug: copy.slug, title: copy.title, description: copy.description, h1: copy.h1, kicker: copy.kicker, lede: copy.lede,
    permitAuthority: context.permitAuthority, codeContext: context.codeContext, localConditions: context.localConditions, projectTypes: context.projectTypes,
    sections: copy.sections, permitSteps: copy.permitSteps, faqs: copy.faqs, sources: [...local.sources, ...stateSources],
  };
}
const nevadaBatch4: Batch2StateExpansion = {
  stateSlug: "nevada", stateName: "Nevada", stateAbbrev: "NV",
  hub: {
    title: "Nevada engineering services for local permit review", description: "Site-specific Nevada structural, MEP, civil, energy, and PE-stamped drawing coordination for city and county review.", h1: "Engineering for Nevada Desert, River, and Mountain Communities", kicker: "Nevada permit and design coordination", lede: "Nevada code resources are statewide, but permit, flood, drainage, utility, zoning, and fire decisions are address-specific.",
    sections: [
      { heading: "Local AHJs administer the work", body: "Las Vegas, Henderson, Reno, Sparks, Carson City, and county jurisdictions use different building, planning, fire, engineering, flood, and right-of-way routes. Confirm the address before selecting a checklist." },
      { heading: "Physical conditions change by valley", body: "Caliche, alluvium, washes, expansive soil, heat, snow, river floodplain, wind, seismic demand, and wildfire exposure affect different parcels and disciplines." },
      { heading: "Utilities and drainage are parallel reviews", body: "Water districts, NV Energy, Southwest Gas, municipal sewer, regional flood-control districts, and NDEP may require separate capacity, connection, discharge, or protection information." },
      { heading: "Additions need complete records", body: "ADUs and additions can affect egress, fire separation, foundation loads, HVAC, service capacity, grading, flood exposure, and energy forms; corrections should stay coordinated." },
      { heading: "Transportation access needs its own handoff", body: "A project fronting a state route may need a Nevada Department of Transportation access, drainage, or encroachment conversation in addition to the city permit. The civil team should identify the roadway owner, driveway spacing, sight-distance, sidewalk, utility-cut, and temporary-traffic requirements before fixing frontage work. A Clark County or Washoe County road is not automatically an NDOT facility, and an NDOT approval does not resolve zoning, flood, or building review. Keep the agency’s written conditions with the survey, grading, utility, and construction-phasing records so later plan-check changes do not quietly conflict with the public right-of-way." },
    ],
    faqs: [
      { question: "Does Nevada have one permit office?", answer: "No. Local city or county authorities administer building and development review, with parallel agencies involved according to the address and scope." },
      { question: "What should be verified before design?", answer: "Verify jurisdiction, code edition, survey, soils, flood and wash status, utilities, drainage outlet, occupancy, zoning, and alteration category." },
      { question: "Does a PE seal guarantee approval?", answer: "No. A seal identifies professional responsibility for a defined scope; the AHJ decides approval and may require separate reviews." },
    ],
    sources: stateSources,
  },
  metros: locals.map((local) => ({
    slug: local.slug, name: local.name, county: local.county,
    services: local.copies.map((copy) => page(local, copy)),
  })),
};
export { nevadaBatch4 };
export default nevadaBatch4;