import type { Batch2CoreServicePage, Batch2StateExpansion } from "./batch2-core-service-types";

type R = {
  serviceSlug: Batch2CoreServicePage["serviceSlug"]; title: string; description: string; h1: string; kicker: string; lede: string;
  permitAuthority: string; codeContext: string; localConditions: string; projectTypes: string;
  sections: [{ heading: string; body: string }, { heading: string; body: string }, { heading: string; body: string }];
  permitSteps: [string, string, string, string];
  faqs: [{ question: string; answer: string }, { question: string; answer: string }, { question: string; answer: string }];
  sources: Array<{ label: string; url: string }>;
};
const src = {
  nashville: [
    { label: "Metro Nashville Codes", url: "https://www.nashville.gov/departments/codes" },
    { label: "Nashville Planning", url: "https://www.nashville.gov/departments/planning" },
    { label: "Metro Water Services", url: "https://www.nashville.gov/departments/water" },
    { label: "Tennessee State Fire Marshal codes", url: "https://www.tn.gov/commerce/fire/codes.html" },
    { label: "Tennessee Board of Architectural and Engineering Examiners", url: "https://www.tn.gov/commerce/regboards/ae.html" },
    { label: "TDEC stormwater", url: "https://www.tn.gov/environment/program-areas/wr-water-resources/stormwater.html" },
    { label: "TDEC water resources", url: "https://www.tn.gov/environment/program-areas/wr-water-resources.html" },
    { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  ],
  memphis: [
    { label: "Memphis Construction Code Enforcement", url: "https://www.memphistn.gov/government/engineering/construction-code-enforcement/" },
    { label: "Memphis and Shelby County Planning", url: "https://www.shelbycountytn.gov/271/Planning-Development" },
    { label: "Memphis Light, Gas and Water", url: "https://www.mlgw.com/" },
    { label: "Tennessee State Fire Marshal codes", url: "https://www.tn.gov/commerce/fire/codes.html" },
    { label: "Tennessee Board of Architectural and Engineering Examiners", url: "https://www.tn.gov/commerce/regboards/ae.html" },
    { label: "TDEC stormwater", url: "https://www.tn.gov/environment/program-areas/wr-water-resources/stormwater.html" },
    { label: "TDEC water resources", url: "https://www.tn.gov/environment/program-areas/wr-water-resources.html" },
    { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  ],
  knoxville: [
    { label: "Knoxville Plans Review and Inspections", url: "https://www.knoxvilletn.gov/government/city_departments_offices/plans_review_inspections" },
    { label: "Knoxville planning and zoning", url: "https://www.knoxvilletn.gov/government/city_departments_offices/plans_review_inspections" },
    { label: "Knoxville Utilities Board", url: "https://www.kub.org/" },
    { label: "Tennessee State Fire Marshal codes", url: "https://www.tn.gov/commerce/fire/codes.html" },
    { label: "Tennessee Board of Architectural and Engineering Examiners", url: "https://www.tn.gov/commerce/regboards/ae.html" },
    { label: "TDEC stormwater", url: "https://www.tn.gov/environment/program-areas/wr-water-resources/stormwater.html" },
    { label: "TVA environmental review", url: "https://www.tva.com/environment" },
    { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  ],
  chattanooga: [
    { label: "Chattanooga Land Development Office", url: "https://chattanooga.gov/government/departments/land-development-office" },
    { label: "Chattanooga development services", url: "https://chattanooga.gov/government/departments/land-development-office" },
    { label: "Tennessee-American Water", url: "https://www.tnamerican.com/" },
    { label: "Tennessee State Fire Marshal codes", url: "https://www.tn.gov/commerce/fire/codes.html" },
    { label: "Tennessee Board of Architectural and Engineering Examiners", url: "https://www.tn.gov/commerce/regboards/ae.html" },
    { label: "TDEC stormwater", url: "https://www.tn.gov/environment/program-areas/wr-water-resources/stormwater.html" },
    { label: "TDEC water resources", url: "https://www.tn.gov/environment/program-areas/wr-water-resources.html" },
    { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  ],
  clarksville: [
    { label: "Clarksville Development Services", url: "https://www.cityofclarksville.com/government/departments/development_services.php" },
    { label: "Clarksville-Montgomery Regional Planning", url: "https://www.cmcrpc.com/" },
    { label: "Clarksville Gas and Water", url: "https://www.cityofclarksville.com/government/departments/gas_and_water.php" },
    { label: "Tennessee State Fire Marshal codes", url: "https://www.tn.gov/commerce/fire/codes.html" },
    { label: "Tennessee Board of Architectural and Engineering Examiners", url: "https://www.tn.gov/commerce/regboards/ae.html" },
    { label: "TDEC stormwater", url: "https://www.tn.gov/environment/program-areas/wr-water-resources/stormwater.html" },
    { label: "TDEC water resources", url: "https://www.tn.gov/environment/program-areas/wr-water-resources.html" },
    { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
  ],
} satisfies Record<string, Array<{ label: string; url: string }>>;
const c = {
  nashville: "Nashville's Cumberland hills, limestone and karst, creek and river floodplains, intense rain, rapid infill, and aging urban utilities",
  memphis: "Memphis' Mississippi and Wolf River floodplains, flat alluvium, loess bluffs, New Madrid seismic influence, heat, and older utility corridors",
  knoxville: "Knoxville's Tennessee Valley ridges, karst and residual soils, river and creek floodplains, steep grades, humidity, and freeze-thaw",
  chattanooga: "Chattanooga's Tennessee River drainage, steep escarpments, karst, industrial reuse, intense rainfall, and regional utility corridors",
  clarksville: "Clarksville's Cumberland River floodplain, rolling limestone and clay, karst, fast growth, severe thunderstorms, and occasional freezes",
};

const records: R[] = [
  { serviceSlug: "structural-engineering", title: "Nashville Tennessee Structural Engineering", description: "Structural design for Nashville additions, karst sites, floodplains, and commercial reuse.", h1: "Structural Engineering in Nashville, Tennessee", kicker: "Cumberland hills and existing-building load paths", lede: "Nashville structures must reconcile limestone and karst, creek flooding, rapid infill, severe storms, and what an older house or commercial shell actually contains.", permitAuthority: "Metro Nashville Codes is the city AHJ; Planning, floodplain, stormwater, fire, historic, Metro Water, and county jurisdictions can have separate roles.", codeContext: "Confirm Tennessee's statewide commercial baseline based on the 2018 IBC, local residential or commercial adoption, amendments, seismic, flood, soil, existing-building, and inspection criteria.", localConditions: c.nashville, projectTypes: "ADUs, residential additions, hillside work, historic renovations, offices, and rooftop equipment", sections: [{ heading: "Karst changes Nashville foundations", body: "Limestone voids, fill, residual clay, and slope drainage can change footing, retaining, and underpinning decisions. Geotechnical evidence should control an addition rather than a typical flat-lot detail." }, { heading: "Creek flood and infill meet", body: "A finished-floor, flood-opening, or access decision near a creek can affect foundations and neighboring runoff. Survey and flood data belong in the structural basis." }, { heading: "Growth makes corrections consequential", body: "Openings, temporary support, rooftop equipment, and excavation beside existing buildings should be answered with revised calculations and coordinated civil or MEP sheets." }], permitSteps: ["Confirm the Nashville address, Codes and Planning intake, zoning, flood map, karst or slope information, and existing permits.", "Record framing, footings, soil, grades, flood or moisture damage, equipment, and demolition limits and flag field verification.", "Coordinate foundations, retaining, flood details, wind and seismic criteria, fire access, MEP penetrations, and inspections.", "Return numbered Metro Codes comments and control revisions when excavation, a substitution, or concealed construction changes the design."], faqs: [{ question: "Does a Nashville ADU need structural engineering?", answer: "New footings, bearing-wall changes, karst or slope conditions, roof work, flood exposure, or uncertain connections can create engineering scope; the AHJ and engineer decide." }, { question: "Why does Nashville karst matter to an addition?", answer: "Subsurface voids and variable rock can change foundations, drainage, retaining, and construction sequencing across a small parcel." }, { question: "How should Nashville corrections be closed?", answer: "Map comments to sheets and calculations, coordinate civil, MEP, and planning changes, and submit the controlled response through Metro Codes." }], sources: src.nashville },
  { serviceSlug: "mep-engineering", title: "Nashville Tennessee MEP Engineering", description: "MEP coordination for Nashville homes, healthcare, offices, restaurants, and additions.", h1: "MEP Engineering in Nashville, Tennessee", kicker: "Humid systems, karst routing, and utility demand", lede: "Nashville MEP work connects rapid occupancy growth to humid-climate controls, utility capacity, flood elevation, and difficult existing corridors.", permitAuthority: "Metro Nashville Codes receives the building record; Planning, Metro Water, fire, floodplain, stormwater, health, and historic reviewers may be separate.", codeContext: "Confirm the 2018 IBC commercial baseline, Tennessee energy path, local mechanical, plumbing, electrical, fuel-gas, fire, and accessibility requirements.", localConditions: c.nashville, projectTypes: "healthcare, restaurants, offices, ADUs, multifamily, schools, and tenant improvements", sections: [{ heading: "Metro Water capacity comes first", body: "Fixture counts, sewer, fire flow, backflow, pressure, and shutdown information should come from Metro Water before a restaurant, clinic, or ADU service is finalized." }, { heading: "Karst and flood change routes", body: "Gravity sewer, condensate, equipment elevation, utility penetrations, and emergency power need to match grade, flood, and subsurface constraints." }, { heading: "Occupied Nashville work needs phasing", body: "Ventilation, fire, exhaust, domestic water, electrical service, and shutdowns should be revised together when Codes returns comments." }], permitSteps: ["Open the Nashville occupancy record and identify Codes, Planning, fire, flood, health, Metro Water, and right-of-way reviews.", "Request address-specific water, sewer, pressure, fire-flow, backflow, electric, gas, and shutdown data.", "Coordinate feeders, risers, ventilation, grease or process waste, condensate, ADU service, controls, and backup power.", "Return numbered MEP corrections through Metro Codes and preserve utility letters, calculations, substitutions, and inspection records."], faqs: [{ question: "Can a Nashville ADU share the house service?", answer: "Load, feeder, water, sewer, ventilation, hot water, karst, flood, and fire requirements must be checked for the address." }, { question: "What does Nashville karst change for MEP work?", answer: "It can affect trenching, gravity sewer, utility routing, drainage concentration, and equipment support; civil and geotechnical information should be coordinated." }, { question: "What belongs in a Nashville MEP response?", answer: "Identify the comment, revise risers and calculations, check fire and structural interfaces, and document utility or equipment changes." }], sources: src.nashville },
  { serviceSlug: "civil-engineering", title: "Nashville Tennessee Civil Engineering", description: "Civil grading, karst, stormwater, floodplain, and utility design for Nashville.", h1: "Civil Engineering in Nashville, Tennessee", kicker: "Cumberland watershed and karst site design", lede: "Nashville civil work must move intense rainfall across karst and hilly infill while protecting creeks, floodplains, streets, and existing homes.", permitAuthority: "Metro Planning and Codes coordinate the city path; Metro Water, floodplain, stormwater, fire, TDEC, historic, and right-of-way decisions may be separate.", codeContext: "Confirm Nashville zoning, stormwater, drainage, floodplain, grading, erosion, utility, steep-site, and TDEC construction-stormwater requirements.", localConditions: c.nashville, projectTypes: "ADU lots, residential additions, hillside infill, subdivisions, commercial sites, and public frontage", sections: [{ heading: "Karst changes detention assumptions", body: "A Nashville drainage plan should not concentrate water over a suspected void. Survey, geotechnical evidence, receiving creek capacity, easements, and maintenance should support the outlet." }, { heading: "Small additions alter creek runoff", body: "An ADU, driveway, or patio can move water toward a crawlspace, neighbor, street, or sinkhole-prone area. Grades, retaining, finished floor, and access need one surface." }, { heading: "Construction stormwater has its own record", body: "TDEC coverage, local erosion controls, utility locates, dewatering, and final stabilization should be sequenced separately from permanent conveyance." }], permitSteps: ["Confirm Nashville jurisdiction, zoning, watershed, flood zone, karst or slope, disturbance, frontage, and Metro Water service.", "Obtain survey and request outlet, geotechnical, utility, fire, flood, erosion, dewatering, and right-of-way criteria.", "Coordinate grading, detention or conveyance, retaining, finished floors, ADU access, erosion controls, utilities, and foundations.", "Track Metro, TDEC, flood, fire, and utility comments by sheet and retain calculations, maintenance, and as-built requirements."], faqs: [{ question: "Does a Nashville ADU trigger civil review?", answer: "A detached pad, impervious area, driveway, floodplain, karst, retaining, sewer tie, or drainage change can create scope; Metro reviewers decide." }, { question: "What controls a Nashville creek outlet?", answer: "Receiving-water capacity, karst, tailwater, flood, survey, easements, erosion, local criteria, and maintenance ownership control it." }, { question: "Why can a Nashville grading correction affect structure?", answer: "Grade and retaining changes can move foundations, finished floors, paths, utility profiles, and concentrated runoff." }], sources: src.nashville },
  { serviceSlug: "energy-compliance", title: "Nashville Tennessee Energy Compliance", description: "Energy documentation for Nashville healthcare, offices, homes, additions, and tenant work.", h1: "Energy Compliance in Nashville, Tennessee", kicker: "2018 baseline and humid mixed-climate records", lede: "Nashville energy work must name the accepted Tennessee path and coordinate humid cooling, shoulder-season heating, glazing, controls, and the actual infill shell.", permitAuthority: "Metro Codes establishes the local intake; confirm the effective Tennessee energy edition, local method, and alteration provisions before modeling.", codeContext: "Tennessee's statewide commercial baseline is based on the 2018 IECC, with ASHRAE 90.1-2016 as an alternate; Metro Codes confirms the project path and local requirements.", localConditions: c.nashville, projectTypes: "healthcare, offices, restaurants, multifamily, ADUs, schools, and tenant improvements", sections: [{ heading: "Nashville occupancy drives the model", body: "Healthcare, offices, restaurants, residences, and tenant spaces have different ventilation, plug, lighting, and schedule assumptions. The model must match the actual conditioned boundary." }, { heading: "Humidity and shoulder seasons both count", body: "Latent cooling, air sealing, solar gain, heat-pump or boiler operation, ventilation, and controls should align across the shell and MEP set." }, { heading: "Corrections follow fast-moving equipment", body: "A revised glazing, lighting, HVAC, or control selection can change the form or model. Update the affected sheets when Codes comments." }], permitSteps: ["Ask Metro Codes which 2018 IECC or ASHRAE path, forms, occupancy, and alteration provisions apply.", "Collect envelope, glazing, lighting, HVAC, ventilation, service-water, controls, schedules, and utility inputs.", "Reconcile energy records with karst or roof details, structural openings, MEP, fire, and ADU boundaries.", "Return numbered corrections and preserve revised forms, model inputs, substitutions, sequences, commissioning, and field checks."], faqs: [{ question: "How should a Nashville ADU enter the energy path?", answer: "Conditioned area, relationship to the house, alteration scope, existing envelope, and Metro's accepted method determine the documents." }, { question: "Does Nashville compliance promise operating savings?", answer: "No. Weather, operation, occupants, controls, construction, maintenance, equipment, and rates determine actual use." }, { question: "What is a useful Nashville energy correction?", answer: "Name the changed form or model input, affected envelope or MEP sheet, method, and coordinated revision returned to Codes." }], sources: src.nashville },
  { serviceSlug: "pe-stamped-drawings", title: "Nashville Tennessee PE-Stamped Drawings", description: "Defined PE responsibility for Nashville karst, flood, infill, and building packages.", h1: "PE-Stamped Drawings in Nashville, Tennessee", kicker: "Karst evidence and Metro review boundaries", lede: "A Nashville sealed package should state its karst, slope, flood, utility, existing-condition, code, and discipline limits before review.", permitAuthority: "Metro Codes and Planning are the local path; Metro Water, fire, floodplain, TDEC, historic, and right-of-way authorities retain separate decisions while the PE defines scope.", codeContext: "The PE identifies the 2018 IBC baseline or applicable local adoption, energy path, Nashville checklist, soil, flood, wind, seismic, inspections, and delegated-design basis.", localConditions: c.nashville, projectTypes: "structural and civil sets, MEP systems, ADUs, additions, healthcare, and commercial reuse", sections: [{ heading: "A Nashville seal needs site evidence", body: "Survey, contours, geotechnical or karst information, framing observations, utility records, flood data, and owner scope support professional judgment." }, { heading: "Metro decisions are not one approval", body: "Codes, Planning, Metro Water, fire, floodplain, TDEC, historic, and public-way reviewers may own different questions; a responsibility matrix should show them." }, { heading: "Hidden conditions change engineering", body: "A void, footing, utility conflict, demolition discovery, or substitution can alter the accepted package. The PE evaluates and controls a revision." }], permitSteps: ["Identify Nashville Codes, Planning, fire, flood, TDEC, Metro Water, historic, and right-of-way handoffs.", "Assemble survey, contours, geotechnical, existing-condition, architectural, equipment, drainage, and utility records.", "Submit authenticated sheets through the Metro process while separating specialty, utility-owner, contractor, and delegated documents.", "Track comments, inspections, RFIs, karst discoveries, and substitutions; issue controlled revisions for changed scope."], faqs: [{ question: "Does a Nashville PE stamp replace Metro approval?", answer: "No. It communicates responsibility for a defined scope; Metro, county, fire, flood, TDEC, utility, historic, and public-way authorities retain decisions." }, { question: "Can a Nashville karst package rely on old records?", answer: "The PE decides whether survey, geotechnical, existing-condition, utility, and field evidence are adequate; voids and concealed work may require investigation." }, { question: "How are Nashville sealed corrections returned?", answer: "Map comments to sheets and calculations, coordinate civil, structural, MEP, and planning effects, and submit a controlled response." }], sources: src.nashville },
  // Memphis
  { serviceSlug: "structural-engineering", title: "Memphis Tennessee Structural Engineering", description: "Structural design for Memphis floodplain, seismic, alluvial, and existing buildings.", h1: "Structural Engineering in Memphis, Tennessee", kicker: "Mississippi corridor seismic and flood review", lede: "Memphis structures must address New Madrid influence, Mississippi and Wolf River flooding, flat alluvium, loess, and aging commercial or residential framing.", permitAuthority: "Memphis Construction Code Enforcement is the city AHJ; Shelby County Planning, floodplain, fire, MLGW, and neighboring municipalities have separate paths.", codeContext: "Confirm the Tennessee 2018 IBC commercial baseline, Memphis or local residential adoption, New Madrid seismic criteria, flood, soil, existing-building, and inspection requirements.", localConditions: c.memphis, projectTypes: "ADUs, logistics buildings, additions, warehouses, historic masonry, schools, and flood repairs", sections: [{ heading: "West Tennessee seismic criteria matter", body: "Memphis lateral systems, anchorage, drift, and equipment connections should use site-specific seismic parameters rather than an inland generic detail." }, { heading: "Alluvium and flood change foundations", body: "Mississippi and Wolf River elevations, loess, soft or fill ground, and saturated soils can affect slabs, footings, flood openings, and utility support." }, { heading: "Logistics buildings need correction discipline", body: "Rooftop equipment, rack loads, openings, fire systems, and occupied phasing should be addressed together when Code Enforcement returns comments." }], permitSteps: ["Confirm Memphis address, code path, seismic basis, flood map, zoning, and existing permit or repair history.", "Record framing, foundations, soil, elevation, damage, equipment, and demolition limits and identify needed field verification.", "Coordinate lateral system, foundations, flood details, fire access, MEP anchorage, openings, and inspections.", "Return numbered corrections through Code Enforcement and control revisions when field discoveries or substitutions change design."], faqs: [{ question: "When can a Memphis ADU need structural engineering?", answer: "New foundations, wall openings, roof work, flood exposure, seismic anchorage, or uncertain existing framing can create scope; the AHJ and engineer decide." }, { question: "Why is Memphis seismic review distinct?", answer: "New Madrid influence can affect lateral design and anchorage, while Mississippi-corridor flood and alluvial conditions affect foundations and utilities." }, { question: "How should Memphis flood corrections be answered?", answer: "State seismic and flood assumptions, revise affected sheets and calculations, coordinate civil and MEP changes, and return the numbered response." }], sources: src.memphis },
  { serviceSlug: "mep-engineering", title: "Memphis Tennessee MEP Engineering", description: "MEP coordination for Memphis logistics, healthcare, homes, and flood-aware renovations.", h1: "MEP Engineering in Memphis, Tennessee", kicker: "MLGW capacity, seismic anchorage, and flood", lede: "Memphis MEP work combines large logistics loads with humid cooling, MLGW service coordination, flood elevation, and seismic equipment anchorage.", permitAuthority: "Memphis Code Enforcement receives the building record; Shelby Planning, MLGW, fire, floodplain, health, and public works can review separate systems.", codeContext: "Confirm Tennessee's 2018 commercial baseline and the locally accepted mechanical, plumbing, electrical, energy, fire, fuel-gas, accessibility, and flood provisions.", localConditions: c.memphis, projectTypes: "distribution facilities, clinics, restaurants, ADUs, multifamily, offices, and tenant improvements", sections: [{ heading: "MLGW records set the service basis", body: "Electric, gas, water, sewer, pressure, fire flow, backflow, and shutdown data should be requested before large logistics or residential service changes." }, { heading: "Flood and seismic affect equipment", body: "Elevated equipment, protected controls, flood openings, anchorage, emergency power, condensate, and ventilation should be coordinated with the surveyed elevation and seismic basis." }, { heading: "Occupied logistics corrections need phasing", body: "Exhaust, electrical distribution, fire systems, domestic water, and shutdowns should be revised together when Code Enforcement comments." }], permitSteps: ["Open the Memphis occupancy file and identify Code, Planning, fire, flood, MLGW, health, and right-of-way reviews.", "Request MLGW and owner data for electric, gas, water, sewer, pressure, fire flow, backflow, and shutdowns.", "Coordinate feeders, risers, flood protection, seismic anchorage, ventilation, process waste, ADU service, and controls.", "Return numbered MEP corrections through the AHJ and retain utility letters, calculations, substitutions, commissioning, and inspections."], faqs: [{ question: "Can a Memphis ADU share MLGW service?", answer: "Load, feeder, water, sewer, flood elevation, ventilation, hot water, anchorage, and the local connection process must be checked." }, { question: "What does flood change for Memphis MEP design?", answer: "Equipment elevation, controls, penetrations, condensate, emergency power, and access can change; flood notes alone are not a complete system design." }, { question: "How should a Memphis correction involving anchorage be handled?", answer: "Revise equipment loads and connections with structural sheets, check flood placement, and return the coordinated response through the AHJ." }], sources: src.memphis },
  { serviceSlug: "civil-engineering", title: "Memphis Tennessee Civil Engineering", description: "Civil design for Memphis floodplain, logistics sites, drainage, and utility work.", h1: "Civil Engineering in Memphis, Tennessee", kicker: "Mississippi and Wolf River watershed coordination", lede: "Memphis civil plans must route intense rainfall across flat alluvial ground while respecting river flood, loess bluffs, logistics access, and aging utilities.", permitAuthority: "Memphis and Shelby County planning and Code Enforcement coordinate local review; TDEC, floodplain, MLGW, fire, drainage, and right-of-way owners can be separate.", codeContext: "Confirm Memphis and Shelby criteria for zoning, drainage, floodplain, erosion, utility, right-of-way, and TDEC construction-stormwater coverage.", localConditions: c.memphis, projectTypes: "logistics yards, ADU sites, additions, industrial redevelopment, warehouses, parking, and frontage", sections: [{ heading: "River and Wolf outlets need capacity", body: "A Memphis plan should state receiving water, tailwater, floodway, pump or gravity assumptions, easements, downstream capacity, and maintenance—not just a nearby ditch." }, { heading: "Flat ground still changes with small work", body: "An ADU, driveway, or warehouse addition can redirect water toward a slab, neighbor, street, or utility corridor. Show grade, floor, access, and drainage together." }, { heading: "Logistics frontage is a civil approval", body: "Truck access, curb cuts, fire lanes, hydrants, utility crossings, sediment control, and construction staging need current owner criteria." }], permitSteps: ["Confirm Memphis or Shelby jurisdiction, zoning, flood zone, watershed, disturbance, logistics frontage, and MLGW service.", "Obtain survey and request outlet, utility, fire-access, flood, erosion, dewatering, and right-of-way criteria.", "Coordinate detention or conveyance, finished floors, ADU access, truck routes, erosion controls, utilities, and foundations.", "Track Memphis, TDEC, flood, MLGW, and fire comments by sheet and retain calculations, maintenance, and as-built records."], faqs: [{ question: "Does a Memphis detached ADU need civil review?", answer: "New impervious area, driveway, floodplain, sewer tie, drainage change, or utility connection can create civil scope; the AHJ decides." }, { question: "What controls a Memphis river outlet?", answer: "River stage, tailwater, floodway, survey, alluvial grade, downstream capacity, easements, erosion, and maintenance ownership control it." }, { question: "Why can a logistics grading correction affect structure?", answer: "Truck grades, finished floor, flood protection, foundations, utilities, fire lanes, and drainage can all move together." }], sources: src.memphis },
  { serviceSlug: "energy-compliance", title: "Memphis Tennessee Energy Compliance", description: "Energy documentation for Memphis logistics, healthcare, homes, and additions.", h1: "Energy Compliance in Memphis, Tennessee", kicker: "2018 baseline, humid loads, and logistics schedules", lede: "Memphis energy records must identify the accepted Tennessee path and reflect humid cooling, New Madrid-region operations, flood repairs, and large logistics schedules.", permitAuthority: "Memphis Code Enforcement establishes the local intake; confirm the Tennessee energy edition, local method, occupancy, and alteration provisions.", codeContext: "The statewide commercial baseline is based on the 2018 IECC with ASHRAE 90.1-2016 alternate; Memphis confirms the applicable local path and forms.", localConditions: c.memphis, projectTypes: "distribution buildings, healthcare, offices, retail, ADUs, multifamily, and tenant improvements", sections: [{ heading: "Warehouse schedules are not office schedules", body: "Dock doors, storage height, ventilation, lighting, plug loads, and occupancy need explicit inputs. A generic commercial profile can misstate a Memphis logistics building." }, { heading: "Humidity and flood repairs meet", body: "Air sealing, latent cooling, equipment elevation, glazing, controls, and replacement assemblies should be coordinated after a river or storm repair." }, { heading: "Seismic and MEP records must agree", body: "Equipment substitutions, anchorage, lighting, and ventilation changes can affect compliance and structural sheets; update both records when Code comments." }], permitSteps: ["Ask Memphis Code Enforcement which 2018 IECC or ASHRAE path, forms, occupancy, and alteration rules apply.", "Collect shell, glazing, lighting, HVAC, ventilation, service-water, controls, dock, and utility schedule inputs.", "Reconcile the model with flood repairs, seismic anchorage, structural openings, MEP selections, and ADU boundaries.", "Return numbered energy corrections and retain revised forms, model inputs, substitutions, controls, commissioning, and field checks."], faqs: [{ question: "How should a Memphis warehouse energy model handle docks?", answer: "Document dock-door operation, storage occupancy, ventilation, lighting, plug loads, and heating or cooling zones rather than using an office schedule." }, { question: "Does Memphis compliance promise lower logistics costs?", answer: "No. Weather, schedules, equipment, controls, construction, maintenance, and operation determine actual energy use." }, { question: "What is a useful Memphis energy correction?", answer: "Name the changed schedule, envelope or equipment input, affected structural or MEP sheet, and coordinated response." }], sources: src.memphis },
  { serviceSlug: "pe-stamped-drawings", title: "Memphis Tennessee PE-Stamped Drawings", description: "Defined PE responsibility for Memphis seismic, flood, utility, and logistics packages.", h1: "PE-Stamped Drawings in Memphis, Tennessee", kicker: "New Madrid and Mississippi corridor evidence", lede: "A Memphis sealed package should state its seismic, flood, alluvial-ground, utility, existing-condition, and discipline boundaries.", permitAuthority: "Memphis Code Enforcement is the building path; Shelby Planning, MLGW, fire, flood, TDEC, health, and public works authorities retain separate decisions while the PE defines scope.", codeContext: "The PE identifies the 2018 IBC baseline or applicable local adoption, seismic, flood, soil, energy, existing-building, inspection, and delegated-design basis.", localConditions: c.memphis, projectTypes: "logistics, structural and civil sets, MEP systems, ADUs, additions, clinics, and industrial reuse", sections: [{ heading: "A Memphis seal needs seismic and flood evidence", body: "Survey, flood elevation, geotechnical data, seismic parameters, existing framing, utility records, and operating scope support responsible judgment." }, { heading: "Logistics projects have many owners", body: "Code, Planning, MLGW, fire, floodplain, TDEC, health, county, and public-way reviewers may each control a decision; document the handoffs." }, { heading: "Repairs and substitutions stay controlled", body: "A discovered footing, flood repair, equipment anchorage change, or contractor substitution can alter the design. The PE evaluates and controls the revision." }], permitSteps: ["Identify Memphis Code, Shelby Planning, fire, flood, TDEC, MLGW, health, and right-of-way handoffs.", "Assemble survey, elevation, geotechnical, seismic, existing-condition, architectural, equipment, drainage, and utility records.", "Submit authenticated sheets through the local process while separating owner, specialty, contractor, and delegated documents.", "Track comments, inspections, RFIs, flood or seismic discoveries, and substitutions; issue controlled revisions for changed scope."], faqs: [{ question: "Does a Memphis PE stamp replace flood or seismic approval?", answer: "No. It communicates responsibility for a defined scope; city, county, fire, flood, TDEC, utility, and public-way authorities retain decisions." }, { question: "Can a Memphis repair rely on photographs?", answer: "The PE decides whether evidence is sufficient; flood, seismic, framing, foundation, soil, utility, and anchorage conditions may require field investigation." }, { question: "How are Memphis sealed corrections returned?", answer: "Map comments to calculations and sheets, coordinate seismic, flood, civil, structural, MEP, and planning effects, and submit a controlled response." }], sources: src.memphis },
  // Knoxville, Chattanooga, and Clarksville are explicit below.
  { serviceSlug: "structural-engineering", title: "Knoxville Tennessee Structural Engineering", description: "Structural design for Knoxville ridges, karst, river sites, and additions.", h1: "Structural Engineering in Knoxville, Tennessee", kicker: "Tennessee Valley slopes and existing framing", lede: "Knoxville structural work must account for ridges, karst, residual soils, Tennessee River flooding, heavy rain, and freeze-thaw around older buildings.", permitAuthority: "Knoxville Plans Review and Inspections is the city AHJ; Knox County, KUB, floodplain, steep-slope, fire, historic, and stormwater reviews may be separate.", codeContext: "Confirm Tennessee's 2018 IBC commercial baseline or applicable local adoption, amendments, slope, karst, flood, wind, seismic, existing-building, and inspections.", localConditions: c.knoxville, projectTypes: "hillside ADUs, residential additions, river work, historic buildings, schools, and commercial reuse", sections: [{ heading: "Knoxville ridges require stepped thinking", body: "Stepped footings, retaining, temporary support, and access may govern a ridge addition. Survey and geotechnical evidence should precede a connection detail." }, { heading: "Karst and river conditions differ", body: "A limestone void and a Tennessee River floodplain create different foundation and elevation decisions. The structural basis should state which condition controls." }, { heading: "Freeze-thaw exposes field changes", body: "Masonry, stairs, retaining, and utility penetrations can move after demolition or winter weather. Correction responses should include affected civil and MEP work." }], permitSteps: ["Confirm Knoxville address, Plans Review intake, zoning, slope, karst, flood map, code path, and existing permits.", "Record framing, footings, grades, rock, moisture, equipment, and demolition limits and flag field verification.", "Coordinate stepped foundations, retaining, flood details, fire access, MEP penetrations, wind and seismic criteria, and inspections.", "Return numbered city comments and control revisions when excavation, freeze damage, or substitution changes design."], faqs: [{ question: "Does a Knoxville hillside ADU need structural engineering?", answer: "New foundations, retaining, bearing-wall work, karst, flood, roof changes, or an uncertain existing connection can create scope; the AHJ and engineer decide." }, { question: "Why do Knoxville sites need both geotechnical and flood review?", answer: "Karst or residual soils govern subsurface support while river or creek elevation governs water exposure; one source does not answer both." }, { question: "How should Knoxville corrections be closed?", answer: "Map comments to calculations and sheets, coordinate slope, civil, MEP, and architectural effects, and submit the controlled response." }], sources: src.knoxville },
  { serviceSlug: "mep-engineering", title: "Knoxville Tennessee MEP Engineering", description: "MEP coordination for Knoxville healthcare, homes, ridges, and river projects.", h1: "MEP Engineering in Knoxville, Tennessee", kicker: "KUB service, karst routing, and four-season systems", lede: "Knoxville MEP documents must manage humid summers, winter freezes, ridge access, karst routing, flood elevation, and KUB capacity.", permitAuthority: "Knoxville Plans Review and Inspections receives the record; KUB, fire, floodplain, steep-slope, historic, and county staff may review separate elements.", codeContext: "Confirm the Tennessee 2018 commercial baseline and Knoxville's accepted mechanical, plumbing, electrical, energy, fire, fuel-gas, and accessibility requirements.", localConditions: c.knoxville, projectTypes: "healthcare, hillside additions, ADUs, laboratories, restaurants, offices, and schools", sections: [{ heading: "KUB data should precede schedules", body: "Electric, water, sewer, pressure, fire flow, backflow, gas, and shutdown information should be requested before an addition or clinic service is sized." }, { heading: "Ridges change gravity systems", body: "Pumps, sewer inverts, condensate, equipment access, retaining penetrations, and emergency power should respond to the surveyed slope and flood basis." }, { heading: "Healthcare corrections require coordination", body: "Ventilation, electrical distribution, fire, domestic water, controls, and shutdown phasing should be revised together after review comments." }], permitSteps: ["Open Knoxville occupancy records and identify Plans Review, KUB, fire, flood, slope, historic, and right-of-way reviews.", "Request KUB water, sewer, pressure, fire-flow, electric, gas, backflow, and shutdown data.", "Coordinate feeders, risers, ventilation, condensate, pumps, ADU service, controls, emergency power, and slope penetrations.", "Return numbered MEP corrections and preserve utility letters, calculations, substitutions, commissioning, and inspections."], faqs: [{ question: "Can a Knoxville ADU share KUB service?", answer: "Load, feeder, water, sewer, slope, pump, ventilation, hot water, flood, and fire requirements must be checked at the address." }, { question: "What does a Knoxville ridge change for MEP design?", answer: "Gravity sewer, pump selection, condensate, access, utility routing, retaining penetrations, and outage planning can all change." }, { question: "How should Knoxville MEP comments be handled?", answer: "Revise the affected riser, load, equipment, controls, fire, and phasing documents together and return the numbered response." }], sources: src.knoxville },
  { serviceSlug: "civil-engineering", title: "Knoxville Tennessee Civil Engineering", description: "Civil design for Knoxville slopes, karst, floodplains, utilities, and additions.", h1: "Civil Engineering in Knoxville, Tennessee", kicker: "Tennessee Valley watershed and ridge grading", lede: "Knoxville civil plans must route heavy rain across ridges and karst while protecting Tennessee River flood areas, access, and existing neighborhoods.", permitAuthority: "Knoxville Plans Review and Inspections is the city path; KUB, Knox County, TDEC, floodplain, fire, slope, and right-of-way decisions can be separate.", codeContext: "Confirm Knoxville grading, stormwater, karst, slope, floodplain, erosion, utility, right-of-way, and TDEC construction-stormwater requirements.", localConditions: c.knoxville, projectTypes: "hillside ADUs, additions, subdivisions, medical sites, river redevelopment, and frontage", sections: [{ heading: "Karst changes infiltration", body: "A Knoxville detention or infiltration concept should use geotechnical evidence and avoid concentrating water over suspected voids. Receiving creek and river conditions still control the outlet." }, { heading: "Ridge access is part of grading", body: "A small addition can change retaining, stairs, accessible paths, finished floors, utility profiles, and runoff toward a lower neighbor." }, { heading: "TDEC and local controls have different jobs", body: "Construction coverage, erosion and dewatering, local drainage, floodplain, and permanent maintenance should be tracked as separate decisions." }], permitSteps: ["Confirm Knoxville jurisdiction, zoning, watershed, flood zone, karst or slope, disturbance, frontage, and KUB area.", "Obtain survey and request outlet, geotechnical, utility, fire, flood, erosion, dewatering, and right-of-way criteria.", "Coordinate grading, retaining, conveyance, finished floors, ADU access, erosion controls, utilities, and foundations.", "Track city, TDEC, KUB, flood, and fire comments by sheet and retain calculations, maintenance, and as-builts."], faqs: [{ question: "Does a Knoxville ridge ADU need civil work?", answer: "A detached pad, retaining, driveway, karst, floodplain, sewer tie, or drainage change can create civil scope; the AHJ decides." }, { question: "What controls a Knoxville creek outlet?", answer: "Survey, karst, tailwater, flood, downstream capacity, erosion, easements, local criteria, and maintenance ownership control it." }, { question: "Why can a Knoxville grading change affect the house?", answer: "Retaining, foundation exposure, finished floor, access, utilities, and concentrated runoff can all move." }], sources: src.knoxville },
  { serviceSlug: "energy-compliance", title: "Knoxville Tennessee Energy Compliance", description: "Energy documentation for Knoxville ridge, healthcare, residential, and commercial work.", h1: "Energy Compliance in Knoxville, Tennessee", kicker: "Four-season envelope and humid-climate records", lede: "Knoxville energy documentation must align the Tennessee baseline with cooler ridge conditions, humid summers, karst or flood repairs, and actual occupancy.", permitAuthority: "Knoxville Plans Review and Inspections establishes the intake; confirm the effective energy edition, method, forms, and alteration provisions.", codeContext: "Confirm the 2018 IECC commercial baseline or ASHRAE 90.1-2016 alternate and Knoxville's accepted local path, residential provisions, amendments, and testing.", localConditions: c.knoxville, projectTypes: "healthcare, schools, homes, ADUs, offices, laboratories, and additions", sections: [{ heading: "Ridge sites still need real schedules", body: "Healthcare, classrooms, homes, and offices have different ventilation, occupancy, and setback inputs. Use the actual conditioned boundary and envelope." }, { heading: "Cooler nights do not remove latent load", body: "Summer humidity, solar gain, heating, freeze protection, ventilation recovery, and controls should match Knoxville equipment and operating assumptions." }, { heading: "Repairs alter more than insulation", body: "Flood or moisture repair can change windows, air barriers, equipment, and controls. Update the compliance record and MEP sheets together." }], permitSteps: ["Ask Knoxville which Tennessee energy path, forms, occupancy, and alteration provisions apply.", "Collect envelope, glazing, lighting, HVAC, ventilation, service-water, controls, schedules, and utility inputs.", "Reconcile the record with ridge, flood, roof, karst, structural opening, MEP, fire, and ADU boundaries.", "Return numbered corrections and retain revised forms, model inputs, substitutions, sequences, commissioning, and field checks."], faqs: [{ question: "How should a Knoxville ADU enter energy review?", answer: "Conditioned area, relationship to the house, alteration scope, existing shell, and the city's accepted method determine the documents." }, { question: "Does Knoxville compliance guarantee comfort?", answer: "No. Weather, ridge exposure, construction, controls, occupants, equipment, operation, and maintenance affect results." }, { question: "What belongs in a Knoxville energy response?", answer: "Name the changed input, affected assembly or MEP sheet, method, and coordinated revision returned to Plans Review." }], sources: src.knoxville },
  { serviceSlug: "pe-stamped-drawings", title: "Knoxville Tennessee PE-Stamped Drawings", description: "Defined PE responsibility for Knoxville ridge, karst, flood, and utility packages.", h1: "PE-Stamped Drawings in Knoxville, Tennessee", kicker: "Valley evidence and multi-reviewer responsibility", lede: "A Knoxville sealed package should identify ridge, karst, flood, utility, existing-condition, and discipline assumptions before construction.", permitAuthority: "Knoxville Plans Review and Inspections is the AHJ; KUB, Knox County, fire, flood, TDEC, slope, historic, and right-of-way authorities retain decisions while the PE defines scope.", codeContext: "The PE identifies the applicable Tennessee code baseline, energy path, Knoxville checklist, soil, slope, karst, flood, inspections, and delegated-design basis.", localConditions: c.knoxville, projectTypes: "structural and civil sets, MEP systems, hillside ADUs, healthcare, additions, and river work", sections: [{ heading: "Knoxville evidence supports the seal", body: "Survey, contours, geotechnical or karst data, existing framing, utility records, flood information, and owner scope support responsible engineering judgment." }, { heading: "Valley projects cross agencies", body: "Plans Review, KUB, fire, floodplain, TDEC, slope, historic, county, and public-way reviewers may each own a decision; state the handoffs." }, { heading: "Field conditions require evaluation", body: "A void, footing, utility conflict, changed retaining wall, or substitution can alter sealed work. The PE evaluates and controls a revision." }], permitSteps: ["Identify Knoxville, Knox County, KUB, fire, flood, TDEC, slope, historic, and right-of-way handoffs.", "Assemble survey, contours, geotechnical, existing-condition, architectural, equipment, drainage, and utility records.", "Submit authenticated sheets through the local process while separating utility-owner, specialty, contractor, and delegated documents.", "Track comments, inspections, RFIs, karst discoveries, and substitutions; issue controlled revisions for changed scope."], faqs: [{ question: "Does a Knoxville PE stamp replace slope or flood review?", answer: "No. It communicates responsibility for a defined scope; city, county, fire, flood, TDEC, utility, historic, and public-way authorities retain decisions." }, { question: "Can a Knoxville ridge package rely on photographs?", answer: "The PE decides whether survey, geotechnical, existing-condition, utility, and field evidence are adequate." }, { question: "How are Knoxville sealed comments handled?", answer: "Map comments to calculations and sheets, coordinate slope, civil, structural, MEP, and planning effects, and submit a controlled response." }], sources: src.knoxville },
  // Chattanooga
  { serviceSlug: "structural-engineering", title: "Chattanooga Tennessee Structural Engineering", description: "Structural design for Chattanooga escarpments, river sites, karst, and reuse.", h1: "Structural Engineering in Chattanooga, Tennessee", kicker: "Escarpment, river, and industrial load paths", lede: "Chattanooga structural work must reconcile steep escarpments, karst, Tennessee River flood, intense rainfall, and industrial reuse conditions.", permitAuthority: "Chattanooga Land Development Office is the city AHJ; Hamilton County, water, sewer, floodplain, fire, stormwater, and historic reviews may be separate.", codeContext: "Confirm Tennessee's 2018 IBC commercial baseline or local adoption, amendments, slope, karst, flood, wind, seismic, existing-building, and inspection criteria.", localConditions: c.chattanooga, projectTypes: "riverfront reuse, hillside additions, ADUs, warehouses, schools, historic buildings, and industrial alterations", sections: [{ heading: "Escarpments need stepped support", body: "A Chattanooga addition can require retaining, rock cuts, temporary support, and careful foundation sequencing. Survey and geotechnical evidence should set the connection." }, { heading: "River flood and karst are different", body: "Flood elevation governs water exposure while limestone voids govern support and drainage concentration. The structural basis should not collapse both into one generic note." }, { heading: "Industrial reuse has hidden loads", body: "Openings, cranes or equipment, vibration, fire protection, and old masonry should be addressed together in plan-check calculations and details." }], permitSteps: ["Confirm Chattanooga address, Land Development intake, slope, karst, flood map, zoning, and existing permits.", "Record framing, foundations, rock, grades, flood or moisture damage, equipment, and demolition limits and identify field checks.", "Coordinate retaining, foundations, flood details, fire access, MEP penetrations, equipment loads, and inspections.", "Return numbered city comments and control revisions when excavation, old construction, or substitution changes design."], faqs: [{ question: "Does a Chattanooga hillside ADU need structural engineering?", answer: "New foundations, retaining, karst, roof or wall work, flood exposure, or an uncertain existing connection can create scope; the AHJ and engineer decide." }, { question: "Why do Chattanooga river sites need geotechnical evidence?", answer: "Flood elevation does not describe rock, fill, residual soil, or foundation support; both water and ground conditions affect the design." }, { question: "How should Chattanooga reuse corrections be answered?", answer: "Tie comments to load-path calculations, equipment or vibration assumptions, fire and MEP interfaces, and a controlled revision." }], sources: src.chattanooga },
  { serviceSlug: "mep-engineering", title: "Chattanooga Tennessee MEP Engineering", description: "MEP coordination for Chattanooga riverfront, industrial, residential, and commercial work.", h1: "MEP Engineering in Chattanooga, Tennessee", kicker: "Escarpment routing and river-ready systems", lede: "Chattanooga MEP projects need utility capacity, humid-climate control, equipment access on grades, and flood-aware routing for occupied or industrial buildings.", permitAuthority: "Chattanooga Land Development receives the local record; Tennessee-American Water, sewer, fire, floodplain, stormwater, and county reviewers can be separate.", codeContext: "Confirm Tennessee's 2018 commercial baseline and Chattanooga's accepted mechanical, plumbing, electrical, energy, fuel-gas, fire, and accessibility provisions.", localConditions: c.chattanooga, projectTypes: "industrial reuse, riverfront offices, restaurants, ADUs, schools, healthcare, and warehouses", sections: [{ heading: "Water and sewer service need letters", body: "Tennessee-American Water and sewer owners should confirm pressure, capacity, fire flow, backflow, and shutdown conditions before a reuse or ADU load is designed." }, { heading: "Grades and flood affect routing", body: "Pumps, sewer inverts, condensate, equipment elevation, access, and emergency power should match escarpment and river elevations." }, { heading: "Industrial corrections cross life safety", body: "Process exhaust, ventilation, electrical distribution, fire systems, controls, and shutdowns should be revised together after review." }], permitSteps: ["Open the Chattanooga occupancy record and identify Land Development, water, sewer, fire, flood, stormwater, and right-of-way reviews.", "Request utility pressure, sewer, fire-flow, electric, gas, backflow, and shutdown data for the project address.", "Coordinate feeders, risers, ventilation, process waste, condensate, pumps, ADU service, controls, and emergency power.", "Return numbered MEP corrections and retain utility letters, calculations, substitutions, commissioning, and inspections."], faqs: [{ question: "Can a Chattanooga ADU share an existing service?", answer: "Load, water, sewer, slope, flood, ventilation, hot water, fire, and the utility connection process must be checked for the address." }, { question: "What does an escarpment change for MEP?", answer: "Gravity drainage, pumps, equipment access, utility trenches, condensate, retaining penetrations, and sequencing can all change." }, { question: "How should Chattanooga industrial MEP comments be closed?", answer: "Revise process, fire, electrical, ventilation, controls, and structural interfaces together and submit the numbered response." }], sources: src.chattanooga },
  { serviceSlug: "civil-engineering", title: "Chattanooga Tennessee Civil Engineering", description: "Civil design for Chattanooga escarpments, river flood, karst, and redevelopment.", h1: "Civil Engineering in Chattanooga, Tennessee", kicker: "Tennessee River and ridge watershed grading", lede: "Chattanooga civil plans must route intense rain through karst and steep terrain while protecting river flood areas, industrial access, and neighboring slopes.", permitAuthority: "Chattanooga Land Development is the local path; Hamilton County, TDEC, water, sewer, floodplain, fire, stormwater, and right-of-way decisions may be separate.", codeContext: "Confirm Chattanooga grading, karst, slope, stormwater, floodplain, erosion, utility, right-of-way, and TDEC construction-stormwater requirements.", localConditions: c.chattanooga, projectTypes: "riverfront redevelopment, hillside ADUs, additions, industrial yards, parking, and frontage", sections: [{ heading: "Karst limits infiltration choices", body: "A Chattanooga drainage concept should use geotechnical evidence, protect void-sensitive ground, and identify the Tennessee River or creek receiving system and maintenance owner." }, { heading: "Escarpments make access a design issue", body: "An addition can change retaining, stairs, accessible routes, finished floors, utility profiles, and runoff toward a lower parcel." }, { heading: "Industrial sites need dewatering records", body: "TDEC coverage, erosion, excavation dewatering, utility locates, fire routes, and permanent conveyance should be sequenced separately." }], permitSteps: ["Confirm Chattanooga jurisdiction, zoning, watershed, flood zone, karst or slope, disturbance, frontage, and water service.", "Obtain survey and request outlet, geotechnical, utility, fire, flood, erosion, dewatering, and right-of-way criteria.", "Coordinate grading, retaining, conveyance, finished floors, ADU access, erosion controls, utilities, and foundations.", "Track city, TDEC, water, flood, and fire comments by sheet and retain calculations, maintenance, and as-builts."], faqs: [{ question: "Does a Chattanooga hillside ADU need civil review?", answer: "A detached pad, retaining, driveway, karst, floodplain, sewer tie, or drainage change can create scope; the AHJ decides." }, { question: "What controls a Chattanooga river outlet?", answer: "River stage, tailwater, karst, survey, downstream capacity, erosion, easements, local criteria, and maintenance ownership control it." }, { question: "Why can Chattanooga grading affect structure?", answer: "Retaining, foundation exposure, finished floor, access, utilities, and slope runoff change with the grade." }], sources: src.chattanooga },
  { serviceSlug: "energy-compliance", title: "Chattanooga Tennessee Energy Compliance", description: "Energy documentation for Chattanooga riverfront, industrial, residential, and addition projects.", h1: "Energy Compliance in Chattanooga, Tennessee", kicker: "Humid climate, industrial schedules, and slope repairs", lede: "Chattanooga energy records must align the Tennessee baseline with river humidity, industrial schedules, hill exposure, flood repairs, and actual shell details.", permitAuthority: "Chattanooga Land Development establishes the local intake; confirm the Tennessee energy edition, forms, method, and alteration provisions.", codeContext: "Confirm the 2018 IECC commercial baseline or ASHRAE 90.1-2016 alternate and the applicable Chattanooga local path and amendments.", localConditions: c.chattanooga, projectTypes: "industrial reuse, offices, restaurants, schools, ADUs, healthcare, and riverfront housing", sections: [{ heading: "Industrial schedules need real loads", body: "Process ventilation, shifts, equipment, dock operation, occupancy, and controls should be documented rather than using a generic office schedule." }, { heading: "Slope and flood repairs change the shell", body: "Glazing, air barriers, insulation, equipment elevation, condensate, and controls should match the surveyed grade and flood or storm-repair scope." }, { heading: "Corrections cross process and building systems", body: "A revised exhaust, motor, lighting, window, or control sequence can alter both compliance and MEP documentation; update them together." }], permitSteps: ["Ask Chattanooga which 2018 IECC or ASHRAE path, forms, occupancy, and alteration provisions apply.", "Collect shell, glazing, lighting, HVAC, process, ventilation, service-water, controls, schedules, and utility inputs.", "Reconcile the record with slope, flood, structural openings, MEP, fire, process, and ADU boundaries.", "Return numbered corrections and retain revised forms, model inputs, substitutions, controls, commissioning, and field checks."], faqs: [{ question: "How should Chattanooga industrial energy schedules be set?", answer: "Use documented process, shift, ventilation, equipment, dock, and occupancy schedules that represent the facility's operation." }, { question: "Does Chattanooga compliance guarantee industrial savings?", answer: "No. Actual performance depends on process operation, weather, controls, equipment, construction, and maintenance." }, { question: "What belongs in a Chattanooga energy response?", answer: "Name the changed schedule or equipment input, affected shell or process sheet, method, and coordinated revision." }], sources: src.chattanooga },
  { serviceSlug: "pe-stamped-drawings", title: "Chattanooga Tennessee PE-Stamped Drawings", description: "Defined PE responsibility for Chattanooga escarpment, river, karst, and industrial packages.", h1: "PE-Stamped Drawings in Chattanooga, Tennessee", kicker: "River and ridge evidence for engineering scope", lede: "A Chattanooga sealed package should state its escarpment, karst, river, utility, process, existing-condition, and discipline assumptions.", permitAuthority: "Chattanooga Land Development is the local AHJ; Hamilton County, water, sewer, fire, flood, TDEC, and right-of-way authorities retain separate decisions while the PE defines scope.", codeContext: "The PE identifies the applicable Tennessee code baseline, energy path, Chattanooga checklist, slope, karst, flood, process, inspections, and delegated-design basis.", localConditions: c.chattanooga, projectTypes: "structural and civil sets, MEP systems, industrial reuse, hillside ADUs, riverfront, and public work", sections: [{ heading: "A Chattanooga seal needs terrain evidence", body: "Survey, contours, geotechnical or karst information, flood data, existing framing, utility records, process scope, and owner requirements support professional judgment." }, { heading: "Industrial and public decisions differ", body: "Land Development, water, sewer, fire, flood, TDEC, county, process owners, and public-way staff may each control a decision; show the handoffs." }, { heading: "Rock and utility discoveries require review", body: "A void, changed retaining wall, buried line, equipment substitution, or demolition discovery can alter sealed work. The PE evaluates and controls the revision." }], permitSteps: ["Identify Chattanooga, Hamilton County, water, sewer, fire, flood, TDEC, process, and right-of-way handoffs.", "Assemble survey, contours, geotechnical, existing-condition, architectural, process, equipment, drainage, and utility records.", "Submit authenticated sheets through the local process while separating owner, specialty, contractor, and delegated documents.", "Track comments, inspections, RFIs, rock discoveries, and substitutions; issue controlled revisions for changed scope."], faqs: [{ question: "Does a Chattanooga PE stamp replace river or slope approval?", answer: "No. It communicates responsibility for a defined scope; city, county, fire, flood, TDEC, utility, and public-way authorities retain decisions." }, { question: "Can a Chattanooga industrial package use photographs only?", answer: "The PE decides whether survey, geotechnical, existing-condition, utility, process, and field evidence are adequate." }, { question: "How are Chattanooga sealed corrections returned?", answer: "Map comments to calculations and sheets, coordinate terrain, process, civil, structural, MEP, and planning effects, and submit a controlled response." }], sources: src.chattanooga },
  // Clarksville
  { serviceSlug: "structural-engineering", title: "Clarksville Tennessee Structural Engineering", description: "Structural design for Clarksville river, karst, growth, and residential projects.", h1: "Structural Engineering in Clarksville, Tennessee", kicker: "Cumberland flood and fast-growth load paths", lede: "Clarksville structures must address Cumberland River flood exposure, rolling clay and limestone, karst, severe storms, and rapid residential construction.", permitAuthority: "Clarksville Development Services and the Regional Planning Commission are the local path; Montgomery County, floodplain, fire, gas and water, and public works may be separate.", codeContext: "Confirm Tennessee's 2018 IBC commercial baseline or applicable local adoption, amendments, flood, soil, karst, wind, existing-building, and inspection criteria.", localConditions: c.clarksville, projectTypes: "ADUs, subdivisions, residential additions, schools, retail, military-adjacent work, and warehouses", sections: [{ heading: "Growth makes existing records important", body: "A new Clarksville addition can meet altered framing, fill, utility work, or shallow footings. Verify the existing structure before sizing openings or connections." }, { heading: "Cumberland flood meets rolling ground", body: "Flood elevation, clay, limestone, runoff, and slope can affect foundation, retaining, access, and MEP penetrations differently across the parcel." }, { heading: "Storm corrections need a coordinated set", body: "Wind, roof, drainage, fire access, and temporary support comments should be answered across structural, civil, and architectural sheets." }], permitSteps: ["Confirm Clarksville address, Development Services and regional planning intake, zoning, flood map, code path, and existing permits.", "Record framing, footings, soil, grades, flood or storm damage, equipment, and demolition limits and flag field checks.", "Coordinate foundations, retaining, flood details, fire access, MEP penetrations, wind criteria, and inspections.", "Return numbered corrections through the local AHJ and control revisions for concealed conditions or substitutions."], faqs: [{ question: "When can a Clarksville ADU need engineering?", answer: "New foundations, wall or roof work, flood, karst, retaining, or uncertain existing connections can create scope; the AHJ and engineer decide." }, { question: "Why is Cumberland flood review relevant to a small addition?", answer: "Elevation can affect foundations, stairs, access, utilities, and flood openings even when the new floor area is limited." }, { question: "How should Clarksville structural comments be closed?", answer: "Map comments to sheets and calculations, coordinate civil and MEP changes, and return the controlled response before construction." }], sources: src.clarksville },
  { serviceSlug: "mep-engineering", title: "Clarksville Tennessee MEP Engineering", description: "MEP coordination for Clarksville growth, homes, schools, and commercial work.", h1: "MEP Engineering in Clarksville, Tennessee", kicker: "Gas, water, flood, and growth coordination", lede: "Clarksville MEP documents must connect fast residential growth to Clarksville Gas and Water capacity, humid cooling, flood elevation, and reliable winter operation.", permitAuthority: "Clarksville Development Services receives the local building record; Regional Planning, Gas and Water, fire, floodplain, and public works can review separate systems.", codeContext: "Confirm Tennessee's 2018 commercial baseline and Clarksville's accepted mechanical, plumbing, electrical, energy, fuel-gas, fire, and accessibility requirements.", localConditions: c.clarksville, projectTypes: "ADUs, residential additions, schools, restaurants, offices, retail, and warehouses", sections: [{ heading: "Clarksville Gas and Water sets the basis", body: "Water, sewer, pressure, gas, fire flow, backflow, electric, and shutdown information should precede fixture and equipment schedules for a growing subdivision or ADU." }, { heading: "Flood and karst affect service routing", body: "Equipment elevation, gravity sewer, pumps, condensate, utility penetrations, controls, and emergency power should match surveyed grade and flood conditions." }, { heading: "New neighborhoods need phasing", body: "Temporary service, fire systems, domestic water, ventilation, and shutdowns should be tracked when development or occupied work receives corrections." }], permitSteps: ["Open Clarksville occupancy records and identify Development Services, Planning, Gas and Water, fire, flood, and right-of-way reviews.", "Request utility pressure, sewer, gas, fire-flow, electric, backflow, and shutdown data for the address.", "Coordinate feeders, risers, ventilation, condensate, pumps, ADU connections, controls, emergency power, and grade interfaces.", "Return numbered MEP corrections and retain utility letters, calculations, substitutions, commissioning, and inspections."], faqs: [{ question: "Can a Clarksville ADU share Gas and Water service?", answer: "Load, pressure, sewer, gas, flood, ventilation, hot water, fire, and connection requirements must be verified for the address." }, { question: "What does Clarksville growth change for MEP?", answer: "Utility capacity, phasing, fire flow, service timing, and temporary systems can be project-specific rather than inferred from a nearby subdivision." }, { question: "How should Clarksville MEP comments be handled?", answer: "Revise risers, loads, equipment, controls, fire, and phasing documents together and return a numbered response." }], sources: src.clarksville },
  { serviceSlug: "civil-engineering", title: "Clarksville Tennessee Civil Engineering", description: "Civil grading, Cumberland flood, karst, utility, and subdivision design for Clarksville.", h1: "Civil Engineering in Clarksville, Tennessee", kicker: "Cumberland watershed and growth-area drainage", lede: "Clarksville civil plans must fit subdivisions and additions into rolling clay and limestone while moving stormwater away from Cumberland flood areas.", permitAuthority: "Clarksville Development Services and Regional Planning coordinate local review; TDEC, Gas and Water, floodplain, fire, county, and right-of-way decisions may be separate.", codeContext: "Confirm Clarksville zoning, subdivision, grading, stormwater, floodplain, erosion, karst, utility, frontage, and TDEC construction-stormwater requirements.", localConditions: c.clarksville, projectTypes: "subdivisions, ADU lots, residential additions, retail sites, schools, warehouses, and roadway frontage", sections: [{ heading: "Cumberland flood controls finished grades", body: "An outlet should identify river stage, tailwater, receiving capacity, floodway, easements, erosion, and maintenance rather than rely on a nearby ditch." }, { heading: "Rolling clay changes neighborhood drainage", body: "A driveway, ADU, or addition can send runoff onto a lower lot or foundation. Grades, retaining, finished floor, access, and utilities should be one plan." }, { heading: "Subdivision phasing needs erosion records", body: "TDEC coverage, temporary BMPs, utility locates, fire access, construction roads, and permanent conveyance should be sequenced and maintained separately." }], permitSteps: ["Confirm Clarksville or Montgomery jurisdiction, zoning, watershed, flood zone, karst or slope, disturbance, frontage, and utility area.", "Obtain survey and request outlet, geotechnical, utility, fire, flood, erosion, and right-of-way criteria.", "Coordinate grading, conveyance, retaining, finished floors, ADU access, erosion controls, utilities, and foundations.", "Track local, TDEC, flood, Gas and Water, and fire comments by sheet and retain calculations, maintenance, and as-builts."], faqs: [{ question: "Does a Clarksville subdivision ADU need civil review?", answer: "A detached pad, driveway, impervious area, floodplain, karst, sewer tie, or drainage change can create scope; the AHJ decides." }, { question: "What controls a Clarksville Cumberland outlet?", answer: "River stage, tailwater, survey, downstream capacity, floodway, erosion, easements, local criteria, and maintenance ownership control it." }, { question: "Why can Clarksville drainage change foundations?", answer: "Grades and retaining alter finished floor, foundation exposure, accessible paths, utility profiles, and concentrated runoff." }], sources: src.clarksville },
  { serviceSlug: "energy-compliance", title: "Clarksville Tennessee Energy Compliance", description: "Energy documentation for Clarksville subdivisions, homes, schools, and commercial work.", h1: "Energy Compliance in Clarksville, Tennessee", kicker: "2018 baseline and growth-area envelope records", lede: "Clarksville energy documentation must match the Tennessee baseline, local permit path, humid cooling, winter operation, and the actual repeated housing or commercial prototype.", permitAuthority: "Clarksville Development Services establishes the local intake; confirm the effective energy edition, forms, method, occupancy, and alteration provisions.", codeContext: "Confirm the 2018 IECC commercial baseline or ASHRAE 90.1-2016 alternate and the local residential or commercial path accepted by Clarksville.", localConditions: c.clarksville, projectTypes: "new homes, ADUs, additions, schools, offices, retail, and warehouses", sections: [{ heading: "Prototype homes still need site records", body: "Repeated plans should use actual conditioned boundaries, orientations, glazing, assemblies, and local site or flood limitations rather than assuming every lot performs identically." }, { heading: "Humid summers meet winter freezes", body: "Latent cooling, air sealing, heating, ventilation, controls, and occasional freeze protection should be consistent across the shell and MEP set." }, { heading: "Corrections propagate through a set", body: "A changed window, heat pump, lighting package, or control sequence can affect many units; update each affected form and sheet rather than leaving a copied result." }], permitSteps: ["Ask Clarksville which 2018 IECC or ASHRAE path, forms, occupancy, and alteration provisions apply.", "Collect actual prototype and site envelope, glazing, lighting, HVAC, ventilation, service-water, controls, and utility inputs.", "Reconcile the record with flood, grade, structural openings, MEP, fire, and ADU boundaries.", "Return numbered corrections and retain revised forms, model inputs, substitutions, sequences, commissioning, and field checks."], faqs: [{ question: "How should a Clarksville ADU enter energy review?", answer: "Conditioned area, relationship to the house, alteration scope, existing shell, and Clarksville's accepted method determine the documents." }, { question: "Does compliance guarantee savings for a subdivision?", answer: "No. Weather, construction, orientation, occupants, equipment, controls, operation, and maintenance determine actual use." }, { question: "What makes a Clarksville energy correction complete?", answer: "Name the changed prototype or site input, affected shell or MEP sheet, method, and coordinated revision returned to the AHJ." }], sources: src.clarksville },
  { serviceSlug: "pe-stamped-drawings", title: "Clarksville Tennessee PE-Stamped Drawings", description: "Defined PE responsibility for Clarksville growth, flood, utility, and subdivision packages.", h1: "PE-Stamped Drawings in Clarksville, Tennessee", kicker: "Cumberland evidence and development responsibility", lede: "A Clarksville sealed package should identify its river, karst, clay, utility, subdivision, existing-condition, and discipline boundaries.", permitAuthority: "Clarksville Development Services and Regional Planning are the local path; Gas and Water, fire, flood, TDEC, county, and right-of-way authorities retain decisions while the PE defines scope.", codeContext: "The PE identifies the applicable 2018 IBC baseline or local adoption, energy path, Clarksville checklist, flood, soil, karst, inspections, and delegated-design basis.", localConditions: c.clarksville, projectTypes: "structural and civil sets, MEP systems, subdivisions, ADUs, schools, and commercial work", sections: [{ heading: "Clarksville evidence supports responsibility", body: "Survey, contours, geotechnical or karst information, flood data, existing framing, utility records, phasing, and owner scope support professional judgment." }, { heading: "Development projects have separate owners", body: "Development Services, Planning, Gas and Water, fire, floodplain, TDEC, county, and public-way reviewers may each control a decision; show the handoffs." }, { heading: "Growth discoveries need controlled changes", body: "A buried utility, changed grade, hidden footing, flood repair, or contractor substitution can alter the accepted design. The PE evaluates and controls revisions." }], permitSteps: ["Identify Clarksville, Montgomery County, Planning, Gas and Water, fire, flood, TDEC, and right-of-way handoffs.", "Assemble survey, contours, geotechnical, existing-condition, architectural, equipment, drainage, phasing, and utility records.", "Submit authenticated sheets through the local process while separating owner, specialty, contractor, and delegated documents.", "Track comments, inspections, RFIs, utility discoveries, and substitutions; issue controlled revisions for changed scope."], faqs: [{ question: "Does a Clarksville PE stamp replace subdivision approval?", answer: "No. It communicates responsibility for a defined scope; city, county, fire, flood, TDEC, utility, planning, and public-way authorities retain decisions." }, { question: "Can a Clarksville growth package rely on old utility plans?", answer: "The PE decides whether survey, locates, geotechnical, existing-condition, utility, and field evidence are adequate." }, { question: "How are Clarksville sealed corrections returned?", answer: "Map comments to calculations and sheets, coordinate subdivision, flood, civil, structural, MEP, and planning effects, and submit a controlled response." }], sources: src.clarksville },
];

const page = (r: R): Batch2CoreServicePage => r;
const rewriteStep = (record: R, step: number, text: string): R => ({ ...record, permitSteps: record.permitSteps.map((value, index) => index === step ? text : value) as R["permitSteps"] });
const rewriteFaq = (record: R, faq: number, text: string): R => ({ ...record, faqs: record.faqs.map((value, index) => index === faq ? { ...value, answer: text } : value) as R["faqs"] });
const currentText = (text: string): string => text
  .replace(/Tennessee's 2018 commercial baseline/g, "Tennessee's current minimum-code rules")
  .replace(/Tennessee 2018 commercial baseline/g, "Tennessee's current minimum-code rules")
  .replace(/the 2018 commercial baseline/g, "current Tennessee minimum-code rules")
  .replace(/2018 IBC commercial baseline/g, "current Tennessee minimum-code requirements")
  .replace(/2018 IBC/g, "current Tennessee minimum-code requirements")
  .replace(/2018 IECC/g, "current Tennessee energy-code requirements");
const authoredRecords: R[] = records.map((record) => ({
  ...record,
  lede: currentText(record.lede),
  permitAuthority: currentText(record.permitAuthority),
  codeContext: currentText(record.codeContext),
  sections: record.sections.map((section) => ({ ...section, body: currentText(section.body) })) as R["sections"],
  permitSteps: record.permitSteps.map((step) => currentText(step).replace("Submit authenticated sheets", "Submit sheets identified and authenticated by the responsible PE")) as R["permitSteps"],
  faqs: record.faqs.map((faq) => ({ ...faq, answer: currentText(faq.answer) })) as R["faqs"],
})) as R[];
authoredRecords[12] = rewriteStep(authoredRecords[12], 1, "Obtain Knoxville's watershed outlet, karst investigation, utility, fire-access, flood, erosion, dewatering, and right-of-way criteria before fixing the civil route.");
authoredRecords[13] = rewriteStep(authoredRecords[13], 1, "Collect Knoxville-specific envelope, glazing, lighting, HVAC, ventilation, service-water, controls, schedules, and utility inputs for the accepted energy method.");
authoredRecords[14] = rewriteStep(authoredRecords[14], 1, "Assemble Knoxville's ridge, karst, existing-condition, utility, contour, equipment, and drainage evidence before the PE defines the sealed scope.");
authoredRecords[14] = rewriteStep(authoredRecords[14], 2, "Submit sheets identified and authenticated by the responsible PE through Knoxville's local process, separating utility-owner, specialty, contractor, and delegated documents.");
authoredRecords[14] = rewriteStep(authoredRecords[14], 3, "Track Knoxville comments, inspections, RFIs, karst discoveries, and substitutions; the responsible PE controls revisions when subsurface evidence changes.");
authoredRecords[17] = rewriteStep(authoredRecords[17], 1, "Obtain Chattanooga's river, escarpment, karst, utility, fire-access, flood, erosion, dewatering, and right-of-way criteria before fixing the civil route.");
authoredRecords[17] = rewriteStep(authoredRecords[17], 2, "Coordinate Chattanooga's grading, retaining, conveyance, finished floors, ADU access, erosion controls, utility corridors, and foundation interfaces.");
authoredRecords[18] = rewriteStep(authoredRecords[18], 3, "Return Chattanooga's revised energy forms, equipment inputs, control sequences, and commissioning evidence with the numbered local review response.");
authoredRecords[19] = rewriteStep(authoredRecords[19], 2, "Submit sheets identified and authenticated by the responsible PE through Chattanooga's local process, separating owner, specialty, contractor, and delegated documents.");
authoredRecords[19] = rewriteFaq(authoredRecords[19], 0, "The responsible Tennessee PE decides whether Chattanooga's river elevation, karst, foundation, utility, and concealed-condition evidence is adequate for the package.");
authoredRecords[21] = rewriteStep(authoredRecords[21], 3, "Return Clarksville's MEP corrections with revised utility letters, gas-and-water calculations, equipment selections, controls, commissioning, and inspection records.");
authoredRecords[23] = rewriteStep(authoredRecords[23], 3, "Return Clarksville's energy corrections with revised forms, prototype or site inputs, envelope details, equipment selections, and field-verification records.");
authoredRecords[24] = rewriteStep(authoredRecords[24], 2, "Submit sheets identified and authenticated by the responsible PE through Clarksville's local process, separating owner, specialty, contractor, and delegated documents.");
const tennesseeBatch4: Batch2StateExpansion = {
  stateSlug: "tennessee", stateName: "Tennessee", stateAbbrev: "TN",
  hub: {
    title: "Tennessee Engineering for River, Valley, and Ridge Projects",
    description: "Engineering coordination for Tennessee code, local AHJs, utilities, karst, slopes, floodplains, and stormwater.",
    h1: "Tennessee Engineering for River, Valley, and Ridge Conditions",
    kicker: "State baseline with local review",
     lede: "Tennessee's current minimum-code rules are administered through the applicable jurisdiction and State Fire Marshal process; local authorities still control address-specific permits, site reviews, and adopted paths.",
    sections: [
      { heading: "Current minimums, local intake", body: "Updated 2025 minimum-code rules do not eliminate local residential, zoning, fire, flood, utility, historic, and development requirements. Confirm the AHJ's adopted edition, amendments, and current intake path at the address." },
      { heading: "West, Middle, and East differ", body: "Memphis adds New Madrid influence, Mississippi flood, alluvium, and loess. Nashville and Clarksville add karst, clay, and Cumberland drainage; Knoxville and Chattanooga add ridges, escarpments, Tennessee River flood, and freeze-thaw." },
      { heading: "Stormwater and utilities are separate threads", body: "TDEC coverage, floodplain data, local drainage, dewatering, fire flow, utility connections, steep-slope or karst evidence, and right-of-way decisions may not be resolved by a building permit." },
      { heading: "ADUs and corrections need evidence", body: "ADUs, additions, tenant work, river redevelopment, and storm repairs should use measured conditions, utility records, explicit code and energy paths, and coordinated responses across disciplines." },
      { heading: "Stream and reservoir edges may need another handoff", body: "A project that fills, relocates, crosses, or builds near a stream may need Tennessee Department of Environment and Conservation review beyond local grading or building approval. Work affecting a TVA-managed shoreline can also involve a separate TVA process, depending on the location and proposed activity. Identify the waterbody, ordinary high-water or flood information, disturbance, access, and proposed stabilization before fixing the site plan. Keep agency correspondence and permit conditions with the civil record, and do not assume a stormwater authorization covers every aquatic-resource or shoreline decision for the specific site." },
    ],
    faqs: [
      { question: "Who reviews a Tennessee project?", answer: "The city or county AHJ administers local permits and inspections. State code, fire, flood, TDEC, utilities, historic, slope, TVA, and right-of-way authorities may have separate roles." },
      { question: "What conditions should be checked?", answer: "River flooding, New Madrid influence, karst, limestone, clay, alluvium, loess, slopes, heavy rain, humidity, freeze-thaw, and utility age can affect scope." },
      { question: "How should corrections be managed?", answer: "Keep comments, numbered responses, revised sheets and calculations, utility and environmental decisions, discipline checks, and field follow-up together." },
    ],
    sources: [
      { label: "Tennessee State Fire Marshal current codes", url: "https://www.tn.gov/commerce/fire/codes.html" },
      { label: "TDEC stormwater", url: "https://www.tn.gov/environment/program-areas/wr-water-resources/stormwater.html" },
      { label: "TDEC water resources", url: "https://www.tn.gov/environment/program-areas/wr-water-resources.html" },
      { label: "FEMA flood maps", url: "https://msc.fema.gov/portal/home" },
    ],
  },
  metros: [
    { slug: "nashville", name: "Nashville", county: "Davidson County", services: authoredRecords.slice(0, 5).map(page) },
    { slug: "memphis", name: "Memphis", county: "Shelby County", services: authoredRecords.slice(5, 10).map(page) },
    { slug: "knoxville", name: "Knoxville", county: "Knox County", services: authoredRecords.slice(10, 15).map(page) },
    { slug: "chattanooga", name: "Chattanooga", county: "Hamilton County", services: authoredRecords.slice(15, 20).map(page) },
    { slug: "clarksville", name: "Clarksville", county: "Montgomery County", services: authoredRecords.slice(20, 25).map(page) },
  ],
};
export { tennesseeBatch4 };
export default tennesseeBatch4;