import type { Batch2CoreServicePage, Batch2CoreServiceSlug, Batch2StateExpansion } from "./batch2-core-service-types";

type Copy = { label: string; description: string; lede: string; sections: [string, string][]; steps: string[]; faqs: [string, string][] };
type Metro = { slug: string; name: string; county: string; ahj: string; local: string; utility: string; sources: { label: string; url: string }[] };
const slugs: Batch2CoreServiceSlug[] = ["structural-engineering", "mep-engineering", "civil-engineering", "energy-compliance", "pe-stamped-drawings"];
const stateSources = [
  { label: "North Dakota State Building Code information", url: "https://www.nd.gov/labor/building-codes" },
  { label: "North Dakota Administrative Code, building code", url: "https://ndlegis.gov/information/acdata/html/24-01.html" },
  { label: "North Dakota PE and land surveyor board", url: "https://ndpelsboard.org/" },
  { label: "North Dakota PE board laws and rules", url: "https://ndpelsboard.org/laws-rules/" },
  { label: "U.S. DOE North Dakota energy code status", url: "https://www.energycodes.gov/status/states/north-dakota" },
  { label: "North Dakota State Fire Marshal", url: "https://www.nd.gov/agency/fire-marshal" },
  { label: "North Dakota DEQ stormwater", url: "https://deq.nd.gov/ndworks/stormwater" },
  { label: "North Dakota floodplain management", url: "https://www.swc.nd.gov/reg_approp/floodplain_management" },
  { label: "FEMA flood maps", url: "https://www.fema.gov/flood-maps" },
];
const m = (slug: string, name: string, county: string, ahj: string, local: string, utility: string, sources: { label: string; url: string }[]): Metro => ({ slug, name, county, ahj, local, utility, sources });
const metros: Metro[] = [
  m("fargo", "Fargo", "Cass County", "City of Fargo Inspections Department", "Fargo Land Development Code, floodplain screening, and local building inspections", "Fargo water and sewer and Public Works; electric and gas service territory must be confirmed for the address (Cass County Electric Cooperative or Xcel Energy may serve different locations)", [
    { label: "Fargo inspections and permits", url: "https://fargond.gov/city-government/departments/inspections" }, { label: "Fargo engineering", url: "https://fargond.gov/city-government/departments/engineering" }, { label: "Fargo Public Works", url: "https://fargond.gov/city-government/departments/public-works" }, { label: "Fargo floodplain information", url: "https://fargond.gov/city-government/departments/engineering/floodplain" },
    { label: "Fargo water utility", url: "https://fargond.gov/city-government/departments/public-works/water-utility" }, { label: "Cass County Electric Cooperative", url: "https://www.casscountyelectric.com/" }, { label: "Xcel Energy service", url: "https://my.xcelenergy.com/s/" },
  ]),
  m("bismarck", "Bismarck", "Burleigh County", "City of Bismarck Community Development Department", "Bismarck development review, grading, floodplain screening, and building permits", "Bismarck water and sewer and Public Works; Montana-Dakota Utilities or another address-serving provider must confirm gas and electric service, with Burleigh County roads reviewed separately", [
    { label: "Bismarck building permits", url: "https://www.bismarcknd.gov/191/Building-Permits" }, { label: "Bismarck engineering", url: "https://www.bismarcknd.gov/214/Engineering" }, { label: "Bismarck public works", url: "https://www.bismarcknd.gov/204/Public-Works" }, { label: "Bismarck floodplain information", url: "https://www.bismarcknd.gov/665/Floodplain-Management" },
    { label: "Bismarck water utility", url: "https://www.bismarcknd.gov/203/Water" }, { label: "Montana-Dakota Utilities", url: "https://www.montana-dakota.com/" },
  ]),
  m("grand-forks", "Grand Forks", "Grand Forks County", "City of Grand Forks Inspections Department", "Grand Forks zoning, post-flood development, stormwater, and local inspections", "Grand Forks Water and Light municipal water, wastewater, and electric service; city Public Works; address-specific gas and any supplemental electric service must be confirmed rather than assumed; Grand Forks County drainage", [
    { label: "Grand Forks inspections", url: "https://www.grandforksgov.com/government/city-departments/inspections" }, { label: "Grand Forks engineering", url: "https://www.grandforksgov.com/government/city-departments/engineering" }, { label: "Grand Forks Public Works", url: "https://www.grandforksgov.com/government/city-departments/public-works" }, { label: "Grand Forks floodplain", url: "https://www.grandforksgov.com/government/city-departments/engineering/floodplain" },
    { label: "Grand Forks Water and Light", url: "https://www.grandforksgov.com/government/city-departments/water-light" },
  ]),
  m("minot", "Minot", "Ward County", "City of Minot Building Division", "Minot building, zoning, Souris floodplain, grading, and public-works review", "Minot water and sewer and Public Works; Montana-Dakota Utilities or another address-serving provider must confirm gas and electric service, with Ward County roads reviewed separately", [
    { label: "Minot building division", url: "https://www.minotnd.gov/government/departments/building-division" }, { label: "Minot engineering", url: "https://www.minotnd.gov/government/departments/engineering" }, { label: "Minot Public Works", url: "https://www.minotnd.gov/government/departments/public-works" }, { label: "Minot floodplain information", url: "https://www.minotnd.gov/government/departments/engineering/floodplain" },
    { label: "Minot water and sewer utility", url: "https://www.minotnd.gov/government/departments/public-works/water-sewer" }, { label: "Montana-Dakota Utilities", url: "https://www.montana-dakota.com/" },
  ]),
  m("west-fargo", "West Fargo", "Cass County", "City of West Fargo Inspections Department", "West Fargo development standards, subdivision drainage, stormwater, and building inspections", "West Fargo water and sewer and Engineering; electric and gas territory must be confirmed for the address (Cass County Electric Cooperative or Xcel Energy may serve different locations)", [
    { label: "West Fargo inspections", url: "https://www.westfargond.gov/396/Building-Inspections" }, { label: "West Fargo engineering", url: "https://www.westfargond.gov/195/Engineering" }, { label: "West Fargo public works", url: "https://www.westfargond.gov/193/Public-Works" }, { label: "West Fargo floodplain information", url: "https://www.westfargond.gov/673/Floodplain-Information" },
    { label: "West Fargo utility services", url: "https://www.westfargond.gov/193/Public-Works" }, { label: "Cass County Electric Cooperative", url: "https://www.casscountyelectric.com/" }, { label: "Xcel Energy service", url: "https://my.xcelenergy.com/s/" },
  ]),
];

const p = (label: string, description: string, lede: string, sections: [string, string][], steps: string[], faqs: [string, string][]): Copy => ({ label, description, lede, sections, steps, faqs });
const copies: Record<string, Record<Batch2CoreServiceSlug, Copy>> = {
  fargo: {
    "structural-engineering": p("Structural Engineering", "Fargo structural design for Red River Valley additions, commercial alterations, and flood-aware permit work.", "Fargo structural investigations follow the Red River Valley's flat clay, shallow groundwater, snow drift, and older-frame conditions from observed framing through the proposed connection.", [["Red River Valley load paths", "Fargo additions near low terraces need verified joists, foundations, and settlement assumptions before a new opening or second story is detailed."], ["Snow, groundwater, and flood elevation", "Roof drift, frost, shallow groundwater, and the finished-floor elevation affect Fargo foundations and equipment supports; FEMA mapping is only one design input."], ["Fargo correction record", "For a Fargo reviewer comment, identify the changed detail, calculation, and inspection hold point; an ADU still requires load-path review where it touches the house or garage."]], ["Confirm Fargo occupancy, flood zone, snow and wind criteria, and existing framing with the Inspections Department.", "Tie survey, soil observations, frost protection, Red River elevation, and shoring assumptions to the structural sheets.", "Coordinate the addition, opening, rooftop unit, or ADU connection with Fargo Engineering and the architect.", "Return each correction with a dated response, clouded detail, revised calculation, and field-verification note."], [["When does a Fargo addition need investigation?", "A new opening, stacked addition, basement change, or ADU connection warrants measured framing and foundation information; the local reviewer decides the submittal scope."], ["How is Fargo flood risk used structurally?", "Use current FEMA and local elevation information with observed groundwater and foundation conditions; flood status does not replace engineering judgment."], ["What is a useful Fargo correction response?", "Quote the comment, identify the Fargo sheet or calculation changed, and list any inspection or survey dependency."]]),
    "mep-engineering": p("MEP Engineering", "Fargo MEP design for cold-weather buildings, utility capacity, ventilation, and local permit coordination.", "A Fargo MEP package must reconcile winter heating, Red River moisture, electrical service, and the actual water, sewer, gas, and electric connection before equipment is selected.", [["Fargo utility coordination", "Fargo Public Works and local utility records establish service points, available capacity, sewer elevations, and backflow or fire-service interfaces for the actual parcel."], ["Cold-weather operation", "Extreme cold, snow at outdoor equipment, spring moisture, and dry indoor air affect freeze protection, ventilation, controls, and maintenance access in Fargo."], ["Fargo plan-check trail", "Keep building, fire, utility, and energy comments together; an ADU or addition can change panel capacity, heat-pump sizing, domestic water, and sanitary loading."]], ["Verify Fargo occupancy, service size, gas availability, water pressure, sewer point, fire thresholds, and current code checklist.", "Document equipment clearances, combustion or heat-pump details, ventilation, controls, fixture demand, and freeze protection.", "Reconcile utility replies and fire comments with risers, panel schedules, equipment schedules, and energy documents.", "Answer each Fargo comment by sheet and calculation, preserving substitutions, testing assumptions, and closeout records."], [["Which utilities matter to Fargo MEP work?", "Fargo Public Works, water and sewer records, Cass County Electric or Xcel service, and the project-specific provider determine connection assumptions."], ["What does Fargo winter change?", "Low temperatures and snow require freeze protection, resilient controls, accessible equipment, and ventilation that matches the actual occupancy."], ["How should Fargo MEP comments be returned?", "Use one dated matrix linking each comment to revised risers, schedules, loads, controls, and any utility response."]]),
    "civil-engineering": p("Civil Engineering", "Fargo civil engineering for flat-site drainage, utilities, floodplain screening, access, and stormwater review.", "Fargo civil design is driven by Red River Valley grades, clay soils, spring runoff, shallow groundwater, and the separation between building, stormwater, right-of-way, and utility approvals.", [["Fargo grading and drainage", "Small changes in a flat Fargo lot can redirect runoff; survey-based contours, finished floors, overland routes, and downstream outfalls must agree."], ["Flood and stormwater agencies", "Review FEMA mapping with Fargo Engineering and North Dakota DEQ stormwater requirements; Cass County drainage responsibilities can remain separate from a city permit."], ["Residential additions and ADUs", "An ADU or addition can add roof runoff, sewer demand, impervious area, and access constraints even without a subdivision, so show those changes on the civil record."]], ["Confirm Fargo jurisdiction, disturbance, flood status, frontage, utility points, soil conditions, and stormwater route.", "Prepare survey-based grading, utility profiles, fire access, finished floors, erosion notes, and maintenance responsibilities.", "Coordinate Fargo Engineering, Public Works, DEQ coverage, fire access, and utility responses before submission.", "Log each correction against revised contours, profiles, calculations, elevations, and accepted agency conditions."], [["Why can a Fargo infill lot need drainage analysis?", "Flat grades and spring snowmelt leave little tolerance for changed runoff; the site must show a safe route and compatible outfall."], ["Who may review Fargo civil work?", "The city, North Dakota DEQ, Cass County or drainage authorities, fire officials, and utilities may each review a different element."], ["How is an Fargo ADU handled?", "Check added impervious area, sewer and water demand, fire access, grading, and flood status rather than assuming the small footprint is exempt."]]),
    "energy-compliance": p("Energy Compliance", "Fargo energy compliance for cold-climate envelopes, HVAC, lighting, and permit documentation.", "Fargo energy documentation should match the adopted code path and the real envelope, windows, heating equipment, ventilation, lighting, and service-water design.", [["Fargo envelope decisions", "Wind, long heating seasons, snow, and spring moisture make air sealing, thermal bridges, roof continuity, and moisture-safe assemblies central to Fargo review."], ["Model-to-drawing consistency", "The report must agree with Fargo architectural details and MEP schedules; a changed window, heat pump, or lighting control is a model change too."], ["Additions and correction responses", "Screen an ADU or residential addition for alteration triggers and connected HVAC or service effects, then answer Fargo comments by input and sheet."]], ["Identify Fargo occupancy, alteration category, current energy edition, climate inputs, and prescriptive or performance route.", "Collect verified assemblies, fenestration, HVAC, ventilation, lighting, controls, and service-water values from the design team.", "Submit coordinated forms or analysis through the local review path and reconcile comments with architectural and MEP changes.", "Issue a dated Fargo response that names changed inputs, sheets, calculations, controls, and closeout assumptions."], [["Which energy path applies in Fargo?", "The AHJ and current North Dakota adoption determine whether the project uses the applicable prescriptive or performance documentation."], ["What climate factors matter?", "Long heating seasons, wind, snow, moisture, and freeze risk affect envelope continuity and HVAC inputs; use project evidence."], ["Does a Fargo addition avoid energy review?", "Not automatically. Alteration scope, connected systems, occupancy, and the adopted code determine required documentation."]]),
    "pe-stamped-drawings": p("PE-Stamped Drawings", "Fargo PE-stamped drawing coordination for defined engineering scope, calculations, and local corrections.", "A Fargo seal package should identify the parcel, observed Red River Valley conditions, design criteria, discipline boundary, and calculations that the responsible professional actually reviewed.", [["Fargo scope boundary", "A PE document does not replace survey, geotechnical, architecture, utility, or fire information; it states which Fargo engineering decisions are within the reviewed scope."], ["Conditions before sealing", "Snow drift, frost, clay, groundwater, flood elevation, and older construction may require field or specialty information before a responsible Fargo PE can complete review."], ["Fargo revision control", "Track every reviewer comment, substitution, RFI, and field change; an ADU or addition remains within the same responsibility record when it changes loads or services."]], ["Map the Fargo parcel, AHJ, code edition, flood check, investigations, utility letters, and discipline boundaries.", "Assemble verified existing conditions, design criteria, calculations, drawings, exclusions, and inspection assumptions for independent review.", "Submit signed and sealed documents through the named Fargo channel; coordinate fire, civil, architectural, and utility packages.", "Issue each correction or field change as a dated reviewed revision, never as an unreviewed contractor substitution."], [["What does a Fargo PE review?", "The PE reviews the defined discipline, evidence, criteria, calculations, and documents within responsible professional judgment."], ["Does a Fargo seal ensure approval?", "No. The AHJ controls acceptance, and a seal does not promise permit approval or conceal unknown field conditions."], ["How should a Fargo revision be issued?", "Reference the comment, cloud the changed sheet, update the calculation index, and preserve the responsible PE's review record."]]),
  },
  bismarck: {
    "structural-engineering": p("Structural Engineering", "Bismarck structural design for Missouri River terraces, hillside grades, snow, wind, and additions.", "Bismarck structural work must account for Missouri River terraces, variable clay or shale, prairie wind, snow, and the way a new opening or hillside addition meets an existing structure.", [["Terrace and hillside load paths", "Bismarck sites can move from river terrace to rolling grade quickly; verify footings, retaining interfaces, and existing framing before sizing a connection."], ["Wind, frost, and snow", "Prairie uplift, drifted snow, frost movement, and freeze-thaw affect Bismarck roof, anchorage, foundation, and construction sequencing decisions."], ["Bismarck review corrections", "Name the Community Development comment and show its effect on the detail or calculation; a residential addition still needs existing-foundation and egress coordination."]], ["Confirm Bismarck occupancy, site grade, soil information, wind and snow criteria, flood status, and existing construction.", "Coordinate retaining, frost, drainage, foundations, roof drift, lateral lines, and temporary shoring with the civil team.", "Submit a connected structural set through Bismarck Building Permits and reconcile Engineering conditions.", "Return each correction in a numbered matrix with clouded sheets, revised calculations, and inspection notes."], [["When should a Bismarck addition be investigated?", "Whenever the addition changes foundations, roof loads, lateral walls, openings, or egress; the actual building and AHJ checklist control."], ["How does Bismarck terrain matter?", "Terrace, clay, shale, grade, frost, snow, and wind alter foundation and retaining assumptions; verify them rather than importing a Fargo detail."], ["What makes a correction useful?", "Tie the reviewer issue to a Bismarck sheet, calculation, field observation, and inspection hold point."]]),
    "mep-engineering": p("MEP Engineering", "Bismarck MEP design for cold weather, river-terrace utilities, public works, and permit review.", "Bismarck MEP documents should start with actual service capacity and winter operation, then coordinate water, sewer, gas, electric, fire, and energy interfaces on the permit set.", [["Bismarck service information", "Water and sewer points, Montana-Dakota Utilities service, electrical demand, and Public Works requirements should be confirmed before equipment schedules are fixed."], ["Cold and elevated sites", "Cold starts, snow, dry indoor air, river humidity, and sloped access affect equipment placement, freeze protection, ventilation, and maintenance in Bismarck."], ["Bismarck additions", "A house addition or ADU may exceed panel, heating, domestic-water, or sanitary capacity; show the existing service and proposed load together."]], ["Confirm Bismarck occupancy, provider, service capacity, water pressure, sewer elevation, fire review, and energy route.", "Prepare coordinated risers, load calculations, equipment clearances, ventilation, controls, and freeze-protection details.", "Resolve Public Works, utility, fire, and building comments before issuing the Bismarck permit package.", "Answer comments by affected sheet and calculation, preserving utility approvals, substitutions, testing, and closeout assumptions."], [["What must Bismarck MEP verify?", "Confirm the address-specific water, sewer, electric, gas, fire, and equipment constraints with the responsible providers and AHJ."], ["What does a Bismarck winter require?", "Freeze protection, reliable controls, snow-aware equipment access, and ventilation suited to the actual occupancy and envelope."], ["How are comments tracked?", "One dated matrix should connect Bismarck comments to risers, load sheets, schedules, controls, and provider responses."]]),
    "civil-engineering": p("Civil Engineering", "Bismarck civil engineering for river terraces, grades, drainage, access, and utility coordination.", "Bismarck civil plans need survey-controlled grades, Missouri River flood screening, hillside drainage, utility profiles, accessible routes, and a clear distinction between city and county review.", [["Bismarck grade transitions", "River terraces, rolling streets, clay or shale, and driveway grades can control finished floors, retaining, accessible routes, and overland drainage."], ["Public works and flood", "Coordinate Bismarck Engineering and Public Works with FEMA and state flood information; a city building permit is not a stormwater or right-of-way approval."], ["Small residential site changes", "An ADU, garage, or addition can alter roof runoff, sewer demand, snow storage, and fire access even when no lot line changes." ]], ["Identify Bismarck frontage, flood status, disturbance, soil and groundwater, utilities, access grades, and downstream route.", "Draft survey-based grading, profiles, drainage, fire access, finished-floor, erosion, and maintenance information.", "Route the set through Bismarck Engineering, Public Works, fire, flood, and utility reviews as applicable.", "Respond with revised contours, profiles, calculations, elevations, and a dated agency comment log."], [["Why check drainage on a Bismarck lot?", "Grade changes and intense rain can send runoff toward a neighboring terrace or public street; the accepted route must be shown."], ["Which Bismarck reviews may be separate?", "Engineering, Public Works, fire, floodplain, utility, and county authorities can control different civil elements."], ["What changes with an ADU?", "Check access, impervious area, sewer and water, drainage, snow storage, and fire separation rather than relying on footprint alone."]]),
    "energy-compliance": p("Energy Compliance", "Bismarck energy compliance for cold, windy envelopes, efficient systems, and local permit documentation.", "The Bismarck energy record should reconcile current code adoption with the high heating load, wind exposure, snow, and moisture details shown on architectural and MEP sheets.", [["Bismarck envelope", "Wind-driven snow, cold, freeze-thaw, and dry winters make continuous air control, thermal bridges, roof edges, and moisture-safe details important."], ["Equipment and model", "Bismarck heating schedules, ventilation, windows, lighting controls, and service water must match the compliance inputs instead of generic climate assumptions."], ["Correction and addition scope", "An addition or ADU can connect to existing heating or electrical service and trigger documentation; answer comments against the changed input and sheet."]], ["Confirm Bismarck AHJ, occupancy, alteration category, current energy edition, climate data, and selected compliance route.", "Collect actual assemblies, windows, HVAC, ventilation, lighting, controls, and service-water specifications.", "Submit the coordinated Bismarck report or forms and synchronize every reviewer change with drawings and schedules.", "Document the dated correction response, final inputs, changed sheets, controls, and field-testing assumptions."], [["Which route applies in Bismarck?", "The AHJ and current adopted North Dakota energy provisions determine the required route and forms."], ["What should the model reflect?", "Bismarck heating, wind, snow, moisture, assemblies, equipment, controls, and actual occupancy—not a copied city profile."], ["Are additions exempt?", "No automatic exemption exists; alteration scope and connected systems determine the documentation."]]),
    "pe-stamped-drawings": p("PE-Stamped Drawings", "Bismarck PE-stamped drawing coordination for defined scope, conditions, calculations, and review corrections.", "A Bismarck PE record should establish what was observed at the river terrace or hillside parcel, what criteria were used, and which sealed engineering documents are within responsible charge.", [["Bismarck professional scope", "The seal covers a defined engineering discipline; survey, geotechnical, architecture, utility, and fire information retain their own roles in the permit record."], ["Evidence before sealing", "Frost, snow, wind, clay or shale, grade, groundwater, and existing construction may require investigation before sealing Bismarck work."], ["Bismarck correction control", "The responsible PE should review each comment and RFI, including an addition or ADU that changes loads, service, drainage, or foundations."]], ["List Bismarck AHJ, code edition, parcel conditions, investigations, utilities, flood check, and discipline boundaries.", "Prepare calculations, design criteria, drawings, notes, exclusions, and verified observations for independent professional review.", "Submit the signed and sealed Bismarck package through the stated channel and coordinate related disciplines.", "Issue a dated, clouded, reviewed revision for each correction, substitution, RFI, or field condition."], [["What is in a Bismarck PE review?", "Defined scope, verified evidence, design criteria, calculations, code basis, and the documents within the PE's professional judgment."], ["Does sealing promise a Bismarck permit?", "No. The city or county AHJ decides acceptance; sealing is not a guarantee or substitute for missing information."], ["How are revisions controlled?", "Reference the comment, cloud the sheet, revise the calculation index, and retain the PE's documented review."]]),
  },
  "grand-forks": {
    "structural-engineering": p("Structural Engineering", "Grand Forks structural design for Red River flood recovery, cold-weather foundations, and additions.", "Grand Forks structural decisions separate river-bottom flood exposure from upland conditions while addressing snow, groundwater, frost, and post-flood construction.", [["Flood-repair load paths", "Measure repaired framing, masonry, foundations, and concealed openings before connecting an addition."], ["River and winter criteria", "Red and Red Lake elevations, shallow groundwater, frost, and snow affect foundations and lateral bracing."], ["Correction record", "A Grand Forks ADU or addition should show load, egress, and fire-separation effects in each response."]], ["Confirm Grand Forks flood status, occupancy, snow and wind criteria, repairs, and inspection route.", "Document framing, foundations, frost, flood elevation, shoring, and concealed-condition uncertainty.", "Coordinate Grand Forks Engineering, architecture, fire, and civil drainage information.", "Return each comment with a dated matrix, calculation, clouded detail, and inspection point."], [["When investigate?", "Post-flood repairs, new openings, foundations, and ADUs can expose unknown load paths."], ["How use flood data?", "Combine current FEMA and local elevations with observed foundations and groundwater."], ["What is a useful response?", "Tie the comment to a Grand Forks sheet, calculation, observation, and inspection."]]),
     "mep-engineering": p("MEP Engineering", "Grand Forks MEP design for flood-aware equipment, severe cold, and utility coordination.", "Grand Forks MEP plans connect cold-weather reliability with flood elevation, recovery-era utility conditions, and actual Water and Light services.", [["Provider record", "Water and Light and Public Works establish connection elevations, capacity, backflow, and equipment constraints."], ["Cold and flood", "Extreme cold, spring breakup, humidity, and flood exposure affect controls, ventilation, freeze protection, and placement."], ["Residential scope", "An addition or ADU can require panel, heat, water, sanitary, and ventilation review."]], ["Confirm Grand Forks occupancy, providers, flood elevation, water pressure, sewer, fire, and energy path.", "Develop risers, loads, ventilation, controls, freeze protection, and elevated-equipment details.", "Reconcile Water and Light, Public Works, fire, and building comments.", "Return each correction by sheet and calculation, retaining provider and testing records."], [["Which providers matter?", "Grand Forks Water and Light is the municipal water, wastewater, and electric contact; Public Works and the address-specific gas or supplemental electric provider must be confirmed separately."], ["How do flood and cold interact?", "Protect services from freezing and elevate flood-sensitive equipment using current site information."], ["What is a good log?", "Link each issue to a revised riser, schedule, load, and utility response."]]),
    "civil-engineering": p("Civil Engineering", "Grand Forks civil engineering for river floodplain, flat drainage, utilities, and recovery work.", "Flat grades, Red River drainage, shallow groundwater, spring snowmelt, and post-flood infrastructure make the Grand Forks civil record site-specific.", [["Flat-site grading", "Show finished floors, overland routes, accessible approaches, and drainage because small grade changes move water."], ["Agency handoffs", "Coordinate FEMA, Grand Forks Engineering, North Dakota DEQ, and county drainage responsibilities separately."], ["Rebuilding and ADUs", "An ADU or repaired addition can change impervious area, sewer loading, access, and flood documentation."]], ["Identify Grand Forks flood zone, disturbance, frontage, survey, soils, utilities, and downstream route.", "Prepare grading, utility, drainage, fire-access, erosion, flood, and maintenance sheets.", "Route applicable work through Engineering, Public Works, fire, DEQ, floodplain, and providers.", "Return numbered corrections with revised contours, profiles, calculations, and elevations."], [["Why drainage analysis?", "Flat river grades, spring runoff, and groundwater leave little tolerance for an unshown path."], ["Who reviews?", "City, state stormwater, county drainage, floodplain, fire, and utilities may differ."], ["What changes with an ADU?", "Check runoff, sewer, water, access, impervious area, and flood records."]]),
    "energy-compliance": p("Energy Compliance", "Grand Forks energy compliance for extreme cold, flood-aware equipment, and coordinated forms.", "Grand Forks energy documents must reflect long heating, wind, snow, moisture, and any equipment-elevation decision.", [["Envelope evidence", "Cold, wind, snow, and spring moisture make air control, thermal bridges, roof edges, and durable assemblies material."], ["Flood-sensitive systems", "Elevated equipment requires schedules, controls, ventilation, and service-water assumptions that still match the drawings."], ["Addition review", "Treat an ADU or addition as an alteration question and update forms when connected systems change."]], ["Confirm Grand Forks occupancy, alteration, code edition, climate data, and compliance route.", "Gather envelope, windows, heating, ventilation, lighting, controls, and service-water inputs.", "Submit coordinated documentation and reconcile Inspections and utility comments.", "Log every change by input, sheet, calculation, control, and field assumption."], [["Which route applies?", "The AHJ and adopted North Dakota energy requirements determine the route."], ["What inputs matter?", "Cold, wind, snow, moisture, assemblies, and actual equipment loads."], ["Is an addition exempt?", "No; alteration scope and connected systems determine documentation."]]),
    "pe-stamped-drawings": p("PE-Stamped Drawings", "Grand Forks PE-stamped coordination for flood recovery, cold evidence, and corrections.", "A Grand Forks PE record identifies flood and existing-building evidence, criteria, calculations, discipline, and responsibility limits.", [["Professional scope", "A seal does not replace flood survey, geotechnical work, architecture, utilities, or fire review."], ["Evidence before sealing", "Repairs, groundwater, frost, snow, and concealed conditions may require investigation."], ["Revision accountability", "Review every comment, RFI, substitution, addition, or ADU service change."]], ["List Grand Forks parcel, AHJ, code, flood check, investigations, utilities, and boundaries.", "Assemble verified conditions, criteria, calculations, drawings, exclusions, and inspection assumptions.", "Submit signed documents through the local channel and coordinate building and civil work.", "Issue reviewed, dated, clouded revisions for each comment or field change."], [["What is reviewed?", "Defined scope, evidence, criteria, calculations, and documents within professional judgment."], ["Does sealing guarantee approval?", "No; the AHJ decides acceptance and concealed conditions remain factual risks."], ["How control revisions?", "Reference the comment, cloud the sheet, update calculations, and retain review."]]),
  },
  minot: {
    "structural-engineering": p("Structural Engineering", "Minot structural design for Souris River flood work, rolling grades, wind, and snow.", "Minot structural work follows Souris flood exposure, rolling terrain, clay or shale, prairie wind, frost, and additions to repaired buildings.", [["Foundation transitions", "River alluvium, sloped ground, and shale can change footing and retaining assumptions across one parcel."], ["Wind, snow, and flood", "Roof drift, uplift, frost, and flood elevation affect lateral connections and equipment supports."], ["Local corrections", "Tie Building Division comments to calculations; ADUs still need foundation, egress, and separation review."]], ["Confirm Minot occupancy, flood status, grade, soil, wind, snow, and existing construction.", "Coordinate foundations, retaining, frost, drainage, lateral lines, roof drift, and temporary conditions.", "Reconcile Engineering, fire, flood, and civil inputs before submission.", "Return dated responses with clouded drawings, calculations, and inspection points."], [["What triggers investigation?", "Openings, additions, retaining, flood repairs, and ADU connections can change the structure."], ["How does Souris matter?", "Flood elevation and groundwater inform foundations while grades affect retaining and drainage."], ["What should a correction show?", "The cited Minot issue, revised sheet, calculation, field basis, and inspection dependency."]]),
    "mep-engineering": p("MEP Engineering", "Minot MEP design for Souris resilience, extreme cold, and utility capacity.", "Minot MEP coordination joins freeze protection and snow operation with flood-sensitive equipment and actual water, sewer, electric, and MDU service.", [["Utility interfaces", "Public Works and provider records establish capacity, connection elevations, backflow, and right-of-way conditions."], ["Souris winter operation", "Flood, cold, wind, and dry air affect equipment, controls, ventilation, freeze protection, and access."], ["Home additions", "Show how an addition changes panel, heating, domestic-water, sanitary, and ventilation demand."]], ["Confirm Minot occupancy, providers, service, water pressure, sewer, flood elevation, fire, and energy.", "Prepare loads, risers, equipment schedules, ventilation, controls, and flood or freeze details.", "Coordinate Public Works, Engineering, fire, utility, and building comments.", "Answer comments by sheet and calculation; retain provider, testing, and substitution records."], [["What utility data is needed?", "Address-specific water, sewer, electric, gas, flood, and fire information."], ["What does winter require?", "Freeze protection, maintainable access, and controls matched to operation."], ["How answer comments?", "Link each issue to changed risers, loads, schedules, controls, and utility evidence."]]),
    "civil-engineering": p("Civil Engineering", "Minot civil engineering for Souris floodplain, rolling grades, drainage, and public works.", "Minot civil plans reconcile Souris flood status with rolling grades, variable soils, utility profiles, access, and downstream drainage.", [["Grade and access", "Slopes, shale or clay, retaining, routes, and driveway transitions need current survey data."], ["Flood handoffs", "Coordinate City Engineering, Public Works, FEMA, state stormwater, and Ward County authorities."], ["Residential sites", "An ADU or garage changes runoff, impervious area, sewer loading, fire access, and finished-floor records."]], ["Identify Minot jurisdiction, flood status, disturbance, frontage, soils, utilities, grades, and receiving route.", "Prepare grading, profiles, drainage, flood elevations, access, erosion, and maintenance plans.", "Route Engineering, Public Works, fire, flood, stormwater, and utilities.", "Respond with revised contours, profiles, calculations, elevations, and accepted conditions."], [["Why analyze a Minot lot?", "Souris flooding and uneven grades make drainage, access, and finished floor interdependent."], ["Who may review?", "Engineering, Public Works, floodplain, state stormwater, county, fire, and providers."], ["What does an ADU add?", "Review impervious area, access, utilities, drainage, snow, and flood status."]]),
    "energy-compliance": p("Energy Compliance", "Minot energy compliance for cold, windy envelopes, flood-aware equipment, and permit review.", "Minot energy documents reflect long heating, wind, snow, freeze, and flood-related equipment decisions shown on the drawings.", [["Minot envelope", "Cold, wind, roof snow, frost, and moisture affect air sealing, thermal bridges, roof edges, and controls."], ["Actual systems", "Heating, ventilation, windows, lighting, and service-water inputs must match Minot schedules."], ["Addition corrections", "An ADU or addition connected to existing systems requires an alteration and correction review."]], ["Confirm Minot occupancy, alteration, code, climate, and energy route.", "Collect assemblies, windows, equipment, ventilation, lighting, controls, and water inputs.", "Submit coordinated forms and reconcile Building Division comments.", "Document each correction, input, sheet, calculation, control, and testing assumption."], [["Which route applies?", "Minot's AHJ and adopted North Dakota provisions establish energy documentation."], ["What does climate change?", "Cold, wind, snow, and moisture affect envelope and equipment assumptions."], ["Can an addition skip review?", "No; connected systems and alteration scope determine documentation."]]),
    "pe-stamped-drawings": p("PE-Stamped Drawings", "Minot PE-stamped coordination for flood, frost, wind, and defined professional scope.", "A Minot PE package documents Souris conditions, evidence, criteria, calculations, discipline limits, and reviewed revisions.", [["Scope", "The seal defines engineering responsibility and does not replace survey, geotechnical, flood, architecture, utility, or fire work."], ["Evidence", "Flood, groundwater, frost, snow, wind, soil, and older construction may require investigation."], ["Corrections", "Review every comment, substitution, and RFI, including additions that change foundations, service, or drainage."]], ["Map Minot parcel, AHJ, code, flood check, investigations, utilities, and discipline.", "Assemble observations, criteria, calculations, drawings, notes, exclusions, and inspection assumptions.", "Submit signed documents through Minot and coordinate related disciplines.", "Issue dated clouded revisions only after PE review of each change."], [["What is reviewed?", "The defined Minot scope, evidence, criteria, calculations, and documents."], ["Is approval guaranteed?", "No; Minot's AHJ decides acceptance and the seal does not promise outcomes."], ["How issue changes?", "Reference the comment, cloud the sheet, update calculations, and retain review."]]),
  },
  "west-fargo": {
    "structural-engineering": p("Structural Engineering", "West Fargo structural design for growth, flat clay sites, snow, wind, and additions.", "West Fargo structural work addresses rapid development, flat clay, groundwater, spring drainage, snow drift, and new connections to existing buildings.", [["Growth-site evidence", "Infill, multifamily, and warehouse work should verify bearing, settlement, diaphragms, openings, and sequence."], ["Snow and flat terrain", "Snow drift, prairie wind, frost, and groundwater affect roofs, anchors, and slabs."], ["Residential review", "A West Fargo ADU or addition should show load transfer and egress effects in each response."]], ["Confirm West Fargo occupancy, soil, groundwater, snow, wind, flood screen, and existing construction.", "Coordinate foundations, framing, lateral, frost, drainage, roof drift, and temporary conditions.", "Reconcile Engineering, fire, civil, and utility interfaces.", "Return each correction with response, clouded detail, calculation, and inspection note."], [["When investigate?", "Openings, second floors, additions, and ADU connections can change the load path."], ["What affects foundations?", "Clay, groundwater, frost, runoff, snow, and construction sequence require parcel evidence."], ["How answer review?", "Name the West Fargo comment, changed sheet, calculation, and field verification."]]),
    "mep-engineering": p("MEP Engineering", "West Fargo MEP design for residential growth, cold operation, and utility coordination.", "West Fargo MEP planning reconciles growth-area water and sewer, electric and gas service, winter operation, ventilation, and occupancy.", [["Utility facts", "Engineering and Public Works plus Cass County Electric or Xcel establish connection and load assumptions."], ["Cold operation", "Extreme cold, snow, spring moisture, and dry air affect equipment, freeze protection, controls, and filtration."], ["ADU service", "An ADU may require panel, heating, water, sewer, ventilation, and service review on the existing lot."]], ["Confirm West Fargo occupancy, territory, service, water, sewer, fire, and energy requirements.", "Coordinate risers, loads, equipment, ventilation, controls, freeze protection, and maintenance.", "Resolve Engineering, Public Works, fire, utility, and building comments.", "Return a dated matrix tied to schedules, risers, calculations, provider responses, and testing."], [["Which providers matter?", "West Fargo Engineering, Public Works, electric, gas, water, and sewer providers."], ["What does winter require?", "Freeze protection, snow-aware access, controls, and occupancy-specific ventilation."], ["How manage corrections?", "Link issues to changed sheet, load, schedule, control, and utility record."]]),
    "civil-engineering": p("Civil Engineering", "West Fargo civil engineering for flat growth sites, drainage, utilities, access, and stormwater.", "West Fargo growth makes flat-site drainage, clay, groundwater, subdivision infrastructure, fire access, and utility phasing central to civil design.", [["Grading", "Current contours, finished floors, overland routes, and downstream assumptions protect neighboring lots."], ["Agency review", "Engineering, Public Works, Cass County drainage, North Dakota DEQ, and flood officials may separate approvals."], ["Infill changes", "An ADU or detached building can add runoff, sewer demand, impervious area, access, and snow storage."]], ["Confirm West Fargo development route, disturbance, flood screen, frontage, soils, utilities, and drainage.", "Prepare grading, drainage, profiles, fire access, finished floors, erosion, snow, and maintenance sheets.", "Coordinate Engineering, Public Works, stormwater, fire, county, DEQ, and utilities.", "Answer corrections with contours, profiles, calculations, elevations, notes, and accepted conditions."], [["Why check flat sites?", "Clay, groundwater, spring runoff, and small grade changes affect drainage."], ["Who reviews?", "City, county drainage, DEQ, floodplain, fire, and utilities may differ."], ["What changes for an ADU?", "Screen runoff, impervious area, sewer, water, access, and snow storage."]]),
    "energy-compliance": p("Energy Compliance", "West Fargo energy compliance for cold growth, envelopes, HVAC, and local forms.", "West Fargo energy documents match current code and the actual assemblies, windows, heating, ventilation, lighting, and controls.", [["Envelope", "Cold, wind, snow, and moisture make air sealing, thermal bridges, roof transitions, and durable details important."], ["Model coordination", "Standard plans must not hide changes in windows, heat pumps, lighting, ventilation, or service water."], ["Small projects", "An ADU or addition needs alteration and connected-service screening before West Fargo submission."]], ["Confirm West Fargo AHJ, occupancy, code, alteration, climate, and route.", "Collect project-specific assemblies, fenestration, HVAC, ventilation, lighting, controls, and water.", "Submit coordinated forms and synchronize Building, Engineering, and MEP revisions.", "Return comments by changed input, sheet, calculation, control, and inspection assumption."], [["Which route applies?", "West Fargo's AHJ and adopted North Dakota requirements determine route and forms."], ["What inputs matter?", "Cold, wind, snow, moisture, assemblies, equipment, controls, and occupancy."], ["Is an ADU exempt?", "No automatic exemption; alteration and connected systems control."]]),
    "pe-stamped-drawings": p("PE-Stamped Drawings", "West Fargo PE-stamped coordination for growth sites, defined scope, and corrections.", "A West Fargo PE record identifies the developing parcel, criteria, conditions, calculations, professional scope, and documents actually reviewed.", [["Responsibility", "A seal covers defined engineering and does not replace survey, geotechnical, architecture, utility, fire, or subdivision information."], ["Site evidence", "Clay, groundwater, frost, snow, wind, rapid site changes, and existing improvements require verification."], ["Corrections", "Review every West Fargo comment, substitution, RFI, addition, and ADU service change."]], ["List West Fargo AHJ, code, parcel, flood screen, investigations, utilities, and boundaries.", "Assemble observations, criteria, calculations, drawings, exclusions, and inspection assumptions.", "Submit sealed documents and coordinate civil, fire, architecture, and utilities.", "Issue dated clouded revisions after review of each comment or field condition."], [["What does the PE review?", "Defined West Fargo discipline, evidence, criteria, calculations, and documents."], ["Does the seal guarantee approval?", "No; the AHJ decides acceptance and the seal does not promise site outcomes."], ["How issue a revision?", "Reference comment, cloud sheet, update calculations, and preserve review."]]),
  },
};

type AuthoredBody = { permitAuthority: string; codeContext: string; localConditions: string; projectTypes: string };
const authoredBodies: Record<string, Record<Batch2CoreServiceSlug, AuthoredBody>> = {
  fargo: {
    "structural-engineering": {
      permitAuthority: "Fargo Inspections Department is the building-review contact for this structural scope; Fargo Engineering, fire officials, and Cass County authorities can impose separate site or access conditions. Confirm the parcel's reviewing authority before sealing.",
      codeContext: "Use the North Dakota State Building Code and its Administrative Code adoption as the starting code basis, then record Fargo's currently accepted edition, amendments, snow and wind criteria, and structural checklist with Inspections.",
      localConditions: "Red River Valley flat grades, compressible or variable clay, shallow groundwater, frost, snow drift, and older framing are Fargo-specific investigation questions; do not carry a Bismarck or West Fargo foundation assumption into the parcel.",
      projectTypes: "Fargo structural work ranges from a measured porch or ADU connection to a warehouse opening, rooftop unit support, flood-repair framing, and a second-story addition; each scope needs its own existing-condition evidence and load path.",
    },
    "mep-engineering": {
      permitAuthority: "Fargo Inspections coordinates the building permit, while Fargo Public Works, fire review, and the address-serving electric or gas company may control distinct utility interfaces. Obtain written service information for the actual address.",
      codeContext: "Anchor the MEP design to North Dakota's adopted building and energy provisions, the current Fargo checklist, and the applicable fire and mechanical requirements; document which edition and transition rule the reviewer accepts.",
      localConditions: "Fargo's long heating season, Red River moisture, spring freeze-thaw, snow around outdoor equipment, and flat-site sewer grades affect capacity, freeze protection, ventilation, and maintenance access.",
      projectTypes: "Fargo MEP assignments include tenant finish, restaurant exhaust, multifamily service upgrades, cold-climate additions, and ADUs that may change panel load, heat, domestic water, sanitary flow, or ventilation.",
    },
    "civil-engineering": {
      permitAuthority: "Fargo Engineering and Public Works review grading, frontage, utilities, and right-of-way matters in addition to the building permit; North Dakota DEQ and Cass County drainage authorities may have independent review.",
      codeContext: "Pair the North Dakota DEQ stormwater program, State Water Commission floodplain information, and the adopted building framework with Fargo's land-development, drainage, erosion, and access requirements for the specific review path.",
      localConditions: "Fargo's very low Red River Valley relief, clay, shallow groundwater, spring snowmelt, and limited outfall fall mean that a few inches of finished-floor or driveway change can redirect runoff.",
      projectTypes: "Fargo civil work covers infill lots, subdivisions, commercial parking, utility extensions, fire lanes, and residential additions or ADUs; the impervious-area, sewer, access, and snow-storage effects must be shown.",
    },
    "energy-compliance": {
      permitAuthority: "Fargo Inspections receives the building energy documentation, but the responsible design team must coordinate architectural, mechanical, and lighting information and answer any separate fire or utility comment.",
      codeContext: "Identify the North Dakota adopted energy-code edition and Fargo's accepted compliance forms before modeling; cite the applicable prescriptive or performance path and preserve any alteration exception determination.",
      localConditions: "Fargo wind, long winter heating, snow, spring moisture, and dry indoor air make continuous air control, thermal-bridge treatment, equipment sizing, ventilation, and service-water inputs consequential.",
      projectTypes: "Fargo energy work includes a new shell, tenant improvement, multifamily renovation, heat-pump conversion, garage-to-living-space change, and addition or ADU tied to an existing HVAC or electrical system.",
    },
    "pe-stamped-drawings": {
      permitAuthority: "The Fargo AHJ decides permit acceptance; a North Dakota-registered PE controls the professional seal within the stated discipline, while survey, geotechnical, fire, utility, and Public Works approvals remain separate.",
      codeContext: "The PE record should name the North Dakota code adoption, Fargo review edition, design criteria, and any amendment or transition decision, consistent with the North Dakota PE board's laws and rules.",
      localConditions: "Before sealing, verify Fargo's parcel survey, clay and groundwater observations, frost depth, Red River flood screening, snow drift, existing framing, and utility correspondence rather than relying on regional boilerplate.",
      projectTypes: "A Fargo sealed package may support a commercial alteration, warehouse equipment frame, flood-sensitive repair, residential opening, ADU connection, or addition, but the PE must define the reviewed evidence and exclusions for that job.",
    },
  },
  bismarck: {
    "structural-engineering": {
      permitAuthority: "Bismarck Community Development handles the building application; Bismarck Engineering, Public Works, fire officials, and Burleigh County can review access, drainage, flood, or road matters outside the structural permit.",
      codeContext: "Record the North Dakota State Building Code adoption, Bismarck's current permit edition and amendments, and the project wind, snow, frost, and seismic criteria before selecting a structural load path.",
      localConditions: "Missouri River terraces, rolling grades, variable clay or shale, prairie wind, frost movement, and freeze-thaw make Bismarck foundations and retaining interfaces different from flat Fargo sites.",
      projectTypes: "Bismarck structural services include hillside retaining, river-terrace foundations, commercial roof alterations, equipment supports, residential additions, and ADUs where existing footing and lateral information must be verified.",
    },
    "mep-engineering": {
      permitAuthority: "Bismarck Community Development reviews the building package; Public Works, fire officials, and Montana-Dakota Utilities separately determine service, fire, right-of-way, and utility conditions for the address.",
      codeContext: "Use North Dakota's adopted building and energy framework with the Bismarck checklist and accepted edition; keep mechanical, electrical, plumbing, fire, and energy assumptions traceable to the reviewed code path.",
      localConditions: "Bismarck cold starts, wind, snow, dry winter air, river-terrace grades, and variable service elevations affect equipment placement, freeze protection, ventilation, controls, and maintenance routes.",
      projectTypes: "Bismarck MEP scopes include civic or tenant renovations, restaurant and commercial equipment, multifamily service changes, hillside additions, and ADUs that may consume existing electric, gas, water, or sewer capacity.",
    },
    "civil-engineering": {
      permitAuthority: "Bismarck Engineering and Public Works can set grading, access, utility, and right-of-way conditions separate from Community Development's building review; Burleigh County or flood authorities may control adjacent parcels.",
      codeContext: "Base the civil record on North Dakota floodplain and DEQ stormwater resources plus Bismarck's engineering, drainage, access, and erosion requirements; identify the road owner and permit separately.",
      localConditions: "Missouri River terrace breaks, rolling streets, clay or shale, intense rainfall, frost, and snow storage affect Bismarck finished floors, retaining, accessible routes, drainage, and utility profiles.",
      projectTypes: "Bismarck civil assignments span hillside lots, river-terrace commercial sites, subdivisions, parking and fire access, utility extensions, and ADUs or garages that add runoff and service demand.",
    },
    "energy-compliance": {
      permitAuthority: "Bismarck Community Development receives energy compliance information with the building application; the engineer must reconcile any mechanical, fire, utility, or architectural comments before issuing a final record.",
      codeContext: "Confirm the North Dakota energy-code adoption and Bismarck's currently accepted edition, forms, and alteration treatment; a model or prescriptive worksheet is valid only for the documented project scope.",
      localConditions: "Bismarck's exposed prairie wind, cold, snow, dry winter, and freeze-thaw conditions make air leakage, roof-edge continuity, thermal bridges, equipment capacity, and ventilation inputs material.",
      projectTypes: "Bismarck energy assignments include new commercial envelopes, tenant alterations, heating replacements, multifamily work, and additions or ADUs that connect to existing heating, lighting, or service-water systems.",
    },
    "pe-stamped-drawings": {
      permitAuthority: "Bismarck's AHJ accepts or rejects the permit, while a North Dakota-registered PE is responsible only for the defined sealed discipline; county roads, utilities, fire, and survey work retain separate authorities.",
      codeContext: "List the adopted North Dakota code edition, Bismarck amendments and checklist, design criteria, and PE responsibility boundary, using the North Dakota registration board rules for sealing and revisions.",
      localConditions: "A Bismarck seal may depend on field evidence of terrace or hillside grade, clay or shale, frost, snow, wind, groundwater, existing construction, and the flood screening at the actual address.",
      projectTypes: "Bismarck sealed drawings may address a retaining interface, roof or equipment alteration, commercial addition, residential opening, ADU, or public-facing improvement when calculations and exclusions match the observed scope.",
    },
  },
  "grand-forks": {
    "structural-engineering": {
      permitAuthority: "Grand Forks Inspections is the building-review contact; Grand Forks Engineering, Public Works, floodplain staff, fire officials, and county drainage authorities may impose separate conditions after flood or repair work.",
      codeContext: "State the North Dakota adopted building code and the Grand Forks review edition, then document flood-related provisions, snow and wind criteria, existing-building triggers, and any locally required inspection sequence.",
      localConditions: "The Red River and Red Lake basin, post-1997 flood recovery work, shallow groundwater, frost, snow, and repaired or concealed framing make a Grand Forks load path an address-specific investigation.",
      projectTypes: "Grand Forks structural work includes flood-repair verification, commercial openings, elevated equipment supports, older-home additions, garages, and ADUs where repaired foundations or framing cannot be assumed sound.",
    },
    "mep-engineering": {
      permitAuthority: "Grand Forks Inspections handles the building review; Grand Forks Water and Light controls its municipal water, wastewater, and electric interfaces, while Public Works, fire officials, and any address-serving gas provider may review separately.",
      codeContext: "Use North Dakota's adopted building and energy requirements with the Grand Forks checklist and accepted edition; retain a written record of flood-elevation, fire, mechanical, plumbing, and electrical decisions.",
      localConditions: "Grand Forks winter cold, Red River spring breakup, flood-sensitive equipment locations, moisture, and older utility infrastructure affect freeze protection, controls, ventilation, service elevations, and access.",
      projectTypes: "Grand Forks MEP scopes include recovery work, municipal or commercial tenant fit-outs, multifamily renovations, service replacements, and additions or ADUs that alter Water and Light, heating, sanitary, or ventilation demand.",
    },
    "civil-engineering": {
      permitAuthority: "Grand Forks Engineering and Public Works review grading, floodplain, drainage, utilities, and right-of-way separately from Inspections; North Dakota DEQ, FEMA information, and county drainage responsibilities must be tracked independently.",
      codeContext: "Use State Water Commission floodplain resources, FEMA mapping, North Dakota DEQ stormwater requirements, and the adopted building framework alongside the Grand Forks drainage, access, and floodplain checklist.",
      localConditions: "Very flat Red River Valley grades, shallow groundwater, spring snowmelt, flood-control infrastructure, and recovery-era utility work make finished-floor, overland-flow, outfall, and access assumptions especially site-specific.",
      projectTypes: "Grand Forks civil work covers flood-recovery rebuilding, infill, commercial parking, utility profiles, fire access, subdivision changes, and ADUs that affect impervious area, sewer loading, drainage, or flood documentation.",
    },
    "energy-compliance": {
      permitAuthority: "Grand Forks Inspections receives the energy package, but flood-sensitive mechanical placement and electrical or utility changes require coordination with Water and Light, Public Works, fire review, and the responsible design disciplines.",
      codeContext: "Identify the North Dakota energy adoption and Grand Forks accepted edition before selecting a compliance path; record alteration treatment and make flood-elevation decisions visible in the coordinated set.",
      localConditions: "Grand Forks long heating seasons, wind, snow, spring moisture, and flood recovery conditions affect air barriers, thermal bridges, durable assemblies, equipment elevation, ventilation, and service-water modeling.",
      projectTypes: "Grand Forks energy work includes flood-repair rehabilitation, cold-climate tenant improvements, multifamily upgrades, envelope replacement, and additions or ADUs connected to existing heat, lighting, and service systems.",
    },
    "pe-stamped-drawings": {
      permitAuthority: "Grand Forks decides permit acceptance, while a North Dakota-registered PE seals only the defined discipline; floodplain, survey, geotechnical, utility, Public Works, and fire approvals are not replaced by that seal.",
      codeContext: "Name the adopted North Dakota code, Grand Forks review edition, flood-related criteria, and professional boundary, and follow the North Dakota PE board's rules for responsible charge and revisions.",
      localConditions: "Before sealing Grand Forks work, verify flood-repair evidence, foundation elevation, groundwater, frost, snow, existing framing, utility records, and concealed-condition limits at the parcel.",
      projectTypes: "Grand Forks sealed packages may cover a flood-recovery repair, commercial alteration, elevated equipment support, residence addition, or ADU, provided the PE identifies investigations, calculations, inspection assumptions, and exclusions.",
    },
  },
  minot: {
    "structural-engineering": {
      permitAuthority: "Minot Building Division administers the building review; Minot Engineering, Public Works, fire officials, Ward County, and floodplain authorities may control separate site, access, or recovery conditions.",
      codeContext: "Record North Dakota's adopted building-code edition and Minot's current checklist, then apply Souris flood criteria, snow, wind, frost, and existing-building provisions appropriate to the structural alteration.",
      localConditions: "Souris River flood exposure, rolling ground, clay or shale, prairie wind, frost, and repaired or older construction can change Minot foundation, retaining, lateral, and equipment-support assumptions within a short distance.",
      projectTypes: "Minot structural services include flood-repair assessment, sloped-site retaining, commercial roof changes, equipment supports, house additions, garages, and ADUs that open or load an existing structure.",
    },
    "mep-engineering": {
      permitAuthority: "Minot Building Division reviews the building package; Minot Public Works, Engineering, fire officials, Montana-Dakota Utilities, and the address-specific electric provider may each control a different service or safety interface.",
      codeContext: "Anchor the Minot MEP record to North Dakota's adopted building and energy provisions and the current local checklist, with explicit fire, flood, plumbing, mechanical, and electrical coordination.",
      localConditions: "Minot cold, wind, Souris flood exposure, rolling utility grades, snow, and dry indoor air affect equipment elevation, freeze protection, controls, ventilation, and maintainable access.",
      projectTypes: "Minot MEP scopes include commercial tenant work, public facilities, service replacements, flood-resilient equipment, multifamily renovations, and additions or ADUs that change water, sewer, electric, gas, heat, or ventilation demand.",
    },
    "civil-engineering": {
      permitAuthority: "Minot Engineering and Public Works may require separate grading, floodplain, drainage, access, utility, or right-of-way approval from the Building Division; Ward County and state stormwater roles must be checked by parcel.",
      codeContext: "Combine Minot's engineering and floodplain requirements with North Dakota DEQ stormwater, State Water Commission, FEMA, and adopted building-code resources; identify the receiving authority for each outfall.",
      localConditions: "Souris flood levels, rolling grades, clay or shale, frost, snowmelt, and variable groundwater make Minot finished floors, retaining, driveway grades, overland routes, and profiles interdependent.",
      projectTypes: "Minot civil work includes flood-recovery sites, sloped commercial lots, residential additions, ADUs, parking, fire access, utility extensions, and drainage corrections where impervious area or sewer demand changes.",
    },
    "energy-compliance": {
      permitAuthority: "Minot Building Division reviews energy compliance with the permit; mechanical, electrical, fire, flood, and utility comments must be reconciled rather than treated as approval of a separate model.",
      codeContext: "Confirm the North Dakota energy-code adoption, Minot's accepted edition and forms, and whether the alteration follows a prescriptive or performance path before collecting inputs.",
      localConditions: "Minot's severe cold, prairie wind, snow, freeze-thaw, Souris flood exposure, and dry winter air affect envelope continuity, equipment elevation, heating capacity, ventilation, and controls.",
      projectTypes: "Minot energy assignments range from new shells and tenant interiors to flood-repair rehabilitation, heating replacement, multifamily work, and additions or ADUs tied to existing systems.",
    },
    "pe-stamped-drawings": {
      permitAuthority: "The Minot AHJ decides acceptance; a North Dakota-registered PE seals the identified engineering discipline only, leaving floodplain, survey, geotechnical, utility, fire, and road approvals with their own authorities.",
      codeContext: "List North Dakota's adopted code, Minot's review edition, Souris flood and design criteria, and the PE's responsibility boundary in accordance with North Dakota registration-board laws and rules.",
      localConditions: "Minot sealing decisions may depend on surveyed grade, flood elevation, groundwater, frost, wind, snow, clay or shale, existing repairs, and utility correspondence that must be verified at the address.",
      projectTypes: "Minot sealed work may support a flood repair, retaining or foundation design, commercial alteration, equipment frame, home addition, or ADU, with calculations and field-review limits stated plainly.",
    },
  },
  "west-fargo": {
    "structural-engineering": {
      permitAuthority: "West Fargo Inspections administers the building review; West Fargo Engineering, Public Works, fire officials, Cass County, and subdivision authorities may set separate conditions for a rapidly developing parcel.",
      codeContext: "Use the North Dakota State Building Code adoption and West Fargo's current structural checklist, recording the accepted edition, amendments, snow and wind criteria, and any subdivision or existing-building trigger.",
      localConditions: "West Fargo's flat growth corridors, clay, groundwater, spring runoff, frost, snow drift, and new-to-existing construction interfaces require parcel evidence rather than a generic Fargo detail.",
      projectTypes: "West Fargo structural assignments include warehouse and retail build-outs, multifamily framing, infill openings, detached garages, additions, and ADUs where new loads meet existing foundations or diaphragms.",
    },
    "mep-engineering": {
      permitAuthority: "West Fargo Inspections reviews the building permit; Engineering, Public Works, fire officials, and the address-serving electric and gas utilities may impose distinct capacity, connection, and right-of-way conditions.",
      codeContext: "Document the North Dakota adopted building and energy editions, West Fargo's checklist, and the mechanical, electrical, plumbing, fire, and utility assumptions accepted for the specific occupancy.",
      localConditions: "West Fargo growth-area utility phasing, flat grades, cold winters, snow, spring moisture, and dry indoor air influence service capacity, sewer elevations, freeze protection, equipment access, and ventilation.",
      projectTypes: "West Fargo MEP work includes new retail or multifamily service, tenant improvements, warehouse systems, residential additions, and ADUs that may exceed existing panel, heat, water, sewer, or ventilation capacity.",
    },
    "civil-engineering": {
      permitAuthority: "West Fargo Engineering and Public Works can separately review subdivision drainage, grading, frontage, utilities, and right-of-way while Inspections handles the building permit; Cass County and DEQ roles depend on the site.",
      codeContext: "Base the civil package on West Fargo standards plus North Dakota DEQ stormwater, State Water Commission floodplain information, FEMA mapping, and the applicable adopted building and access requirements.",
      localConditions: "West Fargo's flat clay sites, high groundwater, rapid subdivision phasing, spring runoff, snow storage, and limited relief make lot-to-lot drainage and construction sequencing critical.",
      projectTypes: "West Fargo civil scopes include subdivisions, infill, commercial parking, fire lanes, utility extensions, detached buildings, additions, and ADUs that alter runoff, impervious area, access, or sewer demand.",
    },
    "energy-compliance": {
      permitAuthority: "West Fargo Inspections receives the energy record with the building application; Engineering, fire, utility, and MEP coordination still govern changes to the systems represented in the compliance documentation.",
      codeContext: "Confirm North Dakota's current energy adoption and West Fargo's accepted edition, forms, and alteration provisions; reconcile the chosen path with the actual architectural and equipment schedules.",
      localConditions: "West Fargo's cold, wind, snow, flat roof drainage, spring moisture, and growth-era envelope interfaces make air sealing, thermal bridges, roof transitions, controls, and heating loads project-specific.",
      projectTypes: "West Fargo energy work covers new development, retail and office tenant improvements, multifamily renovations, heat-pump conversions, and additions or ADUs connected to existing envelope and service systems.",
    },
    "pe-stamped-drawings": {
      permitAuthority: "West Fargo determines permit acceptance, while a North Dakota-registered PE is responsible for the specifically sealed discipline; subdivision, fire, utility, survey, geotechnical, and Public Works approvals remain distinct.",
      codeContext: "Identify the North Dakota code adoption, West Fargo review edition and amendments, design criteria, and PE responsibility boundary, following the North Dakota board's laws and rules for sealing.",
      localConditions: "A West Fargo PE should verify rapid-site-change conditions, clay, groundwater, frost, snow, wind, finished-grade coordination, existing improvements, and utility information before sealing.",
      projectTypes: "West Fargo sealed drawings may address a growth-site structure, warehouse alteration, multifamily addition, equipment support, residential opening, detached garage, or ADU within a documented professional scope.",
    },
  },
};

function formatService(local: Metro, copy: Copy, slug: Batch2CoreServiceSlug): Batch2CoreServicePage {
  const body = authoredBodies[local.slug][slug];
  return {
    serviceSlug: slug,
    title: `${local.name}, North Dakota ${copy.label}`,
    description: copy.description,
    h1: `${copy.label} for ${local.name}, North Dakota Projects`,
    kicker: `${local.name}, North Dakota permit coordination`,
    lede: copy.lede,
    permitAuthority: body.permitAuthority,
    codeContext: body.codeContext,
    localConditions: body.localConditions,
    projectTypes: body.projectTypes,
    sections: copy.sections.map(([heading, body]) => ({ heading, body })),
    permitSteps: copy.steps,
    faqs: copy.faqs.map(([question, answer]) => ({ question, answer })),
    sources: [...local.sources, ...stateSources],
  };
}
const northDakotaBatch4: Batch2StateExpansion = {
  stateSlug: "north-dakota", stateName: "North Dakota", stateAbbrev: "ND",
  hub: {
    title: "North Dakota Engineering Services for Local Permit Review",
    description: "North Dakota structural, MEP, civil, energy, and PE-stamped drawing coordination for river, prairie, residential, and commercial projects.",
    h1: "Engineering for North Dakota River and Prairie Communities",
    kicker: "North Dakota permit coordination",
    lede: "North Dakota projects combine state code resources with city or county building, floodplain, stormwater, fire, utility, and public-works review. The address and observed conditions determine a correction-ready engineering record.",
    sections: [
      { heading: "Local AHJs administer different paths", body: "Fargo, Bismarck, Grand Forks, Minot, and West Fargo apply their own checklists alongside North Dakota code resources. A county parcel may use another authority." },
      { heading: "River and prairie conditions are not interchangeable", body: "Red, Missouri, Souris, and Red Lake flood exposure differs from upland clay, shale, groundwater, frost, snow, wind, and spring breakup." },
      { heading: "Additions and ADUs remain coordinated scopes", body: "Small residential work can change load paths, egress, service, drainage, access, sewer, water, and energy documentation." },
      { heading: "State and local environmental handoffs", body: "North Dakota DEQ stormwater, State Water Commission flood information, FEMA mapping, city engineering, utilities, and county drainage authorities may each control a separate approval." },
      { heading: "Transportation and right-of-way coordination", body: "A North Dakota project that changes a driveway, sidewalk, alley, curb, or utility crossing may need a separate city or county right-of-way review in addition to the building application. Fargo, Bismarck, Grand Forks, Minot, and West Fargo public-works departments can set frontage, sight-distance, access, pavement-restoration, snow-storage, or construction-staging conditions for their facilities. State highway work may involve the North Dakota Department of Transportation rather than the local building office. Confirm the road owner, access permit, utility crossing, and traffic-control requirements before fixing grading or fire access; a building permit does not authorize work in public right-of-way." },
    ],
    faqs: [
      { question: "Does North Dakota have one permit office?", answer: "No. The local city or county AHJ administers building and development review; fire, flood, stormwater, utilities, and public works may be separate." },
      { question: "What should be checked first?", answer: "Confirm jurisdiction, code edition, survey, soils, frost, snow, wind, flood, drainage, utility capacity, occupancy, and alteration scope." },
      { question: "How are corrections returned?", answer: "Use a dated matrix naming the comment, response, revised document, and unresolved field or agency dependency. Approval is not guaranteed." },
    ],
    sources: stateSources,
  },
  metros: metros.map((local) => ({
    slug: local.slug, name: local.name, county: local.county,
    services: slugs.map((slug) => formatService(local, copies[local.slug][slug], slug)),
  })),
};
export { northDakotaBatch4 };
export default northDakotaBatch4;