/** Deep discipline pages — content-rich, top-level service pages
 * (/structural-engineering/, /mep-engineering/, etc.) that establish topical
 * authority for each engineering discipline. Generated by generate.ts.
 */

import { LICENSING_COVERAGE_STATEMENT, PROJECT_JURISDICTION_NOTE } from "../src/lib/licensing";

export interface DisciplineDef {
  slug: string;
  name: string;
  shortName: string;
  h1: string;
  metaTitle: string;
  metaDescription: string;
  kicker: string;
  lede: string;
  sections: { heading: string; paragraphs: string[] }[];
  deliverables: { title: string; desc: string }[];
  useCases: string[];
  faqs: { q: string; a: string }[];
}

export const DISCIPLINES: DisciplineDef[] = [
  {
    slug: "structural-engineering",
    name: "Structural Engineering",
    shortName: "Structural",
    h1: "Structural Engineering Services",
    metaTitle: "Structural Engineering Services | Licensed PE Structural Design | Apex Grid",
    metaDescription:
      "Licensed structural engineering for commercial, residential, and industrial projects: gravity and lateral design, foundations, seismic retrofits, and PE-stamped calculation packages built to pass plan check.",
    kicker: "Licensed Professional Engineering",
    lede:
      "Gravity, lateral, foundation, and retrofit design for steel, concrete, masonry, and timber structures — delivered as PE-stamped drawings and complete calculation packages that municipal reviewers approve the first time.",
    sections: [
      {
        heading: "What Our Structural Engineers Actually Do",
        paragraphs: [
          "Every structure we design starts with a load path. Our engineers trace every pound of dead load, live load, snow, wind, and seismic demand from the roof deck down through beams, columns, shear walls, and footings into the soil — and we document that path in a calculation package a plan reviewer can follow line by line. Gravity design covers member sizing for steel wide-flange framing, glulam and dimensional lumber, reinforced concrete, and load-bearing masonry, checked against ASCE 7 load combinations and the material standards (AISC 360, ACI 318, TMS 402, NDS) referenced by the adopted building code.",
          "Lateral design is where most projects live or die in plan check. We model wind pressures per ASCE 7 directional and envelope procedures and seismic demands using the equivalent lateral force procedure or, where irregularity demands it, modal response spectrum analysis. Diaphragm design, collector and chord forces, shear wall hold-downs, moment frame drift checks, and foundation overturning are all resolved in the calculation set — not left for the contractor to discover in the field.",
          "Foundations are engineered to the project geotechnical report: shallow spread and continuous footings, mat foundations, drilled piers, helical piles, and grade beams, with bearing, settlement, and sliding checks documented. Where no soils report exists, we design to code-presumptive values and say so explicitly, so the jurisdiction knows exactly what basis of design it is approving.",
        ],
      },
      {
        heading: "Retrofits, Assessments, and Existing Buildings",
        paragraphs: [
          "A large share of our structural work is existing buildings: seismic retrofits of unreinforced masonry and soft-story buildings under ASCE 41, tenant-improvement openings cut into bearing walls, mezzanines added inside warehouse shells, and rooftop equipment loads on structures that never anticipated them. We perform ASCE 41 Tier 1 screenings and Tier 2 evaluations, produce retrofit drawings that preserve as much of the existing structure as the numbers allow, and coordinate directly with the jurisdiction on alternative-compliance paths when the letter of the current code cannot practically be met.",
          "Equipment anchorage is its own specialty: seismic anchorage calculations for HVAC units, generators, tanks, and racking per ASCE 7 Chapter 13, with anchor design per ACI 318 Chapter 17. If your mechanical submittal was rejected for missing anchorage calcs, this is the fastest structural scope we turn around.",
        ],
      },
      {
        heading: "How a Structural Project Runs at Apex Grid",
        paragraphs: [
          "Every engagement begins with a scoping call and a fixed-fee proposal that names the deliverables, the code editions we will design to, and the delivery date. Before the first member is sized, we confirm the adopted building code and local amendments with the permitting jurisdiction — the difference between the 2021 and 2018 IBC, or a county wind-speed amendment, can change member sizes, connection details, and even the viability of a framing scheme. Getting that answer in writing on day one is cheaper than discovering it in a correction letter on day ninety.",
          "Design then proceeds in coordination passes, not in isolation. Framing plans are checked against the architectural reflected ceiling plans for depth conflicts, against mechanical routing for duct penetrations through beams and shear walls, and against civil grading for top-of-footing elevations. Penetrations that must happen get engineered — reinforced openings, headers, and transfer details drawn at scale — rather than left as field problems. Because our MEP and civil engineers sit inside the same firm, these checks happen continuously instead of at a single late-stage clash review.",
          "The submittal package itself is engineered for the reviewer: a table of contents in the calculations, load paths presented in the order a checker follows them, design criteria summarized on the general notes sheet, and special inspection requirements itemized so the jurisdiction can issue the permit without a back-and-forth about Chapter 17 inspections. After permit, we stay on the project — reviewing steel and truss shop drawings, answering contractor RFIs with sketches rather than prose, evaluating field deviations against the original calculations, and issuing the structural observation letters many jurisdictions require before final inspection. A stamped drawing set is the start of our responsibility, not the end of it.",
          "Material selection is treated as an economic decision, not a default. On a typical low-rise commercial building we will compare a steel moment frame against braced frames and masonry shear walls, pricing the tradeoffs in tonnage, foundation demand, and erection speed before the architect commits to a floor plan that locks one system in. Timber projects get the same scrutiny: dimensional lumber versus engineered products, prefabricated trusses versus stick framing, and where mass timber genuinely pencils versus where it is fashion. Because the cost of a structural system is set by the earliest decisions, we push this analysis to the front of the schedule — a week of comparison at schematic design routinely saves five or six figures in steel and concrete at bid time.",
        ],
      },
    ],
    deliverables: [
      { title: "PE-Stamped Drawings", desc: "Complete structural sheet sets — foundation plans, framing plans, sections, details, and general notes — coordinated with architectural and MEP documents." },
      { title: "Calculation Package", desc: "A clean, indexed calculation set covering gravity, lateral, foundation, and connection design, formatted for municipal peer review." },
      { title: "Retrofit & Evaluation Reports", desc: "ASCE 41 screenings, feasibility studies, and retrofit construction documents for existing and historic structures." },
      { title: "Construction Support", desc: "RFI responses, shop drawing review, deferred submittal review, and structural observation letters through closeout." },
    ],
    useCases: [
      "Ground-up commercial and mixed-use buildings",
      "ADUs, custom homes, and multifamily",
      "Seismic retrofits (URM, soft-story, tilt-up)",
      "Tenant improvements and wall openings",
      "Mezzanines, canopies, and equipment platforms",
      "Rooftop unit and solar structural reviews",
    ],
    faqs: [
      { q: "Do you stamp drawings in my state?", a: `${LICENSING_COVERAGE_STATEMENT} ${PROJECT_JURISDICTION_NOTE} Tell us where the project is and we confirm the governing code edition in the same call.` },
      { q: "What codes do you design to?", a: "The building code your jurisdiction has adopted — typically an edition of the IBC or IRC with state amendments — with loads per ASCE 7 and material design per AISC 360, ACI 318, TMS 402, and the NDS. We confirm the exact adopted editions with the permit office before design starts." },
      { q: "Do I need a geotechnical report?", a: "For most commercial foundations, yes — and it usually pays for itself in reduced footing sizes. For light residential work, many jurisdictions accept code-presumptive soil values, and we will design to those when appropriate and state the basis of design on the drawings." },
      { q: "Can you fix a plan-check rejection from another engineer?", a: "Frequently. We review the correction letter, the drawings, and the calculations, then either supplement the existing package or re-engineer the deficient scope. Rejections for missing lateral calcs or anchorage design are the most common and fastest to resolve." },
      { q: "How fast can you turn around a structural calculation package?", a: "Simple scopes — beam sizing, equipment anchorage, single wall openings — often ship in days. Full building packages depend on size and coordination, and every proposal we send states the delivery date before you commit." },
    ],
  },
  {
    slug: "mep-engineering",
    name: "MEP Engineering",
    shortName: "MEP",
    h1: "MEP Engineering Services",
    metaTitle: "MEP Engineering Services | Mechanical, Electrical & Plumbing Design | Apex Grid",
    metaDescription:
      `Integrated MEP engineering: HVAC load calculations, electrical distribution, plumbing design, and energy code compliance — coordinated as one system with PE-stamped permit packages. ${LICENSING_COVERAGE_STATEMENT} ${PROJECT_JURISDICTION_NOTE}`,
    kicker: "Integrated Building Systems",
    lede:
      "Mechanical, electrical, and plumbing systems engineered together — clash-checked against the structure, documented for permit, and sized from real load calculations rather than rules of thumb.",
    sections: [
      {
        heading: "One Coordinated Model, Three Disciplines",
        paragraphs: [
          "Uncoordinated MEP drawings are the single largest source of construction RFIs and change orders. A duct that collides with a steel beam, a panel with no working clearance, a sanitary line with nowhere to slope — each one costs days in the field. Because our mechanical, electrical, and plumbing engineers work in the same model alongside our structural team, those collisions are resolved on screen, before the drawings ever reach a bidder.",
          "Mechanical design begins with ACCA Manual J / ASHRAE-based heating and cooling load calculations — room by room, with actual envelope constructions, orientation, and internal gains, never a square-footage rule of thumb. From the loads we select equipment with local climate derating, route duct and refrigerant piping, design ventilation to ASHRAE 62.1 outdoor-air rates, and document economizer, exhaust, and control requirements the energy code imposes.",
          "Electrical design covers service entrance sizing, one-line diagrams, panel schedules with NEC Article 220 load calculations, feeder and branch circuit design, voltage-drop checks, short-circuit and coordination considerations, lighting layouts with fixture schedules and controls narratives, and emergency/egress power where occupancy requires it. Plumbing design covers domestic water sizing by fixture-unit method, water heater and recirculation design, sanitary waste and vent sizing, storm drainage, gas piping with pressure-drop calculations, and backflow prevention coordination with the water purveyor.",
        ],
      },
      {
        heading: "Energy Code Is Engineered In, Not Bolted On",
        paragraphs: [
          "Every MEP package we deliver includes the energy compliance documentation the jurisdiction requires — COMcheck or state-specific forms in most of the country, and full Title 24 Part 6 documentation for California projects, produced in-house. Because compliance is modeled during design rather than after it, we never have to strip efficiency features out of a bid set or re-engineer a system that failed the compliance run at the end.",
          "The same integration pays off in plan check: mechanical, electrical, plumbing, and energy comments arrive at one firm, get resolved against one coordinated model, and go back to the reviewer in one response cycle instead of ricocheting between separate consultants.",
        ],
      },
      {
        heading: "What an MEP Engagement Looks Like",
        paragraphs: [
          "You send architectural backgrounds — CAD or even a clean PDF — plus the project address and a description of the use. We confirm the governing mechanical, electrical, plumbing, and energy codes with the permitting jurisdiction, then return a fixed-fee proposal that itemizes the sheets, calculations, and compliance documents you will receive and the date you will receive them. No hourly meters, no scope ambiguity: if the jurisdiction later adds a requirement we did not anticipate, that conversation happens openly rather than through an invoice.",
          "During design, the three trades are developed against each other in structured coordination passes. Ductwork is routed around structure with real depths, not single-line diagrams; electrical rooms are sized with NEC working clearances drawn to scale; plumbing mains are sloped from the fixture farthest from the point of connection back to it, so the invert elevations actually work. Where the building is existing, we start from a field walk or photo survey of installed conditions, because designing to record drawings that no longer match reality is how change orders are born.",
          "The permit package ships with everything the reviewer needs to say yes: load calculations bound into the set, equipment schedules with model numbers and capacities matching the calcs, energy compliance forms signed and matched to the specified equipment, and a code summary on the cover sheet keyed to the editions the jurisdiction enforces. After permit, we review contractor submittals against the design intent — a substituted RTU with a different electrical load touches three trades, and we check all three — respond to RFIs, and support inspections through closeout. For multi-site operators rolling out the same concept across states, we maintain a prototype set and adapt it jurisdiction by jurisdiction, which is dramatically cheaper than re-engineering each location from scratch.",
          "Special-use projects get discipline-specific attention rather than a generic template. Restaurants carry kitchen hood exhaust, makeup air, grease waste, and heavy gas loads that interact with each other; medical and dental suites add vacuum, compressed air, and equipment-specific electrical circuits with isolated grounding; industrial tenants bring process loads, ventilation for heat and contaminants, and utility services far beyond a standard shell allowance. In every case the question we answer first is whether the base building can support the use — service capacity, gas availability, structural support for rooftop additions — because discovering a $150,000 utility upgrade after the lease is signed is the failure mode we exist to prevent. A one-week due-diligence review of the base building's mechanical, electrical, and plumbing capacity — panel schedules, gas meter sizing, RTU condition, sewer capacity — is the cheapest insurance a tenant or buyer can purchase, and we offer it as a standalone scope for exactly that reason.",
        ],
      },
    ],
    deliverables: [
      { title: "Permit-Ready MEP Sheets", desc: "Mechanical, electrical, and plumbing plans, schedules, details, and specifications — coordinated sheet-by-sheet and stamped by licensed PEs." },
      { title: "Load Calculations", desc: "HVAC heating/cooling loads, NEC electrical load calcs, and plumbing fixture-unit sizing included in the submittal package." },
      { title: "Energy Compliance", desc: "COMcheck, state energy forms, or Title 24 Part 6 documentation matched to the exact code edition your jurisdiction enforces." },
      { title: "Construction Support", desc: "Submittal review, RFI responses, and record-drawing coordination through project closeout." },
    ],
    useCases: [
      "Commercial tenant improvements and restaurants",
      "Ground-up retail, office, and industrial shells",
      "Multifamily and mixed-use buildings",
      "Medical and dental suites",
      "Equipment replacements and system upgrades",
      "Change-of-use and adaptive reuse conversions",
    ],
    faqs: [
      { q: "Can you take on just one trade, or is it all three?", a: "Either. Many clients bring us all three trades to capture the coordination benefit, but we regularly deliver mechanical-only, electrical-only, or plumbing-only scopes — for example, a panel upgrade or an RTU replacement package." },
      { q: "Do you do Title 24 / energy compliance?", a: "Yes, in-house. California Title 24 Part 6 documentation, COMcheck for IECC states, and state-specific compliance forms elsewhere. Energy compliance is included in our MEP proposals by default." },
      { q: "What do you need from me to start?", a: "Architectural backgrounds (CAD or PDF), the project address, and a description of the use. From that we confirm the governing codes with the jurisdiction and return a fixed-fee proposal, typically within 12–24 hours." },
      { q: "Do you size equipment with real load calculations?", a: "Always. Rule-of-thumb tonnage is how buildings end up with oversized, short-cycling systems and failed energy compliance. Every system we specify traces back to a documented load calculation in the permit set." },
      { q: "Can you respond to plan-check corrections on drawings you didn't produce?", a: "Yes. We review the correction list and the existing drawings, then quote either a targeted response or a re-engineered package — whichever is genuinely cheaper for you." },
    ],
  },
  {
    slug: "civil-engineering",
    name: "Civil Engineering",
    shortName: "Civil",
    h1: "Civil Engineering Services",
    metaTitle: "Civil Engineering Services | Site Design, Grading & Stormwater | Apex Grid",
    metaDescription:
      "Civil and site engineering: grading and drainage design, stormwater management, utility plans, erosion control, and ADA site compliance — engineered to your jurisdiction's published standards.",
    kicker: "Site & Land Development",
    lede:
      "Grading, drainage, stormwater, and utility design that bridges raw land and vertical construction — engineered to each jurisdiction's published standards so site plans clear review without redesign cycles.",
    sections: [
      {
        heading: "From Feasibility to Approved Site Plans",
        paragraphs: [
          "The economics of a development are usually decided before the foundation is poured. Our civil work starts at feasibility: conceptual grading studies that expose cut/fill imbalances, utility availability checks with the serving districts, and preliminary stormwater sizing that reveals how much of the parcel a detention requirement will consume. Finding those constraints during due diligence costs a few thousand dollars; finding them after acquisition can cost the project.",
          "Grading and drainage design balances earthwork, sets finished floor elevations above design storm elevations, establishes positive drainage away from structures, and maintains accessible routes at ADA-compliant slopes — running slope, cross slope, and landing requirements verified across every path of travel, not just the striped parking stalls. Drainage design is computed, not sketched: time-of-concentration, rational-method or hydrograph-based peak flows, inlet spacing, and pipe sizing all appear in a drainage report the reviewer can check.",
          "Stormwater management is where local variation is fiercest, and where our multi-state code research pays off. We design retention basins where jurisdictions require full on-site retention, detention with controlled release where downstream capacity governs, and water-quality treatment — bioretention, permeable pavement, proprietary units — where MS4 permits demand it, each sized to the locally mandated storm events and documented in the format the reviewing agency publishes.",
        ],
      },
      {
        heading: "Utilities, Erosion Control, and Agency Coordination",
        paragraphs: [
          "Wet utility design covers domestic water and fire service sizing, sanitary sewer design with slope and manhole spacing per the district's standards, and points of connection negotiated with the serving utility. We prepare SWPPP documentation and erosion-control plans for construction-phase compliance, and we support entitlement packages with the exhibits — preliminary grading, utility, and drainage plans — that planning commissions ask for.",
          "Most importantly, we do the unglamorous work of reading each agency's design manual before we draw. A site plan engineered to the reviewing agency's own published standards, with its own checklist answered in order, is the difference between one review cycle and four.",
        ],
      },
      {
        heading: "How Civil Design Coordinates with the Building",
        paragraphs: [
          "Civil engineering fails quietly when it is designed in a vacuum. A finished floor elevation set without checking the sewer invert forces a grinder pump that nobody budgeted. A transformer pad located for the utility's convenience lands in the fire lane. A beautifully balanced grading plan puts the accessible route at 5.2 percent and fails inspection by two-tenths of a degree. Because our civil engineers work alongside the structural, mechanical, electrical, and plumbing teams on the same projects, these cross-discipline collisions are caught in design — the building and the site are engineered as one system.",
          "The workflow starts with survey and geotechnical data: we review the topographic survey for completeness before design begins, flag missing utility inverts or boundary ambiguities early, and reconcile the soils report's infiltration rates and pavement sections with what the stormwater and paving designs actually assume. Then design proceeds in the order approvals require — conceptual grading for entitlement exhibits, preliminary engineering for agency pre-application meetings, and final construction documents once the path to approval is confirmed. Sequencing it this way means you never pay for final engineering on a layout the planning commission is about to change.",
          "Deliverables are packaged for the specific reviewing agencies involved, which on one project can include the city's engineering department, the regional flood control district, the water and sewer purveyors, the fire marshal, and the state environmental agency for construction stormwater permits. Each gets its submittal in its own required format, and we track each review cycle to closure. During construction we review contractor submittals for pipe and pavement materials, respond to field conflicts — the unmarked utility that every site eventually finds — and prepare the record drawings and engineer's certifications most jurisdictions require before they release occupancy or bonds.",
          "Earthwork economics deserve their own mention, because dirt is often the largest hidden line item on a site budget. A grading design that exports ten thousand yards of soil in a market where haul-off runs twenty dollars a yard has quietly spent two hundred thousand dollars that a balanced design would have kept. We optimize cut and fill iteratively against the constraints that actually govern — finished floor relationships, ADA slopes, drainage patterns, and retaining wall costs — and we present the tradeoffs in dollars, not just contours. When a retaining wall is cheaper than the fill it avoids, or a slightly higher pad elevation eliminates an import, the grading plan should say so, and ours does. The same cost lens applies to pavement sections, pipe materials, and basin geometry — every one of them has a cheaper alternative that still meets the standard, and finding it is part of the engineering.",
        ],
      },
    ],
    deliverables: [
      { title: "Grading & Drainage Plans", desc: "Sealed grading, drainage, and paving plans with earthwork quantities and a computed drainage report." },
      { title: "Stormwater Design", desc: "Retention/detention sizing, water-quality treatment design, and the hydrology report in your agency's required format." },
      { title: "Utility Plans", desc: "Water, fire, sewer, and storm main design with district coordination and points of connection." },
      { title: "SWPPP & Erosion Control", desc: "Construction-phase stormwater pollution prevention plans and erosion-control sheets for permit issuance." },
    ],
    useCases: [
      "Commercial pad and retail site development",
      "Industrial yards and truck maneuvering design",
      "Multifamily and subdivision site plans",
      "ADA path-of-travel and parking upgrades",
      "Drainage problem investigation and correction",
      "Pre-acquisition feasibility studies",
    ],
    faqs: [
      { q: "Do you work in my city or county?", a: `${LICENSING_COVERAGE_STATEMENT} ${PROJECT_JURISDICTION_NOTE} Civil review is intensely local, so the first thing we do is pull the reviewing agency's design standards and drainage manual — then engineer to them from the first sheet.` },
      { q: "What's the difference between retention and detention?", a: "Retention keeps stormwater on site permanently (infiltration or evaporation); detention stores it temporarily and releases it at a controlled rate. Which one you must provide — and for what storm event — is set by the local jurisdiction, and it materially affects how much land your site design loses." },
      { q: "Can you fix a site that drains toward the building?", a: "Yes. We survey existing grades, compute where the water actually goes, and design regrading, area drains, or storm piping to correct it — with a drainage analysis the jurisdiction will accept if permits are required." },
      { q: "Do you handle ADA site compliance?", a: "Yes — accessible parking counts and dimensions, running and cross slopes on every accessible route, ramp and landing geometry, and detectable warnings. ADA site citations are among the most common and most expensive to fix after paving, so we verify them at design." },
      { q: "What does a feasibility study include?", a: "Conceptual grading with cut/fill estimate, utility availability and probable points of connection, preliminary stormwater sizing, and a summary of the entitlements and permits the jurisdiction will require — delivered before you close on the land." },
    ],
  },
  {
    slug: "mechanical-engineering",
    name: "Mechanical Engineering",
    shortName: "Mechanical",
    h1: "Mechanical (HVAC) Engineering Services",
    metaTitle: "Mechanical Engineering Services | HVAC Design & Load Calculations | Apex Grid",
    metaDescription:
      "Mechanical HVAC engineering: room-by-room load calculations, equipment selection, duct design, ventilation per ASHRAE 62.1, and energy-code-compliant mechanical permit sets stamped by licensed PEs.",
    kicker: "HVAC & Mechanical Systems",
    lede:
      "Heating, cooling, and ventilation systems sized from real load calculations — designed for occupant comfort, energy-code compliance, and equipment that lasts because it isn't oversized.",
    sections: [
      {
        heading: "Load Calculations First, Equipment Second",
        paragraphs: [
          "Most comfort complaints, short-cycling equipment, and humidity problems trace back to one root cause: systems sized by square-footage rules of thumb instead of engineering. Every mechanical design we produce starts with a room-by-room heating and cooling load calculation — actual wall, roof, and glazing constructions, real orientation and shading, occupancy and equipment gains, and the local design-day conditions. Only then do we select equipment, and we select it at the calculated load, derated for altitude and climate where applicable.",
          "System selection is matched to the building, not to habit: packaged rooftop units for single-story commercial, split and VRF systems where zoning and part-load efficiency matter, dedicated outdoor air systems where ventilation loads dominate, and hydronic systems where the scale justifies them. Duct design uses static-regain or equal-friction methods with documented pressure-drop budgets, so the fan we schedule actually delivers the airflow on the plans.",
          "Ventilation is engineered to ASHRAE 62.1 (or the mechanical code's equivalent tables): outdoor-air rates by occupancy, demand-controlled ventilation where the energy code requires it, and exhaust systems — restaurant hoods, restroom exhaust, process exhaust — designed with makeup air so the building isn't fighting itself. Kitchen and Type I hood projects include the hood, duct, fire-wrap, and makeup-air package the fire marshal will ask about.",
        ],
      },
      {
        heading: "Compliance, Controls, and Replacements",
        paragraphs: [
          "Mechanical permit sets include the energy-code documentation reviewers demand: equipment efficiencies against the adopted IECC or Title 24 requirements, economizer applicability, duct insulation and sealing notes, and controls narratives covering thermostatic zoning, setback, and demand-controlled ventilation. Structural coordination is built in — rooftop unit weights and anchorage go to our structural team, not to a note that says 'by others.'",
          "We also handle the smallest common scope in mechanical engineering: like-for-like and upsized equipment replacements. Many jurisdictions now require permits, load justification, and energy compliance even for changeouts, and we turn those packages around quickly so a failed unit doesn't become a failed inspection.",
        ],
      },
      {
        heading: "Designing for the Climate the Building Actually Lives In",
        paragraphs: [
          `A mechanical design that works in coastal California will underperform in Phoenix and fail differently in Minneapolis. Design-day conditions drive everything: condenser capacity derates steeply at 115°F ambient, so equipment selected from nominal ratings comes up short exactly when the building needs it most; cold-climate heat pumps need balance-point analysis and supplemental heat sizing; humid-climate buildings need latent capacity and sometimes reheat that a dry-climate design would never include. ${LICENSING_COVERAGE_STATEMENT} ${PROJECT_JURISDICTION_NOTE} Checking the actual ASHRAE design conditions for the project site — not a national default — is built into our load calculation workflow.`,
          "Altitude, economizer requirements, and ventilation strategy shift by geography too. Above roughly 2,500 feet, air density corrections change fan and equipment selections. Energy codes make airside economizers mandatory in some climate zones and pointless in others. Humid regions punish over-ventilated buildings with mold risk; arid regions reward evaporative pre-cooling that would be useless in the Southeast. These are not exotic optimizations — they are the difference between a system that meets its design intent and one that generates comfort complaints for the life of the building.",
          "The engagement itself is straightforward: backgrounds and use description in, fixed-fee proposal out, typically within a day. Design includes coordination with our own structural engineers for equipment support and anchorage and with our electrical engineers for connected loads — so the mechanical schedule, the structural roof framing check, and the electrical panel schedule always agree. After permit we review equipment submittals against scheduled capacities (a substituted unit that is two percent short on paper can be twenty percent short at design conditions), answer RFIs, and verify test-and-balance reports so the airflows the drawings promised are the airflows the building delivers.",
          "Indoor air quality and pressurization round out the discipline. Buildings need to be engineered slightly positive relative to outdoors in most climates — negative buildings pull unconditioned, unfiltered, humid air through every crack in the envelope, which is how conference rooms grow musty and drywall grows mold. We balance outdoor air against exhaust room by room, specify filtration appropriate to the use (MERV 13 has become the de facto floor for many owners since 2020), and design kitchen, laboratory, and process exhaust with the capture velocities and makeup-air paths that keep contaminants moving out rather than drifting into adjacent spaces. These details never appear in a rule-of-thumb design, and they are precisely the ones occupants notice. When an existing building has chronic odor, humidity, or stuffiness complaints, a pressurization and airflow diagnosis is usually where the answer lives, and it is a standalone scope we take on regularly — measurement, root-cause analysis, and a corrective design the owner can permit and build.",
        ],
      },
    ],
    deliverables: [
      { title: "Mechanical Permit Sets", desc: "Plans, equipment schedules, details, and specifications stamped by a licensed mechanical PE." },
      { title: "Load Calculation Reports", desc: "Room-by-room heating and cooling loads documented for plan check and equipment selection." },
      { title: "Ventilation & Exhaust Design", desc: "ASHRAE 62.1 outdoor-air calculations, exhaust and makeup-air systems, and kitchen hood packages." },
      { title: "Energy Compliance", desc: "Mechanical energy-code documentation — IECC, state codes, or Title 24 — included with the permit set." },
    ],
    useCases: [
      "Rooftop unit design and replacement permits",
      "Restaurant hood and makeup-air systems",
      "Office, retail, and medical tenant improvements",
      "VRF and split-system design for multifamily",
      "Warehouse ventilation and evaporative cooling",
      "Comfort problem diagnosis and re-engineering",
    ],
    faqs: [
      { q: "Why does oversizing matter if bigger seems safer?", a: "An oversized system satisfies the thermostat before it dehumidifies or mixes the air, so you get short cycles, clammy spaces, uneven temperatures, and premature compressor wear — plus a larger electrical service than the building needed. Right-sizing from a load calculation avoids all of it." },
      { q: "Do I need an engineer for an equipment changeout?", a: "Increasingly, yes. Many jurisdictions require permits, load justification, and energy-code compliance for replacements — especially upsizing. We produce changeout packages quickly, including the structural anchorage check for rooftop units." },
      { q: "Can you design a kitchen exhaust system?", a: "Yes — Type I and Type II hoods, grease duct routing and fire protection, exhaust fan sizing, and the makeup-air system, coordinated as one package with the fire and building reviewers in mind." },
      { q: "What is a DOAS and do I need one?", a: "A dedicated outdoor air system conditions ventilation air separately from the heating/cooling terminals. It shines in buildings with high occupancy or strict humidity control — schools, gyms, medical — and we'll tell you honestly when your project doesn't need one." },
      { q: "Do your mechanical designs include controls?", a: "Every set includes a controls narrative and points summary appropriate to the system — thermostatic zoning, scheduling and setback, economizer logic, and demand-controlled ventilation where the energy code requires it." },
    ],
  },
  {
    slug: "electrical-engineering",
    name: "Electrical Engineering",
    shortName: "Electrical",
    h1: "Electrical Engineering Services",
    metaTitle: "Electrical Engineering Services | Power Distribution & Lighting Design | Apex Grid",
    metaDescription:
      "Electrical engineering to the NEC: service sizing, one-line diagrams, panel schedules with Article 220 load calcs, lighting and controls design, and emergency power — permit-ready and PE-stamped.",
    kicker: "Power & Lighting Systems",
    lede:
      "Power distribution, lighting, and life-safety electrical systems engineered to the National Electrical Code — with the load calculations, one-line diagrams, and fault-current data reviewers and utilities actually ask for.",
    sections: [
      {
        heading: "Distribution Design That Survives Plan Check",
        paragraphs: [
          "Electrical plan review turns on documentation: a one-line diagram that matches the panel schedules, NEC Article 220 load calculations that justify the service size, and fault-current values that prove the equipment ratings. We produce all of it as a matter of course. Service and feeder design covers utility coordination for new or upgraded services, transformer and switchboard selection, grounding and bonding per Article 250, and voltage-drop checks on long feeder and branch runs so circuits perform at their rated load, not just on paper.",
          "Panel schedules are built from connected and demand loads with the code-permitted demand factors applied and shown — the difference between a service that passes review and one that draws a correction letter asking where the numbers came from. Short-circuit calculations establish available fault current at each bus, and we document series ratings or fully rated equipment accordingly. For projects with generators or larger services, we address selective coordination where the code requires it.",
          "Lighting design pairs photometric layouts with the energy code's lighting power allowances and mandatory controls: occupancy sensors, daylight-responsive dimming, automatic shutoff, and exterior lighting curfews, each documented in a controls narrative the inspector can verify. Egress and emergency lighting is designed to the illumination levels the building code requires, with battery or generator backup circuits identified on the plans.",
        ],
      },
      {
        heading: "Specialty Scopes and Existing Buildings",
        paragraphs: [
          "Beyond core distribution, we engineer EV charging infrastructure with load management where the service can't simply be doubled, photovoltaic interconnections with the required placards and rapid-shutdown documentation, generator and transfer-switch systems for standby power, and motor and equipment circuits for industrial tenants. Each of these scopes has its own code articles and its own reviewer expectations, and each package we deliver is written to them.",
          "Existing-building work — service upgrades, panel replacements, tenant fit-outs on aging infrastructure — starts with a field-verified assessment of what is actually installed. We document existing conditions, calculate spare capacity honestly, and tell you before design begins whether the existing service can carry the new load or an upgrade is unavoidable.",
        ],
      },
      {
        heading: "From Utility Coordination to Final Inspection",
        paragraphs: [
          "Electrical projects have a stakeholder no other trade deals with as directly: the serving utility. New services, capacity increases, and transformer changes all run through the utility's own engineering queue, which in many territories is now the longest lead item on the entire project. We start that process early — load letters, site plans showing equipment locations and clearances, and coordination on primary routing — while the customer-side design proceeds in parallel, so the utility's timeline and the permit timeline converge instead of stacking.",
          "The design phase is anchored by calculations that must agree with each other: the Article 220 service calculation, the panel schedules that roll up to it, the one-line diagram that depicts it, and the fault-current study that proves the equipment can safely interrupt what the utility can deliver. Reviewers check for exactly this internal consistency, and so do we — a one-line showing a 400-amp main over panel schedules that sum to 600 amps of demand is the kind of contradiction that turns one review cycle into three. Voltage drop on long runs, conductor derating for conduit fill and ambient temperature, and working-clearance layouts drawn to scale round out the package.",
          "Coordination with the other trades is continuous because electrical touches everything: mechanical equipment schedules feed the load calculation, so a late RTU substitution gets re-checked against its circuit and breaker; the structural team confirms roof and pad support for transformers and generators; the plumbing team's water heaters and pumps appear on our panel schedules. After permit, we review switchgear and fixture submittals, confirm that substituted equipment preserves the fault-current ratings and coordination assumptions in the study, respond to inspector questions during rough and final, and update the one-line to as-built conditions — because the next engineer to touch the building will start from that drawing.",
          "Capacity planning is where electrical design earns its keep over the life of a building. Electrification is pushing loads upward everywhere: heat pumps replacing gas furnaces, EV chargers appearing in lease requirements, induction replacing gas ranges, and battery storage arriving alongside solar. A service sized to yesterday's load with no spare capacity converts each of those upgrades into a five-figure service replacement. We design distribution with documented spare capacity and physical space for future breakers, and when budgets are tight we at least rough in the pathways — conduit stubs and panel space cost hundreds during construction and thousands after it. Owners planning a phased buildout get a load roadmap showing exactly what the service can absorb before an upgrade becomes unavoidable, with each phase's demand documented against the service rating.",
        ],
      },
    ],
    deliverables: [
      { title: "Permit-Ready Electrical Sets", desc: "Power plans, lighting plans, one-line diagrams, panel schedules, details, and specifications stamped by a licensed PE." },
      { title: "NEC Load Calculations", desc: "Article 220 service and feeder calculations with demand factors documented for plan review." },
      { title: "Fault Current & Coordination", desc: "Short-circuit calculations, equipment ratings documentation, and selective coordination where required." },
      { title: "Lighting & Controls Package", desc: "Photometrics, fixture schedules, energy-code lighting compliance, and controls narratives." },
    ],
    useCases: [
      "Service upgrades and utility coordination",
      "Tenant improvement power and lighting",
      "EV charging infrastructure and load management",
      "Generator and standby power systems",
      "Solar PV interconnection documentation",
      "Industrial equipment and motor circuits",
    ],
    faqs: [
      { q: "How do I know if my existing service can handle new equipment?", a: "With an NEC Article 220 load calculation against the existing service rating — either from historical demand data or a documented connected-load analysis. We do this before design, so you know whether a service upgrade is in the budget on day one." },
      { q: "Do you coordinate with the utility company?", a: "Yes. New services, upgrades, and transformer changes all run through the serving utility's engineering process, and we prepare the load letters and site documentation they require while designing the customer side to match." },
      { q: "What do you need for an EV charging design?", a: "The charger count and levels you want, the panel and service information for the building, and the site plan. We design the distribution, apply load-management where it saves a service upgrade, and document the ventilation and signage requirements that come with it." },
      { q: "Can you stamp electrical drawings for my solar installer?", a: "Yes — we produce or review one-lines, calculations, and interconnection documentation for PV systems, coordinated with the AHJ's and the utility's submission requirements." },
      { q: "Do your lighting designs handle energy-code controls?", a: "Every lighting package includes the mandatory controls for the adopted energy code — occupancy sensing, daylighting zones, automatic shutoff — documented in a narrative format inspectors can walk and verify." },
    ],
  },
  {
    slug: "plumbing-engineering",
    name: "Plumbing Engineering",
    shortName: "Plumbing",
    h1: "Plumbing Engineering Services",
    metaTitle: "Plumbing Engineering Services | Water, Waste, Gas & Storm Design | Apex Grid",
    metaDescription:
      "Plumbing engineering: fixture-unit water sizing, sanitary waste and vent design, gas piping calculations, storm drainage, water heaters, and backflow prevention — permit-ready sets stamped by licensed PEs.",
    kicker: "Water, Waste & Gas Systems",
    lede:
      "Domestic water, sanitary, storm, and fuel-gas systems engineered by calculation — fixture units, pressure budgets, and slope checks documented so plan reviewers approve and installers don't improvise.",
    sections: [
      {
        heading: "Sized by Calculation, Not Habit",
        paragraphs: [
          "Plumbing looks simple until it fails plan check — or worse, until the top-floor fixtures starve at peak demand. Our domestic water design starts with a fixture-unit count per the adopted plumbing code (UPC or IPC), converts it to demand flow, and works through a documented pressure budget: street pressure, meter and backflow losses, elevation head, and pipe friction, ending with the residual pressure at the most remote fixture. If the math says a booster pump or a pressure-reducing valve is needed, it appears on the drawings — not as a field surprise.",
          "Sanitary design assigns drainage fixture units, sizes branches and stacks per the code tables, and verifies slope and cleanout placement so the system is maintainable, not just compliant. Venting is engineered — conventional, circuit, or air-admittance where the jurisdiction allows — because improper venting is the most common source of failed inspections and trap-siphoning callbacks. Grease interceptors for food service are sized to the local pretreatment authority's formula and coordinated with the civil site design for access and pumping.",
          "Fuel-gas piping is calculated on total connected BTU load with the longest-run method, documented pipe-by-pipe, with regulator selection and vent terminations located per code clearances. Storm drainage covers roof drain and overflow sizing for the local rainfall intensity, piping to the point of discharge, and coordination with the civil stormwater system.",
        ],
      },
      {
        heading: "Water Heating, Backflow, and Specialty Systems",
        paragraphs: [
          "Water heater design is matched to the demand profile: storage versus tankless, recovery rates for high-demand uses like restaurants and salons, hot-water recirculation to meet the energy code's dead-leg limits, and thermal expansion control. Mixed-use and multifamily buildings get central-versus-distributed analyses so developers can see the tradeoff in riser space, metering, and maintenance before committing.",
          "Backflow prevention is engineered to the water purveyor's cross-connection control program — assembly type, location, and access documented for the district's inspector. We also design specialty scopes: medical gas systems coordinated with NFPA 99 requirements, compressed air for shops, and acid-waste systems for labs, each with the code documentation the specialty inspector expects to see.",
        ],
      },
      {
        heading: "Where Plumbing Projects Go Wrong — and How We Prevent It",
        paragraphs: [
          "The most expensive plumbing problems are elevation problems. A sanitary main that arrives at the street sewer below the district's invert forces an ejector pump and a lifetime of maintenance; a grease interceptor set without checking the kitchen's slab elevations ends up with fixtures that cannot gravity-drain to it. We design waste systems backwards from the point of connection — verified invert, not assumed — through every interceptor, cleanout, and fixture, with slopes checked at each segment. On tenant improvements, we pothole or camera-verify the existing building drain before committing a layout to it, because record drawings of under-slab piping are wrong more often than they are right.",
          `The second failure mode is jurisdictional. UPC and IPC states size differently; water purveyors run their own backflow programs with their own approved-assembly lists; pretreatment authorities each publish their own interceptor formula; and health departments layer requirements onto food-service plumbing that the plumbing code never mentions. ${LICENSING_COVERAGE_STATEMENT} ${PROJECT_JURISDICTION_NOTE} We check each of these authorities by name for every project, and the drawings cite the specific standards each inspector will enforce — so the health inspector, the cross-connection inspector, and the building inspector are all reading a set that already speaks their language.`,
          "The engagement runs like our other disciplines: backgrounds in, fixed-fee proposal out within about a day, then design coordinated live with the mechanical, electrical, and civil teams — gas loads onto the mechanical equipment schedule, water heater circuits onto the panel schedule, and the building sewer aligned with the civil site utilities at an agreed point of connection five feet outside the building. Permit sets include isometric diagrams where jurisdictions require them, and after permit we review fixture and equipment submittals, answer RFIs with sketches, and support the rough-in, top-out, and final inspections through closeout.",
          "Water efficiency has quietly become a design driver alongside code compliance. Modern energy and green codes cap fixture flow rates, many western jurisdictions add their own conservation ordinances, and owners increasingly ask for the operating-cost math: a hot-water recirculation system tuned with a demand-controlled pump can cut both water waste and heater runtime, while an oversized one wastes energy around the clock. We design to the strictest applicable standard, document the fixture flow rates on the schedules where inspectors look for them, and flag the incentive programs — utility rebates for high-efficiency water heaters and low-flow retrofits are common — that can offset the cost of doing it right. Efficient plumbing is not a premium add-on; engineered correctly, it is simply what the calculation produces. The same discipline applies to material selection — copper, PEX, CPVC, and cast iron each have jurisdictions and applications where they belong, and our specifications say which and why.",
        ],
      },
    ],
    deliverables: [
      { title: "Permit-Ready Plumbing Sets", desc: "Water, waste, vent, storm, and gas plans with isometrics, schedules, and details stamped by a licensed PE." },
      { title: "Sizing Calculations", desc: "Fixture-unit counts, pressure-budget analysis, gas load calculations, and storm sizing documented for plan review." },
      { title: "Water Heating Design", desc: "Heater selection, recirculation design, and energy-code hot-water compliance documentation." },
      { title: "Interceptor & Backflow Packages", desc: "Grease interceptor sizing to the pretreatment authority's formula and backflow assemblies per the purveyor's program." },
    ],
    useCases: [
      "Restaurant and commercial kitchen plumbing",
      "Tenant improvements and fixture additions",
      "Multifamily domestic water and recirculation",
      "Gas piping for new equipment and generators",
      "Grease interceptor sizing and permits",
      "Medical gas and specialty piping systems",
    ],
    faqs: [
      { q: "UPC or IPC — does it matter which code my state uses?", a: `Yes — sizing tables, venting rules, and fixture requirements differ between the Uniform Plumbing Code and International Plumbing Code. We design to whichever your jurisdiction has adopted. ${LICENSING_COVERAGE_STATEMENT} ${PROJECT_JURISDICTION_NOTE} We track which is which.` },
      { q: "Why did the city ask for a grease interceptor calculation?", a: "Food-service uses discharge grease that municipal treatment can't accept, so pretreatment authorities require an interceptor sized by their published formula — typically based on fixture flow or meals served. We produce that calculation and coordinate the interceptor's location with the site design." },
      { q: "Can you tell me if my water pressure will support an addition?", a: "Yes — a fixture-unit and pressure-budget analysis against your street pressure answers it definitively. If the numbers fall short, the fix is usually a larger meter, a pressure-reducing valve reconfiguration, or a booster pump, and we'll show you which." },
      { q: "Do you design gas piping for generators and rooftop equipment?", a: "Yes. New gas loads change the total connected demand, which can require re-sizing runs back to the meter. We calculate the whole system, not just the new branch, so the existing equipment keeps working when the new load fires." },
      { q: "What's required for hot-water recirculation?", a: "Modern energy codes limit how much water can sit stranded between the heater and the fixture. Recirculation loops, demand-controlled pumps, or point-of-use heaters are the standard solutions, and we select based on the building's layout and hours of use." },
    ],
  },
];
