/** Existing Building Engineering ecosystem pages. */

export interface ExistingBuildingPage {
  slug: string;
  title: string;
  description: string;
  h1: string;
  kicker: string;
  lede: string;
  topics: string[];
  note?: string;
}

export const EXISTING_BUILDING_PAGES: ExistingBuildingPage[] = [
  {
    slug: "condition-assessments",
    title: "Existing Building Condition Assessments | Apex Grid Engineering",
    description: "Structural and MEP condition assessments for existing commercial buildings — written reports with findings, deficiency documentation, and repair recommendations.",
    h1: "Existing Building Condition Assessments",
    kicker: "Existing Building Assessment",
    lede: "A condition assessment documents the current state of a building's structural system or MEP systems — identifying deficiencies, prioritizing repairs, and providing the engineering data needed for capital planning, acquisition due diligence, or permit applications.",
    topics: [
      "Visual assessment of structural and MEP systems",
      "Identification and documentation of deficiencies",
      "Repair priority classification",
      "Cost guidance for capital planning",
      "Written engineering report with photos",
      "Recommendations for follow-up design",
      "Pre-acquisition due diligence assessments",
      "Post-event assessments (seismic, storm, impact)",
    ],
  },
  {
    slug: "no-existing-plans",
    title: "Structural Engineering Without Existing Building Plans | Apex Grid",
    description: "Need structural engineering but don't have original drawings? We work from field verification, contractor measurements, photos, and city records to engineer existing buildings.",
    h1: "Structural Engineering When Existing Drawings Aren't Available",
    kicker: "No Drawings? No Problem.",
    lede: "A large percentage of existing building projects have no drawings on file. Engineers work through this all the time — using field verification, contractor-provided measurements and photos, city records, and exploratory openings to document existing conditions and design modifications responsibly.",
    topics: [
      "Field verification process and documentation requirements",
      "Contractor-provided photos and measurements",
      "Exploratory openings to expose concealed framing",
      "City building department records requests",
      "Matterport and 3D scanning for as-built geometry",
      "When a professional site visit is required",
      "Engineering on the basis of verified field data",
      "Permit submittals for buildings without original drawings",
    ],
    note: "Working without original drawings adds engineering time and sometimes cost — but it doesn't make a project impossible. Contact us with what you have and we'll tell you what additional information is needed.",
  },
  {
    slug: "field-verification",
    title: "Engineering Field Verification for Existing Buildings | Apex Grid",
    description: "Field verification documents existing building conditions for engineering — framing, connections, foundations, and systems — when original drawings are unavailable.",
    h1: "Engineering Field Verification for Existing Buildings",
    kicker: "Field Verification Engineering",
    lede: "Field verification collects the physical data about an existing building that engineering design depends on — member sizes, connections, spans, and conditions — directly from the building itself.",
    topics: [
      "Framing exposure and member measurement",
      "Connection inspection and documentation",
      "Foundation type and condition verification",
      "MEP system identification and capacity assessment",
      "Photographic documentation standards",
      "Coordinate with contractor for access and openings",
      "Field report production for engineering basis",
    ],
  },
  {
    slug: "contractor-field-verification",
    title: "Contractor-Assisted Field Verification for Engineering | Apex Grid",
    description: "On many existing building projects, contractor-provided field information — photos, measurements, and framing data — supports structural engineering without requiring an engineer site visit.",
    h1: "Contractor-Assisted Field Verification for Engineering",
    kicker: "Contractor Field Documentation",
    lede: "When contractors provide high-quality field documentation — photographs, measured dimensions, framing member sizes from exposed conditions — this information can support structural engineering remotely for many project types. Here's how to collect it correctly.",
    topics: [
      "What photos to take and how to label them",
      "Measuring framing members — steel, wood, concrete",
      "Documenting connections and bearing conditions",
      "Recording floor plan dimensions and wall locations",
      "Exploratory opening scope and location",
      "When contractor documentation is sufficient",
      "When a professional engineer site visit is required instead",
    ],
    note: "Contractor-provided field information supports engineering review and does not replace a licensed professional engineer's site visit in all circumstances. The engineer determines whether additional direct observation is required.",
  },
  {
    slug: "structural-cracks",
    title: "Structural Engineering Evaluation of Building Cracks | Apex Grid",
    description: "Not all cracks are structural problems — but some are. A structural engineer evaluates crack patterns, causes, and severity to determine whether repair is needed.",
    h1: "Structural Engineering Evaluation of Building Cracks",
    kicker: "Structural Crack Evaluation",
    lede: "Building cracks range from cosmetic shrinkage cracking to indicators of significant structural movement. A structural engineer evaluates the pattern, location, width, and context of cracks to determine cause, assess risk, and recommend appropriate action.",
    topics: [
      "Crack pattern interpretation — structural vs. cosmetic",
      "Diagonal cracks at openings — what they mean",
      "Stair-step cracking in masonry and CMU",
      "Horizontal cracks in foundation or retaining walls",
      "Settlement-related cracking patterns",
      "Monitoring cracks vs. repairing them",
      "When to call a structural engineer immediately",
      "Written engineering report for insurance or permit",
    ],
  },
  {
    slug: "foundation-issues",
    title: "Structural Evaluation of Foundation Issues | Apex Grid Engineering",
    description: "Structural and geotechnical engineering evaluation of foundation problems — settlement, movement, cracking, and repair design for commercial and residential buildings.",
    h1: "Structural Evaluation of Foundation Issues",
    kicker: "Foundation Problem Engineering",
    lede: "Foundation movement — settlement, heave, lateral movement, or deterioration — can manifest as building distress symptoms well above grade. A structural engineer evaluates the foundation conditions and designs repairs or mitigation measures.",
    topics: [
      "Foundation settlement and differential settlement",
      "Expansive soil effects on foundations",
      "Lateral movement in basement and retaining walls",
      "Foundation crack evaluation",
      "Geotechnical coordination for soil investigation",
      "Repair options — underpinning, grouting, structural repair",
      "Foundation modification for added loads or additions",
      "Engineering report for insurance or due diligence",
    ],
  },
  {
    slug: "settlement",
    title: "Building Settlement Evaluation and Structural Engineering | Apex Grid",
    description: "Structural and geotechnical evaluation of building settlement — causes, severity assessment, and repair recommendations.",
    h1: "Building Settlement Evaluation and Structural Engineering",
    kicker: "Settlement Engineering",
    lede: "Building settlement — the gradual or sudden sinking of foundations into the soil — can cause structural damage, operational problems, and safety concerns. Engineering evaluation identifies the cause and scope of settlement and guides appropriate remediation.",
    topics: [
      "Differential vs. uniform settlement",
      "Settlement causes — poor soils, inadequate bearing, consolidation",
      "Visual indicators of settlement distress",
      "Elevation survey data interpretation",
      "Geotechnical investigation coordination",
      "Remediation options",
      "Monitoring programs for progressive settlement",
      "Engineering report production",
    ],
  },
  {
    slug: "roof-modifications",
    title: "Structural Engineering for Roof Modifications | Apex Grid",
    description: "Structural engineering for roof modifications in existing buildings — new openings, added equipment, roofing system changes, and load additions.",
    h1: "Structural Engineering for Roof Modifications",
    kicker: "Roof Modification Engineering",
    lede: "Modifying an existing roof — adding equipment, cutting new penetrations, installing solar, changing roofing systems, or adding a rooftop addition — requires structural engineering to verify the existing framing can handle the change.",
    topics: [
      "Existing roof framing capacity evaluation",
      "New rooftop equipment structural support",
      "Roof penetration structural design",
      "Solar PV mounting structure design",
      "Roofing system load change evaluation (added insulation, ballast)",
      "Structural repair design for damaged roof framing",
      "Snow load and drift evaluation for modified roofs",
    ],
  },
  {
    slug: "rooftop-equipment",
    title: "Structural Evaluation for Rooftop Equipment | Apex Grid Engineering",
    description: "Structural engineering for new and replacement rooftop HVAC, generators, solar, and mechanical equipment — capacity verification and support design.",
    h1: "Structural Evaluation for Rooftop Equipment",
    kicker: "Rooftop Equipment Structural Engineering",
    lede: "Adding or replacing equipment on an existing roof imposes loads on the structural framing below. Engineering verification confirms the roof can handle the load — or designs the reinforcement needed to make it work.",
    topics: [
      "RTU replacement and new installation engineering",
      "Generator and transformer rooftop structural support",
      "Solar PV mounting structure engineering",
      "Telecom equipment and antenna structural support",
      "Battery energy storage systems on rooftops",
      "Equipment weight verification from manufacturer data sheets",
      "Existing roof framing evaluation",
      "Permit calculations and detail drawings",
    ],
  },
  {
    slug: "wall-openings",
    title: "Structural Engineering for Existing Wall Openings | Apex Grid",
    description: "Structural engineering for new openings in existing walls — load-bearing wall removals, widened openings, and new door and window locations in commercial buildings.",
    h1: "Structural Engineering for Existing Wall Openings",
    kicker: "Wall Opening Structural Engineering",
    lede: "Creating new openings or widening existing openings in load-bearing walls requires structural engineering — confirming the wall's structural role, sizing the replacement beam or header, and designing the load path through the structure below.",
    topics: [
      "Load-bearing wall identification",
      "Beam and header sizing for new openings",
      "Post and column design at beam endpoints",
      "Foundation capacity for concentrated loads",
      "Connection design",
      "Commercial and residential applicability",
      "Permit drawings for wall removal scope",
      "Coordination with architectural intent",
    ],
  },
  {
    slug: "repair-design",
    title: "Engineering Design for Existing Building Repairs | Apex Grid",
    description: "Structural repair engineering for existing commercial buildings — repair design, permit drawings, and construction details for structural damage and deficiencies.",
    h1: "Engineering Design for Existing Building Repairs",
    kicker: "Structural Repair Engineering",
    lede: "Structural repairs in existing buildings require engineering design — not just contractor judgment. The repair must address the actual structural condition, comply with current codes, and be documented for the building permit.",
    topics: [
      "Cracked concrete evaluation and repair design",
      "Wood framing repair for rot, damage, or overload",
      "Steel corrosion assessment and repair",
      "Masonry repair and reinforcement",
      "Foundation repair design",
      "Connection repair and reinforcement",
      "Permit drawings for repair scope",
      "Construction observation during repair",
    ],
  },

  // ─── EXISTING BUILDING DEEP EVALUATION PAGES ────────────────────────────

  {
    slug: "from-city-records",
    title: "Structural Engineering From City Building Department Records | Apex Grid",
    description: "When original structural drawings are unavailable, city building department records often contain permits, plan sets, and inspection records that can serve as the engineering basis for existing-building work.",
    h1: "Structural Engineering From City Building Department Records",
    kicker: "Existing Building · City Records",
    lede: "City and county building departments maintain permit records, plan sets, and inspection histories for buildings constructed under their jurisdiction. When original drawings aren't available elsewhere, city records requests can recover partial or complete structural and MEP information that supports engineering for modifications, repairs, or additions.",
    topics: [
      "Building department public records request process",
      "Types of records typically available — permits, plans, inspections",
      "Partial drawing recovery and engineering basis documentation",
      "Limitations of city records — incomplete, damaged, or missing files",
      "Supplementing city records with field verification",
      "Engineering from partial plans and historical permits",
      "Coordination with building department on existing file availability",
      "When city records are sufficient vs. when field verification is required",
    ],
    note: "City records vary in completeness and may not reflect field-verified as-built conditions. Engineering based on city records is typically supplemented with field verification for critical structural elements.",
  },
  {
    slug: "from-contractor-photos",
    title: "Structural Engineering From Contractor Photos | Apex Grid Engineering",
    description: "Contractor-provided photographs of exposed framing, connections, and existing conditions can support structural engineering remotely — when photos are taken correctly and systematically.",
    h1: "Structural Engineering From Contractor Photos",
    kicker: "Existing Building · Contractor Photos",
    lede: "When contractors open walls, ceilings, or floors to expose existing framing during demolition or rough-in, the information documented in photographs can support structural engineering decisions remotely — avoiding the cost and delay of a separate engineer site visit. The quality and completeness of the photo documentation is what makes this work.",
    topics: [
      "What photos to take and why — framing, connections, dimensions",
      "How to measure and document framing member sizes",
      "Photographing connections — beam-to-column, beam-to-wall, holdowns",
      "Documenting floor plan dimensions and wall locations",
      "Recording material types — lumber, steel, concrete, CMU",
      "Organizing photos with location references and notes",
      "When contractor photos are sufficient vs. when a site visit is needed",
      "How photo packages are reviewed and used by the engineer",
    ],
    note: "Photo-based engineering review requires systematic, complete documentation. Incomplete photo sets may require supplemental field verification or a professional site visit before engineering can proceed.",
  },
  {
    slug: "site-visit-when-required",
    title: "When a Structural Engineer Needs a Site Visit | Apex Grid Engineering",
    description: "Not every existing-building project requires a structural engineer site visit — but some do. Understanding when a site visit is required helps project teams plan schedules and budgets appropriately.",
    h1: "When a Structural Engineer Needs a Site Visit",
    kicker: "Existing Building · Site Visit",
    lede: "A structural engineer site visit may be required when existing conditions are complex, when contractor documentation is insufficient, when the AHJ requires direct observation, or when the engineering decision depends on directly observed conditions that cannot be reliably communicated through photos and measurements alone.",
    topics: [
      "Conditions that typically require a site visit — complex framing, inaccessible areas",
      "When contractor documentation is sufficient to avoid a site visit",
      "AHJ requirements for field observation on specific project types",
      "What an engineer observes and documents during a site visit",
      "Site visit scope — targeted vs. comprehensive observation",
      "Coordination with contractor to expose framing before visit",
      "Site visit report and engineering documentation",
      "Timing site visits relative to construction and permit schedules",
    ],
  },
  {
    slug: "exploratory-openings",
    title: "Exploratory Openings for Existing Building Engineering | Apex Grid",
    description: "Exploratory openings — contractor-cut access to concealed framing — are sometimes required to establish existing conditions for structural engineering when other documentation methods are insufficient.",
    h1: "Exploratory Openings for Existing Building Engineering",
    kicker: "Existing Building · Exploratory Openings",
    lede: "When existing drawings are unavailable and visual observation from accessible areas is insufficient, exploratory openings — contractor-cut access holes in drywall, ceilings, or flooring — expose concealed framing and connections for engineering documentation. Exploratory openings are a standard tool on existing-building projects and can often be patched as part of the finish work.",
    topics: [
      "When exploratory openings are required for structural engineering",
      "How to coordinate exploratory opening scope with the contractor",
      "Location selection — where to open for maximum structural information",
      "Documentation of exposed framing during exploratory openings",
      "Minimizing opening count through strategic placement",
      "Patch and repair coordination after engineering inspection",
      "Cost and schedule implications of exploratory openings",
      "Engineering basis documentation from exploratory opening findings",
    ],
  },
  {
    slug: "existing-roof-framing-evaluation",
    title: "Existing Roof Framing Engineering Evaluation | Apex Grid Engineering",
    description: "Engineering evaluation of existing roof framing systems — capacity assessment, deficiency identification, and modification design for commercial buildings.",
    h1: "Existing Roof Framing Engineering Evaluation",
    kicker: "Existing Building · Roof Framing",
    lede: "Existing roof framing must be evaluated before adding loads, cutting openings, or modifying the framing system. Engineering assessment documents framing member sizes, spans, connections, and capacity — identifying whether the existing system can handle the proposed change or needs reinforcement.",
    topics: [
      "Roof framing type identification — wood joists, trusses, steel, concrete",
      "Framing capacity evaluation for added loads",
      "Rooftop equipment load compatibility assessment",
      "Solar PV mounting load evaluation",
      "Roof opening structural evaluation — skylights, penetrations, equipment curbs",
      "Framing damage and deficiency identification",
      "Reinforcement design for insufficient capacity",
      "Documentation of existing roof framing conditions",
    ],
  },
  {
    slug: "existing-floor-framing-evaluation",
    title: "Existing Floor Framing Engineering Evaluation | Apex Grid Engineering",
    description: "Structural engineering evaluation of existing floor framing for added loads, equipment, mezzanines, and building modifications.",
    h1: "Existing Floor Framing Engineering Evaluation",
    kicker: "Existing Building · Floor Framing",
    lede: "Before adding heavy equipment, mezzanines, elevated storage, or occupancy changes, existing floor framing must be evaluated for structural capacity. Engineering assessment determines whether the existing floor system can support proposed loads — or identifies what reinforcement is required.",
    topics: [
      "Floor framing type identification — wood, steel, concrete",
      "Allowable floor load capacity calculation",
      "Added equipment load compatibility evaluation",
      "Mezzanine and elevated platform support evaluation",
      "Change-of-occupancy floor load review",
      "Vibration sensitivity evaluation for sensitive equipment",
      "Floor deflection evaluation for existing conditions",
      "Reinforcement design for insufficient floor capacity",
    ],
  },
  {
    slug: "existing-masonry-evaluation",
    title: "Existing Masonry Wall Engineering Evaluation | Apex Grid Engineering",
    description: "Structural engineering evaluation of existing masonry walls — CMU, brick, and block — for modifications, openings, load changes, and condition assessment.",
    h1: "Existing Masonry Wall Engineering Evaluation",
    kicker: "Existing Building · Masonry",
    lede: "Masonry walls — concrete masonry units (CMU), brick, and block — behave differently from wood and steel framing and require specific engineering expertise when being modified, assessed for new openings, or evaluated for structural condition. Apex Grid engineers masonry wall evaluations and modification designs.",
    topics: [
      "CMU and brick wall structural role identification",
      "Masonry wall opening and lintel engineering",
      "Masonry crack pattern evaluation and classification",
      "Masonry wall out-of-plane and in-plane capacity",
      "Reinforced vs. unreinforced masonry evaluation",
      "Masonry deterioration and moisture damage assessment",
      "Masonry repair and reinforcement design",
      "Seismic evaluation of unreinforced masonry walls",
    ],
  },
  {
    slug: "existing-electrical-evaluation",
    title: "Existing Electrical Service Engineering Evaluation | Apex Grid",
    description: "Engineering evaluation of existing electrical service capacity, panel conditions, and distribution for commercial building modifications, expansions, and equipment additions.",
    h1: "Existing Electrical Service Engineering Evaluation",
    kicker: "Existing Building · Electrical",
    lede: "Before adding significant electrical loads — new equipment, EV charging, expanded tenant space, or system upgrades — the existing electrical service capacity must be evaluated. Engineering assessment determines available capacity, identifies deficiencies, and designs the upgrades or additions needed.",
    topics: [
      "Existing service capacity evaluation — amps, voltage, configuration",
      "Panel condition and code compliance review",
      "Available circuit and breaker capacity assessment",
      "Load study for proposed electrical additions",
      "Utility service upgrade requirements",
      "EV charging load compatibility evaluation",
      "Arc flash study update requirements for modifications",
      "Engineering documentation for permit and utility coordination",
    ],
  },
  {
    slug: "existing-hvac-system-evaluation",
    title: "Existing HVAC System Engineering Evaluation | Apex Grid Engineering",
    description: "Mechanical engineering evaluation of existing HVAC systems for replacement planning, capacity expansion, modification engineering, and renovation projects.",
    h1: "Existing HVAC System Engineering Evaluation",
    kicker: "Existing Building · HVAC",
    lede: "Understanding the existing HVAC system's capacity, condition, and limitations is essential before planning modifications, additions, or tenant changes. Engineering evaluation documents what's installed, what it can handle, and what engineering is needed to support proposed changes.",
    topics: [
      "Existing equipment inventory and capacity documentation",
      "HVAC system age, condition, and remaining useful life assessment",
      "Capacity evaluation for new or expanded occupancy",
      "Ductwork condition and distribution evaluation",
      "Ventilation compliance with current code requirements",
      "Energy performance baseline assessment",
      "Coordination with existing controls and automation systems",
      "Engineering basis for replacement or modification design",
    ],
  },
  {
    slug: "existing-plumbing-evaluation",
    title: "Existing Plumbing System Engineering Evaluation | Apex Grid",
    description: "Engineering evaluation of existing plumbing systems — domestic water, sanitary, and gas — for commercial building modifications, expansions, and renovation projects.",
    h1: "Existing Plumbing System Engineering Evaluation",
    kicker: "Existing Building · Plumbing",
    lede: "Modifying a commercial building's use, expanding the occupancy, or changing plumbing fixture counts requires evaluating whether the existing plumbing system can support the change. Engineering evaluation documents the existing system, identifies capacity constraints, and designs the additions or modifications needed.",
    topics: [
      "Existing domestic water service capacity and pressure assessment",
      "Sanitary drainage system capacity evaluation",
      "Gas service capacity review for added equipment",
      "Plumbing fixture count and fixture unit calculation",
      "Code compliance review of existing plumbing conditions",
      "Grease waste and grease interceptor adequacy review",
      "Water heater capacity and condition assessment",
      "Engineering documentation for permit applications",
    ],
  },
  {
    slug: "seismic-retrofit-engineering",
    title: "Seismic Retrofit Structural Engineering | Apex Grid Engineering",
    description: "Seismic retrofit structural engineering for existing commercial buildings — evaluation, retrofit design, and permit drawings to improve seismic performance.",
    h1: "Seismic Retrofit Structural Engineering",
    kicker: "Existing Building · Seismic Retrofit",
    lede: "Seismic retrofit improves the earthquake resistance of existing buildings that were designed to earlier, less stringent seismic codes. Apex Grid provides engineering evaluation of existing seismic systems and designs targeted retrofits — shear walls, moment frames, diaphragm connections, and foundation improvements — that improve performance to current standards or project-specific objectives.",
    topics: [
      "Existing seismic system evaluation — shear walls, frames, diaphragms",
      "Seismic deficiency identification and classification",
      "Retrofit design — added shear walls, collectors, drag struts",
      "Foundation upgrade engineering for seismic improvements",
      "ASCE 41 evaluation procedures for existing buildings",
      "Los Angeles and California mandatory retrofit program compliance",
      "Non-structural component seismic anchorage design",
      "Seismic retrofit permit drawings and calculations",
    ],
  },
];

export const EXISTING_BUILDING_HUB = {
  title: "Existing Building Engineering | Structural & MEP | Apex Grid",
  description: "Structural condition assessments, renovation engineering, field verification, repair design, and modification engineering for existing commercial buildings.",
  h1: "Engineering for Existing Buildings",
  lede: "Existing buildings are the majority of our work. We specialize in evaluating what's already there, engineering what needs to change, and producing the documentation to get it permitted and built.",
};
