/** Fixed inventory of curated cities that existed before sourced promotion
 * metadata became mandatory. Never add new cities here; migrate entries out by
 * adding approved research metadata to their CityData record. */
export const LEGACY_CURATED_CITY_KEYS = new Set([
  "alabama/birmingham",
  "connecticut/hartford",
  "indiana/fort-wayne",
  "indiana/indianapolis",
  "iowa/des-moines",
  "kansas/wichita",
  "kentucky/louisville",
  "louisiana/new-orleans",
  "maryland/baltimore",
  "massachusetts/boston",
  "michigan/detroit",
  "michigan/grand-rapids",
  "minnesota/minneapolis",
  "minnesota/st-paul",
  "missouri/kansas-city",
  "missouri/saint-louis",
  "nebraska/lincoln",
  "nebraska/omaha",
  "new-jersey/jersey-city",
  "new-jersey/newark",
  "new-mexico/albuquerque",
  "new-york/buffalo",
  "new-york/new-york",
  "ohio/cincinnati",
  "ohio/cleveland",
  "ohio/columbus",
  "ohio/toledo",
  "oklahoma/oklahoma-city",
  "oklahoma/tulsa",
  "oregon/portland",
  "pennsylvania/philadelphia",
  "pennsylvania/pittsburgh",
  "rhode-island/providence",
  "utah/salt-lake-city",
  "washington/seattle",
  "wisconsin/madison",
  "wisconsin/milwaukee",
]);