import type { EngineeringIntentPage } from "./engineering-intent-pages";

type NationalIntentSeed = {
  slug: string;
  title: string;
  description: string;
  h1: string;
  kicker: string;
  need: string;
  scope: string;
  risks: string;
  inputs: string;
  deliverables: string;
  audience: string;
  phrases: string[];
  overlap: string;
};

function makeNationalIntentPage(seed: NationalIntentSeed): EngineeringIntentPage {
  const answer = `${seed.need} Apex Grid begins by defining the requested decision, the responsible engineering disciplines, the available building information, and the authority or project requirements that apply. The scope is confirmed before design or assessment begins; professional licensure, site access, concealed conditions, and permit requirements remain project-specific.`;
  return {
    slug: seed.slug,
    title: seed.title,
    description: seed.description,
    h1: seed.h1,
    kicker: seed.kicker,
    answer,
    sections: [
      {
        heading: "Start with the buyer’s decision",
        body: `${seed.scope} A useful engineering request identifies the decision that must follow: proceed with acquisition, establish a renovation basis, select a system, prepare permit documents, budget a repair, or resolve a known condition. That decision determines the level of investigation and prevents a broad request from producing a report that does not answer the project team’s actual question.`,
      },
      {
        heading: "Existing conditions shape the scope",
        body: `${seed.risks} Existing drawings are reviewed as records, not treated automatically as verified field conditions. The engineer identifies where photographs, measurements, selective openings, testing, survey information, equipment data, or a site observation may be needed. Inaccessible and concealed conditions are documented as limitations rather than filled with unsupported assumptions.`,
      },
      {
        heading: "Information to assemble before kickoff",
        body: `${seed.inputs} Also include the project address, current use, proposed use, jurisdiction, schedule context, known construction history, prior reports, permit correspondence, and the name of the person who will rely on the result. Current architectural backgrounds and clearly labeled photographs help the team separate confirmed facts from items that still require verification.`,
      },
      {
        heading: "Coordinate the engineering disciplines",
        body: `The requested outcome may involve structural, mechanical, electrical, plumbing, civil, geotechnical, accessibility, energy, or fire-protection coordination. Apex Grid identifies the engineering disciplines within its proposed scope and the information needed from architects, specialty consultants, contractors, owners, manufacturers, utilities, or the authority. Discipline coordination does not transfer responsibilities that remain with other project participants.`,
      },
      {
        heading: "Define a usable deliverable",
        body: `${seed.deliverables} The proposal should state the format, design basis, assumptions, exclusions, number of review cycles, and whether construction support or permit responses are included. A memorandum, assessment, calculation, drawing package, or permit set serves a different purpose, so the deliverable must match the next approval, pricing, procurement, or construction decision.`,
      },
      {
        heading: "Plan for code and permit review",
        body: `Applicable codes and submission requirements depend on the project location, adopted editions, local amendments, occupancy, scope of alteration, and authority interpretation. Engineering can document a code basis and support a permit submission, but the authority having jurisdiction decides acceptance. No page, proposal, drawing, or calculation can guarantee permit approval, inspection results, or a particular review duration.`,
      },
      {
        heading: "Avoid preventable scope gaps",
        body: `Common problems include using superseded plans, omitting prior alterations, ordering equipment before capacity is checked, assuming existing systems comply with current code, and requesting a sealed conclusion without sufficient evidence. The project team should record open questions, field-verification needs, owner decisions, and changes made after kickoff. Material changes may require additional review, calculations, drawings, or authority coordination.`,
      },
      {
        heading: "A practical intake checklist",
        body: `Send the address, jurisdiction, requested outcome, current and proposed plans, relevant photographs, prior calculations or reports, permit or inspection correspondence, product data, access constraints, and target decision date. Identify what is already known, what is suspected, and what remains concealed. Apex Grid can then assess fit, qualified engineer availability, required verification, and the narrowest defensible scope without implying nationwide licensure or local presence.`,
      },
    ],
    faqs: [
      {
        q: `What should I send for ${seed.h1.toLowerCase()}?`,
        a: `Send the project address, requested decision, current and proposed plans, photographs, prior reports, jurisdiction correspondence, access limits, and schedule context. Product or equipment data should be included when it affects the scope.`,
      },
      {
        q: "Can the work be completed from existing drawings and photographs?",
        a: "Sometimes. The responsible engineer determines whether the records are adequate or whether measurements, selective openings, testing, survey information, or a site observation are required.",
      },
      {
        q: "Does the engineering scope guarantee permit approval?",
        a: "No. Engineering can prepare and support a defined submission, but the authority having jurisdiction determines permit acceptance and inspection outcomes.",
      },
      {
        q: "Will every engineering discipline be included?",
        a: "Only the disciplines identified in the agreed scope are included. The project may also require an architect, specialty consultant, contractor, surveyor, testing agency, utility, or other project participant.",
      },
    ],
    phrases: seed.phrases,
    audience: seed.audience,
    overlap: seed.overlap,
  };
}

const NATIONAL_FACILITY_INTENT_SEEDS: NationalIntentSeed[] = [
  {
    slug: "warehouse-conversion-engineering",
    title: "Warehouse Conversion Engineering Services | Apex Grid",
    description: "Engineering for warehouse conversions, including new occupancies, floor loads, MEP capacity, egress coordination, accessibility, and permit documents.",
    h1: "Warehouse Conversion Engineering",
    kicker: "Facility Conversion",
    need: "Warehouse conversions require more than a new floor plan because the proposed use can change structural loads, ventilation, power, plumbing, accessibility, and life-safety needs.",
    scope: "The review compares the warehouse’s known construction and current occupancy with the proposed use, occupant load, equipment, storage configuration, interior build-out, and site demands.",
    risks: "Long spans, slab capacity, roof-supported equipment, limited utilities, unconditioned space, prior additions, and undocumented alterations can affect feasibility.",
    inputs: "Provide existing plans, a proposed layout, intended occupancy, equipment and storage loads, clear heights, utility information, and records of prior alterations.",
    deliverables: "Depending on the decision, work may include a feasibility memorandum, structural and MEP assessments, design criteria, coordinated permit drawings, calculations, and responses to review comments.",
    audience: "Developers, warehouse owners, architects, contractors, and prospective tenants",
    phrases: ["warehouse conversion engineer", "warehouse adaptive reuse engineering", "convert warehouse engineering"],
    overlap: "Facility-specific conversion intent; the adaptive-reuse page remains the general change-of-use canonical.",
  },
  {
    slug: "office-renovation-engineering",
    title: "Office Renovation Engineering | Structural & MEP | Apex Grid",
    description: "Engineering for commercial office renovations, including layout changes, HVAC zoning, electrical capacity, plumbing, accessibility, and permit coordination.",
    h1: "Office Renovation Engineering",
    kicker: "Workplace Renovation",
    need: "Office renovations can affect structural framing, HVAC zoning, electrical distribution, lighting, plumbing fixtures, accessibility, and egress even when the exterior remains unchanged.",
    scope: "The engineering basis starts with the proposed workplace layout, occupant count, meeting and support spaces, equipment density, landlord criteria, and the condition of existing systems.",
    risks: "Above-ceiling congestion, limited outdoor air, panel capacity, floor penetrations, demising walls, acoustic expectations, and occupied adjacent suites often control the design.",
    inputs: "Provide the test-fit or architectural plan, reflected ceiling plan, equipment loads, existing MEP drawings, landlord criteria, accessibility concerns, and phasing needs.",
    deliverables: "The defined scope may produce structural details, HVAC and electrical plans, plumbing modifications, energy documentation, calculations, and coordinated permit sheets.",
    audience: "Office tenants, building owners, architects, workplace teams, and general contractors",
    phrases: ["office renovation engineer", "commercial office remodel engineering", "office fit out MEP engineering"],
    overlap: "Office-specific renovation intent; broader tenant-improvement and renovation pages remain cross-facility resources.",
  },
  {
    slug: "retail-renovation-engineering",
    title: "Retail Renovation Engineering Services | Apex Grid",
    description: "Structural and MEP engineering for retail renovations, storefront changes, lighting, HVAC, service upgrades, accessibility, and permit packages.",
    h1: "Retail Renovation Engineering",
    kicker: "Retail Facility Renovation",
    need: "Retail renovation engineering coordinates customer-facing layouts with storefront structure, HVAC, lighting, power, plumbing, accessibility, and landlord or center requirements.",
    scope: "The review focuses on the tenant layout, merchandise and display loads, storefront changes, stock and support areas, customer circulation, operating hours, and utility constraints.",
    risks: "Existing roof units, shared services, rated separations, slab penetrations, sign or canopy supports, and work in an operating center can introduce scope that is not visible on a test-fit.",
    inputs: "Provide the lease plan, landlord design criteria, proposed merchandising plan, equipment schedule, storefront concept, existing drawings, and center utility information.",
    deliverables: "Engineering deliverables may include support details, MEP plans, lighting and load calculations, plumbing design, energy documentation, and coordinated permit revisions.",
    audience: "Retailers, franchise teams, landlords, architects, and tenant-improvement contractors",
    phrases: ["retail renovation engineering", "retail store remodel engineer", "retail tenant improvement MEP"],
    overlap: "Retail-specific buyer intent without replacing the general tenant-improvement canonical.",
  },
  {
    slug: "medical-office-renovation-engineering",
    title: "Medical Office Renovation Engineering Services | Apex Grid",
    description: "Engineering for medical office renovations, including HVAC, plumbing, electrical, equipment support, accessibility, and healthcare permit coordination.",
    h1: "Medical Office Renovation Engineering",
    kicker: "Outpatient Facility Renovation",
    need: "Medical office renovations add clinical workflows, equipment, ventilation, plumbing, power, accessibility, and infection-control coordination to a conventional tenant-improvement scope.",
    scope: "The engineering review begins with the services provided, room functions, patient and staff flows, equipment data, utility needs, pressure or ventilation criteria, and governing facility requirements.",
    risks: "Imaging or clinical equipment loads, emergency power expectations, medical gas by others, plumbing intensity, rooftop capacity, and occupied healthcare operations can change the design path.",
    inputs: "Provide room data, equipment cut sheets, architectural plans, existing system records, owner standards, infection-control requirements, and the applicable licensing or permit correspondence.",
    deliverables: "The agreed work may include equipment support, HVAC and plumbing design, electrical loads and distribution, calculations, schedules, and discipline-coordinated permit documents.",
    audience: "Medical practices, healthcare owners, architects, equipment planners, and contractors",
    phrases: ["medical office renovation engineer", "clinic remodel MEP engineering", "outpatient renovation engineering"],
    overlap: "Outpatient renovation intent; it does not claim healthcare credentials or replace the general healthcare industry page.",
  },
  {
    slug: "laboratory-renovation-engineering",
    title: "Laboratory Renovation Engineering Services | Apex Grid",
    description: "Engineering for laboratory renovations with defined equipment, ventilation, utilities, structural loads, controls, coordination, and permit requirements.",
    h1: "Laboratory Renovation Engineering",
    kicker: "Technical Facility Renovation",
    need: "Laboratory renovations require engineering around process equipment, exhaust, make-up air, pressure relationships, utilities, electrical demand, controls, and structural support.",
    scope: "The design basis identifies laboratory type, processes, chemicals and quantities as provided by the owner, equipment, heat loads, exhaust devices, utility quality, redundancy, and operational constraints.",
    risks: "Unknown process loads, insufficient shafts, roof capacity, incompatible materials, control sequences, utility outages, and assumptions about hazardous classifications can cause major redesign.",
    inputs: "Provide room and equipment data, process narratives, chemical information prepared by the responsible party, utility matrices, exhaust requirements, existing plans, and owner standards.",
    deliverables: "A defined package may include MEP basis documents, structural support, utility and exhaust design, controls narratives, calculations, coordination drawings, and permit support.",
    audience: "Laboratory owners, research organizations, architects, equipment planners, and contractors",
    phrases: ["laboratory renovation engineering", "lab remodel MEP engineer", "laboratory fit out engineering"],
    overlap: "Laboratory-renovation intent centered on project inputs; no unsupported safety certification or facility credential is claimed.",
  },
  {
    slug: "industrial-facility-renovation-engineering",
    title: "Industrial Facility Renovation Engineering | Apex Grid",
    description: "Multidiscipline engineering for industrial facility renovations, equipment changes, utility upgrades, structural modifications, and permit documentation.",
    h1: "Industrial Facility Renovation Engineering",
    kicker: "Industrial Modernization",
    need: "Industrial renovations coordinate building structure and utilities with production equipment, material flow, maintenance access, environmental controls, and phased operations.",
    scope: "The engineering basis defines the process changes, equipment and loads, utility demands, support and anchorage needs, operating constraints, and interfaces with existing production.",
    risks: "Undocumented modifications, vibration, concentrated loads, limited shutdown windows, obsolete distribution, hazardous materials managed by others, and proprietary equipment criteria can affect feasibility.",
    inputs: "Provide process and equipment layouts, manufacturer data, utility loads, existing one-lines and plans, operating constraints, maintenance clearances, and known facility hazards.",
    deliverables: "The scope may produce capacity checks, equipment supports, structural and MEP designs, utility modifications, calculations, sequencing criteria, and permit drawings.",
    audience: "Manufacturers, industrial owners, plant engineers, equipment vendors, and contractors",
    phrases: ["industrial facility renovation engineering", "manufacturing plant renovation engineer", "industrial building upgrade engineering"],
    overlap: "Renovation-stage industrial intent; process design and owner safety programs remain outside unstated scope.",
  },
  {
    slug: "school-renovation-engineering",
    title: "School Renovation Engineering | Structural & MEP | Apex Grid",
    description: "Engineering for school and education facility renovations, including phased work, system upgrades, accessibility, structural changes, and permit support.",
    h1: "School Renovation Engineering",
    kicker: "Education Facility Renovation",
    need: "School renovation engineering must align building upgrades with classroom use, student circulation, accessibility, existing systems, seasonal work windows, and authority requirements.",
    scope: "The review defines affected buildings and rooms, enrollment or occupancy assumptions supplied by the owner, instructional uses, system deficiencies, phasing, and the intended permit packages.",
    risks: "Occupied campuses, short shutdown periods, legacy systems, hazardous-material coordination by others, incomplete records, and work across multiple building eras can constrain design.",
    inputs: "Provide campus and building plans, room uses, facility standards, prior assessments, equipment records, accessibility priorities, phasing dates, and authority correspondence.",
    deliverables: "Engineering may include condition findings, structural modifications, MEP replacement design, energy documentation, calculations, phased permit packages, and construction support.",
    audience: "School owners, education facility teams, architects, program managers, and contractors",
    phrases: ["school renovation engineering", "education facility remodel engineer", "school MEP renovation"],
    overlap: "Education-facility renovation intent; no public procurement, funding, or local authorization claim is made.",
  },
  {
    slug: "hotel-renovation-engineering",
    title: "Hotel Renovation Engineering | Structural & MEP | Apex Grid",
    description: "Engineering for hotel renovations, guest-room upgrades, amenity changes, HVAC and plumbing modifications, structural work, and phased permits.",
    h1: "Hotel Renovation Engineering",
    kicker: "Hospitality Renovation",
    need: "Hotel renovations combine repeated guest-room work with amenity, back-of-house, vertical distribution, accessibility, structural, and building-system decisions.",
    scope: "The engineering basis identifies room types, fixture and equipment changes, amenity scope, operating phasing, brand or owner criteria, existing risers, and affected common areas.",
    risks: "Stacked plumbing, limited shafts, guest occupancy, noise and outage limits, older fan-coil or domestic-water systems, and hidden variations between floors can drive field verification.",
    inputs: "Provide prototype rooms, floor plans, riser diagrams, equipment schedules, owner standards, accessibility scope, operating constraints, and records of prior renovations.",
    deliverables: "The work may include room-type engineering, riser modifications, HVAC and electrical plans, structural details, calculations, phased permit sheets, and field-condition revisions.",
    audience: "Hotel owners, operators, architects, brand teams, and renovation contractors",
    phrases: ["hotel renovation engineering", "hospitality remodel MEP engineer", "hotel guest room renovation engineer"],
    overlap: "Hospitality-specific renovation intent; brand compliance and operating decisions remain owner responsibilities.",
  },
  {
    slug: "multifamily-renovation-engineering",
    title: "Multifamily Renovation Engineering Services | Apex Grid",
    description: "Engineering for multifamily renovations, unit upgrades, structural changes, MEP systems, accessibility, common areas, and phased permit work.",
    h1: "Multifamily Renovation Engineering",
    kicker: "Residential Facility Renovation",
    need: "Multifamily renovation engineering coordinates repeated unit work with common systems, structural alterations, risers, accessibility, occupied-building phasing, and permit requirements.",
    scope: "The review defines unit types, common-area changes, fixture and appliance loads, envelope or balcony concerns, vertical distribution, occupancy during work, and the desired permit sequence.",
    risks: "Variations between units, stacked wet walls, undocumented repairs, occupied access, rated assemblies, aging services, and concealed deterioration can change the assumed repeatable scope.",
    inputs: "Provide unit matrices, representative plans, risers, prior reports, proposed finishes and equipment, accessibility goals, phasing, and known recurring conditions.",
    deliverables: "Deliverables may include prototype details, structural repairs or modifications, MEP plans, load calculations, common-system upgrades, permit packages, and field clarification.",
    audience: "Multifamily owners, developers, architects, asset managers, and renovation contractors",
    phrases: ["multifamily renovation engineering", "apartment renovation engineer", "multifamily MEP remodel"],
    overlap: "Multifamily renovation intent; it does not replace broad residential or existing-building service pages.",
  },
  {
    slug: "commercial-kitchen-renovation-engineering",
    title: "Commercial Kitchen Renovation Engineering | Apex Grid",
    description: "MEP and structural engineering for commercial kitchen renovations, including exhaust, make-up air, utilities, equipment support, and permits.",
    h1: "Commercial Kitchen Renovation Engineering",
    kicker: "Food-Service Renovation",
    need: "Commercial kitchen renovations depend on coordinated exhaust, make-up air, cooling, electrical, gas, plumbing, grease waste, equipment support, and fire-system interfaces.",
    scope: "The design basis starts with the final equipment schedule, hood and appliance data, menu or cooking processes supplied by the operator, utility availability, sanitation layout, and operating constraints.",
    risks: "Late equipment changes, insufficient gas or electrical service, roof capacity, long duct routes, shared grease systems, replacement air, and landlord criteria commonly affect feasibility.",
    inputs: "Provide the kitchen plan, equipment cut sheets, hood data, utility matrix, existing MEP plans, roof information, landlord criteria, and health or building review comments.",
    deliverables: "The scope may include HVAC, electrical and plumbing plans, load calculations, equipment connections, structural support, roof-penetration details, and permit coordination.",
    audience: "Restaurant owners, food-service operators, architects, kitchen consultants, and contractors",
    phrases: ["commercial kitchen renovation engineer", "restaurant kitchen MEP remodel", "kitchen hood renovation engineering"],
    overlap: "Kitchen-renovation intent focused on existing facilities; specialty fire-suppression and health approvals remain with responsible parties.",
  },
  {
    slug: "building-code-compliance-assessment",
    title: "Building Code Compliance Assessment Services | Apex Grid",
    description: "Scoped engineering assessment of existing building conditions against identified code questions, project changes, and authority requirements.",
    h1: "Building Code Compliance Assessment",
    kicker: "Compliance Review",
    need: "A building code compliance assessment compares defined existing conditions or proposed work with identified code criteria; it is not an unlimited certification that every building element complies.",
    scope: "The engagement names the systems, spaces, code questions, adopted editions, project trigger, and decision to be supported so observations can be tied to a clear review basis.",
    risks: "Code editions, local amendments, prior approvals, grandfathered conditions, change-of-use triggers, inaccessible construction, and authority interpretations can limit broad conclusions.",
    inputs: "Provide the project address, current use, proposed changes, available permits and plans, known citations or concerns, prior reports, and the authority’s written questions.",
    deliverables: "A scoped result may include an issues matrix, observed-condition narrative, code references, priorities, recommended investigation, design criteria, or permit-support documents.",
    audience: "Building owners, buyers, facility managers, architects, and legal or insurance teams",
    phrases: ["building code compliance assessment", "existing building code review engineer", "commercial building compliance evaluation"],
    overlap: "Defined compliance-question intent; not a duplicate of a general condition assessment or a guarantee of total compliance.",
  },
  {
    slug: "ada-building-compliance-assessment",
    title: "ADA Building Compliance Assessment Support | Apex Grid",
    description: "Scoped accessibility assessment support for existing commercial buildings and renovations, coordinated with applicable standards and project requirements.",
    h1: "ADA Building Compliance Assessment Support",
    kicker: "Accessibility Review",
    need: "Accessibility assessment support reviews defined routes, entrances, parking, restrooms, controls, and altered areas against the standards identified for the project.",
    scope: "The scope distinguishes an engineering or design review from a legal opinion and identifies the property areas, proposed alterations, governing standards, owner priorities, and required documentation.",
    risks: "Site slopes, legacy construction, tenant boundaries, path-of-travel triggers, dimensional tolerances, local amendments, and incomplete alteration history can affect conclusions.",
    inputs: "Provide site and floor plans, accessible-route information, survey or measurements, alteration history, known complaints or citations, photographs, and the intended renovation scope.",
    deliverables: "The work may produce an observed-conditions list, measured diagrams, priority matrix, concept corrections, coordinated engineering details, or permit documents within the agreed disciplines.",
    audience: "Property owners, facility managers, architects, developers, and renovation teams",
    phrases: ["ADA building compliance assessment", "commercial accessibility assessment", "ADA renovation engineering review"],
    overlap: "Accessibility-focused project assessment; no legal certification or universal ADA compliance claim is made.",
  },
  {
    slug: "existing-building-code-gap-assessment",
    title: "Existing Building Code Gap Assessment Services | Apex Grid",
    description: "Engineering review of gaps between known existing conditions and code criteria triggered by a renovation, occupancy change, repair, or planned investment.",
    h1: "Existing Building Code Gap Assessment",
    kicker: "Existing Building Planning",
    need: "A code gap assessment identifies where known existing conditions may differ from criteria triggered by planned work, helping teams budget investigation and design before permit production.",
    scope: "The review centers on a proposed renovation, addition, occupancy change, repair, or capital plan rather than attempting to certify an entire property without a defined trigger.",
    risks: "Incomplete records, multiple construction eras, past unpermitted work, local amendments, existing-building-code options, and authority discretion can change which gaps matter.",
    inputs: "Provide existing and proposed plans, permit history, prior assessments, known deficiencies, adopted code information if available, and the project decisions the assessment must inform.",
    deliverables: "The report may organize apparent gaps by discipline, evidence, priority, project trigger, required verification, and likely next step without promising authority agreement.",
    audience: "Owners, developers, asset managers, architects, and capital-planning teams",
    phrases: ["existing building code gap assessment", "renovation code gap analysis", "building code deficiency review"],
    overlap: "Project-trigger gap analysis distinct from general condition and full compliance assessments.",
  },
  {
    slug: "facility-capital-needs-assessment",
    title: "Facility Capital Needs Assessment Services | Apex Grid",
    description: "Engineering support for facility capital needs assessments, system condition, repair priorities, replacement planning, and follow-up design decisions.",
    h1: "Facility Capital Needs Assessment",
    kicker: "Capital Planning",
    need: "A facility capital needs assessment organizes observed building and system concerns into repair, replacement, investigation, and design priorities for planning decisions.",
    scope: "The assessment defines the property areas and systems reviewed, planning horizon, document basis, observation level, owner concerns, and whether cost opinions are included or provided by others.",
    risks: "Concealed conditions, deferred maintenance, obsolete equipment, incomplete records, tenant responsibility boundaries, and uncertain remaining life make transparent assumptions essential.",
    inputs: "Provide asset lists, maintenance records, prior assessments, drawings, repair history, known failures, planned use changes, budget categories, and access to representative spaces.",
    deliverables: "A result may include a system inventory, condition observations, priority categories, recommended studies, renewal sequence, and design-scope recommendations; it is not a warranty.",
    audience: "Facility owners, asset managers, investors, lenders, and property-management teams",
    phrases: ["facility capital needs assessment", "building capital planning engineer", "facility systems assessment"],
    overlap: "Capital-planning intent distinct from transaction diligence and a single-condition engineering assessment.",
  },
  {
    slug: "roof-structure-condition-assessment",
    title: "Roof Structure Condition Assessment Services | Apex Grid",
    description: "Structural assessment of existing roof framing for observed distress, deterioration, modifications, added loads, repair planning, and project decisions.",
    h1: "Roof Structure Condition Assessment",
    kicker: "Structural Condition Review",
    need: "A roof structure condition assessment documents visible framing conditions and evaluates defined concerns such as distress, deterioration, prior modifications, or planned load changes.",
    scope: "The review identifies roof framing type, accessible members and connections, known leaks or damage, prior repairs, loading concerns, and the decision the owner or project team needs.",
    risks: "Concealed framing, roofing layers, inaccessible plenums, moisture damage, undocumented openings, ponding, corrosion, and unknown equipment weights can require further investigation.",
    inputs: "Provide structural and roofing plans, leak and repair history, photographs, roof-access rules, equipment records, proposed loads, and any contractor or inspection findings.",
    deliverables: "The scope may produce a condition report, load-capacity analysis, monitoring recommendation, repair concept, reinforcement design, or permit drawings for a defined condition.",
    audience: "Building owners, roof consultants, facility managers, contractors, and insurers",
    phrases: ["roof structure condition assessment", "commercial roof framing inspection engineer", "roof structural evaluation"],
    overlap: "Condition-focused roof intent distinct from design for a specific new rooftop modification.",
  },
  {
    slug: "parking-structure-condition-assessment",
    title: "Parking Structure Condition Assessment | Apex Grid",
    description: "Engineering assessment of parking structure conditions, including visible concrete, steel, drainage, movement, deterioration, and repair-planning needs.",
    h1: "Parking Structure Condition Assessment",
    kicker: "Parking Facility Assessment",
    need: "A parking structure condition assessment records visible structural and serviceability concerns and defines where testing, monitoring, repair design, or specialty investigation may be warranted.",
    scope: "The assessment identifies deck and framing systems, observed cracking or spalling, corrosion indicators, joints, drainage, prior repairs, traffic constraints, and the owner’s planning question.",
    risks: "Chloride exposure, concealed reinforcement, active leaks, coating failures, movement joints, impact damage, and restricted access can require testing or staged investigation.",
    inputs: "Provide original and repair drawings, maintenance history, prior testing, leak maps, photographs, known closures, traffic and access plans, and the intended planning horizon.",
    deliverables: "The result may include mapped observations, condition categories, recommended testing, immediate-action notices where observed, repair priorities, and a basis for later repair design.",
    audience: "Parking owners, facility managers, property managers, contractors, and capital planners",
    phrases: ["parking structure condition assessment", "parking garage structural assessment", "parking deck engineering inspection"],
    overlap: "Parking-structure assessment intent; detailed testing and repair design are separately scoped.",
  },
  {
    slug: "commercial-building-permit-set-engineering",
    title: "Commercial Building Permit Set Engineering | Apex Grid",
    description: "Coordinated structural and MEP engineering for defined commercial building permit sets, with calculations, plans, schedules, and review support.",
    h1: "Commercial Building Permit Set Engineering",
    kicker: "Permit Documents",
    need: "Commercial building permit-set engineering turns an approved project basis into coordinated discipline drawings, calculations, schedules, and details for authority review.",
    scope: "The permit scope identifies the project type, architectural basis, engineering disciplines, jurisdiction, design criteria, owner requirements, delegated items, and review milestones.",
    risks: "Incomplete architectural backgrounds, unresolved equipment, changing layouts, missing survey or geotechnical data, and unclear discipline boundaries can create permit delays and redesign.",
    inputs: "Provide current architectural and site plans, project address, code summary, equipment selections, owner criteria, existing records, survey or geotechnical information, and submission requirements.",
    deliverables: "The package may include structural, mechanical, electrical, plumbing, or civil sheets and calculations specifically listed in the proposal, plus defined coordination and comment-response support.",
    audience: "Commercial owners, developers, architects, contractors, and permit coordinators",
    phrases: ["commercial building permit set engineer", "engineering permit drawing package", "commercial permit plans engineering"],
    overlap: "Buyer intent for a coordinated permit set; discipline pages remain canonical for discipline-specific design searches.",
  },
  {
    slug: "renovation-permit-engineering",
    title: "Commercial Renovation Permit Engineering | Apex Grid",
    description: "Engineering for commercial renovation permits, including existing-condition review, structural and MEP modifications, calculations, and correction support.",
    h1: "Renovation Permit Engineering",
    kicker: "Alteration Permit Support",
    need: "Renovation permit engineering documents how proposed alterations interact with existing structure, systems, occupancy, accessibility, energy, and authority requirements.",
    scope: "The permit basis defines existing and proposed conditions, demolition, retained systems, affected disciplines, project phasing, occupancy during work, and the authority’s submission expectations.",
    risks: "Unknown framing, undocumented past work, outdated system drawings, late equipment changes, concealed utilities, and differences between field conditions and plans can require revision.",
    inputs: "Provide demolition and proposed plans, existing records, field photographs, equipment schedules, prior permits, code or plan-review correspondence, and access for verification.",
    deliverables: "The agreed package may include alteration plans, structural details, MEP modifications, calculations, energy documents, revision narratives, and responses to engineering comments.",
    audience: "Building owners, tenants, architects, renovation contractors, and permit coordinators",
    phrases: ["renovation permit engineering", "commercial remodel permit engineer", "alteration permit drawings engineer"],
    overlap: "Permit-stage renovation intent; general renovation pages cover earlier project planning.",
  },
  {
    slug: "change-of-use-permit-engineering",
    title: "Commercial Change of Use Permit Engineering | Apex Grid",
    description: "Engineering support for change-of-use permits, including occupancy loads, structural capacity, MEP systems, accessibility, and coordinated documents.",
    h1: "Change of Use Permit Engineering",
    kicker: "Occupancy Change Permits",
    need: "Change-of-use permit engineering compares the existing building and systems with the demands and code triggers associated with the proposed use.",
    scope: "The review identifies current and proposed occupancy classifications, occupant and live loads, ventilation, power, plumbing fixtures, accessibility, egress interfaces, and alteration scope.",
    risks: "Higher floor loads, insufficient outdoor air, service capacity, restroom counts, seismic triggers, fire-protection coordination, and incomplete permit history can affect feasibility.",
    inputs: "Provide existing and proposed plans, use narratives, occupant assumptions, equipment data, prior permits, structural records, MEP information, and authority correspondence.",
    deliverables: "Engineering may include capacity assessments, design criteria, structural and MEP modifications, calculations, coordinated permit sheets, and responses to review comments.",
    audience: "Owners, developers, tenants, architects, contractors, and permit consultants",
    phrases: ["change of use permit engineer", "occupancy change engineering plans", "building use conversion permit engineering"],
    overlap: "Permit-specific occupancy-change intent; adaptive reuse remains the broader project-type canonical.",
  },
  {
    slug: "equipment-installation-permit-engineering",
    title: "Equipment Installation Permit Engineering | Apex Grid",
    description: "Structural and MEP engineering for commercial equipment installation permits, including capacity, support, anchorage, utilities, and drawings.",
    h1: "Equipment Installation Permit Engineering",
    kicker: "Equipment Permit Support",
    need: "Equipment installation permit engineering coordinates manufacturer requirements with existing structural capacity, anchorage, clearances, electrical, mechanical, plumbing, and authority needs.",
    scope: "The engineering basis identifies the exact equipment, model, weight, operating loads, support location, utility demands, environmental needs, maintenance access, and installation arrangement.",
    risks: "Pre-purchase assumptions, incomplete submittals, dynamic or seismic loads, roof or floor capacity, utility limitations, penetrations, and substitutions can invalidate early design.",
    inputs: "Provide final manufacturer data, shop drawings, proposed location, existing plans, photographs, utility information, contractor routing, and the authority’s permit requirements.",
    deliverables: "The package may include capacity checks, pads or supports, anchorage, connection loads, MEP plans, one-lines, calculations, details, and permit-comment support.",
    audience: "Facility owners, equipment vendors, contractors, manufacturers, and permit coordinators",
    phrases: ["equipment installation permit engineer", "machinery permit engineering", "commercial equipment anchorage permit"],
    overlap: "Permit-deliverable intent distinct from general equipment replacement planning.",
  },
  {
    slug: "building-envelope-repair-engineering",
    title: "Building Envelope Repair Engineering Services | Apex Grid",
    description: "Engineering support for defined building envelope repairs involving structural substrates, openings, supports, drainage interfaces, and permit documents.",
    h1: "Building Envelope Repair Engineering",
    kicker: "Exterior Repair Design",
    need: "Building envelope repair engineering addresses structural and building-system interfaces behind defined façade, wall, roof-edge, opening, or water-intrusion repairs.",
    scope: "The engagement identifies the observed distress, affected assemblies, structural substrate, drainage path, prior repairs, investigation by envelope specialists if applicable, and the desired construction decision.",
    risks: "Concealed deterioration, water migration, corrosion, incompatible materials, access limits, hazardous materials handled by others, and uncertain original details can expand investigation.",
    inputs: "Provide photographs, leak or distress history, original and repair drawings, prior consultant reports, testing results, access information, and proposed repair materials or concepts.",
    deliverables: "Engineering may include substrate assessment, support and attachment design, repair details, calculations, coordination with an envelope consultant, and permit drawings for the defined scope.",
    audience: "Building owners, architects, envelope consultants, property managers, and repair contractors",
    phrases: ["building envelope repair engineer", "facade repair structural engineering", "exterior wall repair engineering"],
    overlap: "Structural and engineering repair intent; it does not claim comprehensive envelope consulting or testing unless scoped.",
  },
  {
    slug: "facility-system-modernization-engineering",
    title: "Facility System Modernization Engineering | Apex Grid",
    description: "Engineering for coordinated modernization of aging facility HVAC, electrical, plumbing, controls, structural supports, infrastructure, and related permits.",
    h1: "Facility System Modernization Engineering",
    kicker: "Building Systems Modernization",
    need: "Facility system modernization engineering turns replacement goals for aging HVAC, electrical, plumbing, controls, and related supports into a coordinated implementation basis.",
    scope: "The planning scope identifies systems to retain or replace, capacity needs, owner performance criteria, redundancy, phasing, maintenance access, energy requirements, and future flexibility.",
    risks: "Obsolete distribution, limited service capacity, interdependent systems, occupied operations, long-lead equipment, controls integration, and unknown shafts or supports can constrain options.",
    inputs: "Provide asset inventories, condition reports, utility data, controls information, trend or demand records, existing drawings, owner standards, and planned operational changes.",
    deliverables: "Work may include options analysis, basis-of-design documents, load studies, equipment and distribution design, structural supports, phasing criteria, and permit packages.",
    audience: "Facility owners, capital-program teams, property managers, architects, and contractors",
    phrases: ["facility system modernization engineering", "building systems upgrade engineer", "facility infrastructure modernization"],
    overlap: "Coordinated modernization intent distinct from a single equipment replacement or energy-only upgrade.",
  },
  {
    slug: "occupied-building-renovation-engineering",
    title: "Occupied Building Renovation Engineering | Apex Grid",
    description: "Engineering for renovations in occupied commercial buildings, with phasing, temporary conditions, outages, safe access planning, and permit coordination.",
    h1: "Occupied Building Renovation Engineering",
    kicker: "Renovation Phasing",
    need: "Occupied building renovation engineering integrates permanent design with access, shutdown, temporary-condition, sequencing, and communication constraints established by the project team.",
    scope: "The design basis identifies occupied areas, critical operations, allowable outages, swing spaces, work zones, temporary services, egress constraints, and the contractor’s proposed phasing responsibilities.",
    risks: "Hidden conditions, unplanned outages, shared systems, noise and vibration, temporary loads, changing egress, infection or dust controls by others, and limited observation windows affect execution.",
    inputs: "Provide occupancy and phasing plans, shutdown restrictions, existing system diagrams, critical-load lists, access rules, temporary-service concepts, and current construction sequencing.",
    deliverables: "Engineering may include phased drawings, temporary-condition criteria, system cutover plans, structural sequencing requirements, permit packages, and responses to field conditions.",
    audience: "Facility owners, occupants, architects, construction managers, and renovation contractors",
    phrases: ["occupied building renovation engineering", "phased occupied renovation engineer", "renovation engineering during operations"],
    overlap: "Occupied-facility execution intent; contractor means, methods, site safety, and final sequencing remain contractor responsibilities.",
  },
  {
    slug: "phased-renovation-engineering",
    title: "Phased Renovation Engineering | Permit Packages | Apex Grid",
    description: "Engineering for phased commercial renovations, coordinated permit boundaries, temporary conditions, system continuity, and later construction stages.",
    h1: "Phased Renovation Engineering",
    kicker: "Multi-Phase Project Delivery",
    need: "Phased renovation engineering divides a larger alteration into coordinated design and permit packages while preserving system continuity and documenting interfaces between stages.",
    scope: "The phase plan identifies what is built, demolished, occupied, energized, supported, and permitted at each stage, along with dependencies and decisions required before later work.",
    risks: "Unclear phase boundaries, temporary dead ends, undersized interim services, duplicated work, authority sequencing requirements, and changes to later design can undermine early packages.",
    inputs: "Provide the overall concept, phase diagrams, occupancy and outage needs, procurement constraints, existing plans, interim loads, construction sequence, and permit strategy.",
    deliverables: "Engineering may include phase-specific drawings and calculations, temporary-condition criteria, interface matrices, early equipment packages, coordinated revisions, and permit responses.",
    audience: "Owners, developers, program managers, architects, and construction managers",
    phrases: ["phased renovation engineering", "multi phase renovation permit plans", "renovation phasing engineer"],
    overlap: "Permit and coordination intent for multiple stages; general renovation remains the single-phase planning canonical.",
  },
  {
    slug: "pre-design-engineering-assessment",
    title: "Commercial Pre-Design Engineering Assessment | Apex Grid",
    description: "Pre-design engineering assessment for commercial projects, clarifying existing conditions, capacity, constraints, risks, and required investigations.",
    h1: "Pre-Design Engineering Assessment",
    kicker: "Project Feasibility",
    need: "A pre-design engineering assessment helps a project team understand known structural, MEP, civil, and existing-condition constraints before committing to a design direction.",
    scope: "The engagement focuses on the decisions needed for programming, acquisition, budgeting, test fits, equipment selection, or consultant scoping rather than producing final design documents.",
    risks: "Incomplete records, concealed conditions, unverified utility capacity, unknown soils, evolving program requirements, and limited access can make early conclusions conditional.",
    inputs: "Provide the project concept, address, site and building plans, proposed loads and uses, owner criteria, utility information, prior reports, photographs, and key feasibility questions.",
    deliverables: "A result may include findings, capacity observations, constraints, assumptions, options, recommended investigations, discipline scopes, and a roadmap for later design and permitting.",
    audience: "Owners, developers, architects, investors, contractors, and project planners",
    phrases: ["pre design engineering assessment", "engineering feasibility assessment", "commercial project engineering due diligence"],
    overlap: "Early project-feasibility intent distinct from transaction diligence, final design, and broad condition assessment.",
  },
];

export const NATIONAL_FACILITY_INTENT_PAGES = NATIONAL_FACILITY_INTENT_SEEDS.map(makeNationalIntentPage);
