import type { Phase7AeoSeed } from "./phase7-types";

export const PHASE7_TIMELINE_PAGES: Phase7AeoSeed[] = [
  {
    slug: "when-should-engineering-start-before-permit",
    title: "When Should Engineering Start Before a Permit Application? | Apex Grid",
    description: "Engineering should start once the project scope and design basis are defined, with enough lead time for coordination before the permit application is assembled.",
    h1: "When should engineering start before a permit application?",
    answer: "Engineering should start after the owner and design team have a usable project scope, site or existing-condition information, and a clear permit objective, but before the drawings are treated as final. Early involvement lets the responsible engineer identify structural, MEP, civil, energy, utility, and code dependencies while changes are still practical. The right start point varies with project type, design maturity, survey or geotechnical needs, equipment selections, and the AHJ’s checklist. Engineering cannot replace the architect’s scope, contractor means and methods, utility decisions, or the AHJ’s authority to determine submission requirements.",
    topic: "Engineering start point before permit",
    cluster: "Project timelines",
    serviceHref: "/services/structural",
  },
  {
    slug: "what-happens-at-an-engineering-project-kickoff",
    title: "What Happens at an Engineering Project Kickoff? | Apex Grid",
    description: "An engineering kickoff aligns scope, project records, responsibilities, design inputs, review gates, and jurisdictional questions before production begins.",
    h1: "What happens at an engineering project kickoff?",
    answer: "An engineering project kickoff turns a general request into a reviewable scope. The team confirms the address and jurisdiction, project phase, disciplines, existing-condition evidence, architectural background, equipment or utility information, required deliverables, communication contacts, review gates, and known AHJ questions. It also identifies assumptions, missing records, field-verification needs, and who owns decisions that are not engineering decisions. The kickoff does not constitute an approval or transfer the architect’s, contractor’s, owner’s, utility’s, or authority having jurisdiction’s responsibilities. Its value is making dependencies visible before design production and coordination begin.",
    topic: "Engineering project kickoff workflow",
    cluster: "Project timelines",
    serviceHref: "/services/mep",
  },
  {
    slug: "how-long-does-an-engineering-proposal-take",
    title: "How Long Does an Engineering Proposal Take? | Apex Grid",
    description: "An engineering proposal schedule depends on the clarity of the requested scope, available project records, discipline needs, and questions that require professional review.",
    h1: "How long does an engineering proposal take?",
    answer: "There is no universal proposal turnaround because a responsible proposal requires more than matching a project to a menu price. The engineer may need to understand the requested deliverables, building or site conditions, disciplines, jurisdiction, existing documents, field evidence, coordination expectations, and target phase before defining assumptions and exclusions. A clear scope with current plans and comments can support a more efficient proposal review; incomplete or changing information may require questions or a discovery step. A proposal is a commercial scope and planning document, not a design, seal, permit decision, or promise that an AHJ will approve the work.",
    topic: "Engineering proposal preparation",
    cluster: "Project timelines",
    serviceHref: "/services/mep",
  },
  {
    slug: "how-long-does-scope-definition-take-before-engineering",
    title: "How Long Does Scope Definition Take Before Engineering? | Apex Grid",
    description: "Scope definition can be quick for a well-documented request or require investigation when project boundaries, existing conditions, and deliverables are unclear.",
    h1: "How long does scope definition take before engineering?",
    answer: "Scope definition takes as long as needed to state what is changing, what must be documented, and where professional responsibility begins and ends. The effort depends on whether the project has current architectural plans, reliable existing-condition records, a defined occupancy or use, selected equipment, site information, prior permit documents, and an identified AHJ. A focused modification may be scoped from a concise brief, while an existing or multi-discipline project may need records review and a site discussion before the deliverables are known. Scope definition is not design production and cannot determine an AHJ’s final requirements.",
    topic: "Pre-design scope definition",
    cluster: "Project timelines",
    serviceHref: "/services/mep",
  },
  {
    slug: "when-should-architecture-coordinate-with-engineering",
    title: "When Should Architecture Coordinate With Engineering? | Apex Grid",
    description: "Architectural and engineering coordination should begin while the layout and systems are developing, not only after drawings appear final.",
    h1: "When should architectural design be coordinated with engineering?",
    answer: "Architectural design should be coordinated with engineering as soon as the layout establishes decisions that affect structure, shafts, equipment, utilities, accessibility, energy performance, or life-safety documentation. Early coordination allows the architect and engineers to test floor-to-floor space, penetrations, equipment locations, service capacity, drainage, and structural clearances before those decisions harden. The appropriate cadence depends on project complexity, design phase, disciplines, and the quality of the background information. The architect controls architectural design, the engineers control their defined professional scopes, and the AHJ controls its interpretation and review; coordination supports those roles but does not guarantee approval.",
    topic: "Architectural and engineering coordination",
    cluster: "Project timelines",
    serviceHref: "/services/architecture",
  },
  {
    slug: "should-structural-or-mep-engineering-start-first",
    title: "Should Structural or MEP Engineering Start First? | Apex Grid",
    description: "Structural and MEP work usually develop together; the best sequence depends on building geometry, equipment, penetrations, loads, and project dependencies.",
    h1: "Should structural or MEP engineering start first?",
    answer: "Neither discipline always goes first. Structural and MEP engineering should be sequenced around the decisions that constrain the other system: building geometry and load paths inform structure, while equipment, shafts, routes, clearances, and service loads inform MEP design. A project may begin with architectural and structural framing concepts, an equipment-driven MEP layout, or parallel studies that are reconciled through documented coordination reviews. The responsible structural and MEP professionals decide what can proceed from the available information. The owner, architect, contractor, utilities, and AHJ retain their own decisions, and a coordinated sequence is not an approval promise.",
    topic: "Structural and MEP sequencing",
    cluster: "Project timelines",
    serviceHref: "/services/mep",
  },
  {
    slug: "when-should-geotechnical-information-enter-structural-design",
    title: "When Should Geotechnical Information Enter Structural Design? | Apex Grid",
    description: "Geotechnical information should inform foundation and site decisions before those portions of structural design are finalized.",
    h1: "When should geotechnical information enter structural design?",
    answer: "Geotechnical information should enter structural design before foundation systems, bearing assumptions, settlement criteria, lateral soil conditions, retaining elements, or site-specific earthwork recommendations are finalized. The structural engineer uses the report’s stated parameters and limitations, while the geotechnical professional defines the investigation and interprets soil conditions within that discipline. The point at which information is needed depends on building loads, foundation concept, site history, grading, groundwater, and the requirements of the project authority. A geotechnical report does not dictate the entire structural design, and an engineer must not fill unknown conditions with unsupported assumptions.",
    topic: "Geotechnical input sequencing",
    cluster: "Project timelines",
    serviceHref: "/services/structural",
  },
  {
    slug: "when-should-a-site-survey-be-complete-for-civil-design",
    title: "When Should a Site Survey Be Complete for Civil Design? | Apex Grid",
    description: "A current survey should be available before civil design relies on property, elevation, boundary, utility, or existing-improvement information.",
    h1: "When should a site survey be complete for civil design?",
    answer: "A site survey should be complete before civil design relies on its boundary, topographic, elevation, right-of-way, utility, or existing-improvement information. Civil engineers use the survey to establish a defensible base for grading, drainage, access, paving, utility routing, and site constraints; the required contents depend on the project and the surveyor’s scope. An older survey may be inadequate when conditions, ownership, utilities, or proposed work have changed. The surveyor is responsible for the surveyed information, the civil engineer interprets it for the design scope, and the AHJ or utility may require additional evidence.",
    topic: "Survey timing for civil design",
    cluster: "Project timelines",
    serviceHref: "/services/civil",
  },
  {
    slug: "how-long-does-multidiscipline-design-coordination-take",
    title: "How Long Does Multidiscipline Design Coordination Take? | Apex Grid",
    description: "Multidiscipline coordination time depends on the number of interfaces, design maturity, building complexity, and unresolved decisions.",
    h1: "How long does multidiscipline design coordination take?",
    answer: "Multidiscipline design coordination has no responsible universal duration. It includes exchanging current backgrounds, identifying clashes and interface decisions, resolving ownership, updating affected drawings or calculations, and checking that the revision remains consistent across disciplines. The effort depends on building geometry, structural penetrations, equipment and utility requirements, site constraints, design maturity, document quality, and how many decisions remain open. Coordination is a professional design activity, not merely a file comparison, and it may expose work that needs redesign. The team can coordinate its documents, but the owner, architect, contractor, utilities, and AHJ control decisions assigned to them.",
    topic: "Multidiscipline design coordination",
    cluster: "Project timelines",
    serviceHref: "/services/mep",
  },
  {
    slug: "what-is-the-sequence-for-permit-drawing-production",
    title: "What Is the Sequence for Permit Drawing Production? | Apex Grid",
    description: "Permit drawing production moves from scope and design inputs through discipline development, calculations, coordination, quality review, and submission assembly.",
    h1: "What is the sequence for permit drawing production?",
    answer: "Permit drawing production generally begins with the defined scope, current backgrounds, site and existing-condition evidence, adopted-code questions, and required deliverables. Each responsible discipline then develops drawings and calculations, coordinates interfaces and equipment, documents assumptions or alternatives, completes internal review, incorporates authorized revisions, and assembles the files and forms requested by the AHJ. The actual sequence may change when a survey, geotechnical report, utility response, owner decision, or specialist input controls progress. Engineers prepare and take responsibility for eligible engineering documents; the architect, contractor, owner, and AHJ retain their separate roles, and a complete set is not a guarantee of approval.",
    topic: "Permit drawing production sequence",
    cluster: "Project timelines",
    serviceHref: "/services/structural",
  },
  {
    slug: "what-happens-before-permit-submission",
    title: "What Happens Before Permit Submission? | Apex Grid",
    description: "Before submission, the team confirms scope, drawings, calculations, forms, seals, file rules, coordination, and the AHJ’s current intake requirements.",
    h1: "What happens before permit submission?",
    answer: "Before permit submission, the applicant and design team should confirm the project scope, applicable authority, current checklist, required disciplines, drawing and calculation consistency, forms, signatures or seals, file naming and upload rules, and any supporting survey, geotechnical, energy, utility, or product information. A final internal review should track assumptions and unresolved questions rather than quietly treating them as settled. The applicant controls the submission and fees, the responsible professionals control their defined documents, and the AHJ controls completeness and review. These checks reduce avoidable omissions but cannot guarantee acceptance, a particular review path, or approval.",
    topic: "Pre-submission permit workflow",
    cluster: "Project timelines",
    serviceHref: "/services/assessments",
  },
  {
    slug: "when-should-agency-coordination-begin",
    title: "When Should Agency Coordination Begin on an Engineering Project? | Apex Grid",
    description: "Agency coordination should begin when an outside requirement can affect scope, design inputs, site constraints, utilities, or permit sequencing.",
    h1: "When should agency coordination begin on an engineering project?",
    answer: "Agency coordination should begin as soon as a utility, planning office, fire authority, environmental agency, transportation department, health authority, or other reviewing body may affect the project’s design or submission path. Early coordination can identify application prerequisites, service information, access constraints, review interfaces, and questions that the engineering set cannot answer alone. The right point depends on the project type, site, jurisdiction, agency procedures, and whether the work changes an existing service or use. Engineers can prepare technical information and coordinate within their scope, but the owner or applicant remains responsible for agency applications and the agency retains decision authority.",
    topic: "Agency coordination timing",
    cluster: "Project timelines",
    serviceHref: "/services/civil",
  },
  {
    slug: "what-is-a-phased-permit-workflow",
    title: "What Is a Phased Permit Workflow? | Apex Grid",
    description: "A phased permit workflow separates an approved scope into coordinated submissions when the AHJ allows that approach and the project team can define boundaries.",
    h1: "What is a phased permit workflow?",
    answer: "A phased permit workflow divides a project’s permitting into defined packages or stages, such as site work, foundations, shell, interiors, or systems, only when the AHJ permits that approach and the interfaces are clearly documented. Each phase needs an appropriate scope, supporting calculations, discipline coordination, forms, and limits so that later work does not undermine an earlier approval. Phasing can reflect procurement or design readiness, but it does not bypass code requirements, agency review, inspections, or professional responsibility. The applicant must confirm whether phasing is available, what each package must contain, and how revisions or dependencies will be handled.",
    topic: "Phased permit workflow",
    cluster: "Project timelines",
    serviceHref: "/services/structural",
  },
  {
    slug: "when-should-construction-support-be-scheduled",
    title: "When Should Construction Engineering Support Be Scheduled? | Apex Grid",
    description: "Construction engineering support should be planned before work begins, with a defined process for RFIs, submittals, field conditions, observations, and revisions.",
    h1: "When should construction engineering support be scheduled?",
    answer: "Construction engineering support should be discussed during design and scheduled before construction starts, even when the exact amount of support is not yet known. The plan should identify the engineer’s scope, expected communication channel, document-control method, RFI and submittal process, field-observation needs, response authority, and triggers for a drawing revision or site visit. Support needs vary with project complexity, contractor experience, concealed conditions, procurement substitutions, inspection requirements, and the contract. The engineer can address design questions within responsible charge; the contractor controls means and methods, the owner controls project decisions, and the AHJ controls inspections and approvals.",
    topic: "Construction support scheduling",
    cluster: "Project timelines",
    serviceHref: "/services/assessments",
  },
  {
    slug: "when-should-a-contractor-review-engineering-documents",
    title: "When Should a Contractor Review Engineering Documents? | Apex Grid",
    description: "Contractor review should begin while the documents can still inform constructability, procurement, sequencing, access, and field coordination before work is installed.",
    h1: "When should a contractor review engineering documents?",
    answer: "A contractor should review engineering documents as soon as the project team has a sufficiently developed set to evaluate constructability, procurement, access, sequencing, temporary conditions, and coordination interfaces, and again before affected work is installed. Early review can surface conflicts or unavailable materials while the responsible design professional can still evaluate a proposed change. The contractor does not redesign or reinterpret sealed documents, and an engineer’s review does not transfer means-and-methods or safety responsibility. The owner, architect, engineers, contractor, and AHJ should use the contract and approved process to define comments, substitutions, RFIs, and revisions.",
    topic: "Contractor review timing",
    cluster: "Project timelines",
    serviceHref: "/services/structural",
  },
  {
    slug: "when-should-procurement-begin-relative-to-engineering",
    title: "When Should Procurement Begin Relative to Engineering? | Apex Grid",
    description: "Procurement should align with design maturity and approved decisions, while long-lead selections are coordinated early enough to inform engineering without bypassing review.",
    h1: "When should procurement begin relative to engineering?",
    answer: "Procurement should begin when the relevant design decisions, performance requirements, interfaces, and approval path are sufficiently defined, while long-lead equipment and materials are identified early enough for the engineers to evaluate their loads, clearances, connections, controls, utilities, and code implications. Releasing an item before those checks can create substitutions, redesign, or permit conflicts; waiting too long can affect construction readiness. The right sequence depends on project phase, owner-furnished equipment, vendor data, contract terms, and AHJ requirements. The contractor and owner manage purchasing, while the responsible engineer evaluates design compatibility rather than promising product approval.",
    topic: "Procurement and engineering sequencing",
    cluster: "Project timelines",
    serviceHref: "/services/mep",
  },
  {
    slug: "how-long-does-change-order-engineering-review-take",
    title: "How Long Does Change-Order Engineering Review Take? | Apex Grid",
    description: "Change-order engineering review depends on the proposed change, available evidence, affected disciplines, construction status, and required approval path.",
    h1: "How long does change-order engineering review take?",
    answer: "Change-order engineering review takes as long as the responsible professional needs to understand the proposed change, verify its design basis, check affected loads or systems, coordinate other disciplines, and document a safe and authorized response. A straightforward clarification with complete information differs from a change that affects foundations, structural capacity, equipment, utilities, life safety, or work already installed. The review may require photographs, measurements, product data, revised calculations, a site observation, or AHJ involvement. The engineer evaluates technical responsibility within the defined scope; the owner and contractor decide commercial changes, and the AHJ decides whether a revision or resubmittal is required.",
    topic: "Change-order engineering review",
    cluster: "Project timelines",
    serviceHref: "/services/structural",
  },
  {
    slug: "how-long-does-engineering-commissioning-documentation-take",
    title: "How Long Does Engineering Commissioning Documentation Take? | Apex Grid",
    description: "Commissioning documentation time depends on system scope, available records, testing responsibilities, equipment readiness, and the required closeout format.",
    h1: "How long does engineering commissioning documentation take?",
    answer: "Commissioning documentation has no universal production schedule because it records what systems were designed to do, how they were tested, what results were observed, and which issues remain open. The work may include reviewing design intent, equipment data, controls sequences, test reports, start-up records, balancing information, training records, and corrective actions. Timing depends on system complexity, equipment availability, contractor and commissioning-agent responsibilities, access to reliable records, and the owner’s closeout requirements. An engineer can document and evaluate defined technical information, but cannot certify unobserved performance or replace the AHJ’s inspections, the contractor’s testing, or the owner’s acceptance process.",
    topic: "Engineering commissioning documentation",
    cluster: "Project timelines",
    serviceHref: "/services/mep",
  },
];