import type { Phase7AeoSeed } from "./phase7-types";

export const PHASE7_TECHNICAL_PAGES: Phase7AeoSeed[] = [
  {
    slug: "what-is-structural-connection-design",
    title: "What Is Structural Connection Design? | Apex Grid",
    description: "Structural connection design explains how members, anchors, fasteners, welds, and supporting materials transfer forces through a building.",
    h1: "What is structural connection design?",
    answer: "Structural connection design determines how beams, columns, braces, walls, foundations, and manufactured components are joined so forces can travel safely between them. The engineer considers the connected materials, geometry, installation tolerances, gravity and lateral actions, corrosion exposure, access, and the strength of the supporting elements. Existing construction may require field measurements or investigation rather than an assumed typical detail. A responsible structural engineer defines the connection scope and documents eligible work; the contractor controls means and methods, and the AHJ determines what must be submitted and accepted.",
    topic: "Structural connection design",
    cluster: "Technical explainers",
    serviceHref: "/services/structural",
  },
  {
    slug: "underpinning-engineering-explained",
    title: "What Is Underpinning Engineering? | Apex Grid",
    description: "Underpinning engineering evaluates how an existing foundation can be supported, strengthened, or transferred when site or building conditions change.",
    h1: "What is underpinning engineering?",
    answer: "Underpinning engineering develops a controlled way to support an existing foundation when settlement, excavation, an addition, changed loads, or adjacent construction affects the original support conditions. The engineer evaluates the existing foundation, soil and groundwater information, proposed excavation, sequence, access, temporary support, neighboring structures, and how loads will be transferred during and after the work. Underpinning is not a generic repair detail: the responsible engineer selects a feasible scheme for verified conditions and coordinates it with geotechnical and construction professionals. The AHJ decides permit and inspection requirements, while the contractor is responsible for safe execution.",
    topic: "Underpinning engineering",
    cluster: "Technical explainers",
    serviceHref: "/services/assessments",
  },
  {
    slug: "construction-joints-vs-expansion-joints",
    title: "Construction Joints vs. Expansion Joints Explained | Apex Grid",
    description: "Construction and expansion joints serve different movement and placement purposes, so the design intent must be coordinated with materials and sequencing.",
    h1: "What is the difference between a construction joint and an expansion joint?",
    answer: "A construction joint separates portions of work placed at different times and must preserve the intended transfer of forces, durability, and water control. An expansion or movement joint is intentionally detailed to accommodate expected movement between building portions, which can come from temperature, shrinkage, settlement, seismic action, or dissimilar construction. The correct joint depends on the structural system, materials, geometry, exposure, finishes, waterproofing, fire protection, and construction sequence. A project engineer coordinates the details and identifies assumptions; the architect, contractor, manufacturer, and AHJ retain their respective design, installation, product, and approval responsibilities.",
    topic: "Construction and expansion joints",
    cluster: "Technical explainers",
    serviceHref: "/services/structural",
  },
  {
    slug: "temporary-shoring-design-explained",
    title: "What Is Temporary Shoring Design? | Apex Grid",
    description: "Temporary shoring design supports a building, excavation, or work area during construction until the permanent load path is complete.",
    h1: "What is temporary shoring design?",
    answer: "Temporary shoring design provides a planned support system for conditions that exist only during construction, such as wall removal, beam replacement, excavation, demolition, or installation of permanent framing. The engineer considers the sequence, temporary loads, stability, bearing surfaces, access, adjacent structures, existing defects, weather exposure, and the point at which permanent work becomes capable of carrying the load. Shoring drawings do not authorize unsafe field improvisation or replace a contractor's means-and-methods planning. The responsible engineer defines the design scope and limitations, while the contractor controls installation, monitoring, worker protection, and site operations subject to the applicable authority's requirements.",
    topic: "Temporary shoring design",
    cluster: "Technical explainers",
    serviceHref: "/services/structural",
  },
  {
    slug: "special-inspection-program-explained",
    title: "What Is a Special Inspection Program? | Apex Grid",
    description: "A special inspection program identifies construction work that needs documented observation or testing beyond ordinary jurisdiction inspections.",
    h1: "What is a special inspection program?",
    answer: "A special inspection program is a project-specific plan for observing, testing, reporting, and closing out designated construction activities that warrant additional quality verification. It may address materials, connections, reinforcing, welding, concrete, masonry, soils, or other work identified by the adopted code, approved documents, or AHJ. The engineer helps define the technical scope and coordinates inspection requirements with the drawings, specifications, testing agency, contractor, and owner. It is not a blanket certification of construction and does not transfer the contractor's responsibility to build correctly. The authority determines which inspections are required and how reports must be accepted.",
    topic: "Special inspection programs",
    cluster: "Technical explainers",
    serviceHref: "/services/structural",
  },
  {
    slug: "hvac-zoning-explained",
    title: "What Is HVAC Zoning? | Apex Grid",
    description: "HVAC zoning divides a building into areas with related loads, schedules, and control needs so distribution and operation can be coordinated.",
    h1: "What is HVAC zoning?",
    answer: "HVAC zoning groups spaces that have sufficiently similar occupancy, exposure, operating schedule, ventilation needs, and temperature control requirements. A design team uses those relationships to select equipment, air distribution, controls, dampers, and zoning boundaries without treating the entire building as one uniform load. Interior and perimeter spaces, kitchens, high-occupancy rooms, process areas, and spaces with different hours may require different treatment. The mechanical engineer establishes the design basis from current architecture, envelope, equipment, and operating information. The owner confirms operational priorities, the architect coordinates space and ceiling constraints, and the AHJ decides applicable submission requirements.",
    topic: "HVAC zoning",
    cluster: "Technical explainers",
    serviceHref: "/services/mep",
  },
  {
    slug: "testing-adjusting-balancing-explained",
    title: "What Is Testing, Adjusting, and Balancing? | Apex Grid",
    description: "Testing, adjusting, and balancing verifies that building air and hydronic systems deliver the intended distribution and operating conditions.",
    h1: "What is testing, adjusting, and balancing?",
    answer: "Testing, adjusting, and balancing, often called TAB, is the field process of measuring system performance, comparing results with the design intent, and adjusting equipment and distribution so the system operates as coordinated. Depending on the project, it can include airflow, water flow, pressure relationships, temperature, controls, and equipment operation. The TAB agency performs field measurements using its procedures and instruments; the engineer interprets whether results align with the design and identifies unresolved constraints. Results depend on installed equipment, filters, dampers, controls, occupancy, and commissioning sequence. The owner and AHJ determine acceptance and closeout requirements.",
    topic: "Testing, adjusting, and balancing",
    cluster: "Technical explainers",
    serviceHref: "/services/mep",
  },
  {
    slug: "electrical-selective-coordination-explained",
    title: "What Is Electrical Selective Coordination? | Apex Grid",
    description: "Selective coordination studies how protective devices respond so the smallest affected part of an electrical system can be isolated when feasible.",
    h1: "What is electrical selective coordination?",
    answer: "Electrical selective coordination is the design process of evaluating protective devices across a distribution system so a fault is interrupted by the device nearest the problem when the applicable criteria and equipment allow that outcome. The engineer reviews the service, feeders, breakers, fuses, settings, available fault information, equipment ratings, emergency sources, and utility data, then coordinates the results with the one-line diagram and specifications. Manufacturer data and final equipment selections can change the conclusion. Selective coordination is not a promise that outages will always be limited or that a utility will accept a design; the responsible engineer and AHJ confirm the governing requirements.",
    topic: "Electrical selective coordination",
    cluster: "Technical explainers",
    serviceHref: "/services/mep",
  },
  {
    slug: "electrical-grounding-and-bonding-explained",
    title: "What Are Electrical Grounding and Bonding? | Apex Grid",
    description: "Grounding and bonding create intentional electrical paths for fault clearing, voltage stability, and equipment safety within a coordinated system.",
    h1: "What are electrical grounding and bonding?",
    answer: "Grounding connects selected parts of an electrical system to earth or a grounding reference, while bonding connects conductive parts so they remain at a similar potential and provide a reliable path for fault current. A project design considers the service arrangement, source, grounding electrode conditions, equipment, raceways, structural metal, separately derived systems, communications interfaces, and local utility requirements. The electrical engineer documents the system concept and coordinates it with equipment and architectural details; electricians install it according to the approved documents and applicable installation rules. The AHJ and serving utility control their acceptance criteria, so a generic diagram cannot determine a project-specific solution.",
    topic: "Electrical grounding and bonding",
    cluster: "Technical explainers",
    serviceHref: "/services/mep",
  },
  {
    slug: "backflow-prevention-engineering-explained",
    title: "What Is Backflow Prevention Engineering? | Apex Grid",
    description: "Backflow prevention engineering protects a potable water supply by evaluating cross-connections, pressure conditions, devices, and testing responsibilities.",
    h1: "What is backflow prevention engineering?",
    answer: "Backflow prevention engineering identifies connections where contaminated or nonpotable water could move into a potable supply and selects a protection approach appropriate to the hazard and system conditions. The review considers the water source, pressure relationships, equipment, irrigation or process connections, fire systems, chemical exposure, drainage, access for testing, and the water provider's standards. A plumbing engineer coordinates piping, devices, room layout, discharge, and maintenance access with the civil and architectural documents. Device selection alone does not establish compliance: the utility or health authority determines its required protection level, testing program, and approval process, while the owner maintains the system.",
    topic: "Backflow prevention engineering",
    cluster: "Technical explainers",
    serviceHref: "/services/mep",
  },
  {
    slug: "fire-sprinkler-hydraulic-design-explained",
    title: "What Is Fire Sprinkler Hydraulic Design? | Apex Grid",
    description: "Fire sprinkler hydraulic design evaluates water supply, piping, sprinkler layout, and demand so the fire protection system can be reviewed as a coordinated whole.",
    h1: "What is fire sprinkler hydraulic design?",
    answer: "Fire sprinkler hydraulic design uses the building's hazard classification, compartment geometry, sprinkler arrangement, piping, elevation, water supply, control assemblies, and required flow paths to demonstrate that the proposed system can serve its design demand. The fire protection designer coordinates ceiling conditions, structure, mechanical systems, architectural use, fire department connections, and access for inspection and maintenance. Water-flow information must come from a reliable source and final field conditions can affect the design. The responsible designer identifies the system basis and deliverables; the fire marshal, AHJ, and water provider determine review, acceptance, testing, and operational requirements.",
    topic: "Fire sprinkler hydraulic design",
    cluster: "Technical explainers",
    serviceHref: "/services/mep",
  },
  {
    slug: "utility-easement-coordination-explained",
    title: "What Is Utility Easement Coordination? | Apex Grid",
    description: "Utility easement coordination reconciles private property rights, public corridors, provider requirements, and the physical routing of site services.",
    h1: "What is utility easement coordination?",
    answer: "Utility easement coordination maps who owns, controls, accesses, maintains, and approves each utility corridor before a project fixes building, grading, or service locations. The team reviews recorded easements, rights-of-way, utility records, survey information, points of connection, capacity, clearance, access, crossings, abandonment, and conflicts with foundations or landscaping. A civil engineer can coordinate the technical plan, but cannot grant property rights or speak for a utility. Owners, title professionals, surveyors, providers, and public agencies control their respective records and decisions. The AHJ may review site work separately from a provider's service approval, so neither approval should be assumed from proximity alone.",
    topic: "Utility easement coordination",
    cluster: "Technical explainers",
    serviceHref: "/services/civil",
  },
  {
    slug: "liquefaction-screening-explained",
    title: "What Is Liquefaction Screening? | Apex Grid",
    description: "Liquefaction screening considers whether saturated, susceptible soil could lose strength during earthquake shaking and affect a project's foundation decisions.",
    h1: "What is liquefaction screening?",
    answer: "Liquefaction screening is an initial geotechnical evaluation of whether site soils and groundwater conditions may be susceptible to strength loss or settlement during earthquake shaking. The engineer considers geologic setting, fill history, soil layers, groundwater, field and laboratory evidence, seismic criteria, and the proposed building's sensitivity and foundation system. Screening may lead to a more detailed evaluation, mitigation, monitoring, or a conclusion that the available evidence is sufficient for the defined scope. It cannot be responsibly answered from a regional label or neighboring property. A geotechnical engineer defines the investigation and recommendations, the structural engineer coordinates foundation implications, and the AHJ determines required studies.",
    topic: "Liquefaction screening",
    cluster: "Technical explainers",
    serviceHref: "/services/assessments",
  },
  {
    slug: "building-commissioning-explained",
    title: "What Is Building Commissioning? | Apex Grid",
    description: "Building commissioning is a documented process for checking that installed systems are complete, operable, and aligned with the owner's project requirements.",
    h1: "What is building commissioning?",
    answer: "Building commissioning is a quality process that carries the owner's project requirements from design through installation, functional testing, training, and closeout. It may cover HVAC, controls, electrical systems, plumbing, life-safety interfaces, envelope elements, or other systems whose performance depends on coordinated operation. The commissioning team develops checklists, reviews design intent and submittals, witnesses tests, records deficiencies, and verifies resolution within its scope. Commissioning does not replace the engineer's design responsibility, contractor quality control, code inspections, or the owner's decision to accept the facility. The actual systems, project phase, contract documents, and AHJ requirements determine the appropriate depth.",
    topic: "Building commissioning",
    cluster: "Technical explainers",
    serviceHref: "/services/mep",
  },
  {
    slug: "engineering-shop-drawing-review-explained",
    title: "What Is an Engineering Shop Drawing Review? | Apex Grid",
    description: "An engineering shop drawing review compares a fabricator's proposed product or assembly with the approved design intent and project requirements.",
    h1: "What is an engineering shop drawing review?",
    answer: "An engineering shop drawing review checks whether a proposed fabricated item, connection, equipment support, or specialty assembly is consistent with the contract documents and the design assumptions that affect it. The reviewer compares dimensions, materials, loads, attachments, interfaces, clearances, substitutions, tolerances, and installation information, then records comments or a defined disposition. Review is not a redesign of every fabrication detail and does not transfer the contractor's responsibility for dimensions, quantities, coordination, or means and methods. The responsible engineer states the review scope and relies on suitable project records; the contractor remains responsible for fabrication and field verification, and the AHJ controls any required deferred review or approval.",
    topic: "Engineering shop drawing review",
    cluster: "Technical explainers",
    serviceHref: "/services/structural",
  },
  {
    slug: "design-assist-engineering-explained",
    title: "What Is Design-Assist Engineering? | Apex Grid",
    description: "Design-assist engineering brings contractor, vendor, and engineer input into design decisions while preserving clear responsibility for the final documents.",
    h1: "What is design-assist engineering?",
    answer: "Design-assist engineering is a collaborative delivery approach in which a contractor, fabricator, specialty trade, or equipment supplier contributes constructability, product, sequencing, or installation information during design. The engineer evaluates relevant input against the project's performance requirements, site conditions, code path, coordination needs, and professional scope rather than accepting a proposal automatically. The final design responsibility, delegated design boundaries, substitutions, and review milestones should be stated in the contract documents. A vendor's recommendation is not an engineering seal, and design assist does not bypass the AHJ. Owners should confirm who designs, who supplies, who installs, who verifies, and who accepts each element.",
    topic: "Design-assist engineering",
    cluster: "Technical explainers",
    serviceHref: "/services/structural",
  },
  {
    slug: "building-penetration-coordination-explained",
    title: "How Does Engineering Coordinate Building Penetrations? | Apex Grid",
    description: "Building penetration coordination aligns structure, MEP routes, fire protection, waterproofing, and access before openings are cut or formed.",
    h1: "How does engineering coordinate building penetrations?",
    answer: "Engineering coordinates a building penetration by identifying the element being opened, the systems passing through it, and the performance that must remain intact. The review considers member capacity, reinforcement, fire and smoke separation, acoustics, waterproofing, vibration, clearances, sleeves, access, insulation, and the construction sequence. Structural, mechanical, electrical, plumbing, fire protection, and architectural documents must use the same location and dimensions; a field-cut opening should not be treated as an approved design change. The responsible professionals define their discipline boundaries and document acceptable details, while the contractor verifies field conditions and requests changes. The AHJ determines when revised documents or inspections are required.",
    topic: "Building penetration coordination",
    cluster: "Technical explainers",
    serviceHref: "/services/mep",
  },
];