import type { Phase7AeoSeed } from "./phase7-types";

export const PHASE7_HIRING_PAGES: Phase7AeoSeed[] = [
  {
    slug: "how-to-select-an-engineering-provider",
    title: "How to Select an Engineering Provider | Apex Grid",
    description: "A practical, jurisdiction-neutral way to select an engineering provider by matching scope, responsibility, experience, and communication to the project.",
    h1: "How should I select an engineering provider?",
    answer: "Select an engineering provider by first defining the project question, disciplines, location, existing-condition uncertainty, expected documents, and decision date. Then compare providers on relevant work, the people who will actually perform and review the work, their proposed deliverables, assumptions, communication process, and ability to accept professional responsibility for the stated scope. A low fee or attractive portfolio is not enough. Confirm license status and authorization through the applicable board or authority, and ask the provider to identify what remains an owner, architect, contractor, utility, or AHJ decision. The AHJ determines required documents and approval; the engineer determines what can responsibly be designed, reviewed, and sealed.",
    topic: "Selecting an engineering provider",
    cluster: "Hiring and vetting",
    serviceHref: "/services/structural",
  },
  {
    slug: "how-to-write-an-engineering-rfp",
    title: "How to Write an Engineering RFP | Apex Grid",
    description: "Learn what an engineering request for proposals should communicate so responses can be compared on a consistent, responsible scope.",
    h1: "How should I write an engineering request for proposals?",
    answer: "Write an engineering request for proposals by describing the project location, existing and proposed use, known site or building conditions, design stage, disciplines under consideration, desired deliverables, available records, coordination parties, and the authority or permit question already known. Ask each respondent to state its scope, exclusions, assumptions, required owner inputs, review approach, proposed responsible professional, and treatment of revisions. Do not prescribe a seal or approval outcome as the service; the professional must decide whether the work is within competence and authorized for the jurisdiction. The AHJ controls its checklist and interpretation, so the RFP should request confirmation of requirements rather than promise a particular result.",
    topic: "Engineering requests for proposals",
    cluster: "Hiring and vetting",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "how-to-compare-engineering-proposals",
    title: "How to Compare Engineering Proposals | Apex Grid",
    description: "A scope-first method for comparing engineering proposals without treating a professional service as a commodity or a permit approval promise.",
    h1: "How should I compare engineering proposals?",
    answer: "Compare engineering proposals by normalizing the scope before comparing fees. Put each response beside the same questions: which disciplines and project phases are included, what drawings or calculations will be delivered, who performs and reviews the work, how existing conditions will be verified, what coordination and comment responses are included, and which assumptions or exclusions could change the work. Also compare the provider's communication path, revision rules, schedule dependencies, and jurisdictional authorization. A proposal that omits field evidence, coordination, or professional review may appear less expensive while leaving material risk with the owner. The AHJ decides completeness and acceptance; no proposal can responsibly guarantee that decision.",
    topic: "Comparing engineering proposals",
    cluster: "Hiring and vetting",
    serviceHref: "/services/mep",
  },
  {
    slug: "questions-to-ask-an-engineering-firm",
    title: "Questions to Ask an Engineering Firm Before Hiring | Apex Grid",
    description: "Use focused questions about scope, responsibility, evidence, coordination, and authority boundaries before engaging an engineering firm.",
    h1: "What should I ask an engineering firm before hiring it?",
    answer: "Before hiring an engineering firm, ask who will lead the work, which professional will review or seal eligible documents, what information is needed to begin, how uncertain existing conditions will be handled, and which disciplines or consultants are outside the proposal. Ask how the firm records assumptions, coordinates with the architect and contractor, handles owner changes, responds to AHJ comments, and communicates decisions. Request a written description of deliverables and exclusions rather than relying on a sales summary. The answers should fit the building or site, occupancy, design stage, and jurisdiction. The firm can explain engineering judgment and professional responsibility, but the AHJ alone determines its review requirements and approval.",
    topic: "Engineering firm interview questions",
    cluster: "Hiring and vetting",
    serviceHref: "/services/structural",
  },
  {
    slug: "how-to-verify-an-engineers-license",
    title: "How to Verify an Engineer's License Before Hiring | Apex Grid",
    description: "Verify the professional license, status, discipline authority, and project relevance of the engineer proposed for your work.",
    h1: "How should I verify an engineer's license before hiring?",
    answer: "Verify an engineer's license by obtaining the person's full legal name, license or registration information, discipline, current status, and any public restrictions from the applicable licensing board's official lookup. Confirm that the proposed responsible professional—not merely a salesperson or an unrelated reviewer—is identified for the scope. Check whether the project location and requested services require additional authorization, firm registration, a local professional, or another discipline. A license lookup does not prove competence, site knowledge, or the adequacy of a design, so also evaluate relevant work and the written scope. The board controls licensure rules, while the AHJ controls its submittal and review requirements; neither lookup is an approval promise.",
    topic: "Verifying professional engineering licensure",
    cluster: "Hiring and vetting",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "how-to-confirm-engineering-jurisdiction-authorization",
    title: "How to Confirm an Engineer's Jurisdictional Authorization | Apex Grid",
    description: "Understand how project location, discipline, firm status, and board rules affect whether an engineering provider may perform and seal the requested work.",
    h1: "How should I confirm an engineer is authorized for my project jurisdiction?",
    answer: "Confirm jurisdictional authorization by identifying the project location, regulated discipline, type of document, and professional who will accept responsibility, then checking the applicable board and agency requirements. Ask whether the engineer and, where relevant, the firm may provide services in that jurisdiction and whether the proposed work falls within the professional's competence and authorization. Remote availability, a national marketing profile, or a seal image does not answer those questions. Keep the verification record with the contract and submittal file, and revisit it if the location, scope, or responsible professional changes. The licensing board governs authorization and the AHJ determines what it will accept; the provider should not promise either outcome.",
    topic: "Confirming jurisdictional authorization",
    cluster: "Hiring and vetting",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "how-to-evaluate-engineering-experience",
    title: "How to Evaluate an Engineering Firm's Experience | Apex Grid",
    description: "Assess engineering experience by testing its relevance to the actual system, existing conditions, project phase, and jurisdiction—not by counting logos.",
    h1: "How should I evaluate an engineering firm's experience?",
    answer: "Evaluate an engineering firm's experience by asking for examples that match the technical question, building or site conditions, occupancy, scale, design phase, and coordination burden of your project. Ask what the firm actually delivered, which professionals performed the work, what information was available, and how unusual conditions or agency comments were addressed. Distinguish experience of the firm from experience of the proposed team; a general project list is not evidence that the assigned professional will handle your scope. Review examples for relevance without asking for confidential client material. Experience can inform selection, but it cannot replace project-specific investigation or judgment, and the AHJ still decides which documents and code path it requires.",
    topic: "Evaluating relevant engineering experience",
    cluster: "Hiring and vetting",
    serviceHref: "/services/civil",
  },
  {
    slug: "how-to-check-engineering-references",
    title: "How to Check Engineering Firm References | Apex Grid",
    description: "A reference check for engineering services should test scope clarity, communication, coordination, and professional conduct without soliciting confidential information.",
    h1: "How should I check references for an engineering firm?",
    answer: "Check engineering references by using clients who can discuss a comparable scope, project condition, and level of coordination, with permission to make contact. Ask whether the firm understood the brief, identified missing information, kept assumptions visible, communicated changes, coordinated with other professionals, and delivered the agreed documents. Ask how the firm handled uncertainty and authority comments rather than asking a reference to guarantee approval or performance on a new project. Treat one opinion as context, not proof; combine references with license verification, a written proposal, and an interview with the assigned team. References cannot replace the engineer's independent review, and an AHJ's decision remains outside the reference's or provider's control.",
    topic: "Checking engineering references",
    cluster: "Hiring and vetting",
    serviceHref: "/services/structural",
  },
  {
    slug: "how-to-assess-engineering-team-availability",
    title: "How to Assess an Engineering Team's Availability | Apex Grid",
    description: "Assess engineering capacity by clarifying the assigned team, dependencies, review points, and communication plan instead of relying on an unqualified speed claim.",
    h1: "How should I assess an engineering team's availability?",
    answer: "Assess an engineering team's availability by asking who is assigned, who covers absences, how many project decisions require the responsible professional, and when the team can review the information you have. Map dependencies such as architectural decisions, surveys, geotechnical evidence, equipment selections, utility responses, site access, and owner review. Ask how the firm will flag an incomplete input or a scope change and how urgent questions are routed, rather than relying on a generic promise to start immediately. Capacity is project-specific and can change with scope or evidence. The provider controls its staffing commitments, while the AHJ controls its queue and review; neither can promise a complete project outcome from an availability statement.",
    topic: "Assessing engineering team availability",
    cluster: "Hiring and vetting",
    serviceHref: "/services/mep",
  },
  {
    slug: "how-to-evaluate-engineering-change-terms",
    title: "How to Evaluate Engineering Change and Revision Terms | Apex Grid",
    description: "Review how an engineering proposal treats changed information, owner revisions, AHJ comments, and work outside the original scope.",
    h1: "How should I evaluate engineering change and revision terms?",
    answer: "Evaluate engineering change terms by separating foreseeable coordination and review work from a genuinely changed scope. The proposal should explain what happens when the owner changes the program, architectural backgrounds move, existing conditions differ, equipment is substituted, a utility changes its requirements, or the AHJ requests work outside the agreed deliverables. Look for a clear notice process, decision authority, records of assumptions, and a method for agreeing on revised scope before production continues. Do not assume every plan-check comment is automatically included or automatically extra; the written scope and the actual comment control. The engineer can explain technical consequences, but the AHJ decides its comment and the owner must approve contractual changes.",
    topic: "Engineering change and revision terms",
    cluster: "Hiring and vetting",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "how-to-set-engineering-communication-expectations",
    title: "How to Set Engineering Communication Expectations | Apex Grid",
    description: "Set useful communication expectations with an engineering provider by defining contacts, decisions, records, reviews, and escalation boundaries.",
    h1: "How should I set communication expectations with an engineer?",
    answer: "Set communication expectations by naming the project contact, responsible professional, owner decision-maker, and coordination contacts, then defining how questions, approvals, revisions, and field observations will be recorded. Agree on the information the engineer needs before a design decision can be made, how unresolved assumptions are identified, and when the team should pause rather than infer an owner or contractor decision. Include document naming, review comments, meeting records, and escalation for safety or scope concerns. Communication preferences do not transfer professional responsibility: the engineer owns eligible engineering judgments, the architect and contractor retain their own roles, and the AHJ retains authority over official review and acceptance.",
    topic: "Engineering communication expectations",
    cluster: "Hiring and vetting",
    serviceHref: "/services/structural",
  },
  {
    slug: "how-to-review-engineering-insurance-terms",
    title: "How to Review Engineering Insurance and Contract Terms | Apex Grid",
    description: "Review engineering insurance and contract language with the right legal and professional boundaries, without treating coverage as proof of design quality.",
    h1: "How should I review engineering insurance and contract terms?",
    answer: "Review engineering insurance and contract terms by asking what services are covered, which entity is contracting, whether the policy information is current, and whether exclusions, limitations, indemnity, reliance, ownership, and dispute provisions fit the project. Have qualified legal or insurance advisers interpret terms that affect your rights; a certificate or policy summary is not a substitute for that advice. Insurance can address certain claims under its terms, but it does not demonstrate competence, authorize a seal, or guarantee a safe design or permit result. Also make the technical scope, responsible professional, deliverables, records, and change process explicit. The provider and owner negotiate the contract, while boards and AHJs control professional and regulatory requirements.",
    topic: "Engineering insurance and contract terms",
    cluster: "Hiring and vetting",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "how-to-vet-engineering-subconsultants",
    title: "How to Vet Engineering Subconsultants | Apex Grid",
    description: "A practical process for vetting engineering subconsultants, clarifying responsibility, and preventing gaps between prime and specialty scopes.",
    h1: "How should I vet an engineering subconsultant?",
    answer: "Vet an engineering subconsultant by identifying the specialty scope, project jurisdiction, interfaces with the prime consultant, expected deliverables, and professional who will accept responsibility for that work. Verify the proposed professional's board status and authorization, review relevant experience, and ask how calculations, models, drawings, field information, and revisions will pass between teams. The prime agreement should state who selects, directs, pays, reviews, and replaces the subconsultant, while the technical documents should identify boundaries rather than imply that one seal covers every discipline. Each professional remains responsible only for the work properly undertaken and authorized. The AHJ may impose its own identification and submittal rules, so its requirements must be confirmed directly.",
    topic: "Vetting engineering subconsultants",
    cluster: "Hiring and vetting",
    serviceHref: "/services/civil",
  },
  {
    slug: "how-to-review-engineering-document-control",
    title: "How to Review an Engineering Firm's Document Control | Apex Grid",
    description: "Evaluate an engineering provider's document-control habits so current drawings, calculations, comments, and assumptions remain traceable.",
    h1: "How should I review an engineering firm's document control?",
    answer: "Review document control by asking how the firm identifies current and superseded drawings, calculations, models, specifications, field evidence, review comments, and approvals. A sound process records revision purpose, affected disciplines, open assumptions, file ownership, and the relationship between calculations and sheets, while preserving the project record in an agreed location. Ask who checks a package before release and how an urgent change is communicated to the architect, contractor, owner, and other consultants. Document control reduces coordination risk but does not independently verify the engineering. The responsible professional must judge the technical work, the contractor must use current authorized information, and the AHJ controls its required file format and official submission record.",
    topic: "Engineering document control",
    cluster: "Hiring and vetting",
    serviceHref: "/services/mep",
  },
  {
    slug: "how-to-check-engineering-conflicts-of-interest",
    title: "How to Check for Engineering Conflicts of Interest | Apex Grid",
    description: "Identify and manage potential engineering conflicts of interest before hiring, while preserving independent professional judgment and project transparency.",
    h1: "How should I check for conflicts of interest before hiring an engineer?",
    answer: "Check for conflicts of interest by asking the provider to disclose relationships, financial interests, prior work, competing duties, or supplier and contractor ties that could affect independent advice on the defined scope. Explain the decisions the engineer may influence, such as equipment selection, existing-condition conclusions, change evaluation, or review of another party's work. A disclosed relationship is not automatically disqualifying; assess whether it can be managed through recusal, separation, informed consent, or another written safeguard with legal or procurement advice where appropriate. Professional rules and the contract govern the provider's duties, while the AHJ remains the independent authority on compliance. Do not use a conflict disclosure as a substitute for technical qualifications or license verification.",
    topic: "Engineering conflicts of interest",
    cluster: "Hiring and vetting",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "how-to-document-engineering-provider-selection",
    title: "How to Document an Engineering Provider Selection | Apex Grid",
    description: "Create a defensible engineering selection record that ties the chosen provider to scope, responsibility, evidence, and project needs.",
    h1: "How should I document an engineering provider selection?",
    answer: "Document an engineering provider selection with the project brief, respondents considered, scope comparison, license and authorization checks, relevant experience, reference notes, conflicts disclosed, insurance or contract review, and the reasons the selected proposal fits the work. Record which assumptions, exclusions, optional services, and owner decisions were accepted, along with the named team and responsible professional. Keep the final proposal and written clarifications with the agreement so later changes can be traced to the original basis. A selection record supports procurement accountability but is not an engineering review or a permit determination. The selected professional must independently confirm the scope, and the AHJ retains authority over required documents and acceptance.",
    topic: "Documenting an engineering provider selection",
    cluster: "Hiring and vetting",
    serviceHref: "/services/structural",
  },
];