import type { Phase7AeoSeed } from "./phase7-types";

export const PHASE7_PERMIT_PAGES: Phase7AeoSeed[] = [
  {
    slug: "what-is-a-permit-preapplication-meeting",
    title: "What Is a Permit Pre-Application Meeting? | Apex Grid",
    description: "A permit pre-application meeting lets a project team discuss scope, submittal expectations, and likely agency coordination with the authority before filing.",
    h1: "What is a permit pre-application meeting?",
    answer: "A permit pre-application meeting is an early discussion between a project team and the authority having jurisdiction (AHJ) about a proposed scope before a formal application is filed. The team can present the site, use, work limits, existing conditions, and preliminary design questions, while the AHJ can identify applicable review tracks, forms, investigations, or other agencies. It is guidance rather than an approval: the current code, adopted procedures, official checklist, and later review control. An engineer can prepare technical questions and explain the defined engineering scope, but the owner or authorized applicant remains responsible for requesting the meeting and recording the AHJ’s direction.",
    topic: "Permit pre-application meetings",
    cluster: "Plan check and permits",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "what-is-a-permit-completeness-review",
    title: "What Is a Permit Completeness Review? | Apex Grid",
    description: "A permit completeness review checks whether an application contains the forms, drawings, signatures, and supporting information required for intake.",
    h1: "What is a permit completeness review?",
    answer: "A permit completeness review is the AHJ’s intake check that a permit application includes the required forms, drawings, signatures, supporting reports, and submission details before substantive review begins. It asks whether the package is administratively and visibly complete, not whether every design decision complies with the code. The result can depend on project type, application pathway, file rules, required disciplines, and whether other agencies must receive separate materials. Engineers can help organize and quality-check their own deliverables, but only the AHJ can decide whether the application is complete and move it into its official review process.",
    topic: "Permit application completeness",
    cluster: "Plan check and permits",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "zoning-approval-vs-building-permit",
    title: "Zoning Approval vs. Building Permit: What Is the Difference? | Apex Grid",
    description: "Zoning approval addresses land use and site permissions, while a building permit authorizes code-regulated construction after the responsible reviews are satisfied.",
    h1: "What is the difference between zoning approval and a building permit?",
    answer: "Zoning approval and a building permit are separate decisions that can both affect a project. Zoning or land-use review typically addresses use, setbacks, height, site layout, parking, signage, or other property controls; a building permit addresses the regulated construction and safety work shown in the approved documents. A project may need zoning clearance, a planning action, or another land-use decision before or alongside its building application. A civil or structural engineer can document technical site or building information, but cannot grant zoning rights or replace the planning office’s decision. The property, proposed use, local rules, and AHJ workflow determine the actual sequence.",
    topic: "Zoning approval and building permits",
    cluster: "Plan check and permits",
    serviceHref: "/services/civil",
  },
  {
    slug: "which-agencies-review-a-commercial-building-permit",
    title: "Which Agencies Review a Commercial Building Permit? | Apex Grid",
    description: "A commercial building permit may involve building, planning, fire, utilities, environmental, health, or transportation reviewers depending on the site and scope.",
    h1: "Which agencies may review a commercial building permit?",
    answer: "The building department is often the primary permit authority, but a commercial project may also involve planning or zoning, fire protection, public works, utilities, health, environmental, historic-preservation, transportation, or accessibility reviewers. The agencies depend on the address, occupancy, site disturbance, utility work, public-right-of-way effects, and special characteristics of the project. An engineer can map those interfaces, coordinate discipline documents, and identify questions that need confirmation, but one engineering seal does not approve another agency’s subject matter. The owner and applicant should obtain the current agency list and track each decision separately rather than assuming the building permit covers every authorization.",
    topic: "Multi-agency permit review",
    cluster: "Plan check and permits",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "can-construction-start-before-permit-issuance",
    title: "Can Construction Start Before a Permit Is Issued? | Apex Grid",
    description: "Construction should not begin on permit-controlled work until the AHJ confirms the required authorization and any limited exceptions in its current rules.",
    h1: "Can construction start before a permit is issued?",
    answer: "Usually, permit-controlled construction should wait until the responsible AHJ has issued the required authorization, because an application, plan review, or professional seal is not permission to build. Some jurisdictions distinguish emergency stabilization, minor maintenance, site preparation, demolition, or other narrowly defined activities, but those exceptions are local and may require their own notice or approval. Starting work early can create unsafe conditions, inspection problems, concealed work that must be exposed, enforcement action, or a need to revise the design. The owner, contractor, and AHJ control construction authorization; an engineer can advise on the technical consequences and revise engineering documents when scope or field conditions change.",
    topic: "Construction before permit issuance",
    cluster: "Plan check and permits",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "when-are-separate-trade-permits-required",
    title: "When Are Separate Trade Permits Required? | Apex Grid",
    description: "Separate mechanical, electrical, plumbing, fire, or specialty permits may be required when local procedures treat a system as its own regulated scope.",
    h1: "When are separate trade permits required?",
    answer: "Separate trade permits are required when the local permitting process treats mechanical, electrical, plumbing, fire-protection, sign, utility, or another specialty scope as its own application or authorization. The answer depends on the jurisdiction, project type, work limits, utility connection, contractor licensing rules, and whether the trade work is included in a building permit or reviewed independently. Coordinated engineering drawings help keep the scopes consistent, but they do not determine the AHJ’s filing rules. The applicant and contractor should confirm which permits, forms, inspections, and responsible parties apply; the engineer remains responsible only for the defined engineering work accepted under the applicable professional rules.",
    topic: "Separate trade permits",
    cluster: "Plan check and permits",
    serviceHref: "/services/mep",
  },
  {
    slug: "what-are-special-inspections-in-the-permit-process",
    title: "What Are Special Inspections in the Permit Process? | Apex Grid",
    description: "Special inspections are independent or specially qualified field observations required for designated construction elements, separate from the AHJ’s ordinary inspections.",
    h1: "What are special inspections in the permit process?",
    answer: "Special inspections are documented field inspections or tests for construction elements that the adopted code or AHJ identifies as needing additional oversight beyond ordinary building inspections. Depending on the project, they may address structural materials, connections, soils, welding, concrete, anchors, or other critical work. The permit documents should identify the applicable scope and reporting path when the requirement is known, while the AHJ determines whether the inspection program is accepted. The engineer can define or coordinate engineering-related inspection requirements within the professional scope, but does not replace the special inspector, contractor, testing agency, or building inspector. The project team must confirm qualifications, reports, scheduling, and closeout requirements locally.",
    topic: "Special inspections",
    cluster: "Plan check and permits",
    serviceHref: "/services/structural",
  },
  {
    slug: "what-is-a-certificate-of-occupancy",
    title: "What Is a Certificate of Occupancy? | Apex Grid",
    description: "A certificate of occupancy is an AHJ record that a building or space may be occupied for an identified use after required approvals and inspections are satisfied.",
    h1: "What is a certificate of occupancy?",
    answer: "A certificate of occupancy is an official AHJ document or record stating that a building, portion of a building, or identified use may be occupied under the conditions recognized by that authority. Issuance can depend on completed construction, required inspections, life-safety systems, accessibility, utilities, zoning or use approvals, and documentation from other agencies. The exact name and process vary, and some jurisdictions use an equivalent final approval rather than a document with this title. Engineering drawings or a sealed report may support the record, but an engineer cannot issue the occupancy authorization unless the law expressly assigns that function. The AHJ decides whether the space is eligible and what conditions remain.",
    topic: "Certificates of occupancy",
    cluster: "Plan check and permits",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "how-do-permit-expirations-and-extensions-work",
    title: "How Do Permit Expirations and Extensions Work? | Apex Grid",
    description: "Permit expiration and extension rules are controlled by the issuing authority and may depend on activity, inspections, notice, and the current project record.",
    h1: "How do permit expirations and extensions work?",
    answer: "A permit expiration is the end of the validity period or authorization recognized by the issuing AHJ, while an extension is a formal request to keep that authorization active under the authority’s rules. The result can depend on whether work has started, inspection activity, unresolved corrections, changes in ownership or scope, adopted regulations, and the authority’s notice and filing requirements. An extension is not automatic, and a lapsed permit may require renewal, a new application, updated documents, or another review. The owner or authorized applicant must ask the AHJ about the current status; an engineer can evaluate whether changed conditions require technical updates but cannot extend a permit independently.",
    topic: "Permit expiration and extension",
    cluster: "Plan check and permits",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "can-a-building-permit-transfer-to-a-new-owner",
    title: "Can a Building Permit Transfer to a New Owner? | Apex Grid",
    description: "A building permit may or may not transfer after a property change; the issuing authority controls notices, authorization, and any required revalidation.",
    h1: "Can a building permit transfer to a new owner?",
    answer: "A building permit does not automatically transfer simply because property ownership changes. Some AHJs allow an owner or applicant update after a written notice, while others require a new authorization, confirmation of the responsible contractor, or review of changes made to the approved scope. The permit record, local law, construction status, responsible professionals, and any change in use or design can affect the result. The buyer and seller should ask the issuing authority for its current transfer procedure and preserve the approved documents and inspection history. An engineer may review technical continuity or document a scope change, but cannot transfer the permit or release the AHJ’s conditions.",
    topic: "Permit transfer after ownership change",
    cluster: "Plan check and permits",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "what-is-a-phased-building-permit",
    title: "What Is a Phased Building Permit? | Apex Grid",
    description: "A phased building permit separates an approved project into authorized work packages when the AHJ permits that filing strategy and the packages remain coordinated.",
    h1: "What is a phased building permit?",
    answer: "A phased building permit is an AHJ-approved filing strategy that divides a larger project into defined construction or document packages rather than treating every scope as one authorization. A phase may be organized around enabling work, foundations, a building area, or a discipline, but the allowable structure depends on local rules and the authority’s acceptance. Each package needs a clear boundary, enough information for its review, safe interfaces with later work, and a process for coordinating changes. An engineer can design and document a defined phase while identifying assumptions and dependencies, but cannot authorize construction of a later phase or bypass required reviews. The owner, architect, contractor, and AHJ must agree on sequencing and responsibility.",
    topic: "Phased building permits",
    cluster: "Plan check and permits",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "what-is-an-alternate-materials-methods-request",
    title: "What Is an Alternate Materials or Methods Request? | Apex Grid",
    description: "An alternate materials or methods request asks the AHJ to accept a proposed solution that differs from a prescriptive code provision while meeting the applicable performance intent.",
    h1: "What is an alternate materials or methods request?",
    answer: "An alternate materials or methods request is a formal proposal to use a product, assembly, design approach, or construction method that is not the prescriptive option described in the adopted code. The applicant generally needs a technical basis showing why the alternative provides the required level of safety, performance, durability, or function, along with product evidence and limitations when relevant. The responsible engineer can prepare the engineering analysis and identify assumptions within the defined scope, but the AHJ decides whether the alternative is acceptable and whether another agency must concur. Acceptance is project-specific; it does not amend the code for other projects or guarantee approval of a future submission.",
    topic: "Alternate materials and methods",
    cluster: "Plan check and permits",
    serviceHref: "/services/structural",
  },
  {
    slug: "what-does-permit-closeout-include",
    title: "What Does Permit Closeout Include? | Apex Grid",
    description: "Permit closeout confirms that required construction, inspections, documents, and agency actions have been completed so the AHJ can close its record.",
    h1: "What does permit closeout include?",
    answer: "Permit closeout is the final administrative and technical process used by the AHJ to confirm that the permitted work is complete and the required record can be closed. It may include final inspections, special-inspection reports, testing or commissioning records, approved revisions, contractor or owner certifications, as-built information, fees, and sign-offs from other agencies. The exact checklist depends on the permit, project scope, construction changes, and local procedures. Engineers can review whether engineering changes are documented and issue revised or record documents when professionally justified, but cannot certify work they did not observe or make the AHJ close the permit. The owner and contractor should obtain the authority’s current closeout requirements and retain the completed record.",
    topic: "Permit closeout",
    cluster: "Plan check and permits",
    serviceHref: "/permit-engineering/",
  },
  {
    slug: "how-are-permit-conditions-tracked-after-approval",
    title: "How Are Permit Conditions Tracked After Approval? | Apex Grid",
    description: "Permit conditions are approval obligations that the project team should assign, document, and verify throughout design, construction, inspection, and closeout.",
    h1: "How are permit conditions tracked after approval?",
    answer: "Permit conditions are tracked by turning every approval note, deferred requirement, agency commitment, inspection item, and document restriction into a controlled project record with an owner and a point of verification. The team should distinguish conditions that affect drawings from those that affect procurement, construction sequencing, inspections, operations, or closeout, then preserve the AHJ’s wording and evidence of completion. An engineer can maintain the engineering portions of a matrix and revise documents when a condition changes the design, while the owner, contractor, and other agencies retain their assigned responsibilities. The AHJ decides whether a condition is satisfied; an internal checklist is useful evidence but is not itself an approval.",
    topic: "Permit condition tracking",
    cluster: "Plan check and permits",
    serviceHref: "/permit-engineering/",
  },
];