import type { Phase7AeoSeed } from "./phase7-types";

export const PHASE7_COST_PAGES: Phase7AeoSeed[] = [
  {
    slug: "what-should-an-engineering-fee-proposal-include",
    title: "What Should an Engineering Fee Proposal Include? | Apex Grid",
    description: "A useful engineering fee proposal connects a defined scope to deliverables, assumptions, exclusions, coordination, revisions, and payment terms without promising an approval outcome.",
    h1: "What should an engineering fee proposal include?",
    answer: "An engineering fee proposal should identify the project, disciplines, design tasks, documents, calculations, meetings, coordination, site or field work, review of owner information, and expected submission package. It should also state assumptions, exclusions, revision rules, schedule conditions, reimbursable expenses, payment terms, and who supplies information. The engineer can price and accept responsibility only for the defined professional scope; the AHJ controls required documents, fees, interpretation, and approval.",
    topic: "Engineering fee proposal contents",
    cluster: "Cost and pricing",
    serviceHref: "/services/",
  },
  {
    slug: "why-engineering-proposals-list-assumptions-and-exclusions",
    title: "Why Do Engineering Proposals List Assumptions and Exclusions? | Apex Grid",
    description: "Assumptions and exclusions make an engineering price traceable by showing what information, services, conditions, and agency actions the proposal does and does not cover.",
    h1: "Why do engineering proposals list assumptions and exclusions?",
    answer: "Assumptions and exclusions keep an engineering price tied to a known scope. They may address the quality of existing drawings, access to concealed conditions, owner-furnished equipment, survey or geotechnical information, agency forms, construction services, and changes after authorization. They are not a way to avoid professional responsibility: the engineer must disclose material limitations and perform the agreed work competently. The AHJ may still request work outside the initial assumptions.",
    topic: "Engineering proposal assumptions and exclusions",
    cluster: "Cost and pricing",
    serviceHref: "/services/structural",
  },
  {
    slug: "how-to-compare-engineering-fee-proposals",
    title: "How Should an Owner Compare Engineering Fee Proposals? | Apex Grid",
    description: "Compare engineering proposals by scope, deliverables, assumptions, coordination, professional responsibility, revisions, and exclusions rather than by fee alone.",
    h1: "How should an owner compare engineering fee proposals?",
    answer: "Compare engineering proposals on an equivalent scope, not on the fee line alone. Match the disciplines, drawings, calculations, field verification, meetings, coordination, permit support, revision allowance, schedule conditions, and exclusions. Ask who will perform and review the work, what information is assumed, how additions are authorized, and which agency or third-party charges are separate. A low fee may omit necessary work, while a higher fee may include a broader deliverable; the responsible engineer and AHJ remain accountable for their respective decisions.",
    topic: "Comparing engineering proposals",
    cluster: "Cost and pricing",
    serviceHref: "/services/",
  },
  {
    slug: "are-engineering-fees-hourly-or-fixed",
    title: "Are Engineering Fees Hourly or Fixed? | Apex Grid",
    description: "Engineering may be offered as a fixed fee, time-based service, or defined hybrid; the appropriate structure depends on scope certainty, information quality, and revision risk.",
    h1: "Are engineering fees hourly or fixed?",
    answer: "Engineering fees can be fixed, time-based, or a defined combination of both. A fixed fee fits a sufficiently bounded scope with known deliverables and assumptions. Hourly or other time-based billing can be more transparent when existing conditions, agency direction, or design changes are uncertain. A hybrid may fix core documents while treating added services separately. The contract should explain rates or fee logic, authorization, records, and limits; no fee structure transfers AHJ authority or permits work outside the engineer's competence.",
    topic: "Engineering fee structures",
    cluster: "Cost and pricing",
    serviceHref: "/services/mep",
  },
  {
    slug: "what-is-a-not-to-exceed-engineering-fee",
    title: "What Is a Not-to-Exceed Engineering Fee? | Apex Grid",
    description: "A not-to-exceed engineering fee sets a contractual ceiling for defined services while preserving clear rules for scope changes, exclusions, and owner-authorized additions.",
    h1: "What is a not-to-exceed engineering fee?",
    answer: "A not-to-exceed fee is a contractual ceiling for identified engineering services, not an unlimited promise to complete every possible task. The agreement should define the included deliverables, billing basis, assumptions, notice of approaching the ceiling, and treatment of owner changes, concealed conditions, added agency requirements, and other authorized services. The ceiling does not reduce the engineer's duty to review the work or allow an unlicensed person to make professional decisions. The AHJ can still require additional documentation before deciding a submission.",
    topic: "Not-to-exceed engineering fees",
    cluster: "Cost and pricing",
    serviceHref: "/services/structural",
  },
  {
    slug: "what-is-an-engineering-retainer-or-deposit",
    title: "What Is an Engineering Retainer or Deposit? | Apex Grid",
    description: "An engineering retainer or deposit is a contract payment arrangement whose amount, application, replenishment, and refund treatment should be stated before work begins.",
    h1: "What is an engineering retainer or deposit?",
    answer: "An engineering retainer or deposit is an agreed payment collected before or during professional services and applied according to the contract. The proposal should say whether it is an advance against a fixed fee, a balance for time-based work, or a separate nonrefundable commitment, and should explain invoices, replenishment, unused balances, cancellation, and expenses. It does not purchase a seal, approval, or a particular technical conclusion. The engineer must still independently review the scope, and the client remains responsible for AHJ fees and decisions unless the agreement expressly says otherwise.",
    topic: "Engineering retainers and deposits",
    cluster: "Cost and pricing",
    serviceHref: "/services/",
  },
  {
    slug: "which-expenses-are-reimbursable-on-engineering-projects",
    title: "Which Expenses Are Reimbursable on an Engineering Project? | Apex Grid",
    description: "Reimbursable engineering expenses are project costs outside professional labor, such as approved travel, testing, reproduction, or specialist services, and should be defined in the agreement.",
    h1: "Which expenses are reimbursable on an engineering project?",
    answer: "Reimbursable expenses are project-specific costs that are separate from the engineer's professional labor, such as authorized travel, special testing, printing or delivery, survey or laboratory work, specialist consultants, or agency charges when the contract assigns them to the client. The proposal should identify likely categories, approval requirements, markups if any, and supporting records rather than leaving a broad blank check. An engineer should not pass off professional design responsibility as a vendor expense, and the AHJ—not the engineer—sets official application or review charges.",
    topic: "Reimbursable engineering expenses",
    cluster: "Cost and pricing",
    serviceHref: "/services/civil",
  },
  {
    slug: "are-permit-fees-included-in-an-engineering-proposal",
    title: "Are Permit Fees Included in an Engineering Proposal? | Apex Grid",
    description: "Permit and agency charges are often separate from engineering fees; the proposal should identify who pays them and what permit support the engineer will provide.",
    h1: "Are permit fees included in an engineering proposal?",
    answer: "Permit fees are not automatically part of an engineering fee. A proposal should distinguish professional design and documentation from application charges, plan-review fees, utility charges, special inspections, testing, and other amounts set by an agency or third party. It should also state whether the engineer will prepare forms, upload files, attend meetings, or respond to comments, and whether those tasks are included or additional. Only the relevant authority can calculate or waive its charges, and engineering support cannot guarantee that the authority will accept a submission.",
    topic: "Permit fees versus engineering fees",
    cluster: "Cost and pricing",
    serviceHref: "/services/structural",
  },
  {
    slug: "are-plan-check-responses-included-in-an-engineering-fee",
    title: "Are Plan-Check Responses Included in an Engineering Fee? | Apex Grid",
    description: "Plan-check response pricing depends on the agreed scope, the nature of comments, and whether corrections require revised engineering rather than a simple administrative response.",
    h1: "Are plan-check responses included in an engineering fee?",
    answer: "Plan-check responses are included only when the proposal says they are, and the included extent should be described. A response may involve reviewing a comment, preparing a narrative, revising drawings, updating calculations, coordinating other disciplines, or attending an agency meeting. Comments caused by an incomplete original scope, an owner change, new information, or a different interpretation may require additional services under the agreement. The engineer can explain and revise the professional work; the AHJ owns the comment, review process, and final acceptance.",
    topic: "Plan-check response pricing",
    cluster: "Cost and pricing",
    serviceHref: "/services/assessments",
  },
  {
    slug: "are-revisions-included-in-an-engineering-fee",
    title: "Are Revisions Included in an Engineering Fee? | Apex Grid",
    description: "Revision coverage should distinguish coordination needed to complete the agreed design from owner changes, changed information, and new authority requirements.",
    h1: "Are revisions included in an engineering fee?",
    answer: "Some revisions may be included when they are part of completing the agreed design and correcting an engineer's error, but a proposal should define the boundary. Revisions prompted by a changed architectural layout, substituted equipment, concealed conditions, expanded occupancy, new owner direction, or an AHJ request outside the assumed scope may be additional services. The contract should identify review points, authorization, affected deliverables, and communication before extra work proceeds. Inclusion of revisions does not promise approval; the authority evaluates the revised documents independently.",
    topic: "Engineering revision pricing",
    cluster: "Cost and pricing",
    serviceHref: "/services/mep",
  },
  {
    slug: "how-are-engineering-change-orders-priced",
    title: "How Are Engineering Change Orders Priced? | Apex Grid",
    description: "An engineering change order prices a defined addition or alteration by identifying the changed basis, affected deliverables, effort, assumptions, and approval path.",
    h1: "How are engineering change orders priced?",
    answer: "An engineering change order should describe what changed, why it changed, which drawings or calculations are affected, and what added coordination, field work, review, or agency support is required. The parties may agree on a fixed additional fee, time-based billing, or another documented basis after the engineer evaluates the change. A sound change order also states schedule effects, information needed, exclusions, and who can authorize it. It does not allow the engineer to skip independent review, and the AHJ may require additional or different documents regardless of the commercial agreement.",
    topic: "Engineering change orders",
    cluster: "Cost and pricing",
    serviceHref: "/services/structural",
  },
  {
    slug: "how-does-a-scope-change-affect-an-engineering-fee",
    title: "How Does a Scope Change Affect an Engineering Fee? | Apex Grid",
    description: "A scope change can alter engineering fees when it changes the design basis, disciplines, deliverables, coordination, field evidence, or professional review required.",
    h1: "How does a scope change affect an engineering fee?",
    answer: "A scope change can affect a fee because it changes the professional work needed to evaluate, design, document, coordinate, or revise the project. Adding equipment, changing occupancy, moving structural elements, expanding the site, selecting different systems, or changing the permit path can affect multiple disciplines and calculations. The engineer should explain the affected assumptions and obtain authorization before proceeding with additional services. An owner may define the business change, but the engineer determines the technical consequences and the AHJ decides whether the changed project complies.",
    topic: "Engineering scope-change pricing",
    cluster: "Cost and pricing",
    serviceHref: "/services/civil",
  },
  {
    slug: "does-expedited-engineering-change-the-fee",
    title: "Does Expedited Engineering Change the Fee? | Apex Grid",
    description: "Expedited engineering can change pricing when it requires schedule reprioritization, additional coordination, or review capacity, but availability and scope must be confirmed.",
    h1: "Does expedited engineering change the fee?",
    answer: "Expedited engineering may change the fee because the firm may need to reprioritize staff, coordinate concentrated reviews, work from incomplete information with added controls, or provide meetings and responses on a compressed schedule. It is not responsible to promise acceleration before checking the scope, records, decision-makers, and discipline availability. Any expedited arrangement should identify the actual deliverables, information deadline, review assumptions, communication path, and what remains outside the engineer's control. An accelerated design cannot shorten an AHJ queue or guarantee a permit decision.",
    topic: "Expedited engineering pricing",
    cluster: "Cost and pricing",
    serviceHref: "/services/mep",
  },
  {
    slug: "does-an-engineering-site-visit-change-the-fee",
    title: "Does an Engineering Site Visit Change the Fee? | Apex Grid",
    description: "A site visit may affect an engineering fee when observation, travel, measurements, testing, or field reporting is needed beyond the stated remote design scope.",
    h1: "Does an engineering site visit change the fee?",
    answer: "A site visit can affect an engineering fee when the proposal did not include travel, field observation, measurements, testing, access coordination, or a written site report. The need depends on the engineering question, reliability of existing records, concealed conditions, project risk, and the responsible engineer's ability to accept professional responsibility remotely. A visit is not a substitute for design analysis, and remote work is not automatically inadequate. The engineer should define the visit's purpose and deliverable; the AHJ decides whether an inspection, observation, or other evidence is required.",
    topic: "Site-visit pricing",
    cluster: "Cost and pricing",
    serviceHref: "/services/assessments",
  },
  {
    slug: "how-existing-conditions-affect-engineering-fees",
    title: "How Do Existing Conditions Affect Engineering Fees? | Apex Grid",
    description: "Existing conditions influence engineering fees through record quality, field verification, concealed construction, uncertainty, and the analysis needed to connect new work to what exists.",
    h1: "How do existing conditions affect engineering fees?",
    answer: "Existing conditions can affect fees because an engineer must determine what is actually present before relying on it in a design. Missing or conflicting drawings, concealed framing, undocumented utilities, distress, difficult access, and uncertain equipment information may require records research, field verification, testing, or additional analysis. A proposal should say which evidence the client supplies and what happens if it proves incomplete. The engineer decides whether the available evidence supports responsible design; the AHJ may request its own documentation or inspections.",
    topic: "Existing-condition engineering pricing",
    cluster: "Cost and pricing",
    serviceHref: "/services/structural",
  },
  {
    slug: "does-square-foot-pricing-work-for-engineering",
    title: "Does Square-Foot Pricing Work for Engineering? | Apex Grid",
    description: "Square-foot pricing can be a planning shorthand, but it cannot replace a scope-based engineering proposal because complexity and deliverables vary within the same area.",
    h1: "Does square-foot pricing work for engineering?",
    answer: "Square-foot pricing can provide a preliminary planning lens, but it is not a reliable substitute for a defined engineering scope. Buildings with the same area may differ in occupancy, structural systems, site constraints, equipment, energy requirements, existing-condition uncertainty, coordination, and permit deliverables. A responsible proposal ties the fee to professional tasks, assumptions, and documents rather than implying that area alone determines the work. The engineer must verify the project basis, and the AHJ—not a square-foot formula—sets the required submission.",
    topic: "Square-foot engineering pricing",
    cluster: "Cost and pricing",
    serviceHref: "/services/architecture",
  },
  {
    slug: "why-similar-engineering-projects-have-different-fees",
    title: "Why Do Similar Engineering Projects Have Different Fees? | Apex Grid",
    description: "Similar-looking projects can receive different engineering fees because their scope, records, risk, coordination, jurisdiction, deliverables, and commercial terms are not identical.",
    h1: "Why do similar engineering projects have different fees?",
    answer: "Similar project labels do not establish identical engineering scope. Fees can differ because of building configuration, occupancy, loads, existing-condition evidence, site access, utility or equipment information, number of disciplines, coordination needs, calculations, documentation, client review, revisions, schedule constraints, and the applicable AHJ process. Two proposals may also allocate permit support, testing, travel, and construction services differently. Ask each firm to explain assumptions and deliverables rather than treating a price difference as proof of quality; professional judgment and authority decisions remain project-specific.",
    topic: "Comparing fees for similar projects",
    cluster: "Cost and pricing",
    serviceHref: "/services/",
  },
  {
    slug: "what-is-a-budgetary-engineering-estimate",
    title: "What Is a Budgetary Engineering Estimate? | Apex Grid",
    description: "A budgetary engineering estimate is an early planning opinion based on limited project information, not a final fee proposal or a guarantee of total project cost.",
    h1: "What is a budgetary engineering estimate?",
    answer: "A budgetary engineering estimate is an early planning opinion about professional effort and likely scope before the project information is complete. It should identify the basis, maturity of the drawings, disciplines considered, assumptions, exclusions, uncertainty, and events that would require a detailed proposal. It is useful for comparing options or planning an authorization, but it is not a construction estimate, an agency fee quote, or a commitment to perform undefined work. The engineer can refine it as inputs improve; the owner, contractor, and AHJ each control different cost decisions.",
    topic: "Budgetary engineering estimates",
    cluster: "Cost and pricing",
    serviceHref: "/services/",
  },
  {
    slug: "how-multi-discipline-coordination-affects-engineering-fees",
    title: "How Does Multi-Discipline Coordination Affect Engineering Fees? | Apex Grid",
    description: "Multi-discipline coordination can affect engineering pricing through shared design decisions, interface reviews, meetings, clash resolution, and coordinated permit deliverables.",
    h1: "How does multi-discipline coordination affect engineering fees?",
    answer: "Multi-discipline coordination affects fees because structural, mechanical, electrical, plumbing, civil, architectural, and specialty decisions can change one another. The scope may include interface checks, shared backgrounds, equipment and penetration coordination, utility information, model or drawing reviews, meetings, and a coordinated submission set. A proposal should state which disciplines and parties are included, who owns each design decision, and how late changes are handled. Coordination does not merge professional responsibility: each responsible professional remains accountable for the work within their scope, while the AHJ reviews the package under its process.",
    topic: "Multi-discipline coordination pricing",
    cluster: "Cost and pricing",
    serviceHref: "/services/mep",
  },
  {
    slug: "should-construction-administration-be-included-in-engineering-pricing",
    title: "Should Construction Administration Be Included in Engineering Pricing? | Apex Grid",
    description: "Construction administration should be listed separately or clearly included so the owner knows whether engineering support covers submittals, RFIs, observations, and closeout.",
    h1: "Should construction administration be included in engineering pricing?",
    answer: "Construction administration should be identified explicitly in engineering pricing because it is different from design and permit documentation. The scope may include submittal review, responses to contractor questions, site observations, payment or progress input, substitution review, record-document support, or closeout assistance, each with its own limits and triggers. The engineer should state what is included, who requests the service, and how added visits or redesign are handled. Construction administration does not make the engineer the contractor or inspector, and neither role overrides the AHJ's inspection and approval authority.",
    topic: "Construction administration pricing",
    cluster: "Cost and pricing",
    serviceHref: "/services/structural",
  },
];