/** Project Type ecosystem — pages targeting what someone is doing to the building. */

export interface ProjectTypePage {
  slug: string;
  title: string;
  description: string;
  h1: string;
  kicker: string;
  lede: string;
  disciplines: string[];
  topics: string[];
  relatedSlugs: string[];
}

export const PROJECT_TYPE_PAGES: ProjectTypePage[] = [
  {
    slug: "new-construction",
    title: "Engineering for New Construction | Structural, MEP & Civil | Apex Grid",
    description: "Full-service structural, MEP, civil, and geotechnical engineering for new commercial construction — from schematic through permit-ready documents.",
    h1: "Engineering Services for New Construction",
    kicker: "New Construction Engineering",
    lede: "New construction projects require all engineering disciplines working in coordination — structural, MEP, civil, and geotechnical — to deliver a complete, permit-ready document set on schedule.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering", "Geotechnical Engineering"],
    topics: [
      "Foundation design based on geotechnical recommendations",
      "Structural framing — steel, concrete, wood, or CMU",
      "Lateral system design for seismic and wind",
      "MEP systems design — HVAC, electrical, plumbing",
      "Site civil engineering — grading, drainage, utilities",
      "Energy code compliance — ASHRAE 90.1, Title 24",
      "Permit drawings and calculations",
      "Plan check support and response",
    ],
    relatedSlugs: ["building-additions", "renovations", "tenant-improvements"],
  },
  {
    slug: "building-additions",
    title: "Engineering for Building Additions | Apex Grid Engineering",
    description: "Structural, MEP, and civil engineering for horizontal and vertical building additions — tied into existing structure and systems.",
    h1: "Engineering for Building Additions",
    kicker: "Building Addition Engineering",
    lede: "Building additions require engineering that addresses both what's new and what already exists — tying new foundations, framing, and systems into a structure that's already standing.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: [
      "Existing structure evaluation and capacity analysis",
      "New foundation design",
      "Structural tie-in at the addition interface",
      "HVAC expansion or new system for addition",
      "Electrical capacity evaluation and upgrade",
      "Plumbing extension and fixture addition",
      "Site grading and drainage for expanded footprint",
      "Permit documentation for combined existing and new scope",
    ],
    relatedSlugs: ["new-construction", "renovations", "existing-buildings"],
  },
  {
    slug: "renovations",
    title: "Building Renovation Engineering | Structural, MEP & Civil | Apex Grid",
    description: "Engineering for commercial building renovations — structural modifications, MEP system upgrades, and civil site improvements, permit-ready.",
    h1: "Engineering for Building Renovations",
    kicker: "Renovation Engineering",
    lede: "Renovation projects vary from simple interior updates to wholesale building transformations — but whenever structural or building systems are modified, engineering documentation is required for permit.",
    disciplines: ["Structural Engineering", "MEP Engineering"],
    topics: [
      "Existing condition assessment",
      "Structural modifications — wall removals, new openings, reinforcement",
      "MEP system replacement or upgrade",
      "Energy code compliance for altered systems",
      "Historic and older building engineering",
      "Occupied building phasing considerations",
      "Permit drawings and plan check coordination",
    ],
    relatedSlugs: ["tenant-improvements", "adaptive-reuse", "existing-buildings"],
  },
  {
    slug: "tenant-improvements",
    title: "Engineering for Tenant Improvement Projects | Apex Grid",
    description: "Structural, MEP, and engineering services for commercial tenant improvements — from small office fit-outs to complex healthcare and restaurant TIs.",
    h1: "Engineering for Tenant Improvement Projects",
    kicker: "Tenant Improvement Engineering",
    lede: "Commercial TIs are the most frequent driver of engineering permits. From a simple office renovation to a complex restaurant or medical build-out, we provide the structural and MEP engineering to get your TI permitted and built.",
    disciplines: ["Structural Engineering", "MEP Engineering"],
    topics: [
      "Structural scope identification — wall openings, new supports, equipment installation",
      "MEP engineering for new or modified systems",
      "Restaurant kitchen exhaust and make-up air",
      "Healthcare HVAC — pressure relationships, ventilation",
      "Electrical service evaluation and load calculations",
      "Energy code compliance documentation",
      "Fast turnaround for permit-driven schedules",
    ],
    relatedSlugs: ["renovations", "restaurant-build-outs", "new-construction"],
  },
  {
    slug: "adaptive-reuse",
    title: "Adaptive Reuse Engineering | Building Conversion | Apex Grid",
    description: "Structural and MEP engineering for adaptive reuse projects — converting existing buildings to new uses, including change of occupancy and code upgrades.",
    h1: "Adaptive Reuse Engineering",
    kicker: "Adaptive Reuse & Building Conversions",
    lede: "Adaptive reuse converts buildings from one use to another — warehouse to residential, office to medical, retail to fitness. Each conversion involves structural evaluation, MEP redesign, and code compliance analysis for the new occupancy.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: [
      "Change of occupancy analysis",
      "Existing structural system evaluation for new load requirements",
      "MEP system redesign for new occupancy",
      "Accessibility upgrades (ADA compliance)",
      "Seismic upgrade requirements for change of occupancy",
      "Energy code compliance for converted buildings",
      "Historic structure considerations",
      "Office to residential conversion",
      "Industrial to commercial conversion",
    ],
    relatedSlugs: ["change-of-occupancy", "renovations", "existing-buildings"],
  },
  {
    slug: "change-of-occupancy",
    title: "Engineering for Change-of-Occupancy Projects | Apex Grid",
    description: "Structural and MEP engineering for building change-of-occupancy projects — evaluating existing conditions against new use requirements.",
    h1: "Engineering for Change-of-Occupancy Projects",
    kicker: "Change of Occupancy Engineering",
    lede: "Changing a building's occupancy classification triggers code requirements for the new use — higher live loads, different ventilation rates, new accessibility requirements, and potentially seismic upgrades. Engineering analysis determines what's required.",
    disciplines: ["Structural Engineering", "MEP Engineering"],
    topics: [
      "Occupancy classification analysis under IBC",
      "Live load comparison — existing vs. new occupancy",
      "Structural adequacy evaluation for new loads",
      "MEP system evaluation for new ventilation and electrical requirements",
      "Accessible route and restroom compliance",
      "Egress analysis for new occupant load",
      "Sprinkler system evaluation (coordination with fire protection)",
    ],
    relatedSlugs: ["adaptive-reuse", "renovations", "existing-buildings"],
  },
  {
    slug: "building-retrofits",
    title: "Building Retrofit Engineering | Seismic & Structural | Apex Grid",
    description: "Structural retrofit engineering for existing buildings — seismic upgrades, code compliance retrofits, and structural strengthening.",
    h1: "Building Retrofit Engineering",
    kicker: "Structural & Seismic Retrofit Engineering",
    lede: "Building retrofits strengthen or upgrade existing structures to meet current code requirements or address identified deficiencies — most commonly for seismic resistance, but also for wind, gravity, and structural repair.",
    disciplines: ["Structural Engineering"],
    topics: [
      "Seismic deficiency identification",
      "Soft story and weak story retrofits",
      "Unreinforced masonry (URM) retrofits",
      "Concrete moment frame and shear wall upgrades",
      "Wood frame strengthening",
      "Foundation upgrades",
      "Connection and anchorage improvements",
      "California mandatory retrofit compliance",
      "ASCE 41 seismic evaluation methodology",
    ],
    relatedSlugs: ["existing-buildings", "seismic-design", "renovations"],
  },
  {
    slug: "capital-improvements",
    title: "Capital Improvement Engineering | Apex Grid Engineering",
    description: "Engineering for commercial building capital improvement programs — structural, MEP, and civil engineering for planned major repairs, replacements, and upgrades.",
    h1: "Capital Improvement Engineering",
    kicker: "Capital Improvement Program Engineering",
    lede: "Capital improvement programs require engineering documentation for budget planning, competitive bidding, permitting, and construction execution. We provide the engineering that makes capital projects happen on budget and on schedule.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: [
      "Capital needs assessment",
      "HVAC system replacement engineering",
      "Electrical system upgrade design",
      "Parking lot and site improvement engineering",
      "Roof structure evaluation and repair design",
      "Plumbing system replacement",
      "Accessibility upgrade engineering",
      "Energy efficiency upgrade documentation",
      "Permit documentation for capital scope",
    ],
    relatedSlugs: ["renovations", "existing-buildings", "equipment-replacement"],
  },
  {
    slug: "equipment-replacement",
    title: "Engineering for Equipment Replacement Projects | Apex Grid",
    description: "Structural and MEP engineering for mechanical, electrical, and industrial equipment replacement — structural support evaluation, permit documentation, and installation coordination.",
    h1: "Engineering for Equipment Replacement Projects",
    kicker: "Equipment Replacement Engineering",
    lede: "Equipment replacement projects — RTUs, generators, transformers, electrical panels, industrial equipment — require engineering to verify structural support capacity, design new mounting or anchorage, and produce permit documentation.",
    disciplines: ["Structural Engineering", "MEP Engineering"],
    topics: [
      "Rooftop unit (RTU) replacement engineering",
      "Generator installation — structural pad and anchorage",
      "Transformer replacement and electrical service upgrade",
      "Industrial equipment installation and anchorage",
      "Battery energy storage system structural support",
      "Solar PV mounting structure engineering",
      "Electrical load calculation for new equipment",
      "Permit drawings for mechanical equipment permits",
    ],
    relatedSlugs: ["existing-buildings", "capital-improvements", "renovations"],
  },
  {
    slug: "energy-upgrades",
    title: "Engineering for Building Energy Upgrades | Apex Grid",
    description: "MEP and structural engineering for commercial building energy upgrades — HVAC replacement, LED lighting, solar PV, battery storage, and energy compliance documentation.",
    h1: "Engineering for Building Energy Upgrades",
    kicker: "Energy Upgrade Engineering",
    lede: "Energy upgrade projects — from HVAC replacement to solar PV installation to LED lighting conversions — require engineering documentation for permit and professional engineering to ensure systems perform as intended.",
    disciplines: ["MEP Engineering", "Structural Engineering"],
    topics: [
      "HVAC system replacement and energy performance",
      "LED lighting upgrade engineering and photometrics",
      "Solar PV electrical interconnection engineering",
      "Battery energy storage electrical design",
      "EV charging infrastructure engineering",
      "Energy code compliance documentation",
      "Structural support for solar and battery systems",
      "Title 24, ASHRAE 90.1, and IECC compliance",
    ],
    relatedSlugs: ["equipment-replacement", "capital-improvements", "tenant-improvements"],
  },
  {
    slug: "site-expansions",
    title: "Engineering for Site Expansion Projects | Apex Grid",
    description: "Civil and structural engineering for commercial site expansions — parking, building footprints, utility extensions, and site drainage.",
    h1: "Engineering for Site Expansion Projects",
    kicker: "Site Expansion Engineering",
    lede: "Expanding a commercial site — adding parking, extending the building footprint, adding loading docks or drives, or expanding utility infrastructure — requires civil engineering and often structural engineering for new construction.",
    disciplines: ["Civil Engineering", "Structural Engineering", "Geotechnical Engineering"],
    topics: [
      "Site grading and drainage for expanded footprint",
      "Parking lot expansion design",
      "Utility extension — water, sewer, gas, electric",
      "Stormwater management for expanded impervious area",
      "New building foundations coordinated with existing",
      "Retaining walls for grade changes",
      "ADA accessibility for expanded site",
      "Permit engineering for site permit",
    ],
    relatedSlugs: ["new-construction", "parking-expansions", "capital-improvements"],
  },
  {
    slug: "parking-expansions",
    title: "Parking Lot Expansion Engineering | Apex Grid Engineering",
    description: "Civil engineering for parking lot expansion and reconstruction — grading, drainage, pavement design, stormwater, and ADA compliance.",
    h1: "Parking Lot Expansion Engineering",
    kicker: "Parking Civil Engineering",
    lede: "Parking lot expansions require civil engineering for grading, drainage, stormwater management, pavement design, ADA accessibility, and permit documentation.",
    disciplines: ["Civil Engineering", "Geotechnical Engineering"],
    topics: [
      "Grading design for positive drainage",
      "Stormwater detention and infiltration",
      "Pavement section design — asphalt or concrete",
      "Geotechnical recommendations for subgrade",
      "ADA accessible parking and routes",
      "Striping and signage design",
      "Site lighting coordination",
      "Utility coordination at parking areas",
    ],
    relatedSlugs: ["site-expansions", "civil-engineering", "capital-improvements"],
  },
];

export const PROJECT_TYPES_HUB = {
  title: "Engineering for Every Project Type | Apex Grid Engineering",
  description: "Structural, MEP, civil, and geotechnical engineering for new construction, additions, renovations, tenant improvements, retrofits, adaptive reuse, and capital improvements.",
  h1: "Engineering for Every Stage of a Building Project",
  lede: "Whether you're building from the ground up, renovating an existing building, or replacing aging systems — every stage of a building's life cycle involves engineering. We provide the right engineering for every project type.",
};
