/** Project Type ecosystem — pages targeting what someone is doing to the building. */

export interface ProjectTypePage {
  slug: string;
  title: string;
  description: string;
  h1: string;
  kicker: string;
  lede: string;
  disciplines: string[];
  topics: string[];
  relatedSlugs: string[];
  founderPerspective?: string;
  faqs?: { question: string; answer: string }[];
}

export const PROJECT_TYPE_PAGES: ProjectTypePage[] = [
  {
    slug: "new-construction",
    title: "Engineering for New Construction | Structural, MEP & Civil | Apex Grid",
    description: "Full-service structural, MEP, civil, and geotechnical engineering for new commercial construction — from schematic through permit-ready documents.",
    h1: "Engineering Services for New Construction",
    kicker: "New Construction Engineering",
    lede: "New construction projects require all engineering disciplines working in coordination — structural, MEP, civil, and geotechnical — to deliver a complete, permit-ready document set on schedule.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering", "Geotechnical Engineering"],
    topics: [
      "Foundation design based on geotechnical recommendations",
      "Structural framing — steel, concrete, wood, or CMU",
      "Lateral system design for seismic and wind",
      "MEP systems design — HVAC, electrical, plumbing",
      "Site civil engineering — grading, drainage, utilities",
      "Energy code compliance — ASHRAE 90.1, Title 24",
      "Permit drawings and calculations",
      "Plan check support and response",
    ],
    relatedSlugs: ["building-additions", "renovations", "tenant-improvements"],
  },
  {
    slug: "building-additions",
    title: "Engineering for Building Additions | Apex Grid Engineering",
    description: "Structural, MEP, and civil engineering for horizontal and vertical building additions — tied into existing structure and systems.",
    h1: "Engineering for Building Additions",
    kicker: "Building Addition Engineering",
    lede: "Building additions require engineering that addresses both what's new and what already exists — tying new foundations, framing, and systems into a structure that's already standing.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: [
      "Existing structure evaluation and capacity analysis",
      "New foundation design",
      "Structural tie-in at the addition interface",
      "HVAC expansion or new system for addition",
      "Electrical capacity evaluation and upgrade",
      "Plumbing extension and fixture addition",
      "Site grading and drainage for expanded footprint",
      "Permit documentation for combined existing and new scope",
    ],
    relatedSlugs: ["new-construction", "renovations", "existing-buildings"],
  },
  {
    slug: "renovations",
    title: "Building Renovation Engineering | Structural, MEP & Civil | Apex Grid",
    description: "Engineering for commercial building renovations — structural modifications, MEP system upgrades, and civil site improvements, permit-ready.",
    h1: "Engineering for Building Renovations",
    kicker: "Renovation Engineering",
    lede: "Renovation projects vary from simple interior updates to wholesale building transformations — but whenever structural or building systems are modified, engineering documentation is required for permit.",
    disciplines: ["Structural Engineering", "MEP Engineering"],
    topics: [
      "Existing condition assessment",
      "Structural modifications — wall removals, new openings, reinforcement",
      "MEP system replacement or upgrade",
      "Energy code compliance for altered systems",
      "Historic and older building engineering",
      "Occupied building phasing considerations",
      "Permit drawings and plan check coordination",
    ],
    relatedSlugs: ["tenant-improvements", "adaptive-reuse", "existing-buildings"],
  },
  {
    slug: "tenant-improvements",
    title: "Engineering for Tenant Improvement Projects | Apex Grid",
    description: "Structural, MEP, and engineering services for commercial tenant improvements — from small office fit-outs to complex healthcare and restaurant TIs.",
    h1: "Engineering for Tenant Improvement Projects",
    kicker: "Tenant Improvement Engineering",
    lede: "Commercial TIs are the most frequent driver of engineering permits. From a simple office renovation to a complex restaurant or medical build-out, we provide the structural and MEP engineering to get your TI permitted and built.",
    disciplines: ["Structural Engineering", "MEP Engineering"],
    topics: [
      "Structural scope identification — wall openings, new supports, equipment installation",
      "MEP engineering for new or modified systems",
      "Restaurant kitchen exhaust and make-up air",
      "Healthcare HVAC — pressure relationships, ventilation",
      "Electrical service evaluation and load calculations",
      "Energy code compliance documentation",
      "Fast turnaround for permit-driven schedules",
    ],
    relatedSlugs: ["renovations", "restaurant-build-outs", "new-construction"],
  },
  {
    slug: "adaptive-reuse",
    title: "Adaptive Reuse Engineering | Building Conversion | Apex Grid",
    description: "Structural and MEP engineering for adaptive reuse projects — converting existing buildings to new uses, including change of occupancy and code upgrades.",
    h1: "Adaptive Reuse Engineering",
    kicker: "Adaptive Reuse & Building Conversions",
    lede: "Adaptive reuse converts buildings from one use to another — warehouse to residential, office to medical, retail to fitness. Each conversion involves structural evaluation, MEP redesign, and code compliance analysis for the new occupancy.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: [
      "Change of occupancy analysis",
      "Existing structural system evaluation for new load requirements",
      "MEP system redesign for new occupancy",
      "Accessibility upgrades (ADA compliance)",
      "Seismic upgrade requirements for change of occupancy",
      "Energy code compliance for converted buildings",
      "Historic structure considerations",
      "Office to residential conversion",
      "Industrial to commercial conversion",
    ],
    relatedSlugs: ["change-of-occupancy", "renovations", "existing-buildings"],
  },
  {
    slug: "change-of-occupancy",
    title: "Engineering for Change-of-Occupancy Projects | Apex Grid",
    description: "Structural and MEP engineering for building change-of-occupancy projects — evaluating existing conditions against new use requirements.",
    h1: "Engineering for Change-of-Occupancy Projects",
    kicker: "Change of Occupancy Engineering",
    lede: "Changing a building's occupancy classification triggers code requirements for the new use — higher live loads, different ventilation rates, new accessibility requirements, and potentially seismic upgrades. Engineering analysis determines what's required.",
    disciplines: ["Structural Engineering", "MEP Engineering"],
    topics: [
      "Occupancy classification analysis under IBC",
      "Live load comparison — existing vs. new occupancy",
      "Structural adequacy evaluation for new loads",
      "MEP system evaluation for new ventilation and electrical requirements",
      "Accessible route and restroom compliance",
      "Egress analysis for new occupant load",
      "Sprinkler system evaluation (coordination with fire protection)",
    ],
    relatedSlugs: ["adaptive-reuse", "renovations", "existing-buildings"],
  },
  {
    slug: "building-retrofits",
    title: "Building Retrofit Engineering | Seismic & Structural | Apex Grid",
    description: "Structural retrofit engineering for existing buildings — seismic upgrades, code compliance retrofits, and structural strengthening.",
    h1: "Building Retrofit Engineering",
    kicker: "Structural & Seismic Retrofit Engineering",
    lede: "Building retrofits strengthen or upgrade existing structures to meet current code requirements or address identified deficiencies — most commonly for seismic resistance, but also for wind, gravity, and structural repair.",
    disciplines: ["Structural Engineering"],
    topics: [
      "Seismic deficiency identification",
      "Soft story and weak story retrofits",
      "Unreinforced masonry (URM) retrofits",
      "Concrete moment frame and shear wall upgrades",
      "Wood frame strengthening",
      "Foundation upgrades",
      "Connection and anchorage improvements",
      "California mandatory retrofit compliance",
      "ASCE 41 seismic evaluation methodology",
    ],
    relatedSlugs: ["existing-buildings", "seismic-design", "renovations"],
  },
  {
    slug: "capital-improvements",
    title: "Capital Improvement Engineering | Apex Grid Engineering",
    description: "Engineering for commercial building capital improvement programs — structural, MEP, and civil engineering for planned major repairs, replacements, and upgrades.",
    h1: "Capital Improvement Engineering",
    kicker: "Capital Improvement Program Engineering",
    lede: "Capital improvement programs require engineering documentation for budget planning, competitive bidding, permitting, and construction execution. We provide the engineering that makes capital projects happen on budget and on schedule.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: [
      "Capital needs assessment",
      "HVAC system replacement engineering",
      "Electrical system upgrade design",
      "Parking lot and site improvement engineering",
      "Roof structure evaluation and repair design",
      "Plumbing system replacement",
      "Accessibility upgrade engineering",
      "Energy efficiency upgrade documentation",
      "Permit documentation for capital scope",
    ],
    relatedSlugs: ["renovations", "existing-buildings", "equipment-replacement"],
  },
  {
    slug: "equipment-replacement",
    title: "Engineering for Equipment Replacement Projects | Apex Grid",
    description: "Structural and MEP engineering for mechanical, electrical, and industrial equipment replacement — structural support evaluation, permit documentation, and installation coordination.",
    h1: "Engineering for Equipment Replacement Projects",
    kicker: "Equipment Replacement Engineering",
    lede: "Equipment replacement projects — RTUs, generators, transformers, electrical panels, industrial equipment — require engineering to verify structural support capacity, design new mounting or anchorage, and produce permit documentation.",
    disciplines: ["Structural Engineering", "MEP Engineering"],
    topics: [
      "Rooftop unit (RTU) replacement engineering",
      "Generator installation — structural pad and anchorage",
      "Transformer replacement and electrical service upgrade",
      "Industrial equipment installation and anchorage",
      "Battery energy storage system structural support",
      "Solar PV mounting structure engineering",
      "Electrical load calculation for new equipment",
      "Permit drawings for mechanical equipment permits",
    ],
    relatedSlugs: ["existing-buildings", "capital-improvements", "renovations"],
  },
  {
    slug: "energy-upgrades",
    title: "Engineering for Building Energy Upgrades | Apex Grid",
    description: "MEP and structural engineering for commercial building energy upgrades — HVAC replacement, LED lighting, solar PV, battery storage, and energy compliance documentation.",
    h1: "Engineering for Building Energy Upgrades",
    kicker: "Energy Upgrade Engineering",
    lede: "Energy upgrade projects — from HVAC replacement to solar PV installation to LED lighting conversions — require engineering documentation for permit and professional engineering to ensure systems perform as intended.",
    disciplines: ["MEP Engineering", "Structural Engineering"],
    topics: [
      "HVAC system replacement and energy performance",
      "LED lighting upgrade engineering and photometrics",
      "Solar PV electrical interconnection engineering",
      "Battery energy storage electrical design",
      "EV charging infrastructure engineering",
      "Energy code compliance documentation",
      "Structural support for solar and battery systems",
      "Title 24, ASHRAE 90.1, and IECC compliance",
    ],
    relatedSlugs: ["equipment-replacement", "capital-improvements", "tenant-improvements"],
  },
  {
    slug: "facility-upgrades",
    title: "Facility Upgrade Engineering | Apex Grid",
    description: "Engineering for coordinated commercial facility upgrades, including existing-condition review, structural modifications, MEP changes, and permit documentation.",
    h1: "Engineering for Facility Upgrades",
    kicker: "Facility Upgrade Engineering",
    lede: "Facility upgrades can touch structure, HVAC, power, plumbing, site systems, and accessibility at the same time. A clear existing-condition baseline helps define what must be verified before design and permitting begin.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: ["Existing-condition and available-document review", "Upgrade scope and discipline interface definition", "Structural support for altered systems or equipment", "HVAC, electrical, and plumbing modifications", "Site utility and drainage coordination when affected", "Permit drawings, calculations, and response support"],
    relatedSlugs: ["capital-improvements", "equipment-replacement", "renovations"],
    founderPerspective: "I approach a facility upgrade by separating confirmed existing conditions from assumptions that still need field verification. That keeps the owner, design team, and permitting path aligned before multiple disciplines begin changing connected systems.",
    faqs: [
      { question: "What is included in facility upgrade engineering?", answer: "The scope may include existing-condition review, structural modifications, MEP changes, site coordination, calculations, and permit documents, depending on the systems affected." },
      { question: "Which disciplines may be involved?", answer: "Structural, mechanical, electrical, plumbing, and civil engineering may be involved when an upgrade crosses building and site systems." },
      { question: "Why are existing conditions reviewed first?", answer: "Existing documents and field conditions help the team identify available capacity, constraints, and information that must be verified before design." },
      { question: "Can one upgrade require several permit disciplines?", answer: "Yes. Equipment, occupancy, utility, or layout changes can create connected structural, MEP, civil, energy, or accessibility requirements." },
    ],
  },
  {
    slug: "accessibility-upgrades",
    title: "Accessibility Upgrade Engineering | Apex Grid",
    description: "Engineering support for commercial accessibility upgrades involving accessible routes, parking, ramps, structural changes, utilities, and permit coordination.",
    h1: "Engineering for Accessibility Upgrades",
    kicker: "Accessibility Upgrade Engineering",
    lede: "Accessibility upgrades often connect site grades, parking, routes, entrances, restrooms, and existing structural or MEP conditions. The engineering scope should follow the actual alteration and the applicable jurisdictional review.",
    disciplines: ["Civil Engineering", "Structural Engineering", "MEP Engineering"],
    topics: ["Accessible parking and route grading", "Ramp, landing, and entrance coordination", "Structural modifications for altered openings or supports", "Restroom plumbing and fixture coordination", "Site drainage at revised walks and ramps", "Permit documentation for the defined alteration"],
    relatedSlugs: ["renovations", "change-of-occupancy", "site-expansions"],
    founderPerspective: "I treat accessibility work as a connected path rather than a collection of isolated details. The route from parking or arrival through the building needs to be coordinated with grades, drainage, structure, doors, fixtures, and the jurisdiction’s review requirements.",
    faqs: [
      { question: "What can accessibility upgrade engineering include?", answer: "It can include accessible parking, route grading, ramps, entrances, structural modifications, restroom systems, drainage, and permit documentation." },
      { question: "Why can accessibility work involve civil engineering?", answer: "Exterior accessible routes depend on slopes, landings, curb transitions, drainage, and connections between parking and building entrances." },
      { question: "When might structural engineering be needed?", answer: "Structural review may be needed when an upgrade changes openings, stairs, ramps, landings, supports, or other load-carrying elements." },
      { question: "Are requirements the same for every project?", answer: "No. The applicable scope depends on the alteration, existing conditions, adopted requirements, and the authority having jurisdiction." },
    ],
  },
  {
    slug: "building-repairs",
    title: "Building Repair Engineering | Apex Grid",
    description: "Engineering for commercial building repairs, from condition verification and cause assessment through structural, MEP, civil, and permit repair documents.",
    h1: "Engineering for Building Repairs",
    kicker: "Building Repair Engineering",
    lede: "A repair design should begin with the observed condition, available records, and enough investigation to define the affected system. Engineering can then document a repair that responds to verified conditions rather than symptoms alone.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: ["Observed-condition documentation", "Available drawing and maintenance-record review", "Targeted investigation and engineering assessment", "Structural repair or reinforcement details", "MEP or site-system repair coordination", "Permit and construction repair documents"],
    relatedSlugs: ["renovations", "building-retrofits", "capital-improvements"],
    founderPerspective: "I want the repair scope tied to what has actually been observed and verified. When the cause or extent is uncertain, the right next step is targeted investigation—not unsupported certainty—before repair details are finalized.",
    faqs: [
      { question: "What information starts a building repair engineering scope?", answer: "Useful starting information includes photographs, observed symptoms, available drawings, maintenance history, prior reports, and access to the affected area." },
      { question: "Does an engineer always know the cause immediately?", answer: "No. Some conditions require field observation, testing, selective exposure, or specialist input before the cause and repair extent can be defined." },
      { question: "What disciplines can building repairs involve?", answer: "Repairs can involve structural, mechanical, electrical, plumbing, civil, geotechnical, or other specialists depending on the affected condition." },
      { question: "Can repair work require a permit?", answer: "Permit requirements vary by scope and jurisdiction. The authority having jurisdiction determines the required submittal and review." },
    ],
  },
  {
    slug: "code-compliance-upgrades",
    title: "Code Compliance Upgrade Engineering | Apex Grid",
    description: "Engineering support for defined commercial code-compliance upgrades involving existing conditions, structural and MEP changes, accessibility, and permits.",
    h1: "Engineering for Code Compliance Upgrades",
    kicker: "Code Compliance Upgrade Engineering",
    lede: "A code-compliance upgrade starts with a defined trigger, adopted requirements, and the existing condition. The engineering scope should document the changes needed for the specific project without implying that every building requires the same upgrades.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: ["Applicable-code and project-trigger review", "Existing-condition and occupancy documentation", "Structural or system capacity verification", "MEP and energy-related modifications", "Accessibility and site coordination when in scope", "Permit drawings and response documentation"],
    relatedSlugs: ["change-of-occupancy", "building-retrofits", "renovations"],
    founderPerspective: "I keep code-upgrade discussions tied to the adopted requirements, the project trigger, and the condition being altered. That avoids broad claims and gives the owner a traceable path from review comment or requirement to documented scope.",
    faqs: [
      { question: "What triggers a code-compliance upgrade?", answer: "Possible triggers include an alteration, change of occupancy, equipment replacement, permit review, adopted ordinance, or a documented existing condition." },
      { question: "Do all existing buildings need the same upgrades?", answer: "No. Requirements depend on the project scope, adopted codes, existing condition, occupancy, and jurisdictional interpretation." },
      { question: "What engineering disciplines may be involved?", answer: "Structural, MEP, civil, energy, accessibility, and fire-protection coordination may be involved depending on the cited requirement." },
      { question: "What documents are typically prepared?", answer: "The deliverables may include drawings, calculations, narratives, details, and written responses suited to the defined permit or review scope." },
    ],
  },
  {
    slug: "permit-corrections",
    title: "Permit Correction Engineering | Apex Grid",
    description: "Engineering support for commercial permit corrections, including comment review, scope clarification, revised drawings, calculations, and coordinated responses.",
    h1: "Engineering for Permit Corrections",
    kicker: "Permit Correction Engineering",
    lede: "Permit corrections are most effective when each agency comment is traced to the affected drawing, calculation, specification, or scope decision. Coordinated revisions help keep the response clear across disciplines.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: ["Plan-review comment log and responsibility assignment", "Existing submittal and calculation review", "Revised engineering drawings and details", "Updated calculations or narratives", "Cross-discipline revision coordination", "Written response package for resubmittal"],
    relatedSlugs: ["plan-check-responses", "tenant-improvements", "renovations"],
    founderPerspective: "I organize permit corrections comment by comment and keep the written response aligned with the revised documents. The goal is not to argue past the reviewer; it is to make the engineering basis and every resulting change easy to follow.",
    faqs: [
      { question: "What should be provided for a permit correction review?", answer: "Provide the complete agency comment letter, submitted drawings and calculations, available reviewer markups, project contacts, and the resubmittal schedule." },
      { question: "Can permit corrections involve multiple disciplines?", answer: "Yes. One comment cycle can affect architectural coordination, structural calculations, MEP drawings, civil plans, energy documents, or supporting narratives." },
      { question: "What does a coordinated response include?", answer: "A coordinated response typically identifies each comment, explains the action taken, and points to the matching revised sheet, detail, calculation, or document." },
      { question: "Does a correction response guarantee permit approval?", answer: "No. The authority having jurisdiction controls its review and approval. A clear response supports review but cannot guarantee the outcome." },
    ],
  },
  {
    slug: "plan-check-responses",
    title: "Plan Check Response Engineering | Apex Grid",
    description: "Engineering for commercial plan-check responses, with reviewer-comment analysis, revised drawings and calculations, response letters, and resubmittal coordination.",
    h1: "Engineering for Plan-Check Responses",
    kicker: "Plan-Check Response Engineering",
    lede: "A plan-check response should show exactly how each reviewer comment was addressed. That requires consistent revisions across drawings, calculations, narratives, and the formal response letter.",
    disciplines: ["Structural Engineering", "MEP Engineering", "Civil Engineering"],
    topics: ["Reviewer-comment interpretation", "Response matrix and discipline assignment", "Drawing, detail, and schedule revisions", "Calculation and narrative updates", "Response-letter preparation", "Resubmittal document coordination"],
    relatedSlugs: ["permit-corrections", "new-construction", "tenant-improvements"],
    founderPerspective: "I treat the response letter and revised engineering documents as one coordinated package. If a response says one thing while a sheet or calculation says another, the reviewer has to resolve that conflict; our job is to remove it before resubmittal.",
    faqs: [
      { question: "What is needed to start a plan-check response?", answer: "The team needs the full comment letter, the submitted drawing and calculation set, agency markups if available, and the current project schedule." },
      { question: "How are plan-check comments organized?", answer: "Comments are assigned by discipline, traced to affected documents, and answered in a response matrix or letter that references each revision." },
      { question: "Can one response require revised calculations?", answer: "Yes. Comments involving loads, capacities, sizing, compliance, or design criteria may require updated calculations or supporting narratives." },
      { question: "Who makes the final approval decision?", answer: "The authority having jurisdiction makes the final review and approval decision." },
    ],
  },
  {
    slug: "utility-upgrades",
    title: "Commercial Utility Upgrade Engineering | Apex Grid",
    description: "Civil and MEP engineering for commercial utility upgrades involving capacity review, service routing, site coordination, equipment, and permit documents.",
    h1: "Engineering for Commercial Utility Upgrades",
    kicker: "Utility Upgrade Engineering",
    lede: "Utility upgrades require coordination between the property, serving utility, site conditions, building systems, and permitting authority. The scope begins by defining demand, available capacity, routing, and required points of connection.",
    disciplines: ["Civil Engineering", "Electrical Engineering", "Plumbing Engineering", "Mechanical Engineering"],
    topics: ["Existing service and available-capacity review", "Serving-utility coordination", "Water, sewer, gas, and electrical routing", "Service equipment and point-of-connection design", "Trenching, grading, and site-restoration coordination", "Permit drawings and supporting calculations"],
    relatedSlugs: ["site-expansions", "facility-upgrades", "equipment-replacement"],
    founderPerspective: "I start utility-upgrade work by separating what the serving utility controls from what the project team controls. Clear demand, capacity, connection, routing, and site-restoration responsibilities help prevent gaps between civil plans and building-system design.",
    faqs: [
      { question: "What information is needed for a utility upgrade?", answer: "Useful inputs include existing utility records, proposed loads or demands, site plans, service locations, serving-utility requirements, and available survey information." },
      { question: "Which utilities can be part of the scope?", answer: "The scope may include electrical, water, sewer, gas, communications coordination, or other site services depending on the project." },
      { question: "Why is serving-utility coordination important?", answer: "The serving utility may control capacity confirmation, connection requirements, metering, equipment, routing constraints, and portions of the approval process." },
      { question: "Can utility upgrades affect both civil and MEP drawings?", answer: "Yes. Exterior routing and grading must coordinate with building service equipment, loads, piping, conductors, and points of connection." },
    ],
  },
  {
    slug: "site-expansions",
    title: "Engineering for Site Expansion Projects | Apex Grid",
    description: "Civil and structural engineering for commercial site expansions — parking, building footprints, utility extensions, and site drainage.",
    h1: "Engineering for Site Expansion Projects",
    kicker: "Site Expansion Engineering",
    lede: "Expanding a commercial site — adding parking, extending the building footprint, adding loading docks or drives, or expanding utility infrastructure — requires civil engineering and often structural engineering for new construction.",
    disciplines: ["Civil Engineering", "Structural Engineering", "Geotechnical Engineering"],
    topics: [
      "Site grading and drainage for expanded footprint",
      "Parking lot expansion design",
      "Utility extension — water, sewer, gas, electric",
      "Stormwater management for expanded impervious area",
      "New building foundations coordinated with existing",
      "Retaining walls for grade changes",
      "ADA accessibility for expanded site",
      "Permit engineering for site permit",
    ],
    relatedSlugs: ["new-construction", "parking-expansions", "capital-improvements"],
  },
  {
    slug: "parking-expansions",
    title: "Parking Lot Expansion Engineering | Apex Grid Engineering",
    description: "Civil engineering for parking lot expansion and reconstruction — grading, drainage, pavement design, stormwater, and ADA compliance.",
    h1: "Parking Lot Expansion Engineering",
    kicker: "Parking Civil Engineering",
    lede: "Parking lot expansions require civil engineering for grading, drainage, stormwater management, pavement design, ADA accessibility, and permit documentation.",
    disciplines: ["Civil Engineering", "Geotechnical Engineering"],
    topics: [
      "Grading design for positive drainage",
      "Stormwater detention and infiltration",
      "Pavement section design — asphalt or concrete",
      "Geotechnical recommendations for subgrade",
      "ADA accessible parking and routes",
      "Striping and signage design",
      "Site lighting coordination",
      "Utility coordination at parking areas",
    ],
    relatedSlugs: ["site-expansions", "civil-engineering", "capital-improvements"],
  },
];

export const PROJECT_TYPES_HUB = {
  title: "Engineering for Every Project Type | Apex Grid Engineering",
  description: "Structural, MEP, civil, and geotechnical engineering for new construction, additions, renovations, tenant improvements, retrofits, adaptive reuse, and capital improvements.",
  h1: "Engineering for Every Stage of a Building Project",
  lede: "Whether you're building from the ground up, renovating an existing building, or replacing aging systems — every stage of a building's life cycle involves engineering. We provide the right engineering for every project type.",
};
