import type { Phase0AeoPage } from "./phase0-corpus";

const founderNote = "I'm Jeremy Mills, CEO & Founder of Apex Grid Engineering and a U.S. Air Force veteran. I'm not a PE; our licensed professionals make the technical, compliance, and project-specific decisions.";

export const WAVE_IS_B62_ANSWER_PAGES: Phase0AeoPage[] = [
  {
    slug: "what-drawings-need-engineer-stamp-kentucky",
    title: "What Drawings Need an Engineer Stamp for Kentucky Permits?",
    description: "Which Kentucky drawings need a PE stamp? Structural, MEP, and civil sets explained, plus Louisville review rules, karst soil notes, and seismic triggers.",
    h1: "What Drawings Need an Engineer Stamp for Kentucky Permits?",
    answer: "The answer: In Kentucky, structural drawings, commercial MEP drawings, and civil site drawings need a Kentucky-licensed PE stamp before the building department will issue a permit. That means foundation and framing plans, the lateral-force-resisting system, HVAC, electrical, and plumbing drawings for commercial projects, plus grading, drainage, stormwater, and erosion-control plans. The stamp must come from a professional engineer licensed by the Kentucky Board of Licensure for Professional Engineers and Land Surveyors who exercised responsible charge over the design — an out-of-state engineer must obtain Kentucky licensure by comity before sealing a single sheet.\n\nThe structural set is the heart of the stamped package. It includes the foundation plan with footing schedules, floor and roof framing plans, structural sections and details, connection schedules, and the lateral system drawings showing how wind and seismic forces travel to the foundation. The mechanical set carries the HVAC plans with equipment schedules and load calculations; the electrical set carries power and lighting plans with panel schedules and load calculations; the plumbing set carries the sanitary, storm, and domestic water plans with riser diagrams. The civil set covers the site plan, grading, stormwater management, and erosion control. Energy code compliance documentation rides with the permit set, and specialty components — steel connections, wood trusses, curtain wall, fire suppression — arrive as separately sealed deferred submittals.\n\nKentucky's triggers go beyond the code book. Louisville Metro's Department of Codes and Regulations runs the state's largest plan review, and Lexington-Fayette Urban County Government runs the second; both expect fully coordinated, sealed sets and will hold a permit over a missing discipline. Central Kentucky's karst topography — sinkhole-prone limestone — means foundation drawings in the Bluegrass region are reviewed against a geotechnical investigation that addresses voids and soil loss. Eastern Kentucky's historic coal mining adds mine-subsidence review in affected counties. And far western Kentucky around Paducah sits in the New Madrid seismic zone, so structural drawings there must show the seismic design category and the detailing it requires.\n\nThe gray areas are real. Conventional one- and two-family homes built to the Kentucky Residential Code often do not require an engineer stamp — but the building official can demand one for unusual spans, tall retaining walls, steep slopes, or karst sites, and many Kentucky jurisdictions do. Agricultural buildings are exempt in some counties and not in others. Anything marked preliminary or not-for-construction cannot be permitted or built from. When in doubt, the authority having jurisdiction answers the question before design starts, not at the permit counter.",
    directAnswer: "Kentucky requires a Kentucky-licensed PE in responsible charge to stamp structural, commercial MEP, and civil site drawings. Louisville Metro and Lexington-Fayette run the major reviews, karst soils shape Bluegrass foundations, and far western Kentucky adds New Madrid seismic detailing requirements.",
    topic: "PE Stamping by State",
    serviceHref: "/services/structural/",
    sections: [
      {
        heading: "Drawing Sets That Require a Stamp in Kentucky",
        body: "The stamped package in Kentucky breaks into four drawing sets, and the building department expects each one sealed by the Kentucky-licensed engineer who controlled it. The structural set — foundation plan, framing plans, sections, details, and the lateral system — is sealed by the structural engineer of record. The mechanical, electrical, and plumbing sets are sealed by the licensed engineers responsible for each discipline, with calculations to back them: HVAC load calculations, electrical load calculations and panel schedules, plumbing fixture counts and riser diagrams. The civil set — site, grading, drainage, stormwater, erosion control — is sealed by the civil engineer of record. Apex Grid Engineering assigns Kentucky-licensed engineers as engineers of record for each discipline, so every seal on your Kentucky set belongs to the licensed professional who directed that work.\n\nDeferred submittals deserve their own mention because they surprise owners. Steel connection design, pre-engineered wood trusses, curtain wall systems, and fire suppression shop drawings are typically designed by the supplier's engineer after the permit is issued — and each arrives as its own sealed submittal for the building official's review. The structural drawings must reference the design criteria those deferred engineers will use, so the deferred seals and the engineer-of-record seals tell one consistent story at final inspection.",
      },
      {
        heading: "Kentucky-Specific Stamp Triggers",
        body: "Louisville Metro's consolidated city-county government runs Kentucky's highest-volume plan review through its Department of Codes and Regulations, and a commercial set there is checked discipline by discipline — architecture, structure, MEP, civil — with corrections issued per discipline. Lexington-Fayette's Urban County Government runs the Bluegrass market with its own review culture and local amendments. Both jurisdictions will stop a permit over an unsealed or improperly sealed sheet, and both check the Kentucky license status of the sealing engineer.\n\nThe ground itself triggers engineering in Kentucky. The Bluegrass region's karst limestone creates sinkhole and void risk that the geotechnical investigation must address, and the foundation drawings must reflect the investigation's recommendations — the plan reviewer checks that link. In eastern Kentucky's coal country, mine subsidence maps can trigger additional foundation review. In far western Kentucky, the New Madrid seismic zone raises the seismic design category, and the structural drawings must show the category, the lateral system, and the seismic detailing. State-owned and school projects add another layer: Kentucky's Division of Building Code Enforcement reviews state buildings under the Kentucky Building Code, a separate track from the local permit.",
      },
      {
        heading: "Kentucky Drawing Checklist Before Sealing",
        body: "Use this checklist before your Kentucky permit set is sealed:\n\n• Engineer of record for each discipline holds an active Kentucky PE license, verifiable on the board roster\n• Seal shows name, Kentucky license number, and date on every sealed sheet\n• Structural set complete: foundation plan, framing plans, sections, details, lateral system drawings\n• MEP sets include load calculations, equipment and panel schedules, and riser diagrams\n• Civil set covers site, grading, stormwater management, and erosion control\n• Karst regions: geotechnical report addresses voids and the foundation follows its recommendations\n• Far western Kentucky: seismic design category and seismic detailing shown on the structural drawings\n• Authority having jurisdiction confirmed: Louisville Metro, Lexington-Fayette, or the local building department",
      },
    ],
    faqs: [
      {
        question: "Do house plans need an engineer stamp in Kentucky?",
        answer: "Not always. Conventional one- and two-family homes designed within the prescriptive limits of the Kentucky Residential Code typically do not require a PE stamp. But the building official can require engineered drawings for long spans, unusual structural systems, steep slopes, retaining walls, or karst sites — and many Kentucky jurisdictions ask for an engineer on residential work more often than owners expect.",
      },
      {
        question: "What is karst and why does it affect Kentucky foundations?",
        answer: "Karst is the sinkhole-prone limestone terrain underlying much of central Kentucky, including the Lexington-Bluegrass region. Dissolving limestone creates voids and sudden soil loss that can undermine foundations. The geotechnical investigation must characterize the karst risk, and the foundation drawings must reflect the investigation's recommendations — the plan reviewer verifies that the two match.",
      },
      {
        question: "Does the New Madrid seismic zone reach Kentucky?",
        answer: "Yes, in the far west. The New Madrid seismic zone extends into western Kentucky around Paducah, raising the seismic design category for structures there. Structural drawings in that region must show the seismic design category, the lateral-force-resisting system, and the seismic detailing the category requires. The rest of Kentucky designs to lower seismic demands, but the drawings still state the category.",
      },
      {
        question: "Can an out-of-state engineer stamp my Kentucky drawings?",
        answer: "Only after obtaining Kentucky licensure. Kentucky offers comity licensure for engineers licensed in other states who meet the qualifications, but the stamp cannot go on Kentucky drawings until the Kentucky license is active. Working under a Kentucky-licensed engineer in responsible charge is the compliant path while comity is pending.",
      },
    ],
    extraLinks: [
      { label: "How is the plan check corrections process explained?", href: "/answers/plan-check-corrections-process-explained/" },
      { label: "How are someone else's drawings stamped?", href: "/answers/engineer-stamping-someone-elses-drawings/" },
      { label: "How does a digital PE seal compare to a wet seal?", href: "/answers/digital-vs-wet-pe-seal/" },
      { label: "Get an engineering estimate", href: "/estimate" },
    ],
    founderNote,
  },
  {
    slug: "what-drawings-need-engineer-stamp-tennessee",
    title: "What Drawings Need an Engineer Stamp for Tennessee Projects?",
    description: "Which Tennessee drawings need a PE stamp? Structural, MEP, and civil sets explained, plus Nashville review rules and Memphis corridor seismic drawing notes.",
    h1: "What Drawings Need an Engineer Stamp for Tennessee Projects?",
    answer: "The answer: In Tennessee, structural drawings, commercial MEP drawings, and civil site drawings need a Tennessee-licensed PE stamp before the building department will issue a permit. That covers foundation and framing plans, the lateral-force-resisting system, HVAC, electrical, and plumbing drawings for commercial work, plus grading, drainage, stormwater, and erosion-control plans. The stamp must come from a professional engineer licensed by the Tennessee Board of Architectural and Engineering Examiners who exercised responsible charge over the design — an out-of-state engineer must obtain Tennessee licensure by comity before sealing.\n\nThe structural set anchors the package: foundation plan with footing and pier schedules, floor and roof framing plans, structural sections and details, connection schedules, and the lateral system drawings tracing wind and seismic forces to the foundation. The mechanical set includes HVAC plans with equipment schedules and load calculations; the electrical set includes power and lighting plans with panel schedules and load calculations; the plumbing set includes sanitary, storm, and water plans with riser diagrams. The civil set covers the site plan, grading, stormwater management, and erosion control. Energy code compliance documentation accompanies the permit set, and specialty systems — steel connections, wood trusses, curtain wall — arrive as separately sealed deferred submittals reviewed after permit issuance.\n\nTennessee's two big corridors set the review reality. Metro Nashville's Department of Codes and Building Safety runs the state's largest plan review with published submittal checklists, and Memphis and Shelby County's Office of Construction Code Enforcement runs the western market. The defining Tennessee trigger is seismic: Memphis sits in the New Madrid seismic zone with some of the highest seismic design categories east of the Rockies, so structural drawings for the Memphis corridor must show the seismic design category, the lateral system, and the seismic detailing — and the geotechnical investigation must address liquefaction where the maps indicate it. Middle and east Tennessee design to lower seismic demands, but the category still appears on the drawings. State and school projects can add Tennessee State Fire Marshal review on top of the local permit.\n\nThe gray areas follow the national pattern with Tennessee accents. Conventional homes under the residential code often avoid the engineer stamp, but Tennessee building officials routinely require engineered drawings for hillside construction around Nashville, long spans, and retaining walls. Agricultural buildings carry exemptions that vary by county. Preliminary drawings marked not-for-construction cannot be permitted. The authority having jurisdiction decides the edge cases — confirm before design, not at the counter.",
    directAnswer: "Tennessee requires a Tennessee-licensed PE in responsible charge to stamp structural, commercial MEP, and civil site drawings. Nashville and Memphis run the major reviews, and the Memphis corridor's New Madrid seismic demands — including liquefaction review — shape the structural set.",
    topic: "PE Stamping by State",
    serviceHref: "/services/structural/",
    sections: [
      {
        heading: "Drawing Sets That Require a Stamp in Tennessee",
        body: "Tennessee's stamped package divides into four sets, each sealed by the Tennessee-licensed engineer who controlled it. The structural set — foundation plan, framing plans, sections, details, lateral system — is sealed by the structural engineer of record with the seismic design category stated on the cover sheet. The mechanical, electrical, and plumbing sets are sealed by their respective licensed engineers, backed by load calculations, equipment and panel schedules, and riser diagrams. The civil set — site, grading, drainage, stormwater, erosion control — is sealed by the civil engineer of record. Apex Grid Engineering assigns Tennessee-licensed engineers as engineers of record for each discipline, so every seal on your Tennessee set belongs to the licensed professional who directed that work.\n\nDeferred submittals complete the picture. Steel connection engineering, pre-engineered trusses, curtain wall, and fire protection shop drawings are typically sealed by the supplier's engineer after the building permit issues, and the building official reviews each deferred submittal against the design criteria stated on the engineer-of-record drawings. Coordinating those criteria up front — loads, deflections, connection forces — keeps the deferred seals consistent with the permitted set and avoids rework at final inspection.",
      },
      {
        heading: "Tennessee-Specific Stamp Triggers",
        body: "Nashville's growth has made Metro Codes one of the busiest review departments in the Southeast, and its published checklists make the expectations explicit: sealed structural, MEP, and civil sets, coordinated across disciplines, with energy compliance documented. Memphis and Shelby County's review adds the seismic dimension — the New Madrid zone gives the Memphis corridor high seismic design categories, and reviewers there look first for the seismic parameters, the lateral system, and the detailing on the structural drawings. The geotechnical investigation in the Memphis area must address liquefaction and the Mississippi River alluvial soils, and the foundation design must reflect the report.\n\nMiddle Tennessee brings its own ground conditions: the Nashville Basin's expansive clays and shallow limestone shape foundation choices, and hillside development around the city triggers geotechnical and retaining-wall review. East Tennessee's terrain — Knoxville, Chattanooga — adds slope and rock excavation considerations to the civil set. Tornado-resistant design enters the conversation statewide: Tennessee's tornado history makes storm shelter and safe-room provisions a common owner request, and ICC 500 safe-room drawings are sealed structural work when included.",
      },
      {
        heading: "Tennessee Drawing Checklist Before Sealing",
        body: "Use this checklist before your Tennessee permit set is sealed:\n\n• Engineer of record for each discipline holds an active Tennessee PE license, verifiable on the board roster\n• Seal shows name, Tennessee license number, and date on every sealed sheet\n• Structural set complete: foundation plan, framing plans, sections, details, lateral system drawings\n• Seismic design category stated on the structural cover sheet for every project\n• Memphis corridor: liquefaction addressed in the geotechnical report and reflected in the foundation design\n• MEP sets include load calculations, schedules, and riser diagrams\n• Civil set covers site, grading, stormwater management, and erosion control\n• Authority having jurisdiction confirmed: Metro Nashville, Memphis/Shelby County, or the local building department",
      },
    ],
    faqs: [
      {
        question: "Why is seismic design such a big deal in Memphis?",
        answer: "Memphis sits in the New Madrid seismic zone, one of the highest seismic hazard areas in the central and eastern United States. The seismic design categories there drive the lateral system selection, the structural detailing, and the geotechnical investigation — including liquefaction analysis for the alluvial soils. The plan reviewer checks the seismic parameters on the structural cover sheet first.",
      },
      {
        question: "Do Nashville homes need an engineer stamp?",
        answer: "Conventional homes within the residential code's prescriptive limits often do not. But Nashville-area building officials commonly require engineered drawings for hillside lots, long spans, tall retaining walls, and additions that change the structural system. The hillside terrain around Nashville makes geotechnical and structural review more frequent than in flat markets.",
      },
      {
        question: "What is a deferred submittal in Tennessee?",
        answer: "A deferred submittal is a portion of the design — steel connections, wood trusses, curtain wall, fire suppression — submitted and sealed after the building permit is issued, typically by the supplier's engineer. The building official reviews it against the design criteria on the engineer-of-record drawings. Deferred does not mean unreviewed; each deferred seal gets its own plan check.",
      },
      {
        question: "Can an out-of-state engineer stamp my Tennessee drawings?",
        answer: "Only after obtaining Tennessee licensure. Tennessee offers comity for engineers licensed in other states who meet the qualifications, but the stamp cannot go on Tennessee drawings until the Tennessee license is active. Working under a Tennessee-licensed engineer in responsible charge is the compliant interim path.",
      },
    ],
    extraLinks: [
      { label: "How are seismic design categories explained?", href: "/answers/seismic-design-categories-explained/" },
      { label: "How is the plan check corrections process explained?", href: "/answers/plan-check-corrections-process-explained/" },
      { label: "How are deferred submittals explained?", href: "/answers/deferred-submittals-explained/" },
      { label: "Get an engineering estimate", href: "/estimate" },
    ],
    founderNote,
  },
  {
    slug: "what-drawings-need-engineer-stamp-alabama",
    title: "What Drawings Need an Engineer Stamp for Alabama Permits?",
    description: "Which Alabama drawings need a PE stamp? Structural, MEP, and civil sets explained, plus Gulf Coast wind rules, flood elevation notes, and tornado shelter plans.",
    h1: "What Drawings Need an Engineer Stamp for Alabama Permits?",
    answer: "The answer: In Alabama, structural drawings, commercial MEP drawings, and civil site drawings need an Alabama-licensed PE stamp before the building department will issue a permit. That covers foundation and framing plans, the lateral-force-resisting system, HVAC, electrical, and plumbing drawings for commercial projects, plus grading, drainage, stormwater, and erosion-control plans. The stamp must come from a professional engineer licensed by the Alabama Board of Licensure for Professional Engineers and Land Surveyors who exercised responsible charge over the design — an out-of-state engineer must obtain Alabama licensure by comity before sealing.\n\nThe structural set is the core: foundation plan with footing schedules, floor and roof framing plans, structural sections and details, connection schedules, and lateral system drawings showing the wind and seismic load paths. The mechanical set carries HVAC plans with equipment schedules and load calculations; the electrical set carries power and lighting plans with panel schedules and load calculations; the plumbing set carries sanitary, storm, and water plans with riser diagrams. The civil set covers the site plan, grading, stormwater management, and erosion control. Energy code compliance documentation accompanies the permit set, and specialty components — steel connections, trusses, curtain wall — arrive as separately sealed deferred submittals.\n\nAlabama's triggers split between the coast and the interior. Along the Gulf Coast — Mobile, Baldwin County, the beach communities — the ASCE 7 wind speed maps and wind-borne debris provisions govern the structural drawings: design wind speeds, exposure categories, and impact-resistant glazing or protection for openings. FEMA flood zones across the coastal counties add finished-floor elevations, flood-resistant materials, and elevation certificates to the drawing package. Inland, north Alabama sits in tornado alley — Birmingham, Huntsville, Tuscaloosa — where owners increasingly request ICC 500 storm shelters, and shelter drawings are sealed structural work. The Alabama Building Commission administers the state building code for state-owned buildings, while cities and counties adopt their own code editions locally, so the Birmingham reviewer and the Mobile reviewer may be enforcing different amendments.\n\nThe gray areas matter in Alabama's smaller jurisdictions. Conventional residential construction under the residential code often proceeds without an engineer stamp, but building officials can require engineered drawings for unusual conditions — and coastal floodplain administrators routinely do for elevated construction. Agricultural exemptions vary by county. Marking a set preliminary or not-for-construction keeps it out of the permit stream. Confirm the local authority having jurisdiction early, because Alabama's local-adoption model means the rules genuinely change at the county line.",
    directAnswer: "Alabama requires an Alabama-licensed PE in responsible charge to stamp structural, commercial MEP, and civil site drawings. Gulf Coast wind and flood zones shape coastal sets, tornado shelters are common inland, and each city or county enforces its own adopted code edition.",
    topic: "PE Stamping by State",
    serviceHref: "/services/structural/",
    sections: [
      {
        heading: "Drawing Sets That Require a Stamp in Alabama",
        body: "Alabama's stamped package divides into four sets, each sealed by the Alabama-licensed engineer who controlled it. The structural set — foundation plan, framing plans, sections, details, lateral system — is sealed by the structural engineer of record, with the design wind speed, exposure category, and seismic design category stated on the cover sheet. The mechanical, electrical, and plumbing sets are sealed by their respective licensed engineers with load calculations, equipment and panel schedules, and riser diagrams. The civil set — site, grading, drainage, stormwater, erosion control — is sealed by the civil engineer of record. Apex Grid Engineering assigns Alabama-licensed engineers as engineers of record for each discipline, so every seal on your Alabama set belongs to the licensed professional who directed that work.\n\nDeferred submittals round out the package. Steel connection design, pre-engineered trusses, curtain wall systems, and fire suppression shop drawings are typically sealed by the supplier's engineer after permit issuance and reviewed by the building official against the criteria on the engineer-of-record drawings. On the Gulf Coast, the deferred package often includes the window and door product approvals for wind-borne debris compliance — the reviewer verifies each product against the listed approvals, so the approvals must be current and correctly referenced on the drawings.",
      },
      {
        heading: "Alabama-Specific Stamp Triggers",
        body: "The Gulf Coast defines Alabama's most demanding drawing requirements. Mobile and Baldwin County enforce the wind-borne debris region provisions: the structural drawings show the ultimate design wind speed, the exposure category, and the components-and-cladding pressures, and openings are impact-resistant or protected by shutters. FEMA flood zones blanket the coastal counties, so the architectural and structural drawings show the base flood elevation, the finished floor elevation with freeboard, flood-resistant materials below the flood level, and breakaway wall details where applicable — the floodplain administrator reviews these alongside the building plan check.\n\nInland, the triggers shift. North Alabama's tornado history — including the 2011 Super Outbreak — has made storm shelters a standard consideration for schools, public buildings, and many commercial projects; ICC 500 shelter drawings carry a structural seal and their own review. The Alabama Building Commission's state building code applies to state-owned buildings and schools, a separate track from the municipal permit. And because Alabama leaves code adoption to local governments, the applicable edition and amendments genuinely vary: Birmingham, Huntsville, Montgomery, and Mobile each run their own review, and unincorporated county areas may have minimal or no building department — the engineer confirms the authority having jurisdiction before drawing.",
      },
      {
        heading: "Alabama Drawing Checklist Before Sealing",
        body: "Use this checklist before your Alabama permit set is sealed:\n\n• Engineer of record for each discipline holds an active Alabama PE license, verifiable on the board roster\n• Seal shows name, Alabama license number, and date on every sealed sheet\n• Structural set complete: foundation plan, framing plans, sections, details, lateral system drawings\n• Design wind speed, exposure category, and seismic design category on the structural cover sheet\n• Gulf Coast: wind-borne debris protection detailed and product approvals current and referenced\n• Flood zones: base flood elevation, finished floor elevation, and flood-resistant construction documented\n• MEP sets include load calculations, schedules, and riser diagrams\n• Authority having jurisdiction and its adopted code edition confirmed: city, county, or state track",
      },
    ],
    faqs: [
      {
        question: "What is the wind-borne debris region in Alabama?",
        answer: "It is the coastal area — including Mobile and Baldwin counties — where the building code requires openings to resist wind-borne debris from hurricanes. Windows and doors must be impact-resistant or protected by shutters, and the structural drawings show the design wind speed and the protection method for every opening. The plan reviewer verifies the products against their approvals.",
      },
      {
        question: "Do Alabama storm shelters need engineered drawings?",
        answer: "Yes. A storm shelter designed to ICC 500 is structural life-safety work and must be designed and sealed by a licensed engineer. Alabama's tornado history makes shelters common in schools and public buildings, and the shelter drawings — walls, roof, doors, anchorage, ventilation — go through plan review like any other structural system.",
      },
      {
        question: "Does Alabama have a statewide building code?",
        answer: "For private construction, effectively no — Alabama leaves building code adoption to cities and counties, so the enforced edition and amendments vary by jurisdiction. The Alabama Building Commission administers the state building code for state-owned buildings. Your engineer confirms which code and amendments the local authority having jurisdiction enforces before design begins.",
      },
      {
        question: "Can an out-of-state engineer stamp my Alabama drawings?",
        answer: "Only after obtaining Alabama licensure. Alabama offers comity for engineers licensed in other states who meet the qualifications, but the stamp cannot go on Alabama drawings until the Alabama license is active. Working under an Alabama-licensed engineer in responsible charge is the compliant interim path.",
      },
    ],
    extraLinks: [
      { label: "How is hurricane glazing designed?", href: "/answers/hurricane-glazing-design/" },
      { label: "How is flood-resistant design done per ASCE 24?", href: "/answers/asce-24-flood-resistant-design/" },
      { label: "What are Alabama's hurricane and tornado engineering requirements?", href: "/answers/alabama-hurricane-tornado-engineering-requirements/" },
      { label: "Get an engineering estimate", href: "/estimate" },
    ],
    founderNote,
  },
  {
    slug: "what-drawings-need-engineer-stamp-mississippi",
    title: "What Drawings Need an Engineer Stamp for Mississippi Permits?",
    description: "Which Mississippi drawings need a PE stamp? Structural, MEP, and civil sets explained, plus Gulf Coast flood rules, elevation certificates, and freeboard notes.",
    h1: "What Drawings Need an Engineer Stamp for Mississippi Permits?",
    answer: "The answer: In Mississippi, structural drawings, commercial MEP drawings, and civil site drawings need a Mississippi-licensed PE stamp before the building department will issue a permit. That covers foundation and framing plans, the lateral-force-resisting system, HVAC, electrical, and plumbing drawings for commercial projects, plus grading, drainage, stormwater, and erosion-control plans. The stamp must come from a professional engineer licensed by the Mississippi State Board of Registration for Professional Engineers and Surveyors who exercised responsible charge over the design — an out-of-state engineer must obtain Mississippi licensure by comity before sealing.\n\nThe structural set carries the package: foundation plan with footing schedules, floor and roof framing plans, structural sections and details, connection schedules, and lateral system drawings tracing wind and seismic loads to the foundation. The mechanical set includes HVAC plans with equipment schedules and load calculations; the electrical set includes power and lighting plans with panel schedules and load calculations; the plumbing set includes sanitary, storm, and water plans with riser diagrams. The civil set covers the site plan, grading, stormwater management, and erosion control. Energy code compliance documentation accompanies the permit set, and specialty systems — steel connections, trusses, curtain wall — arrive as separately sealed deferred submittals.\n\nMississippi's triggers are written by Hurricane Katrina's legacy. The Gulf Coast — Biloxi, Gulfport, Pascagoula, Ocean Springs — enforces high design wind speeds with wind-borne debris provisions, and FEMA flood zones dominate the coastal drawing package: base flood elevation, finished floor elevation with freeboard, flood-resistant materials, breakaway walls, and elevation certificates the floodplain administrator reviews line by line. Post-Katrina rebuilding standards raised the bar permanently, and coastal reviewers are exacting on the flood details. Inland, Jackson, Hattiesburg, and the university towns run conventional commercial review, while DeSoto County on the Memphis fringe sits close enough to the New Madrid zone for seismic drawing notes to appear.\n\nThe gray areas follow Mississippi's local-adoption model. Mississippi has no single statewide building code for private construction — cities and counties adopt their own editions — so the stamping triggers genuinely vary by jurisdiction. Conventional homes under the residential code often avoid the engineer stamp, but coastal floodplain administrators and building officials routinely require engineered drawings for elevated construction, unusual spans, and retaining walls. Agricultural exemptions vary by county. Confirm the authority having jurisdiction before design starts.",
    directAnswer: "Mississippi requires a Mississippi-licensed PE in responsible charge to stamp structural, commercial MEP, and civil site drawings. The Gulf Coast's strict post-Katrina wind and flood standards dominate coastal drawing sets, and local code adoption means stamping triggers vary by jurisdiction.",
    topic: "PE Stamping by State",
    serviceHref: "/services/structural/",
    sections: [
      {
        heading: "Drawing Sets That Require a Stamp in Mississippi",
        body: "Mississippi's stamped package divides into four sets, each sealed by the Mississippi-licensed engineer who controlled it. The structural set — foundation plan, framing plans, sections, details, lateral system — is sealed by the structural engineer of record, with the design wind speed, exposure category, and seismic design category stated on the cover sheet. The mechanical, electrical, and plumbing sets are sealed by their respective licensed engineers with load calculations, equipment and panel schedules, and riser diagrams. The civil set — site, grading, drainage, stormwater, erosion control — is sealed by the civil engineer of record. Apex Grid Engineering assigns Mississippi-licensed engineers as engineers of record for each discipline, so every seal on your Mississippi set belongs to the licensed professional who directed that work.\n\nDeferred submittals are a routine part of the Mississippi package. Steel connection engineering, pre-engineered trusses, curtain wall systems, and fire suppression shop drawings are typically sealed by the supplier's engineer after permit issuance, and the building official reviews each against the design criteria on the engineer-of-record drawings. On the Gulf Coast, window and door product approvals for wind-borne debris compliance often travel with the deferred package — the reviewer checks every regulated opening against its approval, so the approvals must be current and correctly listed on the drawings.",
      },
      {
        heading: "Mississippi-Specific Stamp Triggers",
        body: "The Mississippi Gulf Coast runs the state's most demanding plan review. Biloxi, Gulfport, Pascagoula, and the Harrison and Jackson County jurisdictions enforce the post-Katrina playbook: elevated construction with the finished floor above the base flood elevation plus freeboard, flood-resistant materials below the flood level, breakaway walls for enclosures, and continuous load paths for the high design wind speeds. The elevation certificate is a core drawing-adjacent document — the floodplain administrator verifies the elevations on the certificate against the elevations on the plans, and a mismatch stops the permit. Wind-borne debris provisions require impact-resistant openings or shutters, with product approvals referenced on the drawings.\n\nInland Mississippi is a different review environment. Jackson's metro jurisdictions, Hattiesburg, Tupelo, and the university towns enforce their locally adopted code editions with conventional commercial checklists — sealed structural, MEP, and civil sets with energy compliance. DeSoto County's growth corridor on the Memphis fringe brings New Madrid seismic awareness into the structural drawings. State-owned buildings and schools follow the state's review track rather than the municipal permit. Because Mississippi leaves code adoption local, the engineer verifies the jurisdiction's edition and amendments for every project — the Gulfport reviewer and the Oxford reviewer are not enforcing the same book.",
      },
      {
        heading: "Mississippi Drawing Checklist Before Sealing",
        body: "Use this checklist before your Mississippi permit set is sealed:\n\n• Engineer of record for each discipline holds an active Mississippi PE license, verifiable on the board roster\n• Seal shows name, Mississippi license number, and date on every sealed sheet\n• Structural set complete: foundation plan, framing plans, sections, details, lateral system drawings\n• Design wind speed, exposure category, and seismic design category on the structural cover sheet\n• Gulf Coast: flood elevations, freeboard, flood-resistant materials, and breakaway walls documented\n• Elevation certificate prepared and consistent with the elevations on the plans\n• Wind-borne debris protection detailed with current product approvals referenced\n• Authority having jurisdiction and its adopted code edition confirmed: city or county",
      },
    ],
    faqs: [
      {
        question: "What is an elevation certificate and why does Mississippi require it?",
        answer: "An elevation certificate documents a building's elevation relative to the base flood elevation, prepared from a field survey. Mississippi's coastal floodplain administrators use it to verify the finished floor, the lowest horizontal structural member, and mechanical equipment elevations against the flood maps. The elevations on the certificate must match the elevations on the construction drawings.",
      },
      {
        question: "How did Hurricane Katrina change Mississippi drawing requirements?",
        answer: "Katrina permanently raised the Gulf Coast's standards: higher design wind speeds, stricter flood elevation and freeboard requirements, flood-resistant construction details, and rigorous floodplain administration. Coastal reviewers scrutinize the flood and wind details on every set, and the post-Katrina standards are now simply the baseline for Mississippi Gulf Coast construction.",
      },
      {
        question: "Does Mississippi have a statewide building code?",
        answer: "Not for private construction. Mississippi leaves building code adoption to cities and counties, so the enforced edition and the stamping triggers vary by jurisdiction. State-owned buildings follow the state's own review track. Your engineer confirms the local authority having jurisdiction and its adopted code before design begins.",
      },
      {
        question: "Can an out-of-state engineer stamp my Mississippi drawings?",
        answer: "Only after obtaining Mississippi licensure. Mississippi offers comity for engineers licensed in other states who meet the qualifications, but the stamp cannot go on Mississippi drawings until the Mississippi license is active. Working under a Mississippi-licensed engineer in responsible charge is the compliant interim path.",
      },
    ],
    extraLinks: [
      { label: "How is an elevation certificate explained?", href: "/answers/elevation-certificate-explained/" },
      { label: "How is flood-resistant design done per ASCE 24?", href: "/answers/asce-24-flood-resistant-design/" },
      { label: "How is hurricane glazing designed?", href: "/answers/hurricane-glazing-design/" },
      { label: "Get an engineering estimate", href: "/estimate" },
    ],
    founderNote,
  },
  {
    slug: "what-drawings-need-engineer-stamp-louisiana",
    title: "What Drawings Need an Engineer Stamp for Louisiana Parishes?",
    description: "Which Louisiana drawings need a PE stamp? Structural, MEP, and civil sets explained, plus parish floodplain review, elevation certificates, and LSUCC notes.",
    h1: "What Drawings Need an Engineer Stamp for Louisiana Parishes?",
    answer: "The answer: In Louisiana, structural drawings, commercial MEP drawings, and civil site drawings need a Louisiana-licensed PE stamp before the parish or municipality will issue a permit. That covers foundation and framing plans, the lateral-force-resisting system, HVAC, electrical, and plumbing drawings for commercial projects, plus grading, drainage, stormwater, and erosion-control plans. The stamp must come from a professional engineer licensed by the Louisiana Professional Engineering and Land Surveying Board (LAPELS) who exercised responsible charge over the design — an out-of-state engineer must obtain Louisiana licensure by comity before sealing.\n\nThe structural set anchors the package: foundation plan with footing and pile schedules, floor and roof framing plans, structural sections and details, connection schedules, and lateral system drawings tracing wind and seismic loads to the foundation. The mechanical set includes HVAC plans with equipment schedules and load calculations; the electrical set includes power and lighting plans with panel schedules and load calculations; the plumbing set includes sanitary, storm, and water plans with riser diagrams. The civil set covers the site plan, grading, stormwater management, and erosion control. Energy code compliance documentation accompanies the permit set, and specialty systems — steel connections, trusses, curtain wall — arrive as separately sealed deferred submittals.\n\nLouisiana permits by parish, and the parish floodplain administrator is often the toughest reviewer on the project. Orleans Parish — the City of New Orleans Department of Safety and Permits — Jefferson Parish, St. Tammany, and East Baton Rouge each run their own review under the Louisiana State Uniform Construction Code, the statewide IBC-based code. Across south Louisiana, FEMA flood zones make the flood drawing package decisive: base flood elevation, finished floor elevation with freeboard, elevation certificates, flood-resistant materials, and breakaway walls. Coastal parishes add hurricane wind design with wind-borne debris provisions. The region's soft clays and subsidence mean the geotechnical investigation drives foundation choices — piles, piers, or engineered fill — and the foundation drawings must track the report.\n\nThe gray areas are parish-specific. Conventional homes under the residential code often avoid the engineer stamp, but Louisiana parishes routinely require engineered drawings for elevated construction in flood zones, and the floodplain administrator's word is final on flood matters. Agricultural exemptions vary. Preliminary sets marked not-for-construction cannot be permitted. Because the parish is the authority having jurisdiction, confirm its submittal checklist before design — New Orleans, Jefferson, and East Baton Rouge do not run identical reviews.",
    directAnswer: "Louisiana requires a Louisiana-licensed PE in responsible charge to stamp structural, commercial MEP, and civil site drawings. Parishes permit under the statewide construction code, floodplain administrators drive the parish flood drawing package, and soft delta soils shape every foundation set.",
    topic: "PE Stamping by State",
    serviceHref: "/services/structural/",
    sections: [
      {
        heading: "Drawing Sets That Require a Stamp in Louisiana",
        body: "Louisiana's stamped package divides into four sets, each sealed by the Louisiana-licensed engineer who controlled it. The structural set — foundation plan, framing plans, sections, details, lateral system — is sealed by the structural engineer of record, with the design wind speed, exposure category, and seismic design category stated on the cover sheet. The mechanical, electrical, and plumbing sets are sealed by their respective licensed engineers with load calculations, equipment and panel schedules, and riser diagrams. The civil set — site, grading, drainage, stormwater, erosion control — is sealed by the civil engineer of record. Apex Grid Engineering assigns Louisiana-licensed engineers as engineers of record for each discipline, so every seal on your Louisiana set belongs to the licensed professional who directed that work.\n\nDeferred submittals are standard in Louisiana practice. Steel connection engineering, pre-engineered trusses, curtain wall systems, and fire suppression shop drawings are typically sealed by the supplier's engineer after permit issuance, and the parish or municipal building official reviews each against the criteria on the engineer-of-record drawings. In flood zones, the elevation certificate functions as a companion document to the sealed set — the floodplain administrator cross-checks its elevations against the plans, and consistency between the two is a permit condition, not a courtesy.",
      },
      {
        heading: "Louisiana-Specific Stamp Triggers",
        body: "The Louisiana State Uniform Construction Code gives the state a uniform IBC-based baseline, but the parishes administer it — and the parish floodplain program is where Louisiana drawing requirements get distinctive. In Orleans, Jefferson, St. Bernard, Plaquemines, Terrebonne, Lafourche, and the other coastal and river parishes, the flood drawing package is reviewed as rigorously as the structural set: finished floor elevations with freeboard above the base flood elevation, flood-resistant materials below the flood level, elevated mechanical equipment, breakaway wall details, and the elevation certificate tying the survey to the plans. A flood detail the building reviewer might wave through will not survive the floodplain administrator.\n\nWind design follows the coast. South Louisiana's hurricane exposure puts the design wind speeds and wind-borne debris provisions on the structural drawings, with impact-resistant openings or shutters and product approvals referenced. The soils add their own trigger: the Mississippi River alluvial clays and the New Orleans area's subsiding soils routinely push foundations to deep piles or drilled piers, and the geotechnical investigation is the document the foundation design — and the reviewer — starts from. North Louisiana's review is more conventional, but the LSUCC baseline and the parish administration apply statewide.",
      },
      {
        heading: "Louisiana Drawing Checklist Before Sealing",
        body: "Use this checklist before your Louisiana permit set is sealed:\n\n• Engineer of record for each discipline holds an active Louisiana LAPELS license, verifiable on the board roster\n• Seal shows name, Louisiana license number, and date on every sealed sheet\n• Structural set complete: foundation plan, framing plans, sections, details, lateral system drawings\n• Design wind speed, exposure category, and seismic design category on the structural cover sheet\n• Flood zones: base flood elevation, finished floor with freeboard, flood-resistant materials, breakaway walls\n• Elevation certificate prepared and consistent with the elevations on the plans\n• Geotechnical report addresses soft clays and subsidence; foundation design follows its recommendations\n• Authority having jurisdiction confirmed: the parish or municipality administering the LSUCC",
      },
    ],
    faqs: [
      {
        question: "Who reviews my drawings in Louisiana — the state or the parish?",
        answer: "The parish or municipality. Louisiana's State Uniform Construction Code sets the statewide baseline, but parishes and cities administer permitting and plan review locally — New Orleans, Jefferson Parish, East Baton Rouge, and the rest each run their own departments. The parish floodplain administrator separately reviews flood compliance, and in flood zones that review is as decisive as the building plan check.",
      },
      {
        question: "Why are Louisiana foundations so often on piles?",
        answer: "South Louisiana's soft alluvial clays, high water tables, and subsiding soils often cannot support conventional shallow foundations for commercial loads. The geotechnical investigation typically recommends driven piles or drilled piers to competent bearing strata. The foundation drawings must reflect the investigation's recommendations — the reviewer checks that the pile capacities, depths, and layout match the report.",
      },
      {
        question: "What does the floodplain administrator look for on my drawings?",
        answer: "The finished floor elevation relative to the base flood elevation, freeboard, flood-resistant materials below the flood level, elevated utilities and mechanical equipment, breakaway walls for enclosures, and an elevation certificate consistent with the plans. In Louisiana's parishes, the floodplain administrator's approval is a permit condition — the building permit does not issue without it in mapped flood zones.",
      },
      {
        question: "Can an out-of-state engineer stamp my Louisiana drawings?",
        answer: "Only after obtaining Louisiana licensure. Louisiana offers comity for engineers licensed in other states who meet the qualifications, but the stamp cannot go on Louisiana drawings until the Louisiana license is active. Working under a Louisiana-licensed engineer in responsible charge is the compliant interim path.",
      },
    ],
    extraLinks: [
      { label: "How is an elevation certificate explained?", href: "/answers/elevation-certificate-explained/" },
      { label: "How is flood-resistant design done per ASCE 24?", href: "/answers/asce-24-flood-resistant-design/" },
      { label: "How is hurricane glazing designed?", href: "/answers/hurricane-glazing-design/" },
      { label: "Get an engineering estimate", href: "/estimate" },
    ],
    founderNote,
  },
  {
    slug: "what-drawings-need-engineer-stamp-arkansas",
    title: "What Drawings Need an Engineer Stamp for Arkansas Permits?",
    description: "Which Arkansas drawings need a PE stamp? Structural, MEP, and civil sets explained, plus New Madrid seismic detailing rules and Little Rock review expectations.",
    h1: "What Drawings Need an Engineer Stamp for Arkansas Permits?",
    answer: "The answer: In Arkansas, structural drawings, commercial MEP drawings, and civil site drawings need an Arkansas-licensed PE stamp before the building department will issue a permit. That covers foundation and framing plans, the lateral-force-resisting system, HVAC, electrical, and plumbing drawings for commercial projects, plus grading, drainage, stormwater, and erosion-control plans. The stamp must come from a professional engineer licensed by the Arkansas State Board of Licensure for Professional Engineers and Professional Surveyors who exercised responsible charge over the design — an out-of-state engineer must obtain Arkansas licensure by comity before sealing.\n\nThe structural set is the core: foundation plan with footing schedules, floor and roof framing plans, structural sections and details, connection schedules, and lateral system drawings showing how wind and seismic forces reach the foundation. The mechanical set carries HVAC plans with equipment schedules and load calculations; the electrical set carries power and lighting plans with panel schedules and load calculations; the plumbing set carries sanitary, storm, and water plans with riser diagrams. The civil set covers the site plan, grading, stormwater management, and erosion control. Energy code compliance documentation accompanies the permit set, and specialty components — steel connections, trusses, curtain wall — arrive as separately sealed deferred submittals.\n\nArkansas's defining trigger is the New Madrid seismic zone in the east. The Delta counties — around West Memphis, Jonesboro, and Blytheville — carry elevated seismic design categories, so structural drawings there must show the seismic design category, the lateral-force-resisting system, and the seismic detailing, with the geotechnical investigation addressing liquefaction in the alluvial soils. Little Rock's Planning and Development Department runs the state's largest review, while the Northwest Arkansas corridor — Fayetteville, Bentonville, Rogers, Springdale — has become a high-volume market with its own review pace. The Arkansas River and Delta floodplains add flood elevation documentation to low-lying projects, and central Arkansas's expansive clays shape foundation choices.\n\nThe gray areas are familiar. Conventional homes under the residential code often proceed without an engineer stamp, but Arkansas building officials require engineered drawings for unusual spans, retaining walls, and floodplain construction. Agricultural exemptions vary by county. Preliminary drawings marked not-for-construction cannot be permitted or built from. The authority having jurisdiction settles the edge cases — confirm before design begins.",
    directAnswer: "Arkansas requires an Arkansas-licensed PE in responsible charge to stamp structural, commercial MEP, and civil site drawings. The eastern Delta's New Madrid seismic demands shape structural sets, Little Rock and Northwest Arkansas run the major reviews, and floodplains add elevation documentation.",
    topic: "PE Stamping by State",
    serviceHref: "/services/structural/",
    sections: [
      {
        heading: "Drawing Sets That Require a Stamp in Arkansas",
        body: "Arkansas's stamped package divides into four sets, each sealed by the Arkansas-licensed engineer who controlled it. The structural set — foundation plan, framing plans, sections, details, lateral system — is sealed by the structural engineer of record, with the seismic design category, design wind speed, and exposure category stated on the cover sheet. The mechanical, electrical, and plumbing sets are sealed by their respective licensed engineers with load calculations, equipment and panel schedules, and riser diagrams. The civil set — site, grading, drainage, stormwater, erosion control — is sealed by the civil engineer of record. Apex Grid Engineering assigns Arkansas-licensed engineers as engineers of record for each discipline, so every seal on your Arkansas set belongs to the licensed professional who directed that work.\n\nDeferred submittals complete the package. Steel connection engineering, pre-engineered trusses, curtain wall systems, and fire suppression shop drawings are typically sealed by the supplier's engineer after permit issuance, and the building official reviews each against the design criteria stated on the engineer-of-record drawings. In the eastern Delta, the deferred package must respect the seismic criteria on the permitted set — connection forces and drift limits carry through, so the criteria need to be explicit on the engineer-of-record drawings from the start.",
      },
      {
        heading: "Arkansas-Specific Stamp Triggers",
        body: "The New Madrid seismic zone is Arkansas's signature engineering trigger. Eastern Arkansas — the Delta counties from Blytheville through West Memphis to the Louisiana line — sits in the zone's footprint, and the seismic design categories there are the highest in the state. Structural drawings in that corridor show the seismic design category, the mapped spectral values, the lateral system, and the seismic detailing; the geotechnical investigation addresses liquefaction and the soft alluvial soils, and the foundation design follows the report. Reviewers in Jonesboro, West Memphis, and the Delta counties check the seismic parameters first.\n\nCentral Arkansas brings expansive clay soils that shape foundation design around Little Rock — the geotechnical report drives the choice between reinforced slabs, piers, and over-excavation, and the drawings must track the report. Northwest Arkansas's boom corridor runs high-volume commercial review in Fayetteville, Bentonville, Rogers, and Springdale, where complete coordinated sets move fastest. The Arkansas River floodplain and the Delta's low-lying ground add base flood elevation and finished-floor documentation to affected projects. State buildings follow the state's review track; everything else goes through the city or county building department.",
      },
      {
        heading: "Arkansas Drawing Checklist Before Sealing",
        body: "Use this checklist before your Arkansas permit set is sealed:\n\n• Engineer of record for each discipline holds an active Arkansas PE license, verifiable on the board roster\n• Seal shows name, Arkansas license number, and date on every sealed sheet\n• Structural set complete: foundation plan, framing plans, sections, details, lateral system drawings\n• Seismic design category and mapped spectral values on the structural cover sheet\n• Eastern Delta: liquefaction addressed in the geotechnical report and reflected in the foundation design\n• Central Arkansas: expansive clays addressed; foundation follows the geotechnical recommendations\n• MEP sets include load calculations, schedules, and riser diagrams\n• Authority having jurisdiction confirmed: Little Rock, Northwest Arkansas city, or the local building department",
      },
    ],
    faqs: [
      {
        question: "Does the New Madrid seismic zone affect Arkansas projects?",
        answer: "Yes — significantly in eastern Arkansas. The Delta counties sit in the New Madrid zone's footprint with the state's highest seismic design categories. Structural drawings there must show the seismic design category, the lateral system, and the seismic detailing, and the geotechnical investigation must address liquefaction. Central and western Arkansas design to lower seismic demands.",
      },
      {
        question: "What soils issues affect Arkansas foundations?",
        answer: "It depends on the region. Central Arkansas has expansive clays that swell with moisture changes, driving pier, reinforced slab, or over-excavation foundation choices. The eastern Delta has soft alluvial soils with liquefaction risk in the seismic zone. Northwest Arkansas's rockier terrain brings different excavation and bearing considerations. The geotechnical report sets the foundation approach in every region.",
      },
      {
        question: "Do Arkansas homes need an engineer stamp?",
        answer: "Conventional homes within the residential code's prescriptive limits often do not. But Arkansas building officials require engineered drawings for long spans, unusual structural systems, tall retaining walls, hillside construction, and floodplain building. The trigger is the condition, not the occupancy — when the design leaves the prescriptive path, the engineer steps in.",
      },
      {
        question: "Can an out-of-state engineer stamp my Arkansas drawings?",
        answer: "Only after obtaining Arkansas licensure. Arkansas offers comity for engineers licensed in other states who meet the qualifications, but the stamp cannot go on Arkansas drawings until the Arkansas license is active. Working under an Arkansas-licensed engineer in responsible charge is the compliant interim path.",
      },
    ],
    extraLinks: [
      { label: "How are seismic design categories explained?", href: "/answers/seismic-design-categories-explained/" },
      { label: "How are expansive soils foundations designed?", href: "/answers/expansive-soils-foundation-design/" },
      { label: "How is the plan check corrections process explained?", href: "/answers/plan-check-corrections-process-explained/" },
      { label: "Get an engineering estimate", href: "/estimate" },
    ],
    founderNote,
  },
  {
    slug: "what-drawings-need-engineer-stamp-missouri",
    title: "What Drawings Need an Engineer Stamp for Missouri Projects?",
    description: "Which Missouri drawings need a PE stamp? Structural, MEP, and civil sets explained, plus St. Louis city-county standards, KC review, and Bootheel seismic notes.",
    h1: "What Drawings Need an Engineer Stamp for Missouri Projects?",
    answer: "The answer: In Missouri, structural drawings, commercial MEP drawings, and civil site drawings need a Missouri-licensed PE stamp before the building department will issue a permit. That covers foundation and framing plans, the lateral-force-resisting system, HVAC, electrical, and plumbing drawings for commercial projects, plus grading, drainage, stormwater, and erosion-control plans. The stamp must come from a professional engineer licensed by the Missouri Board for Architects, Professional Engineers, Professional Land Surveyors, and Professional Landscape Architects who exercised responsible charge over the design — an out-of-state engineer must obtain Missouri licensure by comity before sealing.\n\nThe structural set anchors the package: foundation plan with footing and pier schedules, floor and roof framing plans, structural sections and details, connection schedules, and lateral system drawings tracing wind and seismic forces to the foundation. The mechanical set includes HVAC plans with equipment schedules and load calculations; the electrical set includes power and lighting plans with panel schedules and load calculations; the plumbing set includes sanitary, storm, and water plans with riser diagrams. The civil set covers the site plan, grading, stormwater management, and erosion control. Energy code compliance documentation accompanies the permit set, and specialty systems — steel connections, trusses, curtain wall — arrive as separately sealed deferred submittals.\n\nMissouri has no statewide building code, so the local jurisdiction is everything. The St. Louis region splits between the City of St. Louis Building Division and St. Louis County's Department of Public Works — separate authorities with their own drawing standards, submittal checklists, and review cultures — plus the surrounding municipalities that each run their own review. Kansas City, Missouri's City Planning and Development department runs the western market with its own standards. In the southeastern Bootheel, the New Madrid seismic zone raises the seismic design category, and structural drawings there must show the category, the lateral system, and the seismic detailing with liquefaction addressed in the geotechnical report. The Kansas City and St. Louis metros add expansive clay soils that the foundation drawings must answer to.\n\nThe gray areas reflect Missouri's local-control model. Conventional homes under the residential code often avoid the engineer stamp, but Missouri building officials require engineered drawings for unusual spans, retaining walls, and problematic soils — and the requirements genuinely differ between the City of St. Louis, St. Louis County, and Kansas City. Agricultural exemptions vary by county. Preliminary sets marked not-for-construction cannot be permitted. Confirm the authority having jurisdiction first, because in Missouri the jurisdiction writes the rules.",
    directAnswer: "Missouri requires a Missouri-licensed PE in responsible charge to stamp structural, commercial MEP, and civil site drawings. With no statewide code, St. Louis city, St. Louis County, and Kansas City each set their own standards, and the Bootheel carries New Madrid seismic requirements.",
    topic: "PE Stamping by State",
    serviceHref: "/services/structural/",
    sections: [
      {
        heading: "Drawing Sets That Require a Stamp in Missouri",
        body: "Missouri's stamped package divides into four sets, each sealed by the Missouri-licensed engineer who controlled it. The structural set — foundation plan, framing plans, sections, details, lateral system — is sealed by the structural engineer of record, with the seismic design category, design wind speed, and exposure category stated on the cover sheet. The mechanical, electrical, and plumbing sets are sealed by their respective licensed engineers with load calculations, equipment and panel schedules, and riser diagrams. The civil set — site, grading, drainage, stormwater, erosion control — is sealed by the civil engineer of record. Apex Grid Engineering assigns Missouri-licensed engineers as engineers of record for each discipline, so every seal on your Missouri set belongs to the licensed professional who directed that work.\n\nDeferred submittals are part of the standard Missouri package. Steel connection engineering, pre-engineered trusses, curtain wall systems, and fire suppression shop drawings are typically sealed by the supplier's engineer after permit issuance, and the local building official reviews each against the design criteria on the engineer-of-record drawings. Because Missouri's jurisdictions each run their own review, the deferred submittal expectations — what can defer, what must be in the permit set — vary: the engineer confirms the local policy during design rather than assuming one jurisdiction's practice applies in the next.",
      },
      {
        heading: "Missouri-Specific Stamp Triggers",
        body: "Missouri's local-control model makes the jurisdiction the first design input. In the St. Louis region, the City of St. Louis and St. Louis County are entirely separate building departments with their own amendments, drawing standards, and intake checklists — a set drawn for the county will draw corrections in the city and vice versa. The surrounding municipalities — Chesterfield, O'Fallon, St. Charles, and the rest — add their own layers. Kansas City's Development Services runs the western market with its own standards and a form-based review culture shaped by the city's development code. Springfield, Columbia, and the outstate jurisdictions each enforce their locally adopted editions.\n\nThe Bootheel brings the seismic trigger: southeastern Missouri sits in the New Madrid zone, and structural drawings there carry the seismic design category, the lateral system, and the detailing with liquefaction evaluated in the geotechnical investigation. The Kansas City and St. Louis metros bring expansive clay soils — the geotechnical report drives pier, reinforced slab, or over-excavation foundation decisions, and the reviewer checks the foundation against the report. Missouri's karst regions in the Ozarks add sinkhole considerations to foundation review in the southwest. Every one of these triggers is administered locally, which is why the pre-design jurisdiction check is non-negotiable in Missouri.",
      },
      {
        heading: "Missouri Drawing Checklist Before Sealing",
        body: "Use this checklist before your Missouri permit set is sealed:\n\n• Engineer of record for each discipline holds an active Missouri PE license, verifiable on the board roster\n• Seal shows name, Missouri license number, and date on every sealed sheet\n• Structural set complete: foundation plan, framing plans, sections, details, lateral system drawings\n• Seismic design category, design wind speed, and exposure category on the structural cover sheet\n• Bootheel projects: seismic detailing shown and liquefaction addressed in the geotechnical report\n• Expansive clays: foundation design follows the geotechnical report's recommendations\n• MEP sets include load calculations, schedules, and riser diagrams\n• Authority having jurisdiction confirmed — city, county, and municipality each enforce their own standards",
      },
    ],
    faqs: [
      {
        question: "Does Missouri have a statewide building code?",
        answer: "No. Missouri is a local-control state with no mandatory statewide building code for private construction. Cities and counties adopt and enforce their own code editions and amendments. That means the stamping triggers, the drawing standards, and the review process genuinely differ between the City of St. Louis, St. Louis County, Kansas City, and every other jurisdiction.",
      },
      {
        question: "What is the difference between St. Louis city and county plan review?",
        answer: "They are entirely separate building departments. The City of St. Louis Building Division and St. Louis County's Department of Public Works each maintain their own code amendments, submittal checklists, and review procedures. A permit set must be drawn to the specific authority having jurisdiction — county standards do not transfer to the city or the surrounding municipalities.",
      },
      {
        question: "Does the New Madrid seismic zone reach Missouri?",
        answer: "Yes — southeastern Missouri's Bootheel is in the New Madrid zone. Structures there design to elevated seismic design categories, and the structural drawings must show the category, the lateral-force-resisting system, and the seismic detailing. The geotechnical investigation must address liquefaction. The rest of Missouri designs to lower seismic demands.",
      },
      {
        question: "Can an out-of-state engineer stamp my Missouri drawings?",
        answer: "Only after obtaining Missouri licensure. Missouri offers comity for engineers licensed in other states who meet the qualifications, but the stamp cannot go on Missouri drawings until the Missouri license is active. Working under a Missouri-licensed engineer in responsible charge is the compliant interim path.",
      },
    ],
    extraLinks: [
      { label: "How are seismic design categories explained?", href: "/answers/seismic-design-categories-explained/" },
      { label: "How are expansive soil foundations designed?", href: "/answers/expansive-soil-foundation-solutions/" },
      { label: "How does the engineering board differ from the authority having jurisdiction?", href: "/answers/engineering-board-vs-authority-having-jurisdiction/" },
      { label: "Get an engineering estimate", href: "/estimate" },
    ],
    founderNote,
  },
  {
    slug: "what-drawings-need-engineer-stamp-illinois",
    title: "What Drawings Need an Engineer Stamp Under Chicago's Code?",
    description: "Which Illinois drawings need a PE stamp? Structural, MEP, and civil sets explained, plus Chicago building code rules, SE triggers, and peer review notes.",
    h1: "What Drawings Need an Engineer Stamp Under Chicago's Code?",
    answer: "The answer: In Illinois, structural drawings, commercial MEP drawings, and civil site drawings need an Illinois-licensed PE stamp before the building department will issue a permit — and structural work on many buildings requires an Illinois-licensed Structural Engineer (SE), a separate license above the PE. That covers foundation and framing plans, the lateral-force-resisting system, HVAC, electrical, and plumbing drawings for commercial projects, plus grading, drainage, stormwater, and erosion-control plans. The stamp must come from an engineer licensed by the Illinois Department of Financial and Professional Regulation who exercised responsible charge — an out-of-state engineer must obtain Illinois licensure by endorsement before sealing.\n\nThe structural set is the core: foundation plan with footing and caisson schedules, floor and roof framing plans, structural sections and details, connection schedules, and lateral system drawings. The mechanical set includes HVAC plans with equipment schedules and load calculations; the electrical set includes power and lighting plans with panel schedules and load calculations; the plumbing set includes sanitary, storm, and water plans with riser diagrams. The civil set covers the site plan, grading, stormwater management, and erosion control. Energy code compliance documentation accompanies the permit set, and specialty systems — steel connections, trusses, curtain wall — arrive as separately sealed deferred submittals.\n\nChicago runs its own building code — historically distinct from the model codes and still Chicago-specific in administration — enforced by the Chicago Department of Buildings with its own drawing standards and permit tracks. Standard Plan Review is the full departmental check; the Self-Certification program lets qualified Illinois-licensed architects and structural engineers certify code compliance on eligible projects for faster permitting; Developer Services handles large complex projects. Tall and complex buildings can trigger structural peer review, where an independent SE reviews the structural design. Outside Chicago, Cook County's unincorporated areas and the collar counties — DuPage, Kane, Lake, Will, McHenry — each enforce their own adopted editions, and downstate jurisdictions run smaller but equally binding reviews. Southern Illinois near the New Madrid zone carries modest seismic drawing notes.\n\nThe gray areas have Illinois accents. Conventional homes under the residential code often avoid the engineer stamp, but Illinois municipalities require engineered drawings for unusual spans, retaining walls, and floodplain construction. The SE-versus-PE line matters: Illinois reserves certain structural work for licensed structural engineers, and a PE seal on SE-required work will be rejected. Preliminary sets marked not-for-construction cannot be permitted. Confirm the authority having jurisdiction and the SE trigger before design begins.",
    directAnswer: "Illinois requires an Illinois-licensed PE — or SE for structural work the state reserves to structural engineers — in responsible charge to stamp structural, commercial MEP, and civil site drawings. Chicago enforces its own building code with distinct permit tracks, and tall buildings can trigger structural peer review.",
    topic: "PE Stamping by State",
    serviceHref: "/services/structural/",
    sections: [
      {
        heading: "Drawing Sets That Require a Stamp in Illinois",
        body: "Illinois's stamped package divides into four sets, each sealed by the Illinois-licensed engineer who controlled it. The structural set — foundation plan, framing plans, sections, details, lateral system — is sealed by the structural engineer of record, who must hold the Illinois SE license where the state's practice act reserves the work to structural engineers; the seal shows the licensee's name, license number, and date. The mechanical, electrical, and plumbing sets are sealed by their respective licensed engineers with load calculations, equipment and panel schedules, and riser diagrams. The civil set — site, grading, drainage, stormwater, erosion control — is sealed by the civil engineer of record. Apex Grid Engineering assigns Illinois-licensed engineers as engineers of record for each discipline, so every seal on your Illinois set belongs to the licensed professional who directed that work.\n\nDeferred submittals are routine in Illinois practice. Steel connection engineering, pre-engineered trusses, curtain wall systems, and fire suppression shop drawings are typically sealed by the supplier's engineer after permit issuance, and the building official reviews each against the criteria on the engineer-of-record drawings. In Chicago, the deferred submittal path interacts with the permit track: self-certified projects carry their own documentation discipline, and the structural peer review process for tall buildings examines the structural criteria before the deferred engineers build on them.",
      },
      {
        heading: "Illinois-Specific Stamp Triggers",
        body: "Chicago's building code is the state's defining review environment. The Chicago Building Code — modernized in recent years but still administered as its own code — sets drawing standards, structural provisions, and permit procedures that differ from the IBC-based suburbs. The Department of Buildings offers three tracks: Standard Plan Review for the full departmental check, Self-Certification for eligible projects where an Illinois-licensed architect or structural engineer certifies compliance, and Developer Services for large complex projects. Choosing the track is a strategic decision made before the first sheet is drawn, because the documentation burden differs.\n\nStructural peer review is the Chicago trigger owners least expect. Tall buildings and certain complex structures require an independent licensed structural engineer to review the structural design — a parallel review track with its own comments and sign-off. The SE license trigger is the other Illinois distinctive: the state's practice act reserves specified structural engineering to SEs, and the building official will reject a PE seal where the SE is required. Outside the city, the collar counties enforce their own IBC-based amendments with conventional commercial checklists, and downstate jurisdictions — Springfield, Peoria, Champaign — run smaller reviews where the sealed structural, MEP, and civil sets remain the baseline.",
      },
      {
        heading: "Illinois Drawing Checklist Before Sealing",
        body: "Use this checklist before your Illinois permit set is sealed:\n\n• Engineer of record for each discipline holds an active Illinois PE or SE license, verifiable on the IDFPR roster\n• Structural work the practice act reserves to SEs is sealed by an Illinois-licensed Structural Engineer\n• Seal shows name, Illinois license number, and date on every sealed sheet\n• Structural set complete: foundation plan, framing plans, sections, details, lateral system drawings\n• Chicago projects: permit track selected — Standard Plan Review, Self-Certification, or Developer Services\n• Tall or complex structures: structural peer review requirements identified and programmed\n• MEP sets include load calculations, schedules, and riser diagrams\n• Authority having jurisdiction confirmed: City of Chicago, Cook County, collar county, or downstate municipality",
      },
    ],
    faqs: [
      {
        question: "When does Illinois require a Structural Engineer (SE) instead of a PE?",
        answer: "Illinois licenses Structural Engineers separately from Professional Engineers, and the practice act reserves certain structural work — including the structural design of specified building types — to SEs. A PE seal on SE-reserved work will be rejected at plan review. Your engineer confirms the SE trigger during programming, because discovering it at the permit counter costs weeks.",
      },
      {
        question: "What is Chicago's Self-Certification permit program?",
        answer: "Self-Certification lets qualified Illinois-licensed architects and structural engineers certify that eligible projects comply with the Chicago Building Code, allowing faster permit issuance with reduced departmental plan review. The certifying professional takes on the compliance responsibility, so the drawings and documentation must be airtight — the liability sits with the seal, not the reviewer.",
      },
      {
        question: "What is structural peer review in Chicago?",
        answer: "For tall buildings and certain complex structures, Chicago requires an independent licensed structural engineer — the peer reviewer — to review the structural design separately from the Department of Buildings plan check. The peer review runs on its own track with its own comments, and the project needs the peer reviewer's sign-off alongside the permit.",
      },
      {
        question: "Can an out-of-state engineer stamp my Illinois drawings?",
        answer: "Only after obtaining Illinois licensure. Illinois offers endorsement for engineers licensed in other states who meet the qualifications, but the stamp cannot go on Illinois drawings until the Illinois license is active — and the SE license has its own requirements. Working under an Illinois-licensed engineer in responsible charge is the compliant interim path.",
      },
    ],
    extraLinks: [
      { label: "How does an architect stamp differ from a PE stamp?", href: "/answers/architect-stamp-vs-pe-stamp/" },
      { label: "How is the deferred submittal process run?", href: "/answers/deferred-submittal-process-guide/" },
      { label: "Can a PE stamp drawings in another state?", href: "/answers/can-a-pe-stamp-drawings-in-another-state/" },
      { label: "Get an engineering estimate", href: "/estimate" },
    ],
    founderNote,
  }
];
