import { useParams } from "wouter";
import { useMemo, useEffect } from "react";

/**
 * Wave 1: high-value metro x core-service dynamic pages.
 * Route: /wave1/:service/:city/:state/
 * Example: /wave1/structural-engineering/phoenix/arizona/
 *
 * 6 services x 4 templates x ~1,042 cities = 25,000 URLs.
 * Cohorts tracked by (service, state) via per-cohort sitemaps.
 * Template version: wave1-v1 (bump when content changes).
 */

export const WAVE1_TEMPLATE_VERSION = "wave1-v1";

/**
 * Wave 1 attribution: first-touch is IMMUTABLE.
 * On first Wave 1 pageview, store {landing_url, cohort_id, service, metro, state,
 * template_version, timestamp} in localStorage under "apex_first_touch".
 * Never overwritten — later pageviews (even other Wave 1 pages) do not replace it.
 * The estimate page reads this for RFQ attribution alongside conversion-touch.
 */
const FIRST_TOUCH_KEY = "apex_first_touch";

export interface FirstTouchAttribution {
  landing_url: string;
  cohort_id: string;
  service: string;
  metro: string;
  state: string;
  template_version: string;
  timestamp: string;
}

function recordFirstTouch(attribution: FirstTouchAttribution): void {
  try {
    if (typeof window === "undefined" || !window.localStorage) return;
    if (window.localStorage.getItem(FIRST_TOUCH_KEY)) return; // immutable: never overwrite
    window.localStorage.setItem(FIRST_TOUCH_KEY, JSON.stringify(attribution));
  } catch {
    // storage unavailable — attribution degrades gracefully
  }
}

export function getFirstTouch(): FirstTouchAttribution | null {
  try {
    if (typeof window === "undefined" || !window.localStorage) return null;
    const raw = window.localStorage.getItem(FIRST_TOUCH_KEY);
    return raw ? (JSON.parse(raw) as FirstTouchAttribution) : null;
  } catch {
    return null;
  }
}

interface ServiceInfo { name: string; title: string; description: string; edge: string; services: string[]; }
const SERVICES: Record<string, ServiceInfo> = {
  "structural": {
    name: "Structural",
    title: "Structural Engineering",
    description: "Structural engineering for commercial, residential, and industrial buildings \u2014 foundation design, framing systems, lateral force resisting systems, and structural assessments. Our licensed structural engineers design steel, concrete, masonry, and timber structures to IBC standards with full calculation packages, structural drawings, and PE stamps accepted by building departments in all 49 states.",
    edge: "Structural surprises kill budgets. We front-load the structural investigation \u2014 geotechnical review, as-built verification, load path analysis \u2014 so the framing plan you bid is the framing plan you build.",
    services: [
      "Foundation design: spread footings, mat slabs, drilled piers, and retaining walls",
      "Framing systems: structural steel, reinforced concrete, masonry, and heavy timber",
      "Lateral design: wind and seismic force resisting systems per ASCE 7",
      "Structural assessments: existing building evaluations, load ratings, and retrofit design",
      "Special inspections coordination and structural observation services",
    ],
  },
  "mep": {
    name: "MEP",
    title: "MEP Engineering",
    description: "Full mechanical, electrical, and plumbing engineering \u2014 integrated MEP design for new construction, renovations, and tenant improvements. HVAC load calculations, electrical distribution, plumbing and fire protection systems, all coordinated in a single clash-free model. One MEP team, one point of responsibility, stamped drawings in 49 states.",
    edge: "MEP coordination failures are the #1 cause of field rework. We model all three disciplines together from day one \u2014 so ductwork, conduit, and piping arrive coordinated, not conflicting.",
    services: [
      "HVAC design: load calculations, equipment selection, ductwork, and controls",
      "Electrical: power distribution, lighting, fire alarm, and low-voltage systems",
      "Plumbing: water, waste, vent, storm drainage, and medical gas where required",
      "Fire protection: sprinkler and standpipe system design and hydraulic calculations",
      "Energy modeling and Title 24 / IECC compliance documentation",
    ],
  },
  "electrical": {
    name: "Electrical",
    title: "Electrical Engineering",
    description: "Electrical engineering for buildings and sites \u2014 power distribution, lighting design, fire alarm, and emergency systems. Service entrance sizing, panel schedules, fault current and arc-flash analysis, lighting photometrics, and EV charging infrastructure. NEC-compliant designs with PE stamps in all 49 states.",
    edge: "Electrical bids go sideways when the service size is wrong. We nail the load calculations up front \u2014 utility coordination, demand factors, spare capacity \u2014 so your electrical contractor prices it once and builds it once.",
    services: [
      "Power distribution: service sizing, switchgear, panelboards, and branch circuiting",
      "Lighting: interior/exterior lighting design, photometrics, and controls",
      "Fire alarm and detection: addressable systems, notification, and mass notification",
      "Emergency and standby power: generators, UPS, and life-safety circuits",
      "Studies: short-circuit, arc-flash, and selective coordination analysis",
    ],
  },
  "mechanical-hvac": {
    name: "Mechanical/HVAC",
    title: "Mechanical & HVAC Engineering",
    description: "Mechanical and HVAC engineering \u2014 heating, cooling, ventilation, and building controls designed for comfort, efficiency, and code compliance. ACCA Manual J/S/D calculations, equipment selection, ductwork design, ventilation per ASHRAE 62.1, and building automation systems. Designs stamped by licensed mechanical engineers in 49 states.",
    edge: "Oversized equipment short-cycles; undersized equipment can't keep up. We size from real load calculations \u2014 not rules of thumb \u2014 so the system runs efficiently from the first day of occupancy.",
    services: [
      "Load calculations: ACCA Manual J commercial and residential heating/cooling loads",
      "System selection: rooftop units, VRF/VRV, chillers, boilers, and heat pumps",
      "Ductwork and piping: Manual D duct design, hydronic piping, and refrigerant layout",
      "Ventilation: ASHRAE 62.1 outdoor air, exhaust systems, and demand-controlled ventilation",
      "Controls: building automation sequences, thermostats, and energy management",
    ],
  },
  "plumbing": {
    name: "Plumbing",
    title: "Plumbing Engineering",
    description: "Plumbing engineering for commercial and residential projects \u2014 domestic water, sanitary waste and vent, storm drainage, natural gas, and medical gas systems. Fixture unit calculations, water heater and booster pump sizing, grease interceptors, backflow prevention, and rainwater harvesting. IPC/UPC-compliant designs stamped in 49 states.",
    edge: "Plumbing problems hide until they don't. We design for the worst day \u2014 peak demand, grease loading, storm events \u2014 with cleanouts, access, and slopes that keep maintenance simple for decades.",
    services: [
      "Domestic water: distribution sizing, pressure analysis, booster pumps, and recirculation",
      "Sanitary and vent: DWV layouts, fixture unit calculations, and interceptor sizing",
      "Storm drainage: roof drains, site stormwater, and detention coordination",
      "Gas systems: natural gas and propane distribution, load calculations, and metering",
      "Specialty: medical gas, acid waste, grease waste, and backflow prevention",
    ],
  },
  "civil": {
    name: "Civil",
    title: "Civil Engineering",
    description: "Civil engineering for land development and site infrastructure \u2014 grading and drainage, utilities, paving, and stormwater management. Site plans, erosion control, detention design, ADA site compliance, and agency permitting. Our civil engineers deliver permit-ready site packages stamped in all 49 states.",
    edge: "Site work is where schedules die \u2014 utility conflicts, drainage comments, agency revisions. We front-load agency coordination and design the site around what the reviewers actually want, cutting review cycles in half.",
    services: [
      "Grading and drainage: site grading plans, earthwork quantities, and surface drainage",
      "Stormwater: detention/retention design, water quality, and municipal compliance",
      "Utilities: water, sewer, and storm extensions with agency coordination",
      "Paving and access: parking lots, driveways, fire access, and ADA routes",
      "Permitting: site plan submittals, SWPPP, and agency approval management",
    ],
  },
};

interface TemplateInfo { name: string; label: string; angle: string; cta: string; }
const TEMPLATES: Record<string, TemplateInfo> = {
  "standard": {
    name: "Standard",
    label: "",
    angle: "From ground-up construction to major renovations, our engineers deliver complete permit-ready drawing sets \u2014 calculations, plans, details, and specifications \u2014 coordinated across disciplines and stamped for your jurisdiction.",
    cta: "Send us your project address and scope",
  },
  "commercial": {
    name: "Commercial",
    label: "Commercial",
    angle: "Commercial projects live on schedule and budget certainty. We engineer office, retail, restaurant, and mixed-use buildings with fast-track drawing packages, tenant-improvement expertise, and shell-and-core coordination that keeps your GC moving.",
    cta: "Send us your site address and building program",
  },
  "residential": {
    name: "Residential",
    label: "Residential",
    angle: "From custom homes to multifamily developments, we engineer residential projects that pass plan check the first time. Production-friendly details, value-engineered systems, and structural plans your framer will actually enjoy building from.",
    cta: "Send us your lot address and house plans",
  },
  "industrial": {
    name: "Industrial",
    label: "Industrial",
    angle: "Industrial facilities demand heavy-duty engineering \u2014 high-bay structures, process utilities, heavy power, and clear-span layouts. We design warehouses, manufacturing plants, and distribution centers built for equipment loads and 24/7 operations.",
    cta: "Send us your facility requirements and site plan",
  },
};

// service slug -> [serviceKey, templateKey]
const SERVICE_SLUGS: Record<string, [string, string]> = {
  "structural-engineering": ["structural", "standard"],
  "commercial-structural-engineering": ["structural", "commercial"],
  "residential-structural-engineering": ["structural", "residential"],
  "industrial-structural-engineering": ["structural", "industrial"],
  "mep-engineering": ["mep", "standard"],
  "commercial-mep-engineering": ["mep", "commercial"],
  "residential-mep-engineering": ["mep", "residential"],
  "industrial-mep-engineering": ["mep", "industrial"],
  "electrical-engineering": ["electrical", "standard"],
  "commercial-electrical-engineering": ["electrical", "commercial"],
  "residential-electrical-engineering": ["electrical", "residential"],
  "industrial-electrical-engineering": ["electrical", "industrial"],
  "mechanical-hvac-engineering": ["mechanical-hvac", "standard"],
  "commercial-mechanical-hvac-engineering": ["mechanical-hvac", "commercial"],
  "residential-mechanical-hvac-engineering": ["mechanical-hvac", "residential"],
  "industrial-mechanical-hvac-engineering": ["mechanical-hvac", "industrial"],
  "plumbing-engineering": ["plumbing", "standard"],
  "commercial-plumbing-engineering": ["plumbing", "commercial"],
  "residential-plumbing-engineering": ["plumbing", "residential"],
  "industrial-plumbing-engineering": ["plumbing", "industrial"],
  "civil-engineering": ["civil", "standard"],
  "commercial-civil-engineering": ["civil", "commercial"],
  "residential-civil-engineering": ["civil", "residential"],
  "industrial-civil-engineering": ["civil", "industrial"],
};

const STATE_NOTES: Record<string, string> = {
  "Alabama": "Alabama has no statewide code \u2014 Birmingham, Huntsville, and coastal cities enforce IBC-family codes locally. Hurricane provisions on the Gulf Coast; red clay and high water tables inland.",
  "Arizona": "Arizona jurisdictions adopt IBC-family codes with local amendments. Extreme heat drives cooling-dominated mechanical design and thermal expansion detailing; expansive soils in parts of the Valley require careful geotechnical coordination for foundations.",
  "Arkansas": "Arkansas adopts IBC-family codes. New Madrid seismic zone in the northeast, expansive soils, and heavy rainfall shape foundation and site design.",
  "California": "California enforces the California Building Code (Title 24), including the nation's strictest energy standards. Seismic design per CBC/ASCE 7 is mandatory statewide; our engineers detail for high seismic design categories daily.",
  "Colorado": "Colorado jurisdictions adopt IBC-family codes. High-altitude and snow-load design govern mountain markets; expansive soils along the Front Range require specialized foundation engineering.",
  "District of Columbia": "DC enforces its own building code (IBC-family) with rigorous plan review. Urban infill, historic overlays, and DDOT public-space coordination are standard parts of every project.",
  "Florida": "Florida enforces the Florida Building Code \u2014 the nation's strictest hurricane code. Wind-borne debris regions, flood zones, and high water tables drive structural, envelope, and site engineering on every project.",
  "Georgia": "Georgia adopts IBC-family codes statewide with amendments. Hurricane provisions apply along the coast; red clay soils and heavy rainfall shape foundation and stormwater design inland.",
  "Illinois": "Illinois municipalities adopt IBC-family codes (Chicago has its own building code). Freeze-thaw cycles, snow loads, and deep frost-depth footings govern structural and site design.",
  "Indiana": "Indiana enforces its state building code (IBC-family). Snow, freeze-thaw, and lake-effect conditions in the north drive structural and envelope decisions.",
  "Kentucky": "Kentucky enforces its building code (IBC-family) statewide. New Madrid seismic considerations in the west, freeze-thaw cycles, and karst topography in places drive design.",
  "Louisiana": "Louisiana enforces its state uniform construction code (IBC-family). Hurricane wind design, flood zones, and soft delta soils make geotechnical coordination essential on every project.",
  "Maryland": "Maryland adopts IBC-family codes with state amendments. Chesapeake Bay critical-area rules affect waterfront sites; snow loads apply in western counties.",
  "Massachusetts": "Massachusetts enforces its state building code (IBC-family) with strict energy provisions (Stretch Code in many municipalities). Snow, freeze-thaw, and historic building stock are constant factors.",
  "Michigan": "Michigan adopts IBC-family codes. Heavy snow loads, deep frost depths, and freeze-thaw durability govern structural and site design statewide.",
  "Minnesota": "Minnesota enforces its state building code with among the nation's strictest energy requirements. Extreme cold, deep frost, and snow loads drive every engineering decision.",
  "Missouri": "Missouri has no statewide code \u2014 St. Louis and Kansas City each enforce IBC-family codes locally. New Madrid seismic zone affects the southeast; freeze-thaw governs the rest.",
  "Nevada": "Nevada adopts IBC-family codes with amendments. Seismic design applies in the Reno/Tahoe corridor; extreme heat in Las Vegas drives cooling-load and energy-code strategy.",
  "New Mexico": "New Mexico adopts IBC-family codes. High desert climate, expansive soils, and seismic provisions in the Rio Grande corridor drive design decisions.",
  "New York": "New York City enforces its own NYC Building Code; the rest of the state uses IBC-family codes. Snow loads upstate, flood zones, and dense urban logistics shape engineering statewide.",
  "North Carolina": "North Carolina enforces its state building code (IBC-family). Hurricane provisions on the coast, snow in the mountains, and red-clay soils statewide shape engineering decisions.",
  "Ohio": "Ohio enforces the Ohio Building Code (IBC-family) statewide. Snow loads along Lake Erie, freeze-thaw cycles, and expansive clays in the southwest shape design.",
  "Oklahoma": "Oklahoma adopts IBC-family codes. Tornado and high-wind design is critical statewide; expansive clay soils demand careful foundation engineering.",
  "Oregon": "Oregon enforces the Oregon Structural Specialty Code (IBC-family) with strong energy provisions. Cascadia seismic requirements and persistent rainfall shape design west of the Cascades.",
  "Pennsylvania": "Pennsylvania enforces the Uniform Construction Code (IBC-family) statewide. Snow loads, freeze-thaw durability, and older-city infill conditions drive design.",
  "Tennessee": "Tennessee adopts IBC-family codes. Seismic design applies in the New Madrid zone near Memphis; the rest of the state focuses on wind, rain, and expansive-soil foundation design.",
  "Texas": "Texas has no statewide building code \u2014 each municipality adopts its own (typically IBC-family). Wind design along the Gulf Coast follows hurricane provisions; expansive clay soils statewide demand pier-and-beam or post-tensioned slab expertise.",
  "Utah": "Utah adopts IBC-family codes. High seismic design categories along the Wasatch Front, snow loads in mountain markets, and expansive soils require specialized engineering.",
  "Virginia": "Virginia enforces the Uniform Statewide Building Code (IBC-family). Hurricane provisions in Hampton Roads, snow in the west, and Chesapeake Bay regulations shape engineering.",
  "Washington": "Washington adopts the IBC with state amendments and enforces the Washington State Energy Code. Seismic requirements apply west of the Cascades; wet climate demands careful envelope and drainage design.",
  "Wisconsin": "Wisconsin enforces its commercial building code (IBC-family). Extreme cold, deep frost footings, and heavy snow loads govern engineering statewide.",
};

const METRO_NOTES: Record<string, string> = {
  "Albuquerque": "High-desert climate, expansive soils, and Rio Grande corridor seismic provisions define the market. Federal lab-adjacent work requires precision and security awareness.",
  "Atlanta": "Red clay soils, heavy rainfall, and hurricane-season wind provisions shape Atlanta engineering. The logistics boom along I-75/I-85 drives massive warehouse and distribution work.",
  "Austin": "Central Texas expansive soils and flash-flood hydrology define site and structural work. The tech boom drives high-end office, multifamily, and mixed-use at breakneck speed.",
  "Baltimore": "Chesapeake Bay critical-area rules, historic building stock, and urban infill define Baltimore work. Port and logistics markets add industrial engineering demand.",
  "Birmingham": "Red clay, heavy rainfall, and hurricane-season remnants define Birmingham work. Healthcare (UAB) and automotive-supplier industrial are core markets.",
  "Boston": "Strict energy stretch codes, heavy snow, and 300-year-old building stock define Boston engineering. Lab and life-sciences work in Cambridge requires precision MEP.",
  "Charlotte": "The banking capital's office and mixed-use boom pairs with red-clay soils and heavy summer storms. Data center growth in the region adds mission-critical MEP work.",
  "Chicago": "Deep frost footings, heavy snow loads, and Chicago's own building code separate it from the rest of Illinois. High-rise, institutional, and cold-storage industrial are core markets.",
  "Cincinnati": "Ohio River valley freeze-thaw, clay soils, and hillside geotechnical work shape Cincinnati projects. Consumer-goods and logistics markets drive industrial volume.",
  "Cleveland": "Lake-effect snow loads are among the heaviest in the nation; freeze-thaw durability is critical. Healthcare and manufacturing anchor the engineering market.",
  "Columbus": "Ohio State and the tech corridor (Intel) fuel institutional and advanced-manufacturing work. Freeze-thaw cycles and clay soils are standard design factors.",
  "Dallas": "North Texas expansive clays make foundation engineering the first conversation on every project. DFW's corporate-relocation boom drives office, data center, and mixed-use work at a relentless pace.",
  "Denver": "Front Range expansive soils and mountain snow loads require location-specific structural judgment. Rapid growth in multifamily, office, and industrial keeps all disciplines in demand.",
  "Detroit": "Freeze-thaw durability and industrial adaptive reuse are Detroit signatures. The manufacturing resurgence drives heavy industrial and automotive-facility engineering.",
  "El Paso": "Desert climate with Chihuahuan temperature swings; proximity to Juarez maquiladora corridor drives industrial engineering. Wind and dust detailing matter.",
  "Houston": "Gulf Coast hurricane wind provisions, flood-plain regulations, and soft soils define Houston engineering. The energy corridor and medical center generate constant institutional and industrial work.",
  "Indianapolis": "Logistics crossroads of America \u2014 warehouse and distribution engineering at scale. Snow, freeze-thaw, and lake-effect weather in the northern suburbs.",
  "Jacksonville": "Northeast Florida's hurricane exposure and high water tables govern structural and site design. Port logistics and explosive suburban growth drive volume.",
  "Kansas City": "Tornado and high-wind design is non-negotiable; expansive clays complicate foundations. The logistics corridor along I-70 drives big-box industrial work.",
  "Las Vegas": "Extreme heat and cooling-dominated loads shape mechanical design; resort and hospitality work demands fast-track MEP delivery. Seismic provisions apply and are often underestimated.",
  "Little Rock": "New Madrid seismic proximity, expansive soils, and heavy rainfall shape Little Rock engineering. State government and medical markets anchor institutional work.",
  "Los Angeles": "High seismic design categories and Title 24 energy compliance shape every LA project. Dense urban infill, adaptive reuse, and soft-story retrofit programs create steady structural demand.",
  "Louisville": "Ohio River flood considerations, karst topography in the region, and freeze-thaw cycles define Louisville engineering. UPS Worldport logistics work is a constant.",
  "Memphis": "New Madrid seismic zone makes structural detailing critical \u2014 the highest seismic risk in the central US. Logistics (FedEx hub) drives massive distribution-center engineering.",
  "Miami": "Florida Building Code high-velocity hurricane zone requirements govern everything \u2014 impact glazing, roof pressures, flood elevation. Corrosion-resistant detailing is mandatory near saltwater.",
  "Milwaukee": "Lake-effect snow, deep frost, and freeze-thaw durability govern Milwaukee design. Brewing, manufacturing, and cold-storage markets are local specialties.",
  "Minneapolis": "Among the nation's toughest energy codes and deepest frost depths. Extreme cold-weather mechanical design and snow-load structures are daily work.",
  "Nashville": "Middle Tennessee's explosive growth means production multifamily and mixed-use at scale. Karst topography in places requires geotechnical attention for foundations.",
  "New Orleans": "Below-sea-level flood protection, hurricane wind design, and delta soft soils make New Orleans uniquely demanding. Every foundation starts with geotechnical strategy.",
  "New York": "NYC's own building code, supertall structural demands, and flood-zone rules make it the nation's most complex market. Outer-borough industrial and residential work moves faster but still demands rigor.",
  "Oklahoma City": "Tornado Alley wind design and expansive red clay are the defining challenges. Energy-sector and logistics work provide steady industrial volume.",
  "Orlando": "Hurricane wind design and high water tables define Central Florida engineering. Hospitality, theme-park-adjacent, and explosive residential growth drive volume.",
  "Philadelphia": "Older building stock means constant structural assessment, retrofit, and adaptive-reuse work. Snow loads and freeze-thaw durability govern new construction.",
  "Phoenix": "Extreme desert heat makes cooling-load accuracy and energy-code compliance the central mechanical challenge. The nation's fastest-growing major market means high-volume production work \u2014 subdivisions, multifamily, and logistics \u2014 where fast engineering turnaround wins bids.",
  "Pittsburgh": "Steep-slope geotechnical challenges, historic steel-town building stock, and freeze-thaw cycles define Pittsburgh. Robotics and eds/meds markets add modern facility work.",
  "Portland": "Cascadia seismic design and Oregon's strong energy code are the baseline. Persistent rain demands excellent envelope and stormwater engineering.",
  "Raleigh": "Research Triangle institutional and lab work demands precise MEP engineering. Clay soils and hurricane-season rainfall shape site and structural decisions.",
  "Richmond": "State-capital institutional work plus hurricane-season wind and Chesapeake Bay watershed rules. Historic districts require sensitive structural approaches.",
  "Salt Lake City": "Wasatch Front high seismic categories plus snow loads make structural engineering demanding. Rapid growth in tech and logistics adds commercial volume.",
  "San Antonio": "Expansive clays and South Texas heat govern foundation and mechanical design. Military, medical, and logistics markets provide steady institutional work.",
  "San Diego": "Coastal corrosion, mild seismic requirements, and California's strict energy code govern San Diego work. Biotech and defense-adjacent markets drive specialized facility engineering.",
  "San Francisco": "Some of the nation's highest seismic design categories plus Title 24 energy rules. Tight urban sites, historic building stock, and mandatory retrofit ordinances keep structural engineers busy.",
  "Seattle": "Cascadia seismic design and the Washington State Energy Code are the twin drivers. The tech economy fuels office, lab, and data center construction across the metro.",
  "St. Louis": "The metro straddles two states with different code regimes \u2014 we handle both. Expansive clays, freeze-thaw, and Mississippi River flood considerations shape design.",
  "Tampa": "Tampa Bay's hurricane exposure and flood zones require careful structural and site engineering. Rapid growth in multifamily and healthcare keeps MEP teams busy.",
  "Tucson": "Sonoran Desert heat and monsoon-season cloudbursts shape mechanical and site design. Lower seismicity than Phoenix but identical expansive-soil challenges.",
  "Tulsa": "Same Tornado Alley and clay-soil challenges as OKC, with a strong historic-building retrofit market downtown. Energy and aerospace-adjacent manufacturing add specialty work.",
  "Virginia Beach": "Hampton Roads hurricane wind provisions and flood zones are mandatory design inputs. Military-adjacent work demands security-aware engineering.",
  "Washington": "DC's rigorous plan review, historic overlays, and DDOT public-space rules make permitting the critical path. Secure-facility and institutional work is a specialty market.",
};

// city-state slug pair -> metro name, for metro market notes
// state slug -> abbreviation (for cohort IDs)
const STATE_ABBR: Record<string, string> = {
  "alabama": "al",
  "arizona": "az",
  "arkansas": "ar",
  "california": "ca",
  "colorado": "co",
  "florida": "fl",
  "georgia": "ga",
  "illinois": "il",
  "indiana": "in",
  "kentucky": "ky",
  "louisiana": "la",
  "maryland": "md",
  "massachusetts": "ma",
  "michigan": "mi",
  "minnesota": "mn",
  "missouri": "mo",
  "nevada": "nv",
  "new-mexico": "nm",
  "new-york": "ny",
  "north-carolina": "nc",
  "ohio": "oh",
  "oklahoma": "ok",
  "oregon": "or",
  "pennsylvania": "pa",
  "tennessee": "tn",
  "texas": "tx",
  "utah": "ut",
  "virginia": "va",
  "washington": "wa",
  "wisconsin": "wi",
};

const CITY_TO_METRO: Record<string, string> = {
  "phoenix/arizona": "Phoenix",
  "mesa/arizona": "Phoenix",
  "chandler/arizona": "Phoenix",
  "scottsdale/arizona": "Phoenix",
  "tempe/arizona": "Phoenix",
  "goodyear/arizona": "Phoenix",
  "yuma/arizona": "Phoenix",
  "flagstaff/arizona": "Phoenix",
  "maricopa/arizona": "Phoenix",
  "lake-havasu-city/arizona": "Phoenix",
  "prescott-valley/arizona": "Phoenix",
  "prescott/arizona": "Phoenix",
  "bullhead-city/arizona": "Phoenix",
  "san-luis/arizona": "Phoenix",
  "sahuarita/arizona": "Phoenix",
  "florence/arizona": "Phoenix",
  "nogales/arizona": "Phoenix",
  "coolidge/arizona": "Phoenix",
  "douglas/arizona": "Phoenix",
  "chino-valley/arizona": "Phoenix",
  "cottonwood/arizona": "Phoenix",
  "show-low/arizona": "Phoenix",
  "dallas/texas": "Dallas",
  "fort-worth/texas": "Dallas",
  "laredo/texas": "Dallas",
  "amarillo/texas": "Dallas",
  "pasadena/texas": "Dallas",
  "carrollton/texas": "Dallas",
  "college-station/texas": "Dallas",
  "allen/texas": "Dallas",
  "wichita-falls/texas": "Dallas",
  "mission/texas": "Dallas",
  "flower-mound/texas": "Dallas",
  "harlingen/texas": "Dallas",
  "rowlett/texas": "Dallas",
  "port-arthur/texas": "Dallas",
  "rockwall/texas": "Dallas",
  "sherman/texas": "Dallas",
  "schertz/texas": "Dallas",
  "rosenberg/texas": "Dallas",
  "prosper/texas": "Dallas",
  "texarkana/texas": "Dallas",
  "del-rio/texas": "Dallas",
  "deer-park/texas": "Dallas",
  "houston/texas": "Houston",
  "arlington/texas": "Houston",
  "irving/texas": "Houston",
  "grand-prairie/texas": "Houston",
  "mesquite/texas": "Houston",
  "lewisville/texas": "Houston",
  "richardson/texas": "Houston",
  "sugar-land/texas": "Houston",
  "conroe/texas": "Houston",
  "georgetown/texas": "Houston",
  "cedar-park/texas": "Houston",
  "san-marcos/texas": "Houston",
  "euless/texas": "Houston",
  "texas-city/texas": "Houston",
  "grapevine/texas": "Houston",
  "keller/texas": "Houston",
  "weslaco/texas": "Houston",
  "hurst/texas": "Houston",
  "socorro/texas": "Houston",
  "weatherford/texas": "Houston",
  "cleburne/texas": "Houston",
  "seguin/texas": "Houston",
  "los-angeles/california": "Los Angeles",
  "san-jose/california": "Los Angeles",
  "long-beach/california": "Los Angeles",
  "anaheim/california": "Los Angeles",
  "santa-ana/california": "Los Angeles",
  "santa-clarita/california": "Los Angeles",
  "modesto/california": "Los Angeles",
  "oxnard/california": "Los Angeles",
  "ontario/california": "Los Angeles",
  "rancho-cucamonga/california": "Los Angeles",
  "lancaster/california": "Los Angeles",
  "corona/california": "Los Angeles",
  "sunnyvale/california": "Los Angeles",
  "visalia/california": "Los Angeles",
  "orange/california": "Los Angeles",
  "santa-clara/california": "Los Angeles",
  "clovis/california": "Los Angeles",
  "fairfield/california": "Los Angeles",
  "richmond/california": "Los Angeles",
  "temecula/california": "Los Angeles",
  "costa-mesa/california": "Los Angeles",
  "west-covina/california": "Los Angeles",
  "san-diego/california": "San Diego",
  "fresno/california": "San Diego",
  "oakland/california": "San Diego",
  "stockton/california": "San Diego",
  "irvine/california": "San Diego",
  "fremont/california": "San Diego",
  "fontana/california": "San Diego",
  "huntington-beach/california": "San Diego",
  "elk-grove/california": "San Diego",
  "oceanside/california": "San Diego",
  "palmdale/california": "San Diego",
  "hayward/california": "San Diego",
  "escondido/california": "San Diego",
  "torrance/california": "San Diego",
  "victorville/california": "San Diego",
  "simi-valley/california": "San Diego",
  "vallejo/california": "San Diego",
  "berkeley/california": "San Diego",
  "carlsbad/california": "San Diego",
  "downey/california": "San Diego",
  "menifee/california": "San Diego",
  "jurupa-valley/california": "San Diego",
  "san-francisco/california": "San Francisco",
  "sacramento/california": "San Francisco",
  "bakersfield/california": "San Francisco",
  "riverside/california": "San Francisco",
  "chula-vista/california": "San Francisco",
  "san-bernardino/california": "San Francisco",
  "moreno-valley/california": "San Francisco",
  "glendale/california": "San Francisco",
  "santa-rosa/california": "San Francisco",
  "garden-grove/california": "San Francisco",
  "salinas/california": "San Francisco",
  "roseville/california": "San Francisco",
  "pomona/california": "San Francisco",
  "fullerton/california": "San Francisco",
  "pasadena/california": "San Francisco",
  "thousand-oaks/california": "San Francisco",
  "concord/california": "San Francisco",
  "antioch/california": "San Francisco",
  "murrieta/california": "San Francisco",
  "santa-maria/california": "San Francisco",
  "san-buenaventura-ventura/california": "San Francisco",
  "el-monte/california": "San Francisco",
  "seattle/washington": "Seattle",
  "spokane/washington": "Seattle",
  "tacoma/washington": "Seattle",
  "vancouver/washington": "Seattle",
  "bellevue/washington": "Seattle",
  "kent/washington": "Seattle",
  "everett/washington": "Seattle",
  "spokane-valley/washington": "Seattle",
  "renton/washington": "Seattle",
  "federal-way/washington": "Seattle",
  "yakima/washington": "Seattle",
  "bellingham/washington": "Seattle",
  "kirkland/washington": "Seattle",
  "auburn/washington": "Seattle",
  "kennewick/washington": "Seattle",
  "pasco/washington": "Seattle",
  "redmond/washington": "Seattle",
  "marysville/washington": "Seattle",
  "sammamish/washington": "Seattle",
  "lakewood/washington": "Seattle",
  "richland/washington": "Seattle",
  "shoreline/washington": "Seattle",
  "denver/colorado": "Denver",
  "colorado-springs/colorado": "Denver",
  "aurora/colorado": "Denver",
  "fort-collins/colorado": "Denver",
  "lakewood/colorado": "Denver",
  "thornton/colorado": "Denver",
  "arvada/colorado": "Denver",
  "westminster/colorado": "Denver",
  "pueblo/colorado": "Denver",
  "greeley/colorado": "Denver",
  "centennial/colorado": "Denver",
  "boulder/colorado": "Denver",
  "longmont/colorado": "Denver",
  "castle-rock/colorado": "Denver",
  "loveland/colorado": "Denver",
  "broomfield/colorado": "Denver",
  "grand-junction/colorado": "Denver",
  "commerce-city/colorado": "Denver",
  "parker/colorado": "Denver",
  "littleton/colorado": "Denver",
  "brighton/colorado": "Denver",
  "northglenn/colorado": "Denver",
  "las-vegas/nevada": "Las Vegas",
  "henderson/nevada": "Las Vegas",
  "north-las-vegas/nevada": "Las Vegas",
  "reno/nevada": "Las Vegas",
  "sparks/nevada": "Las Vegas",
  "carson-city/nevada": "Las Vegas",
  "fernley/nevada": "Las Vegas",
  "mesquite/nevada": "Las Vegas",
  "elko/nevada": "Las Vegas",
  "boulder-city/nevada": "Las Vegas",
  "fallon/nevada": "Las Vegas",
  "winnemucca/nevada": "Las Vegas",
  "west-wendover/nevada": "Las Vegas",
  "ely/nevada": "Las Vegas",
  "yerington/nevada": "Las Vegas",
  "carlin/nevada": "Las Vegas",
  "lovelock/nevada": "Las Vegas",
  "wells/nevada": "Las Vegas",
  "caliente/nevada": "Las Vegas",
  "austin/texas": "Austin",
  "corpus-christi/texas": "Austin",
  "garland/texas": "Austin",
  "brownsville/texas": "Austin",
  "mcallen/texas": "Austin",
  "abilene/texas": "Austin",
  "league-city/texas": "Austin",
  "tyler/texas": "Austin",
  "san-angelo/texas": "Austin",
  "baytown/texas": "Austin",
  "mansfield/texas": "Austin",
  "north-richland-hills/texas": "Austin",
  "wylie/texas": "Austin",
  "little-elm/texas": "Austin",
  "bedford/texas": "Austin",
  "haltom-city/texas": "Austin",
  "coppell/texas": "Austin",
  "duncanville/texas": "Austin",
  "la-porte/texas": "Austin",
  "hutto/texas": "Austin",
  "celina/texas": "Austin",
  "nacogdoches/texas": "Austin",
  "san-antonio/texas": "San Antonio",
  "plano/texas": "San Antonio",
  "frisco/texas": "San Antonio",
  "killeen/texas": "San Antonio",
  "waco/texas": "San Antonio",
  "round-rock/texas": "San Antonio",
  "odessa/texas": "San Antonio",
  "new-braunfels/texas": "San Antonio",
  "temple/texas": "San Antonio",
  "longview/texas": "San Antonio",
  "missouri-city/texas": "San Antonio",
  "pflugerville/texas": "San Antonio",
  "kyle/texas": "San Antonio",
  "galveston/texas": "San Antonio",
  "cedar-hill/texas": "San Antonio",
  "the-colony/texas": "San Antonio",
  "friendswood/texas": "San Antonio",
  "midlothian/texas": "San Antonio",
  "farmers-branch/texas": "San Antonio",
  "cibolo/texas": "San Antonio",
  "lufkin/texas": "San Antonio",
  "forney/texas": "San Antonio",
  "chicago/illinois": "Chicago",
  "aurora/illinois": "Chicago",
  "naperville/illinois": "Chicago",
  "joliet/illinois": "Chicago",
  "rockford/illinois": "Chicago",
  "elgin/illinois": "Chicago",
  "springfield/illinois": "Chicago",
  "peoria/illinois": "Chicago",
  "champaign/illinois": "Chicago",
  "waukegan/illinois": "Chicago",
  "cicero/illinois": "Chicago",
  "bloomington/illinois": "Chicago",
  "schaumburg/illinois": "Chicago",
  "evanston/illinois": "Chicago",
  "arlington-heights/illinois": "Chicago",
  "bolingbrook/illinois": "Chicago",
  "decatur/illinois": "Chicago",
  "palatine/illinois": "Chicago",
  "skokie/illinois": "Chicago",
  "des-plaines/illinois": "Chicago",
  "orland-park/illinois": "Chicago",
  "oak-lawn/illinois": "Chicago",
  "atlanta/georgia": "Atlanta",
  "columbus/georgia": "Atlanta",
  "macon-bibb-county/georgia": "Atlanta",
  "savannah/georgia": "Atlanta",
  "south-fulton/georgia": "Atlanta",
  "sandy-springs/georgia": "Atlanta",
  "roswell/georgia": "Atlanta",
  "warner-robins/georgia": "Atlanta",
  "johns-creek/georgia": "Atlanta",
  "mableton/georgia": "Atlanta",
  "stonecrest/georgia": "Atlanta",
  "peachtree-corners/georgia": "Atlanta",
  "milton/georgia": "Atlanta",
  "statesboro/georgia": "Atlanta",
  "lagrange/georgia": "Atlanta",
  "chamblee/georgia": "Atlanta",
  "pooler/georgia": "Atlanta",
  "union-city/georgia": "Atlanta",
  "sugar-hill/georgia": "Atlanta",
  "griffin/georgia": "Atlanta",
  "perry/georgia": "Atlanta",
  "kingsland/georgia": "Atlanta",
  "miami/florida": "Miami",
  "st-petersburg/florida": "Miami",
  "tallahassee/florida": "Miami",
  "gainesville/florida": "Miami",
  "west-palm-beach/florida": "Miami",
  "miami-gardens/florida": "Miami",
  "sunrise/florida": "Miami",
  "deerfield-beach/florida": "Miami",
  "largo/florida": "Miami",
  "doral/florida": "Miami",
  "weston/florida": "Miami",
  "port-orange/florida": "Miami",
  "palm-beach-gardens/florida": "Miami",
  "apopka/florida": "Miami",
  "winter-haven/florida": "Miami",
  "titusville/florida": "Miami",
  "clermont/florida": "Miami",
  "oakland-park/florida": "Miami",
  "lake-worth-beach/florida": "Miami",
  "oviedo/florida": "Miami",
  "riviera-beach/florida": "Miami",
  "dunedin/florida": "Miami",
  "orlando/florida": "Orlando",
  "port-st-lucie/florida": "Orlando",
  "fort-lauderdale/florida": "Orlando",
  "miramar/florida": "Orlando",
  "lakeland/florida": "Orlando",
  "davie/florida": "Orlando",
  "deltona/florida": "Orlando",
  "melbourne/florida": "Orlando",
  "miami-beach/florida": "Orlando",
  "daytona-beach/florida": "Orlando",
  "delray-beach/florida": "Orlando",
  "sanford/florida": "Orlando",
  "north-miami/florida": "Orlando",
  "bradenton/florida": "Orlando",
  "pensacola/florida": "Orlando",
  "fort-pierce/florida": "Orlando",
  "altamonte-springs/florida": "Orlando",
  "greenacres/florida": "Orlando",
  "hallandale-beach/florida": "Orlando",
  "royal-palm-beach/florida": "Orlando",
  "estero/florida": "Orlando",
  "panama-city/florida": "Orlando",
  "tampa/florida": "Tampa",
  "hialeah/florida": "Tampa",
  "pembroke-pines/florida": "Tampa",
  "coral-springs/florida": "Tampa",
  "clearwater/florida": "Tampa",
  "boca-raton/florida": "Tampa",
  "plantation/florida": "Tampa",
  "north-port/florida": "Tampa",
  "kissimmee/florida": "Tampa",
  "lauderhill/florida": "Tampa",
  "ocala/florida": "Tampa",
  "wellington/florida": "Tampa",
  "margate/florida": "Tampa",
  "sarasota/florida": "Tampa",
  "pinellas-park/florida": "Tampa",
  "ocoee/florida": "Tampa",
  "north-lauderdale/florida": "Tampa",
  "ormond-beach/florida": "Tampa",
  "deland/florida": "Tampa",
  "aventura/florida": "Tampa",
  "parkland/florida": "Tampa",
  "cooper-city/florida": "Tampa",
  "memphis/tennessee": "Nashville",
  "knoxville/tennessee": "Nashville",
  "clarksville/tennessee": "Nashville",
  "franklin/tennessee": "Nashville",
  "jackson/tennessee": "Nashville",
  "bartlett/tennessee": "Nashville",
  "kingsport/tennessee": "Nashville",
  "collierville/tennessee": "Nashville",
  "gallatin/tennessee": "Nashville",
  "columbia/tennessee": "Nashville",
  "mount-juliet/tennessee": "Nashville",
  "la-vergne/tennessee": "Nashville",
  "oak-ridge/tennessee": "Nashville",
  "morristown/tennessee": "Nashville",
  "shelbyville/tennessee": "Nashville",
  "east-ridge/tennessee": "Nashville",
  "springfield/tennessee": "Nashville",
  "goodlettsville/tennessee": "Nashville",
  "dyersburg/tennessee": "Nashville",
  "arlington/tennessee": "Nashville",
  "white-house/tennessee": "Nashville",
  "elizabethton/tennessee": "Nashville",
  "charlotte/north-carolina": "Charlotte",
  "greensboro/north-carolina": "Charlotte",
  "winston-salem/north-carolina": "Charlotte",
  "cary/north-carolina": "Charlotte",
  "high-point/north-carolina": "Charlotte",
  "asheville/north-carolina": "Charlotte",
  "gastonia/north-carolina": "Charlotte",
  "apex/north-carolina": "Charlotte",
  "chapel-hill/north-carolina": "Charlotte",
  "kannapolis/north-carolina": "Charlotte",
  "wake-forest/north-carolina": "Charlotte",
  "wilson/north-carolina": "Charlotte",
  "hickory/north-carolina": "Charlotte",
  "fuquay-varina/north-carolina": "Charlotte",
  "salisbury/north-carolina": "Charlotte",
  "goldsboro/north-carolina": "Charlotte",
  "new-bern/north-carolina": "Charlotte",
  "morrisville/north-carolina": "Charlotte",
  "statesville/north-carolina": "Charlotte",
  "clayton/north-carolina": "Charlotte",
  "asheboro/north-carolina": "Charlotte",
  "thomasville/north-carolina": "Charlotte",
  "raleigh/north-carolina": "Raleigh",
  "durham/north-carolina": "Raleigh",
  "fayetteville/north-carolina": "Raleigh",
  "wilmington/north-carolina": "Raleigh",
  "concord/north-carolina": "Raleigh",
  "greenville/north-carolina": "Raleigh",
  "jacksonville/north-carolina": "Raleigh",
  "huntersville/north-carolina": "Raleigh",
  "burlington/north-carolina": "Raleigh",
  "rocky-mount/north-carolina": "Raleigh",
  "mooresville/north-carolina": "Raleigh",
  "holly-springs/north-carolina": "Raleigh",
  "indian-trail/north-carolina": "Raleigh",
  "monroe/north-carolina": "Raleigh",
  "garner/north-carolina": "Raleigh",
  "cornelius/north-carolina": "Raleigh",
  "sanford/north-carolina": "Raleigh",
  "matthews/north-carolina": "Raleigh",
  "leland/north-carolina": "Raleigh",
  "kernersville/north-carolina": "Raleigh",
  "mint-hill/north-carolina": "Raleigh",
  "waxhaw/north-carolina": "Raleigh",
  "baltimore/maryland": "Baltimore",
  "frederick/maryland": "Baltimore",
  "gaithersburg/maryland": "Baltimore",
  "rockville/maryland": "Baltimore",
  "bowie/maryland": "Baltimore",
  "hagerstown/maryland": "Baltimore",
  "annapolis/maryland": "Baltimore",
  "college-park/maryland": "Baltimore",
  "salisbury/maryland": "Baltimore",
  "laurel/maryland": "Baltimore",
  "greenbelt/maryland": "Baltimore",
  "hyattsville/maryland": "Baltimore",
  "westminster/maryland": "Baltimore",
  "cumberland/maryland": "Baltimore",
  "takoma-park/maryland": "Baltimore",
  "easton/maryland": "Baltimore",
  "aberdeen/maryland": "Baltimore",
  "elkton/maryland": "Baltimore",
  "havre-de-grace/maryland": "Baltimore",
  "new-carrollton/maryland": "Baltimore",
  "cambridge/maryland": "Baltimore",
  "la-plata/maryland": "Baltimore",
  "philadelphia/pennsylvania": "Philadelphia",
  "allentown/pennsylvania": "Philadelphia",
  "erie/pennsylvania": "Philadelphia",
  "scranton/pennsylvania": "Philadelphia",
  "harrisburg/pennsylvania": "Philadelphia",
  "wilkes-barre/pennsylvania": "Philadelphia",
  "state-college/pennsylvania": "Philadelphia",
  "norristown/pennsylvania": "Philadelphia",
  "mount-lebanon-municipality/pennsylvania": "Philadelphia",
  "hazleton/pennsylvania": "Philadelphia",
  "monroeville-municipality/pennsylvania": "Philadelphia",
  "plum/pennsylvania": "Philadelphia",
  "pottstown/pennsylvania": "Philadelphia",
  "carlisle/pennsylvania": "Philadelphia",
  "baldwin/pennsylvania": "Philadelphia",
  "west-chester/pennsylvania": "Philadelphia",
  "west-mifflin/pennsylvania": "Philadelphia",
  "johnstown/pennsylvania": "Philadelphia",
  "hanover/pennsylvania": "Philadelphia",
  "franklin-park/pennsylvania": "Philadelphia",
  "greensburg/pennsylvania": "Philadelphia",
  "dunmore/pennsylvania": "Philadelphia",
  "new-york/new-york": "New York",
  "buffalo/new-york": "New York",
  "yonkers/new-york": "New York",
  "rochester/new-york": "New York",
  "syracuse/new-york": "New York",
  "albany/new-york": "New York",
  "new-rochelle/new-york": "New York",
  "kiryas-joel/new-york": "New York",
  "spring-valley/new-york": "New York",
  "port-chester/new-york": "New York",
  "north-tonawanda/new-york": "New York",
  "harrison/new-york": "New York",
  "newburgh/new-york": "New York",
  "glen-cove/new-york": "New York",
  "lindenhurst/new-york": "New York",
  "ossining/new-york": "New York",
  "rockville-centre/new-york": "New York",
  "peekskill/new-york": "New York",
  "garden-city/new-york": "New York",
  "mineola/new-york": "New York",
  "lockport/new-york": "New York",
  "lynbrook/new-york": "New York",
  "boston/massachusetts": "Boston",
  "worcester/massachusetts": "Boston",
  "springfield/massachusetts": "Boston",
  "cambridge/massachusetts": "Boston",
  "lowell/massachusetts": "Boston",
  "brockton/massachusetts": "Boston",
  "quincy/massachusetts": "Boston",
  "lynn/massachusetts": "Boston",
  "new-bedford/massachusetts": "Boston",
  "fall-river/massachusetts": "Boston",
  "newton/massachusetts": "Boston",
  "lawrence/massachusetts": "Boston",
  "somerville/massachusetts": "Boston",
  "braintree-town/massachusetts": "Boston",
  "amherst-town/massachusetts": "Boston",
  "watertown/massachusetts": "Boston",
  "randolph-town/massachusetts": "Boston",
  "franklin-town/massachusetts": "Boston",
  "north-attleborough-town/massachusetts": "Boston",
  "melrose/massachusetts": "Boston",
  "west-springfield-town/massachusetts": "Boston",
  "agawam-town/massachusetts": "Boston",
  "detroit/michigan": "Detroit",
  "grand-rapids/michigan": "Detroit",
  "warren/michigan": "Detroit",
  "sterling-heights/michigan": "Detroit",
  "ann-arbor/michigan": "Detroit",
  "lansing/michigan": "Detroit",
  "dearborn/michigan": "Detroit",
  "livonia/michigan": "Detroit",
  "troy/michigan": "Detroit",
  "westland/michigan": "Detroit",
  "farmington-hills/michigan": "Detroit",
  "flint/michigan": "Detroit",
  "wyoming/michigan": "Detroit",
  "rochester-hills/michigan": "Detroit",
  "southfield/michigan": "Detroit",
  "kalamazoo/michigan": "Detroit",
  "kentwood/michigan": "Detroit",
  "battle-creek/michigan": "Detroit",
  "portage/michigan": "Detroit",
  "roseville/michigan": "Detroit",
  "east-lansing/michigan": "Detroit",
  "saginaw/michigan": "Detroit",
  "minneapolis/minnesota": "Minneapolis",
  "st-paul/minnesota": "Minneapolis",
  "rochester/minnesota": "Minneapolis",
  "bloomington/minnesota": "Minneapolis",
  "duluth/minnesota": "Minneapolis",
  "brooklyn-park/minnesota": "Minneapolis",
  "plymouth/minnesota": "Minneapolis",
  "woodbury/minnesota": "Minneapolis",
  "lakeville/minnesota": "Minneapolis",
  "blaine/minnesota": "Minneapolis",
  "maple-grove/minnesota": "Minneapolis",
  "st-cloud/minnesota": "Minneapolis",
  "eagan/minnesota": "Minneapolis",
  "burnsville/minnesota": "Minneapolis",
  "coon-rapids/minnesota": "Minneapolis",
  "eden-prairie/minnesota": "Minneapolis",
  "apple-valley/minnesota": "Minneapolis",
  "edina/minnesota": "Minneapolis",
  "minnetonka/minnesota": "Minneapolis",
  "st-louis-park/minnesota": "Minneapolis",
  "shakopee/minnesota": "Minneapolis",
  "mankato/minnesota": "Minneapolis",
  "st-louis/missouri": "St. Louis",
  "springfield/missouri": "St. Louis",
  "independence/missouri": "St. Louis",
  "o-fallon/missouri": "St. Louis",
  "st-joseph/missouri": "St. Louis",
  "st-peters/missouri": "St. Louis",
  "florissant/missouri": "St. Louis",
  "wentzville/missouri": "St. Louis",
  "cape-girardeau/missouri": "St. Louis",
  "university-city/missouri": "St. Louis",
  "liberty/missouri": "St. Louis",
  "kirkwood/missouri": "St. Louis",
  "gladstone/missouri": "St. Louis",
  "hazelwood/missouri": "St. Louis",
  "nixa/missouri": "St. Louis",
  "webster-groves/missouri": "St. Louis",
  "sedalia/missouri": "St. Louis",
  "rolla/missouri": "St. Louis",
  "warrensburg/missouri": "St. Louis",
  "farmington/missouri": "St. Louis",
  "manchester/missouri": "St. Louis",
  "kirksville/missouri": "St. Louis",
  "kansas-city/missouri": "Kansas City",
  "columbia/missouri": "Kansas City",
  "lee-s-summit/missouri": "Kansas City",
  "st-charles/missouri": "Kansas City",
  "blue-springs/missouri": "Kansas City",
  "joplin/missouri": "Kansas City",
  "chesterfield/missouri": "Kansas City",
  "jefferson-city/missouri": "Kansas City",
  "wildwood/missouri": "Kansas City",
  "ballwin/missouri": "Kansas City",
  "raytown/missouri": "Kansas City",
  "maryland-heights/missouri": "Kansas City",
  "grandview/missouri": "Kansas City",
  "belton/missouri": "Kansas City",
  "raymore/missouri": "Kansas City",
  "ozark/missouri": "Kansas City",
  "arnold/missouri": "Kansas City",
  "republic/missouri": "Kansas City",
  "creve-coeur/missouri": "Kansas City",
  "ferguson/missouri": "Kansas City",
  "lake-st-louis/missouri": "Kansas City",
  "clayton/missouri": "Kansas City",
  "columbus/ohio": "Columbus",
  "toledo/ohio": "Columbus",
  "parma/ohio": "Columbus",
  "hamilton/ohio": "Columbus",
  "kettering/ohio": "Columbus",
  "cuyahoga-falls/ohio": "Columbus",
  "dublin/ohio": "Columbus",
  "mentor/ohio": "Columbus",
  "fairfield/ohio": "Columbus",
  "huber-heights/ohio": "Columbus",
  "reynoldsburg/ohio": "Columbus",
  "westerville/ohio": "Columbus",
  "upper-arlington/ohio": "Columbus",
  "gahanna/ohio": "Columbus",
  "fairborn/ohio": "Columbus",
  "massillon/ohio": "Columbus",
  "bowling-green/ohio": "Columbus",
  "marysville/ohio": "Columbus",
  "wooster/ohio": "Columbus",
  "avon-lake/ohio": "Columbus",
  "centerville/ohio": "Columbus",
  "zanesville/ohio": "Columbus",
  "fort-wayne/indiana": "Indianapolis",
  "evansville/indiana": "Indianapolis",
  "south-bend/indiana": "Indianapolis",
  "fishers/indiana": "Indianapolis",
  "carmel/indiana": "Indianapolis",
  "bloomington/indiana": "Indianapolis",
  "hammond/indiana": "Indianapolis",
  "noblesville/indiana": "Indianapolis",
  "lafayette/indiana": "Indianapolis",
  "gary/indiana": "Indianapolis",
  "greenwood/indiana": "Indianapolis",
  "muncie/indiana": "Indianapolis",
  "kokomo/indiana": "Indianapolis",
  "terre-haute/indiana": "Indianapolis",
  "anderson/indiana": "Indianapolis",
  "westfield/indiana": "Indianapolis",
  "elkhart/indiana": "Indianapolis",
  "columbus/indiana": "Indianapolis",
  "jeffersonville/indiana": "Indianapolis",
  "mishawaka/indiana": "Indianapolis",
  "lawrence/indiana": "Indianapolis",
  "west-lafayette/indiana": "Indianapolis",
  "milwaukee/wisconsin": "Milwaukee",
  "madison/wisconsin": "Milwaukee",
  "green-bay/wisconsin": "Milwaukee",
  "kenosha/wisconsin": "Milwaukee",
  "racine/wisconsin": "Milwaukee",
  "appleton/wisconsin": "Milwaukee",
  "waukesha/wisconsin": "Milwaukee",
  "eau-claire/wisconsin": "Milwaukee",
  "oshkosh/wisconsin": "Milwaukee",
  "janesville/wisconsin": "Milwaukee",
  "west-allis/wisconsin": "Milwaukee",
  "la-crosse/wisconsin": "Milwaukee",
  "sheboygan/wisconsin": "Milwaukee",
  "wauwatosa/wisconsin": "Milwaukee",
  "fond-du-lac/wisconsin": "Milwaukee",
  "brookfield/wisconsin": "Milwaukee",
  "new-berlin/wisconsin": "Milwaukee",
  "wausau/wisconsin": "Milwaukee",
  "menomonee-falls/wisconsin": "Milwaukee",
  "sun-prairie/wisconsin": "Milwaukee",
  "greenfield/wisconsin": "Milwaukee",
  "oak-creek/wisconsin": "Milwaukee",
  "portland/oregon": "Portland",
  "eugene/oregon": "Portland",
  "salem/oregon": "Portland",
  "gresham/oregon": "Portland",
  "hillsboro/oregon": "Portland",
  "bend/oregon": "Portland",
  "beaverton/oregon": "Portland",
  "medford/oregon": "Portland",
  "springfield/oregon": "Portland",
  "corvallis/oregon": "Portland",
  "albany/oregon": "Portland",
  "tigard/oregon": "Portland",
  "lake-oswego/oregon": "Portland",
  "grants-pass/oregon": "Portland",
  "keizer/oregon": "Portland",
  "oregon-city/oregon": "Portland",
  "redmond/oregon": "Portland",
  "mcminnville/oregon": "Portland",
  "woodburn/oregon": "Portland",
  "tualatin/oregon": "Portland",
  "wilsonville/oregon": "Portland",
  "west-linn/oregon": "Portland",
  "salt-lake-city/utah": "Salt Lake City",
  "west-valley-city/utah": "Salt Lake City",
  "west-jordan/utah": "Salt Lake City",
  "provo/utah": "Salt Lake City",
  "st-george/utah": "Salt Lake City",
  "orem/utah": "Salt Lake City",
  "sandy/utah": "Salt Lake City",
  "ogden/utah": "Salt Lake City",
  "lehi/utah": "Salt Lake City",
  "layton/utah": "Salt Lake City",
  "south-jordan/utah": "Salt Lake City",
  "millcreek/utah": "Salt Lake City",
  "herriman/utah": "Salt Lake City",
  "taylorsville/utah": "Salt Lake City",
  "logan/utah": "Salt Lake City",
  "eagle-mountain/utah": "Salt Lake City",
  "draper/utah": "Salt Lake City",
  "murray/utah": "Salt Lake City",
  "saratoga-springs/utah": "Salt Lake City",
  "riverton/utah": "Salt Lake City",
  "bountiful/utah": "Salt Lake City",
  "spanish-fork/utah": "Salt Lake City",
  "albuquerque/new-mexico": "Albuquerque",
  "las-cruces/new-mexico": "Albuquerque",
  "rio-rancho/new-mexico": "Albuquerque",
  "santa-fe/new-mexico": "Albuquerque",
  "roswell/new-mexico": "Albuquerque",
  "farmington/new-mexico": "Albuquerque",
  "hobbs/new-mexico": "Albuquerque",
  "clovis/new-mexico": "Albuquerque",
  "carlsbad/new-mexico": "Albuquerque",
  "alamogordo/new-mexico": "Albuquerque",
  "gallup/new-mexico": "Albuquerque",
  "los-lunas/new-mexico": "Albuquerque",
  "sunland-park/new-mexico": "Albuquerque",
  "deming/new-mexico": "Albuquerque",
  "las-vegas/new-mexico": "Albuquerque",
  "artesia/new-mexico": "Albuquerque",
  "portales/new-mexico": "Albuquerque",
  "lovington/new-mexico": "Albuquerque",
  "espa-ola/new-mexico": "Albuquerque",
  "silver-city/new-mexico": "Albuquerque",
  "bernalillo/new-mexico": "Albuquerque",
  "grants/new-mexico": "Albuquerque",
  "tucson/arizona": "Tucson",
  "gilbert/arizona": "Tucson",
  "glendale/arizona": "Tucson",
  "peoria/arizona": "Tucson",
  "surprise/arizona": "Tucson",
  "buckeye/arizona": "Tucson",
  "avondale/arizona": "Tucson",
  "queen-creek/arizona": "Tucson",
  "casa-grande/arizona": "Tucson",
  "marana/arizona": "Tucson",
  "oro-valley/arizona": "Tucson",
  "sierra-vista/arizona": "Tucson",
  "apache-junction/arizona": "Tucson",
  "el-mirage/arizona": "Tucson",
  "kingman/arizona": "Tucson",
  "fountain-hills/arizona": "Tucson",
  "eloy/arizona": "Tucson",
  "payson/arizona": "Tucson",
  "somerton/arizona": "Tucson",
  "paradise-valley/arizona": "Tucson",
  "camp-verde/arizona": "Tucson",
  "safford/arizona": "Tucson",
  "el-paso/texas": "El Paso",
  "lubbock/texas": "El Paso",
  "mckinney/texas": "El Paso",
  "denton/texas": "El Paso",
  "midland/texas": "El Paso",
  "pearland/texas": "El Paso",
  "beaumont/texas": "El Paso",
  "edinburg/texas": "El Paso",
  "bryan/texas": "El Paso",
  "pharr/texas": "El Paso",
  "leander/texas": "El Paso",
  "victoria/texas": "El Paso",
  "desoto/texas": "El Paso",
  "burleson/texas": "El Paso",
  "huntsville/texas": "El Paso",
  "waxahachie/texas": "El Paso",
  "lancaster/texas": "El Paso",
  "copperas-cove/texas": "El Paso",
  "san-juan/texas": "El Paso",
  "fulshear/texas": "El Paso",
  "harker-heights/texas": "El Paso",
  "greenville/texas": "El Paso",
  "oklahoma-city/oklahoma": "Oklahoma City",
  "norman/oklahoma": "Oklahoma City",
  "edmond/oklahoma": "Oklahoma City",
  "moore/oklahoma": "Oklahoma City",
  "enid/oklahoma": "Oklahoma City",
  "owasso/oklahoma": "Oklahoma City",
  "muskogee/oklahoma": "Oklahoma City",
  "bixby/oklahoma": "Oklahoma City",
  "yukon/oklahoma": "Oklahoma City",
  "ponca-city/oklahoma": "Oklahoma City",
  "sapulpa/oklahoma": "Oklahoma City",
  "del-city/oklahoma": "Oklahoma City",
  "claremore/oklahoma": "Oklahoma City",
  "durant/oklahoma": "Oklahoma City",
  "el-reno/oklahoma": "Oklahoma City",
  "tahlequah/oklahoma": "Oklahoma City",
  "chickasha/oklahoma": "Oklahoma City",
  "newcastle/oklahoma": "Oklahoma City",
  "guymon/oklahoma": "Oklahoma City",
  "weatherford/oklahoma": "Oklahoma City",
  "elk-city/oklahoma": "Oklahoma City",
  "guthrie/oklahoma": "Oklahoma City",
  "tulsa/oklahoma": "Tulsa",
  "broken-arrow/oklahoma": "Tulsa",
  "lawton/oklahoma": "Tulsa",
  "midwest-city/oklahoma": "Tulsa",
  "stillwater/oklahoma": "Tulsa",
  "bartlesville/oklahoma": "Tulsa",
  "shawnee/oklahoma": "Tulsa",
  "jenks/oklahoma": "Tulsa",
  "ardmore/oklahoma": "Tulsa",
  "duncan/oklahoma": "Tulsa",
  "mustang/oklahoma": "Tulsa",
  "bethany/oklahoma": "Tulsa",
  "sand-springs/oklahoma": "Tulsa",
  "altus/oklahoma": "Tulsa",
  "mcalester/oklahoma": "Tulsa",
  "ada/oklahoma": "Tulsa",
  "glenpool/oklahoma": "Tulsa",
  "miami/oklahoma": "Tulsa",
  "choctaw/oklahoma": "Tulsa",
  "woodward/oklahoma": "Tulsa",
  "okmulgee/oklahoma": "Tulsa",
  "warr-acres/oklahoma": "Tulsa",
  "little-rock/arkansas": "Little Rock",
  "fayetteville/arkansas": "Little Rock",
  "fort-smith/arkansas": "Little Rock",
  "springdale/arkansas": "Little Rock",
  "jonesboro/arkansas": "Little Rock",
  "rogers/arkansas": "Little Rock",
  "conway/arkansas": "Little Rock",
  "north-little-rock/arkansas": "Little Rock",
  "bentonville/arkansas": "Little Rock",
  "pine-bluff/arkansas": "Little Rock",
  "hot-springs/arkansas": "Little Rock",
  "benton/arkansas": "Little Rock",
  "sherwood/arkansas": "Little Rock",
  "bella-vista/arkansas": "Little Rock",
  "paragould/arkansas": "Little Rock",
  "jacksonville/arkansas": "Little Rock",
  "texarkana/arkansas": "Little Rock",
  "russellville/arkansas": "Little Rock",
  "cabot/arkansas": "Little Rock",
  "west-memphis/arkansas": "Little Rock",
  "van-buren/arkansas": "Little Rock",
  "searcy/arkansas": "Little Rock",
  "chattanooga/tennessee": "Memphis",
  "murfreesboro/tennessee": "Memphis",
  "johnson-city/tennessee": "Memphis",
  "hendersonville/tennessee": "Memphis",
  "smyrna/tennessee": "Memphis",
  "spring-hill/tennessee": "Memphis",
  "cleveland/tennessee": "Memphis",
  "brentwood/tennessee": "Memphis",
  "lebanon/tennessee": "Memphis",
  "germantown/tennessee": "Memphis",
  "cookeville/tennessee": "Memphis",
  "maryville/tennessee": "Memphis",
  "bristol/tennessee": "Memphis",
  "farragut/tennessee": "Memphis",
  "tullahoma/tennessee": "Memphis",
  "sevierville/tennessee": "Memphis",
  "dickson/tennessee": "Memphis",
  "greeneville/tennessee": "Memphis",
  "nolensville/tennessee": "Memphis",
  "athens/tennessee": "Memphis",
  "lakeland/tennessee": "Memphis",
  "birmingham/alabama": "Birmingham",
  "huntsville/alabama": "Birmingham",
  "mobile/alabama": "Birmingham",
  "montgomery/alabama": "Birmingham",
  "tuscaloosa/alabama": "Birmingham",
  "hoover/alabama": "Birmingham",
  "auburn/alabama": "Birmingham",
  "madison/alabama": "Birmingham",
  "decatur/alabama": "Birmingham",
  "florence/alabama": "Birmingham",
  "vestavia-hills/alabama": "Birmingham",
  "alabaster/alabama": "Birmingham",
  "gadsden/alabama": "Birmingham",
  "northport/alabama": "Birmingham",
  "daphne/alabama": "Birmingham",
  "athens/alabama": "Birmingham",
  "homewood/alabama": "Birmingham",
  "trussville/alabama": "Birmingham",
  "bessemer/alabama": "Birmingham",
  "pelham/alabama": "Birmingham",
  "fairhope/alabama": "Birmingham",
  "foley/alabama": "Birmingham",
  "new-orleans/louisiana": "New Orleans",
  "shreveport/louisiana": "New Orleans",
  "lake-charles/louisiana": "New Orleans",
  "kenner/louisiana": "New Orleans",
  "bossier-city/louisiana": "New Orleans",
  "monroe/louisiana": "New Orleans",
  "alexandria/louisiana": "New Orleans",
  "central/louisiana": "New Orleans",
  "slidell/louisiana": "New Orleans",
  "new-iberia/louisiana": "New Orleans",
  "ruston/louisiana": "New Orleans",
  "hammond/louisiana": "New Orleans",
  "sulphur/louisiana": "New Orleans",
  "zachary/louisiana": "New Orleans",
  "natchitoches/louisiana": "New Orleans",
  "youngsville/louisiana": "New Orleans",
  "gretna/louisiana": "New Orleans",
  "thibodaux/louisiana": "New Orleans",
  "opelousas/louisiana": "New Orleans",
  "broussard/louisiana": "New Orleans",
  "pineville/louisiana": "New Orleans",
  "gonzales/louisiana": "New Orleans",
  "jacksonville/florida": "Jacksonville",
  "cape-coral/florida": "Jacksonville",
  "hollywood/florida": "Jacksonville",
  "palm-bay/florida": "Jacksonville",
  "pompano-beach/florida": "Jacksonville",
  "palm-coast/florida": "Jacksonville",
  "fort-myers/florida": "Jacksonville",
  "homestead/florida": "Jacksonville",
  "boynton-beach/florida": "Jacksonville",
  "tamarac/florida": "Jacksonville",
  "st-cloud/florida": "Jacksonville",
  "jupiter/florida": "Jacksonville",
  "coconut-creek/florida": "Jacksonville",
  "bonita-springs/florida": "Jacksonville",
  "coral-gables/florida": "Jacksonville",
  "winter-garden/florida": "Jacksonville",
  "cutler-bay/florida": "Jacksonville",
  "north-miami-beach/florida": "Jacksonville",
  "plant-city/florida": "Jacksonville",
  "winter-springs/florida": "Jacksonville",
  "lauderdale-lakes/florida": "Jacksonville",
  "haines-city/florida": "Jacksonville",
  "richmond/virginia": "Richmond",
  "chesapeake/virginia": "Richmond",
  "newport-news/virginia": "Richmond",
  "hampton/virginia": "Richmond",
  "roanoke/virginia": "Richmond",
  "lynchburg/virginia": "Richmond",
  "leesburg/virginia": "Richmond",
  "charlottesville/virginia": "Richmond",
  "danville/virginia": "Richmond",
  "fredericksburg/virginia": "Richmond",
  "staunton/virginia": "Richmond",
  "fairfax/virginia": "Richmond",
  "hopewell/virginia": "Richmond",
  "christiansburg/virginia": "Richmond",
  "colonial-heights/virginia": "Richmond",
  "manassas-park/virginia": "Richmond",
  "vienna/virginia": "Richmond",
  "front-royal/virginia": "Richmond",
  "martinsville/virginia": "Richmond",
  "warrenton/virginia": "Richmond",
  "pulaski/virginia": "Richmond",
  "abingdon/virginia": "Richmond",
  "virginia-beach/virginia": "Virginia Beach",
  "norfolk/virginia": "Virginia Beach",
  "alexandria/virginia": "Virginia Beach",
  "suffolk/virginia": "Virginia Beach",
  "portsmouth/virginia": "Virginia Beach",
  "harrisonburg/virginia": "Virginia Beach",
  "blacksburg/virginia": "Virginia Beach",
  "manassas/virginia": "Virginia Beach",
  "petersburg/virginia": "Virginia Beach",
  "winchester/virginia": "Virginia Beach",
  "salem/virginia": "Virginia Beach",
  "herndon/virginia": "Virginia Beach",
  "waynesboro/virginia": "Virginia Beach",
  "culpeper/virginia": "Virginia Beach",
  "bristol/virginia": "Virginia Beach",
  "radford/virginia": "Virginia Beach",
  "williamsburg/virginia": "Virginia Beach",
  "falls-church/virginia": "Virginia Beach",
  "poquoson/virginia": "Virginia Beach",
  "purcellville/virginia": "Virginia Beach",
  "smithfield/virginia": "Virginia Beach",
  "franklin/virginia": "Virginia Beach",
  "pittsburgh/pennsylvania": "Pittsburgh",
  "reading/pennsylvania": "Pittsburgh",
  "bethlehem/pennsylvania": "Pittsburgh",
  "lancaster/pennsylvania": "Pittsburgh",
  "york/pennsylvania": "Pittsburgh",
  "altoona/pennsylvania": "Pittsburgh",
  "penn-hills-municipality/pennsylvania": "Pittsburgh",
  "chester/pennsylvania": "Pittsburgh",
  "bethel-park-municipality/pennsylvania": "Pittsburgh",
  "easton/pennsylvania": "Pittsburgh",
  "williamsport/pennsylvania": "Pittsburgh",
  "lebanon/pennsylvania": "Pittsburgh",
  "chambersburg/pennsylvania": "Pittsburgh",
  "new-castle/pennsylvania": "Pittsburgh",
  "murrysville-municipality/pennsylvania": "Pittsburgh",
  "phoenixville/pennsylvania": "Pittsburgh",
  "lansdale/pennsylvania": "Pittsburgh",
  "mckeesport/pennsylvania": "Pittsburgh",
  "hermitage/pennsylvania": "Pittsburgh",
  "whitehall/pennsylvania": "Pittsburgh",
  "indiana/pennsylvania": "Pittsburgh",
  "wilkinsburg/pennsylvania": "Pittsburgh",
  "cleveland/ohio": "Cleveland",
  "akron/ohio": "Cleveland",
  "canton/ohio": "Cleveland",
  "youngstown/ohio": "Cleveland",
  "elyria/ohio": "Cleveland",
  "newark/ohio": "Cleveland",
  "euclid/ohio": "Cleveland",
  "beavercreek/ohio": "Cleveland",
  "delaware/ohio": "Cleveland",
  "grove-city/ohio": "Cleveland",
  "findlay/ohio": "Cleveland",
  "hilliard/ohio": "Cleveland",
  "marion/ohio": "Cleveland",
  "brunswick/ohio": "Cleveland",
  "stow/ohio": "Cleveland",
  "north-olmsted/ohio": "Cleveland",
  "garfield-heights/ohio": "Cleveland",
  "green/ohio": "Cleveland",
  "troy/ohio": "Cleveland",
  "xenia/ohio": "Cleveland",
  "perrysburg/ohio": "Cleveland",
  "sandusky/ohio": "Cleveland",
  "cincinnati/ohio": "Cincinnati",
  "dayton/ohio": "Cincinnati",
  "lorain/ohio": "Cincinnati",
  "springfield/ohio": "Cincinnati",
  "middletown/ohio": "Cincinnati",
  "lakewood/ohio": "Cincinnati",
  "mansfield/ohio": "Cincinnati",
  "strongsville/ohio": "Cincinnati",
  "cleveland-heights/ohio": "Cincinnati",
  "lancaster/ohio": "Cincinnati",
  "warren/ohio": "Cincinnati",
  "north-ridgeville/ohio": "Cincinnati",
  "mason/ohio": "Cincinnati",
  "lima/ohio": "Cincinnati",
  "westlake/ohio": "Cincinnati",
  "north-royalton/ohio": "Cincinnati",
  "shaker-heights/ohio": "Cincinnati",
  "kent/ohio": "Cincinnati",
  "medina/ohio": "Cincinnati",
  "avon/ohio": "Cincinnati",
  "barberton/ohio": "Cincinnati",
  "wadsworth/ohio": "Cincinnati",
  "lexington-fayette-urban-county/kentucky": "Louisville",
  "bowling-green/kentucky": "Louisville",
  "owensboro/kentucky": "Louisville",
  "covington/kentucky": "Louisville",
  "georgetown/kentucky": "Louisville",
  "richmond/kentucky": "Louisville",
  "florence/kentucky": "Louisville",
  "elizabethtown/kentucky": "Louisville",
  "nicholasville/kentucky": "Louisville",
  "hopkinsville/kentucky": "Louisville",
  "independence/kentucky": "Louisville",
};

function slugToTitle(slug: string): string {
  return slug.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

function buildFaqs(service: ServiceInfo, template: TemplateInfo, city: string, state: string) {
  const svcLower = service.title.toLowerCase();
  const scope = template.label ? `${template.label.toLowerCase()} ` : "";
  return [
    {
      q: `How fast can Apex Grid deliver ${scope}${svcLower} drawings in ${city}?`,
      a: `We quote ${scope}${svcLower} projects in ${city}, ${state} within 24 hours. Drawing delivery depends on scope — straightforward projects in days, complex ones in weeks — and every schedule is committed up front.`,
    },
    {
      q: `Is Apex Grid licensed to stamp ${svcLower} drawings in ${state}?`,
      a: `Yes. Apex Grid Engineering is licensed in 49 states including ${state}. One firm stamps your ${city} project — no sourcing a local engineer of record.`,
    },
    {
      q: `What do you need from us to start ${scope}${svcLower} in ${city}?`,
      a: `${template.cta.charAt(0).toUpperCase() + template.cta.slice(1)} — plus any existing drawings, surveys, or geotechnical reports. We'll confirm scope, fee, and schedule within 24 hours.`,
    },
  ];
}

export default function Wave1CityPage() {
  const params = useParams();
  const serviceSlug = params.service as string;
  const citySlug = params.city as string;
  const stateSlug = params.state as string;

  const mapping = SERVICE_SLUGS[serviceSlug];
  const city = useMemo(() => slugToTitle(citySlug || ""), [citySlug]);
  const state = useMemo(() => slugToTitle(stateSlug || ""), [stateSlug]);

  if (!mapping || !city || !state) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold mb-4">Page Not Found</h1>
          <p>The requested engineering page could not be found.</p>
        </div>
      </div>
    );
  }

  const service = SERVICES[mapping[0]];
  const template = TEMPLATES[mapping[1]];
  const templateLabel = template.label ? `${template.label} ` : "";
  const fullTitle = `${templateLabel}${service.title}`;

  const stateNote = STATE_NOTES[state] || "";
  const metroName = CITY_TO_METRO[`${citySlug}/${stateSlug}`];
  const metroNote = (metroName && METRO_NOTES[metroName]) || "";

  // ── Wave 1 attribution (first-touch immutable) ──
  const serviceKey = mapping[0];
  const templateKey = mapping[1];
  const stateAbbr = STATE_ABBR[stateSlug] || "";
  const cohortId = `wave1-${serviceKey}-${stateAbbr}`;
  const landingUrl = `https://apexgrideng.com/wave1/${serviceSlug}/${citySlug}/${stateSlug}/`;

  useEffect(() => {
    recordFirstTouch({
      landing_url: landingUrl,
      cohort_id: cohortId,
      service: serviceKey,
      metro: metroName || "",
      state: state,
      template_version: WAVE1_TEMPLATE_VERSION,
      timestamp: new Date().toISOString(),
    });
  }, [landingUrl, cohortId, serviceKey, metroName, state]);

  // CTA carries attribution params for the estimate page
  const attributionParams = new URLSearchParams({
    src: "wave1",
    cohort: cohortId,
    service: serviceKey,
    metro: metroName || "",
    state: state,
    tv: WAVE1_TEMPLATE_VERSION,
    landing: landingUrl,
  }).toString();
  const estimateHref = `/estimate?${attributionParams}`;

  const pageTitle = `${fullTitle} in ${city}, ${state} | Apex Grid`;
  const metaDescription =
    `${fullTitle} services in ${city}, ${state} — ${service.description} ` +
    `49-state PE licensure, 24-hour quotes. ${template.cta.charAt(0).toUpperCase() + template.cta.slice(1)}.`;

  const faqs = buildFaqs(service, template, city, state);

  const serviceJsonLd = {
    "@context": "https://schema.org",
    "@type": "Service",
    name: `${fullTitle} in ${city}, ${state}`,
    provider: {
      "@type": "Organization",
      name: "Apex Grid Engineering PLLC",
      url: "https://apexgrideng.com",
    },
    areaServed: { "@type": "City", name: `${city}, ${state}` },
    description: metaDescription,
    url: `https://apexgrideng.com/wave1/${serviceSlug}/${citySlug}/${stateSlug}/`,
  };

  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <div
      className="min-h-screen bg-white"
      data-wave1-cohort={cohortId}
      data-wave1-service={serviceKey}
      data-wave1-template={templateKey}
      data-wave1-template-version={WAVE1_TEMPLATE_VERSION}
      data-wave1-metro={metroName || ""}
      data-wave1-state={state}
    >
      <meta name="wave1:cohort" content={cohortId} />
      <meta name="wave1:template_version" content={WAVE1_TEMPLATE_VERSION} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <main className="max-w-4xl mx-auto px-4 py-12">
        <nav className="text-sm text-gray-500 mb-6">
          <a href="/" className="hover:underline">Home</a>{" > "}
          <a href="/services" className="hover:underline">Services</a>{" > "}
          <span>{fullTitle}</span>{" > "}
          <span>{city}, {state}</span>
        </nav>

        <h1 className="text-4xl font-bold mb-6">
          {fullTitle} in {city}, {state}
        </h1>

        <p className="text-lg text-gray-700 mb-8">{service.description}</p>

        <div className="prose max-w-none mb-12">
          <h2 className="text-2xl font-semibold mb-4">
            {templateLabel}{service.name} Engineering for {city} Projects
          </h2>
          <p className="mb-4">{template.angle}</p>
          <p className="mb-4">{service.edge}</p>

          {metroNote && (
            <>
              <h2 className="text-2xl font-semibold mb-4 mt-8">
                Engineering in the {metroName} Market
              </h2>
              <p className="mb-4">{metroNote}</p>
            </>
          )}

          {stateNote && (
            <>
              <h2 className="text-2xl font-semibold mb-4 mt-8">
                {state} Code &amp; Permitting Notes
              </h2>
              <p className="mb-4">{stateNote}</p>
            </>
          )}

          <h2 className="text-2xl font-semibold mb-4 mt-8">
            What We Deliver
          </h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            {service.services.map((s, i) => (
              <li key={i}>{s}</li>
            ))}
          </ul>

          <h2 className="text-2xl font-semibold mb-4 mt-8">
            Why {city} Developers Choose Apex Grid
          </h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li><strong>49-State Licensure:</strong> One firm, one contract, every market — including {state}.</li>
            <li><strong>24-Hour Quotes:</strong> Pricing in 12–24 hours so your schedule never waits on engineering.</li>
            <li><strong>Permit-Ready Drawings:</strong> Stamped plan sets tuned to {city}'s building department and {state} code amendments.</li>
            <li><strong>Fast-Track Delivery:</strong> Phased drawing releases keep procurement and construction moving.</li>
          </ul>

          <h2 className="text-2xl font-semibold mb-4 mt-8">
            Frequently Asked Questions
          </h2>
          {faqs.map((f, i) => (
            <div key={i} className="mb-4">
              <h3 className="text-lg font-semibold mb-1">{f.q}</h3>
              <p className="text-gray-700">{f.a}</p>
            </div>
          ))}

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mt-8">
            <h3 className="text-xl font-semibold mb-3">
              Get Your {city} {templateLabel}{service.name} Project Engineered
            </h3>
            <p className="mb-4">
              {template.cta.charAt(0).toUpperCase() + template.cta.slice(1)}. We&apos;ll have a
              quote back in 24 hours and permit-ready drawings on your schedule.
            </p>
            <a
              href={estimateHref}
              className="inline-block bg-blue-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-blue-700"
            >
              Send Us Your Project
            </a>
          </div>
        </div>

        <div className="border-t pt-8 mt-12">
          <p className="text-sm text-gray-500">
            Apex Grid Engineering PLLC is licensed in 49 states, including {state}. Professional{" "}
            {service.title.toLowerCase()} services for {templateLabel.toLowerCase()}
            projects in {city} and surrounding areas. Template {WAVE1_TEMPLATE_VERSION}.
          </p>
        </div>
      </main>
    </div>
  );
}
