import type { CityData } from "../types";
export const allentown: CityData = {
  slug: "allentown", name: "Allentown", stateSlug: "pennsylvania", county: "Lehigh County",
  ahj: { office: "City of Allentown Bureau of Building Standards and Safety", process: "Commercial permits are submitted through the City's building-permit process for building and trade review, with zoning, land development, fire, stormwater, and utility approvals coordinated as applicable. Pennsylvania UCC review and Lehigh County or state environmental approvals may be separate for site work." },
  codes: { building: "2018 International Building Code as adopted by Pennsylvania's Uniform Construction Code, with Pennsylvania amendments", energy: "2018 International Energy Conservation Code as adopted under the Pennsylvania UCC, with Pennsylvania amendments", amendments: "Allentown zoning, historic, stormwater, floodplain, parking, and land-development standards supplement the statewide UCC. Redevelopment, brownfields, and constrained industrial parcels often require utility and environmental coordination beyond the building permit." },
  utilities: { electric: "PPL Electric Utilities", notes: "PPL coordinates service capacity, demand, transformers, and distributed-generation interconnection. City of Allentown provides water and sewer; capacity, fire flow, backflow, and connection requirements must be confirmed by parcel." },
  climateNotes: "Allentown is mixed-humid ASHRAE 4A, with hot humid summers, winter heating and snow, freeze-thaw, thunderstorms, and rolling terrain. Industrial fills, urban heat island, and Lehigh River/creek flooding affect site and building details.",
  marketNotes: "Allentown's market spans healthcare, education, logistics, advanced manufacturing, industrial redevelopment, downtown mixed-use, and the broader Lehigh Valley distribution corridor. Brownfield constraints, traffic, stormwater, and aging utilities influence redevelopment economics.",
  narratives: {
    mep: "Allentown MEP design handles 4A seasonal extremes across healthcare, logistics, manufacturing, and adaptive reuse. We coordinate PPL commercial service and demand, City water/sewer capacity, freeze protection, humidity control, ventilation, and existing-building conditions early. UCC energy documentation is matched to the real occupancy and equipment schedule.",
    structural: "Allentown structural design includes snow, freeze-thaw, inland wind, moderate seismic demand, and variable urban or industrial fills. The Lehigh River and tributary floodplains affect elevation and foundation choices, while brownfield or adjacent-building work may require investigation and shoring. Pennsylvania UCC loads, site class, and geotechnical data control the final design.",
    civil: "Civil design coordinates Allentown zoning and land development with stormwater, Pennsylvania erosion and sediment control, floodplain, brownfield, access, and PPL or water/sewer corridors. Rolling grades and constrained industrial parcels make BMP placement and utility conflicts consequential. We resolve outfalls, fire access, and impervious-area calculations before final site geometry.",
    energy: "The Pennsylvania UCC applies the 2018 IECC commercial framework with state amendments. In 4A, efficient heating and cooling, airtight envelopes, heat recovery, solar control, lighting controls, and process-load accounting are key. PPL demand and industrial schedules belong in the compliance model, while existing-building constraints are documented rather than assumed away.",
  },
  faqs: [
    { q: "Which code applies to Allentown commercial buildings?", a: "The Pennsylvania Uniform Construction Code governs, using the 2018 IBC and 2018 IECC frameworks with Pennsylvania amendments. City zoning, land development, stormwater, historic, and floodplain standards also apply." },
    { q: "Who supplies Allentown water and electricity?", a: "PPL Electric Utilities supplies electricity, and the City of Allentown provides water and sewer. Confirm capacity, fire flow, transformer/service needs, connection requirements, and existing-utility conflicts for each parcel." },
    { q: "What should redevelopment teams investigate first?", a: "Screen floodplain, brownfield or fill conditions, stormwater, traffic/access, zoning, historic constraints, and utility capacity before fixing the footprint. These issues can change grading, foundation, BMP, and equipment-room decisions." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 81, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.allentownpa.gov/Departments/Building-Standards-and-Safety"], codes: ["https://www.pa.gov/agencies/dli/resources/compliance-laws-and-regulations/labor-management-relations/bois/ucc-regulations-and-statutes"], amendments: ["https://www.allentownpa.gov/Departments/Planning-and-Zoning"], utilities: ["https://www.pplelectric.com/site/Business", "https://www.allentownpa.gov/Departments/Public-Works/Water-and-Sewer"], climate: ["https://www.weather.gov/phi/"], market: ["https://www.lehighvalley.org/"] } },
};