import type { CityData } from "../types";
export const annArbor: CityData = {
  slug: "ann-arbor", name: "Ann Arbor", stateSlug: "michigan", county: "Washtenaw County",
  ahj: { office: "City of Ann Arbor Building Department", process: "The Building Department receives building permit applications and coordinates plan review and inspections; zoning, site-plan, stormwater, and fire reviews can be distinct city approvals. Michigan's statewide construction code is administered locally." },
  codes: { building: "Michigan Building Code, 2015 edition (based on the 2015 IBC), as adopted statewide", energy: "Michigan commercial energy code based on ASHRAE 90.1-2013, administered under the Michigan Construction Code", amendments: "Ann Arbor does not replace the statewide commercial building code with a city IBC edition; local zoning, site-plan, stormwater, historic-district, and fire requirements remain project-specific." },
  utilities: { electric: "DTE Energy", notes: "DTE coordinates new electric service and distributed generation. The City of Ann Arbor provides water and sanitary sewer; verify capacity, water-main extensions, fire flow, and stormwater requirements early." },
  climateNotes: "Ann Arbor is climate zone 5A, with cold snowy winters, humid summers, freeze-thaw, and heavy-rain events. Hilly glacial terrain, clay soils, and Huron River watershed conditions make grading, erosion, and infiltration site-specific.",
  marketNotes: "University of Michigan, healthcare, research, mobility, and technology support Ann Arbor's institutional and innovation construction market. Infill and campus-adjacent work commonly requires careful utility, traffic, stormwater, and existing-building coordination.",
  narratives: {
    mep: "Ann Arbor MEP design pairs 5A heating and freeze protection with summer humidity control and ventilation. DTE service capacity and the City's water/fire-flow requirements are established before equipment selection for laboratory, healthcare, and university work. The statewide Michigan code baseline is coordinated with campus operations and phasing.",
    structural: "Snow, wind, frost, and glacial soils dominate Ann Arbor structural decisions more than high seismic demand. Sloped sites, variable fill, and wet Huron watershed soils can change foundation and retaining-wall assumptions. Campus and infill projects add existing-condition and construction-sequencing requirements.",
    civil: "Ann Arbor civil work must coordinate site-plan, stormwater, erosion control, water, sanitary, and floodplain review with the City. Huron River watershed protection, steep grades, clay soils, and constrained utility corridors can govern layout and discharge. Michigan construction stormwater coverage applies where disturbance thresholds are met.",
    energy: "Commercial compliance follows Michigan's ASHRAE 90.1-2013-based energy requirements. In 5A, envelope continuity, condensation control, heat recovery, efficient heating, and lighting controls should be reconciled with DTE service and the operating schedules of research or institutional buildings."
  },
  faqs: [
    { q: "What code does Ann Arbor use for commercial buildings?", a: "Ann Arbor administers Michigan's statewide 2015 Michigan Building Code, based on the 2015 IBC, with commercial energy requirements based on ASHRAE 90.1-2013." },
    { q: "Which utilities serve Ann Arbor?", a: "DTE Energy provides electric service; the City provides water and sanitary sewer. Confirm parcel-specific capacity, fire flow, extensions, and stormwater discharge requirements." },
    { q: "Why does site design need early watershed review?", a: "Ann Arbor's Huron River watershed, glacial slopes, clay soils, and heavy-rain events make stormwater quality, erosion, grading, and a lawful outlet important before the site plan is fixed." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 80, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.a2gov.org/departments/build-rent-inspect/building/Pages/default.aspx"], codes: ["https://michigan.gov/lara/bureau-list/bcc"], amendments: ["https://library.municode.com/mi/ann_arbor/codes/code_of_ordinances"], utilities: ["https://www.dteenergy.com/","https://www.a2gov.org/departments/water-treatment/Pages/default.aspx"], climate: ["https://www.weather.gov/dtx/"], market: ["https://annarborusa.org/"] } }
};