import type { CityData } from "../types";
export const batonRouge: CityData = {
  slug: "baton-rouge", name: "Baton Rouge", stateSlug: "louisiana", county: "East Baton Rouge Parish",
  ahj: { office: "City-Parish of Baton Rouge Department of Development—Permits and Inspections", process: "Commercial applications move through the City-Parish permit process, with building, fire, zoning, floodplain, and public-works reviews as applicable. Electronic submittal and parish utility or drainage coordination should be confirmed at intake." },
  codes: { building: "Louisiana State Uniform Construction Code, based on the 2021 International Building Code", energy: "Louisiana State Uniform Construction Code commercial provisions based on the 2021 IECC; ASHRAE 90.1-2019 alternate path", amendments: "The statewide LSUCC is supplemented by City-Parish zoning, floodplain, drainage, fire, and site requirements. Flood elevations and stormwater controls can change finished-floor and equipment design." },
  utilities: { electric: "Entergy Louisiana", notes: "Entergy Louisiana provides electric and gas service and coordinates commercial upgrades; Baton Rouge Water Company and/or East Baton Rouge Parish utilities serve water and sewer by location." },
  climateNotes: "Baton Rouge is hot-humid zone 2A with large latent loads, intense rainfall, hurricanes, floodplain exposure, high groundwater, and soft or variable Gulf Coastal Plain soils.",
  marketNotes: "The petrochemical corridor, LSU and healthcare, port/logistics, industrial expansion, government, and mixed-use development support Baton Rouge construction. Industrial sites and flood-sensitive parcels commonly need early utility, drainage, and geotechnical coordination.",
  narratives: { mep: "Baton Rouge MEP design prioritizes dehumidification, corrosion resistance, and reliable operation during heat and storms. Entergy load coordination, flood-aware equipment elevations, and water/sewer availability are developed alongside the LSUCC building and trade requirements.", structural: "Wind, flood, corrosion, and soft soils govern Baton Rouge structural work more than seismic demand. Foundations follow site geotechnical data; continuous hurricane load paths, equipment anchorage, and flood-resistant detailing follow the LSUCC and floodplain datum.", civil: "Flat terrain and intense rainfall make drainage and floodplain compliance central. Civil plans coordinate City-Parish criteria, detention or discharge, finished grades, utility connections, erosion controls, and Louisiana stormwater permit coverage.", energy: "Commercial compliance follows LSUCC provisions based on the 2021 IECC, or the permitted ASHRAE 90.1-2019 route. Low-SHGC glazing, air barriers, efficient dehumidifying cooling, and controls are essential in zone 2A." },
  faqs: [
    { q: "Which code governs commercial work in Baton Rouge?", a: "Louisiana's State Uniform Construction Code, based on the 2021 IBC with commercial energy provisions based on the 2021 IECC, governs statewide. City-Parish floodplain, zoning, drainage, and fire requirements also apply." },
    { q: "Who provides Baton Rouge electric service?", a: "Entergy Louisiana provides electric and gas service in the area. Water and sewer providers vary by location, so capacity and connection requirements are confirmed for each parcel." },
    { q: "Why do Baton Rouge projects need early flood review?", a: "Low terrain, intense rain, high groundwater, and FEMA flood hazards can control finished-floor elevations, equipment locations, drainage, foundations, and utility routing." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 83, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.brla.gov/750/Permits-Inspections"], codes: ["https://lsuccc.la.gov/"], amendments: ["https://www.brla.gov/750/Permits-Inspections"], utilities: ["https://www.entergy.com/business"], climate: ["https://www.weather.gov/lix/"], market: ["https://www.brac.org/"] } }
};