import type { CityData } from "../types";
export const bellevue: CityData = {
  slug: "bellevue", name: "Bellevue", stateSlug: "nebraska", county: "Sarpy County",
  ahj: { office: "City of Bellevue Planning and Building Department", process: "Bellevue accepts commercial permit applications and coordinates plan review and inspections through its planning and building function; zoning, fire, site, stormwater, and public-works approvals may be separate. Nebraska's state building-code framework and local ordinances both apply." },
  codes: { building: "2018 International Building Code, as adopted by Nebraska and administered locally", energy: "2018 International Energy Conservation Code, as adopted in Nebraska", amendments: "Bellevue uses the state-adopted commercial code framework with municipal zoning, floodplain, stormwater, fire, and right-of-way requirements affecting site design." },
  utilities: { electric: "Omaha Public Power District (OPPD)", notes: "OPPD coordinates electric service and distributed generation. Bellevue supplies water and sewer through its utility systems; confirm pressure, fire flow, capacity, and extensions for the parcel." },
  climateNotes: "Bellevue is climate zone 4A, mixed-humid, with hot summers, cold winters, freeze-thaw, severe thunderstorms, tornado exposure, and Missouri River floodplain conditions. Loess and alluvial soils and rolling bluff terrain influence grading and foundations.",
  marketNotes: "Bellevue benefits from Omaha-metro defense, healthcare, logistics, manufacturing, and residential-commercial growth, including proximity to Offutt Air Force Base. Greenfield development and redevelopment require utility, transportation, floodplain, and phased construction coordination.",
  narratives: {
    mep: "Bellevue MEP design balances 4A cooling and humidity control with winter heating and freeze protection. OPPD service capacity and Bellevue water/fire flow are checked early for commercial, defense-support, and logistics loads. Nebraska's 2018 IECC baseline is coordinated with actual schedules and resilience needs.",
    structural: "Bellevue structures require storm and tornado load-path detailing, snow and frost checks, and geotechnical response to loess, alluvial soils, and bluff slopes. Missouri River floodplain screening can affect finished-floor and equipment elevations. Existing and defense-adjacent work adds phasing and security coordination.",
    civil: "Bellevue civil design coordinates local grading, stormwater, erosion control, floodplain, water, sewer, and public-way review. Missouri River drainage, rolling bluffs, loess erosion, intense rainfall, and detention outlets can control the site. Nebraska construction-stormwater requirements apply at qualifying disturbance.",
    energy: "Bellevue commercial energy compliance follows Nebraska's adopted 2018 IECC. In 4A, solar control, efficient cooling, dehumidification, air sealing, and lighting controls matter; OPPD demand and water-service limitations should be addressed with the building program."
  },
  faqs: [
    { q: "Which commercial codes apply in Bellevue?", a: "Bellevue administers Nebraska's state-adopted 2018 IBC and 2018 IECC framework, together with local zoning, fire, floodplain, stormwater, and site requirements." },
    { q: "Who provides Bellevue utilities?", a: "OPPD provides electric service; Bellevue provides water and sewer. Verify parcel-specific capacity, pressure, fire flow, and extensions." },
    { q: "What site risks should Bellevue projects screen?", a: "Missouri River floodplain, intense rainfall, loess erosion, alluvial soils, bluff grades, freeze-thaw, and stormwater outlets can affect grading, foundations, and equipment elevations." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 79, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://bellevue.net/departments/community-development/"], codes: ["https://dhhs.ne.gov/Pages/Building-Department.aspx"], amendments: ["https://library.municode.com/ne/bellevue/codes/code_of_ordinances"], utilities: ["https://www.oppd.com/","https://bellevue.net/departments/public-works/"], climate: ["https://www.weather.gov/oax/"], market: ["https://www.omahachamber.org/"] } }
};