import type { CityData } from "../types";
export const billings: CityData = {
  slug: "billings", name: "Billings", stateSlug: "montana", county: "Yellowstone County",
  ahj: { office: "City of Billings Community Development Division", process: "Commercial applications go through the city's permitting and plan-review process, with building, planning, fire, and public-works reviews coordinated as applicable. Confirm zoning, floodplain, right-of-way, and fire requirements with the city before submittal because Yellowstone County and Billings have distinct jurisdictions." },
  codes: { building: "2021 Montana Building Code (2021 IBC with Montana amendments)", energy: "2021 Montana Energy Code (2021 IECC with Montana amendments)", amendments: "Montana adopts construction codes statewide; Billings local land-use, subdivision, floodplain, fire, and administrative rules remain applicable. The parcel's city or county jurisdiction should be verified before selecting the permit path." },
  utilities: { electric: "NorthWestern Energy", notes: "NorthWestern Energy provides electric and natural-gas service; City of Billings Public Works and local districts govern water, sewer, and drainage interfaces. Confirm service capacity, gas pressure, and frontage requirements early for industrial and commercial loads." },
  climateNotes: "Billings is a cold semi-arid climate (ASHRAE 5B), with cold windy winters, hot dry summers, snow, freeze-thaw cycles, and regional wildfire-smoke exposure.",
  marketNotes: "Billings is Montana's largest trade, healthcare, energy, and logistics center, with commercial work tied to medical campuses, distribution, retail, and industrial users. Harsh weather, long utility runs, and floodplain questions along the Yellowstone can affect schedule and site cost.",
  narratives: {
    mep: "Billings MEP design must cover 5B winter heating, freeze protection, summer cooling, wind-driven infiltration, and smoke-aware ventilation. We verify NorthWestern Energy service and gas availability early, coordinate municipal water and sewer interfaces, and document the 2021 Montana energy path around a robust envelope and appropriately sized equipment.",
    structural: "Billings structural work follows the 2021 Montana code and site geotechnical data, with snow drift, wind, frost, seismic demand, and variable alluvial soils considered explicitly. Rooftop equipment and industrial structures need anchorage and vibration coordination; floodplain elevation can also affect foundations and access near the Yellowstone.",
    civil: "Civil design coordinates Billings development standards, NorthWestern corridors, municipal or district utilities, stormwater, and floodplain mapping. We establish grading and drainage around freeze-thaw performance and snow storage, and resolve access and frontage improvements before building plans are finalized.",
    energy: "Commercial compliance uses Montana's 2021 IECC-based energy code. In cold 5B conditions, continuous insulation, air control, efficient heating, and careful ventilation matter more than a generic western prescriptive checklist; utility fuel and electrical-service choices are tested together in the compliance model.",
  },
  faqs: [
    { q: "Does Billings use a city building code?", a: "Montana's construction codes apply statewide, while Billings adds local planning, floodplain, fire, development, and administrative requirements. Confirm the actual jurisdiction and parcel overlays before filing." },
    { q: "Who provides Billings commercial utilities?", a: "NorthWestern Energy supplies electricity and natural gas. Water, sewer, drainage, and frontage requirements are handled through the city and applicable local districts, subject to parcel location." },
    { q: "What should a Billings site investigation address?", a: "Snow, wind, frost, freeze-thaw, variable soils, drainage, and possible Yellowstone floodplain exposure should be evaluated. Regional smoke exposure can also affect ventilation and filtration decisions." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 70, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.billingsmt.gov/149/Community-Development"], codes: ["https://bsd.dli.mt.gov/building-codes-permits/"], amendments: ["https://www.billingsmt.gov/149/Community-Development"], utilities: ["https://www.northwesternenergy.com/business"], climate: ["https://www.weather.gov/byz/climate"], market: ["https://commerce.mt.gov/"] } },
};