import type { CityData } from "../types";
export const brownsville: CityData = {
  slug: "brownsville", name: "Brownsville", stateSlug: "texas", county: "Cameron County",
  ahj: { office: "City of Brownsville Building Department", process: "Commercial applications are submitted to the city for building, trade, zoning, and related site review. Projects may also require Cameron County or other agency coordination, and coastal flood and wind information should be established during intake." },
  codes: { building: "2021 International Building Code with City of Brownsville amendments", energy: "2021 IECC commercial provisions (Texas SECO baseline)", amendments: "Municipal amendments, floodplain rules, fire requirements, and Texas coastal wind provisions supplement the adopted IBC. The applicable windstorm and flood criteria are confirmed by site rather than assumed from inland Texas." },
  utilities: { electric: "AEP Texas", notes: "AEP Texas provides electric delivery and handles service upgrades and interconnection; Brownsville Public Utilities Board provides municipal electric, water, and wastewater services in much of the city, so the serving territory must be confirmed by address." },
  climateNotes: "Brownsville is hot-humid climate zone 2A with tropical-storm and hurricane exposure, salt-laden coastal air, intense rain, and flood-prone low terrain.",
  marketNotes: "The Port of Brownsville, border trade, manufacturing, logistics, healthcare, and public infrastructure drive commercial work. Coastal corrosion, port-adjacent utilities, and flood resilience can add scope beyond a standard Texas commercial project.",
  narratives: { mep: "Brownsville MEP design manages high latent cooling loads, corrosion, and hurricane continuity. Utility territory and service capacity are checked with BPUB or AEP Texas, while generators, electrical rooms, and mechanical equipment receive flood-aware elevations and anchorage.", structural: "Coastal wind and flood exposure govern Brownsville structural design more than seismic demand. The geotechnical report informs soft-soil foundations; continuous load paths, corrosion-resistant connections, roof uplift, and windstorm documentation are coordinated with the city's code.", civil: "Low coastal grades make drainage, floodplain, finished-floor, and utility design central. Civil plans coordinate BPUB capacity, detention or discharge, erosion controls, and TCEQ stormwater coverage while accounting for saline groundwater and hurricane rainfall.", energy: "Zone 2A compliance uses the 2021 IECC baseline. Solar-control glazing, air sealing, efficient dehumidifying cooling, corrosion-resistant equipment, and resilient controls deliver more useful performance than nominal insulation alone." },
  faqs: [
    { q: "Which electric provider serves Brownsville?", a: "Brownsville Public Utilities Board serves much of the city, while AEP Texas also serves portions of the region. The provider is address-specific and must be confirmed before service and interconnection design." },
    { q: "What hazards affect Brownsville commercial structures?", a: "Hurricane wind, flood, intense rainfall, coastal corrosion, and soft or variable soils are key hazards. Site-specific flood and geotechnical information should establish elevations, foundations, and durability details." },
    { q: "What commercial energy code is used in Brownsville?", a: "The Texas commercial baseline is the 2021 IECC through SECO, subject to the city package and applicable alternate compliance provisions." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 72, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.brownsvilletx.gov/150/Building-Department"], codes: ["https://www.brownsvilletx.gov/150/Building-Department"], amendments: ["https://www.brownsvilletx.gov/DocumentCenter"], utilities: ["https://www.bpu.net/"], climate: ["https://www.weather.gov/bro/"], market: ["https://www.portofbrownsville.com/"] } }
};