import type { CityData } from "../types";

export const burlingtonVermont: CityData = {
  slug: "burlington", name: "Burlington", stateSlug: "vermont", county: "Chittenden County",
  ahj: { office: "Vermont Division of Fire Safety, Burlington Regional Office", process: "Commercial and public-building plans are reviewed through the state Division of Fire Safety, while Burlington separately reviews zoning, site, public works, and local development approvals. Larger projects may also require Act 250, stormwater, wetlands, or wastewater approvals through state agencies." },
  codes: { building: "Vermont Fire and Building Safety Code, based on the 2015 IBC and NFPA framework", energy: "Vermont Commercial Building Energy Standards (CBES), current state commercial standard", amendments: "State Fire Safety review is the principal commercial building path; Burlington zoning, design review, floodplain, stormwater, and Lake Champlain-related requirements add local constraints. Act 250 and Agency of Natural Resources permits can be separate from the building review." },
  utilities: { electric: "Green Mountain Power", notes: "Green Mountain Power coordinates commercial service, capacity, and distributed-energy interconnection. Burlington Electric Department serves much of the city and has its own service and efficiency programs; Burlington Department of Public Works manages water and wastewater connections." },
  climateNotes: "Burlington sits in a cold 5A/6A transition climate with severe heating seasons, snow, deep frost, freeze-thaw, and Lake Champlain wind and flood exposure. High-performance envelopes, floodplain screening, and phosphorus-sensitive stormwater design are central to early decisions.",
  marketNotes: "The city market is led by University of Vermont and healthcare work, education, technology, food and beverage, tourism, municipal projects, and constrained multifamily or adaptive reuse. Lake Champlain watershed obligations and limited land make site permitting and infrastructure coordination unusually consequential.",
  narratives: {
    mep: "Burlington MEP design is heating-dominated and increasingly electrified, with cold-climate heat pumps, heat recovery, freeze protection, and envelope quality setting the operating-cost baseline. We coordinate Green Mountain Power or Burlington Electric service, water and wastewater connections, and rooftop equipment against Burlington zoning and state Fire Safety review. Efficiency Vermont support can strengthen the business case for CBES performance beyond minimum.",
    structural: "Burlington structural design must account for snow, deep frost, wind off Lake Champlain, and floodplain exposure more than seismic demand. Existing masonry and timber buildings require condition and load-path investigation for adaptive reuse, while frost-susceptible soils, fill, or shoreline conditions can change the foundation concept. The state Fire and Building Safety Code and site-specific geotechnical report govern final decisions.",
    civil: "Burlington civil design combines dense urban parcels, lake and river flood exposure, winter freeze, and strict Lake Champlain watershed water-quality goals. Burlington public-works review and Vermont ANR stormwater, wetlands, and wastewater permits may require phosphorus reduction, treatment, and carefully sequenced construction controls. We coordinate utility capacity, fire access, infiltration testing, and finished elevations before fixing the site plan.",
    energy: "Commercial energy compliance uses Vermont's mandatory CBES rather than a generic local code worksheet. In the 5A/6A transition, continuous insulation, airtightness, thermal-bridge control, high-performance glazing, and efficient cold-climate heating dominate the model. We coordinate CBES documentation with Efficiency Vermont opportunities and the electric-service assumptions from GMP or Burlington Electric so electrification loads are credible.",
  },
  faqs: [
    { q: "Who permits commercial buildings in Burlington?", a: "The Vermont Division of Fire Safety is the principal commercial building and life-safety reviewer, while Burlington handles zoning, site, public-works, and local development approvals. Act 250 and Vermont ANR permits may be separate for larger or environmentally sensitive projects." },
    { q: "What energy standard applies to Burlington commercial work?", a: "Vermont's mandatory Commercial Building Energy Standards (CBES) apply statewide to commercial buildings. The severe climate and Efficiency Vermont programs commonly support performance beyond the minimum standard." },
    { q: "What site risks matter around Burlington?", a: "Snow and frost, Lake Champlain and river flooding, freeze-thaw, groundwater, and phosphorus-sensitive stormwater are recurring concerns. Local and state permitting can materially affect grading, finished elevations, treatment, and utility layout." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 79, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://firesafety.vermont.gov/"], codes: ["https://firesafety.vermont.gov/buildingcode"], amendments: ["https://www.burlingtonvt.gov/DH"], utilities: ["https://greenmountainpower.com/business/", "https://www.burlingtonelectric.com/", "https://www.burlingtonvt.gov/DPW"], climate: ["https://www.weather.gov/btv/"], market: ["https://vermontbiz.com/"] } },
};