import type { CityData } from "../types";
export const cedarRapids: CityData = {
  slug: "cedar-rapids", name: "Cedar Rapids", stateSlug: "iowa", county: "Linn County",
  ahj: { office: "City of Cedar Rapids Community Development Department, Building Services", process: "Cedar Rapids Building Services receives commercial permit applications and conducts local plan review and inspections; zoning, fire, floodplain, site, and public-works reviews may be separate. Iowa's adopted building code and local ordinances govern the permit." },
  codes: { building: "2015 International Building Code with Iowa amendments, as adopted in Iowa", energy: "2012 International Energy Conservation Code with Iowa amendments", amendments: "Cedar Rapids uses Iowa's statewide commercial-code framework; local floodplain, zoning, stormwater, fire, and right-of-way requirements add project-specific conditions." },
  utilities: { electric: "Alliant Energy (Interstate Power and Light)", notes: "Alliant Energy coordinates new electric and gas service. Cedar Rapids Utilities provides water and sanitary sewer; confirm capacity, fire flow, and flood-resilient connection details." },
  climateNotes: "Cedar Rapids is climate zone 5A, with cold winters, humid summers, freeze-thaw, severe storms, and Cedar River flood exposure. Alluvial soils, floodplain elevation, and groundwater can materially affect foundations and civil design.",
  marketNotes: "Cedar Rapids is an eastern Iowa hub for food and beverage, bioscience, manufacturing, logistics, healthcare, and downtown redevelopment. Industrial and flood-recovery work often requires resilience, phased construction, and utility capacity planning.",
  narratives: {
    mep: "Cedar Rapids MEP design addresses 5A heating, humidity, freeze protection, and flood-resilient equipment placement. Alliant service capacity and Cedar Rapids Utilities fire flow are coordinated early for food, manufacturing, and warehouse loads. Iowa's energy baseline is documented while controls and efficient systems target actual operations.",
    structural: "Wind, snow, frost, severe thunderstorms, and Cedar River flood elevation shape Cedar Rapids structures. Alluvial soils and groundwater require geotechnical direction; flood-prone facilities may need elevated or protected equipment and foundations. Existing industrial conditions add investigation and sequencing.",
    civil: "Civil design begins with Cedar River floodplain, city stormwater, grading, water, sanitary, and right-of-way review. Iowa construction-stormwater requirements, alluvial soils, and limited infiltration can control detention and outlet selection. Flood resilience must be coordinated with utility entries and finished-floor elevations.",
    energy: "Cedar Rapids commercial work follows Iowa's 2012 IECC-based energy requirements with Iowa amendments. In 5A, air control, insulation continuity, heating efficiency, and summer moisture management matter; process, refrigeration, and Alliant demand loads should be modeled honestly."
  },
  faqs: [
    { q: "Which energy code applies in Cedar Rapids?", a: "Iowa's adopted commercial framework uses the 2012 IECC with Iowa amendments, alongside the 2015 IBC-based building-code requirements." },
    { q: "Who supplies Cedar Rapids utilities?", a: "Alliant Energy supplies electric and gas service; Cedar Rapids Utilities provides water and sanitary sewer. Site-specific capacity and flood-resilient connections require confirmation." },
    { q: "How does the Cedar River affect projects?", a: "Floodplain elevations, alluvial soils, groundwater, stormwater outlets, and protected utility entries can affect site grading, foundations, and equipment placement." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 77, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.cedar-rapids.org/local_government/departments_a_-_f/building_services/index.php"], codes: ["https://www.legis.iowa.gov/law/administrativeRules/rules?agency=661&chapter=301"], amendments: ["https://codelibrary.amlegal.com/codes/cedarrapids/latest/overview"], utilities: ["https://www.alliantenergy.com/","https://www.cedar-rapids.org/local_government/departments_a_-_f/water_utilities/index.php"], climate: ["https://www.weather.gov/dmx/"], market: ["https://www.cedarrapids.org/"] } }
};