import type { CityData } from "../types";

export const charlestonWestVirginia: CityData = {
  slug: "charleston", name: "Charleston", stateSlug: "west-virginia", county: "Kanawha County",
  ahj: { office: "City of Charleston Office of Building Inspections", process: "Commercial permits are submitted to the City for building and trade review, with zoning, fire, floodplain, and site approvals coordinated as applicable. West Virginia State Fire Marshal and WVDEP permits can be separate from the City process, particularly for life-safety, regulated construction stormwater, and industrial work." },
  codes: { building: "West Virginia State Building Code, based on the 2015 I-Codes with state amendments, as locally enforced by Charleston", energy: "2015 IECC with ASHRAE 90.1-2013 alternate under the West Virginia State Building Code", amendments: "Charleston zoning, floodplain, fire, hillside, stormwater, and public-works requirements supplement the state code. Kanawha River floodplain and industrial-site conditions can add review beyond the building permit." },
  utilities: { electric: "Appalachian Power", notes: "Appalachian Power coordinates commercial service, transformer capacity, and distributed generation. Charleston provides municipal water and sewer services; fire flow, capacity, backflow, and extensions must be confirmed for each parcel." },
  climateNotes: "Charleston is a humid 4A/5A valley climate with hot summers, winter heating, intense rainfall, flash-flood exposure, freeze-thaw, and steep surrounding terrain. Flood elevations, slope stability, mine or karst screening, and durable drainage details can affect feasibility.",
  marketNotes: "Charleston's market centers on state government, healthcare, education, energy and chemical industry, river logistics, and downtown redevelopment. Floodplain constraints, aging infrastructure, and hillside access shape commercial and industrial site decisions.",
  narratives: {
    mep: "Charleston MEP design balances humid summer cooling with winter heating and the resilience demands of a river valley. We coordinate Appalachian Power service, municipal water and sewer capacity, process or healthcare ventilation, flood-protected equipment, and reliable emergency power where occupancy requires it. The City permit, State Fire Marshal review, and locally enforced 2015 IECC path should be reconciled before equipment schedules are fixed.",
    structural: "Charleston structural design is governed by flood, steep terrain, variable soils, and industrial loads more than by high seismic or snow demand. Kanawha River flood elevations affect equipment and finished floors, while hillside sites may require retaining, slope stabilization, or foundations adapted to colluvium and shallow rock. Existing industrial and masonry structures deserve a condition survey before reuse or added process loads.",
    civil: "Charleston civil work starts with floodplain and topography: narrow valleys, intense rainfall, steep slopes, and flash flooding drive grading, detention, erosion control, and access. City requirements coordinate with WVDEP construction stormwater and floodplain rules, and utility capacity can constrain otherwise buildable parcels. We establish outfalls, finished elevations, retaining needs, and Appalachian Power/municipal utility corridors early.",
    energy: "Where Charleston enforces the West Virginia State Building Code, commercial compliance follows the 2015 IECC or ASHRAE 90.1-2013 alternate path. In humid 4A/5A, efficient cooling, dehumidification, envelope air sealing, heating efficiency, and controls need to be balanced rather than optimized in isolation. Industrial process loads and Appalachian Power service assumptions should be represented honestly in the compliance model.",
  },
  faqs: [
    { q: "Who reviews a commercial building permit in Charleston, West Virginia?", a: "The City of Charleston Office of Building Inspections handles the municipal building and trade process, with zoning, fire, floodplain, and site reviews as applicable. State Fire Marshal and WVDEP approvals may be separate." },
    { q: "What energy code applies in Charleston?", a: "Charleston's locally enforced State Building Code is based on the 2015 I-Codes; commercial energy compliance follows the 2015 IECC with ASHRAE 90.1-2013 as an alternate. Confirm the active local enforcement path for the parcel." },
    { q: "What site hazards should Charleston projects screen?", a: "Kanawha River flooding, intense rainfall, steep slopes, colluvial soils, shallow rock, and legacy industrial conditions can change foundations, grading, equipment elevation, and stormwater. Floodplain and geotechnical review should start before layout is committed." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 77, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.charlestonwv.gov/node/1323"], codes: ["https://code.wvlegislature.gov/pdf/15A-11/"], amendments: ["https://www.charlestonwv.gov/government/planning_Archive"], utilities: ["https://www.appalachianpower.com/business"], climate: ["https://www.weather.gov/rlx/"], market: ["https://www.charlestonwv.com/"] } },
};