import type { CityData } from "../types";
export const charleston: CityData = {
  slug: "charleston", name: "Charleston", stateSlug: "south-carolina", county: "Charleston County",
  ahj: { office: "City of Charleston Department of Building Services", process: "Commercial applications use the City's permitting and plan-review process, with building and trade review coordinated with zoning, fire, site, and historic-preservation authorities as applicable. Floodplain, stormwater, and coastal permitting can involve Charleston County and state agencies in separate tracks." },
  codes: { building: "2021 South Carolina Building Codes, including the 2021 IBC, as adopted by the South Carolina Building Codes Council", energy: "2021 South Carolina Energy Standard, based on the 2021 IECC with South Carolina amendments", amendments: "Charleston's historic-district review, zoning, flood-damage-prevention, stormwater, tree, and coastal-site rules add local design constraints. The City and County flood criteria are particularly consequential on low-lying peninsula and waterfront parcels." },
  utilities: { electric: "Dominion Energy South Carolina", notes: "Dominion coordinates commercial service, demand, transformer, and distributed-generation needs. Charleston Water System provides water and wastewater to much of the urban area; fire flow, capacity, and backflow requirements are parcel-specific." },
  climateNotes: "Charleston is hot-humid ASHRAE 3A, with intense solar gain, long latent-cooling seasons, hurricanes, storm surge, tidal flooding, heavy rain, salt air, and high groundwater. Elevation, corrosion, and moisture management govern coastal details.",
  marketNotes: "Charleston combines tourism and hospitality, port and logistics, aerospace and advanced manufacturing, healthcare, higher education, and historic-district infill. Waterfront flood exposure and preservation review often constrain otherwise valuable redevelopment sites.",
  narratives: {
    mep: "Charleston MEP design combines 3A humidity control with coastal corrosion and flood resilience. We coordinate Dominion service, Charleston Water System capacity, protected/elevated equipment, condensate management, and historic-building routing constraints. Historic review and the City's permit process require clear coordination between visible equipment, envelope work, and the state energy standard.",
    structural: "Charleston structural work is governed by hurricane wind, flood elevation, corrosion, and variable coastal soils, with little seismic or snow demand. Historic masonry, soft soils, settlement, and adjacent-building conditions can require careful underpinning and vibration control; FEMA and local flood criteria establish the datum. Wind load paths and durable connections remain essential beyond the historic façade.",
    civil: "Low terrain, tidal tailwater, high groundwater, and intense storms make Charleston drainage site-specific. City and County stormwater, floodplain, coastal, SCDHEC erosion-control, and utility requirements affect grading, BMPs, outfalls, and finished floors. We coordinate Charleston Water System and fire access while preserving historic streetscapes and tree resources.",
    energy: "The 2021 South Carolina Energy Standard applies to commercial work. In 3A, low-SHGC glazing, airtight historic-compatible assemblies, efficient cooling, dedicated dehumidification, and lighting controls address the dominant loads. The compliance model must represent preservation constraints honestly and coordinate Dominion electrical demand with the selected HVAC strategy.",
  },
  faqs: [
    { q: "Which energy code applies in Charleston?", a: "Commercial projects use the 2021 South Carolina Energy Standard, based on the 2021 IECC with state amendments. Confirm the edition and any project-specific transition provisions with the City before final compliance documentation." },
    { q: "What extra reviews can affect a Charleston permit?", a: "Depending on location and scope, historic-district, zoning, fire, floodplain, stormwater, coastal, and utility reviews may be separate from building and trade review. Waterfront and historic peninsula sites should be screened before design is advanced." },
    { q: "Why do Charleston foundations and drainage need early study?", a: "Low elevations, tidal tailwater, high groundwater, soft or variable coastal soils, and hurricane rainfall affect both bearing and stormwater outfalls. FEMA/local flood elevations, geotechnical findings, and City/County criteria can materially change the building pad." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 84, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.charleston-sc.gov/100/Building-Services"], codes: ["https://llr.sc.gov/bcc/"], amendments: ["https://www.charleston-sc.gov/100/Building-Services"], utilities: ["https://www.dominionenergy.com/south-carolina/business", "https://www.charlestonwater.com/"], climate: ["https://www.weather.gov/chs/"], market: ["https://www.crda.org/"] } },
};