import type { CityData } from "../types";
export const cheyenne: CityData = {
  slug: "cheyenne", name: "Cheyenne", stateSlug: "wyoming", county: "Laramie County",
  ahj: { office: "City of Cheyenne Development Department, Building Division", process: "The Building Division receives commercial permit applications and coordinates plan review with planning, fire, and other city functions. Verify whether work is inside city limits, and resolve zoning, floodplain, public-way, and utility approvals before submitting the building package." },
  codes: { building: "2018 International Building Code as adopted by the City of Cheyenne", energy: "2018 International Energy Conservation Code as adopted by the City of Cheyenne", amendments: "Cheyenne's municipal adoption and development standards control inside city limits; county requirements are separate. Local zoning, subdivision, fire, and floodplain rules can add design obligations beyond the base IBC and IECC." },
  utilities: { electric: "Black Hills Energy", notes: "Black Hills Energy provides electric and natural-gas service in Cheyenne. The City of Cheyenne provides water and sewer services; confirm service availability, meter sizing, and utility extensions with both providers before civil plans are fixed." },
  climateNotes: "Cheyenne is a cold semi-arid, high-plains climate (ASHRAE 5B), with high winds, cold winters, snow, freeze-thaw, intense sun, and occasional severe convective storms.",
  marketNotes: "Cheyenne's market is anchored by state government, military and logistics activity, healthcare, distribution, and commercial services. Wind, snow, utility extensions, and the distinction between city and county jurisdiction are recurring project constraints.",
  narratives: {
    mep: "Cheyenne MEP systems are sized for cold 5B winters, high winds, summer sun, and freeze protection rather than a mild plains average. We coordinate Black Hills Energy gas and electric service, city water and sewer, and ventilation filtration while documenting the city's 2018 IECC path. Air sealing and vestibule strategy are especially valuable in this windy setting.",
    structural: "The 2018 IBC framework in Cheyenne is applied with site-specific wind, snow, frost, seismic, and geotechnical inputs. High winds make roof uplift and equipment anchorage prominent, while frost and expansive or variable soils affect foundations. Confirm city amendments and special inspections with the Building Division rather than relying on county forms.",
    civil: "Cheyenne civil plans must coordinate city utilities, Black Hills corridors, snow storage, drainage, access, and any floodplain or public-way approvals. Freeze-thaw durability and severe-weather runoff should be built into grading and pavement details, with jurisdiction verified before plans are filed.",
    energy: "Commercial projects use the adopted 2018 IECC path. A high-performance envelope, controlled infiltration, efficient heating, and heat recovery where appropriate address Cheyenne's 5B heating burden; the compliance model should reflect the actual Black Hills service and fuel choice rather than assume one utility configuration.",
  },
  faqs: [
    { q: "Who is the Cheyenne commercial AHJ?", a: "Inside city limits, the City of Cheyenne Development Department and Building Division are the primary building authorities. Laramie County has a separate jurisdiction, so the parcel boundary must be confirmed first." },
    { q: "Which codes apply in Cheyenne?", a: "Cheyenne's adopted commercial basis is the 2018 IBC and 2018 IECC, subject to municipal amendments and local planning, fire, floodplain, and development standards. Confirm the current city adoption at intake." },
    { q: "What is the main climate design issue?", a: "High winds combine with cold winters, snow, frost, freeze-thaw, and strong sun. Roof uplift, infiltration, snow drift, equipment anchorage, and foundation conditions deserve early engineering attention." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 64, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.cheyennecity.org/Community/Development"], codes: ["https://www.cheyennecity.org/Community/Development/Building"], amendments: ["https://www.cheyennecity.org/Community/Development"], utilities: ["https://www.blackhillsenergy.com/efficiency-and-savings/commercial-rebates/commercial-rebates-cheyenne-electric-laramie-county"], climate: ["https://www.weather.gov/cys/climate"], market: ["https://wyomingbusiness.org/"] } },
};