import type { CityData } from "../types";
export const columbia: CityData = {
  slug: "columbia", name: "Columbia", stateSlug: "south-carolina", county: "Richland County",
  ahj: { office: "City of Columbia Development Services / Richland County building inspections", process: "Commercial permits move through local development-services and electronic permitting channels, with building, trade, zoning, site, fire, and stormwater review coordinated by the responsible jurisdiction. Richland County and state environmental approvals may be separate for grading, floodplain, or utility work." },
  codes: { building: "2021 South Carolina Building Codes, including the 2021 IBC, adopted by the South Carolina Building Codes Council", energy: "2021 South Carolina Energy Standard, based on the 2021 IECC with amendments", amendments: "Columbia's zoning, landscape, tree, stormwater, floodplain, and site-development rules add local obligations to the statewide code. Congaree River and creek floodplains, heat, and intense thunderstorms influence site and enclosure design." },
  utilities: { electric: "Dominion Energy South Carolina", notes: "Dominion coordinates commercial loads, service upgrades, transformers, and distributed generation. City of Columbia provides water and sewer in its service area; capacity, fire flow, and extension requirements require parcel confirmation." },
  climateNotes: "Columbia is hot-humid ASHRAE 3A, with very hot summers, long cooling/dehumidification seasons, thunderstorms, occasional freezes, and red-clay or sandy soils. Heat island, river flooding, and erosion are significant design inputs.",
  marketNotes: "The capital-region market includes state government, healthcare, higher education, technology, manufacturing, logistics, and riverfront/mixed-use redevelopment. Infrastructure upgrades and flood/stormwater constraints shape infill and industrial site feasibility.",
  narratives: {
    mep: "Columbia MEP design prioritizes 3A latent load, high summer peaks, and dependable service for government, healthcare, education, and manufacturing. We coordinate Dominion demand and transformer needs with City water/sewer capacity, humidity-aware ventilation, and storm-resilient electrical distribution. Local site and flood reviews are carried through the permit package rather than isolated from MEP design.",
    structural: "Columbia uses the South Carolina statewide code with inland wind and thunderstorm exposure, modest seismic demand, and no meaningful snow design. Piedmont and Coastal Plain transition soils, fills, and clay affect foundations and settlement; floodplain sites along the Congaree and tributaries require elevation analysis. Industrial vibration or equipment loads are checked independently of the ordinary frame.",
    civil: "Civil design must manage intense rainfall over clay and rolling terrain while respecting Columbia and Richland County stormwater, floodplain, tree, and erosion-control requirements. Congaree watershed and creek flooding can control outfalls and finished grades. We coordinate City water/sewer, fire access, Dominion corridors, and SCDHEC construction coverage before fixing impervious area.",
    energy: "Commercial projects follow the 2021 South Carolina Energy Standard. Columbia's 3A loads reward low-SHGC glazing, efficient cooling, dehumidification, air sealing, controls, and heat-island-conscious site choices. Dominion peak demand and realistic institutional or industrial schedules must be reflected in the compliance path.",
  },
  faqs: [
    { q: "Who handles Columbia commercial development review?", a: "City and Richland County development and inspection functions handle the applicable building and site tracks, with zoning, fire, stormwater, floodplain, and state environmental reviews potentially separate. Verify jurisdiction and submittal sequence for the parcel." },
    { q: "What code edition governs Columbia commercial work?", a: "South Carolina adopted the 2021 South Carolina Building Codes, including the IBC, and the 2021 South Carolina Energy Standard with state amendments. Local zoning and site-development rules remain additional obligations." },
    { q: "How does river flooding affect Columbia sites?", a: "Congaree River and tributary floodplains can control finished-floor elevations, floodproofing, access, drainage outfalls, and utility placement. FEMA mapping and local floodplain review should be screened before the site plan is fixed." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 82, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.columbiasc.gov/depts/development-services"], codes: ["https://llr.sc.gov/bcc/"], amendments: ["https://www.richlandcountysc.gov/Government/Departments/Planning-Development"], utilities: ["https://www.dominionenergy.com/south-carolina/business", "https://www.columbiasc.gov/water"], climate: ["https://www.weather.gov/cae/"], market: ["https://www.commerce.sc.gov/"] } },
};