import type { CityData } from "../types";
export const dayton: CityData = {
  slug: "dayton", name: "Dayton", stateSlug: "ohio", county: "Montgomery County",
  ahj: { office: "City of Dayton Division of Building Services", process: "Dayton routes commercial building permits and plan review through its building-services process; zoning, fire, right-of-way, and utility approvals may be separate. Ohio's certified local building department administers the statewide code." },
  codes: { building: "Ohio Building Code, 2024 edition (based on the 2021 IBC)", energy: "Ohio Building Code commercial energy provisions based on the 2021 IECC; ASHRAE 90.1 is an alternate path", amendments: "Ohio's commercial code is statewide; Dayton local ordinances and zoning, floodplain, fire, and site-development requirements remain applicable." },
  utilities: { electric: "AES Ohio", notes: "AES Ohio coordinates new service and generation interconnection. Dayton supplies water and sewer through Dayton Water; confirm capacity, fire flow, and connection requirements with each utility." },
  climateNotes: "Dayton is ASHRAE 5A (cool-humid), with freeze-thaw winters, humid summers, severe thunderstorms, and Great Miami River floodplain exposure. Clay and alluvial soils make drainage and geotechnical investigation site-specific design inputs.",
  marketNotes: "Dayton's market is anchored by aerospace and defense, Wright-Patterson Air Force Base, healthcare, logistics, and advanced manufacturing. Redevelopment and industrial work often combines existing-condition investigation with utility and floodplain coordination.",
  narratives: {
    mep: "Dayton MEP systems must handle 5A heating, summer latent loads, and freeze protection. AES Ohio capacity should be confirmed early for manufacturing and research loads, while Dayton Water fire flow and service routing influence plant rooms. We coordinate the Ohio 2021-IECC baseline with operational controls and resilience rather than treating compliance as an isolated worksheet.",
    structural: "Dayton structural design is governed mainly by snow, wind, frost, and variable alluvial or fill soils, with low-to-moderate seismic demand assessed from the site. Roof drift, tornado-resistant load paths, and foundations below frost depth deserve attention. Existing industrial and aerospace facilities require careful investigation and special-inspection coordination.",
    civil: "Civil design in Dayton must establish a lawful stormwater outlet and screen Great Miami River tributary floodplains early. Ohio EPA construction-stormwater requirements, local drainage review, water/sewer capacity, grading, and redevelopment erosion controls shape the site plan. Clay and alluvial soils can limit infiltration.",
    energy: "Dayton commercial energy documentation follows Ohio's 2021-IECC-based provisions or ASHRAE 90.1 alternate path. In 5A, continuous air and insulation control, efficient heating, humidity management, and lighting controls matter for both compliance and operating cost. AES Ohio demand and any process loads should be included in the design model."
  },
  faqs: [
    { q: "Which commercial code applies in Dayton?", a: "The statewide 2024 Ohio Building Code, based on the 2021 IBC, applies; its commercial energy provisions are based on the 2021 IECC, with ASHRAE 90.1 available as an alternate path." },
    { q: "Who serves Dayton commercial utilities?", a: "AES Ohio is the electric utility. Dayton Water provides municipal water and sewer; service capacity, fire flow, and connection requirements should be confirmed for the parcel." },
    { q: "What site risks should Dayton projects screen?", a: "Floodplain and tributary drainage, freeze-thaw, clay or alluvial soils, and qualifying construction-stormwater obligations can affect grading, foundations, and the lawful discharge point." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 78, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.daytonohio.gov/250/Building-Services"], codes: ["https://com.ohio.gov/divisions-and-programs/industrial-compliance/building-code"], amendments: ["https://codelibrary.amlegal.com/codes/dayton/latest/overview"], utilities: ["https://www.aes-ohio.com/","https://www.daytonohio.gov/390/Water"], climate: ["https://www.weather.gov/iln/"], market: ["https://daytonchamber.org/"] } }
};