import type { CityData } from "../types";
export const fayettevilleArkansas: CityData = {
  slug: "fayetteville", name: "Fayetteville", stateSlug: "arkansas", county: "Washington County",
  ahj: { office: "City of Fayetteville Development Services—Building Safety", process: "Commercial permit applications are submitted to Fayetteville Development Services for building, fire, zoning, and site review. Civil, utility, and erosion-control approvals are coordinated for new construction and substantial site work." },
  codes: { building: "2021 International Building Code as adopted by Arkansas, with City of Fayetteville amendments", energy: "2021 IECC commercial provisions as adopted by Arkansas", amendments: "Arkansas's statewide code and Fayetteville's zoning, fire, stormwater, tree, and site regulations apply together. Local site and stormwater standards can materially affect grading and utility layouts." },
  utilities: { electric: "Ozarks Electric Cooperative and SWEPCO (territory depends on site)", notes: "The serving electric utility is address-specific; Fayetteville Public Works provides municipal water and wastewater, with capacity and connection requirements confirmed during civil review." },
  climateNotes: "Fayetteville is climate zone 4A with mixed humid heating and cooling, winter freezes, severe thunderstorms, hail, rolling terrain, and locally variable rock and soils.",
  marketNotes: "University of Arkansas growth, healthcare, technology, retail, multifamily, and the Northwest Arkansas logistics corridor drive commercial construction. Sloped sites and rapid development increase the importance of stormwater, access, and utility coordination.",
  narratives: { mep: "Fayetteville MEP design serves a mixed-humid climate with both heating and cooling seasons. Utility territory is confirmed before electrical service design, while municipal water, fire protection, freeze protection, and local site constraints are coordinated through Development Services.", structural: "Rolling terrain and variable subsurface conditions make geotechnical investigation important in Fayetteville. Wind, hail, seismic demand, retaining conditions, and roof equipment anchorage are addressed under Arkansas's adopted 2021 IBC.", civil: "Fayetteville civil work is shaped by slopes, intense rainfall, erosion, and stormwater detention. Grading, access, utility connections, tree/site rules, and Arkansas construction-stormwater coverage are coordinated before site work.", energy: "The adopted 2021 IECC provides the commercial baseline. In 4A, balanced envelope insulation and air sealing, efficient heating and cooling, lighting controls, and seasonal load calculations support compliance and operating performance." },
  faqs: [
    { q: "Who is Fayetteville's commercial building AHJ?", a: "City of Fayetteville Development Services—Building Safety handles building permits and coordinates applicable fire, zoning, site, stormwater, and utility reviews." },
    { q: "Which electric company serves Fayetteville?", a: "Ozarks Electric Cooperative and SWEPCO serve different territories in the region. The serving provider must be confirmed by project address before load and interconnection design." },
    { q: "Why is civil design important on Fayetteville sites?", a: "Rolling terrain and intense rainfall create grading, erosion, detention, and access challenges. Utility capacity and stormwater approvals can control a greenfield schedule." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 76, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.fayetteville-ar.gov/167/Development-Services"], codes: ["https://www.arkansas.gov/energy/"], amendments: ["https://www.fayetteville-ar.gov/DocumentCenter"], utilities: ["https://www.ozarksecc.com/"], climate: ["https://www.weather.gov/tsa/"], market: ["https://fayettevillear.com/"] } }
};