import type { CityData } from "../types";
export const fayetteville: CityData = {
  slug: "fayetteville", name: "Fayetteville", stateSlug: "north-carolina", county: "Cumberland County",
  ahj: { office: "City of Fayetteville Development Services / Cumberland County inspections", process: "Commercial permits and inspections are handled through the City's development-services process with electronic applications and coordinated county code enforcement. Zoning, site, stormwater, fire, transportation, and utility reviews may be distinct, particularly for work near Fort Liberty." },
  codes: { building: "North Carolina State Building Code, state-amended and locally enforced", energy: "North Carolina Energy Conservation Code, state-amended and IECC-derived", amendments: "The statewide code controls technical building work; Fayetteville's Unified Development Ordinance, stormwater, watershed, tree, airport, and military-compatibility rules add site requirements. Fort Liberty and airport clearances can affect height, lighting, access, and security-sensitive projects." },
  utilities: { electric: "Fayetteville Public Works Commission (PWC)", notes: "PWC provides electric, water, and sewer in its service area; commercial load, transformer, fire-flow, and extension studies should precede final site and MEP sizing. Distributed generation and larger services require utility coordination." },
  climateNotes: "Fayetteville is humid subtropical climate zone 3A, with hot cooling seasons, thunderstorms, occasional winter freezes, and red-clay or sandy Piedmont-Coastal Plain transition soils. Wind and rainfall resilience matter even though the city is inland from the coast.",
  marketNotes: "The market is anchored by Fort Liberty, defense contracting, healthcare, logistics, manufacturing, education, and growing commercial corridors. Military compatibility, secure or mission-related facilities, and infrastructure capacity shape development around the regional employment base.",
  narratives: {
    mep: "Fayetteville MEP systems serve humid 3A comfort loads and a mix of healthcare, logistics, defense, and institutional programs. We coordinate PWC electric, water, sewer and fire flow early, account for demand and standby power, and design ventilation and humidity control for durable operation. Airport and military constraints can affect equipment height, lighting, and site utilities.",
    structural: "Structural design uses North Carolina's amended code with inland wind and thunderstorm exposure, negligible snow, and low-to-moderate seismic demand. Red clay, sandy transition soils, fills, and variable groundwater make geotechnical data essential for foundations, slabs, retaining, and settlement. Mission-sensitive facilities may also require progressive-collapse, vibration, or blast criteria established by the owner rather than assumed.",
    civil: "Fayetteville civil plans coordinate the UDO, Cumberland County erosion control, stormwater, floodplain mapping, fire access, and PWC extensions. Heavy summer rainfall on clay can produce erosion and concentrated runoff, while Fort Liberty and airport constraints affect access and grading. Early BMP, utility, and watershed screening keeps the building envelope realistic.",
    energy: "Commercial compliance follows the effective state-amended NC Energy Conservation Code. Cooling efficiency, humidity-aware ventilation, air sealing, solar control, lighting controls, and realistic mission schedules are key in 3A. PWC service and standby-power decisions should be reflected in the energy and electrical load documentation rather than treated as afterthoughts.",
  },
  faqs: [
    { q: "Who reviews commercial permits in Fayetteville?", a: "Fayetteville Development Services and Cumberland County code-enforcement functions coordinate commercial permitting and inspections, while zoning, stormwater, fire, transportation, and utility approvals can remain separate. Projects near Fort Liberty should add the applicable installation or compatibility review." },
    { q: "What utility serves Fayetteville commercial buildings?", a: "Fayetteville Public Works Commission provides electric, water, and sewer in its service area. Confirm parcel-specific capacity, fire flow, transformer requirements, extensions, and standby or distributed-generation coordination." },
    { q: "Do Fort Liberty or airport rules affect ordinary development?", a: "They can. Location and project characteristics may trigger height, lighting, access, security, or compatibility coordination even though the building permit remains a local process. Screen those constraints before fixing site geometry." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 80, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.fayettevillenc.gov/City-Departments/Development-Services/Permitting-Inspections"], codes: ["https://www.ncosfm.gov/codes"], amendments: ["https://www.fayettevillenc.gov/City-Departments/Development-Services/Permitting-Inspections"], utilities: ["https://www.faypwc.com/"], climate: ["https://www.weather.gov/rah/"], market: ["https://www.fayettevilleregionalairport.com/"] } },
};