import type { CityData } from "../types";

export const fortLauderdale: CityData = {
  slug: "fort-lauderdale",
  name: "Fort Lauderdale",
  stateSlug: "florida",
  county: "Broward County",
  ahj: { office: "City of Fort Lauderdale Development Services Department", process: "Commercial applications are submitted through the City's online LauderBuild portal for building and trade review. Zoning, site-plan, landscaping, drainage, floodplain, fire, and utility approvals may be separate reviews; Broward County environmental and regional drainage requirements also apply where triggered." },
  codes: { building: "Florida Building Code, 8th Edition (2023), based on the 2021 IBC; Broward County is in the High-Velocity Hurricane Zone", energy: "Florida Building Code—Energy Conservation, 8th Edition (2023), with ASHRAE 90.1 as an alternate commercial path", amendments: "Broward's HVHZ provisions require enhanced wind design, impact protection or approved shutters, and approved exterior assemblies. Fort Lauderdale's Unified Land Development Regulations, floodplain/freeboard, landscaping, seawall, and stormwater rules add local constraints." },
  utilities: { electric: "Florida Power & Light (FPL)", notes: "FPL commercial service, demand charges, transformer availability, and distributed-generation interconnection should be confirmed early. Fort Lauderdale provides water and sewer through its 24-inch utility system in much of the city; capacity, fire flow, and reclaimed-water availability are parcel-specific." },
  climateNotes: "Fort Lauderdale is ASHRAE 1A hot-humid, with year-round latent cooling, salt air, intense rain, hurricane wind, storm surge, and a high water table. Finished-floor elevation, corrosion protection, and moisture control are fundamental design inputs.",
  marketNotes: "The market combines beach and downtown hospitality, residential/mixed-use redevelopment, marine industries, healthcare, airport-oriented commerce, and Port Everglades logistics. Limited low-lying land makes flood, seawall, drainage, and utility-capacity analysis important on both infill and waterfront work.",
  narratives: {
    mep: "Fort Lauderdale MEP design starts with 1A latent load, salt-air corrosion, and hurricane survivability. We coordinate dehumidification, air sealing, condensate drainage, protected electrical equipment, FPL service and demand characteristics, and City water/sewer capacity before equipment rooms or risers are fixed. LauderBuild documentation must reconcile the 2023 Florida energy provisions with flood and HVHZ details.",
    structural: "Broward's HVHZ makes continuous load paths, impact-rated openings, roof uplift, and approved cladding and roofing assemblies central structural issues. Fort Lauderdale's high groundwater and coastal sands make the geotechnical report decisive for piles, shallow foundations, settlement, and seawalls; FEMA elevation and local freeboard establish the datum. Seismic and snow demands are negligible, but corrosion detailing is not.",
    civil: "Civil design must move rainfall through flat coastal terrain with high groundwater and tidal tailwater. City drainage, Broward County review, FEMA flood mapping, SFWMD criteria, seawalls, and FDEP NPDES coverage can all affect grading, exfiltration, outfalls, and finished floors. We coordinate FPL, city water/sewer, fire flow, and saltwater-resistant site details before locking the footprint.",
    energy: "Commercial compliance follows the 2023 Florida Energy Conservation Code or its ASHRAE 90.1 alternate. In 1A, low-SHGC impact glazing, tight envelopes, efficient variable-speed cooling, dedicated humidity control, lighting controls, and corrosion-resistant equipment produce more value than heating-focused measures. FPL demand charges make peak-load reduction and right-sized service part of the energy decision.",
  },
  faqs: [
    { q: "Is Fort Lauderdale in the High-Velocity Hurricane Zone?", a: "Yes. Broward County is within Florida's HVHZ, so projects must address the heightened wind provisions, windborne-debris protection, and approved exterior components and roofing assemblies in addition to the 2023 Florida Building Code." },
    { q: "How are commercial permits submitted in Fort Lauderdale?", a: "The Development Services Department uses the LauderBuild online portal for commercial building and trade applications and review. Zoning, site, drainage, fire, and utility approvals can remain distinct tracks, so a building approval does not replace site approvals." },
    { q: "What controls Fort Lauderdale stormwater design?", a: "Flat grades, high groundwater, tidal conditions, FEMA flood requirements, City and Broward criteria, and applicable South Florida Water Management District permits control drainage. Finished-floor elevation and outfall feasibility should be tested before site layout." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 90, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.fortlauderdale.gov/government/departments-a-h/development-services"], codes: ["https://www.floridabuilding.org/"], amendments: ["https://www.broward.org/Building/Pages/Default.aspx"], utilities: ["https://www.fpl.com/business.html", "https://www.fortlauderdale.gov/government/departments-a-h/public-works/water-and-sewer"], climate: ["https://www.weather.gov/mfl/"], market: ["https://www.greaterfortlauderdale.com/"] } },
};