import type { CityData } from "../types";
export const frederick: CityData = {
  slug: "frederick", name: "Frederick", stateSlug: "maryland", county: "Frederick County",
  ahj: { office: "City of Frederick Department of Public Works / Frederick County Division of Permits and Inspections", process: "Commercial building permits are reviewed through the responsible City or County permitting office using electronic applications and coordinated building, trade, zoning, site, and fire review. Stormwater, forest conservation, water/sewer, and historic-area approvals can be separate tracks." },
  codes: { building: "Maryland Building Performance Standards, currently based on the 2021 IBC with Maryland amendments", energy: "Maryland Building Performance Standards energy provisions, based on the 2021 IECC and ASHRAE 90.1", amendments: "Maryland statewide codes are supplemented by Frederick's zoning, historic preservation, forest-conservation, adequate-public-facilities, and stormwater rules. The City's historic core and County growth areas can have materially different site and review constraints." },
  utilities: { electric: "Potomac Edison (FirstEnergy)", notes: "Potomac Edison coordinates commercial service, capacity, transformers, and distributed generation. City of Frederick and Frederick County water/sewer service areas require capacity, fire-flow, and extension confirmation during site planning." },
  climateNotes: "Frederick is mixed-humid ASHRAE 4A, with hot summers, winter heating, freeze-thaw, thunderstorms, and rolling Piedmont terrain with clay and weathered-rock soils. Stormwater, erosion, and thermal-season balance matter.",
  marketNotes: "Frederick's market includes biotechnology and life sciences, healthcare, advanced manufacturing, distribution, education, historic downtown reuse, and I-270/I-70-linked growth. Forest conservation, watershed protection, and infrastructure capacity influence greenfield and adaptive-reuse feasibility.",
  narratives: {
    mep: "Frederick MEP design serves mixed-humid 4A conditions and a diverse life-science, healthcare, manufacturing, and adaptive-reuse market. We coordinate Potomac Edison service, City/County water and sewer, heating plus summer dehumidification, ventilation, and historic routing constraints. Maryland performance-code documentation must reflect actual laboratory or process schedules.",
    structural: "Frederick structural design addresses moderate seismic demand, snow and freeze-thaw, inland wind, rolling terrain, and variable residual soils over weathered rock. Geotechnical findings govern settlement, retaining, slabs, and foundations; historic masonry and additions require careful load-path and connection surveys. Maryland amendments and local review establish the final design basis.",
    civil: "Civil design coordinates Frederick County and City stormwater, Maryland erosion and sediment control, forest conservation, watershed protection, access, and water/sewer capacity. Rolling grades and clay soils affect BMPs, retaining, and accessible routes; historic districts add streetscape constraints. Early utility and stormwater layout protects developable area.",
    energy: "Maryland's Building Performance Standards apply the 2021 IECC/ASHRAE 90.1 framework. Frederick's 4A climate rewards right-sized heating and cooling, heat recovery, airtight envelopes, controlled solar gain, lighting controls, and realistic lab ventilation. Potomac Edison demand and process loads are integrated into the chosen compliance path.",
  },
  faqs: [
    { q: "Are Frederick permits handled by the City or County?", a: "It depends on the parcel and jurisdiction. City and Frederick County permitting offices coordinate building and trade review, while zoning, site, stormwater, fire, forest-conservation, and historic approvals can be separate. Verify the jurisdiction before submittal." },
    { q: "What energy standard applies to a Frederick commercial project?", a: "Maryland Building Performance Standards govern, with provisions based on the 2021 IECC and ASHRAE 90.1 plus Maryland amendments. Confirm the applicable transition and project pathway with the reviewing authority." },
    { q: "What site constraints are common around Frederick?", a: "Rolling terrain, clay and weathered-rock soils, stormwater and erosion control, forest conservation, watershed requirements, historic resources, and water/sewer capacity can reshape a site. Screen those constraints before fixing grading or the building pad." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 78, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.cityoffrederickmd.gov/"], codes: ["https://mdcodes.urbitact.com/"], amendments: ["https://frederickcountymd.gov/181/Permits-Inspections"], utilities: ["https://www.firstenergycorp.com/help/outages/storm_info/potomac_edison.html"], climate: ["https://www.weather.gov/lwx/"], market: ["https://www.discoverfrederickmd.com/"] } },
};