import type { CityData } from "../types";
export const greenBay: CityData = {
  slug: "green-bay", name: "Green Bay", stateSlug: "wisconsin", county: "Brown County",
  ahj: { office: "City of Green Bay Department of Community and Economic Development", process: "The city building-services function receives commercial permits and coordinates inspections; Wisconsin commercial-code review is administered locally, with zoning, site plan, fire, erosion-control, and stormwater approvals potentially separate." },
  codes: { building: "Wisconsin Commercial Building Code, SPS 361–366, based on the 2015 IBC", energy: "Wisconsin Commercial Energy Code, SPS 363", amendments: "Wisconsin's commercial building code is statewide; Green Bay zoning, shoreland, floodplain, erosion-control, stormwater, and public-works rules add local project requirements." },
  utilities: { electric: "Wisconsin Public Service", notes: "Wisconsin Public Service coordinates electric and natural-gas service and distributed generation. Green Bay Water Utility provides municipal water and sewer; confirm industrial capacity, fire flow, and connection requirements." },
  climateNotes: "Green Bay is climate zone 6A, with cold snowy winters, freeze-thaw, humid summers, and Great Lakes moisture. Fox River and bay shoreline flood risk, frost, and variable glacial soils affect site and foundation design.",
  marketNotes: "Green Bay's market is supported by paper and packaging, food processing, manufacturing, logistics, healthcare, and port activity. Industrial expansion and redevelopment often require high process loads, utility coordination, and environmental or floodplain screening.",
  narratives: {
    mep: "Green Bay MEP design is heating- and freeze-protection-led in 6A, with humidity control for summer ventilation. Wisconsin Public Service capacity and gas availability should be confirmed for process, refrigeration, and manufacturing loads; Green Bay Water fire flow informs plant sizing. Wisconsin SPS 363 documentation is coordinated with actual operating schedules.",
    structural: "Heavy snow, drift, wind, frost, and wet glacial soils drive Green Bay structural design. Fox River and bay-adjacent groundwater can change foundation and excavation assumptions, while industrial roofs need careful equipment and drift coordination. Existing mills and warehouses add investigation and phasing demands.",
    civil: "Green Bay civil plans coordinate city stormwater, erosion control, water and sewer, and Brown County or watershed constraints. Fox River/bay floodplain screening, frozen-ground construction, and limited infiltration can govern grading and detention. Wisconsin construction-stormwater coverage applies at qualifying disturbance.",
    energy: "Commercial energy work follows Wisconsin SPS 363. In 6A, insulation continuity, air barriers, condensation control, efficient heating, and lighting controls have material winter impact. Process exhaust, refrigeration, and Wisconsin Public Service demand should be represented in the design rather than hidden as plug loads."
  },
  faqs: [
    { q: "Which commercial code applies in Green Bay?", a: "Green Bay administers Wisconsin's statewide Commercial Building Code SPS 361–366, based on the 2015 IBC, and SPS 363 commercial energy provisions." },
    { q: "Who supplies Green Bay utilities?", a: "Wisconsin Public Service supplies electric and gas service; Green Bay Water Utility supplies municipal water and sewer. Capacity and fire flow must be confirmed for each site." },
    { q: "What is a major Green Bay site-design concern?", a: "Snow and frost combine with Fox River/bay floodplain and wet glacial-soil conditions. Early elevations, geotechnical work, stormwater outlet, and utility review reduce redesign risk." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 74, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://greenbaywi.gov/550/Inspections"], codes: ["https://dsps.wi.gov/Pages/Programs/CommercialBuildings/Default.aspx"], amendments: ["https://library.municode.com/wi/green_bay/codes/code_of_ordinances"], utilities: ["https://www.wisconsinpublicservice.com/","https://greenbaywi.gov/355/Water-Utility"], climate: ["https://www.weather.gov/grb/"], market: ["https://www.greatergbc.org/"] } }
};