import type { CityData } from "../types";
export const gulfport: CityData = {
  slug: "gulfport", name: "Gulfport", stateSlug: "mississippi", county: "Harrison County",
  ahj: { office: "City of Gulfport Building Department", process: "Gulfport's Building Department receives commercial permit applications and coordinates building, fire, zoning, floodplain, and site reviews. Coastal parcels may also require Harrison County, FEMA, and utility coordination before construction." },
  codes: { building: "2021 International Building Code with City of Gulfport amendments", energy: "2021 IECC commercial provisions as adopted by Mississippi", amendments: "Local floodplain, coastal, stormwater, zoning, and fire requirements supplement the adopted IBC. Hurricane wind criteria and flood elevations are site-specific and should be confirmed at permitting." },
  utilities: { electric: "Mississippi Power", notes: "Mississippi Power provides electric delivery and coordinates commercial service and upgrades; Gulfport Water and Sewer provides municipal water and wastewater in its service area." },
  climateNotes: "Gulfport is hot-humid zone 2A with hurricane wind, storm surge, salt air, intense rain, high groundwater, and coastal corrosion exposure.",
  marketNotes: "Port of Gulfport, tourism and hospitality, aerospace and advanced manufacturing, logistics, healthcare, and coastal redevelopment support the city's commercial market. Resilient repair and new coastal construction must account for wind, flood, and corrosion together.",
  narratives: { mep: "Gulfport MEP systems address high latent loads, salt-air corrosion, and continuity during hurricanes. Mississippi Power service, municipal water/sewer, generator locations, and flood elevations are coordinated early, with durable equipment and protected electrical distribution.", structural: "Gulfport structural design is dominated by hurricane wind, flood, corrosion, and coastal soils. Foundations follow geotechnical data; continuous load paths, roof uplift, equipment anchorage, protected openings, and corrosion-resistant connections follow the adopted 2021 IBC and local coastal criteria.", civil: "Coastal Gulfport civil work begins with FEMA flood information, finished grades, drainage, and discharge capacity. Plans coordinate Gulfport utilities, detention, access, erosion controls, stormwater permitting, and saltwater exposure rather than assuming inland site criteria.", energy: "The 2021 IECC commercial baseline applies in hot-humid zone 2A. Solar control, airtight envelopes, efficient dehumidifying cooling, corrosion-resistant equipment, and resilient controls should be documented together in the compliance package." },
  faqs: [
    { q: "Who reviews commercial permits in Gulfport?", a: "The City of Gulfport Building Department is the building AHJ, with fire, zoning, floodplain, site, county, and utility reviews added as the project requires." },
    { q: "What hazards drive Gulfport structural design?", a: "Hurricane wind, storm surge and flood, coastal corrosion, intense rain, and variable soils are primary drivers. Site-specific flood and geotechnical data establish elevations and foundations." },
    { q: "Which utility provides Gulfport electricity?", a: "Mississippi Power provides electric service and coordinates commercial upgrades. Gulfport Water and Sewer provides municipal water and wastewater within its service area." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 71, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.gulfport-ms.gov/180/Building-Department"], codes: ["https://www.gulfport-ms.gov/180/Building-Department"], amendments: ["https://www.gulfport-ms.gov/DocumentCenter"], utilities: ["https://www.mississippipower.com/"], climate: ["https://www.weather.gov/lix/"], market: ["https://portofthegulfport.com/"] } }
};