import type { CityData } from "../types";
export const harrisburg: CityData = {
  slug: "harrisburg", name: "Harrisburg", stateSlug: "pennsylvania", county: "Dauphin County",
  ahj: { office: "City of Harrisburg Bureau of Building and Housing Development", process: "Commercial permit applications use the City's permitting process for building and trade review, coordinated with zoning, fire, land development, floodplain, and utility approvals. Dauphin County and Pennsylvania environmental reviews may apply separately to grading, erosion, and stormwater work." },
  codes: { building: "2018 International Building Code as adopted through the Pennsylvania Uniform Construction Code (UCC), with Pennsylvania amendments", energy: "2018 International Energy Conservation Code as adopted under the Pennsylvania UCC, with Pennsylvania amendments", amendments: "Harrisburg zoning, historic preservation, floodplain, stormwater, parking, and land-development requirements supplement the statewide UCC. Susquehanna River and urban infill conditions can materially affect elevation, access, and utility routing." },
  utilities: { electric: "PPL Electric Utilities", notes: "PPL coordinates commercial service, demand, transformer, and distributed-generation requirements. Harrisburg City Authority provides water and sewer in the city; capacity, fire flow, and aging-utility coordination are parcel-specific." },
  climateNotes: "Harrisburg is mixed-humid ASHRAE 4A, with hot summers, winter heating and snow, freeze-thaw, thunderstorms, Susquehanna flooding, and urban heat-island effects. Soils, historic fabric, and flood elevation affect design.",
  marketNotes: "The capital-region market includes state government, healthcare, education, logistics, riverfront redevelopment, adaptive reuse, and industrial activity along major interstate and rail corridors. Aging infrastructure and flood exposure make due diligence important for infill.",
  narratives: {
    mep: "Harrisburg MEP design must balance 4A heating, summer humidity, freeze protection, and adaptive-reuse constraints. We coordinate PPL service and demand, City water/sewer capacity, flood-protected electrical rooms, ventilation, and historic routing before selecting equipment. The Pennsylvania UCC energy path must represent existing-building conditions rather than generic new construction assumptions.",
    structural: "Harrisburg structural work combines Pennsylvania UCC requirements with snow, freeze-thaw, moderate seismic demand, inland wind, and variable urban fills. River flood elevations, historic masonry, adjacent construction, and geotechnical settlement can control foundations and additions. We establish loads and special inspections from the governing UCC edition and project site class.",
    civil: "Urban Harrisburg civil design addresses Susquehanna and tributary floodplains, steep or constrained parcels, Pennsylvania erosion and sediment control, stormwater, historic streets, and aging utilities. We coordinate Harrisburg City Authority capacity, fire access, PPL corridors, and outfall feasibility before final grading.",
    energy: "The Pennsylvania UCC commercial energy provisions adopt the 2018 IECC framework with state amendments. In 4A, envelope air control, balanced insulation, efficient heating and cooling, heat recovery, lighting controls, and flood-safe equipment placement are key. PPL demand and existing-building limitations should be documented in the selected compliance method.",
  },
  faqs: [
    { q: "What code governs commercial work in Harrisburg?", a: "Pennsylvania's Uniform Construction Code governs, with the 2018 IBC and 2018 IECC frameworks as adopted and amended by Pennsylvania. Harrisburg zoning, historic, floodplain, and site rules remain additional requirements." },
    { q: "How does Susquehanna flooding affect Harrisburg design?", a: "Floodplain mapping and elevation can affect finished floors, utilities, access, foundations, and allowable site work. Confirm FEMA and City floodplain criteria early, especially for riverfront redevelopment and adaptive reuse." },
    { q: "Which utilities serve Harrisburg?", a: "PPL Electric Utilities supplies electricity, and Harrisburg City Authority provides water and sewer in the city. Confirm capacity, fire flow, transformer needs, connections, and existing-utility conflicts for the parcel." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 76, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.harrisburgpa.gov/bureau-of-building-and-housing-development/"], codes: ["https://www.pa.gov/agencies/dli/programs-services/ucc"], amendments: ["https://www.harrisburgpa.gov/"], utilities: ["https://www.pplelectric.com/site/Business"], climate: ["https://www.weather.gov/ctp/"], market: ["https://www.harrisburgregion.com/"] } },
};