import type { CityData } from "../types";
export const hialeah: CityData = {
  slug: "hialeah", name: "Hialeah", stateSlug: "florida", county: "Miami-Dade County",
  ahj: { office: "City of Hialeah Building Department", process: "Commercial permits use the City's electronic permitting and plan-review process, with building, trade, zoning, and site reviews coordinated through municipal departments. Miami-Dade County flood, environmental, water/sewer, and HVHZ requirements apply in addition to municipal review." },
  codes: { building: "Florida Building Code, 8th Edition (2023), based on the 2021 IBC, with Miami-Dade High-Velocity Hurricane Zone provisions", energy: "Florida Building Code—Energy Conservation, 8th Edition (2023), with ASHRAE 90.1 alternate", amendments: "Miami-Dade HVHZ rules require impact protection and Miami-Dade Product Control approvals (NOAs) for covered exterior and roofing assemblies. Hialeah zoning, floodplain, parking, drainage, and Miami-Dade WASD requirements add local design obligations." },
  utilities: { electric: "Florida Power & Light (FPL)", notes: "FPL service studies, demand charges, transformers, and interconnection are early design inputs. Miami-Dade Water and Sewer Department (WASD) generally governs regional water and sewer connections, capacity, and fire-flow requirements." },
  climateNotes: "Hialeah is climate zone 1A: hot, humid, heavily irradiated, and exposed to hurricane wind and intense rainfall. Flat terrain, porous limestone, high groundwater, flood risk, and salt-laden air drive drainage, envelope, and equipment decisions.",
  marketNotes: "Hialeah's market is strongly industrial and logistics-oriented, with manufacturing, warehousing, wholesale, healthcare, and infill commercial redevelopment tied to the Miami-Dade distribution network. Constrained parcels make parking, loading, drainage, fire flow, and utility capacity consequential.",
  narratives: {
    mep: "Hialeah MEP work must control 1A humidity while serving high-bay industrial, warehouse, and mixed-use loads. We coordinate FPL service and demand characteristics, WASD capacity, condensate and ventilation, corrosion protection, and elevated/protected equipment where flood exposure warrants it. HVHZ openings and the City's electronic review make envelope and MEP documentation inseparable.",
    structural: "HVHZ design drives impact protection, roof uplift, positive load paths, and Miami-Dade NOA documentation. Hialeah's limestone and variable fill require geotechnical confirmation of bearing, settlement, slabs, and foundations; high groundwater and flood elevation affect the structural datum. Seismic and snow are negligible, while durable reinforcement and connections address moisture and salt exposure.",
    civil: "Flat Hialeah sites drain through high groundwater and porous limestone, so exfiltration, drainage wells, retention, and outfall assumptions must be confirmed with Miami-Dade and SFWMD criteria. We coordinate WASD, fire access, parking, flood elevations, FDEP construction stormwater coverage, and municipal site review before sizing the building pad.",
    energy: "The 2023 Florida commercial energy code or ASHRAE 90.1 alternate applies. In 1A, efficient cooling and dehumidification, low-SHGC impact glazing, air sealing, lighting controls, and high-bay lighting zoning are the principal levers. FPL demand charges make controls, right-sized transformers, and peak-load management important to both compliance and operation.",
  },
  faqs: [
    { q: "What wind rules apply in Hialeah?", a: "Hialeah is in Miami-Dade County's HVHZ. Commercial designs must address enhanced wind pressures, windborne-debris impact protection, and Miami-Dade Product Control NOAs for covered exterior and roofing products." },
    { q: "Who handles water and sewer capacity for a Hialeah project?", a: "Miami-Dade Water and Sewer Department generally governs regional connections, capacity, and fire-flow coordination, while the City handles its municipal permitting tracks. Confirm service availability and connection requirements for the specific parcel." },
    { q: "Why is drainage difficult on Hialeah industrial sites?", a: "Sites are flat, groundwater can be high, and limestone drainage systems are sensitive to water-table and flood conditions. Retention, exfiltration or drainage wells, finished floors, and applicable SFWMD and Miami-Dade approvals should be evaluated before grading is fixed." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 87, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.hialeahfl.gov/177/Building-Department"], codes: ["https://www.floridabuilding.org/"], amendments: ["https://www.miamidade.gov/global/economy/building.page"], utilities: ["https://www.fpl.com/business.html", "https://www.miamidade.gov/global/water/wastewater.page"], climate: ["https://www.weather.gov/mfl/"], market: ["https://www.beaconcouncil.com/"] } },
};