import type { CityData } from "../types";

export const honoluluHawaii: CityData = {
  slug: "honolulu", name: "Honolulu", stateSlug: "hawaii", county: "Honolulu County",
  ahj: { office: "City and County of Honolulu Department of Planning and Permitting", process: "Commercial building applications are submitted through the City's Department of Planning and Permitting process and may involve building, zoning, engineering, fire, and public-works reviews. Coastal projects can require Special Management Area, shoreline, flood, and historic-site approvals in separate tracks; the exact review path depends on the parcel and scope." },
  codes: { building: "2018 Hawaii State Building Code as adopted and amended by the City and County of Honolulu", energy: "Hawaii Energy Conservation Code as adopted by Honolulu, with ASHRAE 90.1 available as an alternate path", amendments: "Honolulu amendments and zoning rules affect high-rise, fire/life-safety, wind, flood, shoreline setback, SMA, accessibility, and site work. DPP's adopted county code, rather than a generic state summary, controls the permit basis." },
  utilities: { electric: "Hawaiian Electric", notes: "Hawaiian Electric coordinates commercial service, large-load studies, distributed generation, and interconnection. The Honolulu Board of Water Supply provides water; wastewater and stormwater connections and capacity require project-specific City coordination." },
  climateNotes: "Honolulu is a hot, humid 1A coastal climate with trade winds, salt-laden air, intense sun, hurricane exposure, tsunami and coastal flood risk, and no meaningful snow load. Corrosion, moisture, wind uplift, seismic demand, and high electricity prices should shape early design decisions.",
  marketNotes: "Honolulu's market is led by tourism and hospitality, healthcare, military and federal activity, higher education, government, and constrained multifamily redevelopment. Imported materials, labor capacity, high construction cost, and limited land make phasing, maintainability, and utility coordination consequential.",
  narratives: {
    mep: "Honolulu MEP systems must control year-round latent cooling while surviving salt air and supporting expensive, constrained electrical service. We coordinate Hawaiian Electric large-load and interconnection assumptions with Board of Water Supply capacity, fire protection, corrosion-resistant equipment, and trade-wind opportunities. DPP review and any SMA or shoreline track should be reflected in equipment locations, visible rooftop work, and service routing.",
    structural: "Honolulu structural design combines hurricane-prone wind, seismic demand, corrosion, and coastal flood or tsunami exposure. Continuous load paths, roof uplift, durable connections, concrete cover, and protected steel matter, while site-specific geotechnical work addresses fill, high groundwater, and variable volcanic or reef-derived soils. County amendments and the adopted 2018 State Building Code establish the final design basis.",
    civil: "Honolulu civil design is constrained by steep island topography, intense rainfall, limited land, and coastal regulation. DPP engineering review, SMA and shoreline rules, flood and tsunami mapping, Board of Water Supply requirements, and NPDES stormwater obligations can change grading, outfalls, setbacks, and usable area. Early utility and erosion-control coordination is essential where imported fill and narrow access make rework costly.",
    energy: "Honolulu's county-adopted Hawaii Energy Conservation Code and ASHRAE 90.1 alternate path are only the floor in an expensive-electricity market. In 1A, low-SHGC glazing, shading, efficient variable-speed cooling, dedicated outdoor-air control, natural ventilation where suitable, and PV or storage integration drive results. Hawaiian Electric service constraints and DPP documentation should be coordinated with the compliance model from schematic design.",
  },
  faqs: [
    { q: "Which authority permits commercial work in Honolulu?", a: "The City and County of Honolulu Department of Planning and Permitting is the primary building and land-use authority. Fire, engineering, public works, SMA, shoreline, flood, and historic reviews may be separate depending on the parcel." },
    { q: "What code and utility issues are most important in Honolulu?", a: "Honolulu adopts the Hawaii State Building Code with county amendments and uses its adopted Hawaii Energy Conservation Code, with ASHRAE 90.1 as an alternate. Hawaiian Electric service studies and Board of Water Supply capacity should be confirmed early." },
    { q: "What hazards affect Honolulu design?", a: "Hurricane wind, salt corrosion, seismic shaking, tsunami and coastal flooding, intense rain, and high groundwater can affect structure, enclosure, grading, and equipment elevation. Site-specific county and hazard-map requirements control." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 91, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.honolulu.gov/dpp/"], codes: ["https://ags.hawaii.gov/bcc/"], amendments: ["https://www.honolulu.gov/dpp/"], utilities: ["https://www.hawaiianelectric.com/business", "https://www.boardofwatersupply.com/"], climate: ["https://www.weather.gov/hfo/"], market: ["https://www.honolulu.gov/dcs/dcs-cbdd-community-development-block-grant-cbdg-program/"] } },
};