import type { CityData } from "../types";

export const manchesterNewHampshire: CityData = {
  slug: "manchester", name: "Manchester", stateSlug: "new-hampshire", county: "Hillsborough County",
  ahj: { office: "City of Manchester Department of Planning and Community Development, Building Services", process: "Commercial permit applications go through Manchester Building Services for building and trade review, with zoning, fire, site, and utility coordination as applicable. Larger earth disturbances, wetlands, or shoreline work can require separate New Hampshire Department of Environmental Services permits in addition to the City permit." },
  codes: { building: "2018 New Hampshire State Building Code, based on the 2018 I-Codes, with state amendments", energy: "2018 IECC / ASHRAE 90.1-2016 under the New Hampshire State Energy Code", amendments: "Manchester zoning, site-plan, fire, floodplain, and public-works requirements supplement the statewide code. Local review can impose access, parking, stormwater, and infrastructure conditions even though the technical building code is statewide." },
  utilities: { electric: "Eversource Energy", notes: "Eversource coordinates commercial service, transformer capacity, and distributed generation. Manchester Water Works supplies water and the City's sewer system serves developed areas; available fire flow, capacity, and extension requirements are site-specific." },
  climateNotes: "Manchester is a cold 6A inland climate with long heating seasons, snow, freeze-thaw, deep frost, and humid summers. Shallow granite, ledge, steep grades in parts of the city, and Merrimack River flood exposure can affect foundations and drainage.",
  marketNotes: "Manchester's market includes advanced manufacturing, aerospace and defense, healthcare, higher education, office conversion, logistics, and multifamily development along the I-93/Route 3 corridor. Older mill and industrial buildings create recurring adaptive-reuse, hazardous-material, utility, and structural coordination needs.",
  narratives: {
    mep: "Manchester MEP design begins with Zone 6A heating, freeze protection, and envelope performance, then accounts for humid summer cooling and process loads in the manufacturing corridor. We coordinate Eversource service and power quality, Manchester Water Works capacity, sewer and fire-flow assumptions, and maintainable equipment layouts for reused mills. The City's building, zoning, and fire reviews should track the statewide 2018 IECC/ASHRAE 90.1 compliance path.",
    structural: "Manchester structures face snow, frost, wind, freeze-thaw, and variable glacial soils or shallow granite more than seismic demand. Existing mill masonry and timber often require a careful load-path and condition survey, while new foundations may encounter ledge, fill, or settlement-sensitive ground. Merrimack floodplain screening and local code amendments belong in the early structural basis.",
    civil: "Manchester civil work must fit constrained redevelopment parcels, steep local grades, ledge, and winter stormwater conditions. City site-plan and public-works requirements coordinate with NHDES Alteration of Terrain, wetlands, and floodplain rules where thresholds apply. We resolve Manchester Water Works service, sewer, fire access, infiltration feasibility, and erosion controls before fixing grading.",
    energy: "Manchester commercial projects comply with New Hampshire's statewide 2018 IECC or ASHRAE 90.1-2016 alternative path. In 6A, continuous insulation, airtightness, thermal bridges, heat recovery, and efficient heating have the largest impact, while process ventilation can dominate manufacturing loads. NHSaves incentives may support above-code measures, but the City permit package still needs a documented code path.",
  },
  faqs: [
    { q: "Who reviews commercial permits in Manchester, New Hampshire?", a: "Manchester Building Services is the municipal building and trade reviewer, with zoning, fire, site, and utility review as applicable. NHDES permits may be separate for larger earth disturbance, wetlands, or shoreline work." },
    { q: "What code and energy standard apply in Manchester?", a: "New Hampshire's statewide code is based on the 2018 I-Codes with state amendments; commercial energy compliance follows the 2018 IECC with ASHRAE 90.1-2016 as an alternate. Manchester local site and fire requirements still apply." },
    { q: "What site conditions should Manchester projects investigate?", a: "Snow and deep frost, shallow granite or ledge, glacial soils, fill, winter drainage, and Merrimack River flood exposure can affect feasibility. A geotechnical report and NHDES/City stormwater screening should precede final grading and foundation decisions." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 80, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.manchesternh.gov/Departments/Planning-and-Community-Development/Building-Services"], codes: ["https://www.oplc.nh.gov/building-codes"], amendments: ["https://www.manchesternh.gov/Departments/Planning-and-Community-Development"], utilities: ["https://www.eversource.com/content/business"], climate: ["https://www.weather.gov/gyx/"], market: ["https://manchester-chamber.org/"] } },
};