import type { CityData } from "../types";
export const newHaven: CityData = {
  slug: "new-haven", name: "New Haven", stateSlug: "connecticut", county: "New Haven County",
  ahj: { office: "City of New Haven Building Department", process: "The Building Department receives commercial applications through the city's permitting process and coordinates building, zoning, fire, and related reviews. Historic-district, wetlands, coastal, public-way, and utility approvals can be separate; confirm the project's review path before filing." },
  codes: { building: "2022 Connecticut State Building Code (2021 IBC with Connecticut amendments)", energy: "2022 Connecticut State Building Code energy provisions based on the 2021 IECC and ASHRAE 90.1-2019", amendments: "Connecticut's state building code applies statewide, while New Haven adds zoning, historic-district, coastal, wetlands, fire, and administrative requirements. Existing-building work must also be checked under the applicable state rehabilitation provisions." },
  utilities: { electric: "United Illuminating", notes: "United Illuminating provides electric service and interconnection in New Haven; the South Central Connecticut Regional Water Authority provides water and the city or regional systems provide sewer service. Verify service territory, capacity, and street-opening requirements early." },
  climateNotes: "New Haven is ASHRAE climate zone 5A, cool-humid, with snowy winters, humid summers, coastal storm and flood exposure, freeze-thaw, and dense urban drainage constraints.",
  marketNotes: "The market is driven by Yale and other institutional work, healthcare, life sciences, multifamily housing, education, and redevelopment of older industrial and urban buildings. Existing masonry, tight sites, brownfields, and coastal resilience make renovation and infrastructure coordination recurring needs.",
  narratives: {
    mep: "New Haven MEP projects reconcile 5A heating and freeze protection with humid summers, older-building constraints, and coastal resilience. We coordinate United Illuminating service and interconnection, water authority interfaces, and the Connecticut energy path while addressing ventilation, dehumidification, and occupied-phasing requirements early.",
    structural: "Structural design follows the 2022 Connecticut code with site-specific snow, wind, seismic, flood, and geotechnical inputs. Older masonry, timber, and industrial structures need field verification before rooftop equipment or change-of-use loads are designed; coastal and flood conditions can add corrosion and elevation requirements.",
    civil: "New Haven civil design coordinates dense streets, regional water, sewer, stormwater, wetlands, coastal flood, brownfield, and public-way constraints. We reserve space for treatment and access, confirm utility ownership, and coordinate city and state approvals before grading or utility plans are advanced.",
    energy: "Commercial energy compliance follows Connecticut's 2022 code path, based on the 2021 IECC and ASHRAE 90.1-2019. In 5A, continuous insulation, air sealing, humidity-safe assemblies, efficient heating, and heat recovery must fit historic and occupied-building realities as well as the UI electrical-service plan.",
  },
  faqs: [
    { q: "Which building code applies in New Haven?", a: "The 2022 Connecticut State Building Code, based on the 2021 IBC with Connecticut amendments, governs commercial work. New Haven zoning, historic, coastal, wetlands, and fire requirements remain additional reviews." },
    { q: "Who serves New Haven electrically?", a: "United Illuminating provides electric service and interconnection. Water is provided by the South Central Connecticut Regional Water Authority, while sewer and public-way requirements must be confirmed for the parcel." },
    { q: "What makes New Haven renovations challenging?", a: "Older masonry and industrial buildings, tight rights-of-way, occupied institutional uses, coastal flooding, and brownfield or wetlands constraints can all affect design. Existing-condition investigation and agency coordination should precede major assumptions." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 80, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.newhavenct.gov/government/departments-divisions/building"], codes: ["https://portal.ct.gov/dcp/office-of-state-building-inspector/connecticut-state-building-code"], amendments: ["https://www.newhavenct.gov/government/departments-divisions/zoning"], utilities: ["https://www.uinet.com/business", "https://www.rwater.com/"], climate: ["https://www.weather.gov/okx/climate"], market: ["https://portal.ct.gov/DECD"] } },
};