import type { CityData } from "../types";
export const norfolk: CityData = {
  slug: "norfolk", name: "Norfolk", stateSlug: "virginia", county: "City of Norfolk",
  ahj: { office: "City of Norfolk Department of Planning / Permits and Inspections", process: "Commercial building applications use Norfolk's online permitting and plan-review process, with building and trade review coordinated with zoning, site, fire, floodplain, and utility departments. Tidewater regional, port, and environmental approvals may be separate from the building permit." },
  codes: { building: "Virginia Uniform Statewide Building Code, 2021 edition, based on the 2021 IBC", energy: "Virginia Energy Conservation Code, 2021 edition, based on the 2021 IECC", amendments: "Norfolk zoning, floodplain, stormwater, Chesapeake Bay protection, coastal resilience, and site-plan rules add local requirements. Waterfront and military/port contexts can impose access, elevation, security, or coordination constraints." },
  utilities: { electric: "Dominion Energy Virginia", notes: "Dominion coordinates commercial service, demand, transformer, and distributed-generation interconnection. Norfolk Department of Utilities provides water and sewer; available capacity, fire flow, and low-lying-site connections require parcel confirmation." },
  climateNotes: "Norfolk is humid coastal climate zone 4A, with long cooling seasons, winter heating, hurricanes, tidal flooding, storm surge, heavy rain, salt air, and high groundwater. Flood elevation and corrosion-resistant detailing are core design inputs.",
  marketNotes: "Norfolk's economy supports Naval Station Norfolk and defense, the Port of Virginia, shipbuilding, healthcare, higher education, logistics, and downtown/waterfront redevelopment. Sea-level-rise adaptation and limited developable land make resilient infill and utility coordination especially important.",
  narratives: {
    mep: "Norfolk MEP design balances 4A heating and cooling with tidal flood, salt air, and mission-critical port and defense loads. We coordinate Dominion service, protected/elevated electrical equipment, Norfolk water/sewer, humidity control, and emergency power while respecting waterfront or security constraints. Energy documentation must track the Virginia code edition through local review.",
    structural: "Norfolk structural design combines coastal wind, flood, corrosion, and soft/filled soils with modest seismic and snow demands. Geotechnical data may lead to piles, ground improvement, or settlement mitigation; FEMA and local freeboard set the datum. Durable connections, flood-resistant materials, and continuous wind load paths are essential for waterfront and port-adjacent work.",
    civil: "Norfolk civil work addresses flat grades, tidal tailwater, high groundwater, Chesapeake Bay protections, and intense rainfall. City stormwater, Virginia erosion and sediment control, floodplain, coastal, and utility requirements govern BMPs, outfalls, finished floors, and access. Early regional and Norfolk utility coordination prevents water and drainage conflicts.",
    energy: "The 2021 Virginia Energy Conservation Code applies to commercial buildings. In 4A, efficient heat pumps or other right-sized systems, humidity control, air sealing, solar control, heat recovery, and lighting controls must be balanced with flood-resilient equipment placement. Dominion service demand and standby loads should be represented in the compliance model.",
  },
  faqs: [
    { q: "Which energy code applies in Norfolk?", a: "Norfolk uses Virginia's 2021 Energy Conservation Code, based on the 2021 IECC, subject to the applicable state transition and local review requirements. Confirm the governing edition at submittal." },
    { q: "What makes Norfolk site design different from inland Virginia?", a: "Tidal flooding, storm surge, sea-level-rise exposure, high groundwater, salt air, soft fills, and Chesapeake Bay stormwater protections affect elevation, foundations, drainage, materials, and utilities. FEMA and City flood criteria are parcel-specific." },
    { q: "Who supplies Norfolk commercial utilities?", a: "Dominion Energy Virginia supplies electricity, and the City of Norfolk Department of Utilities supplies water and sewer. Confirm service capacity, fire flow, transformer needs, elevation, and extension requirements early." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 85, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.norfolk.gov/469/Permits-Inspections"], codes: ["https://www.dhcd.virginia.gov/virginia-uniform-statewide-building-code"], amendments: ["https://www.norfolk.gov/469/Permits-Inspections"], utilities: ["https://www.dominionenergy.com/virginia/business", "https://www.norfolk.gov/1037/Utilities"], climate: ["https://www.weather.gov/akq/"], market: ["https://www.portsmouthvirginia.com/"] } },
};