import type { CityData } from "../types";
export const norman: CityData = {
  slug: "norman", name: "Norman", stateSlug: "oklahoma", county: "Cleveland County",
  ahj: { office: "City of Norman Development Services—Building Permits and Inspections", process: "Norman routes commercial applications through Development Services for building, fire, zoning, and site review. Electronic or counter submittal requirements and applicable utility or floodplain reviews should be confirmed with the city before design release." },
  codes: { building: "2018 International Building Code with City of Norman amendments", energy: "2018 IECC commercial provisions as adopted by Oklahoma", amendments: "Norman's local amendments and zoning, fire, floodplain, and stormwater rules supplement the IBC. The municipal package should be distinguished from Oklahoma City and state agency requirements." },
  utilities: { electric: "OG&E", notes: "Oklahoma Gas and Electric provides electric service and coordinates commercial upgrades; Norman Utilities provides water and wastewater service." },
  climateNotes: "Norman is IECC climate zone 4A, with hot summers, winter freezes, severe thunderstorms and tornado risk, hail, and expansive soils.",
  marketNotes: "The University of Oklahoma, research, healthcare, education, retail, and I-35 logistics support Norman's commercial market. Campus-adjacent and storm-resilient projects often require careful phasing and utility coordination.",
  narratives: { mep: "Norman MEP work balances zone 4A heating and cooling, tornado-weather continuity, and OG&E service coordination. Mechanical and electrical systems are checked against the city's 2018-based package, with emergency power, sheltering, and freeze protection evaluated by occupancy.", structural: "Norman structural design emphasizes tornado and wind load paths, hail, and expansive soils; seismic forces are comparatively low. The geotechnical report controls foundations and slabs, while roof and equipment anchorage follow the adopted 2018 IBC provisions.", civil: "Norman civil design addresses stormwater, floodplain, erosion, and utility capacity, with site grading designed for intense convective rainfall. Water/wastewater connections and Oklahoma construction-stormwater obligations are coordinated before site release.", energy: "Commercial work follows the adopted 2018 IECC provisions. In 4A, envelope continuity, balanced heating and cooling, efficient equipment, lighting controls, and documented trade-offs matter across the full seasonal load profile." },
  faqs: [
    { q: "Who reviews Norman commercial permits?", a: "The City of Norman Development Services department handles building permits and coordinates applicable fire, zoning, site, floodplain, and utility reviews." },
    { q: "What severe-weather loads matter in Norman?", a: "Severe thunderstorms, tornadoes, hail, and high winds are practical design concerns. A continuous load path, protected equipment, and occupancy-specific emergency provisions should be developed from the adopted code." },
    { q: "Which utilities serve Norman?", a: "OG&E provides electric service, while Norman Utilities provides water and wastewater. Service capacity and connection requirements should be confirmed for the project address." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 68, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.normanok.gov/businesses/builders-contractors"], codes: ["https://www.normanok.gov/businesses/builders-contractors"], amendments: ["https://www.normanok.gov/businesses/builders-contractors"], utilities: ["https://www.oge.com/"], climate: ["https://www.weather.gov/oun/"], market: ["https://www.normanok.gov/"] } }
};