import type { CityData } from "../types";
export const overlandPark: CityData = {
  slug: "overland-park", name: "Overland Park", stateSlug: "kansas", county: "Johnson County",
  ahj: { office: "City of Overland Park Planning and Development Services", process: "Overland Park routes commercial permits and plans through its development-services process, with building, planning, fire, site, and public-works reviews coordinated as applicable. The city adopts and amends model codes through municipal ordinance." },
  codes: { building: "2018 International Building Code, as adopted and amended by Overland Park", energy: "2018 International Energy Conservation Code, as adopted and amended by Overland Park", amendments: "Municipal amendments and Overland Park zoning, site-plan, stormwater, fire, and right-of-way requirements supplement the adopted IBC and IECC." },
  utilities: { electric: "Evergy Kansas Central", notes: "Evergy coordinates electric service and generation interconnection. Johnson County Wastewater and municipal water providers serve the area; verify the parcel's provider, capacity, fire flow, and extensions." },
  climateNotes: "Overland Park is climate zone 4A, mixed-humid, with hot summers, winter freeze-thaw, severe thunderstorms, tornado exposure, and intense rainfall. Rolling terrain and clay soils influence grading, retaining, infiltration, and detention.",
  marketNotes: "Overland Park's market includes corporate offices, healthcare, technology, logistics, retail, and substantial suburban mixed-use development. Greenfield growth and redevelopment both require careful Evergy capacity, traffic, stormwater, and phased site coordination.",
  narratives: {
    mep: "Overland Park MEP work emphasizes 4A cooling, dehumidification, ventilation, and freeze protection during winter events. Evergy service and the applicable Johnson County water/wastewater provider are identified before plant sizing. Locally amended IECC documentation is integrated with office, healthcare, and mixed-use operating schedules.",
    structural: "Overland Park structural design is driven by wind and tornado load paths, moderate snow, frost, severe storms, and expansive or variable clay soils. Rolling sites may require retaining systems and careful foundation elevations. Roof equipment and parapet drift are coordinated with municipal review.",
    civil: "Civil packages coordinate Overland Park site plan, stormwater, grading, fire access, water, sewer, and right-of-way review. Clay soils, rolling terrain, intense rainfall, and limited infiltration can control detention and outlet selection. Johnson County and municipal requirements must be reconciled before final grading.",
    energy: "Overland Park commercial compliance follows its adopted and amended 2018 IECC. In 4A, solar control, efficient cooling, dehumidification, air sealing, and lighting controls are material; Evergy demand and the building's actual occupancy schedule belong in design decisions."
  },
  faqs: [
    { q: "What energy code applies in Overland Park?", a: "Overland Park uses its municipally adopted and amended 2018 IECC for commercial energy compliance, alongside its adopted and amended 2018 IBC." },
    { q: "Which utilities serve Overland Park?", a: "Evergy Kansas Central supplies electric service. Water and wastewater provider boundaries vary by parcel in Johnson County, so capacity and fire flow must be confirmed." },
    { q: "What civil constraints are common?", a: "Rolling grades, clay soils, intense rainfall, stormwater detention, fire access, and municipal or county outlet requirements can materially affect the site plan." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 83, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.opkansas.org/city-services/planning-development/"], codes: ["https://www.opkansas.org/city-services/planning-development/building-codes/"], amendments: ["https://library.municode.com/ks/overland_park/codes/code_of_ordinances"], utilities: ["https://www.evergy.com/","https://www.jcw.org/"], climate: ["https://www.weather.gov/eax/"], market: ["https://www.opchamber.org/"] } }
};