import type { CityData } from "../types";

export const portlandMaine: CityData = {
  slug: "portland", name: "Portland", stateSlug: "maine", county: "Cumberland County",
  ahj: { office: "City of Portland Inspections Division", process: "Commercial applications are submitted through the City's permitting process and coordinated among building, zoning, fire, historic-preservation, and site reviewers as applicable. Larger or environmentally sensitive projects may also require Maine DEP, utility, or regional approvals outside the building permit." },
  codes: { building: "Maine Uniform Building and Energy Code (MUBEC), based on the 2015 IBC, as enforced by Portland", energy: "MUBEC commercial energy provisions based on the adopted IECC / ASHRAE 90.1 path", amendments: "Portland zoning, historic-district, site-plan, stormwater, shoreland, and local land-use requirements supplement MUBEC. Downtown and waterfront work may require historic and flood review in addition to building review." },
  utilities: { electric: "Central Maine Power", notes: "Central Maine Power coordinates commercial service, transformer capacity, and distributed-generation interconnection. Portland Water District supplies water and wastewater service; fire flow, capacity, and public-utility extensions should be confirmed for the parcel." },
  climateNotes: "Portland is a cold 6A coastal climate with long heating seasons, heavy snow, nor'easters, salt air, deep frost, and occasional coastal flooding. Marine clay, fill, groundwater, and freeze-thaw make geotechnical and enclosure detailing important.",
  marketNotes: "Portland anchors Maine's healthcare, life-sciences, education, food, marine, hospitality, and multifamily markets. Downtown adaptive reuse, waterfront redevelopment, and limited land keep existing-building, utility, stormwater, and historic-review coordination central to project feasibility.",
  narratives: {
    mep: "Portland MEP design is heating-dominated, with freeze protection and moisture control carrying more weight than peak cooling. We coordinate cold-climate heat pumps or hydronic systems, heat recovery, CMP service capacity, Portland Water District connections, and salt-air protection for coastal equipment. MUBEC compliance and Portland's historic or site-plan reviews should be developed together so vents, rooftop equipment, and penetrations remain approvable.",
    structural: "Portland structural work must handle substantial snow, coastal wind, deep frost, and variable fill or marine clay. Roof drift, rain-on-snow, corrosion-resistant connections, and frost-depth decisions are recurring concerns; waterfront parcels also require flood-elevation review. Existing brick, mill, and timber buildings need investigation before adaptive reuse or added loads.",
    civil: "Portland civil design combines tight urban parcels with Maine DEP stormwater, shoreland, wetland, and local site-plan requirements. Marine clay, groundwater, winter freeze, and intense rainfall influence infiltration, detention, utility trenches, and outfalls. We coordinate Portland Water District service, fire access, CMP corridors, and erosion control early, particularly on waterfront or redevelopment sites.",
    energy: "Commercial energy compliance follows MUBEC's adopted IECC or ASHRAE 90.1 path, with COMcheck or modeling supporting the permit package. In Zone 6A, continuous insulation, air sealing, thermal-bridge control, heat recovery, and cold-climate heat-pump capacity at design temperature are decisive. Efficiency Maine incentives can support above-code electrification without substituting for the code review.",
  },
  faqs: [
    { q: "Which code does Portland, Maine use for commercial buildings?", a: "Portland enforces Maine's MUBEC framework, currently based on the 2015 IBC, with its commercial energy provisions and adopted IECC/ASHRAE 90.1 paths. City zoning, site, historic, fire, and environmental reviews remain separate." },
    { q: "How does Portland's climate affect engineering?", a: "Heavy snow, long cold winters, deep frost, nor'easters, salt air, freeze-thaw, and coastal flooding affect roofs, foundations, equipment, envelopes, and drainage. Marine clay, fill, and groundwater should be investigated early." },
    { q: "Which utilities serve Portland commercial projects?", a: "Central Maine Power provides electric service and the Portland Water District provides water and wastewater. Service capacity, transformer location, fire flow, and extensions must be confirmed for the specific site." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 82, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.portlandmaine.gov/325/Inspections-Division"], codes: ["https://www.maine.gov/dps/fmo/building-codes"], amendments: ["https://www.portlandmaine.gov/DocumentCenter/Index/"], utilities: ["https://www.cmpco.com/for-your-business", "https://www.pwd.org/"], climate: ["https://www.weather.gov/gyx/"], market: ["https://prosperityme.org/"] } },
};