import type { CityData } from "../types";
export const provo: CityData = {
  slug: "provo", name: "Provo", stateSlug: "utah", county: "Utah County",
  ahj: { office: "City of Provo Community Development, Building Division", process: "Provo accepts commercial permit applications through its online permitting services and coordinates building, planning, fire, and public-works review. Pre-application coordination is appropriate for larger projects; zoning, site-plan, utility, and right-of-way approvals can be separate from the building permit." },
  codes: { building: "2021 Utah State Construction Code (2021 IBC with Utah amendments)", energy: "2021 IECC as adopted in the Utah State Construction Code, with Utah amendments", amendments: "Utah's construction code is statewide, while Provo's zoning, subdivision, hillside, fire, and development standards are local overlays. Confirm the adopted code transition and parcel-specific requirements with Provo before design is locked." },
  utilities: { electric: "Rocky Mountain Power", notes: "Rocky Mountain Power provides electric service and interconnection; Provo City operates municipal water, wastewater, and power-related utility services in its service area. Verify which Provo utility serves the parcel and resolve capacity and meter requirements early." },
  climateNotes: "Provo is a cold semi-arid valley climate (ASHRAE 5B), with cold winters, hot dry summers, strong solar gain, inversion episodes, and Wasatch foothill seismic and slope hazards.",
  marketNotes: "Utah County growth supports technology, education, healthcare, multifamily, industrial, and mixed-use construction. The Wasatch Front's rapid development makes transportation, utility capacity, air-quality episodes, and hillside or drainage constraints material to schedule.",
  narratives: {
    mep: "Provo MEP design responds to 5B heating and hot-summer cooling, strong solar exposure, and winter inversion episodes. We identify the actual Rocky Mountain Power or Provo utility service, model electrification and demand implications, and coordinate water and sewer capacity with the city's plan review. Filtration and ventilation strategies should acknowledge episodic poor valley air quality.",
    structural: "Utah's 2021 IBC framework requires site-specific seismic, snow, wind, and geotechnical design in Provo. Wasatch Front seismic demand, foothill slope conditions, and variable valley soils can govern the lateral and foundation systems; rooftop equipment anchorage and snow drift are coordinated with the building permit and special inspections.",
    civil: "Provo civil design coordinates city development standards, municipal utilities, Rocky Mountain Power corridors, stormwater, hillside constraints, and access. We establish drainage and erosion control before grading, check floodplain and slope data, and confirm whether a parcel's water, sewer, and electric service are city- or utility-provider controlled.",
    energy: "The 2021 Utah commercial energy path is based on the 2021 IECC with state amendments. In Provo's 5B climate, envelope continuity, solar control, efficient heating and cooling, and air-quality-conscious ventilation should be modeled together; service capacity and demand are verified with the actual serving utility.",
  },
  faqs: [
    { q: "Which authority issues Provo commercial permits?", a: "Provo Community Development and its Building Division coordinate commercial permitting, with planning, fire, and public-works reviews as applicable. Site zoning and utility approvals can be separate review tracks." },
    { q: "What energy code applies in Provo?", a: "Utah's statewide construction code includes the 2021 IECC with Utah amendments for commercial work. Verify the current effective edition and Provo site requirements at application." },
    { q: "Why does a Provo geotechnical report matter?", a: "Wasatch Front seismic demand, valley soils, snow, and foothill slope or drainage conditions vary materially by parcel. Those inputs can change foundations, lateral systems, grading, and retaining-wall design." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 81, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.provo.gov/181/Community-Development"], codes: ["https://www.dopl.utah.gov/building-codes/"], amendments: ["https://www.provo.gov/181/Community-Development"], utilities: ["https://www.rockymountainpower.net/working-with-us/business-customers.html", "https://www.provo.org/government/departments/public-works"], climate: ["https://www.weather.gov/wrh/climate?wfo=slc"], market: ["https://business.utah.gov/"] } },
};