import type { CityData } from "../types";
export const rochester: CityData = {
  slug: "rochester", name: "Rochester", stateSlug: "minnesota", county: "Olmsted County",
  ahj: { office: "City of Rochester Building Safety Department", process: "Rochester Building Safety accepts commercial permit applications and coordinates plan review and inspections; zoning, site, fire, stormwater, and public-works approvals may be separate. Minnesota's statewide construction code is administered by the city." },
  codes: { building: "2020 Minnesota Building Code, based on the 2018 IBC, with Minnesota amendments", energy: "2020 Minnesota Energy Code, based on ASHRAE 90.1-2016 / 2018 IECC provisions", amendments: "Rochester administers the statewide Minnesota code; local zoning, stormwater, floodplain, subdivision, and public-infrastructure requirements remain applicable." },
  utilities: { electric: "Rochester Public Utilities (RPU)", notes: "RPU provides electric and water; the city provides sanitary sewer and stormwater services. Confirm service capacity, substation/feeder needs, water pressure, fire flow, and utility extensions early." },
  climateNotes: "Rochester is climate zone 6A, with severe cold, snow, frost, freeze-thaw, and humid summers. Root River watershed drainage, variable glacial soils, and high groundwater in some areas affect foundations and stormwater.",
  marketNotes: "Mayo Clinic and related healthcare, medical research, education, manufacturing, and Destination Medical Center investment drive Rochester construction. Healthcare and campus projects require phasing, resilience, utility redundancy, and occupied-site coordination.",
  narratives: {
    mep: "Rochester MEP design must be winter-resilient in 6A, with robust freeze protection, heat recovery, and summer humidity control. RPU service and city water/fire flow are established early for healthcare and research loads. Minnesota code documentation is integrated with infection-control, phasing, and operational continuity requirements where applicable.",
    structural: "Rochester structures are designed for substantial snow and drift, wind, frost, and cold-weather durability. Root River conditions, glacial soils, and groundwater influence foundations and retaining systems; healthcare additions add vibration and existing-structure coordination. The Minnesota code and local inspections govern the permit basis.",
    civil: "Rochester civil design coordinates city stormwater, grading, erosion control, floodplain, water, and sanitary systems. Root River watershed discharge, snowmelt, frozen soils, and constrained medical-campus utilities can control the feasible layout. Minnesota construction-stormwater permitting applies at qualifying disturbance.",
    energy: "Commercial energy compliance follows the 2020 Minnesota Energy Code. In 6A, airtight envelopes, continuous insulation, heat recovery, efficient heating, and lighting controls are central to both winter performance and compliance. RPU demand and critical-facility redundancy should be included in load decisions."
  },
  faqs: [
    { q: "What code applies to a Rochester commercial building?", a: "The city administers Minnesota's 2020 Building Code, based on the 2018 IBC with Minnesota amendments, and the 2020 Minnesota Energy Code." },
    { q: "Who provides Rochester utilities?", a: "Rochester Public Utilities provides electric and water service; city systems provide sanitary sewer and stormwater. Confirm capacity, pressure, fire flow, and extensions for the parcel." },
    { q: "Why is snowmelt drainage important in Rochester?", a: "Climate zone 6A cold, snow, frost, and freeze-thaw combine with Root River watershed drainage and glacial soils, so elevations, detention, erosion control, and outlets need early review." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 86, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.rochestermn.gov/departments/community-development/building-safety"], codes: ["https://www.dli.mn.gov/business/codes-and-laws/2020-minnesota-building-code"], amendments: ["https://library.municode.com/mn/rochester/codes/code_of_ordinances"], utilities: ["https://www.rpu.org/"], climate: ["https://www.weather.gov/arx/"], market: ["https://www.rochestermn.gov/government/departments/community-development/destination-medical-center"] } }
};