import type { CityData } from "../types";
export const salem: CityData = {
  slug: "salem", name: "Salem", stateSlug: "oregon", county: "Marion County",
  ahj: { office: "City of Salem Community Planning and Development Department, Building and Safety Division", process: "Salem routes commercial building applications through its permit services and coordinates building, planning, fire, and public-works review. Land-use, tree, floodplain, right-of-way, and utility approvals may be separate; confirm the applicable review path before submittal." },
  codes: { building: "2022 Oregon Structural Specialty Code (2021 IBC with Oregon amendments)", energy: "2023 Oregon Energy Efficiency Specialty Code (commercial provisions based on ASHRAE 90.1-2019)", amendments: "Oregon's specialty codes apply statewide and include Oregon amendments; Salem adds land-use, tree, stormwater, and administrative requirements. Do not substitute the base IBC or an older Oregon energy edition for the effective state specialty code." },
  utilities: { electric: "Portland General Electric", notes: "Portland General Electric provides electric service; the City of Salem provides water, sewer, and stormwater services in the city. Confirm PGE service capacity and city connection, frontage, and stormwater requirements early." },
  climateNotes: "Salem is ASHRAE climate zone 4C, marine and wet, with mild heating-dominated winters, dry warm summers, heavy seasonal rain, wildfire smoke, and floodplain exposure along the Willamette.",
  marketNotes: "As Oregon's capital, Salem has state and institutional, healthcare, education, multifamily, food and agriculture, and public-sector construction. Wet-weather site logistics, stormwater, seismic retrofit, and wildfire-smoke resilience are recurring design considerations.",
  narratives: {
    mep: "Salem MEP design prioritizes moisture management and efficient heating in the 4C marine climate while allowing for increasingly useful summer cooling and smoke filtration. We coordinate PGE service with city water and sewer, use the 2023 Oregon energy path from the start, and protect equipment and controls from the region's wet winter conditions.",
    structural: "Salem structural design uses the 2022 OSSC and site-specific seismic, wind, rain, and geotechnical inputs. Cascadia and crustal seismic hazards make lateral design and, on susceptible sites, liquefaction review important; wet soils, floodplain elevation, and corrosion exposure also influence foundations and detailing.",
    civil: "Civil packages in Salem must fit stormwater quality and flow-control requirements, city utility standards, wet-weather grading, trees, access, and possible Willamette floodplain constraints. We coordinate PGE corridors and public-way work early and reserve space for treatment facilities rather than treating drainage as a late permit add-on.",
    energy: "Commercial compliance follows the 2023 Oregon Energy Efficiency Specialty Code, with commercial provisions based on ASHRAE 90.1-2019. In 4C, air sealing, moisture-safe envelope assemblies, heat recovery, efficient heat pumps, and smoke-capable ventilation form a coherent strategy rather than isolated checklist measures.",
  },
  faqs: [
    { q: "Which code edition does Salem use?", a: "The 2022 Oregon Structural Specialty Code is based on the 2021 IBC with Oregon amendments. Commercial energy compliance uses the effective 2023 Oregon Energy Efficiency Specialty Code; confirm transition dates for the permit." },
    { q: "Who provides Salem utilities?", a: "Portland General Electric provides electric service, while the City of Salem provides water, sewer, and stormwater services in the city. Capacity and connection requirements are parcel-specific." },
    { q: "What hazards affect Salem structural and civil work?", a: "Cascadia and local seismic hazards, wet soils, seasonal flooding, heavy rain, and wildfire smoke are important inputs. Geotechnical, floodplain, and stormwater reviews should be started with the concept site plan." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 76, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.cityofsalem.net/government/shaping-salem-s-future/planning/building-permits"], codes: ["https://www.oregon.gov/bcd/codes-stand/Pages/adopted-codes.aspx"], amendments: ["https://www.cityofsalem.net/government/shaping-salem-s-future/planning"], utilities: ["https://portlandgeneral.com/business"], climate: ["https://www.weather.gov/wrh/climate?wfo=pqr"], market: ["https://www.oregon.gov/biz/Pages/default.aspx"] } },
};