import type { CityData } from "../types";
export const southBend: CityData = {
  slug: "south-bend", name: "South Bend", stateSlug: "indiana", county: "St. Joseph County",
  ahj: { office: "City of South Bend Department of Community Investment, Building Department", process: "South Bend's building department handles local permits and inspections; many commercial projects also require an Indiana Construction Design Release through state plan review. Zoning, fire, drainage, and right-of-way approvals are separate tracks." },
  codes: { building: "Indiana Building Code (675 IAC 13), based on the 2012 IBC with Indiana amendments", energy: "Indiana Energy Conservation Code, using adopted ASHRAE 90.1/IECC provisions with Indiana amendments", amendments: "Indiana's commercial code is statewide rather than a city-selected IBC edition; local zoning, floodplain, utility, and site requirements still apply." },
  utilities: { electric: "Indiana Michigan Power (AEP)", notes: "Indiana Michigan Power coordinates service and generation interconnection. The City of South Bend Department of Public Works provides water and sewer; establish capacity, fire flow, and connection details early." },
  climateNotes: "South Bend is climate zone 5A with heavy lake-effect snow potential, cold winters, humid summers, and freeze-thaw. St. Joseph River floodplain, glacial soils, and high groundwater can control foundations and drainage.",
  marketNotes: "South Bend's market includes University of Notre Dame, healthcare, advanced manufacturing, logistics, and downtown redevelopment. Adaptive reuse and industrial projects frequently require existing-utility, floodplain, and state/local review coordination.",
  narratives: {
    mep: "South Bend MEP systems need winter heating, snow-season freeze protection, and summer latent control. Indiana Michigan Power service and City water/fire flow are resolved early for manufacturing, institutional, and redevelopment loads. State energy documentation and local permit submissions are kept consistent across both review tracks.",
    structural: "Lake-effect snow, roof drift, wind, frost, and variable glacial or fill soils are primary South Bend structural inputs. River-adjacent groundwater and older industrial buildings require geotechnical and existing-condition investigation. Indiana's statewide code and state release establish the technical review baseline.",
    civil: "Civil design begins with South Bend drainage, floodplain, water, sewer, and right-of-way constraints. St. Joseph River conditions, high groundwater, clay/till soils, and winter construction affect grading and stormwater outlets. Indiana construction-stormwater permitting applies to qualifying disturbance.",
    energy: "South Bend commercial energy compliance follows Indiana's adopted energy code and amendments, not a city-specific code cycle. In 5A, snow-season heating, envelope air control, efficient lighting, and humidity management are important; utility demand and process loads should inform the compliance design."
  },
  faqs: [
    { q: "Is state approval needed in addition to a South Bend permit?", a: "Many commercial projects need an Indiana Construction Design Release through state plan review in addition to the local South Bend permit and separate zoning, fire, drainage, and right-of-way approvals." },
    { q: "Who supplies utilities in South Bend?", a: "Indiana Michigan Power provides electric service, while the City provides water and sewer. Capacity, fire flow, and extensions are parcel-specific." },
    { q: "What affects South Bend civil design?", a: "Lake-effect snow, freeze-thaw, St. Joseph River floodplain and drainage, glacial soils, and high groundwater can affect elevations, foundations, detention, and the lawful stormwater outlet." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 76, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://southbendin.gov/government/departments/community-investment/building/"], codes: ["https://www.in.gov/dhs/fire-and-building-safety/code-enforcement/indiana-building-codes/"], amendments: ["https://codelibrary.amlegal.com/codes/southbend/latest/overview"], utilities: ["https://www.indianamichiganpower.com/","https://southbendin.gov/government/departments/public-works/"], climate: ["https://www.weather.gov/iwx/"], market: ["https://www.greaterstjoseph.com/"] } }
};