import type { CityData } from "../types";
export const springfield: CityData = {
  slug: "springfield", name: "Springfield", stateSlug: "missouri", county: "Greene County",
  ahj: { office: "City of Springfield Building Development Services", process: "Springfield Building Development Services accepts commercial permits and coordinates building plan review and inspections; zoning, fire, site, stormwater, and utility reviews may be distinct. The city administers Missouri's adopted commercial code framework." },
  codes: { building: "2018 International Building Code, as adopted by the City of Springfield with local amendments", energy: "2018 International Energy Conservation Code, as adopted by Springfield", amendments: "Springfield's adopted ordinances amend the IBC and IECC; local zoning, fire, stormwater, tree, and public-infrastructure requirements also affect design." },
  utilities: { electric: "City Utilities of Springfield (electric, water, and sewer)", notes: "City Utilities handles electric, water, and sewer service and coordinates new connections and distributed generation. Confirm system capacity, fire flow, sewer availability, and stormwater discharge early." },
  climateNotes: "Springfield is climate zone 4A, mixed-humid, with hot humid summers, winter freeze-thaw, severe thunderstorms, and occasional tornado risk. Karst-prone Ozark geology and variable soils make subsurface and drainage investigation important.",
  marketNotes: "Springfield is a regional hub for healthcare, education, distribution, manufacturing, and food production. Healthcare and logistics growth creates demand for resilient MEP, utility-capacity planning, and greenfield civil work.",
  narratives: {
    mep: "Springfield MEP systems balance 4A cooling and dehumidification with winter freeze protection. City Utilities capacity, water pressure, fire flow, and sewer routing are early design constraints for healthcare, food, and distribution projects. Springfield's locally adopted IECC path is coordinated with actual operating loads.",
    structural: "Springfield structural design must address wind and severe-storm load paths, roof equipment, moderate snow, frost, and variable Ozark soils. Karst or subsurface void conditions cannot be assumed away; geotechnical investigation informs foundations and slabs. Existing downtown and healthcare work adds phasing requirements.",
    civil: "Springfield civil design coordinates local stormwater, grading, water, sewer, floodplain, and construction access requirements. Ozark karst, sinkhole potential, variable soils, intense rainfall, and limited infiltration can affect detention and outlet design. Early utility and geotechnical work protects the site plan.",
    energy: "Springfield commercial energy compliance follows the locally adopted 2018 IECC with amendments. In 4A, envelope solar control, efficient cooling, dehumidification, air sealing, and lighting controls matter; City Utilities demand and water/sewer capacity should be checked alongside the energy model."
  },
  faqs: [
    { q: "Which codes does Springfield use?", a: "Springfield has locally adopted the 2018 IBC and 2018 IECC with city amendments; zoning, fire, stormwater, and utility requirements are additional review considerations." },
    { q: "Who serves Springfield utilities?", a: "City Utilities of Springfield provides electric, water, and sewer service. New loads and connections require parcel-specific capacity and routing confirmation." },
    { q: "Why investigate Springfield sites early?", a: "Mixed-humid rainfall, severe storms, variable Ozark soils, and potential karst conditions can affect drainage, foundations, finished grades, and utility corridors." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 76, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.springfieldmo.gov/413/Building-Development-Services"], codes: ["https://www.springfieldmo.gov/DocumentCenterView/"], amendments: ["https://library.municode.com/mo/springfield/codes/code_of_ordinances"], utilities: ["https://www.cityutilities.net/"], climate: ["https://www.weather.gov/sgf/"], market: ["https://www.springfieldregion.com/"] } }
};