import type { CityData } from "../types";
export const tacoma: CityData = {
  slug: "tacoma", name: "Tacoma", stateSlug: "washington", county: "Pierce County",
  ahj: { office: "City of Tacoma Planning and Development Services", process: "Tacoma accepts commercial permit applications through its online permit system and coordinates building, land-use, fire, and public-works reviews. Larger projects may benefit from pre-application coordination; shoreline, critical-area, right-of-way, and utility approvals can be separate from the building permit." },
  codes: { building: "2021 Washington State Building Code (2021 IBC with Washington amendments)", energy: "2021 Washington State Energy Code, Commercial (WSEC-C)", amendments: "Tacoma administers the statewide Washington codes with local land-use, shoreline, critical-area, stormwater, fire, and administrative requirements. Confirm Tacoma amendments and the parcel's shoreline or critical-area status at intake." },
  utilities: { electric: "Tacoma Power", notes: "Tacoma Power provides municipal electric service and handles service and distributed-generation coordination; Tacoma Water and Environmental Services handle water, sewer, and stormwater. Early load, transformer, and connection discussions are important for industrial and multifamily projects." },
  climateNotes: "Tacoma is ASHRAE climate zone 4C, marine and wet, with cool wet winters, mild summers, seismic and liquefaction exposure, and coastal, river, and landslide hazards.",
  marketNotes: "Tacoma's market includes port and industrial logistics, healthcare, education, multifamily, adaptive reuse, and waterfront redevelopment. Port-adjacent soils, dense utility corridors, shoreline rules, and seismic resilience distinguish projects from inland Puget Sound work.",
  narratives: {
    mep: "Tacoma MEP design pairs 4C moisture control and heating with occasional summer cooling and wildfire-smoke filtration. Tacoma Power's municipal service and Tacoma Water and Environmental Services coordination belong in early load and site planning, while the 2021 WSEC-C model drives envelope, HVAC, lighting, and controls decisions before permit review.",
    structural: "Tacoma structural design uses the 2021 Washington code and must account for Cascadia and local seismic hazards, liquefaction in filled or waterfront soils, wind, rain, and site-specific foundations. Port and shoreline parcels often need intensive geotechnical and corrosion review, with special inspections coordinated through Tacoma's permit process.",
    civil: "Tacoma civil work is shaped by city stormwater standards, shoreline and critical-area rules, steep slopes, port fill, and constrained utility corridors. We coordinate Tacoma Water, Environmental Services, Tacoma Power, and right-of-way requirements early and test flood, drainage, and erosion assumptions before site layout is committed.",
    energy: "The 2021 Washington State Energy Code—Commercial governs Tacoma. In wet 4C conditions, heat recovery, airtight moisture-safe envelopes, efficient heat pumps, and controls matter; Tacoma Power's municipal grid and service constraints should be integrated into the electrical and energy compliance strategy.",
  },
  faqs: [
    { q: "Does Tacoma use Seattle's energy code?", a: "No. Tacoma administers the statewide 2021 Washington State Energy Code—Commercial, while Seattle has a separate city energy code. Tacoma still has local land-use, stormwater, shoreline, and critical-area requirements." },
    { q: "What utility coordination is needed?", a: "Tacoma Power handles electric service and interconnection, while Tacoma Water and Environmental Services cover water, sewer, and stormwater. Confirm capacity and connection requirements for the actual parcel." },
    { q: "Why are Tacoma waterfront sites complex?", a: "Filled and soft soils can amplify seismic and liquefaction concerns, while shoreline, flood, stormwater, corrosion, and right-of-way reviews add constraints. Geotechnical and civil work should begin before architectural layout is final." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 84, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.cityoftacoma.org/government/city_departments/planning_and_development_services"], codes: ["https://sbcc.wa.gov/state-codes-regulations-guidelines"], amendments: ["https://www.cityoftacoma.org/government/city_departments/planning_and_development_services"], utilities: ["https://www.mytpu.org/business/"], climate: ["https://www.weather.gov/wrh/climate?wfo=sew"], market: ["https://www.portoftacoma.com/"] } },
};