import type { CityData } from "../types";
export const waco: CityData = {
  slug: "waco", name: "Waco", stateSlug: "texas", county: "McLennan County",
  ahj: { office: "City of Waco Development Services—Building Inspections", process: "Waco receives commercial permit and plan-review materials through its development-services process. Building, fire, zoning, engineering, and utility reviews apply according to scope, with site and drainage approvals coordinated for new development." },
  codes: { building: "2021 International Building Code with City of Waco amendments", energy: "2021 IECC commercial provisions (Texas SECO baseline)", amendments: "Waco's municipal amendments and development standards supplement the IBC with local fire, zoning, floodplain, drainage, and administrative requirements." },
  utilities: { electric: "Oncor Electric Delivery", notes: "Oncor handles regulated electric delivery and upgrades in ERCOT; Waco provides water and wastewater through the City of Waco Water Utilities system." },
  climateNotes: "Waco is climate zone 3A with hot summers, severe thunderstorm and hail exposure, occasional freezes, expansive soils, and Trinity/Brazos watershed flood considerations.",
  marketNotes: "Waco's market includes logistics and manufacturing along I-35, healthcare and education, downtown redevelopment, hospitality, and industrial expansion. Highway-oriented sites commonly require careful access, drainage, and utility-capacity coordination.",
  narratives: { mep: "Waco MEP systems are sized for long zone 3A cooling seasons and coordinated with Oncor and municipal water capacity. Freeze protection, hail exposure, and local fire and trade amendments matter alongside ordinary HVAC, electrical, and plumbing calculations.", structural: "Waco foundations must account for expansive soils identified by geotechnical investigation. Seismic demand is modest; wind, hail, roof uplift, and durable rooftop-equipment anchorage are more typical design drivers under Waco's 2021-based code.", civil: "Waco civil work connects grading and detention to floodplain and watershed constraints, especially near the Brazos and Bosque systems. Water/wastewater availability, roadway access, erosion controls, and TCEQ stormwater coverage are coordinated with the city.", energy: "The 2021 IECC commercial baseline supports COMcheck or an allowed ASHRAE 90.1 path. In zone 3A, solar control, infiltration control, efficient cooling, and lighting controls should be evaluated together." },
  faqs: [
    { q: "Who is Waco's commercial permitting AHJ?", a: "City of Waco Development Services—Building Inspections handles building permits and coordinates applicable fire, zoning, engineering, floodplain, and utility reviews." },
    { q: "What utility serves commercial electricity in Waco?", a: "Oncor Electric Delivery provides regulated delivery service and handles meters and upgrades; the city provides water and wastewater utilities." },
    { q: "Are expansive soils a Waco design concern?", a: "Yes. Geotechnical testing should establish shrink-swell behavior and guide foundation, slab, pavement, drainage, and moisture-control design." }
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering","structural-engineering","civil-engineering","energy-code-compliance"], priority: { commercialOpportunity: 70, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.waco-texas.com/Departments/Development-Services"], codes: ["https://www.waco-texas.com/Departments/Development-Services"], amendments: ["https://www.waco-texas.com/Departments/Development-Services"], utilities: ["https://www.oncor.com/"], climate: ["https://www.weather.gov/fwd/"], market: ["https://wacochamber.com/"] } }
};