import type { CityData } from "../types";
export const wilmington: CityData = {
  slug: "wilmington", name: "Wilmington", stateSlug: "north-carolina", county: "New Hanover County",
  ahj: { office: "City of Wilmington Development Services / New Hanover County inspections", process: "Commercial building permits are submitted through the area's electronic permitting process and coordinated with New Hanover County inspections. City site, zoning, floodplain, stormwater, fire, and utility reviews can be separate, and coastal projects should confirm elevation and flood-zone requirements before submittal." },
  codes: { building: "North Carolina State Building Code, state-amended and enforced locally by New Hanover County", energy: "North Carolina Energy Conservation Code, state-amended and IECC-derived", amendments: "North Carolina's statewide code supplies the technical baseline; Wilmington's land-development, tree, flood-damage-prevention, stormwater, and coastal site rules add local requirements. Coastal AEC and wind provisions become especially important near the Cape Fear River and Atlantic." },
  utilities: { electric: "Duke Energy Progress", notes: "Duke coordinates commercial service, demand, transformer, and distributed-generation needs. Cape Fear Public Utility Authority provides water and sewer in the Wilmington area; capacity, fire flow, and extension requirements are site-specific." },
  climateNotes: "Wilmington is humid coastal climate zone 3A, with long cooling seasons, hurricanes, storm surge, intense rain, salt air, and occasional freezes. Coastal flood elevation, corrosion resistance, and moisture management should be established early.",
  marketNotes: "Growth spans port and logistics activity, healthcare, university-related work, film production, hospitality, multifamily, and residential-to-commercial redevelopment. Coastal land and floodplain constraints make resilient infill, drainage, and utility coordination central to feasibility.",
  narratives: {
    mep: "Wilmington MEP design addresses humid 3A loads, salt exposure, hurricane outages, and coastal flood conditions. We coordinate dehumidification, corrosion-resistant equipment, protected electrical distribution, Duke service capacity, and Cape Fear Public Utility Authority water and sewer before selecting plant rooms or service entrances. The state energy-code package must align with the local electronic review path.",
    structural: "Wilmington structural design is dominated by coastal wind and flood rather than seismic or snow. Windborne debris, roof uplift, continuous load paths, corrosion detailing, and FEMA elevation/freeboard affect the frame and enclosure; sandy or fill soils and high groundwater may favor deep foundations or ground improvement. The geotechnical report and current North Carolina code establish the final basis.",
    civil: "Coastal rainfall, flat grades, tidal tailwater, and high groundwater govern Wilmington drainage. City and county stormwater, flood-damage-prevention, NCDEQ erosion control, coastal rules, and Cape Fear utility standards can change grading, BMPs, outfalls, and finished floor. We resolve flood and utility availability before committing the site plan.",
    energy: "The state-amended North Carolina Energy Conservation Code applies to commercial work. In humid 3A, solar control, airtightness, efficient cooling, dedicated dehumidification, lighting controls, and resilient electrical loads matter more than heating-only strategies. Duke demand characteristics and coastal corrosion are coordinated with the envelope and mechanical compliance model.",
  },
  faqs: [
    { q: "Which authority reviews Wilmington commercial building permits?", a: "The City and New Hanover County coordinate commercial development and inspections, with county enforcement of the statewide building code and separate city or county site, zoning, stormwater, flood, and fire tracks. Confirm the parcel's assigned review path before submission." },
    { q: "What climate risks affect Wilmington design?", a: "Atlantic hurricane wind, storm surge, coastal flooding, intense rainfall, salt air, and high groundwater all affect enclosure, structure, grading, equipment elevation, and corrosion protection. FEMA and local flood requirements are parcel-specific." },
    { q: "Who provides utilities in Wilmington?", a: "Duke Energy Progress is the electric utility, and Cape Fear Public Utility Authority provides water and sewer in its service area. Commercial capacity, fire flow, service extensions, transformer needs, and connection timing must be confirmed for the site." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 83, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.wilmingtonnc.gov/departments/development-services"], codes: ["https://www.ncosfm.gov/codes"], amendments: ["https://www.wilmingtonnc.gov/departments/development-services"], utilities: ["https://www.duke-energy.com/business", "https://www.cfpua.org/"], climate: ["https://www.weather.gov/ilm/"], market: ["https://wilmingtonbusinessdevelopment.com/"] } },
};