import type { CityData } from "../types";
export const worcester: CityData = {
  slug: "worcester", name: "Worcester", stateSlug: "massachusetts", county: "Worcester County",
  ahj: { office: "City of Worcester Division of Inspectional Services", process: "Worcester accepts commercial permit applications through its online permitting services and routes them through building, zoning, fire, and other reviews as applicable. Historic, wetlands, public-way, and utility approvals can be separate, and larger projects should confirm the required review sequence with Inspectional Services." },
  codes: { building: "10th edition Massachusetts State Building Code (780 CMR), incorporating the 2021 I-Codes with Massachusetts amendments", energy: "10th edition 780 CMR energy provisions, incorporating the 2021 IECC with Massachusetts amendments; Worcester is a Specialized Energy Code community", amendments: "Worcester enforces the statewide 10th-edition code and its existing-building provisions, with local zoning, historic, wetlands, stormwater, and administrative overlays. Its Specialized Energy Code status is separate from the base building-code adoption and affects commercial energy design." },
  utilities: { electric: "National Grid", notes: "National Grid supplies electricity and natural gas in Worcester; the City of Worcester Department of Public Works provides water and sewer service. Confirm electric capacity, gas service, and municipal connection and street-opening requirements early for redevelopment and laboratory or industrial loads." },
  climateNotes: "Worcester is ASHRAE climate zone 5A, cool-humid and higher-elevation than coastal Massachusetts, with cold snowy winters, humid summers, freeze-thaw, and inland flood and stormwater exposure.",
  marketNotes: "Worcester's market includes healthcare, higher education, biotechnology, advanced manufacturing, multifamily, and downtown adaptive reuse. Older mill and masonry buildings, constrained urban utilities, and institutional expansion make existing-condition and phasing expertise valuable.",
  narratives: {
    mep: "Worcester MEP design handles 5A heating, snow and freeze protection, humid-summer ventilation, and the constraints of older mills and institutional buildings. We coordinate National Grid service with city water and sewer, model the Specialized Energy Code path from schematic design, and plan phasing where occupied healthcare, education, or lab facilities cannot be shut down.",
    structural: "Structural work in Worcester uses 780 CMR and site-specific snow, wind, frost, seismic, and geotechnical inputs. Existing brick, timber, and steel mills require investigation before new lab exhaust, rooftop equipment, or change-of-use loads are introduced; excavation beside neighboring foundations and special inspections need early planning.",
    civil: "Worcester civil design coordinates city water and sewer, National Grid corridors, steep or constrained urban sites, stormwater, wetlands, flood mapping, and public-way work. We resolve grading, snow storage, access, and utility connections early because redevelopment parcels often have little spare area for late drainage changes.",
    energy: "Worcester's 10th-edition Massachusetts code includes the Specialized Energy Code path, so commercial compliance is more than a generic 2021 IECC exercise. In cold-humid 5A, airtight insulation, thermal-bridge control, efficient heating, heat recovery, and moisture-safe retrofit details need to be checked against National Grid service and the building's future operational-emissions strategy.",
  },
  faqs: [
    { q: "What code does Worcester use for commercial permits?", a: "Worcester enforces the 10th edition Massachusetts State Building Code, 780 CMR, incorporating the 2021 I-Codes with Massachusetts amendments. The city is also a Specialized Energy Code community, which affects energy compliance beyond the base code." },
    { q: "Which utilities serve Worcester?", a: "National Grid supplies electricity and natural gas, while the City of Worcester provides water and sewer service. Capacity, service extensions, and street-opening requirements should be verified for the actual project address." },
    { q: "Why is existing-building investigation important?", a: "Worcester's mills, masonry buildings, institutional campuses, and dense redevelopment parcels can conceal structural and utility conditions. Field verification, excavation coordination, and phasing are often as important as the new system design." },
  ],
  research: { lastVerified: "2026-09-11", reviewStatus: "approved", reviewedBy: "Apex Grid evidence review", supportedServiceSlugs: ["mep-engineering", "structural-engineering", "civil-engineering", "energy-code-compliance"], priority: { commercialOpportunity: 83, searchConsoleImpressions: 0, searchConsolePeriod: "unavailable" }, sources: { ahj: ["https://www.worcesterma.gov/inspectional-services"], codes: ["https://www.mass.gov/info-details/building-code"], amendments: ["https://www.worcesterma.gov/planning-regulatory"], utilities: ["https://www.nationalgridus.com/business"], climate: ["https://www.weather.gov/box/climate"], market: ["https://www.mass.gov/orgs/massachusetts-life-sciences-center"] } },
};